### PR TITLE
checker: fix `&` on pointers

### PR DESCRIPTION
**Pull request by spaceface777**

### CODE REVIEW

**Comment by medvednikov** [comment]
Can you add a small test for the bug this PR fixes?

**Comment by spytheman** [comment]
after this PR this program works:
```v
struct Context { x int = 123 }
fn no_newlines(s string) string { return s.replace('\n', ' ') }
fn print_contexts(x &Context, y &Context) {
    println('ctx_base ptr: ${ptr_str(x)}, ctx_base content: ' + no_newlines('$x'))
    println('     ctx ptr: ${ptr_str(y)},      ctx content: ' + no_newlines('$y'))
}

fn main() {
    ctx_base := &Context{456}
    mut ctx := &Context{789}
    print_contexts(ctx_base, ctx)
    assert ctx_base.x == 456
    assert ptr_str(ctx_base) != ptr_str(ctx)
    unsafe {
        x := &ctx_base
        *x = ctx
        // now ctx_base should point to the same structure, to which ctx points too
    }
    assert ctx_base.x == 789
    assert ptr_str(ctx_base) == ptr_str(ctx)
    print_contexts(ctx_base, ctx)
}
```
It prints:
```
ctx_base ptr: 629430, ctx_base content: &Context{     x: 456 }
     ctx ptr: 629450,      ctx content: &Context{     x: 789 }
ctx_base ptr: 629450, ctx_base content: &Context{     x: 789 }
     ctx ptr: 629450,      ctx content: &Context{     x: 789 }
```

Before this PR, it segfaulted after the `unsafe{}` block.

**Comment by spaceface777** [comment]
@spytheman that works too, the test I added is *a little* more basic :)

**Comment by spytheman** [comment]
Yours is better.

**Pull request merged**
