### PR TITLE
parser: cleanup `dot_expr()`

### PR DESCRIPTION
**Pull request by zakuro9715**
Just extract code into `dot_expr_method_call()` from `dot_expr()`

### CODE REVIEW

**Comment by medvednikov** [comment]
parser.v conflict

**Comment by zakuro9715** [comment]
fixed

**Comment by medvednikov** [comment]
Unlike your other PR which removed duplicate code by extracting common code in a function, this one doesn't do it.

` p.dot_expr_method_call(left, field_name, name_pos, concrete_types, concrete_list_pos)`

This method has too many params, this call is not really readable.

I'd leave it the way it was.

**Comment by zakuro9715** [comment]
Ah, I wrote this because I thought `dot_expr()` was too big, but this may not be as good as it seems. Better to move it to `call_expr()`, as noted in the comments.

**Pull request closed without merging**
