### PR TITLE
checker: implement smartcast if multi conds (part 2)

### LINKED ISSUE #10380: type check & casting / error: field `XX` does not exist or have the same type in all sumtype variants
OS: macos, macOS, 11.4, 20F71
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.9)

getwd: /Users/ah/SVN-Checkouts/TST/vlang-test
vmodules: /Users/ah/.vmodules
vroot: /usr/local/Cellar/vlang/0.2.2/libexec
vexe: /usr/local/Cellar/vlang/0.2.2/libexec/v
vexe mtime: 2021-06-06 21:30:18
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 f4486d7.114c382

Git version: git version 2.32.0
Git vroot status: weekly.2021.22-52-g114c382c (8 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 689c8a02

**What did you do?**

nested type check to access sum type variables

**What did you expect to see?**

no error 

**What did you see instead?**

```
v run types-match2.v
types-match2.v:26:36: error: field `source_line` does not exist or have the same type in all sumtype variants
   24 | fn ok(mapping_a Mapping, mapping_b Mapping) bool {
   25 |     if mapping_a.source_position is SourcePosition && mapping_b.source_position is SourcePosition {
   26 |         return mapping_a.source_position.source_line != mapping_b.source_position.source_line
      |                                          ~~~~~~~~~~~
   27 |                 || mapping_a.source_position.source_column != mapping_b.source_position.source_column
   28 |     }
types-match2.v:27:34: error: field `source_column` does not exist or have the same type in all sumtype variants
   25 |     if mapping_a.source_position is SourcePosition && mapping_b.source_position is SourcePosition {
   26 |         return mapping_a.source_position.source_line != mapping_b.source_position.source_line
   27 |                 || mapping_a.source_position.source_column != mapping_b.source_position.source_column
      |                                              ~~~~~~~~~~~~~
   28 |     }
   29 |     return false
```

`types-match2.v`:
```v

struct Empty {}

struct SourcePosition {
	source_line   u32
	source_column u32
}

type SourcePositionType = Empty | SourcePosition
type NameIndexType = Empty | u32

struct GenPosition {
	gen_line   u32
	gen_column u32
}

struct Mapping {
	GenPosition
	sources_ind     u32
	names_ind       NameIndexType
	source_position SourcePositionType
}

fn ok(mapping_a Mapping, mapping_b Mapping) bool {
	if mapping_a.source_position is SourcePosition && mapping_b.source_position is SourcePosition {
		return mapping_a.source_position.source_line != mapping_b.source_position.source_line
				|| mapping_a.source_position.source_column != mapping_b.source_position.source_column
	}
	return false
}


```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR implement if smartcast multi cond (fix #10380) part 2.

Sorry, This two-step submission is still failed. It can only be modified all at once and cannot rebuild from v.c, so I don't know how to resolve it. @medvednikov  I wonder if there is a good way?

- Implement if smartcast multi cond.
- Modify all the related called.
- Add test.

```vlang
struct Empty {}

struct SourcePosition {
	source_line   u32
	source_column u32
}

type SourcePositionType = Empty | SourcePosition
type NameIndexType = Empty | u32

struct GenPosition {
	gen_line   u32
	gen_column u32
}

struct Mapping {
	GenPosition
	sources_ind     u32
	names_ind       NameIndexType
	source_position SourcePositionType
}

fn ok(mapping_a Mapping, mapping_b Mapping) bool {
	if mapping_a.source_position is SourcePosition && mapping_b.source_position is SourcePosition {
		return mapping_a.source_position.source_line != mapping_b.source_position.source_line
			|| mapping_a.source_position.source_column != mapping_b.source_position.source_column
	}
	return false
}

fn main() {
	a := Mapping{
		source_position: SourcePosition{
			source_line: 11
			source_column: 22
		}
	}
	b := Mapping{
		source_position: SourcePosition{
			source_line: 22
			source_column: 11
		}
	}
	ret := ok(a, b)
	println(ret)
	assert ret
}

PS D:\Test\v\tt1> v run .
true
```

### CODE REVIEW

**Comment by SleepyRoy** [comment]
CI says bootstrap failed. Did you try bootstrapping locally?
```
./v -o v2.exe -cc clang cmd/v
vlib/v/gen/js/sourcemap/mappings.v:153:32: error: field `source_line` does not exist or have the same type in all sumtype variants
  151 |     if mapping_a.source_position.type_name() == mapping_b.source_position.type_name()
  152 |         && mapping_b.source_position is SourcePosition {
  153 |         if mapping_a.source_position.source_line != mapping_b.source_position.source_line
      |                                      ~~~~~~~~~~~
  154 |             || mapping_a.source_position.source_column != mapping_b.source_position.source_column {
  155 |             return true
vlib/v/gen/js/sourcemap/mappings.v:154:33: error: field `source_column` does not exist or have the same type in all sumtype variants
  152 |         && mapping_b.source_position is SourcePosition {
  153 |         if mapping_a.source_position.source_line != mapping_b.source_position.source_line
  154 |             || mapping_a.source_position.source_column != mapping_b.source_position.source_column {
      |                                          ~~~~~~~~~~~~~
  155 |             return true
  156 |         }
vlib/v/parser/sql.v:37:15: error: field `name` does not exist or have the same type in all sumtype variants
   35 |             e := where_expr as ast.InfixExpr
   36 |             if e.op == .eq && e.left is ast.Ident {
   37 |                 if e.left.name == 'id' {
      |                           ~~~~
   38 |                     query_one = true
   39 |                 }
vlib/v/gen/c/comptime.v:328:46: error: field `typ` does not exist or have the same type in all sumtype variants
  326 |                         if interface_sym.info is ast.Interface {
  327 |                             // q := g.table.get_type_symbol(interface_sym.info.types[0])
  328 |                             checked_type := g.unwrap_generic(left.typ)
      |                                                                   ~~~
  329 |                             // TODO PERF this check is run twice (also in the checker)
  330 |                             // store the result in a field
vlib/v/gen/js/js.v:853:19: error: field `val` does not exist or have the same type in all sumtype variants
  851 |         g.write('$field.name: ')
  852 |         if field.has_expr && field.expr is ast.IntegerLiteral {
  853 |             i = field.expr.val.int()
      |                            ~~~
  854 |         }
  855 |         g.writeln('$i,')
vlib/v/checker/checker.v:2920:25: error: field `embeds` does not exist or have the same type in all sumtype variants
 2918 |         && sym.language == .v {
 2919 |         // x.Foo.y => access the embedded struct
 2920 |         for embed in sym.info.embeds {
      |                               ~~~~~~
 2921 |             embed_sym := c.table.get_type_symbol(embed)
 2922 |             if embed_sym.embed_name() == field_name {
vlib/v/checker/checker.v:2923:16: error: cannot assign to `node.typ`: expected `ast.Type`, not `void`
 2921 |             embed_sym := c.table.get_type_symbol(embed)
 2922 |             if embed_sym.embed_name() == field_name {
 2923 |                 node.typ = embed
      |                            ~~~~~
 2924 |                 return embed
 2925 |             }
vlib/v/checker/checker.v:2924:12: error: cannot use `void` as type `ast.Type` in return argument
 2922 |             if embed_sym.embed_name() == field_name {
 2923 |                 node.typ = embed
 2924 |                 return embed
      |                        ~~~~~
 2925 |             }
 2926 |         }
vlib/v/checker/checker.v:4269:60: error: field `typ` does not exist or have the same type in all sumtype variants
 4267 |                 if is_variable {
 4268 |                     if left_sym.kind in [.sum_type, .interface_] {
 4269 |                         c.smartcast(infix.left, infix.left_type, infix.right.typ, mut
      |                                                                              ~~~
 4270 |                             node.scope)
 4271 |                     }
vlib/v/checker/checker.v:5991:45: error: field `typ` does not exist or have the same type in all sumtype variants
 5989 |                         && sym.kind == .interface_ {
 5990 |                         // is interface
 5991 |                         checked_type := c.unwrap_generic(left.typ)
      |                                                               ~~~
 5992 |                         should_skip = !c.table.type_implements_interface(checked_type,
 5993 |                             got_type)
vlib/v/checker/checker.v:6180:49: error: field `typ` does not exist or have the same type in all sumtype variants
 6178 |                     if cond.left is ast.TypeNode && cond.right is ast.TypeNode {
 6179 |                         // `$if Foo is Interface {`
 6180 |                         sym := c.table.get_type_symbol(cond.right.typ)
      |                                                                   ~~~
 6181 |                         if sym.kind != .interface_ {
 6182 |                             c.expr(cond.left)
```

**Comment by medvednikov** [comment]
@yuyi98 first you need to push the first small part of this to update v.c.

Then push the remaining part.

Locally it worked for you since you also gradually updated v.c.

**Comment by yuyi98** [comment]
@medvednikov  Sorry, I coundn't push the first part, temporary function renaming cannot be used for this case.

**Comment by SleepyRoy** [comment]
@yuyi98 I guess it's because this PR is a breaking change. You may try locally
a. do your PR's code change (1/2)
b. make sure bootstrap doesn't break anymore, then generate new v.c
c. build new compiler with above new v.c
d. do your PR's code change (2/2), and make sure all code works, you know just like a usual PR

**Comment by yuyi98** [comment]
@SleepyRoy  Thank you very much for your advice, I'll try.

**Pull request closed without merging**
