### PR TITLE
main: repl hotfix add

### PR DESCRIPTION
**Pull request by Glitchfix**
This hotfix makes V repl work similar to python interactive shell.

```
>>> a:=23
>>> a 
23
>>> println(25)
25
>>> println(35)
35
>>> a
23
>>> 

```

Please feel free to share your views.

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks.

This removes the need to call `println` to print values, nothing else, right?

**Comment by Glitchfix** [comment]
Not just that

`
>>> a=23
undefined: `a`
>>> 
`

**Comment by Glitchfix** [comment]
Not just that this too
shows you the error then and there
```
>>> a=23
undefined: `a`
>>> 
```

**Comment by Glitchfix** [comment]
Please refer https://github.com/vlang/v/pull/973

**Pull request closed without merging**
