### PR TITLE
WIP: Windows Unicode I/O, 3rd try

### PR DESCRIPTION
**Pull request by vitalyster**
Continuing https://github.com/vlang/v/pull/1266, rebased on latest Windows changes

### CODE REVIEW

**Comment by vitalyster** [comment]
I will check other required changes after msvc support was added

**Comment by medvednikov** [comment]
Success!

**Comment by vitalyster** [comment]
There are some issues described on first try, the most one is string interpolation which is hardcoded with `printf` while it should use `_wprintf` and `L""` literals, can you please check?

**Comment by medvednikov** [comment]
@vitalyster CI is ok, but unfortunately it doesn't build on Windows atm. vlib not found.

Perhaps the unicode flags need to be added to https://github.com/vlang/v/blob/master/make.bat ?

**Pull request merged**
