### PR TITLE
math: added fast aprox cos and sin

### PR DESCRIPTION
**Pull request by memeone**
```v
math.aprox_sin(a f64)
math.aprox_cos(a f64)
```

Approximate cos and sin implemented using [lolremez](https://github.com/samhocevar/lolremez) as suggested by @dumblob

About 50% faster from my testing, 354ms vs 172ms on 10M iterations

### CODE REVIEW

**Comment by penguindark** [comment]
what are the limits on the use of these functions?

**Comment by memeone** [comment]
Well, since they're just approximate the value isn't exactly perfect. Here's and example of the differences
```
real cos: 0.877583
aprox cos: 0.877549
delta: 0.000033

real sin: 0.479426
aprox sin: 0.479075
delta: 0.000351
```
The difference isn't too large so they can be used instead when you don't need absolute precision. I plan to use them for arc and circle rendering in gg.

**Comment by penguindark** [comment]
ok :)
I was asking what are angle limitation from your knowledge.
This type of approximation usually have an angle limitation, I was asking only to have a warning int function documentation.

**Comment by memeone** [comment]
Ah, sorry for the misunderstanding. Falls off pretty bad outside of `-2π to 2π` ish

**Comment by penguindark** [comment]
tnx :)

**Pull request merged**
