### PR TITLE
 checker: disallow sum type holding alias ptrs

### PR DESCRIPTION
**Pull request by Delta456**
Fixes https://github.com/vlang/v/issues/20782

### CODE REVIEW

**Comment by MCausc78** [comment]
```v
vlib/v/checker/tests/sum_type_holding_alias_ptr_err.vv:3:12: error: sum type cannot hold a reference type 
     1 | type Alias1 = &int 
     2 | type Alias2 = &string 
     3 | type Qwe = Alias1 | Alias2 
       |            ~~~~~~ 
     4 |  
     5 | fn main() { 
 Details: declare the sum type with non-reference types: `Qwe = Alias1 | ...` 
 and use a reference to the sum type instead: `var := &Qwe(Alias1(val))`
```
Can we get other Details message?

**Comment by Delta456** [comment]
> ```v
> vlib/v/checker/tests/sum_type_holding_alias_ptr_err.vv:3:12: error: sum type cannot hold a reference type 
>      1 | type Alias1 = &int 
>      2 | type Alias2 = &string 
>      3 | type Qwe = Alias1 | Alias2 
>        |            ~~~~~~ 
>      4 |  
>      5 | fn main() { 
>  Details: declare the sum type with non-reference types: `Qwe = Alias1 | ...` 
>  and use a reference to the sum type instead: `var := &Qwe(Alias1(val))`
> ```
> 
> Can we get other Details message?

Like what?

**Comment by MCausc78** [comment]
> > ```v
> > vlib/v/checker/tests/sum_type_holding_alias_ptr_err.vv:3:12: error: sum type cannot hold a reference type 
> >      1 | type Alias1 = &int 
> >      2 | type Alias2 = &string 
> >      3 | type Qwe = Alias1 | Alias2 
> >        |            ~~~~~~ 
> >      4 |  
> >      5 | fn main() { 
> >  Details: declare the sum type with non-reference types: `Qwe = Alias1 | ...` 
> >  and use a reference to the sum type instead: `var := &Qwe(Alias1(val))`
> > ```
> > 
> > Can we get other Details message?
> 
> Like what?

Current one is confusing, since `Qwe = Alias1 | ...` declares sumtype with reference, something like `declare alias as non-reference type, then declare sumtype as Qwe = Alias1 `

**Comment by Delta456** [comment]
> > > ```v
> > > vlib/v/checker/tests/sum_type_holding_alias_ptr_err.vv:3:12: error: sum type cannot hold a reference type 
> > >      1 | type Alias1 = &int 
> > >      2 | type Alias2 = &string 
> > >      3 | type Qwe = Alias1 | Alias2 
> > >        |            ~~~~~~ 
> > >      4 |  
> > >      5 | fn main() { 
> > >  Details: declare the sum type with non-reference types: `Qwe = Alias1 | ...` 
> > >  and use a reference to the sum type instead: `var := &Qwe(Alias1(val))`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Can we get other Details message?
> > 
> > 
> > Like what?
> 
> Current one is confusing, since `Qwe = Alias1 | ...` declares sumtype with reference, something like `declare alias as non-reference type, then declare sumtype as Qwe = Alias1 `

It makes it clear, thanks!

**Comment by MCausc78** [comment]
Forbid `type Foo = &int; type Bar = Foo; type Baz = Bar | int | string` too

**Comment by Delta456** [comment]
> type Foo = &int; type Bar = Foo; type Baz = Bar | int | string

This already works 

```
file.v:1:29: error: type `Foo` is an alias, use the original alias type `int` instead
    1 | type Foo = &int; type Bar = Foo; type Baz = Bar | int | string
      |                             ~~~
```

**Comment by JalonSolov** [comment]
Hmm... that last error message is incorrect/confusing.  Should be fixed in another PR.

**Review by spytheman — APPROVED** [review]
Good work.

**Pull request merged**
