### PR TITLE
return checking: check that functions return in all if/else branches

### PR DESCRIPTION
**Pull request by schurhammer**
Raise a compile error if the function doesn't return for some code branch.
e.g.
```
fn test() int {
    if <condition> {
        return 1
    }
    // no return here, compile error
}
```
One known caveat is that it doesn't recognize infinite loops that can only end in return, and thus require a return after the infinite loop.
e.g.
```
fn test() int {
    for {
        if <condition> {
            return 1
        }
    }
    // no return here, compile error - v doesn't know this is unreachable
}
```

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks

Can you remove this:
`// TODO can never get here - v doesn't know that`

I wouldn't worry about that. That's how C# works too.
Explicit returns even when they are 100% unreachable.
It makes the compiler easier and user code modifications unnecessary.

**Comment by avitkauskas** [comment]
I'd like V to be better than Go in this regard and would not require me put `return` where it is not actually necessary.

**Comment by schurhammer** [comment]
I think we should keep it. The example is actually more like https://play.golang.org/p/5jURcrZcWZd
Go allows it without a return at the end.

**Comment by avitkauskas** [comment]
This works in Go:

```go
func foo() bool {
    for {
        if true {
            return true
        }
    }
}
```

**Pull request merged**
