### PR TITLE
encoding.utf8 Update

### PR DESCRIPTION
**Pull request by penguindark**
**encoding.utf8 Utilities**

This is an update of the utility file for utf8 strings.
The functions are improved as speed, further improvement are possible.

**Functions**
```v
//
// len
// Parameters:
//  - s string
// Output:
//  - int
//
// get the lenght of the string as utf8 chars
//
pub fn len(s string) int 

/
// u_len
// Parameters:
//  - s ustring
// Output:
//  - int
//
// get the lenght of the ustring
//
pub fn u_len(s ustring) int 

//
// to_upper
// Parameters:
//  - s string
// Output:
//  - string
//
// Convert a utf8 string to uppercase
//
pub fn to_upper(s string) string 

//
// to_upper
// Parameters:
//  -s ustring
// Output:
//  - ustring
//
// Convert a ustring to uppercase
//
pub fn u_to_upper(s ustring) ustring 

//
// to_lower
// Parameters:
//  -s string
// Output:
//  - string
//
// Convert a utf8 string to lowercase
// 
pub fn to_lower(s string) string 

//
// to_lower
// Parameters:
//  - s ustring
// Output:
//  - ustring
//
// Convert a ustring to lowercase
// 
pub fn u_to_lower(s ustring) ustring 
```

**Example of use**
```v

import encoding.utf8

// string test
src:="ăĂ ôÔ testo æ€”" // len 15 runes, raw 24 bytes
upper:=utf8.to_upper(src)
lower:=utf8.to_lower(src)

// ustring test
src1:=src.ustring()
upper1:=utf8.u_to_upper(src1)
lower1:=utf8.u_to_lower(src1)

// test len function
len1 := utf8.len("pippo") // 5
len2 := utf8.len(src) // 15

// test u_len function
len3 := utf8.u_len(src1) // 15
len4 := utf8.u_len("pippo".ustring()) //5
```

**Next steps**
-Benchmark on "big data"
-Add more speed to the `up_low` function
-Improve integration with string and ustring structs

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks!

Please use the following documenting format:

```
// len returns the length of the string as utf8 codepoints
fn len
```

instead of

```
//
// len
// Parameters:
//  - s string
// Output:
//  - int
//
// get the lenght of the string as utf8 chars
//
fn len
```

**Comment by penguindark** [comment]
Ok, I hope that now the comments are ok.
please, let me know :)
```v
// return the leght as number of unicode chars from a string
pub fn len(s string) int 
```
**Question**
By the way, is there  some documentation about how to document the source code?
Just to have a standard for comments as so for and augurably have auto-doc in the project.

**Comment by medvednikov** [comment]
https://vlang.io/docs#writing_docs

The comment must begin with the function's name.

**Comment by penguindark** [comment]
Thanks for the info :) I'll study it

**Pull request merged**
