### PR TITLE
checker: disallow pointer arithmetic

### PR DESCRIPTION
**Pull request by danieldaeschle**
Fixes https://github.com/vlang/v/issues/169

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
good work

**Comment by danieldaeschle** [comment]
Fixes https://github.com/vlang/v/issues/812 as well

**Comment by danieldaeschle** [comment]
@Larpon can you fix the failing vab?

**Comment by spytheman** [comment]
> @Larpon can you fix the failing vab?

rebase over current master for now

**Pull request merged**
