### PR TITLE
builtins: ustring comparisons, concatenation and other functions

### PR DESCRIPTION
**Pull request by Henrixounez**
**Additions:**
Displaying an `ustring` using `println`
Comparing `ustring`
Concatenating `ustring`
`count` and `index_after` functions for `ustring`
Few other fixes on `ustring` functions.
New tests for `ustring`

### CODE REVIEW

**Comment by medvednikov** [comment]
`ustring` is a temporary solution until `[]rune` is implemented.

That's why it's not documented.

All string operations should be performed on `ustring.str`

**Comment by medvednikov** [comment]
@Henrixounez what problem are you solving with this?

Why not use ustring.str for now?

**Comment by lcddh** [comment]
@medvednikov 
the ustring now is defined 
struct ustring {
pub:
	s     string
	runes []int
	len   int
}
Do you need to change s to str?

**Comment by Delta456** [comment]
@lcddh Is there any need to?

**Comment by Henrixounez** [comment]
@medvednikov I was using `ustring` in the readline, i needed to be able to print n characters. But `ustring.s` can have multi-byte characters (sizes defined on the `runes[]`). It was easier to add those functions for the `ustring` in the lib instead of doing weird calculations on the readline module.

**Comment by medvednikov** [comment]
@Henrixounez 

I see, I'll think about the best way to solve this.

**Pull request merged**
