### PR TITLE
v.util: add iabs

### PR DESCRIPTION
**Pull request by zakuro9715**
int abs fn exist only in fmt for now. But it could be used in other places. Avoid to define same function, I added iabs at v.util

### CODE REVIEW

**Comment by serkonda7** [comment]
I think this should better go under vlib/math.
Maybe we could create an new submodule `math.util`

**Comment by spytheman** [comment]
> I think this should better go under vlib/math.
> Maybe we could create an new submodule `math.util`

That may be a good idea ... The reason that abs is defined in several places, is to avoid importing `math` (which is big) and the definition is small, but a smaller `math.util` submodule containing only abs and min/max functions for int, u32, f32, f64 will be fine I think.

Can you make a PR with that @serkonda7 ?

**Comment by serkonda7** [comment]
@spytheman yeah ofc I can make a PR.

And a question: importing a big module won't be a problem anymore with `-skip-unused`, right?

**Comment by spytheman** [comment]
It is complicated. It will for `math`, and it is not perfect yet. `math` also has a libc dependency, that is not good for the cross platform portability of the compiler itself.

**Pull request merged**
