### PR TITLE
interpolation: change to `${xxx}`

### PR DESCRIPTION
**Pull request by yuyi98**
This PR change interpolation to `${xxx}`.

- Modify `vfmt` to fit this syntax.
- Modify vlib/v to `S{xxx}`.

### CODE REVIEW

**Comment by spytheman** [comment]
why is this needed?

**Comment by Delta456** [comment]
https://github.com/vlang/v/issues/7173

**Comment by spytheman** [comment]
thanks @Delta456

**Comment by medvednikov** [comment]
Sorry for not being explicit enough in my comment @yuyi98 

What I meant to say was that having just `${}` would be simple and align with the "one way" philosophy. But `x = $x` is very important for simplicity and readability as well.

I do agree that rules like `$x.foo()` should be removed, however `x = $x` and `y = $x.y` are too fundamental and should stay.

**Comment by yuyi98** [comment]
Ok, I see.

**Pull request closed without merging**
