### PR TITLE
`make test` now builds v twice before running actual tests

### PR DESCRIPTION
**Pull request by Compro-Prasad**

### CODE REVIEW

**Comment by medvednikov** [comment]
Please update this, it referes to old vc, which was removed.

**Comment by Compro-Prasad** [comment]
Done.

**Comment by Compro-Prasad** [comment]
I think this was added in: https://github.com/vlang/v/commit/6a0ac35af2e9971114c4f49da08f9c818392a590

Updating the PR title and description.

**Comment by Compro-Prasad** [comment]
All updated.

**Comment by medvednikov** [comment]
I still see `vc: v.c` in the diff.

**Comment by Compro-Prasad** [comment]
`vc` is different from `v` as it is the C build. I could add a `bootstrap` target which builds `v` and cleans `v.c` and `vc.

> I still see vc: v.c in the diff.

This is needed because, in order to build `vc` we need the C source `v.c`.

**Comment by Compro-Prasad** [comment]
By adding a `bootstrap` target we can ensure that it is only for the first time. After that the user would only use `make` which would run `buildtwice` target. Is this approach correct?

**Comment by Compro-Prasad** [comment]
Rebased with the latest changes on master.

Also, I don't get the point of not using `vc`. Is there a specific reason? If so, please explain it. I may remove it. But anyway, that won't be a good way to write a `Makefile`.

* `make test`
```
Checking if V can build itself..
Passed
Running tests using final build
============running ../base64/base64_test==============================
PASSED: test_decode()
CAST TYP=int tok=
int
CAST TYP=int tok=
int
============running ../glm/glm_test==============================
glm ortho(0.000000, 200.000000, 400.000000, 0.000000)
0.010000
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
PASSED: test_ortho()
rotate
[ 2.00 0.00 0.00 0.00 
  0.00 2.00 0.00 0.00 
  0.00 0.00 2.00 0.00 
  0.00 0.00 0.00 1.00 ]
[ 1.08 1.68 0.00 0.00 
  -1.68 1.08 0.00 0.00 
  0.00 0.00 2.00 0.00 
  0.00 0.00 0.00 1.00 ]
[ 1.00 0.00 0.00 0.00 
  0.00 1.00 0.00 0.00 
  0.00 0.00 1.00 0.00 
  0.00 0.00 -0.50 1.00 ]
============running ../builtin/string_test==============================
PASSED: test_add()
PASSED: test_add()
PASSED: test_add()
PASSED: test_add()
PASSED: test_ends_with()
PASSED: test_between()
PASSED: test_compare()
PASSED: test_lt()
PASSED: test_lt()
PASSED: test_lt()
PASSED: test_lt()
PASSED: test_lt()
PASSED: test_lt()
PASSED: test_ge()
PASSED: test_ge()
PASSED: test_ge()
PASSED: test_ge()
PASSED: test_ge()
PASSED: test_compare_strings()
PASSED: test_compare_strings()
PASSED: test_compare_strings()
PASSED: test_compare_strings()
PASSED: test_compare_strings()
PASSED: test_compare_strings()
PASSED: test_sort()
PASSED: test_sort()
PASSED: test_sort()
PASSED: test_sort()
PASSED: test_sort()
PASSED: test_split()
PASSED: test_split()
PASSED: test_split()
PASSED: test_split()
PASSED: test_split()
PASSED: test_split()
PASSED: test_split()
PASSED: test_split()
PASSED: test_split()
PASSED: test_split()
PASSED: test_trim_space()
PASSED: test_trim_space()
PASSED: test_join()
PASSED: test_join()
PASSED: test_clone()
PASSED: test_clone()
PASSED: test_clone()
PASSED: test_replace()
PASSED: test_replace()
PASSED: test_replace()
PASSED: test_replace()
PASSED: test_replace()
PASSED: test_replace()
PASSED: test_replace()
PASSED: test_replace()
PASSED: test_itoa()
PASSED: test_itoa()
PASSED: test_itoa()
PASSED: test_itoa()
PASSED: test_itoa()
PASSED: test_itoa()
PASSED: test_reassign()
PASSED: test_reassign()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_runes()
PASSED: test_lower()
PASSED: test_lower()
PASSED: test_lower()
PASSED: test_lower()
PASSED: test_lower()
PASSED: test_lower()
PASSED: test_lower()
PASSED: test_left_right()
PASSED: test_left_right()
PASSED: test_left_right()
PASSED: test_left_right()
PASSED: test_contains()
PASSED: test_contains()
PASSED: test_arr_contains()
PASSED: test_arr_contains()
PASSED: test_to_num()
PASSED: test_to_num()
PASSED: test_to_num()
PASSED: test_to_num()
PASSED: test_hash()
PASSED: test_hash()
PASSED: test_hash()
PASSED: test_hash()
PASSED: test_hash()
PASSED: test_hash()
PASSED: test_trim_left()
PASSED: test_trim_left()
PASSED: test_all_after()
============running ../builtin/array_test==============================
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_ints()
[1, 5, 2, 3]
[1, 5, 2, 3, 4]
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_ints()
PASSED: test_short()
PASSED: test_short()
PASSED: test_short()
PASSED: test_short()
PASSED: test_short()
PASSED: test_large()
PASSED: test_large()
PASSED: test_empty()
PASSED: test_empty()
PASSED: test_empty()
PASSED: test_empty()
PASSED: test_push()
PASSED: test_push()
PASSED: test_strings()
PASSED: test_repeat()
PASSED: test_repeat()
PASSED: test_right()
PASSED: test_right()
PASSED: test_left()
PASSED: test_left()
3
4
PASSED: test_slice()
[3, 4]
PASSED: test_push_many()
PASSED: test_push_many()
PASSED: test_push_many()
PASSED: test_push_many()
[1, 2, 3, 4, 5, 6]
Running examples using final build
println
println
Generating main()...
```

**Pull request closed without merging**
