### PR TITLE
fmt: fix alignment of enumeration types

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix alignment of enumeration types fields.

### CODE REVIEW

**Comment by spytheman** [comment]
Try running `VAUTOFIX=1 v check-md doc/docs.md`

**Comment by spytheman** [comment]
Please also add 1 or more `_keep.vv` files for the change.

**Comment by yuyi98** [comment]
Ok, I'll add test for it.

**Comment by spytheman** [comment]
Thank you.

**Pull request merged**
