### PR TITLE
Escape string function in gen/str.v

### LINKED ISSUE #6316: Compiler error with escaped double-quote
**V version:** 2cb711e
**OS:** Win10

**What did you do?**
Tried to compile this file:
```
fn main() {
	s := "escaped double-quote \""
	println(s)
}
```

**What did you expect to see?**
That it compiles.
 
**What did you see instead?**
I get following error:
```
D:\src\v>v error.v
builder error: Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl -w /we4013 /volatile:ms /Fo"C:\temp\v\error.tmp.c.obj" /MDd "C:\temp\v\error.tmp.c" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared" kernel32.lib user32.lib advapi32.lib dbghelp.lib /link /NOLOGO /OUT:"D:\src\v\error.exe" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\X64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\X64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\lib\X64" /DEBUG:FULL

error.tmp.c
C:\temp\v\error.tmp.c(8010): error C2146: syntax error: missing ')' before identifier 'bar'
C:\temp\v\error.tmp.c(8010): error C2017: illegal escape sequence
C:\temp\v\error.tmp.c(8010): error C2059: syntax error: ')'
```

### PR DESCRIPTION
**Pull request by orneo1212**
PR to fix #6316  and #5912

### CODE REVIEW

**Comment by orneo1212** [comment]
Will fix #2216 too.

**Comment by medvednikov** [comment]
Sorry, I had to revert this. It slowed the compiler down by almost 100%:

0.266s => 0.423s

**Comment by medvednikov** [comment]
Using string concat in a loop for such a critical part of the compiler is a bad idea. Try a byte array or a string builder.

**Comment by orneo1212** [comment]
How can I check this time?
Will refactor it for speed

**Comment by medvednikov** [comment]
`time v -o v.c  cmd/v`

@orneo1212

**Pull request merged**
