### PR TITLE
vlib: fixed bst child access if root is none

### PR DESCRIPTION
**Pull request by mjh316**
Fixed child access handling for 'none' == root added tests.
Mentioned in #14059.

### CODE REVIEW

**Comment by yuyi98** [comment]
Please modify the error message location of `checker/tests/check_err_msg_with_generics.out`  accordingly.

**Comment by mjh316** [comment]
The file contents are:
`
vlib/v/checker/tests/check_err_msg_with_generics.vv:15:10: error: cannot cast struct `BSTree<Result<[]Token, Err<string>>>` to `int`
   13 | fn test_err_msg() {
   14 |     typ := datatypes.BSTree<Result<[]Token, Err<string>>>{}
   15 |     println(int(typ))
      |             ~~~~~~~~
   16 | }
vlib/datatypes/bstree.v:190:17: error: cannot append `T` to `[]T`
  188 |     }
  189 |     bst.in_order_traversal_helper(node.left, mut result)
  190 |     result << node.value
      |                    ~~~~~
  191 |     bst.in_order_traversal_helper(node.right, mut result)
  192 | }
vlib/datatypes/bstree.v:210:17: error: cannot append `T` to `[]T`
  208 |     bst.post_order_traversal_helper(node.left, mut result)
  209 |     bst.post_order_traversal_helper(node.right, mut result)
  210 |     result << node.value
      |                    ~~~~~
  211 | }
  212 |
vlib/datatypes/bstree.v:226:17: error: cannot append `T` to `[]T`
  224 |         return
  225 |     }
  226 |     result << node.value
      |                    ~~~~~
  227 |     bst.pre_order_traversal_helper(node.left, mut result)
  228 |     bst.pre_order_traversal_helper(node.right, mut result)
`
I'm new to V, and so I'm not sure why you can't append T to an apparently resizable array of type T. Any guidance or thoughts would be appreciated. I'm also not sure why the test_err_msg() function test failed, as I assumed the purpose of that function was to throw an error message.
Thanks!

**Comment by yuyi98** [comment]
Just change `checker/tests/check_err_msg_with_generics.out` to:
```v
vlib/v/checker/tests/check_err_msg_with_generics.vv:15:10: error: cannot cast struct `BSTree<Result<[]Token, Err<string>>>` to `int`
   13 | fn test_err_msg() {
   14 |     typ := datatypes.BSTree<Result<[]Token, Err<string>>>{}
   15 |     println(int(typ))
      |             ~~~~~~~~
   16 | }
vlib/datatypes/bstree.v:196:17: error: cannot append `T` to `[]T`
  194 |     }
  195 |     bst.in_order_traversal_helper(node.left, mut result)
  196 |     result << node.value
      |                    ~~~~~
  197 |     bst.in_order_traversal_helper(node.right, mut result)
  198 | }
vlib/datatypes/bstree.v:216:17: error: cannot append `T` to `[]T`
  214 |     bst.post_order_traversal_helper(node.left, mut result)
  215 |     bst.post_order_traversal_helper(node.right, mut result)
  216 |     result << node.value
      |                    ~~~~~
  217 | }
  218 |
vlib/datatypes/bstree.v:232:17: error: cannot append `T` to `[]T`
  230 |         return
  231 |     }
  232 |     result << node.value
      |                    ~~~~~
  233 |     bst.pre_order_traversal_helper(node.left, mut result)
  234 |     bst.pre_order_traversal_helper(node.right, mut result)
```

**Comment by spytheman** [comment]
For a method like `pub fn (bst &BSTree<T>) contains(value T) bool {`, it is the responsibility of the caller, that the receiver `bst` is not null/zero.

Masking such a problem, by checking if it is 0 inside each method, can only delay the detection of the actual problem imho, and thus make fixing the actual error harder.

**Comment by spytheman** [comment]
The .min method can be fixed with:
```v
pub fn (bst &BSTree<T>) min() ?T {
    if bst.root == 0 {
        return none
    }
    min := bst.get_min_from_left(bst.root)
    if !min.is_init {
        return none
    }
    return min.value
}
```
note, that the segmentation fault is not caused, by accessing bst (which is not 0), but by calling `get_min_from_left` with a 0 argument, where that method will try to access fields on that value (dereferencing the 0 pointer, and thus segfaulting).

**Comment by mjh316** [comment]
Thanks for the assistance - I remove it to only the four functions that seemed to have this issue, but feel free to modify as needed.

**Pull request merged**
