### PR TITLE
tetris: add ghost

### PR DESCRIPTION
**Pull request by nsauzede**
Trivial enhancement to Tetris example, displaying a "ghost" of the current tetro,
at the place it would land if we would be hitting the "drop" key.

### CODE REVIEW

**Comment by medvednikov** [comment]
Original tetris game didn't have this and I think it makes the game more challenging and interesting, and the implementation simpler.

**Comment by spytheman** [comment]
It depends on the difficulty/speed. Having a ghost is beneficial in the initial stages, but can make the game more difficult later on. I just tried the game and I think it would be a good addition. Perhaps we can have a toggle key for it, so it can be optional?

**Comment by medvednikov** [comment]
Toggle key sounds good.

**Comment by nsauzede** [comment]
i will add the toggle key

**Comment by nsauzede** [comment]
I added 'g' as toggle key, and ghost view is disabled by default.
Is that Ok ?

**Comment by medvednikov** [comment]
Yes, perfect.

**Pull request merged**
