### PR TITLE
js: More tests & add array prepend codegen

### PR DESCRIPTION
**Pull request by playXE**
More tests were added, array.prepend codegen and a small cast bug fix.

### CODE REVIEW

**Comment by playXE** [comment]
CI gets this error 🤔 
```
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

typedef byte u8;
             ^
/tmp/v/v.16185080130902759146.tmp.c:427:17: note: previous definition is here
typedef uint8_t u8;
```

**Comment by spytheman** [comment]
That CI failure is unrelated, it will be fixed soon.

**Comment by div72** [comment]
Wouldn't it be better to use `assert`s instead of stdout in tests?

**Comment by spytheman** [comment]
> Wouldn't it be better to use `assert`s instead of stdout in tests?

they do not work yet properly in the js backend

**Pull request merged**
