### PR TITLE
main: vrepl interactive shell update

### PR DESCRIPTION
**Pull request by Glitchfix**
Python like interactive shell

```
>>> a=24
undefined: `a`
>>> a:=24
>>> a
24
>>> a=25
`a` is immutable
>>> mut a:=24
redefinition of `a`
>>> mut b:=25 
>>> b=25
>>> b
25
>>> println(b)
25
>>> b
25
```

Not sure how to make test case for this it has to be done manually

### CODE REVIEW

**Comment by pverghese** [comment]
Doesn't work for this:

mut a:= 2
println(a) // Gives 2
a = 3 // a value doesn't change
println(a) // Gives 2 again

**Comment by Glitchfix** [comment]
@pverghese It works fine now please try it out

**Comment by pverghese** [comment]
It works fine now for the example above. But a small bug is present.

Example in the REPL

import http

a:=http.get('')
println(a) // Prints error message http:empty get url from the previous step

b:=2
println(b) // Prints the error message above and then the value of b

Not a big issue. But can get cumbersome if a number of error messages are piled up as all the error messages get printed before the print statement is executed

**Comment by Glitchfix** [comment]
@pverghese it's actually a hotfix there's a lot of features I'm gonna add to this.

**Comment by pverghese** [comment]
Cool. Looks good then.

**Comment by medvednikov** [comment]
Thanks

**Pull request merged**
