### PR TITLE
fix:type alias println

### PR DESCRIPTION
**Pull request by lcddh**
```
type Myint int
fn main() {
    i := Myint(10)
    ret := i + 100
    print(ret)
}
```
not need to println(ret.str()).
You can also customize your own print function fn (n Myint) str () {...}

### CODE REVIEW

**Comment by medvednikov** [comment]
Your code works for me without this PR.

**Comment by lcddh** [comment]
image

**Comment by ecreeth** [comment]
In the playground works!
image

**Comment by medvednikov** [comment]
Yeah works locally as well.

Make sure you have the latest V installed.

**Comment by lcddh** [comment]
image
I am on windows 10

**Comment by lcddh** [comment]
```
if !T.has_method('str') 

fn (t &Type) has_method(name string) bool {
	_ = t.find_method(name) or { return false }
	return true
}
**this function does not find parent**
fn (t &Type) find_method(name string) ?Fn {
	// println('$t.name find_method($name) methods.len=$t.methods.len')
	for method in t.methods {
		// println('method=$method.name')
		if method.name == name {
			return method
		}
	}
	return none
}
**but this function does**
fn (table &Table) find_method(typ &Type, name string) ?Fn {
	t := table.typesmap[typ.name]
	for method in t.methods {
		if method.name == name {
			return method
		}
	}
	if typ.parent != '' {
		parent := table.find_type(typ.parent)
		for method in parent.methods {
			if method.name == name {
				return method
			}
		}
		return none
	}
	return none
}

**Comment by spytheman** [comment]
int and derivations from it are special and already work.
I think a better illustration for the utility of this PR is this program:
```
struct Human { name string }
pub fn (h Human) str() string { return 'Human: $h.name' }
type Person Human

fn main() {
   p := Person{'Bilbo'}
   println(p)
}
```

For it, without this PR, I get an error: ```  `Person` needs to have method `str() string` to be printable``` .

With this PR, it compiles, runs and prints: `Human: Bilbo` as expected.

Moreover, with this PR, the following also works:
```v
struct Human { name string }
pub fn (h Human) str() string { return 'Human: $h.name' }
type Person Human

pub fn (h Person) str() string { return 'Person: $h.name' }
fn main() {
   p := Person{'Bilbo'}
   println(p)
}
```
and prints: `Person: Bilbo` .

**Comment by medvednikov** [comment]
Thanks @spytheman

**Comment by medvednikov** [comment]
I've added these examples to the tests.

**Comment by medvednikov** [comment]
Thanks for the fix @lcddh this was very important.

**Pull request merged**
