### PR TITLE
doc: Add a note on how to define type aliases.

### PR DESCRIPTION
**Pull request by AlbertoGP**
Seems obvious and natural now that I know it.

### CODE REVIEW

**Comment by serkonda7** [comment]
I personally think this is redundant.

**Comment by spytheman** [comment]
I think it is a good and clear change that will help people in the future. Please move it right after the [Sum types section](https://github.com/vlang/v/blob/master/doc/docs.md#sum-types), may be in its own subsection "Type Aliases". I think that the types section should start with the primitives. Type aliasing is something that is little more advanced imho (most people may not need to use it ever).

**Comment by AlbertoGP** [comment]
I’ve moved it to its own section inside Types2, where it fits better:
https://github.com/AlbertoGP/v/blob/doc-type-alias/doc/docs.md#table-of-contents

**Comment by AlbertoGP** [comment]
Should I also re-balance the columns in the TOC?
I would move Unions to the first column under Structs.

**Comment by AlbertoGP** [comment]
Re-balanced the TOC columns too, will undo if that’s a problem.

**Pull request merged**
