### PR TITLE
fmt: remove extra comma of branch instead of parse error

### PR DESCRIPTION
**Pull request by zakuro9715**
See test.

### CODE REVIEW

**Comment by spytheman** [comment]
I am not sure that is a good idea - imho vfmt should only format code, not fix syntax errors 🤔 , and this is invalid V code:
```v
fn match_branch_extra_comma() {
	match x {
		Foo, Bar, {}
		int,,, string, {}
	}
	match n {
		0...5, {}
		2, 3, {}
		else {}
	}
}
```
@medvednikov what do you think?

**Comment by zakuro9715** [comment]
Yes this is invalid V code. But I often make this mistake when cut then paste to another branch. 

I agree that v fmt doesn't  aggressively fix syntax errors. but this case is simple and useful, so I think it's acceptable .

**Comment by JalonSolov** [comment]
This one I can see having - other languages _require_ the extra comma sometimes, so people may be used to that.  Maybe limited a bit... it it's a comma just before the closing `]` or `}`, remove it.  The pathological example spy gave should still fail.

**Comment by spytheman** [comment]
All right, I could not see the usecase, but if it does happen in practice, it may be valuable indeed.

**Pull request merged**
