### PR TITLE
gen: fix multi statement if_expr

### PR DESCRIPTION
**Pull request by Gladear**
So, after realizing what I did last time with if expressions was very limiting (no loop, no optional, and almost certainly other things I didn't think of), here's another try !

What still needs to be done :
- [ ] Make multi return work with MSVC
- [ ] Handle variable mutation in infix expression (see test `test_if_expression_mutate_var`, `vlib/v/tests/if_expression_test.v`)

I have an idea on how to handle variable mutation, but I may need help for MSVC... It may be a subject for later though.

### CODE REVIEW

**Comment by emily33901** [comment]
multi return should work with msvc now after #5065 (unless you mean specifcally in if statements in which case i have no idea 🙃

**Comment by Gladear** [comment]
Yes, I meant specifically in if expressions 🙂

**Comment by emily33901** [comment]
Cool I can see if I can get a fix to that extent up and running 👌

**Comment by Gladear** [comment]
They work with the current implementation, but not with modifications I made.
I would be most grateful if you could help me figure out what's going on :smile:

**Comment by joe-conigliaro** [comment]
I have been doign some work which greatly simplifies multi exprs so they should be able to be used anywhere

**Comment by Gladear** [comment]
Nice ! Is it merged already, or work in progress ?

**Comment by joe-conigliaro** [comment]
@Gladear work in progress I started a few days ago, Ive already merged assign/expr assign/stmt and got it to compile... cleaned up a bunch of stuff in parser, but still working through some checker errors things its very confusing at the moment because to many fixes for different things in different places, hopefully

**Comment by JalonSolov** [comment]
@joe-conigliaro is your work done, now?

**Comment by joe-conigliaro** [comment]
@JalonSolov nah I have only done the assign stuff, still haven't done the muiti expr stuff

**Comment by medvednikov** [comment]
Joe pushed his fix.

**Pull request closed without merging**
