### PR TITLE
[02/07/19]: Make the REPL Work Well

### PR DESCRIPTION
**Pull request by monarrk**
The repl now executes code as you enter it. Here's how it works:
1. Text is taken into a var `line`. The line is added to the array of lines
2. The array of lines is split by \n and added to a source file
3. V compiles the source file
4. The V REPL takes the output of the binary and prints it out

Now you no longer need to call `print` to execute your code and you don't have weird arguably insecure code like `line.starts_with('print')`

You can watch a video of this [here](https://imgur.com/a/v9MCdYt)

### CODE REVIEW

**Comment by medvednikov** [comment]
I'm considering removing the `declared and not used` error from REPL.

**Comment by monarrk** [comment]
> You should not compile at every line written, because it would lead to compilation errors where you would have wanted to keep writing.
Do you suggest having a command of sorts like `exit` to compile with? Or do you suggest we compile only when calling a certain func such as `println` like before?

**Comment by Henrixounez** [comment]
I don't know if we should need to compile only with a certain function or with a keyword.
Either way, the thing is that as my previous examples of `fn` or `if` it can cause annoyance.
One thing that could be done in those cases is to potentially track brackets to know whether or not it should compile now.

An other comment on REPL as a whole is the fact that if we want to compile something again, it would go into the process of doing everything again. It would be great if variables values and functions were stored somewhere.
It could be kind of annoying of having everything done again for example with multiple prints : 
```
>>> println('one')
one
>>> println('two')
one
two
>>> 
```

**Comment by MaD70** [comment]
I see two possible solutions to this problem:

1. provide an explicit line continuation character at the end of the line, before typing a carriage return (like `\` in C macros, see [example](https://stackoverflow.com/a/10419556));
2. provide an explicit termination character just for REPL.

**Comment by Glitchfix** [comment]
Please can you refer to my hotfix https://github.com/vlang/v/pull/962

**Comment by aguspiza** [comment]
> I'm considering removing the `declared and not used` error from REPL.

Evaluate at the end of the scope and enter a scope when starting REPL.
Would this work?

**Comment by medvednikov** [comment]
Sorry for the delay and thanks for the PR.

This was fixed a while ago by a different PR with several other improvements.

**Pull request closed without merging**
