### PR TITLE
cgen: fix auto eq for fixed array

### LINKED ISSUE #23149: C error on compare aliased arrays with initialisation: `Arr{} == Arr{}`
**V doctor:**

```
V full version: V 0.4.8 5ec9bb5.610558d
OS: linux, Linux version 6.6.8-arch1-1 (linux@archlinux) (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.41.0) #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000
Processor: 16 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i5-1240P

getwd: /home/ge/Code/v/netaddr/issues
vexe: /home/ge/.vlang/v
vexe mtime: 2024-12-13 10:58:51

vroot: OK, value: /home/ge/.vlang
VMODULES: OK, value: /home/ge/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.47.1
Git vroot status: weekly.2024.50-22-g610558d4
.git/config present: true

CC version: cc (GCC) 14.2.1 20240910
emcc version: N/A
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg initialized_aliased_arrays_comparison.vv`

```v
type Arr = [4]u8

a := Arr{}
b := Arr{}

// works fine
assert a == b

// C error on each below

assert Arr{} == Arr{}

assert Arr{} == [4]u8{}

assert Arr{} == [u8(0), 0, 0, 0]!
```

**What did you expect to see?**

Assertions passed, no C errors

**What did you see instead?**

```
================== C compilation error (from tcc): ==============
cc: /tmp/v_1000/initialized_aliased_arrays_comparison.01JEZXWR0N6F9QFTPX5ED09YM8.tmp.c:5883: error: expression expected before '{'
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVjMjA4YjFlMDYzMmRkMDhlMzc5ZDEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.aNG-5OUFPueEmg0ywsMrvxw4IMLQcpaDLx9bSHf9UhQ">Huly&reg;: <b>V_0.6-21586</b></a></sub>

### PR DESCRIPTION
**Pull request by felipensp**
Fix vlib/json/tests/json_generic_array_test.v failing test

Fix #23149

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVlMzhkNDFlMDYzMmRkMDhlM2FiNmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.feIqXqij8whdtFrYC9ACCytkCc20pvbEDtt5Zk096Co">Huly&reg;: <b>V_0.6-21606</b></a></sub>

### CODE REVIEW

**Comment by spytheman** [comment]
It still fails one of the sanitized checks for:
```
#0 09:56:27 ^ master /v/oo>./v -keepc -cg -cc clang-18 -cflags -fsanitize=memory vlib/json/tests/json_generic_array_test.v
Uninitialized bytes in MemcmpInterceptorCommon at offset 4 inside [0x7fffffffbe18, 32)
==2255226==WARNING: MemorySanitizer: use-of-uninitialized-value
/usr/bin/llvm-symbolizer-18: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/llvm-symbolizer-18)
    #0 0x5555555d3625 in memcmp (/space/v/oo/vlib/json/tests/json_generic_array_test+0x7f625) (BuildId: eef1284e3cc1c46b79b037fa8f91e8c96d6db0ed)
    #1 0x5555556838ba in _option_Array_fixed_int_1_arr_eq /tmp/v_1000/json_generic_array_test.tmp.c:4218:7
    #2 0x5555556840ea in main__DocumentFindFilter_T_int_struct_eq /tmp/v_1000/json_generic_array_test.tmp.c:4232:77
    #3 0x55555570f761 in main__test_int /tmp/v_1000/json_generic_array_test.tmp.c:10751:6
    #4 0x555555714a94 in main /tmp/v_1000/json_generic_array_test.tmp.c:10930:3
    #5 0x7ffff7be8082 in __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16
    #6 0x55555559466d in _start (/space/v/oo/vlib/json/tests/json_generic_array_test+0x4066d) (BuildId: eef1284e3cc1c46b79b037fa8f91e8c96d6db0ed)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/space/v/oo/vlib/json/tests/json_generic_array_test+0x7f625) (BuildId: eef1284e3cc1c46b79b037fa8f91e8c96d6db0ed) in memcmp
Exiting
#1 09:57:10 ^ master /v/oo>
```

**Review by spytheman — APPROVED** [review]
Excellent work.

I think it will pass this time all sanitized CI jobs.

**Comment by spytheman** [comment]
`vlib/v/tests/assert_alias_array_test.v` is missing (it was reverted on master)

**Comment by felipensp** [comment]
> `vlib/v/tests/assert_alias_array_test.v` is missing (it was reverted on master)

Oh thanks.

**Pull request merged**
