### PR TITLE
Perf: arrays.sum

### PR DESCRIPTION
**Pull request by esquerbatua**
Remove the check inside the loop, initializing value with 0

### CODE REVIEW

**Comment by spytheman** [comment]
`mut head := 0` will work only for integers, but not for other types like Structs etc, unlike
`mut head := array[0]` .

**Comment by spytheman** [comment]
Try this for example:
```v
import arrays

struct Abc {
	x int = 5
}

fn (a Abc) + (b Abc) Abc {
	return Abc{
		x: a.x + b.x
	}
}

a := [1, 2, 3, 5]
dump(arrays.sum(a)!)

s := [Abc{
	x: 30
}, Abc{
	x: 20
}, Abc{
	x: 10
}]
dump(arrays.sum(s)!)
```

printing:
```
[a.v:14] arrays.sum(a)!: 11
[a.v:23] arrays.sum(s)!: Abc{
    x: 60
}
```

**Comment by esquerbatua** [comment]
> `mut head := 0` will work only for integers, but not for other types like Structs etc, unlike `mut head := array[0]` .

Right, sorry, I'll think another solution to optimize it. Ty!

**Comment by spytheman** [comment]
if your goal is to just avoid the check with the `continue`, a C style for loop: `for i:=1; i<a.len;i++ { e := a[i] ...` can work, skipping the 0th element.

**Pull request closed without merging**
