### PR TITLE
v2: add Expr to AsCast

### PR DESCRIPTION
**Pull request by alexesprit**

### CODE REVIEW

**Comment by medvednikov** [comment]
`a := expr1() as Foo`

You test won't compile. Add an actual sum type please.

**Comment by alexesprit** [comment]
Added. `simple_expected.vv` does not contain `FooBar` declaration, though, as `fmt` does not process `TypeDecl` statements.

Also, I didn't expect fmt tests should be compileable (as least now).

**Comment by medvednikov** [comment]
Yes the goal is to have them compilable :)

**Comment by spytheman** [comment]
@medvednikov, @alexesprit 
I also think that a fmt _input.vv test should NOT be expected to be compilable. v fmt will be used in cases of incomplete code (missing declarations, missing methods (which may be in other files in the same module) and so on). The test files for vfmt should be *parseable* by their own, but NOT necessarily compilable.

Also simple_input..vv is now anything but simple ... In my opinion, it would be much easier to maintain, if it is splitted to several different _input.vv files, each with a more clear purpose. 

In this way when there are errors, they would be easier to spot and finding the cause of them and fixing them will be also easier.

**Comment by spytheman** [comment]
For example:
mistery

We can see that there are 4 cases of unhandled Expr nodes, and that they are in simple_input.vv .
Where/What are they exactly - who knows... It is impossible to tell, without first simplifying the simple_input.vv file by stripping the stuff that works...

**Comment by spytheman** [comment]
For the record, the unhandled nodes were for array slices. This _input.vv program generates them:
```v
fn slices(){
    a := 1 in arr[0..]
    b := 1 in arr[..2]
    e := arr[2..]
    f := arr[..2]
}
```

**Pull request merged**
