### PR TITLE
builtin: add Ordering enum for comparison result

### PR DESCRIPTION
**Pull request by remimimimi**

### CODE REVIEW

**Comment by spytheman** [comment]
I do not see the point of that. Returning a negative integer, 0 or a positive integer for sort comparison functions is very common across programming languages. What would requiring a specific enum to be used instead bring except another level of indirection/complication?

**Comment by remimimimi** [comment]
Very common != actually a good design decision. It's like using 0 and 1 for bool in C. The specific enum is needed to make it easier to pass around Orderings as opposed to just numbers because match statement will ensure that you handled all the variants. Plus you can not mix up a number with an ordering. @spytheman

**Comment by spytheman** [comment]
I have not experienced the need to pass Orderings whatever that means, and I think such a thing should not be part of every V program, also sort callbacks become harder to write with this PR.

@medvednikov what do you think?

Should sort callbacks return simple negative/0/positive values, or specific values from a specific new enum instead?

**Comment by Gladear** [comment]
Using integers allow to do things like
`str_a.len - str_b.len` to order strings by length, it is very handy, I personally use it all the time

**Comment by medvednikov** [comment]
These are internal functions (although `fn compare_strings` is public, it shouldn't be).

I don't see any reason to change those.

**Pull request closed without merging**
