### PR TITLE
parser: fix handling of `-` inside array literals

### PR DESCRIPTION
**Pull request by UweKrueger**
V has been accepting array initializations without commata a while now:
```v
a := [1 2 7 2]
```
However this syntax used to produce unexpected results in case of negative numbers, i.e.
```v
a := [3 -4 5]
```
has been read as `a := [(3 - 4), 5]`.

This PR fixes this by taking into account if there is a space after the minus sign (and before - so `[3-2,4,5]` is still an array with 3 elements). This is consistent with what [Julia](https://julialang.org/), [Matlab](https://www.mathworks.com/products/matlab.html), [Octave](https://www.gnu.org/software/octave/) and [GNU Emacs Calc](https://www.gnu.org/software/emacs/manual/html_node/calc/index.html) do.

Other ambigous operators (`&`, `*`, `<-`) are treated the same for consistency.

Unfortunately it's not possible to add a functional test case for this since `vfmt` inserts commata - and unformatted test cases are not accepted any more. So a `vfmt` test case is added, instead (edited).

### CODE REVIEW

**Comment by Gladear** [comment]
I may be wrong, but I think v for doesn't insert commas if the array is spread on multiple lines, which could enable you to add a test

**Comment by UweKrueger** [comment]
> I may be wrong, but I think v for doesn't insert commas if the array is spread on multiple lines, which could enable you to add a test

Yes, but it would not be a good test, either, because line breaks inside array literals are treated special, too.

**Comment by Gladear** [comment]
Hmm, right. However, this gave me another idea.
You could add a `v fmt` test. If `[1 -2]` gets formatted to `[1, -2]`, this is fine, if it doesn't (e.g. `[1 - 2]`) it means the parsing failed

**Comment by UweKrueger** [comment]
> You could add a `v fmt` test. If `[1 -2]` gets formatted to `[1, -2]`, this is fine, if it doesn't (e.g. `[1 - 2]`) it means the parsing failed

Something like this came into my mind, too. It's somewhat indirect but it would at least shaw that the parser works correctly.

**Pull request merged**
