### PR TITLE
i add Dockerfile with the same docker container that golang use, safe , faste, secure

### PR DESCRIPTION
**Pull request by anagobabatunde**
Please title your PR as follows: `adding docker`.
changing -std arguemnt to c++11 because gnu11 doesn't work with docker
adding docker file to run vlang in container
updating readme
using same container that golang use

### CODE REVIEW

**Comment by elimisteve** [comment]
Why all the added newlines?

**Comment by anagobabatunde** [comment]
Excuse me it's my editor that added newlines in the readme automatically

**Comment by anagobabatunde** [comment]
Added clang to compile with gnu11

**Comment by anagobabatunde** [comment]
it's ok i fix all bug

**Comment by medvednikov** [comment]
Can you update this: `github.com/anagobabatunde/v`?

**Comment by anagobabatunde** [comment]
sorry , Yes, I just changed it.

**Comment by medvednikov** [comment]
I don't have Docker, can anyone test this please? Thanks.

**Comment by ComlanGiovanni** [comment]
i test it , it's work, good job

**Comment by ComlanGiovanni** [comment]
Screenshot_20190718_215606

**Comment by medvednikov** [comment]
Noob question: this doesn't fetch any containers from an external repository, right?

It just runs the commands in the RUN section.

**Comment by anagobabatunde** [comment]
yes, it executes all commands that are in RUN

**Comment by anagobabatunde** [comment]
can you add me as a contributor so that I can regularly update and improve my dockerfile?

**Pull request merged**
