### PR TITLE
io: buffered line-reader

### PR DESCRIPTION
**Pull request by mobarski**
High performance buffered line-reader with interface similar to golang's bufio.Reader.
Default buffer settings (128KB of initial buffer) are good for reading large-ish files (~500MB) and having intuitive interface (will read line as long as your RAM can handle).

example use:
```v
import os
import io

f := os.open('example.txt') ?
mut r := io.new_reader(file:f) ? 
for {
	line,_ := r.read_line() or { break }
	println('> $line')
}
```

other examples of initialization:
```v
// filename instead of a file
mut r := io.new_reader(filename:"foo.txt") ?

// with initial buffer length of 512 bytes
mut r := io.new_reader(file:f, buf_len=512) ?

// with maximum buffer length of 16MB
mut r := io.new_reader(file:f, buf_max=16*1024*1024) ?
```

### CODE REVIEW

**Comment by JalonSolov** [comment]
One conflict to resolve.  Anything else holding this up?

**Comment by emily33901** [comment]
Can we call this `BufferedReader` or similar instead of just `Reader` since we are probably going to want some interface like go's reader

**Comment by Larpon** [comment]
I think CI might just need a re-run here?

**Comment by Delta456** [comment]
Closing as superseded PR is made by @emily33901 https://github.com/vlang/v/pull/6754

**Pull request closed without merging**
