### PR TITLE
ui: increase ui module level in vlib

### PR DESCRIPTION
**Pull request by yuyi98**
This PR increase ui module level in vlib.
```v
ui.clipboard
ui.eventbus
ui.fontstash
ui.freetype
ui.gg
ui.gg2
ui.gl
ui.glfw
ui.glm
ui.gx
ui.sdl
ui.sokol
ui.stbi
ui.uiold
```
This makes the layers of the library clearer.

### CODE REVIEW

**Comment by spytheman** [comment]
picoev & picohttpparser have nothing to do with ui

**Comment by spytheman** [comment]
uiold is obsolete

**Comment by spytheman** [comment]
eventbus && clipboard also are not related to ui (at least they are not graphical) in my opinion

**Comment by spytheman** [comment]
As for the rest of these, v already has a ui module installable with `v install ui` - https://github.com/vlang/ui. 

I think putting the other modules under a ui common title will be confusing.

**Comment by yuyi98** [comment]
`https://github.com/vlang/ui`.  I think vui is better than ui for v ui.

**Comment by medvednikov** [comment]
Agreed with @spytheman.

None of these are UI modules. And there's `v install ui`.

**Comment by medvednikov** [comment]
`gg`, `gl`, `glfw` are for graphics rendering, doesn't have to be UI.

Clipboard can be used for anything, not just UI, etc.

**Pull request closed without merging**
