### PR TITLE
checker: rename `check_expr_opt_call` to `check_expr_result_call`

### PR DESCRIPTION
**Pull request by steven-mathew**
Renames `check_expr_opt_call` function to match the behavior since only the `.result` flag is cleared.

### CODE REVIEW

**Comment by shove70** [comment]
No, check both.
For historical reasons (splitting optional into optional and result), there are places in the system where `opt` is used to refer to both.

**Comment by spytheman** [comment]
@shove70, @steven-mathew how about `check_expr_opt_call` -> `check_expr_option_or_result_call` ?

**Comment by shove70** [comment]
> @shove70, @steven-mathew how about `check_expr_opt_call` -> `check_expr_option_or_result_call` ?

yep, this is reasonable

**Comment by shove70** [comment]
@steven-mathew You can change it to `check_expr_option_or_result_call`, as spytheman's suggests

**Comment by spytheman** [comment]
The CI failure is unrelated. Excellent work.

**Review by spytheman — APPROVED** [review]

**Pull request merged**
