### PR TITLE
math: Add uint module

### PR DESCRIPTION
**Pull request by playXE**
uint128 implementation is based on https://github.com/lukechampine/uint128

### CODE REVIEW

**Comment by changrui** [comment]
Why not `i128` and 'u128'?

**Comment by JalonSolov** [comment]
Agree - these will complete the missing pieces that have been documented in V - `i128` and `u128`.  That also implies this support should be in `builtin` module, same a `i64`, `u64`, etc.

**Comment by spytheman** [comment]
rebased over current master (that has the fix for `bits.div_64`)

**Comment by playXE** [comment]
> Agree - these will complete the missing pieces that have been documented in V - `i128` and `u128`. That also implies this support should be in `builtin` module, same a `i64`, `u64`, etc.

@JalonSolov @changrui i128 and u128 would require compiler support and they are not available for all targets and usually require compiler runtime in order to work while `math.uint` will be fully cross-platform and will not require special compiler handling. Once i128 and u128 get into V we could simply use `math.uint.Uint128` when i128 or u128 are not supported by some target (i.e -wasm32-unknonw-unknown with -ffreestanding does not support i128 and u128)

**Pull request merged**
