### PR TITLE
util: fix an wrong in path analysis when parsing 'mod_name'(fix #18970)

### LINKED ISSUE #18970: v fmt add dot to constant name and make its treated like an enum
### Describe the bug

I dont know, its happen only to me, or just my foolishness, or others have an issue too..but i can reproduce it in my environment.
The bug of v formatter, happen in project tree in `v.mod` mode where run `$v fmt -w .` to format all files, its changes constant name in respective file where they defined by adding dot (.) to the constant name, and make its like an enum. When its happen, its can lead horrible fail of tests or builds.
see attached files for example.

### Expected Behavior

its just format it, or..add the module name in front of constant name.
example: constant `max_hadiah_amount` after ` v fmt` would not change or changes it to `modulename.max_hadiah_amount` ...

### Current Behavior

Its change constant name by adding dot . in front of the name.
similar like this ```max_hadiah_amount``` become ```.max_hadiah_amount```

### Reproduction Steps

make v project folder structure by run `v init` or others.
my `$tree` of simple reproducer 
```tree
├── src
│   ├── aa.v
│   ├── bb.v
│   └── beer.v
└── v.mod
2 directories, 4 files
```

 i'm attach 3 unformatted files as an example how i reproduce its. dont look at the content or logic. its a bull. [src.zip](https://github.com/vlang/v/files/12168061/src.zip)

run `$v fmt -w .` from top level project dir, and see at constant name before and after running `v fmt -w .`
Maybe someone has a similar issues, 

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### V version

```$ v version V 0.4.0 5ecbfb7```

### Environment details (OS name and version, etc.)

```$ v doctor
V full version: V 0.4.0 c2dc1ca.5ecbfb7
OS: windows, Microsoft Windows 10 Home Single Language v19045 64-bit
Processor: 2 cpus, 64bit, little endian, 

getwd: C:\msys64\home\reguler\beer
vexe: C:\msys64\home\reguler\github\v\v.exe
vexe mtime: 2023-07-26 04:38:06

vroot: OK, value: C:\msys64\home\reguler\github\v
VMODULES: OK, value: C:\msys64\home\reguler\.vmodules
VTMP: OK, value: C:\msys64\tmp\v_0

Git version: git version 2.37.1
Git vroot status: weekly.2023.28-88-g5ecbfb7b-dirty
.git/config present: true

CC version: cc (Rev3, Built by MSYS2 project) 12.1.0
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620```

### PR DESCRIPTION
**Pull request by shove70**
Fix issue: #18970 

But I couldn't find a good way to write test cases, so I continued to try...

### CODE REVIEW

**Comment by spytheman** [comment]
> But I couldn't find a good way to write test cases, so I continued to try...

Me too :-| . In fact, that is the main problem with changes to that cursed file...

**Comment by spytheman** [comment]
To me the change seems logical (using a longer name is perhaps more likely for it to be a fully qualified name), but since there are no tests or a spec that details what should and what should not be supported, that thought is just a heuristic, and I do not know if it will not break more code than it will help.

**Comment by shove70** [comment]
> To me the change seems logical (using a longer name is perhaps more likely for it to be a fully qualified name), but since there are no tests or a spec that details what should and what should not be supported, that thought is just a heuristic, and I do not know if it will not break more code than it will help.

Hmm, I simulated various situations on this machine for manual testing, which seems normal, but I am also worried about the issues you are concerned about

**Comment by spytheman** [comment]
I think the main problem is caused by the double meaning of "relative", when it comes to files:
  1) a path can be relative to the current working folder.
  2) a path can be relative to the current file/module etc.

(1) is a problem, since the compiler can be launched in different situations in different working folders, compiling the same exact code (that does not move) on the same machine.
For example you can do `v .` manually, or `v ~/.vmodules/some_project`, or use an IDE that does `v /full/path/to/some_project`, and to me they all should work exactly the same, given the same project, but currently that is not the case.

(2) is usually not subject to additional user input, unless the project is moved.

**Comment by shove70** [comment]
👍 It makes sense!

**Pull request merged**
