### PR TITLE
json: support system cJSON library through pkgconfig

### PR DESCRIPTION
**Pull request by davidebeatrici**
We have to either wait for the next cJSON release or add a symbol check before merging: DaveGamble/cJSON#697

### CODE REVIEW

**Comment by spytheman** [comment]
It should not be the first choice/the default. The system provided cJSON library may be much older than what V expects.

You can use `$if system_cjson ? {` to surround the check, if you do want to support it as an option.

**Comment by davidebeatrici** [comment]
https://github.com/vlang/v/blob/fcde63127fdf7588cb54360ee25f4be96cbd5e2b/thirdparty/cJSON/cJSON.h#L81-L84

The latest version is currently 1.7.15, but `cJSON_GetErrorPos()` is missing because not upstreamed yet.

I agree that adding an option is probably the best solution right now.

**Comment by medvednikov** [comment]
We prefer static linking for binaries generated by V. Especially for something that's part of the language.

**Comment by davidebeatrici** [comment]
Understandable, the upstream pull request is not merged yet anyway.

**Pull request closed without merging**
