### PR TITLE
vweb: straight forward middleware implementation

### PR DESCRIPTION
**Pull request by Terisback**
Basic implementation of middleware *guards*, with that you cannot call **next** handler and see what result is, but some basic auth stuff should work.

Works like a charm:
```v
module main

import net.http
import vweb

struct App {
	vweb.Context
}

fn (mut app App) index() vweb.Result {
	return app.text('Hello from index handler')
} 

['/:some...']
fn (mut app App) some(some string) vweb.Result {
	return app.text('Hello from some handler')
}

['/'; use]
fn (mut app App) index_mid() {
	if 'hello' in app.query {
		app.done = true
		app.conn.write(http.new_response(
			status: .ok
			text: 'Hello from index middleware'
		).bytes()) or {}
	}
}

['/:some...'; use]
fn (mut app App) mid(some string) {
	if 'hello' in app.query {
		app.done = true
		app.conn.write(http.new_response(
			status: .ok
			text: 'Hello from some middleware $some'
		).bytes()) or {}
	}
}

['/exact'; use]
fn (mut app App) exact_mid() {
	app.done = true
	app.conn.write(http.new_response(
		status: .ok
		text: 'Hello from middleware with `exact` path'
	).bytes()) or {}
}

fn main() {
	vweb.run(App{}, 8089)
}
```
vweb-middleware-demo

### CODE REVIEW

**Comment by Terisback** [comment]
I will write the proper tests for this "later"

**Comment by spytheman** [comment]
what does `use` mean in this context?
I do not understand the motivation for this functionality. Can you provide some description/documentation?

**Comment by Terisback** [comment]
In web frameworks `use` is usually used to assign middlewares.
Motivation, guard some paths with authorisation, like if we have whole route 
/admin
  /delete-world 
  /... and 5 more routes which can only be accessed by admin
in this case you just make one guard for `/admin` path, and check jwt, session, login+pass.

**Comment by danieldaeschle** [comment]
It is strange imo and ai don‘t realle like it. With this proposal it would be way better: https://github.com/vlang/v/discussions/11732

**Comment by dumblob** [comment]
From my experience this is handy only for the most simplified scenarios. And even there I wouldn't recommend it as it's a dead end :cry:.

Always when I needed some advanced user management (especially with overlapping roles, login permissions based not only on the identity but also the state of the web application, etc.) this all was not just insufficient but also a burden to rewrite because it didn't play nicely with the finer-grained authentication infrastructure.

**Comment by JalonSolov** [comment]
Any updates?

**Comment by ylluminate** [comment]
Friendly ping...

**Comment by vladimirmyshkovski** [comment]
It seems to me that it would be more logical to pass a function returning `bool` instead of `use`, and use that function as `middleware`.

**Comment by Terisback** [comment]
@vladimirmyshkovski you are right)

**Comment by vladimirmyshkovski** [comment]
@Terisback @medvednikov @dumblob @spytheman  does it make sense to implement `middleware` in a similar way as proposed in this PR, but using a function that returns `bool` in the place where `use` is now used? I can do that.

**Comment by ArtemkaKun** [comment]
@Terisback Hi, is this still actual? Should somebody from the community rebase this PR and try to merge it (in case you don't have time/are not interested in it anymore)

@vladimirmyshkovski Have you managed to complete this implementation?

**Comment by medvednikov** [comment]
@vladimirmyshkovski sounds good.

**Pull request closed without merging**
