### PR TITLE
WIP: Azure Pipelines CI/CD setup

### PR DESCRIPTION
**Pull request by itsbalamurali**
Azure DevOps Pipelines offers multi-platform infrastructure building and testing (free for open source)
mainly:
-  Windows
-  Linux
-  macOSX

Current setup (org will be dedicated to the vlang team): https://dev.azure.com/vlanguage/v/_build/results?buildId=6

Currently, the builds are failing due to a know segfault in the v compiler.

The idea is to be able to Test, Build and Ship the v compiler suite via CI/CD setup preferably Azure DevOps and also enable CI checks on pull requests.

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks a lot! This is super useful.

How much does this cost? Couldn't find the pricing.

**Comment by itsbalamurali** [comment]
@medvednikov it's free for open source. https://github.com/marketplace/azure-pipelines. I will transfer the existing Azure DevOps organization ownership to you later once the PR is complete.

**Comment by medvednikov** [comment]
Wow. Microsoft has changed :)

Thank you very much for this!

**Comment by medvednikov** [comment]
You only added one file, but it complains about conflicts. Is this because of the segfault?

**Comment by itsbalamurali** [comment]
@medvednikov I don't see any conflicts.

image

**Comment by medvednikov** [comment]
Screen Shot 2019-06-24 at 12 41 36

**Comment by itsbalamurali** [comment]
@medvednikov let me open another PR.

**Comment by itsbalamurali** [comment]
new PR: https://github.com/vlang/v/pull/508

**Pull request closed without merging**
