### PR TITLE
[WIP] term: Fix: error: functions with type only args can not have bodies

### PR DESCRIPTION
**Pull request by esquerbatua**
This PR fix the error: "error: functions with type only args can not have bodies"
And creates a new fn imax in math and use it over repeated versions in vlang/vlibs

### CODE REVIEW

**Comment by JalonSolov** [comment]
I think `imax` would be better as `intmax` or even `int_max`.  It's not a type of theater, it's an integer maximum.

Can't use `maxint` because that could be confused with the MAXINT constant, and `maxi`... sounds like a feminine hygiene product...

**Comment by esquerbatua** [comment]
@spytheman I don't know if actually that changes are needed, the fail that I was trying to solve actually it's working.
I don't know also if the fn min and max for ints are intended to be out of the math method and use it everywere.
Thanks by advance!

**Comment by spytheman** [comment]
Personally I do not like importing the whole of the math module for just imax/imin, because on some platforms, math requires math.h and linking with -lm on the C side, while imax/imin can be implemented with pure v code without a problem.
It is a code duplication indeed, but I think the benefit of not having to deal with `math` is worth it.
@medvednikov what do you think?

**Comment by JalonSolov** [comment]
That sounds like a good optimization, @spytheman - don't bring in extra unless you really need it.  In fact, a short routine like that can be declared locally, and with [inline] just to make the resulting code even more compact.

**Comment by esquerbatua** [comment]
Maybe make other file with only that two functions to the whole module building to prevent import the math.h?

**Pull request closed without merging**
