### PR TITLE
fix: nreadelements naming

### PR DESCRIPTION
**Pull request by thecodrr**
It was giving an error that `nreadelements` should be `n_read_elements`, so fixed that.

### CODE REVIEW

**Comment by medvednikov** [comment]
The limit was changed to 15, so you must have an old version.

Also in V the convention is to use `nr_xxxx`

**Comment by thecodrr** [comment]
@medvednikov Actually, in the last PR by @prime31 that fixed the `read_bytes` function, he forgot to name `nreadelements` as `n_read_elements`. Maybe it was just my system giving the error but I couldn't run the tests (after rebasing to latest) until after I changed this.

**Comment by medvednikov** [comment]
CI is green, everything works fine on my machine as well.

`os` module is used by the compiler.

**Comment by medvednikov** [comment]
try `git pull --rebase && make`

**Comment by thecodrr** [comment]
Hm. Then it must have been a wrong warning...

**Comment by medvednikov** [comment]
Anyway I'll merge this once you rename it to `nr_read_elements` :)

**Comment by thecodrr** [comment]
Done.

**Pull request merged**
