### PR TITLE
fmt: remove space in front of ? and !

### PR DESCRIPTION
**Pull request by danieldaeschle**
before:
```v
foo() ?
```
after:
```v
foo()?
```

### CODE REVIEW

**Comment by danieldaeschle** [comment]
Wondering why so many additional lines and less new lines. 🤔

**Comment by danieldaeschle** [comment]
> Wondering why so many additional lines and less new lines. 🤔

regex_test fmt for example resulted in this.

**Comment by spytheman** [comment]
Revert the fmt changes to files mentioned in `cmd/tools/vtest-cleancode.v` .

**Comment by danieldaeschle** [comment]
thank you :)

**Comment by danieldaeschle** [comment]
That shitty CI xD

I hate it.

**Comment by spytheman** [comment]
`regex_test.v` is still formatted, but it should not be :-| .

**Comment by spytheman** [comment]
> That shitty CI xD
> 
> I hate it.

me too - hopefully the other PR will improve the situation

**Comment by danieldaeschle** [comment]
image

**Pull request merged**
