### PR TITLE
gg: add draw_ellipse() + draw_ellipse_empty() APIs

### PR DESCRIPTION
**Pull request by BenStigsen**
image

```v
import gg
import gx
import math

struct App {
mut:
	gg     &gg.Context
}

fn main() {
	mut app := &App{
		gg: 0
	}
	
	app.gg = gg.new_context(
		width: 200
		height: 200
		window_title: 'Draw Ellipse'
		frame_fn: frame
		user_data: app
	)
	
	app.gg.run()
}

fn frame(mut app App) {
	app.gg.begin()
	app.gg.draw_ellipse(100, 100, 100, 50, gx.red)
	app.gg.draw_empty_ellipse(100, 100, 50, 25, gx.black)
	app.gg.end()
}
```

### CODE REVIEW

**Comment by spytheman** [comment]
(rebased over current master; moved the new functions to `gg.c.v`)

**Comment by JalonSolov** [comment]
Same naming thing as discussed on discord... if it was `draw_ellipse` and `draw_ellipse_empty` it would be better for sorting and code completion, keeping all `draw_ellipse*` methods next to each other.

**Comment by BenStigsen** [comment]
So it is official? We do the renaming to the `gg` library? I can go ahead and do this at one point, then make it work with UI and the test file.

**Comment by BenStigsen** [comment]
Should `gg.draw_ellipse()` be called `gg.draw_ellipse_filled()`?

**Comment by JalonSolov** [comment]
I'd rather see it the other way around, really... I expect `draw_ellipse` to draw an empty ellipse, and `draw_ellipse_filled` to draw one filled in.  Or, to beat a dead (or seems to be at least dying) horse... `draw_ellipse` should take options for how to draw, including filled or not, then have "helper" functions like `draw_ellipse_empty` and `draw_ellipse_filled` that set options for you.

**Comment by BenStigsen** [comment]
I think it would make more sense to just be explicit with both 
`draw_ellipse_empty()`
`draw_ellipse_filled()`

**Comment by JalonSolov** [comment]
And my argument there is that it would be good to have a `draw_ellipse` that took options, because it will be simpler to use at runtime if you want to _change_ how things are drawn at runtime.  Could just call the same routine with different options, instead of having a big "if/else" block to decide which separate routine to call.

The individual "helper" routines would just set the correct options for you then call the base `draw_ellipse` (or `draw_<whatever shape>`) routine.

**Comment by BenStigsen** [comment]
Being able to pass a config would definitely make sense at some point, this would also allow for options about anti-aliasing, gradients and so on, but for the functions as the are right now.
Should they renamed from:
`draw_empty_triangle()`
`draw_triangle()`

To:
`draw_triangle_empty()`
`draw_triangle_filled()`
?

**Comment by spytheman** [comment]
This PR is only for the new 2 functions and I would be happy with any names for them (the current ones look good to me too).
The renaming of the rest can be done in another PR imho.

**Comment by BenStigsen** [comment]
Okidoki, are more tests needed or can ot be merged?

**Comment by spytheman** [comment]
I am waiting for the `Code CI / alpine-musl` to pass (it failed last time), and I will merge it.

**Comment by JalonSolov** [comment]
If you want to allow for the more flexible approach, then `draw_ellipse` should be renamed to `draw_ellipse_filled` to avoid a breaking change later.

**Pull request merged**
