### PR TITLE
all: batch application the new interpolation (for verification)

### PR DESCRIPTION
**Pull request by shove70**
This PR is used to continuously verify the correctness and stability of new interpolation.

### CODE REVIEW

**Comment by JalonSolov** [comment]
The failure appears to be a CI setup error, not any problem with this change.

**Comment by shove70** [comment]
It seems OK. The following forms cannot be converted temporarily:

```
1. other_expr('{foo. jin (' ')}')   Nested quote inside an expr
2. '{foo:10}'   has a format specifier
3. '{@LINE}'    compile time variable
```

**Comment by spytheman** [comment]
I think that merging this will be a huge mistake at this point in time, the new {} interpolation is not stable enough, and is constantly being "fixed" still.

@medvednikov merge it if you want, but please note, that it will make reverting to the sane `${}` interpolation that already does work harder :-| .

**Comment by shove70** [comment]
> I think that merging this will be a huge mistake at this point in time, the new {} interpolation is not stable enough, and is constantly being "fixed" still.
> 
> @medvednikov merge it if you want, but please note, that it will make reverting to the sane `${}` interpolation that already does work harder :-| .

OK, I understand your concern. It doesn't matter if the PR is not merged. I can constantly verify new interpolation through it
😄

**Comment by medvednikov** [comment]
@spytheman I agree.

**Comment by medvednikov** [comment]
Great work @shove70

**Pull request closed without merging**
