### PR TITLE
examples: minor optimization of calculator

### PR DESCRIPTION
**Pull request by SleepyRoy**

### CODE REVIEW

**Comment by medvednikov** [comment]
What was the typo?

**Comment by SleepyRoy** [comment]
@medvednikov file name regex_with_memoization.v lol

**Comment by JalonSolov** [comment]
That's not a typo.  https://en.wikipedia.org/wiki/Memoization

**Comment by SleepyRoy** [comment]
@JalonSolov Hmmm...I used to think it was. Good to know the fact.

**Comment by JalonSolov** [comment]
Memorization is also a valid word, just not what was meant here:  <https://en.wikipedia.org/wiki/Memorization>

**Pull request merged**
