### PR TITLE
compiler: streamline main function handling

### PR DESCRIPTION
**Pull request by spytheman**
The v main function is now translated as an ordinary v module function.
It is now named main__main in the generated C code.
It is treated like all the other v functions more or less.
This simplifies the generation of the C main() ( and in turn enables moving the -live implementation nearly completely into an ordinary v module on a next stage)

### CODE REVIEW

**Comment by spytheman** [comment]
Travis is failing again. I do not know why ...

**Comment by medvednikov** [comment]
just windows/gcc

it's been failing for a couple of days now, memory issues

will fix once my memory work is complete later this week

**Comment by joe-conigliaro** [comment]
@spytheman theres a memory bug, it only affects GCC / windows.

**Comment by medvednikov** [comment]
@spytheman 2 conflicts.

Sorry, couldn't merge right away due to broken master.

**Comment by spytheman** [comment]
Rebased over current master and solved conflict in compiler/scanner.v

**Pull request merged**
