### PR TITLE
Updated gg.draw_rect to gg.draw_rect_filled

### PR DESCRIPTION
**Pull request by nikeedev**
Cause why not? :)

### CODE REVIEW

**Comment by Larpon** [comment]
The existing code is shorter and is part of a an example about variable shadowing - making it more verbose is needless noise the reader has to filter out when reading it. I don't see a need for this particular change

**Comment by spytheman** [comment]
I agree, that the existing code is shorter, and that the focus is on demonstrating the feature (although the feature itself (module name shadowed by a local variable), imho needs to be removed, since it leads to confusion).

**Comment by spytheman** [comment]
@nikeedev thanks for the PR anyway, if you do spot another problem, do not be discouraged to post about it and make another PR.

**Comment by nikeedev** [comment]
> @nikeedev thanks for the PR anyway, if you do spot another problem, do not be discouraged to post about it and make another PR.

Okay, thanks!

**Pull request closed without merging**
