### PR TITLE
vlib/x/crypto: add poly1305 message authentication code (mac) in pure v 

### PR DESCRIPTION
**Pull request by blackshirt**
This is our third attempt to contribute more broadly and usefully to the vlang community. In this pull request, we propose a new module, named `poly1305`, Poly1305 message authentication code (MAC) in pure v to the experimental namespaces `vlib/x/crypto`. See [poly1305](https://cr.yp.to/mac/poly1305-20050329.pdf.) for more detail.

This module was inspired mostly by the go version of the same module, and tries hard to keep up with the go version, but with some slight differences in places and adding some comments to the existing code to make it easier for other developers and community members to learn and read.

The differences includes:
- Differences in the name of the public api provided, favouring the public implementation of [poly1305-donna](https://github.com/floodyberry/poly1305-donna)
- Using a custom allocator in the form of a `Uint192` structure representing 192 bits unsigned integer, which is fundamentally and functionally the same as in the go version, with its `[3]u64`. This can be extended or added to `math.unsigned` if needed. See `custom.v` for more details.
- Using some of the structures, functions and methods from standard vlib of the `math.unsigned` module, this also serves as a test bed for standard vlib, especially the `math.unsigned` module.

So, please give us a review, feedback, criticism or suggestions would be greatly appreciated.
thanks to everyone

Update: 
- This is second effort after my bad mistakes in [mistakenly-closes-pr](https://github.com/vlang/v/pull/20745#event-11733847949)
- There are two issues that cannot be resolved at this time, but will be updated in the next iteration., first is about additional usage test [usage test](https://github.com/vlang/v/pull/20745#discussion_r1481429374) from @spytheman  and the second is about using fixed-sized bytes array for [key setup](https://github.com/vlang/v/pull/20745#discussion_r1481185384) from @spytheman , @Larpon ... 
- Btw, thanks for reviewing it ..for guide to restore it (even its hard), so i choose to reopen a new PR 

New update
- I have sent updates to this PR, at [50d98e4](https://github.com/vlang/v/pull/20752/commits/50d98e42a4c239dab63d38497b5b84048059a0d9) with some bits of changes, 
- Add examples section in README files
- Add an `usage_test.v` file to test public API ... its address some advices from @spytheman, [see](https://github.com/vlang/v/pull/20752#issuecomment-1935475172)
- Some bits of restructuring and make it more simple
- Add test to incremental `.update` of Poly1305 instance, copied and adapted from [poly1305_power_on_self_test](https://github.com/floodyberry/poly1305-donna/blob/master/poly1305-donna.c#L84)

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by Larpon** [comment]
Thanks for contributing.

**Comment by spytheman** [comment]
@blackshirt, I'll wait until `usage_test.v` that tests only the public API is pushed here, before merging it.

**Comment by blackshirt** [comment]
> @blackshirt, I'll wait until `usage_test.v` that tests only the public API is pushed here, before merging it.

i have sent updates to this pr

**Comment by blackshirt** [comment]
> Good work.



> Good work.

Thank guys ..

**Pull request merged**
