### PR TITLE
cgen: fix filter in map

### PR DESCRIPTION
**Pull request by danieldaeschle**
Fixes https://github.com/vlang/v/issues/7793

### CODE REVIEW

**Comment by danieldaeschle** [comment]
why is CI failing? i didn't change anything related.

**Comment by StunxFS** [comment]
> why is CI failing? i didn't change anything related.

```
Run ./v run cmd/tools/check-md.v -all
builder error: cannot import module "mymod.sha256" (not found)
/tmp/check_docs_md_example_1253__1260__01EV4YY5EDFZQ8VX5Q9HETEJP0.v is not vfmt'ed
Encountered a total of: 1 errors.
./tutorials/building-a-simple-web-blog-with-vweb.md:238:105: warn: long V example line
./doc/docs.md:1254:1: error: example is not formatted
struct Foo {
	n   int // n is 0 by default
	s   string // s is '' by default
	a   []int // a is `[]int{}` by default
	pos int = -1 // custom default value
}

./tutorials/building-a-simple-web-blog-with-vweb.md:240:106: warn: long V example line
./tutorials/building-a-simple-web-blog-with-vweb.md:399:102: warn: long link
./tutorials/building-a-simple-web-blog-with-vweb.md:405:109: warn: long link
./vlib/sync/bench/results.md:21:113: warn: long table
./vlib/sync/bench/results.md:22:112: warn: long table
./vlib/sync/bench/results.md:23:112: warn: long table
./vlib/sync/bench/results.md:24:112: warn: long table
./vlib/sync/bench/results.md:25:112: warn: long table
./vlib/sync/bench/results.md:26:112: warn: long table
./vlib/strconv/format.md:47:103: warn: long table
./vlib/strconv/format.md:48:161: warn: long table
./vlib/strconv/format.md:49:211: warn: long table
./vlib/strconv/format.md:81:118: warn: long table
./vlib/strconv/format.md:82:140: warn: long table
./vlib/strconv/format.md:84:126: warn: long table
./vlib/strconv/format.md:85:129: warn: long table
./vlib/strconv/format.md:86:128: warn: long table
./vlib/strconv/format.md:87:109: warn: long table
./vlib/strconv/format.md:187:138: warn: long code block line
./vlib/term/ui/README.md:94:160: warn: long link
./vlib/term/README.md:22:113: warn: long V example line
./vlib/term/README.md:24:108: warn: long V example line
./vlib/term/README.md:56:157: warn: long V example line
./vlib/x/websocket/tests/autobahn/README.md:15:105: warn: long link
./vlib/v/pkgconfig/README.md:64:301: warn: long code block line
./vlib/regex/README.md:389:107: warn: long V example line
./vlib/regex/README.md:494:102: warn: long V example line
./vlib/regex/README.md:495:104: warn: long V example line
./vlib/regex/README.md:547:120: warn: long V example line
./vlib/regex/README.md:666:102: warn: long code block line
./vlib/regex/README.md:667:103: warn: long code block line
./vlib/regex/README.md:668:103: warn: long code block line
./vlib/regex/README.md:680:102: warn: long code block line
./vlib/regex/README.md:681:102: warn: long code block line
./vlib/regex/README.md:683:103: warn: long code block line
./vlib/regex/README.md:684:103: warn: long code block line
./vlib/regex/README.md:685:103: warn: long code block line
./vlib/regex/README.md:686:103: warn: long code block line
./vlib/regex/README.md:767:108: warn: long V example line
./vlib/regex/README.md:768:110: warn: long V example line
./vlib/regex/README.md:772:102: warn: long V example line
./vlib/rand/README.md:65:148: warn: long link
./CONTRIBUTING.md:119:106: warn: long link
./README.md:3:118: warn: long link
./README.md:90:123: warn: long link
./README.md:92:107: warn: long link
./README.md:181:102: warn: long link
./README.md:247:133: warn: long link
./README.md:252:111: warn: long link
./README.md:256:142: warn: long link
./README.md:259:109: warn: long link
./README.md:260:141: warn: long link
./README.md:261:245: warn: long link
./README.md:268:134: warn: long link
./doc/docs.md:941:102: warn: long V example line
./doc/docs.md:1659:108: warn: long V example line
./doc/docs.md:2613:117: warn: long link
./doc/docs.md:2763:106: warn: long V example line
./doc/docs.md:2885:111: warn: long link
./doc/docs.md:2916:112: warn: long link
./doc/docs.md:2982:102: warn: long table
./doc/docs.md:2983:102: warn: long table
./doc/docs.md:2984:102: warn: long table
./doc/docs.md:2985:102: warn: long table
./doc/docs.md:2986:102: warn: long table
./doc/docs.md:3276:119: warn: long link
./examples/tetris/README.md:1:102: warn: long link
./examples/term.ui/README.md:1:108: warn: long link
builder error: cannot import module "mymodule" (not found)

Warnings: 69 | Errors: 1 | OKs: 140
```

**Comment by danieldaeschle** [comment]
yeah, i saw that. but that example is the same if i use vfmt

**Comment by danieldaeschle** [comment]
it fails on master as well

**Pull request merged**
