### PR TITLE
fix Byteptr to byte* error #584

### PR DESCRIPTION
**Pull request by kitech**

### CODE REVIEW

**Comment by medvednikov** [comment]
I think fixed this in one of my earlier commits. Can you test please?

**Comment by kitech** [comment]
Yes tested. I saw your fix here, https://github.com/vlang/v/commit/2a3cf0bec94b1312ac2ffdaa2ca4090a34c8b450

After your fix, it's not report this issue error message, but will generate error code, and also related to this issue. I think this issue need fix two place.

**Comment by kitech** [comment]
Example of this fix:

v code:
```
mut s = 'abcdef'
mut p = byteptr(s.str)
println(tos(p, s.len))
```

generated c code without this patch:
```
string s= tos2("abcdef") ;
byteptr p= (/*casttt*/ (byteptr)( /*77*/ s .str ) ) ;
println ( tos (& /*11 EXP:"byte*" GOT:"byteptr" */ p , s .len ) ) ; 
```
The last line generated code cause wrong result because of an extran `&`.

**Comment by ntrel** [comment]
Why do we even have byteptr? This is also related to (wrongly closed) https://github.com/vlang/v/issues/218. With true type aliases the compiler should treat them like the underlying type, without any special handling.

**Comment by medvednikov** [comment]
> With true type aliases the compiler should treat them like the underlying type, without any special handling.

Indeed.

This particular issue was resolved in a different commit.

**Pull request closed without merging**
