### PR TITLE
vdoc: fix syntax highlighting for symbols before `!` and between `(` and `,`

### PR DESCRIPTION
**Pull request by Delta456**
Fixes syntax highlighting 

| **Before** | **After** |
|--------|--------|
| image |  image | 

| **Before** | **After** |
|--------|--------|
| image |  image| 

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 522e83e</samp>

Improve symbol detection in `vdoc` tool. Handle cases where a token is preceded by a dot or a backtick.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 522e83e</samp>

* Add two cases for detecting symbols in the documentation generator: when the token is a type name or a module name ([link](https://github.com/vlang/v/pull/19888/files?diff=unified&w=0#diff-8fad233717d5242a053d169185e05f8fafe37c5bd976c13fa40d8c2efe6116a7L216-R222))

### CODE REVIEW

**Comment by spytheman** [comment]
This needs a test to prevent regressions too.

**Comment by spytheman** [comment]
I'll add one, since it is something, that could have been useful for @nedpals's https://github.com/vlang/v/pull/19785 and https://github.com/vlang/v/pull/19784 , and I do not want this PR to linger and be closed as well :-| .

**Comment by Delta456** [comment]
> This needs a test to prevent regressions too.

Should I proceed with using the `color_highlight` function for testing?

**Comment by Delta456** [comment]
> I'll add one, since it is something, that could have been useful for @nedpals's #19785 and #19784 , and I do not want this PR to linger and be closed as well :-| .

Sure

**Pull request merged**
