### PR TITLE
Use 'and' instead of '&' in error message

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by dhonx** [comment]
What is the reason behind that? Just curious

**Comment by iredmail** [comment]
> What is the reason behind that? Just curious

Clearer text.

**Comment by dhonx** [comment]
@iredmail Make sense...

**Comment by medvednikov** [comment]
& is a token in V, so for better readability `and` is better

**Comment by radare** [comment]
Closed (not merged)?

**Pull request closed without merging**
