### PR TITLE
mysql: Using `int.str()` instead of `string(int)`

### PR DESCRIPTION
**Pull request by dhonx**
Got a warning after update V compiler
```
vlib/mysql/result.v:53:4: error: use `number.str()` instead of `string(number)`
```
The problem after updating is this

### BEFORE
V Programming Language

### AFTER
V Programming Language

### CODE REVIEW

**Comment by elimisteve** [comment]
@dhonx As per https://github.com/vlang/v/commit/a0ca68ce3f50982186cc047d36fe8c846d2ff240 it looks like your commit is a good one

**Comment by spytheman** [comment]
string() converted C style strings to V style strings when used over byteptr.
The error is appropriate for other situations, where a number was passed.
Try using:
```v
row.vals << cstring_to_vstring( rr[i] )
```
... instead, and see if it will fix it (I do not have easy access to a mysql server right now and can not test it).

**Comment by spytheman** [comment]
Another possible fix, is if you use: `&&byte` instead of `&byteptr` in the declaration:
`pub fn (r Result) fetch_row() &byteptr {`

**Comment by spytheman** [comment]
Btw, imo it will be better, if instead of 
`pub fn (r Result) fetch_row() &byteptr {`
... we have:
`pub fn (r Result) fetch_row() Row {`
so that the raw byteptr's are not exposed to V users of this API.

**Comment by dhonx** [comment]
> @dhonx As per [a0ca68c](https://github.com/vlang/v/commit/a0ca68ce3f50982186cc047d36fe8c846d2ff240) it looks like your commit is a good one

Hihihi... Thanks man,,, :smile: 



> string() converted C style strings to V style strings when used over byteptr.
> The error is appropriate for other situations, where a number was passed.
> Try using:
> 
> ```v
> row.vals << cstring_to_vstring( rr[i] )
> ```
> 
> ... instead, and see if it will fix it (I do not have easy access to a mysql server right now and can not test it).

I try it before & got the same

**Comment by spytheman** [comment]
The musl CI failure is unrelated.

**Pull request merged**
