### PR TITLE
js: Use prefixed names for functions and global symbols

### PR DESCRIPTION
**Pull request by playXE**
This PR will make JS backend emit prefixed names for functions and global symbols. This will stop using methods in the JS backend which simplifies codegen and potentially improves performance since no more `Object.getPrototypeOf` will be involved to invoke methods of types.

### CODE REVIEW

**Comment by playXE** [comment]
At this point code is compiled to JS and no syntax errors are produced but most of V code compiled to JS will not work at all, there's still a lot of things to change to make it work.

**Comment by Gladear** [comment]
I thought about this, and if I understand correctly, not using methods has one downside: generics.

When using generics in JavaScript, currently, you can basically skip them and it should work.
If you stop using methods, generation of one function per call type will be required. Here's an example:

```v
fn generic<T>(a T) {
    a.call_method()
}
```

```js
// currently
function generic(a) {
    a.call_method()
}

// after change
function generic_MyStruct1(a) {
    MyStruct1_call_method(a)
}

function generic_MyStruct2(a) {
    MyStruct2_call_method(a)
}
```
I hope you get the idea, I feel like I've been unclear. Let me know if you need further explanation

**Comment by spytheman** [comment]
> When using generics in JavaScript, currently, you can basically skip them and it should work.
> If you stop using methods, generation of one function per call type will be required.

Imho, it is much better to have a unified strategy between the backends, than have little (or not so little) implementation quirks, that make pure code written in V, run in one of the backends, but not in the others.

**Comment by playXE** [comment]
> > When using generics in JavaScript, currently, you can basically skip them and it should work.
> > If you stop using methods, generation of one function per call type will be required.
> 
> Imho, it is much better to have a unified codegen strategy between the backends, than have little (or not so little) implementation quirks, that make pure code written in V, run in one of the backends, but not in the others.

@Gladear I agree with @spytheman. It is much easier to maintain a compiler when backends are similar. In the JS world we could use methods to simplify interfaces implementation but is it really worth using methods for generics? I don't think so.

**Comment by Gladear** [comment]
I do agree that similar backends are nice to have and probably make maintenance easier, but the generated JavaScript is, among others, made for browser, where bundle size is the crux. Web developers try to find the best tools to have the smallest file size possible. Duplicating functions and methods is counter-productive in that regard.

**Pull request merged**
