### PR TITLE
Update vhelp.v

### PR DESCRIPTION
**Pull request by nsauzede**
Minor help enhancements

### CODE REVIEW

**Comment by nsauzede** [comment]
hmmm Ok, but then it would a V subcommand, rather than an option ?
Do you want me to add a "version" subcommand, and keep -v and --version ?
It would be more than nice than to keep "--version", because it is oh-so standard everywhere else.. (gcc, python, make, bash, etc...)
No problem (to me) to keep all three (subcommand : as for "git version" "go version", etc..; and -v/--version, as for "gcc --version", "make --version")
what do you think ?

**Comment by medvednikov** [comment]
@nsauzede that's how it already works

-v, --version, version
-h, --help, help

they all work :)

**Comment by nsauzede** [comment]
ok; but then, version and help are both an option and a subcommand ? so they shoulb documented two times each ? o_O
BTW, why "subcommand" and not just.. "command" ?
Eg: v up is a command right ? Or you consider already "v" being a command (=the compiler), and such "v up" is the subcommand "up" of the command "v" ?

**Comment by medvednikov** [comment]
You are right, the current wording is confusing.

It shouldn't be "subcommands", and -o exe_name is definitely not a "debugging option".

I'll clean it all up today.

**Pull request merged**
