### PR TITLE
fixed : "C:\v\tools\vrepl.v" could not be compiled.

### PR DESCRIPTION
**Pull request by ahgm**
err:"V panic: V tool "C:\v\tools\vrepl.v" could not be compiled.
print_backtrace_skipping_top_frames is not implemented on this platform for now..."
it was my problem but temporarily i solved it better a better way

### CODE REVIEW

**Comment by spytheman** [comment]
It may be more robust, if the recompilation is retried in a loop, something like:
```
try_compilers := if os.user_os() == 'windows' { [ '', '-cc msvc', '-cc gcc'] } else { [ '', '-cc gcc', '-cc clang'] }
for ccompiler in try_compilers {
    // compile until succeeds, appending errors in an earray, instead of panic-ing, then break if it succeeds in producing an executable)
}
// check for final executable existance, and spit out the accumulated errors if it still does not
```
As it is, merging this PR, will break people that do not have msvc on windows.

Another easier option, that will not require code changes, is if you just set VFLAGS to `-cc msvc` in your environment. This will make it so v will always try to use msvc as its C backend.

**Comment by medvednikov** [comment]
@spytheman yes, and it should happen in cc.v for all V programs.

In fact it's better to detect whether a compiler exists, and then use it. Otherwise it'd try to build a program with an error over and over again if the system has different compilers.

**Comment by MahdiBaghbani** [comment]
Hi, I'm against your idea to hard-code a default compiler in V source code, and that's what you have actually did that led to this error, isn't it better to let users choose their preferred compiler at first place?

I agree with @spytheman on his last statement -cc msvc but it is a bit implicit and many users wouldn't be aware of this.

IMO possible ways to tackle this is to prompt and ask people of their desired compiler backend at first compile time, or adding a CLI command for changing V compiler backend (probably named --cc-backend)

**Comment by spytheman** [comment]
@MahdiBaghbani it already has it, it is named: -cc

**Comment by spytheman** [comment]
Or do you mean an option, that will change it permanently (i.e. stored in a configuration file somewhere, that v reads in addition to VFLAGS and its CLI options)?

**Comment by MahdiBaghbani** [comment]
@spytheman yes, i mean an option to change it permanently, -cc is a good choice but it's a bit annoying to write -cc msvc **every** time we want to compile a V source code on a windows machine where no gcc or clang installed, -cc is good for temporary use and comparing various backend output file to each other, but V **needs** to have an option to let the users config a default (permanent) c backend! this is not only limited to windows machines.

for example what if I want to use clang as default c backend in my Linux machine? or even using other backends which aren't as popular as gcc and clang? I have to write -cc each time! a default config can solve this problem for everyone and also would avoid missing compiler problems in auto detect compiler procedure, because the users **know** which compilers are installed on their machines.

**Comment by medvednikov** [comment]
@MahdiBaghbani this will be fixed in a different way.

V will detect MSVC/GCC installation and use the right compiler.

**Comment by spytheman** [comment]
@MahdiBaghbani personally, I solve this by putting:
`export VFLAGS='-cc clang-7 -g -keep_c' `
in my .bashrc .

**Pull request closed without merging**
