### PR TITLE
Vweb: add controllers

### PR DESCRIPTION
**Pull request by Casper64**
Vweb add ability to use controller so you are able to have one struct per `"/"`.  E.g. a struct `Admin` for urls starting with `"/admin"` and a struct `Foo` for urls starting with `"/foo"`

## Usage
In the following example all urls starting with `"/admin"` will be passed to the `Admin` struct and likewise all urls starting with `"/foo"` will be passed to `Foo`.

```v
module main

import vweb

struct App {
	vweb.Context
	vweb.Controller
}

struct Admin {
	vweb.Context
}

struct Foo {
	vweb.Context
}

fn main() {
	mut app := &App{
		controllers: [
			vweb.controller('/admin', &Admin{}),
			vweb.controller('/foo', &Foo{})
		]
	}
	vweb.run(app, 8080)
}
```

You can do everything with a controller struct as with the regular `App` struct. The only difference being is that only the main app that is being passed to `vweb.run` is able to have controllers. If you add `vweb.Controller` on a controller struct it will simply be ignored.

## Routing
Any route inside a controller struct is treated as a relative route to its controller namespace.

**Example:**
```v
['/']
pub fn (mut app Admin) home vweb.Result {
    return app.text('Admin')
}
```
When we created the controller with `vweb.controller('/admin', &Admin{})` we told vweb that the namespace of that controller is `"/admin"` so in this example we would see the text `"Admin"` if we navigate to the url `"/admin/"`.

## Speed results
In my limited testing we can see that the performance is barely effected by adding controllers:

Tested with `wrk -c 100 -t 4 -d 30s [url]` after letting the server do some with for about a minute.
```
Running 30s test @ http://localhost:8080/
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.22ms  421.06us  17.29ms   92.01%
    Req/Sec     4.03k   131.65     4.28k    69.50%
  481807 requests in 30.01s, 50.54MB read
Requests/sec:  16053.97
Transfer/sec:      1.68MB
===========================================================
Running 30s test @ http://localhost:8080/admin/
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.11ms  347.61us  11.68ms   79.70%
    Req/Sec     3.99k   228.83     4.40k    63.17%
  476937 requests in 30.01s, 53.22MB read
  Socket errors: connect 0, read 0, write 0, timeout 2
Requests/sec:  15891.23
Transfer/sec:      1.77MB
```
### Why not embed controller structs?
Each time a new connection is handled a fresh instance of App is created, if the controller structs are embedded they would also be reconstructed. Which is unnecesarry and a waste of memory since each controller has its own namespace and operates only within its namespace.

### So what about Shared data and `[vweb_global]`?

When a new request app is created the variables marked with `[vweb_global]` are copied to the new struct. If you want to also have it on other controllers you could just pass a copy of it to their contstructors and it's the same story with shared variables. This is already done by vweb internally when creating a new app instance for a request.

They are all constructed before the web server is ran. And since it remains optional you have more control over what variables you only want for one controller.

In my opinion, variables with the attribute `[vweb_global]` are meant to persist between each request, not necessarely contollers. And you could use a shared variable if you want to be able to mutate the data.

**Database example:**
```v
fn main() {
	mut db := sqlite.connect(database_path)!
	mut app := &App{
		db: db
		controllers: [
			vweb.controller('/admin', &Admin{
				db: db
			}),
		]
	}
}
```

### No fallback routes
In the current implementation if a route is defined twice or more, the route is only handled by the controller that handles the namespace.

**Example:**
```v
module main

import vweb 

struct App {
    vweb.Context
    vweb.Controller
}

struct Admin {
    vweb.Context
}

fn main () {
    app := &App{
        controllers: [
            vweb.controller('/admin', &Admin{})
        ]
    }
    vweb.run(app, 8080)
}

['/admin/page']
fn (mut app App) page() vweb.Result {
    return app.text('from app')
}
```

Even though there is a route defined for `"/admin/page"` the server will return 404, since there is no function with the route `"/page"` on the admin app. 

But this could easily be changed so that all undefined routes from a controller will be handled by the main app struct (maybe as a configuration option?)

Will add tests and documentation later.

### CODE REVIEW

**Comment by medvednikov** [comment]
Amazing work!

**Comment by enghitalo** [comment]
>In the current implementation if a route is defined twice or more, the route is only handled by the controller that handles the namespace

Why not return a error to avoid mistakes and/or bugs?

**Comment by Casper64** [comment]
> >In the current implementation if a route is defined twice or more, the route is only handled by the controller that handles the namespace
> 
> Why not return a error to avoid mistakes and/or bugs? And preserve the v's one single way rule. By the way, excellent work.

Good suggestion, I'll implement it

**Comment by medvednikov** [comment]
There's a small conflict after the workers PR was merged. Please resolve it, and I'll merge your PR asap @Casper64

**Pull request merged**
