### PR TITLE
vdoc: fix parsing of static functions

### PR DESCRIPTION
**Pull request by Delta456**
This PR fixes parsing of static functions for `vdoc`

| **Before** | **After** |
|--------|--------|
| image|  image| 

### <samp>🤖 Generated by Copilot at 82bc0c8</samp>

Refactored `stmt_name` function in `vlib/v/doc/utils.v` to use `get_name` method for `ast.FnDecl`. This improves the documentation of anonymous functions and methods.

### <samp>🤖 Generated by Copilot at 82bc0c8</samp>

* Refactor documentation generation for V code ([link](https://github.com/vlang/v/pull/19876/files?diff=unified&w=0#diff-e89b89f2e86d67496ebd7146e83d28b27420a52ea6231140909a896a39b00d57L134-R139),                              F30

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
The title should be `fn XmlDocument.from_file` .

**Review by spytheman — CHANGES_REQUESTED** [review]
The title should be `fn XmlDocument.from_file` .

**Comment by Delta456** [comment]
Also working on `v doc` terminal

image

**Review by spytheman — APPROVED** [review]

**Comment by spytheman** [comment]
It seems a bit weird that the static methods are sorted first, disconnected by all the rest, but it is much better than before.

**Pull request merged**
