### PR TITLE
Rewrite time module, make it more common to use.

### PR DESCRIPTION
**Pull request by ofunc**
- It can correctly process the calculation of time difference when the system time is changed, such as leap seconds, or manually modify the system time.
- `time` module has been fully implemented on Linux.
- On MacOS and Windows,  It can also working properly, but more improvements are needed.

Examples:
```
	// I'm not sure if there's a BUG about `tos2`.
	// Without this line, the print of formatted time is strange.
	println('')

	// Get the current time.
	t1 := time.now()
	// Print formatted Time.
	println(t1.format('%Y-%m-%d %H:%M:%S'))

	// Get time information for the local time zone.
	// Use t1.utc() to get UTC time information.
	info := t1.local()
	println('${info.year}/${info.month}/${info.day}')

	// Make time from time information.
	t2 := time.make(info) or {
		return
	}
	println(t2.format('%Y-%m-%d %H:%M:%S'))

	// Make a 500ms duration.
	d1 := time.milliseconds(500)
	println(d1) // --> 500.0ms

	// Sleep 500ms.
	time.sleep(d1)

	// Get the current time again.
	t3 := time.now()

	// Calculate the duration from `t1` to `t3`.
	d2 := t3 - t1
	// Time implements str().
	println(d2)
	// Convert to second or other unit of time.
	println('${d2.seconds()} seconds')

	// Add 8 hours.
	t4 := t3 + time.hours(8)
	println(t4.format('%Y-%m-%d %H:%M:%S'))

	// Parse a time string.
	t5 := time.parse('2019-06-26 17:46:50', '%Y-%m-%d %H:%M:%S') or {
		return
	}
	println(t5.format('%Y-%m-%d %H:%M:%S'))
```

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks for so much work! 

One suggestion: can you please implement 5 * time.Second instead of time.seconds(5), like in Go?

https://golang.org/pkg/time/#pkg-constants

I want the 2 stdlibs to be similar.

**Comment by ofunc** [comment]
> Thanks for so much work!
> 
> One suggestion: can you please implement 5 * time.Second instead of time.seconds(5), like in Go?
> 
> https://golang.org/pkg/time/#pkg-constants
> 
> I want the 2 stdlibs to be similar.

I considered this style, but for some reasons I gave up:

- If time.Second is defined as an integer constant, then `5*time.Second` is an integer, and I still need to convert it to `Duration` in some way.
- If time.Second is defined as an `time.Duration`, then get a compile error: expected type `int`, but got `time.Duration`. Maybe you will fix this problem later, but the compilation is not successful now.

In fact, I don't think the designing of duration is good in Go. There are some problems: `5*time.Second` is obviously OK. But what about `n * time.Second`?
- If n is `int`, then get a compile error.
- If n is `time.Duration`, for example `n := time.Duration(2)`, then it is very strange: `n` is `2ns`, `time.Second` is `1s`, `2ns * 1s == 2s`, the dimension is wrong!

**Comment by ofunc** [comment]
In my design, Time and Duration are of the same type, so I can use it this way:
```
t2 - t1 // t2.Sub(t1) in Go
t + d // t.Add(d) in Go
time.now() - t // time.Since(t) in Go
```
This design makes duration type is not an integer kind type, duration is `Time`.
This is in conflict with `5*time.Second` style design.

**Comment by medvednikov** [comment]
All right, let's try this. Can you fix the conflict please?

**Comment by ofunc** [comment]
The conflict is fixed, and all checks have passed.

The module is fully implemented on Linux.
On MacOS and Windows, It can also working properly, but more improvements are needed, such as nanosecond, monotonic and thread safety.

**Comment by medvednikov** [comment]
Thanks!

**Pull request merged**
