### PR TITLE
math: add factorial submodule and log_factorial function

### PR DESCRIPTION
**Pull request by ulises-jeremias**
In this PR I am adding the factorial submodule and the log_factorial function to this module in vlib/math.

The chosen definition for the implementation is in the domain of real numbers. For this, the table lookup method is used for those arguments belonging to the set of natural numbers less than 172. In any other case, the log_gamma function of the successor of the income number for any other case. If the natural number is greater than 171, then an asymptotic expansion is used to compute the log_factorial.

_NOTE: For any number n lower than 0 the result of n! it will be `-max_f64`._

```v
// vlib/math/factorial/factorial_tables.v
const(
        log_sqrt_2pi = 9.18938533204672741780329736e-1

        B = [
        /* Bernoulli numbers B(2),B(4),B(6),...,B(20).  Only B(2),...,B(10) currently
        * used.
        */
    f64(1.0 / (6.0 * 2.0 * 1.0)),
       -1.0 / (30.0 * 4.0 * 3.0),
        1.0 / (42.0 * 6.0 * 5.0),
       -1.0 / (30.0 * 8.0 * 7.0),
        5.0 / (66.0 * 10.0 * 9.0),
       -691.0 / (2730.0 * 12.0 * 11.0),
        7.0 / (6.0 * 14.0 * 13.0),
       -3617.0 / (510.0 * 16.0 * 15.0),
        43867.0 / (796.0 * 18.0 * 17.0),
       -174611.0 / (330.0 * 20.0 * 19.0)
        ]
	LOG_FACTORIALS = [
        f64(...),
        ...
        ]
)

// vlib/math/factorial/factorial.v
// log_factorial calculates the log-factorial of the provided value.
pub fn log_factorial(n f64) f64 {
	// For a large postive argument (n < 0) return max_f64

	if n < 0 {
                return -math.max_f64
	}

	// If n < N then return ln(n!).

	if n != f64(i64(n)) {
		return math.log_gamma(n+1)
	} else if n < LOG_FACTORIALS.len {
                return LOG_FACTORIALS[i64(n)]
        }

	// Otherwise return asymptotic expansion of ln(n!).

        return log_factorial_asymptotic_expansion(int(n))
}

fn log_factorial_asymptotic_expansion(n int) f64 {
       . . .
}

// vlib/math/factorial/factorial_test.v
import math
import math.factorial as fact

fn test_factorial() {
	assert fact.factorial(12) == 479001600
	assert fact.factorial(5) == 120
	assert fact.factorial(0) == 1
}

fn test_log_factorial() {
	assert fact.log_factorial(12) == math.log(479001600)
	assert fact.log_factorial(5) == math.log(120)
	assert fact.log_factorial(0) == math.log(1)
}
```

### CODE REVIEW

**Comment by medvednikov** [comment]
Hm somehow there are conflicts I can't resolve with the web ui.

**Comment by ulises-jeremias** [comment]
Merge problems were solved in the last commit

**Comment by ulises-jeremias** [comment]
All checks have passed! :smiley:

**Comment by ulises-jeremias** [comment]
@thecodrr I did the pull request to continue with the development of [vsl](https://github.com/ulises-jeremias/vsl). If you want you can take a look. Some code review will always be welcome! :smiley:

**Comment by thecodrr** [comment]
Did you see https://github.com/vlang-num/vnum? Maybe you both can join efforts? Also please join the discord channel: https://discord.gg/rqH2Yn

I will be glad to give a review as soon as I get a chance. Thank you so much for developing in V!

**Pull request merged**
