### PR TITLE
v: allow fixed array return

### LINKED ISSUE #15089: Allow functions to return fixed-size arrays.
Currently functions can't return fixed-size arrays. The current workarounds are to return a regular array or to create a new struct for every kind of fixed-size array. This can be solved by having the compiler generate a struct for every kind/size of fixed-size array that is returned by a function.

### PR DESCRIPTION
**Pull request by felipensp**
Fix #15089

Added flag to `ast.ArrayFixed` to indicate if it is a fixed array used on fn return, in this case it generates an struct enclosing the fixed array and uses `memcpy` to copy data.

### <samp>🤖 Generated by Copilot at 5a8cd70</samp>

This pull request adds support for array fixed types as function return types in the V language and its C backend. It modifies the `vlib/v/ast/table.v`, `vlib/v/checker/containers.v`, `vlib/v/checker/fn.v`, `vlib/v/checker/return.v`, `vlib/v/gen/c/assign.v`, `vlib/v/gen/c/auto_str_methods.v`, `vlib/v/gen/c/cgen.v`, `vlib/v/ast/types.v`, and `vlib/v/parser/parse_type.v` files to handle the new feature. It also adds a new test file `vlib/v/tests/fn_fixed_array_ret_test.v` to verify the correctness and functionality of the feature.

### <samp>🤖 Generated by Copilot at 5a8cd70</samp>

*  Add a new parameter `is_fn_ret` to the `find_or_register_array_fixed` method of the `Table` struct and the `ArrayFixed` struct that holds the information of the array fixed type ([link](https://github.com/vlang/v/pull/17931/files?diff=unified&w=0#diff-cfd5d819278aed172646f4254f098c98ee8bb62abdd0fd839359f6376c913614L1064-R1066), [link](https://github.com/vlang/v/pull/17931/files?diff=unified&w=0#diff-cfd5d819278aed172646f4254f098c98ee8bb62abdd0fd839359f6376c913614L1071-R1072), [link](https://github.com/vlang/v/pull/17931/files?diff=unified&w=0#diff-cfd5d819278aed172646f4254f098c98ee8bb62abdd0fd839359f6376c913614R1082), [link](https://github.com/vlang/v/pull/17931/files?diff=unified&w=0#diff-b9cd311e4eb5925e472e2d7f062cd82f2974db9d695c97eccd6ad2d54c2910b1R228)). The parameter indicates whether the array fixed type is used as a function return type or not, and is needed to distinguish between different array fixed types that have the same element type and size but different return contexts.

### CODE REVIEW

**Comment by JalonSolov** [comment]
How does this work?  Fixed arrays are created on the stack, which means they'll be corrupted quickly as the program does more function calls, etc.

**Comment by felipensp** [comment]
> How does this work? Fixed arrays are created on the stack, which means they'll be corrupted quickly as the program does more function calls, etc.

Yes, It's intended to be used knowing about stack size, etc. Just like we already need when creating a fixed array.

**Comment by spytheman** [comment]
@felipensp 
image

**Comment by spytheman** [comment]
Such a function could be simulated, by passing an additional parameter - the target address, and then doing the memcpy *inside* the function, when the fixed array is still valid on the stack, instead of returning it, then doing the copy in the caller.
I'm not sure it is worth it though.

**Comment by spytheman** [comment]
```v
fn f() [4]int {
    return [1,2,3,4]!
}

zzz := f()
dump(zzz)
dump(zzz[0])
```
leads to a cgen error:
```
/tmp/v_1000/z.11365486265824014296.tmp.c:12604:57: error: subscripted value is neither array nor pointer nor vector
12604 |   _v_dump_expr_int(_SLIT("z.v"), 7, _SLIT("zzz[0]"), zzz[0]);
```

The same, but with f() inlined, compiles and works fine.

In the case of f() returning [4]int, the generated struct for the fixed array is:
```c
struct _v_Array_fixed_int_4 {
    Array_fixed_int_4 ret_arr;
};
```

**Comment by spytheman** [comment]
imho that new structure, that has a `.ret_arr` field, has to be used *only* for returning fixed arrays, but it *should not* be used for their normal representation, *or* all fixed arrays should be represented by such a struct:
```c
struct _v_Array_fixed_int_4 {
    int value[4];
};
```
In any case, having 2 different and incompatible ways of implementing fixed array values, depending on how those values were produced should be avoided.

**Comment by felipensp** [comment]
> imho that new structure, that has a `.ret_arr` field, has to be used _only_ for returning fixed arrays, but it _should not_ be used for their normal representation, _or_ all fixed arrays should be represented by structs, similar to these (so that they could be returned freely without copying), at the cost of having to change all fixed array accesses to use that .value field too:
> 
> ```c
> struct _v_Array_fixed_int_4 {
>     int value[4];
> };
> ```
> 
> In any case, having 2 different and incompatible ways of implementing fixed array values, depending on how those values were produced should be avoided.

Ok, I've changed a bit more the implementation to be more strict to the returning ones. It also have changed to struct declaration to not depends on another typedef.

**Comment by medvednikov** [comment]
Amazing work @felipensp !

I just realized, can you please add @spytheman's example as a test?

```
fn f() [4]int {
    return [1,2,3,4]!
}

zzz := f()
dump(zzz)
dump(zzz[0])
```

**Comment by felipensp** [comment]
> Amazing work @felipensp !
> 
> I just realized, can you please add @spytheman's example as a test?
> 
> ```
> fn f() [4]int {
>     return [1,2,3,4]!
> }
> 
> zzz := f()
> dump(zzz)
> dump(zzz[0])
> ```

Thanks, I've added such test including a fix in another PR.

**Pull request merged**
