### PR TITLE
Add vast to v

### PR DESCRIPTION
**Pull request by lydiandy**
1. v ast xxx.v
2. add vast  help text
3. add demo.v for test

### CODE REVIEW

**Comment by JalonSolov** [comment]
Need to `v fmt` the code, and tcc on Windows _really_ doesn't like it...  :-\

**Comment by lydiandy** [comment]
I have already fmt the code before commit. but why?

**Comment by JalonSolov** [comment]
Sorry.  The format failure is not in your code.  It is complaining that v.v isn't formatted.

**Comment by lydiandy** [comment]
yeah, I will fmt the v.v file, thanks~~

**Comment by medvednikov** [comment]
Yay! Very glad to see it merge with V.

For some reason ubuntu-tcc fails with

```
cmd/tools/vast/vast.v:124:7: error: unknown function: json_print
  122 |     t.root = t.ast_file(ast_file)
  123 |     // generate the ast string
  124 |     s := json_print(t.root)
      |          ~~~~~~~~~~~~~~~~~~
  125 |     return s
  126 | }
```

Also ideally V's json should be flexible enough so that calling cJSON fns directly is not necessary.

**Comment by spytheman** [comment]
> For some reason ubuntu-tcc fails with

Should be fixed in the latest commit - `cmd/tools/vbuild-tools.v` needed to be modified, so that it knows about the new folder, to not try to compile individual files in it one by one.

**Comment by lydiandy** [comment]
> Yay! Very glad to see it merge with V.
> 
> For some reason ubuntu-tcc fails with
> 
> ```
> cmd/tools/vast/vast.v:124:7: error: unknown function: json_print
>   122 |     t.root = t.ast_file(ast_file)
>   123 |     // generate the ast string
>   124 |     s := json_print(t.root)
>       |          ~~~~~~~~~~~~~~~~~~
>   125 |     return s
>   126 | }
> ```
> 
> Also ideally V's json should be flexible enough so that calling cJSON fns directly is not necessary.

ok, I will try V's json later.

**Comment by spytheman** [comment]
> Also ideally V's json should be flexible enough so that calling cJSON fns directly is not necessary.

That is going to be hard - the `json` module as it is, is more rigid than the API that the cJSON library provides, and vast is using the flexibility very effectively.

We can perhaps gradually migrate it to `x.json2`, but that can be done later, after its merging imho.

**Comment by JalonSolov** [comment]
`x.json2` really needs to be finished, so it can completely replace `json`, and the cJSON dependency will go away.

**Pull request merged**
