### PR TITLE
checker: require `params` attribute to use struct as keyword arguments in function

### PR DESCRIPTION
**Pull request by danieldaeschle**
Before we had a problem that calling `foo()` works even it's not wanted.
```v
fn foo(table &ast.Table) {...}
```

I choosed `kwargs` because it's short and well known from Python.

### CODE REVIEW

**Comment by spytheman** [comment]
hm, I see what you mean:
```v
struct Table {
	x int = 123
	y f32 = 1.3
}

fn foo(table &Table) int {
	dump(table)
	return 123
}

fn main() {
	a := foo() // allowed on master, makes an empty Table, and passes it to `foo()`
	dump(a)
}
```

**Comment by danieldaeschle** [comment]
Exactly.. It happened to me several times know and I wondered why.

**Comment by spytheman** [comment]
for some reason the CI is not available here 🤔 
`ui` at least will need tagging their config structs

**Comment by danieldaeschle** [comment]
I did it for UI already locally, but UI has some other problems I don't know how to solve. Do you know how?

**Comment by medvednikov** [comment]
@danieldaeschle this can be achieved without adding a new feature to the language:

```
struct Config {
    x int [required]
}
fn f(c Config) int { return c.x }

fn main() {
    dump( f(x:123) )
    dump( f() )
}
```

**Comment by medvednikov** [comment]
Just need to make the error message nicer for this particular case.

**Comment by danieldaeschle** [comment]
I will think about it. It still can lead to bugs when developers forget required flag. The kwargs flag is explicitly needed which results in less mistakes.

You have to add required flag in every struct to prevent such mistakes.

I'm pretty sure the proposed solution is better.

**Comment by spytheman** [comment]
Personally, I like the explicit tagging for the special case, and it does solve/prevent problems. 
I do not like the tag name `kwargs` however - it is not very readable imho.

**Comment by danieldaeschle** [comment]
@spytheman I have the same opinion like you. But I didn't found a better name. I'm still sure this is needed @medvednikov. Otherwise there is working code and the user does not know why it compiles. I'm on my mobile phone and I can't write a good example right now.

**Comment by spytheman** [comment]
> I'm still trying to figure out why this is a problem.

If you have this:
```v
fn abc(x int) {}
abc()
```
... the compiler will helpfully tell you:
```
x.v:2:1: error: expected 1 arguments, but got 0
    1 | fn abc(x int) {}
    2 | abc()
      | ~~~~~
```

That is expected behavior and it is a good one, since it catches silly arrity mismatch mistakes, and ensures that the intent of the API designer match the intent of the caller (and the compiler checks that).

If the type of the parameter `x` is not `int`, but a sumtype instead, or an interface or string etc, the compiler will still complain.

If however, the type of the parameter is a struct (any struct), then V currently will *accept* that, as a call to a function that accepts a default struct, and will *not complain*. Instead the V compiler, will prepare an empty value of that struct, and pass it to the function.

That emergent behavior is relatively recent - before, V required at least `{}` for such calls, otherwise you would get the same error.
It changed, when we made that {} optional too, which is a useful feature by itself, but only for functions that do accept default structs, not for any other functions that just accept arbitrary structs.

I do not like the name of the tag, but something like that is needed, so that in the case, when the designer of an API just wants to accept a required struct in the parameter, he can do that, *and* when the need is for a default struct (for key-value kind of arguments), he can do that too - the intent of the API designer is different enough in these situations, that it should be expressible somehow. Not being able to do that, means that there will be bugs, when people design APIs that do require a struct argument, but where instead users/callers do not supply it, and the compiler just accepts that, and provides an empty default one instead.

**Comment by Gladear** [comment]
I personally think the tag should be on the function, not the struct.
A struct can be used in multiple functions, each of them might not want the struct to be considered as "parameters".

Maybe a keyword can be added before the argument ?
```v
fn my_function(opts struct MyStructOptions) {
    // ...
}
```

**Comment by danieldaeschle** [comment]
The kwargs flag should mark a struct to be used as keyword/named arguments in functions. Without this, you could forget to specify a required flag and this would lead to strange/unwanted function calls as it happened to me several times in the compiler now.

**Comment by danieldaeschle** [comment]
I'm okay with changing the attribute name. Adding an attribute to the param would also be fine for me, but it introduces a new syntax.

**Comment by JalonSolov** [comment]
While I agree with Gladear that it would be nice to have the flexibility, the attribute is just as new as the keyword in the params.

If we go with the attribute, how about `[no_default_init]`, or just `[no_default]` or similar - much more explicit was to what we want.

**Comment by danieldaeschle** [comment]
@JalonSolov But it does something different. `[kwargs]` still allows default init, but not setting this flag prevents the named/keyword arguments syntax in function calls. In this case Opt-In is also better than Opt-Out.

**Comment by elimisteve** [comment]
> That emergent behavior is relatively recent - before, V required at least {} for such calls, otherwise you would get the same error.
> It changed, when we made that {} optional too, which is a useful feature by itself, but only for functions that do accept default structs, not for any other functions that just accept arbitrary structs.

Why not simply require either `f({})` or `f(x: 456, y: 2.4)` and not permit `f()` at all when `f` takes > 0 arguments?

**Comment by danieldaeschle** [comment]
@elimisteve We removed the syntax `{}` and we introduced `foo()` as a feature because you might not want to give any special named value because the default values are fine.

This problem only appears if a struct as parameter is expected which shouldn't serve as named arguments. Our problem is that structs are values but also serve as named arguments. We need to restrict that.

**Comment by danieldaeschle** [comment]
Yeah, I don't know why this could should work. What is seed?

**Comment by spytheman** [comment]
@medvednikov , @JalonSolov , @danieldaeschle 
I've just rebased the PR over the current master, and it actually caught a bug in an unrelated recent change:
```v
-       cmp := a.abs_cmp()
+       cmp := a.abs_cmp(b)
```

The original was a typo (a missing `b` parameter), but still compiled on master, while with this PR, it did not, i.e. V really did caught a bug, exactly as it should have, proving the value of explicitly marking the keyword structs imho.

**Comment by danieldaeschle** [comment]
Thanks for finding out :)

Now you all have the proof that this is needed 😁

**Comment by elimisteve** [comment]
> Now you all have the proof that this is needed :grin: 

Proof that X is a problem is different from proof that Y is a great solution to X :slightly_smiling_face: .

A simpler solution to making `cmp := a.abs_cmp()` fail to compile when it should indeed fail is to require `cmp := a.abs_cmp({})` (see below).

Relatedly, having named arguments falls into various famous issues that @medvednikov talked about in https://discord.com/channels/592103645835821068/592115457029308427/839911336158429224 .

What these two changes have in common are that they (1) make V needlessly more complex, (2) make it ambiguous how many arguments a function takes, and (3) give us almost almost nothing in return.

Guys... replacing `f(util.MyConfig{})` with just `f({})` is a _huge_ victory, and improves on the very concept of type inference!  This move is _excellent_.

I appreciate trying to go further in this direction, but the additional "benefit" of allowing users to type `f()` instead of `f({})` is that it arguably looks less crufty, but at a significant cost to readability. And it makes things buggier, which makes it seem like even cruftier things like `[kwargs]` is needed!

Ruby, Perl, and Go have taught the language community a very important lesson: sacrificing readability for small gains in "writability" simply isn't worth it in the end. As Rob Pike likes to say, code is read many more times than it is written. So let's make it readable, specifically by setting the following standard for ourselves: **V should always make it clear how many arguments a function or method call takes**, period.

If V permits `f(x: 1, y: 2)` as shorthand for `f({x: 1, y: 2})` as shorthand for `f(util.MyConfig{x: 1, y: 2})`, I think that's reasonable, but absolutely _not_ if it's combined with `f()` being permitted _or_ with named arguments. Then we'd be creating ambiguities when reading code, and ain't nobody got time for that.

**Comment by danieldaeschle** [comment]
`{}` is no longer valid syntax because we want to keep the one-way philosophy.

Imo having real named arguments would be the nicer solution. But V will never have that. V's named arguments are built with structs.

I think this is a opinionated discussion but I don't like `{}`.

**Comment by elimisteve** [comment]
> `{}` is no longer valid syntax because we want to keep the one-way philosophy.

But keeping (or, apparently, resuscitating) `f({})` _does_ adhere to One Way, whereas doing without it, doesn't! Banning `f({})` creates _two_ ways: one where we must pass an argument to a function that requires an argument (`f(x)` or `f(x: 1, y: 2)`), and one where we mustn't (`f()`).

Besides, what if `f` takes `(struct, int, struct)`? Won't we have to do `f({}, 5, {})` anyway? Is `f({}, 5)` enough? Or even `f(5)`???

How many problems are we willing to create for ourselves so that users don't have to type 2 extra characters? (Characters that disambiguate what's going on, no less!)

**Comment by elimisteve** [comment]
@medvednikov Please, please bring back `f({})` for the many reasons described in my previous 2 comments!

**Comment by medvednikov** [comment]
> Imo having real named arguments would be the nicer solution. But V will never have that. V's named arguments are built with structs.

I wouldn't say never, maybe that'd be a simpler way than struct args.

I'll think of the best way to resolve this.

**Comment by JalonSolov** [comment]
I know some people think `f({})` is ugly (It's awkward, but I'm ok with it), but it is definitely explicit that you're passing in an empty struct, as opposed to forgetting to pass anything at all.

If we switch to having to always pass named arguments... how many?  ALL of them, or just 1?  If just one, does it matter which one?  Does the order matter?  If so, what happens if the order changes?

Imagine a struct with a LOT of fields... look at gitly, with a lot of different structs with more than a dozen fields each...

**Comment by danieldaeschle** [comment]
`{}` was removed and is now reserved for maps.

Yes, named arguments are always optional (if not [required] attribute is set). That's why we had to support `foo()`. Tricky situation, indeed.

**Comment by Gladear** [comment]
Having named arguments implies having default parameters, doesn't it ?
I'm not completely against it, but the topic has been brought up many times

**Comment by medvednikov** [comment]
Yeah, but we already have default args with default struct field values.

**Comment by Gladear** [comment]
Indeed, but if named parameters are chosen, it will introduce a new syntax for default parameters.
Again, I'm not against it, just saying.

**Comment by danieldaeschle** [comment]
push

**Comment by elimisteve** [comment]
Any update on this?

**Comment by JalonSolov** [comment]
Alex gave it the go-ahead on Discord, but wants the attribute named `[params]` instead of `[kwargs]`.

**Comment by danieldaeschle** [comment]
Will do it today or tomorrow

**Comment by danieldaeschle** [comment]
@medvednikov change is finished

**Comment by danieldaeschle** [comment]
@medvednikov please merge it finally.

**Comment by elimisteve** [comment]
@medvednikov Please don't! This is a step in the wrong direction. Let's solve the upstream issues, described above, that will obviate the need for this PR.

**Comment by danieldaeschle** [comment]
@elimisteve You suggestions doesn't really solve the prolem. We already mentioned it. It breaks the one-way rule by the way.
If you have better suggestions, let me hear.

**Comment by elimisteve** [comment]
> It breaks the one-way rule by the way.

@danieldaeschle I already refuted that claim in detail, here: https://github.com/vlang/v/pull/11135#issuecomment-910132715 . Do you have a specific response to that?

**Comment by elimisteve** [comment]
```v
-       cmp := a.abs_cmp()
+       cmp := a.abs_cmp(b)
```

@spytheman That is indeed a problem. I think the best solution is to not obfuscate how many parameters that functions and methods accept. One may think that it is "cleaner" to not make the user type `{}` nor `MyStruct{}`, but that hides important information from whoever is reading the code.

@medvednikov If `f({})` causes serious parsing issues, how about just requiring `f(MyStruct{})` (or `f(x: 1, y: 2)`) rather than accepting `f()`, which makes it look like there is no input parameter, which is misleading, and which causes bugs like the above (as you know)?

**Comment by elimisteve** [comment]
@danieldaeschle And what about this part of one of my earlier messages above? I think this is a good argument:

> Besides, what if `f` takes `(struct, int, struct)`? Won't we have to do `f({}, 5, {})` anyway? Is `f({}, 5)` enough? Or even `f(5)`???
>
> How many problems are we willing to create for ourselves so that users don't have to type 2 extra characters? (Characters that disambiguate what's going on, no less!)

Fundamentally, merging this PR only makes sense if we are wedded to keeping `f()` as valid syntax for a function call that accepts one struct, which we shouldn't be, for the following reasons:

1. [It violates One Way](https://github.com/vlang/v/pull/11135#issuecomment-910132715)
2. It causes ambiguities in the number of parameters when reading code (does `f()` mean f accept 0 params or 1?)
3. It causes the kinds of [bugs](https://github.com/vlang/v/pull/11135#issuecomment-909725514) that this PR is meant to solve

Therefore, if we can make one simple ~trick~ change -- namely disallowing `f()` and requiring either `f(x: 1, y: 2)`, `f(MyStruct{})`, or `{}` (if the parsing issues Alex mentioned to be can be solved) -- then in one fell swoop, we can solve problems 1, 2, and 3! :tada: _And_ we can avoid the complexity of adding to V the new feature that this PR would add.

One change => Three problems solved.

One non-merge => One additional piece of complexity prevented.

What do you say, gents?

**Comment by spytheman** [comment]
> One change => Three problems solved.

> One non-merge => One additional piece of complexity prevented.

I would say - one merge, to solve the pressing problem of having easily catch-able bugs (which is the current state), and then discuss the other changes later. What you are suggesting (`{}`to mean an empty struct in the function calls only) @elimisteve, is not easy to do (due to the parser ambiguity that it re-introduces) and will take time and effort, and make tooling harder. I can see its benefits, and it may very well be the better solution in the long term. In the short term however, we do need a solution for the current syntax. This PR provided it for over a month now, and so far no one has suggested a better solution (+ and working code) to solve the current problem. Discussing this further delays solving it.

**Comment by elimisteve** [comment]
> What you are suggesting (`{}` to mean an empty struct in the function calls only) @elimisteve, is not easy to do (due to the parser ambiguity that it re-introduces)

Then let's skip allowing `{}` for now (or forever) and only accept `f(x: 1, y: 2)` and `f(MyStruct{})`, but not `f()`.

If this PR is accepted then we will have to go back in and manually pass in empty structs. This will also break other people's code. If that is going to happen then, like `os.chdir(...)` -> `os.chdir(...) ?` from 2 weeks ago, we'd might as well get it out of the way now rather than write more code that relies on something that is going to change anyway.

**Comment by spytheman** [comment]
> `f(MyStruct{})`
That is not a viable option imho, since it will require the writer to know the exact name of the config struct, and type it every single time, in the most common case (when all the fields have their default values). For example, given this API (from the `time` module):
`pub fn new_stopwatch(opts StopWatchOptions) StopWatch {`

=> callers will be required to always do `mut sw := time.new_stopwatch(time.StopWatchOptions{})`, which is very verbose imho, without providing any additional benefit to the source code readers/maintainers.

**Comment by Gladear** [comment]
What about named/default parameters ?
Wouldn't that solve all problems ?
It does introduce new things and complicates the compiler, indeed, but it may be worth it ?

**Comment by elimisteve** [comment]
@Gladear Given how structs work, and given that the functionality is almost identical to named parameters + default values, adding the latter as feature would basically mean adding that same functionality to V a second time.

**Comment by Gladear** [comment]
It is the same functionality, without all the drawbacks !
You wouldn't have to tag a struct for being a "param", and there would be no short struct init syntax

**Comment by Gladear** [comment]
Oh by the way, I mean to remove the short struct init syntax along with the introduction of named params

**Comment by elimisteve** [comment]
@spytheman Of course it's viable. Is Go not viable? It does the same thing and it works great. It's just not as convenient for the caller as my original proposal, which you're opposed to for the sake of solving one problem now at the expense of creating several other problems for the foreseeable future. I think that's a poor trade-off, especially when simplicity is something we are degrading along the way, particularly when a major goal of V is simplicity.

On top of all of the above, here is yet _another_ problem with this PR, and one that nobody has mentioned yet, myself included: since `[params]` tags a type, and thereby affects _every use_ of that type, using `[params]` creates potential bugs every place that type is used, not just in the first use case that made `[params]` seem appealing.

If I add `[params]` to a type in my library, and you import my library, then you are right back where we started before `[params]` was introduced. Except with all the same problems as before, _and_ a new language feature to watch out for.

Therefore, this PR doesn't even solve the problem it was designed to solve, namely cases like

```v
-       cmp := a.abs_cmp()
+       cmp := a.abs_cmp(b)
```

@medvednikov If we want an actual solution, and not just a temporary partial solution with its own downsides, then we should solve the problem upstream and disallow `f()`.

**Comment by elimisteve** [comment]
@Gladear I've seen that done in Python, and it's good at first, and then eventually there's 25 parameters that can't be grouped into the 3 separate categories of parameters they really _are_ in unless you give their names prefixes, which makes everything needlessly verbose.

If V permits structs to be passed to functions and methods anyway -- surely we must allow this, or else we couldn't pass a `User` or other "objects" around -- and if those semantics are basically the same as named default parameters, aren't we kind of back where we started, but with another language feature?

That said, it's true that instead of having this sort of conflation between "object structs" and "config structs", so to speak, which I think is part of the tension, then yeah, people could use named default parameters rather than defining a "config struct".

Still seems like almost the same feature twice, plus the issues that @medvednikov mentioned in Discord:

> @penguindark @🌸mint🌸 and everyone else who suggested named args. They are nice, but they do have lots of problems as well. From the Go dicussion:
>
> Exported functions cannot change their parameter names anymore or risk to invalidate existing code that uses those names (mentioned by @bradfitz ).
>
> Named arguments lead to overly long parameter lists ( @bradfitz ).
>
> What about variables of function types? At the moment, one can assign functions with different parameter names to assignment-compatible function variables. Do parameter names have to match (and thus become part of type identity)? ( @nigeltao )
>
> When should one use named arguments, and when not? Easily can lead to needless style-guide wars.
>
> What about variadic functions? How do I provide arguments for the variadic parameter? Or should variadic functions be excluded from this?
>
> What about functions with unnamed parameters? (We cannot use the type names as in structs since the same parameter type may occur more than once). We would have to exclude those functions as well.

**Comment by JalonSolov** [comment]
We _do_ already have a "placeholder" for when we don't care about things.

If `f({})` can't be used (too complex, or whatever), why not simply `f(_)`?

I agree with @elimisteve - forcing an extra parameter just to allow `f()` feels like the wrong way to do things.

**Comment by danieldaeschle** [comment]
**Ok, let's go through from the beginning.**

There were `MyStruct{}`, `{}` and `foo(bar: 5)`. All of the initialized a struct. The last one is syntax sugar for declarative programming and is very equivalent to optional & keyword arguments. Other languages have native support for that.
In V we solved it by using structs.

Since we had three ways of initiate a struct, we removed `{}` because it created bugs with maps (it is already removed and won't come back). Now we have `MyStruct{}` and `foo(bar: 5)`. On the latest one, we had a problem when the user doesn't need to pass any value because the default values are sufficient. That's why we allowed to use `foo()` which in turn came with another bug. This PR tries to solve this bug.

In Kotlin this works like this as well btw:
```kotlin
fun foo(bar: Int = 5) {
    println("Foo bar: $bar")
}

fun main() {
    foo()
}
```

It is valid code and it works. Other languages have that too, it's nothing new.

So, V has optional & named parameters like other languages that behave very similar with this PR.

**What's the problem now?** The problem I have is that we're using structs for that. It's not nice because structs are for something different normally. But it was invented like this to keep the compiler simple and small. Hey, it works and I'm fine we have this syntax!

The better solution would be having native named arguments. But this is better than nothing. Please stop complaining about a feature that is very common in programming.

Regarding go that does not have this kind of syntax. _That's why Go sucks with UI and delcarative programming._


If we are going to implement native named arguments with default values, the syntax will be equivalent to this.

**Comment by medvednikov** [comment]
I'll merge it for now since it solves a big problem, we can discuss this further later.

**Comment by elimisteve** [comment]
> Please stop complaining about a feature that is very common in programming.

@danieldaeschle V should strive to include features that are well-designed, regardless of how common they may be elsewhere. Popular != good.

**Comment by danieldaeschle** [comment]
Popular != bad

**Comment by kahsa** [comment]
Hmm, this is just a workaround for a bug that can't be fixed.

It's trying to mix up two things that clearly have different meanings: giving just an argument and an argument that is initialized at the same time.

**Comment by kahsa** [comment]
> That is not a viable option imho, since it will require the writer to know the exact name of the config struct, and type it every single time, in the most common case (when all the fields have their default values). For example, given this API (from the `time` module):
> `pub fn new_stopwatch(opts StopWatchOptions) StopWatch {`

By the way, although it will be in the future, why not let the IDE or LSP do these things for the writer?
Scripting languages have been shortened to make them more convenient for writers, but the result is a pile of syntax sugar.

**Comment by danieldaeschle** [comment]
> It is logically correct to revive func({}).
I don't see it as ugly or a hassle.

it's not about ugly or hassle, it's about that the syntax is removed and does not work with other features.

**Comment by danieldaeschle** [comment]
> but this is adding to the confusion.

What is confusing for you?

**Comment by dumblob** [comment]
I hope I'm not too late to the party (over the coming weeks I'll try to find again some time to take a look at what happend during the past 2 months in *V*). Let's do what @medvednikov proposed:

> I'll merge it for now since it solves a big problem, we can **discuss this further** later.

I'm really surprised nobody questioned the need to **always** use `{}` for maps - because that's the **only** argument of @danieldaeschle why `{}` creates ambiguity:

> There were `MyStruct{}`, `{}` and `foo(bar: 5)`. All of the initialized a struct. The last one is syntax sugar for declarative programming and is very equivalent to optional & keyword arguments. Other languages have native support for that.
> In V we solved it by using structs.
> 
> Since we had three ways of initiate a struct, we removed `{}` because it created bugs with maps (it is already removed and won't come back). Now we have `MyStruct{}` and `foo(bar: 5)`. On the latest one, we had a problem when the user doesn't need to pass any value because the default values are sufficient. That's why we allowed to use `foo()` which in turn came with another bug. This PR tries to solve this bug.

I'm a strong advocate for `foo( {} )` instead of `foo()` (for the important reasons @elimisteve precisely outlined above). I'm totally fine taking the route to complicate the parser. But if that poses a *serios amount of complexity*, then why not to re-evaluate the mantra "`{}` is always an empty map"?

First, could you @danieldaeschle provide more insight why this map mantra came true?

I think we all agree than passing "keyword" arguments is much more common (probably orders of magnitude) than using an empty map as the only argument. Thus `foo( {} )` instead of `foo( MyStruct{} )` sound like a much better choice than `foo( {} )` instead of `foo( map[int]string{} )` (aka "inline typed map" - I have no idea whether *V* already supports that but from the discussion above I suppose it does) or `foo( map{} )` (a possible shortcut notation).

It's unambiguous, it doesn't violate the "do things one way" (i.e. the empty map is explicitly typed) and it should be easy to implement (shouldn't complicate *anything*). It also allows to preserve the IMHO rather smart choice of passing structs as wannabe keyword arguments as it's fast (unlike probably all keyword arguments implementations I know of).

Thoughts?

**Comment by danieldaeschle** [comment]
`{"test": "bar"}` for maps and the old syntax for struct init was `{test: "bar"}`. Both ways were possible and that lead to compiler problems. So we changed `{}` to `map{}`. But then we had an inconsitency of `[]` for arrays and `map{}` for maps but we had 3 ways of struct init. The only way to remove `{}` for struct init was to get consistency in both worlds, struct init and map init.

imo introducing short struct init `{}` is no option anymore.

**Comment by dumblob** [comment]
> `{"test": "bar"}` for maps and the old syntax for struct init was `{test: "bar"}`. Both ways were possible and that lead to compiler problems.

That's understandable and clear.

>So we changed `{}` to `map{}`. But then we had an inconsitency of `[]` for arrays and `map{}` for maps but we had 3 ways of struct init. The only way to remove `{}` for struct init was to get consistency in both worlds, struct init and map init.

Let me summarize how I understand these facts:

1. `map{}` poses no technical nor parser nor readability problems but someone from the community thinks it's inconsistent with arrays for no reason (which I myself find amusing as `map` can never be consistent because it requires specifying two types instead one)
2. 3 ways of struct init is too much freedom (which I agree with) and none of them poses any problems (assuming my proposal in the comment above), so let's choose the simpliest and most frequent one and ditch it (I disagree with this choice)
3. *V* community finds (for no obvious reason) almost the weakest possible relation between `{}` and some other pair of characters (this time `[]`) instead of focusing on trying to **consistently** disambiguate the closest possible relation - yes the characters `{}` themselves! They're used for lexical context, for structs, for maps, etc. - that's where **consistency** (of orthogonality) plays an immense role, but **not** where other characters do something unrelated (arrays have one type, maps have two - I'll reiterate, there is no similarity whatsoever).
4. *V* community did not take a serious enough look at how detrimental this choice was - e.g. using V UI reminds the Go/Java verbosity instead of the previous sleek readable & "skimmable" source code
4. *V* community didn't seem to evaluate how ditching (either of) the other 2 ways of struct init would look like **in detail** (incl. consequences)

> imo introducing short struct init `{}` again is no option anymore.

Admittedly I don't share this thought - we're talking about rather huge amount of problematic consequences caused by a thing merged few days/weeks ago.

All in all this decision to not use `map{}` (of course **only** on those **extremely rare** places - *compare this to places with keyword arguments which are **extremely frequent*** - where the disambiguation is necessary and optional elsewhere where `{}` meaning an empty map is enough and totally clear) probably because of "very few community members who have shouted too loudly" sounds rather like a joke and not a thought-out step forward.

Yeah, it's good *V* tried to explore that step, but now it's time to get wise again and re-do it properly (btw. there are at least 2 other options not discussed in this comment - namely "true keyword args" and "let's complicate parser to disambiguate").

@medvednikov do you have time to react here?

**Comment by spytheman** [comment]
> 4. V community did not take a serious enough look at how detrimental this choice was - e.g. using V UI reminds the Go/Java verbosity instead of the previous sleek readable & "skimmable" source code

Can you clarify that @dumblob ?
Currently, you can do for example: `ui.label(text: '2/10')`, or even just: `ui.label()`, if you want a simple label in your UI, and you can customize all its properties too if you want too. I do not see how is that verbose?

**Comment by spytheman** [comment]
> V community didn't seem to evaluate how ditching (either of) the other 2 ways of struct init would look like in detail (incl. consequences)

The discussion about removing {} was very lively if I remember correctly, but I do not remember that someone foresaw the problem that this PR solved (distinguishing *EXPLICITLY* and *CLEARLY*, what is a default struct declaration, so that functions that do use them, can be distinguished by both the compiler and the developers).

Unlike others, I can speak only for myself, not for the V community as a whole. I do lack a magic ball, and I can foresee the future only in some cases for limited situations. I do welcome the interested future tellers, to join the V Discord (and be active in it, when discussions like the mentioned do happen), so that they can prevent future bugs and regressions in simplicity *before they happen* by their talents, and *NOT* derail the efforts of others after the fact, paralyzing working PRs, that provide solutions to existing problems, for *weeks*. Providing PRs by said future tellers, that implement their ideas, will be even better, but optional.

**Comment by spytheman** [comment]
> places with keyword arguments which are extremely frequent
I agree here, and also think that well designed with keyword arguments should use them to the fullest, by taking advantage of the *default values* that they can have.

Thus the *most frequent* usage of such functions, should be more or less `f()`, not `f({})`, do not you agree?

**Comment by spytheman** [comment]
> By the way, although it will be in the future, why not let the IDE or LSP do these things for the writer?

@kahsa, I do not want V to become a second Java, and be dependable on IDEs for productive work, without having to remember the names of irrelevant structs. Imho IDEs should remain *aids*, *not necessities*. Normal text editors currently do work fine, lets keep it that way (like emacs or vim without an LSP plugin).

**Comment by dumblob** [comment]
> > 1. V community did not take a serious enough look at how detrimental this choice was - e.g. using V UI reminds the Go/Java verbosity instead of the previous sleek readable & "skimmable" source code
> 
> Can you clarify that @dumblob ?
> Currently, you can do for example: `ui.label(text: '2/10')`, or even just: `ui.label()`, if you want a simple label in your UI, and you can customize all its properties too if you want too. I do not see how is that verbose?
> If you prefer, have a look at https://github.com/vlang/ui/blob/master/examples/users_resizable.v.
> Can you tell me, how you can simplify that code further if `{}` was still supported?

I read my post again and it seems exaggerated. I'm sorry for that. I saw https://github.com/vlang/ui/commit/628cea4e9c2b7e90525c67ab7f775843f60f571f (and https://github.com/vlang/ui/pull/364/files ) and freaked out why do I need to specify anything like that.

To give more context - I was also the one proposing (true) keyword arguments in the past in the V issue tracker. My intention was (and still is) to have **inline** keywoard arguments (i.e. without defining a named struct up front). I don't see any point of reusing such "named keyword arguments" structs. But it was decided to do it that way :cry:. And now **exactly this decision is the culprit**. So let's make a patch caused by the wrong decision and "bind" the struct to a (group of certain) function. But well, this patch is not being fully accepted by the V community.

If *V* had **only** inline (anonymous struct based) keyword arguments, there wouldn't be need for any `[params]` tag. This is the message I want to convey.

As you can see this is quite unrelated to the `f( {} )` syntax at the call site which is a separate issue on its own - read further.

> > V community didn't seem to evaluate how ditching (either of) the other 2 ways of struct init would look like in detail (incl. consequences)
> 
> The discussion about removing {} was very lively if I remember correctly, but I do not remember that someone foresaw the problem that this PR solved (distinguishing _EXPLICITLY_ and _CLEARLY_, what is a default struct declaration, so that functions that do use them, can be distinguished by both the compiler and the developers).
> 
> Unlike others, I can speak only for myself, not for the V community as a whole. I do lack a magic ball, and I can foresee the future only in some cases for limited situations. I do welcome the interested future tellers, to join the V Discord (and be active in it, when discussions like the mentioned do happen), so that they can prevent future bugs and regressions in simplicity _before they happen_ by their talents, and _NOT_ derail the efforts of others after the fact, paralyzing working PRs, that provide solutions to existing problems, for _weeks_. Providing PRs by said future tellers, that implement their ideas, will be even better, but optional.

This makes me sad as I fully understand PRs are the best means to push things forward (which is unreachable for me as a father with a rather turbulent job). And I'm sorry if my behavior "derails the efforts of others after the fact...". I was under the impression that if any such "fact" ignites any flames in the community (which this PR clearly caused from the very beginning), then everybody (stakeholders, PR authors, commenters, V community, etc.) will realize it's not the long-term path forward. @medvednikov clearly realized that and encouraged further discussion.

Back to the technical points. So again, it's all about trying to define inherently **inline** "keywoard structs" as **global** structs. That's where all these multiple syntactical ways of passing such struct stem from. It's all about anonymous versus global struct definition.

Did the lively discussion identify this quite simple observation?

What were the outcomes (pros & cons)?

Is by "would complicate the parser" meant the implementation of "anonymous structs as keyword arguments"?

> > places with keyword arguments which are extremely frequent
> 
> I agree here, and also think that well designed functions, that accept keyword arguments, should use them to the fullest, by taking advantage of the _default values_ that they can have.

Yes.

> Thus the _most frequent_ usage of such functions, should be more or less `f()`, not `f({})`, do not you agree?

Most APIs involving keyword arguments require combination of non-zero number of always-to-specify arguments and a non-zero number of optionally-to-specify arguments.

So the usage will mostly look like `f( field00: 'abc' )` than `f( {} )`. And this is the main driver behind my comments above. I want to make it **explicit** that we're dealing with default arguments pretty much the same as in the most common cases (`f( field00: 'abc' )`) where you already **explicitly** see that you're dealing with optional arguments.

`f( {} )` was a nice way to convey this message. I'm definitely open to other means of conveying the message **at the call site**. I also think the conflict with `map` is a negligible and easily solvable problem as outlined by many (incl. myself), but if there is anything better to convey the message, please speak up.

Thoughts?

**Comment by danieldaeschle** [comment]
I'm on your side, we should have native support for keyword arguments.

**Pull request merged**
