### PR TITLE
examples (vweb): fullstack example

### PR DESCRIPTION
**Pull request by enghitalo**
I'm thinking of using this project in https://github.com/vlang/v/pull/16738
image

image

### CODE REVIEW

**Comment by spytheman** [comment]
Showing a table with all registered users, and their password hashes is not a good idea in an example imho.

**Comment by enghitalo** [comment]
> Showing a table with all registered users, and their password hashes is not a good idea in an example imho.

I will change for a list o product for each user. What you thing?

**Comment by Larpon** [comment]
> > Showing a table with all registered users, and their password hashes is not a good idea in an example imho.
> 
> I will change for a list o product for each user. What you thing?

Anything else than passwords, so a product sounds good to me

**Comment by spytheman** [comment]
Yes, a list of products is ok imho.

**Comment by enghitalo** [comment]
Note for me. Add 'parents' and 'children' fields for User struct and user just a struct.

**Pull request merged**
