### PR TITLE
Added colors.v: Bring colors to terminal

### PR DESCRIPTION
**Pull request by Kriyszig**
V is a great language to write backend programs. Let's bring the colors to the terminal then.

Running this program:
```go
import colors

fn main()
{
	println('bgblack: ' + colors.bg_black('bgblack'))
	println('bgblue: ' + colors.bg_blue('bgblue'))
	println('bgcyan: ' + colors.bg_cyan('bgcyan'))
	println('bggreen: ' + colors.bg_green('bggreen'))
	println('bgmagenta: ' + colors.bg_magenta('bgmagenta'))
	println('bgred: ' + colors.bg_red('bgred'))
	println('bgwhite: ' + colors.bg_white('bgwhite'))
	println('bgyellow: ' + colors.bg_yellow('bgyellow'))
	println('black: ' + colors.black('black'))
	println('blue: ' + colors.blue('blue'))
	println('bold: ' + colors.bold('bold'))
	println('cyan: ' + colors.cyan('cyan'))
	println('dim: ' + colors.dim('dim'))
	println('green: ' + colors.green('green'))
	println('gray: ' + colors.gray('gray'))
	println('hidden: ' + colors.hidden('hidden'))
	println('italic:' + colors.italic('italic'))
	println('inverse: ' + colors.inverse('inverse'))
	println('magenta: ' + colors.magenta('magenta'))
	println('reset: ' + colors.reset('reset'))
	println('red: ' + colors.red('red'))
	println('strikethrough: ' + colors.strikethrough('strikethrough'))
	println('underline: ' + colors.underline('underline'))
	println('white: ' + colors.white('white'))
	println('yellow: ' + colors.yellow('yellow'))
}
```

[This is the output](https://drive.google.com/file/d/1JhNnKrluq0XyOZV8m2WuJpt9K6JTj1YT/view)
I wasn't able to upload the image on imgur for some reason so I had to use Google Drive :octocat:

### CODE REVIEW

**Comment by Kriyszig** [comment]
cc/ @medvednikov 
I thought this would be a good addition to V. Let me know what you think :octocat:

**Comment by Kriyszig** [comment]
Thanks for the review @AurelienFT :+1:

**Comment by medvednikov** [comment]
Thanks!

**Comment by Kriyszig** [comment]
Thank you for making V and open-sourcing it :octocat:

**Pull request merged**
