### PR TITLE
term: fix typo

### PR DESCRIPTION
**Pull request by czkz**

### CODE REVIEW

**Comment by Terisback** [comment]
I don't think it's a typo 😕

**Comment by czkz** [comment]
The function is called `warn_message`, and not `warning_message`; readme uses the wrong name.
https://modules.vlang.io/term.html#warn_message
Probably it's just outdated and not a typo, but the PR still stands

**Comment by Terisback** [comment]
You're right

**Comment by Larpon** [comment]
@czkz sorry, I need to look more closely next time 🧐

**Pull request merged**
