### PR TITLE
examples/dynamic_library_...: fix .so directory.

### PR DESCRIPTION
**Pull request by changrui**

### CODE REVIEW

**Comment by spytheman** [comment]
See `examples/dynamic_library_loading/use_test.v` - it is the driver of that example.

**Comment by changrui** [comment]
> See `examples/dynamic_library_loading/use_test.v` - it is the driver of that example.

I do `v run use.v` and `v test .` under WSL2 of ubuntu, but error on Windows 11 powershell, after fixing.
```
[root@iphone13 dynamic_library_loading]# v run .
handle: 5611d590aa80
f: 7f6898431256
res: 4
[root@iphone13 dynamic_library_loading]# v run .
handle: 5612c8dc6a80
f: 7f0838f84256
res: 4
[root@iphone13 dynamic_library_loading]# v test .
---- Testing... --------------------------------------------------------------------------------------------------------
 OK   15421.367 ms /mnt/d/v/examples/dynamic_library_loading/use_test.v
------------------------------------------------------------------------------------------------------------------------
Summary for all V _test.v files: 1 passed, 1 total. Runtime: 15425 ms, on 1 job.
```

**Comment by spytheman** [comment]
i.e. your problem is that you want to pass the test, while running it from the folder itself, with `v test .` on windows 11 in powershell, and not from the main v repo folder with `v examples/dynamic_library_loading/use_test.v` as the CI does ?

**Comment by spytheman** [comment]
You can change the executable to:
`library_file_path := os.join_path(os.dir(@FILE), dl.get_libname('library'))`
and it will become position independent.

**Pull request closed without merging**
