### PR TITLE
vfmt: improve the documentation for the -c flag

### PR DESCRIPTION
**Pull request by serkonda7**
`fmt -c <file>` and `fmt -verify <file>` have the same purpose.
Therefore this PR deprecates the `-c` flag, that I never saw used anywhere, in favor of `-verify`.

### CODE REVIEW

**Comment by spytheman** [comment]
-is_verify is slower - it does a color diff comparison of the files using an external command, then discards the results. 
-c  just does `fc != formatted_fc`.

**Comment by spytheman** [comment]
```
0[16:39:46]delian@nemesis: /v/pv $ time ./v fmt -c vlib/
File is not formatted: /v/pv/vlib/flag/flag.v

real    0m0.038s
user    0m0.022s
sys     0m0.016s
2[16:39:48]delian@nemesis: /v/pv $ time ./v fmt -verify vlib/
/v/pv/vlib/flag/flag.v is not vfmt'ed

real    0m0.089s
user    0m0.067s
sys     0m0.021s
1[16:39:52]delian@nemesis: /v/pv $
```

**Comment by JalonSolov** [comment]
Rather than deprecate -c, would be better to change the help to specify that `-c` is a "quick" verify.  `-v` is a more complete, but slower verify.

**Comment by serkonda7** [comment]
Should the exitcode stay 2?

**Comment by Gladear** [comment]
But then, there is also `-diff`, isn't it the same as `-verify` if I understand correctly ?

**Comment by serkonda7** [comment]
No, - diff prints the color diff what would change on format, while - verify just tells if something is formatted or not

**Comment by spytheman** [comment]
> Should the exitcode stay 2?

Currently it is not used for anything except for breaking a script when it fails, so it can be anything != 0.

**Comment by serkonda7** [comment]
I think 1 is more common as error exitcode.

**Pull request merged**
