### PR TITLE
Fix array.reverse() test

### PR DESCRIPTION
**Pull request by joe-conigliaro**
This fixes the broken test

### CODE REVIEW

**Comment by medvednikov** [comment]
`==` doesn't work for arrays, does it?

**Comment by joe-conigliaro** [comment]
@medvednikov nah I just realized, i should have tested it first sorry

**Comment by joe-conigliaro** [comment]
I shouldn't have done the test like that it should only really assert twice for each array but I knew master was broken and wanted a quick fix

**Comment by medvednikov** [comment]
Thanks for fixing it. `==` will be implemented for arrays and structs soon.

**Pull request merged**
