### PR TITLE
Add os.environ

### PR DESCRIPTION
**Pull request by kitech**
* add os.environ to get get environment variables
* permit init args/envs in test

### CODE REVIEW

**Comment by spytheman** [comment]
Why is this needed?
There are already these functions for manipulating the environment variables.
os.getenv
os.setenv
os.unsetenv

They work on all platforms.

**Comment by kitech** [comment]
I think it's not the same thing, you cannot got a key that you don't
know with exist os.xxxenv

**Comment by spytheman** [comment]
That is true, but why would you want to get all environment variables, even ones that you do not care about, and why would every v program need access to them (modifying the C main generation)?
I do not understand the utility, that is all.

**Comment by kitech** [comment]
But indeed not `every v program` need to access it, unless the program
import `os` package

One case, on github actions platform, github will export a list of
GITHUB_* environs, and some other platforms is similar. With this, one
can filter on the list very easy. 

Last, most OSes and programming languages have this.

**Comment by medvednikov** [comment]
This function is indeed ok.

But I don't think there's a need to make the values "global", like os.args.

os.args are constant, environment can change.

I'd do it like in Go:

https://golang.org/src/os/env.go?s=3883:3906#L129

**Comment by spytheman** [comment]
Can the new os.environ() use https://linux.die.net/man/5/environ on unixes, and https://docs.microsoft.com/bg-bg/windows/win32/api/processenv/nf-processenv-getenvironmentstrings on windows instead?

In this way, only programs that call os.environ() will pay the price of the access.

I do not like the runtime initialization that happens inside main. It is not avoidable for argc and argv, but I think it is for os.environ() ?

**Comment by kitech** [comment]
I use go's os.Evnrion ever, and before submit this commit, I took a look
at go's os.Evniron little, it also use a global but private var to
store the initial env list, and ofcause go have more modify functions.

I want do like that, but it not easy to save a global vars like that in
V, so is there some way to store the initial env list?

So, if there's a plan, hope see this feature soon.

**Comment by kinggoesgaming** [comment]
why would you want to get all environment variables, even ones that you do not care about, and why would every v test program need access to them (modifying the C main generation)?
I do not understand the utility, that is all

@spytheman 

This could useful for passing env onto a process started by a V program.

**Comment by medvednikov** [comment]
Fixed in https://github.com/vlang/v/pull/3971

**Pull request closed without merging**
