### PR TITLE
1150: Add production mode tests

### PR DESCRIPTION
**Pull request by tobyjwebb**
Due to the inability to detect warnings in REPL tests, I implemented running something very similar, but with the -prod flag enabled.
(See https://github.com/vlang/v/pull/2536)

There is also a minor change in os.walk_ext to not add duplicated path separators:
/path//file.ext -> /path/file.ext

### CODE REVIEW

**Comment by tobyjwebb** [comment]
********* Windows...

**Comment by spytheman** [comment]
(close/reopen to force CI test reruns)

**Comment by medvednikov** [comment]
@tobyjwebb can we simply not run them on Windows for now?

**Comment by tobyjwebb** [comment]
Sounds like a hack to me XD

Ok, I'll change it at some point.

Regards

**Pull request merged**
