### PR TITLE
Fix typos in CHANGELOG.md

### PR DESCRIPTION
**Pull request by yuyi98**
This PR is to fix typos in CHANGELOG.md.

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks for the typo fixes, but lines longer than 80-100 chars should stay wrapped.

**Comment by yuyi98** [comment]
Ok, I'm going to fix that.

**Comment by dhonx** [comment]
Maybe we should add a little CI tool to check the line length

**Comment by spytheman** [comment]
Some MD formatting for links is broken now (because of the line length restriction), but they still work, and the formatting can be fixed, when we have a proper Markdown parser in cmd/tools/check-md.v .

**Pull request closed without merging**
