### PR TITLE
bf: add basic documentation

### PR DESCRIPTION
**Pull request by ciubotaru**
Added a README file listing and describing all methods and functions provided by 'bf' module.

### CODE REVIEW

**Comment by medvednikov** [comment]
Function documentation should be right before the function is defined, then vdoc can generate documentation for the entire module, like in Go:

```
// clearall clears (sets to zero) all bits in the array
fn clearall() {
}
```

An overview of the module must be placed in the first comment right after the module name:


```
module bf

/*
bf (BitField) is a module (shared library for V programming language) for
manipulating arrays of bits, i.e. series of zeroes and ones spread across an
array of storage units (unsigned 32-bit integers).

BitField structure
------------------

Bit arrays are stored in data structures called 'BitField'. The structure is
'opaque', i.e. its internals are not available to the end user. This module
provides API (functions and methods) for accessing and modifying bit arrays (see
'Functions').
*/
```

**Comment by ciubotaru** [comment]
We need documentation for creating documentation :-)

**Comment by medvednikov** [comment]
Done: https://vlang.io/docs#writing_docs

:)

**Comment by iredmail** [comment]
> Done: https://vlang.io/docs#writing_docs

Can we emit the function name in comment line? It's pretty command that we will rename functions, it will save programmer some time to change function name in multiple places.

### Current

```
// clearall my comment here
fn clearall() {}
```

### Suggested

```
// my comment here without starting with function name
fn clearall() {}
```

**Comment by ciubotaru** [comment]
@medvednikov, thank you for your feedback. I updated documentation, as you advised.

**Comment by medvednikov** [comment]
@iredmail the idea is to make it greppable: `grep "// clearall "`

**Comment by iredmail** [comment]
@medvednikov I think it’s not necessary because you can grep the function instead:

grep “fn clearall”

**Comment by medvednikov** [comment]
Won't work with methods :)

**Comment by medvednikov** [comment]
Also: 

```
Notice this comment is a complete sentence that begins with the name of the element it describes. This important convention allows us to generate documentation in a variety of formats, from plain text to HTML to UNIX man pages, and makes it read better when tools truncate it for brevity, such as when they extract the first line or sentence.
```

https://blog.golang.org/godoc-documenting-go-code

**Pull request merged**
