### PR TITLE
V script: Add example

### PR DESCRIPTION
**Pull request by Delta456**

### CODE REVIEW

**Comment by medvednikov** [comment]
It's better to write something that actually does something on the user's machine.

Create some files, move them around, and remove.

**Comment by Delta456** [comment]
ok

**Comment by Delta456** [comment]
Ready to merge?

**Comment by medvednikov** [comment]
It still moves around non-existent files:

mv('v.exe', 'bin/v.exe')
rm('tmp.c')

**Comment by spytheman** [comment]
Unfortunately, you can not do `println( ls('.') )` anymore.

**Pull request closed without merging**
