### PR TITLE
 checker: disallow `Result` callbacks functions like `map/filter/all/any`

### PR DESCRIPTION
**Pull request by Delta456**
Fixes https://github.com/vlang/v/issues/21049

### CODE REVIEW

**Comment by spytheman** [comment]
`.map(f()!)` should be allowed, since `f()!` is sugar for `f() or { return err }`, which is well defined.

**Comment by spytheman** [comment]
The checker however should check whether `f()!` returns a valid type . 
In other words, it should allow:
`f1()!`, for `fn f1() !Type {`
... but it should not allow:
`f2()!` for `fn f2() ! {`

**Comment by Delta456** [comment]
> The checker however should check whether `f()!` returns a valid type . In other words, it should allow: `.map( f1()! )`, for `fn f1() !Type {` ... but it should not allow: `.map( f2()! )` for `fn f2() ! {`

Fair

**Review by spytheman — APPROVED** [review]
Excellent work.
Sorry for the delay.

**Comment by ttytm** [comment]
Wanted to try to utilize it instead of an or block, I'm still running into a builder error here:

https://github.com/vlang/v/blob/bccf660456713122e1db652a0b729ff814ba86c4/vlib/x/json2/decoder.v#L292-L294

**Pull request merged**
