### PR TITLE
orm: refactor insert part of orm_stmt_gen method

### PR DESCRIPTION
**Pull request by ppshobi**
This is a super small refactoring on the ORM part of vlang. I have refactored the `insert` statement generation part of the `orm_stmt_gen`. This should make the piece of code a little more readable. If something like this is welcome I could go ahead and try to clean up the ORM and add more SQL functionalities (Of course through other PRs as required). 

Also, I haven't touched the tests since this is just a refactor

This is more of testing the water type of PR.

### CODE REVIEW

**Review by ppshobi — COMMENTED** [review]
@LouisSchmieder any reason why the variable name `para` is used for the quotation marks? as far as I can see it accepts a single quote only

**Comment by spytheman** [comment]
It seems that the different drivers do use different characters:
```
vlib/mysql/orm.v:93:    query := orm.orm_stmt_gen(table, '`', .insert, false, '?', 1, data, orm.QueryData{})
vlib/mysql/orm.v:98:    query := orm.orm_stmt_gen(table, '`', .update, false, '?', 1, data, where)
vlib/mysql/orm.v:103:   query := orm.orm_stmt_gen(table, '`', .delete, false, '?', 1, orm.QueryData{}, where)
vlib/sqlite/orm.v:51:   query := orm.orm_stmt_gen(table, '`', .insert, true, '?', 1, data, orm.QueryData{})
vlib/sqlite/orm.v:56:   query := orm.orm_stmt_gen(table, '`', .update, true, '?', 1, data, where)
vlib/sqlite/orm.v:61:   query := orm.orm_stmt_gen(table, '`', .delete, true, '?', 1, orm.QueryData{}, where)
vlib/pg/orm.v:30:       query := orm.orm_stmt_gen(table, '"', .insert, true, '$', 1, data, orm.QueryData{})
vlib/pg/orm.v:35:       query := orm.orm_stmt_gen(table, '"', .update, true, '$', 1, data, where)
vlib/pg/orm.v:40:       query := orm.orm_stmt_gen(table, '"', .delete, true, '$', 1, orm.QueryData{}, where)
```

**Comment by spytheman** [comment]
only `vlib/orm/orm_fn_test.v` uses `"'"`

**Comment by ppshobi** [comment]
Yes yes. But why is it named `para`, an apt name would be `quote` right? or is there a meaning behind `para`?

**Comment by spytheman** [comment]
> Yes yes. But why is it named `para`, an apt name would be `quote` or `quote_char` right? or is there a meaning behind `para`?

I agree - these are more meaningful/clear names.

**Pull request merged**
