### PR TITLE
fmt: sort syms in selective imports

### PR DESCRIPTION
**Pull request by zakuro9715**
Sort syms in selective imports alphabetically

### CODE REVIEW

**Comment by spytheman** [comment]
why is that needed?

**Comment by zakuro9715** [comment]
I think imports should be sorted like go fmt. It makes it easy to see which module are being imported.

Because it is easy to implement, I implemented sorting for only selective imports for now. If this PR is accepted, sorting all imports will be implemented in future PR

**Comment by spytheman** [comment]
The list of imported modules in any given .v file should be short enough, to not need sorting at all imho. 
Instead keeping the intent of the writer seems more appropriate to me.
The same logic applies to the list of imported symbols.
@medvednikov what do you think?

**Comment by spytheman** [comment]
Also there were bugs caused by different import orders in recent history. 
These should not happen in theory, but they do in practice :-| . 
Implementing sorting will make working around such bugs needlessly difficult.

**Comment by medvednikov** [comment]
hm I don't mind either way

I don't think it's a big deal

we sort sum type declarations `type X = A | B| C`, so why not?

**Pull request merged**
