### PR TITLE
json2: Optional json2 encode

### PR DESCRIPTION
**Pull request by enghitalo**
```v
struct EmployeeOptional {
pub mut:
	name      string
	last_name ?string = none
	age       ?int    = none
	salary    ?f32    = none
	title     JobTitle
}

fn test_simple_optional() {
	x := EmployeeOptional{
		name: 'Peter'
	}
	s := json.encode<EmployeeOptional>(x)
	assert s == '{"name":"Peter","title":"manager"}'
}
```

### CODE REVIEW

**Comment by enghitalo** [comment]
```v
struct EmployeeOptional {
pub mut:
	name      ?string
}

x := EmployeeOptional{
	name: 'Peter'
}
```
will return `{"name":"Option('Peter')"}` :cry:

**Comment by enghitalo** [comment]
- Can someone help me with this errors? @spytheman, @shove70 :cry: 
`error: cannot convert 'struct _option_string' to 'struct string'`

- All test pass if I comment `test_simple_optional`

- cgen option string for `encode_value_with_level` function
```C
VV_LOCAL_SYMBOL _result_void x__json2__Encoder_encode_value_with_level_T__option_string(x__json2__Encoder* e, string val, int level, io__Writer* wr);
```
```C

VV_LOCAL_SYMBOL _result_void x__json2__Encoder_encode_value_with_level_T__option_string(x__json2__Encoder* e, string val, int level, io__Writer* wr) {
	#if 20 == 20
	{
		_result_void _t2 = x__json2__Encoder_encode_string(e, val, wr);
		if (_t2.is_error) {
			_result_void _t3;
			memcpy(&_t3, &_t2, sizeof(_result));
			return _t3;
		}
		
 ;
	}
	#elif 20 == 105
	{
	}
	#elif 20 == 106
	{
	}
	#elif 20 == 179
	{
	}
	#elif 20 == 182 || 20 == 18 || 20 == 15 || 20 == 16 || 20 == 5 || 20 == 6 || 20 == 7 || 20 == 8 || 20 == 10 || 20 == 11 || 20 == 12 || 20 == 13
	{
	}
	#elif 0
	{
	}
	#elif 20 == 37
	{
	}
	#elif 0
	{
	}
	#elif 0
	{
	}
	#else
	{
		return (_result_void){ .is_error=true, .err=_v_error( str_intp(2, _MOV((StrIntpData[]){{_SLIT("cannot encode value with "), /*115 &string*/0xfe10, {.d_s = _SLIT("string")}}, {_SLIT(" type"), 0, { .d_c = 0 }}}))), .data={EMPTY_STRUCT_INITIALIZATION} };
	}
	#endif
	return (_result_void){0};
}
```

**Comment by shove70** [comment]
I will complete comptime "or_block" as soon as possible, and your problems may disappear after completion

**Comment by ylluminate** [comment]
@shove70 happen to have any luck yet?

**Comment by shove70** [comment]
> @shove70 happen to have any luck yet?

Ha ha, I'm not lucky at all. A version has been made, It which requires that all structure events have the same optional type, so I have not submitted the PR for the time being. I am considering whether there is a better way, such as changing the following language features:

1. When the user uses ```or {}, !, ?```, the compiler only generates the corresponding C code for the method whose return type is ```optimoanl or result```.

2. When the user does not use ```or {}, !, ?```, the compiler will only generate the corresponding C code for methods whose return type is not ```optimoanl or result```.

In addition, my daughter was hospitalized and I was accompanying her in the hospital during this period, so my work efficiency was very low. Forgive me, guys. I'll try my best.

**Comment by Delta456** [comment]
> In addition, my daughter was hospitalized and I was accompanying her in the hospital during this period, so my work efficiency was very low. Forgive me, guys. I'll try my best.

I am so sorry to hear this I hope she gets well soon.

**Comment by shove70** [comment]
@Delta456, Thanks! ❤️

**Comment by ylluminate** [comment]
So sorry @shove70 - our family has also been taking our turns with a nasty flu. Hope you're all well soon.

**Comment by JalonSolov** [comment]
Never apologize for putting your family first!  Hopefully she will make a swift recovery.

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by Delta456** [comment]
@enghitalo Amazing work 💯

**Pull request merged**
