### PR TITLE
cgen: sort const array init order (fix #14748)

### LINKED ISSUE #14748: sort array consts failed
```v
const (
	cst3 = [[[cst1, cst2]]]
	cst1 = [11]
	cst2 = [22]
)

fn main() {
	println(cst3)
}

PS D:\Test\v\tt1> v run .
[[[[], []]]]
```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR sort const array init order (fix #14748).

- Sort const array init order.
- Add test.

```v
const (
	cst3 = [[[cst1, cst2]]]
	cst1 = [11]
	cst2 = [22]
)

fn main() {
	println(cst3)
	assert cst3 == [[[[11], [22]]]]
}

PS D:\Test\v\tt1> v run .
[[[[11], [22]]]]
```

### CODE REVIEW

**Comment by spytheman** [comment]
Here is a minimum case for the vshader.v failure:
```v
import os

const (
	shdc_full_hash   = '33d2e4cc26088c6c28eaef5467990f8940d15aab'
	tool_version     = '0.0.1'
	tool_description = "Compile shaders in sokol's annotated GLSL format to C headers for use with sokol based apps"
	tool_name        = os.file_name(os.executable())
	cache_dir        = os.join_path(os.cache_dir(), 'v', tool_name)
	runtime_os       = os.user_os()
)

const (
	supported_hosts  = ['linux', 'macos', 'windows']
	supported_slangs = [
		'glsl330', // desktop GL
		'glsl100', // GLES2 / WebGL
		'glsl300es', // GLES3 / WebGL2
		'hlsl4', // D3D11
		'hlsl5', // D3D11
		'metal_macos', // Metal on macOS
		'metal_ios', // Metal on iOS device
		'metal_sim', // Metal on iOS simulator
		'wgpu', // WebGPU
	]
	default_slangs   = [
		'glsl330',
		'glsl100',
		'glsl300es',
		// 'hlsl4', and hlsl5 can't be used at the same time
		'hlsl5',
		'metal_macos',
		'metal_ios',
		'metal_sim',
		'wgpu',
	]

	shdc_version     = shdc_full_hash[0..8]
	shdc_urls        = {
		'windows': 'https://github.com/floooh/sokol-tools-bin/raw/$shdc_full_hash/bin/win32/sokol-shdc.exe'
		'macos':   'https://github.com/floooh/sokol-tools-bin/raw/$shdc_full_hash/bin/osx/sokol-shdc'
		'linux':   'https://github.com/floooh/sokol-tools-bin/raw/$shdc_full_hash/bin/linux/sokol-shdc'
	}
	shdc_version_file = os.join_path(cache_dir, 'sokol-shdc.version')
	shdc              = shdc_exe()
	shdc_exe_name     = 'sokol-shdc.exe'
)

struct Options {
	show_help    bool
	verbose      bool
	force_update bool
	slangs       []string
}

struct CompileOptions {
	verbose     bool
	slangs      []string
	invoke_path string
}

fn main() {
	dump(shdc_full_hash)
	dump(tool_version)
	dump(tool_description)
	dump(tool_name)
	dump(cache_dir)
	dump(runtime_os)
	dump(supported_hosts)
	dump(supported_slangs)
	dump(default_slangs)
	dump(shdc_version)
	dump(shdc_urls)
	dump(shdc_version_file)
	dump(shdc)
	dump(shdc_exe_name)
	dump(os.wd_at_startup)
	exit(1)
}

// shdc_exe returns an absolute path to the `sokol-shdc` tool.
// Please note that the tool isn't guaranteed to actually be present, nor is
// it guaranteed that it can be invoked.
fn shdc_exe() string {
	return os.join_path(cache_dir, shdc_exe_name)
}
```

**Comment by spytheman** [comment]
A temporary workaround, is if we change `shdc_exe` in cmd/tools/vshader.v to:
```v
fn shdc_exe() string {
    return os.join_path(os.cache_dir(), shdc_exe_name)
}
```

**Comment by spytheman** [comment]
in Go:
```go
package main

var b = fb()
var a = fa()
func fa() int { return b + 1 }
func fb() int { return a + 1 }

func main() {
   println(a)
   println(b)
}
```
prints:
```
# command-line-arguments
./zz.go:3:5: initialization loop:
        /v/cleanv/zz.go:3:5: b refers to
        /v/cleanv/zz.go:6:6: fb refers to
        /v/cleanv/zz.go:4:5: a refers to
        /v/cleanv/zz.go:5:6: fa refers to
        /v/cleanv/zz.go:3:5: b
```

**Comment by yuyi98** [comment]
ok, I see.
@spytheman  Thanks !!!
I'll try to parse fn_call's body.

**Comment by spytheman** [comment]
> ok, I see. @spytheman Thanks !!! I'll try to parse fn_call's body.

You are welcome, I am happy to help.

I think that should not be done in the parser, but in the checker - the parser does not have the complete information (for example the const may be declared in one file, while the function is in another).

**Comment by yuyi98** [comment]
I have implemented it, but it raises other issues.
```v
import os

const (
	shdc_exe_name = 'sokol-shdc.exe'
	tool_name     = os.file_name(os.executable())
	cache_dir     = os.join_path(os.cache_dir(), 'v', tool_name)
	shdc          = shdc_exe()
)

fn main() {
	dump(cache_dir)
	dump(shdc)
}

fn shdc_exe() string {
	return os.join_path(cache_dir, shdc_exe_name)
}

PS D:\Test\v\tt1> v run .
[.\\tt1.v:11] main.cache_dir: C:\Users\yuyi9\.cache\v\tt1.exe
[.\\tt1.v:12] main.shdc: \sokol-shdc.exe
```

**Comment by yuyi98** [comment]
It's okay, I'll push another PR to fix them.

**Pull request merged**
