### PR TITLE
examples/audio: fix audio example to work on FreeBSD

### PR DESCRIPTION
**Pull request by kimshrier**
This just adds the configuration needed for compiling the audio example.

### CODE REVIEW

**Comment by Larpon** [comment]
@kimshrier good work! Any chance these changes could end up in sokol upstream?

**Comment by kimshrier** [comment]
I haven't tried pushing this change upstream.  I'll look into it.

**Comment by kimshrier** [comment]
I pushed this change upstream and it was merged. [1055](https://github.com/floooh/sokol/pull/1055)

**Comment by JalonSolov** [comment]
So instead of this PR, we need one to update to the latest sokol, right?

**Comment by kimshrier** [comment]
yes

**Pull request merged**
