### PR TITLE
fmt: fix optional formatting

### LINKED ISSUE #4524: vfmt formats an option ref type to &?SomeType
**V version:**  V 0.1.26 27e0474  
**OS:**  Windows 10 x64 1909

**What did you do?**
v fmt a source file with an option return type of a ref struct

**What did you expect to see?**
pub fn parse_epoch_ms(epoch u64) ?&SomeType
 
**What did you see instead?**
pub fn parse_epoch_ms(epoch u64) &?SomeType

### PR DESCRIPTION
**Pull request by krischerven**
fixes #4524

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks

A small fmt_keep test please

**Comment by krischerven** [comment]
Added

**Comment by medvednikov** [comment]
tests/optional_keep.vv

**Comment by krischerven** [comment]
Renamed

**Pull request merged**
