### PR TITLE
vlib builtin: add string.count(substr)

### PR DESCRIPTION
**Pull request by joe-conigliaro**
this adds string.count(substr) which counts occurrences of substr in s

### CODE REVIEW

**Comment by avitkauskas** [comment]
Does this actually work? How can you modify `s` in your code?
```s = s.right(i+substr.len)```

**Comment by medvednikov** [comment]
@avitkauskas it works, but it's a bug in the compiler.

Function arguments are mutable by default, I need to fix it asap.

The string is still passed by value, so the original won't be modified.

**Comment by joe-conigliaro** [comment]
I did it on purpose not to allocate another string, since it worked

**Comment by ntrel** [comment]
`mut tmp := s` should not heap allocate, it should share a pointer to the same allocation.
(The optimiser should be able to unify s and tmp).

**Comment by medvednikov** [comment]
if s is a string, that's what already happens.

**Pull request merged**
