### PR TITLE
doc: move operator overloading section, inline assenbly section, hot code reloading section

### PR DESCRIPTION
**Pull request by kahsa**
more appropriate grouping.
and in order to separate C related sections more clearer.

I have a suggestion: how about creating a new section called "V and C or Other Languages"?

I have a suggestion regarding the overall structure.

1. essential information for users new to V
2. information for users who are serious about using V, such as creating modules
3. information that not all V users will use

1 is really just the basics.
2 is the detailed information that most users want.
3 is core information that only some users are interested in

I think that thorough compartmentalization will make the document easier to read and find.
Currently, these different levels of information are mixed together.
I know it is very hard work tho..

### CODE REVIEW

**Review by spytheman — COMMENTED** [review]
The ordering of these seems entirely subjective to me.

I do not see the objective reason for that change - tomorrow, someone may do the opposite ordering in another PR.

**Comment by spytheman** [comment]
About the suggestion, you can create a discussion about it if you want.

**Comment by kahsa** [comment]
> The ordering of these seems entirely subjective to me.

mainly this reason.

> in order to separate C related sections more clearer.

Then I ask what is the reason for the current placement order?
I do not have to stick to the order in which I have arranged them.
The purpose is as stated above.
What do you think is the best order to achieve that goal? @spytheman

**Comment by kahsa** [comment]
> About the suggestion, you can create a discussion about it if you want.

OK, I understand that you don't have any idea.

**Comment by kahsa** [comment]
> tomorrow, someone may do the opposite ordering in another PR.

That's exactly the kind of inaction that causes inaction. lol
If there is a clear rationale for the order, you can simply provide that rationale and reject tomorrow's PR.
It is your judgment that seems rather subjective.

**Comment by kahsa** [comment]
@spytheman I'm waiting for your answer.

**Comment by kahsa** [comment]
It is very easy to assess others' judgments as subjective.
You don't have to think about anything. Just feelings.

**Comment by spytheman** [comment]
> It is very easy to assess others' judgments as subjective.
> You don't have to think about anything. Just feelings.

That is what I want to avoid as much as possible - feelings. I prefer clearly stated reasons.

**Comment by spytheman** [comment]
> What do you think is the best order to achieve that goal? @spytheman
I do not know, I have not thought about it.

> You seem to have considered looking at it subjectively, but to me the current order seems unthinking. They are simply arranged in the order they were written, and seem to be arranged for no particular reason.

Yes, I agree 100% with that. Still, it is the status-quo, and changing for the better requires reasoning.

**Pull request closed without merging**
