### PR TITLE
cgen: fix missing panic message for 'option not set' on debug

### LINKED ISSUE #18167: print, println of Option with value "none" panics
### Describe the bug

Panic when a print statement is passed an unwrapped Optional none.

### Expected Behavior

Print ""

### Current Behavior

panic

### Reproduction Steps

```
a := ?int(1234)
println(a?)

b := ?int(none)
println(b?)

---
1234
================ V panic ================
   module: main
 function: main()
  message: 
     file: code.v:1
   v hash: e738d67
=========================================
/tmp/v_60000/../../../../../../home/admin/v/vlib/builtin/builtin.c.v:68: at panic_debug: Backtrace
/tmp/v_60000/../../../../../../box/code.v:8: by main__main
/tmp/v_60000/../../../../../../tmp/v_60000/code.2248510540689415407.tmp.c:17331: by main
Exited with error status 1
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### V version

3.4

### Environment details (OS name and version, etc.)

V Playground

### PR DESCRIPTION
**Pull request by felipensp**
Fix #18167

This PR makes V emits "option not set()" error message for unwrapping a none value when built with `-cg` option.

### <samp>🤖 Generated by Copilot at 6077c69</samp>

Fix a bug in the C backend of the V compiler that causes a segmentation fault when printing empty error messages. Modify the `panic_debug` function call in `vlib/v/gen/c/cgen.v` to pass a default message instead of an empty string.

### <samp>🤖 Generated by Copilot at 6077c69</samp>

* Fix bug where empty error messages cause segmentation fault in stack trace printing ([link](https://github.com/vlang/v/pull/18168/files?diff=unified&w=0#diff-1327b3543e8530b1f5a8352284a6ad6acd3565e323c845af1fb372d34faafcecL5961-R5961))

### CODE REVIEW

**Comment by spytheman** [comment]
Please add a small test for it, so that it does not regress silently.

**Comment by felipensp** [comment]
> Please add a small test for it, so that it does not regress silently.

How make the test ignore the V hash?

image

**Comment by spytheman** [comment]
> > Please add a small test for it, so that it does not regress silently.
> 
> How make the test ignore the V hash? @spytheman 
> 
> image
> 

edit out/omit the last lines in the .out file (the ones that change).
The .out files are searched not for an exact match, but by a prefix search.

**Comment by medvednikov** [comment]
Nice one!

**Pull request merged**
