### PR TITLE
checker: require binary operands for &&, ||

### LINKED ISSUE #6438: OR || operation not returning first non-zero operation with integers
**V version:** V 0.1.29 0f1c484

**OS:** Linux

**What did you do?**
```
println(2 || 1)
```

**What did you expect to see?**
```
2
```
 
**What did you see instead?**
```
1
```

**Note**
The output is 1 due to how C works, it returns a boolean on these operations, (`0` == `false`, `1` == `true`):
`0 || 0` => `0`
`2 || 0` => `1`
`0 || 3` => `1`
`2 || 3` => `1`

`0 && 0` => `0`
`2 && 0` => `0`
`0 && 3` => `0`
`2 && 3` => `1`

### PR DESCRIPTION
**Pull request by ntrel**
This follows Go and Rust.
Fixes #6438.

### CODE REVIEW

**Comment by Delta456** [comment]
@ntrel It is not decided if we should this or not. I think its better to wait for others decision especially @medvednikov's on this.

**Comment by ntrel** [comment]
@Delta456 It would be inconsistent to allow the operators on integers outside of `if` but not inside `if`:
```
../old/ifint.v:1:1: error: non-bool type `any_int` used as if condition
    1 | if 1 && 2 {
      | ~~~~~~~~~
    2 |
    3 | }
```

**Comment by ntrel** [comment]
I've just seen the existing check inside an `if` condition is more subtle, and this overrides that. So this probably needs modifying.

**Comment by medvednikov** [comment]
@Delta456 it's not undecided. Bools and ints have always been separate in V.

**Comment by Delta456** [comment]
@medvednikov Ok then

**Comment by medvednikov** [comment]
Looks like there are some offenders :)

```
examples/2048/2048.v:546:16: error: left operand for `||` is not a boolean
  544 | 
  545 | fn (mut app App) resize() {
  546 |     mut s := sapp.dpi_scale() || 1
```

**Pull request merged**
