### PR TITLE
parser: parse `map{key_expr: val_expr}`

### PR DESCRIPTION
**Pull request by ntrel**
Part of https://github.com/vlang/v/issues/8596.

Alex approved the syntax here: https://discord.com/channels/592103645835821068/592320321995014154/806974618296254525

It's needed to allow variable names as keys in a map literal, and it also allows `const` names, expressions etc. I added a workaround to allow `map{field_name: ` in `builtin/map.v` as a struct init, the `map` struct isn't needed anywhere else.

* *parser: only parse `field: expr` function args when calling fn* - before any expression that started with a name and colon got parsed as a struct init, so I had to fix that.
* *checker: fix duplicate map key check* - now only literals get checked
* *Add test for variables as keys in map literal*

### CODE REVIEW

**Comment by ntrel** [comment]
BTW I'll do the deprecation of `{'key': expr}` and updating `vfmt` to add the `map` prefix to map literals in a separate pull.

**Comment by nyx-litenite** [comment]
Does this allow enums as map keys? if not it does **NOT** fix my issue which Alex M said is valid ([enums as maps keys](https://discord.com/channels/592103645835821068/592294828432424960/807433458082644028)), so it'll be great to merge this but don't close my issue if enums can't be used.

**Comment by ntrel** [comment]
@nyx-litenite Sorry, you are right this doesn't implement allowing enum keys for maps. I have now added the `const` map and `const` key as a test from your issue though.

**Comment by nyx-litenite** [comment]
No worries :) was just making sure that I didn't misunderstand and that the issue got closed/left open as needed :D thanks for your work on this!

**Pull request merged**
