### PR TITLE
vlib: transfer module intro to readme; normalize comments

### PR DESCRIPTION
**Pull request by nedpals**
- With the inclusion of #5252, it now transfers some of the module introductions to their respective README's.
- Fixed comments for better output.

### CODE REVIEW

**Comment by JalonSolov** [comment]
I know it's more work, but I'd suggest stripping leading <whitespace>*<whitespace> from the lines while vdoc is processing them, rather than trying to edit every file that might use that style of commenting.

It is a _very_ common style, and you can't guarantee it won't be used in many, many modules in the future.

**Comment by spytheman** [comment]
Yeah, auto stripping leading * from /* */ comments would be good indeed, many editors have an option to generate such comments, and they are very widely used.

**Comment by spytheman** [comment]
That may happen in another PR though.

**Comment by nedpals** [comment]
I have a commented code that was merged from PR #5252 that strips that but yeah it will be in another PR.

**Pull request merged**
