### PR TITLE
freestanding: Add core linux syscalls and associated tests

### PR DESCRIPTION
**Pull request by bogen85**
I don't expect this to be accepted right away. I just need a code review and to explain some things before continuing.

1) I currently can't do freestanding tests via the built in framework as it attempts to use the C flavor as well, which causes conflicts.
2) I currently don't have the malloc/free pulled in. (I do have it tested separately in freestanding, but I need to make sure you will accept the kind of work of I'm doing first before continuing down this path).
3) I added some sample tests to  examples/freestanding/tests/ because I currently can't use the built in testing framework. (So unless I get advise on making the existing test framework working, I will continue to put my tests there, unless you have a better interim solution).
4) Every function I have added I will write a test for (print/println using dup2 and pipes, panic using pipes as well and forking and checking the exit code, and so forth).

### CODE REVIEW

**Comment by bogen85** [comment]
1) I see it is failing v to c tests... I guess that is to be expected...
2) I can comment out my fork and getpid and try to run a test with "v --enable-globals -freestanding test" and then it complains about needing malloc.
3) I currently use globals in some of the tests because I don't have another way of creating arrays (because of no malloc) and I need arrays for some of the tests.

**Comment by medvednikov** [comment]
Amazing job @bogen85 

I'll definitely merge this.

Indeed, freestanding tests are broken right now.

CI runs all examples, so you can move examples directory to bare/ for now.

**Comment by bogen85** [comment]
Alright, I had to do some interim renaming (syscallN to sys_callN) and write to sys_write (and related) to avoid conflict with existing code.

When this gets to the point where existing code can start using it, the interim naming can be reverted.
(Unless you have a better suggestion)

**Comment by bogen85** [comment]
I will now continue adding tests for these core syscall wrappers and functions that use them.

**Comment by medvednikov** [comment]
Ok, so merging after  all the tests?

**Comment by bogen85** [comment]
I writing the rest of the tests now.

**Comment by bogen85** [comment]
So far I've written tests for:   sys_pipe  sys_write  sys_read sys_close
I'm writing the test for sys_open now.
If you want, you can merge after I finish the test for open?
I will keep working on the other tests.
That will give some more functionality (and print/println will work, and panic will work better).
sys_exit works, I just don't have a test for it yet.

**Comment by bogen85** [comment]
I added the test for sys_open and it is passing (well, not multiple checks as far as several error returns).
Current my wrappers don't act exactly like the libc ones in regard to return value, so they have the raw syscall behavior.
  1) there is no errno
  2) if zero is the expected value, a value > 0 is the error code
  3) if a >=0 is a good value, then for errors, a negative error_code is returned

**Pull request merged**
