### PR TITLE
gen: initial option auto str support

### PR DESCRIPTION
**Pull request by danieldaeschle**
initial Option printin /auto str.
Doesn't work compeltely, But since Option types are not supported in all scenarions this might not be possible currently.

This fixes https://github.com/vlang/v/issues/6724

### CODE REVIEW

**Comment by Delta456** [comment]
Can you also a `str` method for printing `none`?

**Comment by spytheman** [comment]
@Delta456 see create_option_none in the added tests

**Comment by Delta456** [comment]
I meant just doing `println(none)` directly i.e. not using any function or we will disallow that perhaps?

**Comment by danieldaeschle** [comment]
I can do it in  another pr

**Comment by spytheman** [comment]
yes, a separate PR would be better.

**Comment by danieldaeschle** [comment]
why not merging?

**Comment by Delta456** [comment]
Let's wait for Alex to merge

**Pull request merged**
