### PR TITLE
map: small cleanup

### PR DESCRIPTION
**Pull request by ka-weihe**
Small cleanup 🙂

### CODE REVIEW

**Comment by medvednikov** [comment]
You've reverted vfmt changes. This will be overwritten since vfmt is run on every single file.

**Comment by medvednikov** [comment]
Since you also modified some comments, I recommend simply running `v fmt -w map.v`

**Comment by ka-weihe** [comment]
Okay

**Comment by medvednikov** [comment]
Thanks. Vfmt has some bugs like a missing space after `unsafe`, these will be fixed.

**Pull request merged**
