### PR TITLE
tests: unify all temporary files/folders under `$VTMP/v`, so they can be cleaned by `v wipe-cache` too

### PR DESCRIPTION
**Pull request by spytheman**

### CODE REVIEW

**Comment by JalonSolov** [comment]
There was discussion in the past of making the combined area default to `<user home dir>/.v` or similar, as some systems don't allow writing to /tmp.

Any thoughts on making that the default for this PR?

**Comment by Larpon** [comment]
> There was discussion in the past of making the combined area default to `<user home dir>/.v` or similar, as some systems don't allow writing to /tmp.
> 
> Any thoughts on making that the default for this PR?

Please, no temporary files in places you don't expect them. They tend to pile up and use precious space in places where the system don't know about them (non-standard locations). If /tmp is not writeable, maybe implement a fallback list instead - it can be cached when found to not consume to much cycles. I could live with `~/.cache/v` as a fallback if it must be under home 🙂

IIRC chrome once had it's ridicules huge tmp dir hidden deep under ~/.chrome somewhere. I lost gigabytes of space, that I could've been used better, that slipped my radar for years 🙂

**Comment by JalonSolov** [comment]
I believe the request to put stuff under the user's home dir was from the people using NixOS.  It has some _very_ strict rules about where files can/cannot be put.

Basically, no matter what is done, not everyone will be happy.  That's why `VTMP` will be available - those who don't like the default can change it (without having to modify the code).

I think as long as it's documented properly, it'll be fine.

**Comment by spytheman** [comment]
Setting `VTMP` can be used to change the prefix. This PR does not change that. 

It only makes it so that all tests and their temporary files, are not written in say `/tmp`, and various subfolders under it, but in `/tmp/v`, so only that single folder can be removed by `v wipe-cache`.

**Comment by spytheman** [comment]
> I think as long as it's documented properly, it'll be fine.

I will document all the used env variables in a separate `v help env` topic soon.
It will be mentioned in the main `v help` screen too.

**Pull request merged**
