### PR TITLE
os: Make windows allocations more consistent & LocalFree args_list

### PR DESCRIPTION
**Pull request by emily33901**
If max is 512 then allocate `max * sizeof(wchar_t)` which should be max*2 on all supported platforms.

### CODE REVIEW

**Comment by medvednikov** [comment]
You can use ` MAX_PATH * sizeof(wchar_t)` in V instead of magic consts.

**Comment by emily33901** [comment]
This is true but MAX_PATH on windows should be 260 and V defines it as 4096 so im not sure whats best to do - No reason to allocate the extra space if (as it is right now) its not going to be freed?

**Comment by medvednikov** [comment]
The best way is to have 

```
// os_nix.v
const (
  MaxPath = 4096
)

// os_win.v
const (
  MaxPath = 260
)
```

**Comment by medvednikov** [comment]
I'm wrapping up memory management right now by the way.

**Pull request merged**
