### PR TITLE
checker: disallow `mut_ptr = &immutable_var`

### PR DESCRIPTION
**Pull request by ntrel**
Previously only initialization was detected.
Also add fn Ident.is_mut().

### CODE REVIEW

**Comment by Larpon** [comment]
I've had problems with CI not running on PRs on vlang/sdl as well I think there's GitHub issues:
https://www.githubstatus.com/

**Comment by spytheman** [comment]
Yeah, it is probably a github actions issue. It seems to be working now.

**Comment by ntrel** [comment]
Thanks for fixing the tests. (I was busy until now).

**Comment by spytheman** [comment]
> Thanks for fixing the tests. (I was busy until now).

Happy to help. Thanks for the useful check, that already caught bugs in the test suite.

**Pull request merged**
