### PR TITLE
cgen: fix go call anon fn with closure (fix #15526, #15634)

### LINKED ISSUE #15526: When an anonymous function has closure parameters, it crashes when called in a thread
OS: macos, macOS, 12.5.1, 21G83
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
CC version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

getwd: /Users/shove/Projects/Temp/v/v_test_001
vmodules: /Users/shove/.vmodules
vroot: /usr/local/v
vexe: /usr/local/v/v
vexe mtime: 2022-08-25 08:16:53
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 c662431

Git version: git version 2.32.1 (Apple Git-133)
Git vroot status: 0.3-395-gc662431c
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 46662e20

**What did you do?**

```v
import time

fn main() {
	a := 1

	b := fn [a] () {
		println(a)
	}

	go b()
	time.sleep(10 * time.second)
}

```

**What did you expect to see?**

 ```
1
```

**What did you see instead?**

```
signal 11: segmentation fault
0   libsystem_platform.dylib            0x00007ff81f616dfd _sigtramp + 29
1   ???                                 0x0000000000000000 0x0 + 0
2   v_test_001                          0x000000010f4216d1 anon_fn_843cb5e832d2b9f1__1744_thread_wrapper + 17
3   v_test_001                          0x000000010f46293c GC_start_routine + 100
4   libsystem_pthread.dylib             0x00007ff81f6014e1 _pthread_start + 125
5   libsystem_pthread.dylib             0x00007ff81f5fcf6b thread_start + 15
```

### LINKED ISSUE #15634: Started thread can't access variables from the scope they were created in using closure (SIG fault)
**V version:** 
V 0.3.0 70f4664
**OS:** 
linux, Ubuntu 22.04.1 LTS

**What did you do?**
```v
m := {
  "key1": 1,
  "key2": 2
}

h := go fn [m] () {
  println(m["key1"])
}()

h.wait()
````
**What did you expect to see?**
```sh
 1
```
**What did you see instead?**
```sh
v run main.v 
signal 11: segmentation fault
/tmp/v_1000/main.14547779162727104743.tmp.c:7254: at print_backtrace: Backtrace
/tmp/v_1000/main.14547779162727104743.tmp.c:7329: by v_segmentation_fault_handler
7ff24cc39520 : by ???
/tmp/v_1000/main.14547779162727104743.tmp.c:2033: by anon_fn_aa4c3c73e99943ac__51_thread_wrapper
004620c1 : by ???
7cf8d34677de1338 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
01120300 : by ???
```

from the documentaion
> Inherited variables are copied when the anonymous function is created 

Not sure why this is not working as it should.

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix go call anon fn with closure (fix #15526, fix #15634).

- Fix go call anon fn with closure.
- Add test.

```v
fn main() {
	a := 1

	b := fn [a] () int {
		println(a)
		return a
	}

	g := go b()
	ret := g.wait()
	assert ret == 1
}

PS D:\Test\v\tt1> v run .
1
```
```v
fn main() {
	m := {
		'key1': 1
		'key2': 2
	}

	h := go fn [m] () int {
		println(m['key2'])
		return m['key2']
	}()

	ret := h.wait()
	assert ret == 2
}

PS D:\Test\v\tt1> v run .
2
```

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Excellent work!

**Comment by spytheman** [comment]
(The Doom CI failure is unrelated)

**Comment by shove70** [comment]
Worship

**Comment by yuyi98** [comment]
Thanks !!!

**Pull request merged**
