### PR TITLE
parser: enable simplified bool expression

### PR DESCRIPTION
**Pull request by hazohelet**
This PR enables Python-styled bool expressions such as `min <= value <= max`
Now users don't take the trouble of writing `min <= value && value <= max` instead of `min <= value <= max`
Type of `value` can be `string`
example:
```
month := 9
if 4 <= month < 7 { // same as `4 <= month && month < 7`
	println('warm')
}
else if 7 <= month < 9 { //same as `7 <= month && month < 9`
	println('hot')
}
else if month == 9 {
	println('warm')
}
else {
	println('cold')
}
```

### CODE REVIEW

**Comment by medvednikov** [comment]
This is nice, but it go against the "one way" principle a bit.

Thoughts?

**Comment by hazohelet** [comment]
I know you are surely right, but I guess this is similar to the idea of In Operator in terms of *simpler alternative* helping developers to write more *easy-to-read* source codes. The chances are low that this syntax will confuse developers, I guess.
```
if parser.token == .plus || parser.token == .minus || parser.token == .div || parser.token == .mult {
	... 
} 

if parser.token in [.plus, .minus, .div, .mult] {
	... 
} 
```

**Comment by iredmail** [comment]
I vote for “min <= value <= max”. :)

**Comment by hazohelet** [comment]
I personally like this syntax but it seems not to match the philosophy of V.

**Comment by medvednikov** [comment]
I mean not necessarily. The one way thing is not a strict rule. The `in` example you referenced proves that. There are other things like 3 different `for` loops, functions vs methods etc.

It's very hard to build a language where there's always only one way to do things.

**Comment by whoizit** [comment]
should be discussed. I'm for PR

**Comment by hazohelet** [comment]
There're both advantages and disadvantages in this feature, but eventually it's a matter of taste and is difficult to discuss logically, i think. 
It's ultimately up to @medvednikov

**Comment by joe-conigliaro** [comment]
:thin

**Comment by medvednikov** [comment]
Decided to close this for now.

If the community wants this feature, it's easy to bring it back. It's a small fix.

**Pull request closed without merging**
