### PR TITLE
parser/fmt: fix comments in structs/consts

### PR DESCRIPTION
**Pull request by ka-weihe**
This is an attempt to format comments in structs. Each field in the struct has responsibility for the comments before and on the same line as the field. Not sure if this is the way we want to handle comments - just an idea/attempt. Feedback will be appreciated.

Multiline comments need some fixing, but that is just in general - not only multiline comments in structs. 

I have also added support for multiple comments before const fields, so the formatter is now able to format `map.v` for example :slightly_smiling_face:, but I've not handled all cases for consts yet.

### CODE REVIEW

**Comment by medvednikov** [comment]
@ka-weihe I wanted to support multiple // comments by merging them into a single multiline comment, but with a flag, so that vfmt knows it's not a /* */ comment

I think it's simpler and faster than having []Comment

**Comment by ka-weihe** [comment]
Hmm okay, then I guess this PR is not of much use.

**Comment by medvednikov** [comment]
Well it fixes the problem, we can change the algorithm later.

**Comment by medvednikov** [comment]
Thanks!

**Comment by ka-weihe** [comment]
No problem. I agree using `Comment` is probably better than []Comment. I will fix it tomorrow maybe.

**Pull request merged**
