### PR TITLE
cgen: fix generics with embed generics (fix #8694)

### LINKED ISSUE #8694: generics: iterators produce invalid C code
**OS**: linux, "Fedora release 33 (Thirty Three)"
**CC version**: cc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)

**What did you do?**
Tried to print ints from a generic iterator
```v
struct Group<T> {
	len int
	val []T
mut:
	index int
}

fn group_new<T>(val ...T) Group<T> {
	mut arr := []T{cap: val.len}
	for i in val {
		arr << i
	}
	mut g := Group<T>{
			  len: val.len
			  val: arr
		  }  

	return g
}

fn (mut it Group<T>) next() ?T {
	if it.index >= it.len {
		return none
	}
	v := it.val[it.index]
	it.index++
	return v
}

gx := group_new<int>(1,2,3)
for x in gx {
   println(x)
}
```

**What did you expect to see?**
```bash
1
2
3
```
 
**What did you see instead?**
```bash
cgen error: could not generate string method T_str for type 'T'
```
Removing the `for..in` loop gives
```
/tmp/v/check.18053186489265579245.tmp.c:832:19: error: ‘T’ undeclared here (not in a function)
  832 |  byte data[sizeof(T)];
      |                   ^
/tmp/v/check.18053186489265579245.tmp.c:1413:1: error: unknown type name ‘main__Group_T_int’; did you mean ‘main__Group’?
 1413 | main__Group_T_int main__group_new_T_int(array_T val);
      | ^~~~~~~~~~~~~~~~~
      | main__Group
/tmp/v/check.18053186489265579245.tmp.c:1414:31: error: unknown type name ‘main__Group_T_T’; did you mean ‘main__Group’?
 1414 | Option_T main__Group_T_T_next(main__Group_T_T* it);
      |                               ^~~~~~~~~~~~~~~
      |                               main__Group
/tmp/v/check.18053186489265579245.tmp.c:1474:4: error: expected specifier-qualifier-list before ‘T’
 1474 |    T  data;
      |    ^
.
.
.


/tmp/v/check.18053186489265579245.tmp.c: At top level:
/tmp/v/check.18053186489265579245.tmp.c:8509:31: error: unknown type name ‘main__Group_T_T’; did you mean ‘main__Group’?
 8509 | Option_T main__Group_T_T_next(main__Group_T_T* it) {
      |                               ^~~~~~~~~~~~~~~
      |                               main__Group
/tmp/v/check.18053186489265579245.tmp.c: In function ‘main__main’:
/tmp/v/check.18053186489265579245.tmp.c:8525:2: error: unknown type name ‘main__Group_T_T’; did you mean ‘main__Group’?
 8525 |  main__Group_T_T gx = main__group_new_T_int(new_array_from_c_array(1, 1, sizeof(T), _MOV((T[1]){asd})));
      |  ^~~~~~~~~~~~~~~
      |  main__Group
/tmp/v/check.18053186489265579245.tmp.c:8525:96: error: expected ‘)’ before ‘{’ token
 8525 |  main__Group_T_T gx = main__group_new_T_int(new_array_from_c_array(1, 1, sizeof(
```
[full error message](https://github.com/vlang/v/files/5969619/error.txt)

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix generics with embed generics (fix #8694).

- Fix generics with embed generics.
- Add test.

```vlang
struct Group<T> {
	len int
	val []T
mut:
	index int
}

fn group_new<T>(val ...T) Group<T> {
	mut arr := []T{cap: val.len}
	for i in val {
		arr << i
	}
	mut g := Group<T>{
		len: val.len
		val: arr
	}

	return g
}

fn (mut it Group<T>) next<T>() ?T {
	if it.index >= it.len {
		return none
	}
	v := it.val[it.index]
	it.index++
	return v
}

fn main() {
	gx := group_new<int>(1, 2, 3)
	for x in gx.val {
		println(x)
	}
	assert gx.val == [1, 2, 3]
}

D:\Test\v\tt1>v run .
1
2
3
```

### CODE REVIEW

**Comment by nyx-litenite** [comment]
@yuyi98 if you're available, could you verify if this still works for you? I'm getting `a struct must have a 'next()' method to be an iterator'. Calling the next method directly works, so V is recognizing that it's there

**Comment by yuyi98** [comment]
Yes, It's still works, I just tested it.

**Comment by nyx-litenite** [comment]
Hmm, what compiler? It's failing for me when copied exactly

**Comment by yuyi98** [comment]
Win10, default tcc.

**Comment by nyx-litenite** [comment]
Ok, maybe something was up with my V install. Re-cloned and it seems to compile now. A bit odd, because I test this it failed, I v up'ed to make sure i was on most recent, and it still failed. Sry to bother. Thanks for your time!

**Comment by yuyi98** [comment]
I'll try the latest v version.

**Comment by JalonSolov** [comment]
On Windows, `v up` doesn't always work.  In fact, for me, it almost never did.  I always used `git pull` then `make.bat`.

It's because Windows locks the executable on disk while it's running, and you have to hit it with _just_ the right timing for `v up` to work, since it is trying to replace the running copy of v.  I was looking into how to make it work all the time, but then I decided to finally ditch Windows completely.  :-)

**Comment by nyx-litenite** [comment]
@JalonSolov ya, I'm on fedora and haven't had to reclone in quite awhile. That's why i didn't think about it until yuyi said it worked for him.

**Comment by nyx-litenite** [comment]
@yuyi98 actually just looking back at this as I was trying to match my new project's code to fix the error, this doesn't even use the custom iterator. You've got `for x in gx.val` where it should be `for x in gx`. You're just iterating over the inner array here...

**Comment by nyx-litenite** [comment]
I believe it's to do with the variadics. I change group_new to 
```
fn group_new<T>(val []T) Group<T> {
	// mut arr := []T{cap: val.len}
	// for i in val {
	// 	arr << i
	// }
	mut g := Group<T>{
		len: val.len
		val: val
	}

	return g
}
```

and this now compiles just fine. Definitely still needs to work w/ variadics still though

**Pull request merged**
