### PR TITLE
json: change json tests to tests folder

### PR DESCRIPTION
**Pull request by enghitalo**
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI1NTNjNDI3Y2M3NjgxYzYyNWNlNzIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.yeIyQ0OFV3ApZdPVIpvgedd_gDe365FwjhzPkn1FJ2s">Huly&reg;: <b>V_0.6-21178</b></a></sub>

### CODE REVIEW

**Comment by enghitalo** [comment]
I have not ideia why this fails hahah

```sh
  FAIL  [1605/2074] C:  1827.4 ms, R:     9.050 ms vlib/v/tests/modules/enum_from_string_in_different_mods/src/main_test.v
         retry: 1
      comp_cmd: "D:\a\v\v\v.exe" -skip-running   -o "C:\Users\runneradmin\AppData\Local\Temp\v_0\tsession_18d0_01JBQPJPPNB8BG9M19RSHDYKQ6\1604_0\main_test.exe" "D:\a\v\v\vlib\v\tests\modules\enum_from_string_in_different_mods\src\main_test.v"
       run_cmd: "C:\Users\runneradmin\AppData\Local\Temp\v_0\tsession_18d0_01JBQPJPPNB8BG9M19RSHDYKQ6\1604_0\main_test.exe"
failure code: 1; foutput.len: 364; failure output:
---------------------------------------------------------------------------------------------------- retry: 0 ; max_retry: 0 ; r.exit_code: 1 ; trimmed_output.len: 196
'"C:\Users\runneradmin\AppData\Local\Temp\v_0\tsession_18d0_01JBQPJPPNB8BG9M19RSHDYKQ6\1604_0\main_test.exe"' is not recognized as an internal or external command,

operable program or batch file.
```

**Review by spytheman — COMMENTED** [review]
Just `tests/` is shorter and simpler.
The `json_` prefix does not add any additional information since the parent folder is already `vlib/json` .

**Comment by spytheman** [comment]
> I have not ideia why this fails

I've renamed that test as a workaround in 462f186 . It has nothing to do with this PR.

**Comment by enghitalo** [comment]
> Just `tests/` is shorter and simpler.
> The `json_` prefix does not add any additional information since the parent folder is already `vlib/json` .
> 

I separated the name to make it easier to merge x.json2, x.json2.decode2 and json. If you prefer, I can divide it into 3 folders like tests/json, tests/encoder, tests/decoder. What do you think?

**Comment by spytheman** [comment]
I think that they should stay as they are in the top level, or use test/ folder.

**Pull request merged**
