### PR TITLE
vdoc: rewrite style

### PR DESCRIPTION
**Pull request by danieldaeschle**
TODO:
* [x] Dark mode
* [x] Fancy scrollbar on left menu
* [x] collapsing on left menu
* [ ] scroll indicator on right menu
* [ ] automatic scroll to (left) menu entry when clicking it.

Preview:
image
Dark:
image

### CODE REVIEW

**Comment by danieldaeschle** [comment]
Maybe we should split structs, methods and functions in the document.

**Comment by dhonx** [comment]
@danieldaeschle The constants id is duplicate, so its better to add a number to it

**Comment by nedpals** [comment]
Let's move it to draft for now, since we need to finalize everything before it becomes available to use and uploaded on modules.vlang.io

**Comment by danieldaeschle** [comment]
@medvednikov maybe we could fix this socket webserver under windows. but it's not working and i don't know why. could someone take a look at it?

**Comment by dhonx** [comment]
@danieldaeschle Im on it... almost done... will push withing a minute

**Pull request merged**
