### PR TITLE
checker: allow mut arg on C functions

### LINKED ISSUE #11153: `mut arg` fails for `C.function`
**V version: 0.2.2 bd0653a.90adf4d** 
**OS: macos, macOS, 11.5.1,** 

**What did you do?**

```v
fn C.EVP_PKEY_sign(ctx &C.EVP_PKEY_CTX,
	sig &char, // unsigned char *sig
	mut siglen &size_t, // size_t *siglen,
	tbs &char, // const unsigned char *tbs,
	tbslen size_t // size_t tbslen
) int

fn main() {
	C.EVP_PKEY_sign(ctx, C.NULL, mut siglen, md, mdlen)
}

```

**What did you expect to see?**
no errors
 
**What did you see instead?**
```sh
error: `C.EVP_PKEY_sign` parameter `siglen` is `mut`, you need to provide `mut` e.g. `mut arg3`
```

**extra notes**

the following works somehow
```v
fn main() {
	mut a := size_t(0)
	mut_arg(mut a)
	println(a)
}

fn mut_arg(mut a size_t) {
	a = 10
}
```

and the following works as expected

```v
fn main() {
	mut a := size_t(0)
	mut_arg(mut &a)
	println(a)
}

fn mut_arg(mut a &size_t) {
	a = 10
}
```

### PR DESCRIPTION
**Pull request by Gladear**
Fixes #11153

I'm not sure how to add tests for this, it should basically pass the checker, but not go further since the C function would be a non-existing function, therefore failing C compilation

### CODE REVIEW

**Comment by spytheman** [comment]
> I'm not sure how to add tests for this, it should basically pass the checker, but not go further since the C function would be a non-existing function, therefore failing C compilation

Make a new folder in `vlib/v/tests/`, and put an empty `v.mod` file in the new folder.
Then add a file `code.c` in it, containing the C function that you want to call.
Then add a `code_test.v` in it too, containing at the top:
```v
#include "@VMODROOT/code.c"
```
When V compiles the `code_test.v`, it will include the source code in `code.c` too, so the function there will be available.

**Comment by Gladear** [comment]
`vfmt` is changing `fn C.mut_arg(key &byte, mut val &size_t)` to `fn C.mut_arg(key &byte, mut val size_t)`, which is in turn not compilable...

**Comment by spytheman** [comment]
> `vfmt` is changing
> 
> ```v
> fn C.mut_arg(key &byte, mut val &size_t)
> ```
> 
> to
> 
> ```v
> fn C.mut_arg(key &byte, mut val size_t)
> ```
> 
> which is in turn not compilable...

That is because `mut` in function params already implies a level of indirection, so:
```c
void mut_arg(const byte *_key, size_t *val) {
```
should be declared as:
```v
void mut_arg(const_key &byte, mut val size_t) {
```
(note that it is `mut val size_t`, and not `mut val &size_t`)

**Comment by spytheman** [comment]
Although ideally vfmt should not change what the user typed 🤔, that is probably a bug/antifeature in vfmt. I'll fix it soon.

**Comment by medvednikov** [comment]
Good to merge?

**Pull request merged**
