### PR TITLE
fix: changes math.big.divmod to return (quotient, remainder)

### PR DESCRIPTION
**Pull request by blackshirt**
The current `divmod` function from `math.big` module was in the form `pub fn divmod(a &Number, b &Number, c &Number) Number`, return only the remainder part of the results. 

This situation doesn't  reflects underlying `C.bignum_divmod` function being wrapped, it should return quotient and remainder instead. 
This pull changes above situation, especially, the `divmod` function to return pair of quotient and remainder. As a notes, this changes  **change signature of divmod API** and makes it reflect how `C.bignum_divmod` works, and make its consistent and in accordance with the other languages of divmod operation.
See python divmod function or golang version of math.bits.Div and math.big.DivMod

### CODE REVIEW

**Review by spytheman — CHANGES_REQUESTED** [review]
Good work. Just format the changed files and it will be good to merge.

**Comment by blackshirt** [comment]
> Good work. Just format the changed files and it will be good to merge.

Thank, you're welcime..there are some CI checks was not succesfull,, a lot of them was '`Error: The operation was canceled.` warning, is this something unusual ?

**Comment by JalonSolov** [comment]
It used to be unusual, until Github started limiting CI checks.  Note that all the ones that are marked "cancelled" timed out.

After everything else settles down, we can close/re-open this PR, and hopefully the checks will run better next time.

**Comment by spytheman** [comment]
I think it is good to merge as it is - the tests passed locally for me.

**Pull request merged**
