### PR TITLE
fmt: add a sapce after operator in overload function

### PR DESCRIPTION
**Pull request by serkonda7**
`(a Foo) +(b Foo)` --> `(a Foo) + (b Foo)`

### CODE REVIEW

**Comment by danieldaeschle** [comment]
why? This is inconsistent.

**Comment by serkonda7** [comment]
I partly agree with you (especially since I now know how operator overloading is handled internally). But this makes the operator easier recognizable and is fine imo as it still is a special case of function declaration.

**Comment by danieldaeschle** [comment]
Can we rediscuss this?

**Comment by Delta456** [comment]
It's seems fine to me as operator overloading are an another exception

**Comment by medvednikov** [comment]
It's fine.

**Pull request merged**
