### PR TITLE
example: C interop for HTML to PDF conversion using libwkhtmltox

### PR DESCRIPTION
**Pull request by leandrosilva**
I wrote yet another example of C interop (I know there is that interesting one with SQLite) for the handy task of convert HTML to PDF using [libwkhtmltox ](https://wkhtmltopdf.org/).

In the process, it shows how to deal with pointers and write bytes to a file, in order to save the PDF, step by step.

Thanks.

### CODE REVIEW

**Comment by clubby789** [comment]
Looks like the dependencies will need to be updated for the CI actions.

**Comment by leandrosilva** [comment]
Is it possible for me to do that or will it require maintainer of the repo do that?
I apologize.
First time I'm caught on this situation.

**Comment by JalonSolov** [comment]
Probably better to do a separate PR to fix the dependencies, and have this PR wait for that one.  Only a couple of people can merge commits.

**Comment by spytheman** [comment]
This is a good C interoperation example, that does an useful task. 
I could compile it on Ubuntu 20.04, by downloading a .deb file from  , then doing:
```bash
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
sudo apt-get install xfonts-75dpi
sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
```
These instructions can be added to .github/workflows/ci.yml, in one of the `ubuntu-` jobs, so we can be sure that it is tested and does not regress.
However I am not sure, that the installation will be as straightforward on other platforms like macos and windows, and the .deb package is ~15MB.

@medvednikov what is your opinion, should we add examples like these, and should they be in the main `examples/` folder?

**Comment by medvednikov** [comment]
The dependencies are on the heavy side, but it's a useful example, and the deps are only installed on one CI instance.

**Pull request merged**
