### PR TITLE
Regex: bugfix for #18363, [^\s]+ act different from \S+

### PR DESCRIPTION
**Pull request by penguindark**
**What's inside**
- Bug fix for the bug #18363
- Added more tests

### CODE REVIEW

**Comment by penguindark** [comment]
@spytheman the CI is failing on the coroutines code, do I have to do anything or is it a known issue?

**Comment by JalonSolov** [comment]
One problem is that coroutines only work on Mac right now, so that particular test shouldn't even be running for others.

**Comment by medvednikov** [comment]
I fixed the failing example.

**Comment by penguindark** [comment]
unfortunately CI continue to fail :(

**Comment by penguindark** [comment]
@medvednikov can you merge this bugfix?

**Pull request merged**
