### PR TITLE
flag: modify flag parser intelligence

### PR DESCRIPTION
**Pull request by chipnetics**
In the flag module, the current behaviour of using a function such as `string_multi` is that to generate an array of a specific option, you need to *repeat the flag* repeatedly.  

For instance. in the current V master....

```v
xer_arg := fp.string_multi('xerlist', `x`, 'specify XER files')
```

```
$> foo -x this -x that -x other ---> ['this','that','other']      // -x flag specified 3 times
$> foo -x this that other --> ['this']                            // -x specified once, only first parameter consumed
```
In the revised code....

```
$> foo -x this that other --> ['this','that','other']            // all 3 parameters after flag consumed
$> foo -x this -g -x that other  --> ['this','that','other']     // intermingling flags
```

I've ran an existing program of mine with various combinations as a test, interweaving flags etc.... see below.

```bash
jp@chipnetics ~/S/v/x/src (main)> v run xerdump.v -s -x DD00000000.xer DD20210630.xer
Running on files: ['DD00000000.xer', 'DD20210630.xer']
Compiling INSERT commands...       [DONE]
Deleting existing datase....       [DONE]
Executing CREATE TABLE commands... [DONE]
[DONE]

jp@chipnetics ~/S/v/x/src (main)> v run xerdump.v -x DD00000000.xer -s -x DD20210630.xer DD20210725.xer 
Running on files: ['DD00000000.xer', 'DD20210630.xer', 'DD20210725.xer']
Compiling INSERT commands...       [DONE]
Deleting existing datase....       [DONE]
Executing CREATE TABLE commands... [DONE]
[DONE]

jp@chipnetics ~/S/v/x/src (main)> v run xerdump.v -x DD00000000.xer DD20210630.xer -s -x DD20210725.xer DD20210830.xer 
Running on files: ['DD00000000.xer', 'DD20210630.xer', 'DD20210725.xer', 'DD20210830.xer']
Compiling INSERT commands...       [DONE]
Deleting existing datase....       [DONE]
Executing CREATE TABLE commands... [DONE]
[DONE]

jp@chipnetics ~/S/v/x/src (main)> v run xerdump.v -x DD00000000.xer DD20210630.xer -x DD20210725.xer DD20210830.xer -s
Running on files: ['DD00000000.xer', 'DD20210630.xer', 'DD20210725.xer', 'DD20210830.xer']
Compiling INSERT commands...       [DONE]
Deleting existing datase....       [DONE]
Executing CREATE TABLE commands... [DONE]
[DONE]
```

### CODE REVIEW

**Comment by JalonSolov** [comment]
What about `foo -x this that other filename_to_process`?  Your change will "eat" the filename as another `-x` value.

I'd prefer to see `-x this,that,other` or `-x this:that:other` or some other non-space delimited way of handling multiple values for a single flag.

**Comment by spytheman** [comment]
@JalonSolov is right. Consuming more than one token after any given flag is confusing.

**Comment by chipnetics** [comment]
Okay no worries. Do you think it's less confusing having a delimiter like ':'?

For CLI apps that do multi-file processing, using the same flag over and over seems tedious. Something like gcc with multiple c source files handles it.

**Comment by chipnetics** [comment]
Hrmmm you are correct, I actually also don't think I realized flag.args was public, so I can get whatever is left that wasn't consumed by the flag parser.... ie....

Ah well :) the code edit didn't take too long, thanks for reviewing @spytheman and @JalonSolov 

```bash
jp@chipnetics ~/S/v/x/src (main)> v run xerdump.v DD00000000.xer -s DD20210630.xer
['DD00000000.xer', 'DD20210630.xer']
```

**Pull request closed without merging**
