### PR TITLE
vweb example: Making css in vweb_assets.v work

### PR DESCRIPTION
**Pull request by enghitalo**

### CODE REVIEW

**Comment by medvednikov** [comment]
```examples/vweb/vweb_assets/vweb_assets.v:26:6: error: type `App` has no field or method `vweb`.
1 possibility: `Context`.
   24 |     // This would make available all known static mime types from current
   25 |     // directory and below.
   26 |     app.vweb.handle_static('.')
      |         ~~~~
   27 | }```

**Comment by enghitalo** [comment]
> ```
> examples/vweb/vweb_assets/vweb_assets.v:26:6: error: type `App` has no field or method `vweb`.
> 1 possibility: `Context`.
>    24 |     // This would make available all known static mime types from current
>    25 |     // directory and below.
>    26 |     app.vweb.handle_static('.')
>       |         ~~~~
>    27 | }
> ```

fixed

**Comment by medvednikov** [comment]
Thanks and sorry for the delay.

**Comment by enghitalo** [comment]
> Thanks and sorry for the delay.

don't worry. Thanks for merge

**Pull request merged**
