### PR TITLE
parser: check for_in mut key

### PR DESCRIPTION
**Pull request by yuyi98**
This PR check for_in mut key.

- Check for_in mut key.
- Add test.

```vlang
fn main() {
	mut m := {'foo': 1, 'bar': 2}
	for mut k, _ in m {
		println(k)
	}
}

vlib/v/parser/tests/for_in_mut_key_of_map.vv:3:6: error: index of array or key of map cannot be mutated
    1 | fn main() {
    2 |     mut m := {'foo': 1, 'bar': 2}
    3 |     for mut k, _ in m {
      |         ~~~
    4 |         println(k)
    5 |     }
```
```vlang
fn main() {
	mut m := [1, 2, 3]
	for mut i, _ in m {
		println(i)
	}
}

vlib/v/parser/tests/for_in_mut_index_of_array.vv:3:6: error: index of array or key of map cannot be mutated
    1 | fn main() {
    2 |     mut m := [1, 2, 3]
    3 |     for mut i, _ in m {
      |         ~~~
    4 |         println(i)
    5 |     }
```

### CODE REVIEW

**Comment by SleepyRoy** [comment]
I guess `key of map cannot be mutated` is more clear.

**Comment by yuyi98** [comment]
It also check `for mut i, v in arr` situation.

**Comment by SleepyRoy** [comment]
Then how about `index of array or key of map cannot be mutated`?
And could you also add a test for that?

**Comment by yuyi98** [comment]
OK

**Pull request merged**
