### PR TITLE
[trivial] Rename pointer_arithmetic_should_be_checked.vv -> unsafe_required.vv

### PR DESCRIPTION
**Pull request by ntrel**
It has other unsafe check(s) e.g. unsafe method.
Fix mixed indentation types.

### CODE REVIEW

**Comment by spytheman** [comment]
unsafe_required.out has embedded the name of the .v file that originated the error, you will have to edit it too

**Comment by spytheman** [comment]
Oops, sorry. I had split that file to 2 in a fix to one of the previous PRs:
vlib/v/checker/tests/unsafe_c_calls_should_be_checked.vv
vlib/v/checker/tests/unsafe_pointer_arithmetic_should_be_checked.vv
(and their corresponding .out files)

**Comment by ntrel** [comment]
> unsafe_required.out has embedded the name of the .v file that originated the error

Oops, fixed.

>  I had split that file to 2

Did that get lost? That would be OK. I was thinking that combining related tests in the same file would be quicker for the test runner.

**Comment by ntrel** [comment]
BTW why do we use `file.vv` for tests with `file.out`, wouldn't just `file.v` work? To generate the file.out file I have to first rename file.vv -> file.v because V doesn't like it!

**Comment by spytheman** [comment]
Historic reasons - while the new AST compiler was being developed, we needed a way to distinguish between the old and new files, so that the old compiler could skip the new files, while the new one could be run on both. After that it was reused for the .vv/.out combination that vlib/v/compiler_errors_test.v expects.

**Comment by medvednikov** [comment]
Getting rid of .vv would be nice.

**Pull request merged**
