### PR TITLE
Fixed path to clang on linux OS [WIP]

### PR DESCRIPTION
**Pull request by juliancoffee**
In linux clang is in /usr/bin/clang, now It is fixed in main.v

### CODE REVIEW

**Comment by juliancoffee** [comment]
work in progress

**Comment by Oxylibrium** [comment]
@juliancoffee would it be possible to use `os.getenv('PATH')` on Linux and macOS in place of hardcoding `/usr/bin`?

**Comment by juliancoffee** [comment]
> @juliancoffee would it be possible to use `os.getenv('PATH')` on Linux and macOS in place of hardcoding `/usr/bin`?

sounds good

**Comment by medvednikov** [comment]
Right now it will work if `cc` is in the PATH. Why do we need this?

The fast_clang hack is for using  llvm 8.0.0 for cross compiling, which is much faster.

**Comment by juliancoffee** [comment]
> Right now it will work if `cc` is in the PATH. Why do we need this?
> 
> The fast_clang hack is for using llvm 8.0.0 for cross compiling, which is much faster.

Because in Linux we don't have /usr/local/Cellar, we have only /usr/bin/clang
And so we can't compile V code with clang)
And `cc` is symlink to `gcc `for compatibility reasons, as it was standard in open source.

**Comment by Bowero** [comment]
Please look at another open PR: #452

**Pull request closed without merging**
