### PR TITLE
parser: check empty interface (fix #10292)

### LINKED ISSUE #10292: C error. This should never happen. -> Passing structs as if empty interface
**V doctor:** 
```
OS: linux, "Artix Linux"
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 3600 6-Core Processor
CC version: cc (GCC) 11.1.0

getwd: /home/me/coding/v/tests
vmodules: /home/me/.vmodules
vroot: /home/me/Programs/v
vexe: /home/me/Programs/v/v
vexe mtime: 2021-05-31 20:13:53
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 e4f6369.67518f9

Git version: git version 2.31.1
Git vroot status: weekly.2021.22-1-g67518f94
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```

**What did you do?**
`v run test_interface.v`
```
fn main(){
	stru := Stru{}
	fnc1(stru)
}
interface Inter{	
}

struct Stru{
	bruh int
}

fn fnc1(inter Inter){
	println(inter)
}
```

**What did you expect to see?**
No compiler errors
 
**What did you see instead?**
```
==================
/tmp/v/test_interface.15567707270108548358.tmp.c:2087: error: cannot convert 'struct string' to 'void *'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR check empty interface (fix #10292).

- Disallow the use of empty interfaces.
Because when we use empty interface, it will generate all the types cast functions :
```vlang
static main__Inter I_main__Stru_to_Interface_main__Inter(main__Stru* x);
int _main__Inter_main__Stru_index = 0;
static main__Inter I_ustring_to_Interface_main__Inter(ustring* x);
int _main__Inter_ustring_index = 1;
static main__Inter I_voidptr_to_Interface_main__Inter(voidptr* x);
int _main__Inter_voidptr_index = 2;
static main__Inter I_array_to_Interface_main__Inter(array* x);
int _main__Inter_array_index = 3;
static main__Inter I_map_to_Interface_main__Inter(map* x);
int _main__Inter_map_index = 4;
static main__Inter I_VCastTypeIndexName_to_Interface_main__Inter(VCastTypeIndexName* x);
int _main__Inter_VCastTypeIndexName_index = 5;
static main__Inter I_VAssertMetaInfo_to_Interface_main__Inter(VAssertMetaInfo* x);
int _main__Inter_VAssertMetaInfo_index = 6;
static main__Inter I_MethodArgs_to_Interface_main__Inter(MethodArgs* x);
int _main__Inter_MethodArgs_index = 7;
static main__Inter I_FunctionData_to_Interface_main__Inter(FunctionData* x);
int _main__Inter_FunctionData_index = 8;
static main__Inter I_FieldData_to_Interface_main__Inter(FieldData* x);
int _main__Inter_FieldData_index = 9;
static main__Inter I_StructAttribute_to_Interface_main__Inter(StructAttribute* x);
int _main__Inter_StructAttribute_index = 10;
static main__Inter I_SymbolInfo_to_Interface_main__Inter(SymbolInfo* x);
int _main__Inter_SymbolInfo_index = 11;
static main__Inter I_SymbolInfoContainer_to_Interface_main__Inter(SymbolInfoContainer* x);
int _main__Inter_SymbolInfoContainer_index = 12;
static main__Inter I_Line64_to_Interface_main__Inter(Line64* x);
int _main__Inter_Line64_index = 13;
static main__Inter I_ExceptionRecord_to_Interface_main__Inter(ExceptionRecord* x);
int _main__Inter_ExceptionRecord_index = 14;
static main__Inter I_ContextRecord_to_Interface_main__Inter(ContextRecord* x);
int _main__Inter_ContextRecord_index = 15;
static main__Inter I_ExceptionPointers_to_Interface_main__Inter(ExceptionPointers* x);
int _main__Inter_ExceptionPointers_index = 16;
static main__Inter I_strconv__Float64u_to_Interface_main__Inter(strconv__Float64u* x);
int _main__Inter_strconv__Float64u_index = 17;
static main__Inter I_strconv__Float32u_to_Interface_main__Inter(strconv__Float32u* x);
int _main__Inter_strconv__Float32u_index = 18;
static main__Inter I_DenseArray_to_Interface_main__Inter(DenseArray* x);
int _main__Inter_DenseArray_index = 19;
static main__Inter I_Error_to_Interface_main__Inter(Error* x);
int _main__Inter_Error_index = 20;
static main__Inter I_None___to_Interface_main__Inter(None__* x);
int _main__Inter_None___index = 21;
static main__Inter I_Option_to_Interface_main__Inter(Option* x);
int _main__Inter_Option_index = 22;
static main__Inter I_VMemoryBlock_to_Interface_main__Inter(VMemoryBlock* x);
int _main__Inter_VMemoryBlock_index = 23;
static main__Inter I_mapnode_to_Interface_main__Inter(mapnode* x);
int _main__Inter_mapnode_index = 24;
static main__Inter I_SortedMap_to_Interface_main__Inter(SortedMap* x);
int _main__Inter_SortedMap_index = 25;
static main__Inter I_RepIndex_to_Interface_main__Inter(RepIndex* x);
int _main__Inter_RepIndex_index = 26;
static main__Inter I_StrIntpMem_to_Interface_main__Inter(StrIntpMem* x);
int _main__Inter_StrIntpMem_index = 27;
static main__Inter I_StrIntpData_to_Interface_main__Inter(StrIntpData* x);
int _main__Inter_StrIntpData_index = 28;
static main__Inter I_strconv__BF_param_to_Interface_main__Inter(strconv__BF_param* x);
int _main__Inter_strconv__BF_param_index = 29;
static main__Inter I_StrIntpCgenData_to_Interface_main__Inter(StrIntpCgenData* x);
int _main__Inter_StrIntpCgenData_index = 30;
static main__Inter I_strconv__PrepNumber_to_Interface_main__Inter(strconv__PrepNumber* x);
int _main__Inter_strconv__PrepNumber_index = 31;
static main__Inter I_strconv__Dec32_to_Interface_main__Inter(strconv__Dec32* x);
int _main__Inter_strconv__Dec32_index = 32;
static main__Inter I_strconv__Uf32_to_Interface_main__Inter(strconv__Uf32* x);
int _main__Inter_strconv__Uf32_index = 33;
static main__Inter I_strconv__Dec64_to_Interface_main__Inter(strconv__Dec64* x);
int _main__Inter_strconv__Dec64_index = 34;
static main__Inter I_strconv__Uf64_to_Interface_main__Inter(strconv__Uf64* x);
int _main__Inter_strconv__Uf64_index = 35;
static main__Inter I_strconv__Uint128_to_Interface_main__Inter(strconv__Uint128* x);
int _main__Inter_strconv__Uint128_index = 36;
// ^^^ number of types for interface main__Inter: 37
```
That's not what we want.
- Check empty interface.
- Modify all the related.
- Add test.

```vlang
fn main() {
	stru := Stru{}
	fnc1(stru)
}

interface Inter {
}

struct Stru {
	bruh int
}

fn fnc1(inter Inter) {
	println(inter)
}

PS D:\Test\v\tt1> v run .
.\tt1.v:6:11: error: disallow the use of empty interfaces
    4 | }
    5 |
    6 | interface Inter {
      |           ~~~~~
    7 | }
    8 |
```

### CODE REVIEW

**Comment by spytheman** [comment]
Handling empty interfaces is a feature, not a bug.

**Comment by spytheman** [comment]
We should improve the codegen, so that it does not break for the example code, not disallow empty interfaces, which already work in some cases, and which enable an important design mechanism.

**Comment by yuyi98** [comment]
Ok, I see.

**Comment by spytheman** [comment]
The codegen improvements are in c3b9eaf .

**Pull request closed without merging**
