### PR TITLE
WIP: js: eval takes a JS.String, not `string`, which fails in Frida

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by spytheman** [comment]
can you fix the failing test?

**Comment by trufae** [comment]
@spytheman actually this "fix" exposes a problem that i would prefer to discuss before merging (let me add WIP in the title).

The problem is that I didnt find a way to access the `.str` when using the js backend of V, and thats a similar issue to using v-strings and c-strings with cgen. So not sure if that cast should be automatic, but none of the standard javascript global functions should be taking `string` because thats a v-specific thing.

any thoughs on this @playXE ?

This program shows the problem:

```js
$ cat vstr.js

function string(str) { if (str === undefined) { str = new String(""); }this.str = str.toString(); this.len = this.str.length }

var a = new string("123");
var b = "123";

console.log(eval(a));
console.log(eval(b));
console.log(eval(String(b)));

$
```

**Comment by spytheman** [comment]
Imho this should be an issue/feature request, not a PR.

**Comment by trufae** [comment]
i was going to update the PR after clarifying this with @playXE because its clear to me that all those JS declarations are wrong but there are tests asuming passing a v-string to a js-string argument is fine, which is not and wont work well in some situations, that patch makes the v-frida module to work. ill just create another pr when this is clear or just let @playXE do the thing

**Comment by trufae** [comment]
just workarounded this so i dont depend on this bugfix to use v-frida https://github.com/trufae/v-frida/commit/7f0c2fe7c462316f712f962e2b228a9e0503d7ff

**Pull request closed without merging**
