### PR TITLE
vfmt: change all '$expr' to '${expr}'

### PR DESCRIPTION
**Pull request by yuyi98**
This PR change all '$expr' to '${expr}' except simple '$name'.

### CODE REVIEW

**Comment by Delta456** [comment]
Weren't we gonna remove `$name` all together to be replaced with `${name}`?

**Comment by medvednikov** [comment]
Ok, more than 80% prefer the one way.

https://twitter.com/v_language/status/1592209623624609792

@yuyi98 please update the PR so that $foo is also changed to ${foo}.

I really liked having $foo, but at least I can type it like this, it'll be updated to ${foo} by vfmt.

**Comment by yuyi98** [comment]
Ok, I'll change all '$expr' to '${expr}'.

**Comment by yuyi98** [comment]
go2v will be fixed after this PR merged.

**Comment by Larpon** [comment]
Legendary work :muscle:

**Comment by medvednikov** [comment]
Great work! Thanks!

**Pull request merged**
