### PR TITLE
Update docs.md

### PR DESCRIPTION
**Pull request by mehanalavimajd**

### CODE REVIEW

**Comment by mehanalavimajd** [comment]
Update the winfows installation with two commands in one line

**Comment by mehanalavimajd** [comment]
No one will answer ?¿?

**Comment by spytheman** [comment]
It is better to have them on 2 lines - easier to read and to follow.

**Comment by mehanalavimajd** [comment]
So why did you put 3 commands in 1 line in linux installation doc?

**Comment by mehanalavimajd** [comment]
isn't it unreadable?

**Comment by spytheman** [comment]
It is fixed in https://github.com/vlang/v/commit/13350681dd1115e2a234ed8af285afb307ab65e6 . Both instructions use separate lines now.

**Comment by mehanalavimajd** [comment]
Ok.
Good luck 👍.

**Comment by spytheman** [comment]
Good luck to you too 👍🏻 .

**Pull request closed without merging**
