### PR TITLE
vweb: Add chromium filter for double http requests

### PR DESCRIPTION
**Pull request by LouisSchmieder**
This PR adds a chromium filter for doubled http requests on loading the site. The problem is known and this PR handle is that the handle_conn don't get called twice and that there is no `failed first_line` error.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Does this actually need the `is_chromium` check?  Seems like the code would work the same without that.  Also means you don't have to keep a list of `chromium_head_names`, etc., which could become a nightmare to keep updated.  :-\

**Comment by LouisSchmieder** [comment]
close #7950 7950

**Comment by LouisSchmieder** [comment]
I simplified it now but yeah the list is needed to detect the browser: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#browser_name it's not changing and maybe should be updated when a new chromium based browser releases

**Comment by JalonSolov** [comment]
https://en.wikipedia.org/wiki/Chromium_(web_browser) - section titled "Browsers based on Chromium"
Like anything else on the 'net, it may or may not be a complete list, but there are 26 browsers listed there.

**Pull request closed without merging**
