### PR TITLE
math: implement logarithm function in pure V

### LINKED ISSUE #12074: vlib/math: Add log function for default pure V backend
This ticket is one of the needed steps to finish the pure V implementation of `vlib/math`. We need to add the function `log` for `f64`. For that we can follow the following steps:

- We need to update [log.v](https://github.com/vlang/v/blob/master/vlib/math/log.v) adding a function `fn log(x f64) f64`
- You can check how it is implemented on golang's source code [here](https://github.com/golang/go/blob/96fface83ad69b6d6ad8059d61d232737572e85d/src/math/log.go#L87) for reference

## Testing

- We don't need to add any test for this ticket. All tests are already defined at math_test.v [here](https://github.com/vlang/v/blob/2526aca75fee4d63b13f3aa249810916b6290b36/vlib/math/math_test.v#L669)
- We need to define the new function and make sure that all existing tests pass with the new definition of `log`
  - In case we have any precission issue, reach out to me @ulises-jeremias and we can discuss about it 👌🏻

### PR DESCRIPTION
**Pull request by playXE**
Closes #12074

### CODE REVIEW

**Comment by medvednikov** [comment]
Is it faster than C.log()?

JS has a logarithm function, we can use that for the JS backend.

**Comment by ulises-jeremias** [comment]
https://github.com/vlang/v/projects/11 @playXE @medvednikov

**Comment by medvednikov** [comment]
I understand, that C fn calls shouldn't be present in vlib/math. But why not just use C fn call in math.c.v and JS fn call in math.js.v?

**Comment by ulises-jeremias** [comment]
Yeah, probably it is part of a longuer discussion, but right now with V using the C backend as default on most tests we don't have a good way to track if we are loosing precision and performance on the vlib math on each change, and also having multiple backends for math it is difficult to guarantee that we are offering the same precision and results for all platform to our users

That is way most languages have their pure implementation, because having a pure V math will make it possible to assume that our modules that are using math have a similar precision and same results for each function, and also the performance will improve with the language improvement

**Comment by ulises-jeremias** [comment]
Anyways, we can keep the C call for now (@playXE can you add it back?) And we can reopen this discussion in the context of the other PR I'm working on right now 👌🏻

**Pull request merged**
