### PR TITLE
android: fix os.create and builtin, so that v still use libc

### PR DESCRIPTION
**Pull request by spytheman**
Fixes Termux/Android build.

### CODE REVIEW

**Comment by medvednikov** [comment]
Need `$if os1 || os2 {` support asap :)

**Comment by medvednikov** [comment]
`linux_or_mac` is a temp hack that will be removed.

**Comment by spytheman** [comment]
Indeed, support for `$if x || y {}` would be very nice indeed, but I do not know if it would be easy to do with the old compiler ?

**Comment by medvednikov** [comment]
Yeah it's best not to touch the old parser, and implement it in the new one.

**Pull request merged**
