### PR TITLE
- allow multiple vsrc to be specified

### LINKED ISSUE #17063: specify files to convert
### Describe the issue

Both below works (in examples/call_v_from_c):

```
$ v -shared -o v_test_math.c v_test_math.v
$ v -shared -o v_test_both.c .
```

But not below
```
$ v -shared -o v_test_math.c v_test_math.v v_test_print.v
Too many targets. Specify just one target: <target.v|target_directory>.
```

Is it possible to specify a list of files to be converted into C, rather than the full directory?

Use case is simple. I have two folders: vsrc_a, and vsrc_b, each containing some v sources. Now if I do:
```
$ vsrc_a$ v -shared -o vsrc_a.c .
$ vsrc_b$ v -shared -o vsrc_b.c .

$ gcc -o test vsrc_a.c  vsrc_b.c
Won't work because vsrc_a.c and vsrc_b.c contain duplicated boilerplate codes.

```

### Links

No link.

### PR DESCRIPTION
**Pull request by wenq1**
fixes #17063 17063

### CODE REVIEW

**Comment by JalonSolov** [comment]
Yes, it's simple enough... but what if I do want a separate .c file for every .v file?  What if I want one .c file for the first 3 .v files, but a different .c file for the next 2?  I wouldn't want to have to type separate commands for that, after all...

As soon as you change what is already done, someone will ask for more variations.

**Comment by JalonSolov** [comment]
This might need more discussion, and perhaps see if anyone else wants this feature badly enough for it to be added to V.

@medvednikov what do you think?

**Comment by wenq1** [comment]
Below is what I'll expect from a normal compiler. 
```
<command> -o <output> <input1> <input2> ...
```

Anything complicated than that is beyond my comprehension and I'll not join the conversation.

**Comment by wenq1** [comment]
> Yes, it's simple enough... but what if I do want a separate .c file for every .v file? What if I want one .c file for the first 3 .v files, but a different .c file for the next 2? I wouldn't want to have to type separate commands for that, after all...
> 
That's the job of a good old Makefile. Not the compiler.

**Comment by JalonSolov** [comment]
V treats all the files in a directory as being part of the same project.  That's why it wants to compile all the files together.

Or you can compile a specific file, if you have a bunch of separate single files in one directory.

It was never meant to handle multiple related files mixed with unrelated files in the same directory.

**Comment by spytheman** [comment]
> However, I don't think v should automagically read all .v files in my directory, some of which might be related to the conversion session while others might just be related to other targets.

Too bad. V expects all files in a folder to be part of the same project/module, and that is not going to change.

**Pull request closed without merging**
