### PR TITLE
websocket utf8: move utf8 things of websocket to encoding.utf8, and make test (4/4)

### PR DESCRIPTION
**Pull request by esquerbatua**
This PR moves all of the utf8 implemented inside websocket module to the encoding.utf8.

I'm not sure if this is correct, but if there is a module for utf8 it will be all of the related with utf8 inside, the functions of the moved file validates if an string have utf8 correct encoding.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Seems like a good move to me.  Better to have utf-8 handling in a single module, than multiple copies spread around.  If it need to be fixed, it can be fixed in that one module.

**Comment by esquerbatua** [comment]
> Seems like a good move to me. Better to have utf-8 handling in a single module, than multiple copies spread around. If it need to be fixed, it can be fixed in that one module.
> 
> However, you imported it but never used it.

I have moved it but had not changed the references in ws :sweat_smile:

**Comment by JalonSolov** [comment]
Looks good now.  :-)

**Comment by esquerbatua** [comment]
Resolved conflict

**Pull request merged**
