### PR TITLE
add time.parse_iso

### PR DESCRIPTION
**Pull request by kitech**
Parse ISO time format like `Thu, 12 Dec 2019 06:07:45 GMT`

### CODE REVIEW

**Comment by donnisnoni95** [comment]
@kitech Great !!! Can you add a test for this ???

**Comment by medvednikov** [comment]
Yes @kitech can you please add tests for both PRs?

Thanks

**Comment by kitech** [comment]
new added function seems not working, it should be defined, what can I do?

vlib/time/time_test.v:241:16: undefined: `parse_iso`

**Comment by medvednikov** [comment]
I've fixed the test @kitech

You need `time.` before the function. That was fixed recently, I'll update the test later.

**Comment by kitech** [comment]
I see, although it should be in the same module, think it would omit module name.

**Comment by medvednikov** [comment]
The test doesn't pass @kitech

**Comment by kitech** [comment]
Because time.parse's bug, need merge this fix first, https://github.com/vlang/v/pull/3161

**Pull request merged**
