### PR TITLE
Windows Unicode I/O

### PR DESCRIPTION
**Pull request by vitalyster**
Second try of https://github.com/vlang/v/pull/1208, will try to run and fix tests on Windows

### CODE REVIEW

**Comment by medvednikov** [comment]
Windows build is failing with the same `V panic: compiler isn't a directory`

You can test it yourself by running `v.exe -o v2.exe compiler`.

**Comment by joe-conigliaro** [comment]
when i tried ls / dir_exists / file_exits are were not working. that's why the build is failing. I'm not sure what it was but they all use to_wide

**Comment by vitalyster** [comment]
Yes, it is because first `v.exe` is built from non-unicode `vlang/vc` version while `compiler` is already unicode.
I got correct compiler C sources with `-debug` option, then built it with `gcc -DUNICODE -D_UNICODE` and it works after that. So new compiler must be placed into `vlang/vc` repo first.

**Comment by medvednikov** [comment]
Ok, I'll try that.

**Comment by joe-conigliaro** [comment]
Ahh I see

**Comment by joe-conigliaro** [comment]
@medvednikov did you try this, I tried like you said @vitalyster bit It still didn't work? I don't understand why v -debug would product a different C file though either?

**Comment by vitalyster** [comment]
@joe-conigliaro it works for Travis :)

**Comment by joe-conigliaro** [comment]
@vitalyster that's so weird because I just looked at the travis.yaml and i swear that's exactly what i did. well I'm glad it works :D

**Comment by medvednikov** [comment]
Merged it, getting `V panic: compiler isn't a directory` again :(

`gcc -DUNICODE -D_UNICODE .v2.exe.c -o v2.exe` is used.

Perhaps this is caused by the big Microsoft C commit?

**Comment by vitalyster** [comment]
It also wants microsoft_craziness now, I did create new PR, update Travis command line and it works

**Comment by joe-conigliaro** [comment]
lol @ microsoft_craziness.h

**Pull request merged**
