### PR TITLE
fn: can re-assign fn to variable (fixes #4751)

### LINKED ISSUE #4751: calling variable function crashes
**V version:** V 0.1.27 b627bb9
**OS:** linux amd64

**What did you do?**
```v
fn a() int {
  return 1
}

fn main() {
  x := a
  _ = x()
}
```

**What did you expect to see?**
compiles, and with a check if inside `main.main` and `x` got `main.main` then same error as calling `main.main` from `main.main`.

 
**What did you see instead?**
crashes

### PR DESCRIPTION
**Pull request by dkull**
This PR allows functions to be assigned to variables and to be called.

Was broken (issue #4751):
```
fn a() int {
  return 1
}

fn main() {
  x := a
  _ = x()
}
```

### CODE REVIEW

**Comment by tim-st** [comment]
The following code should be checked
```v
fn main() {
	x := main
	x()
}
```
as described here <https://github.com/vlang/v/issues/4751#issue-613166530>

**Comment by spytheman** [comment]
No it should not - why should the compiler prevent recursion on main through a variable?
If someone is so persistent that he want to recurse on main, let them.

**Comment by tim-st** [comment]
@spytheman 
Because it's currently not allowed, just try the following code:
```v
fn main() {
	main()
}
```
it doesn't compile.
I just noticed that, so the compiler is consistent about this.

**Comment by spytheman** [comment]
Should we also make v check for example this:
```v
type Func fn()
fn main(){
   a := abc()
   a()
}
fn abc() Func {
   return main
}
```
Do we also solve the halting problem in the same PR?

**Comment by spytheman** [comment]
The existing checks for main, and disallowing calling it/making it special is done to protect people, since it is translated to C functions named `main`, `wmain`, or `wWinMain`.

A much better solution for all this would be if we generate a single `main__main` that is an ordinary C function, that would then be simply called by the C's main,wmain,wWinMain ones.

@medvednikov I think it is better to bring back main module prefixing - it would solve many problems and simplify and unify function handling.

**Pull request merged**
