### PR TITLE
vdoc: minor css fix + add error message

### PR DESCRIPTION
**Pull request by nedpals**
- Minor CSS fix for distinguishing inline and block `<code>` tags.
- Take advantage of `error_with_code` and add a custom error message when running vdoc on folders without V content or contains subfolders.

(Edit) Preview:
image

### CODE REVIEW

**Comment by danieldaeschle** [comment]
@nedpals can you post a image of the result?

**Comment by nedpals** [comment]
sure thing

**Comment by danieldaeschle** [comment]
ok, it looks misalgined, i will adjust it a little bit later.

**Comment by danieldaeschle** [comment]
image

**Pull request merged**
