### PR TITLE
native: drop x64 backend reference

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by JalonSolov** [comment]
Are we dropping it in the `-arch` option as well?  It currently still works there.

**Comment by trufae** [comment]
Nope. -arch and -os are used by -b native. Maybe those should be listed in that file too as separate items

**Comment by JalonSolov** [comment]
What I meant was that I can currently use `-arch x64` on the command line with no complaints.  You typed it yourself on discord.  I thought the only valid arches (right now) were `amd64` and `arm64`.

**Comment by trufae** [comment]
pref/pref.v:            'amd64', 'x86_64', 'x64', 'x86' { // amd64 recommended

**Pull request merged**
