### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JasonHonor**
add compile command for centos.

### CODE REVIEW

**Comment by Bowero** [comment]
I would like to note that this isn't only the case for CentOS. It is also necessary for other Linux distros and I think that the Makefile should play a bigger role here, instead of the README.md.

**Comment by vxlcxn** [comment]
More importantly it's why we have ``cc``; a symlink to either gcc or clang which is installed on the system. This proposal is unnecessary.

**Comment by LouCle** [comment]
@medvednikov Please close

**Comment by Oxylibrium** [comment]
Curious as to why this is needed - @JasonHonor what causes the existing `cc` command to fail on CentOS?

**Comment by medvednikov** [comment]
@JasonHonor @Bowero what's wrong with `cc -std=c11 ` on these distros?

**Comment by Bowero** [comment]
`cc` defaults to `gcc`, which gives segmentation faults. This problem can be found in tens of issues. `clang` does not have this error.

Using `clang` does not fix everything though. `cc` is used in various other situations too. Compiling `tetris.v` for example, also results in a segfault. A solution for this is setting `clang` as the default compiler for `cc`, as I have done. After doing this, everything works perfectly.

```
sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
```

**Comment by Bowero** [comment]
Please look at another open PR: #451

**Comment by medvednikov** [comment]
This was fixed.

**Pull request closed without merging**
