### PR TITLE
doc: reorganize sorting

### PR DESCRIPTION
**Pull request by kahsa**
The documentation has become more complete, but some topics were scattered all over the place and were difficult to read, so I have reorganized them, especially those related to compilation and C.

### CODE REVIEW

**Comment by kahsa** [comment]
So far, I have changed the order and made some minor modifications, but now I will also modify the table of contents.

**Review by spytheman — COMMENTED** [review]
As they say "cool URIs do not change" (without good reason).

**Comment by kahsa** [comment]
what do you mean??

**Comment by kahsa** [comment]
@spytheman Did you read it in HTML?
Or did you just spinalize it?
I think it was very well organized, don't you?
Can you give me some specific thoughts on what you read?

**Comment by spytheman** [comment]
I read everything, and it would take too much time to point out everything that I do not agree, so I will just point out 2 specific examples:
```md
- ## Module imports
+ ## Modules
```
Changing that just because you do not like it in the original, is making all the links that point to the old section invalid, without bringing significant clarification.

```md
-* [Package Management](#package-management)
-	* [Publish package](#publish-package)
+* [Module Management](#module-management)
+	* [Publish module](#publish-module)
```
Same thing - it seems that you are re-organizing things just for the sake of it.

You will have much better chances of your PRs getting accepted, if:
a) you do smaller ones, that are easier to review (and accept/reject individually).
b) you make logical changes, describing the need for each. Just not liking something, is *not a good reason* to change it.

A PR that reorganizes the universe so to speak, is *VERY UNLIKELY* to be accepted.

**Comment by kahsa** [comment]
Oh, you think it's just because of MY Likeness.
Humm, you are wrong.

And, Package? or Module? in V.
Not consistent.

Smaller, OK you are right.

Logcal change, humm,  That is where you should be specific.

**Comment by kahsa** [comment]
OK, I will go step by step PR.

**Comment by kahsa** [comment]
In any case, the document needs to be organized by someone.
A half-baked table of contents will lead the reader astray.
Related topics should be well organized.
If I am not doing a good enough job, someone else who is competent should do it. I strongly hope so.
You will not understand why I am having trouble because you already have the doc all in your head.

**Comment by spytheman** [comment]
A package can contain multiple modules. In V a module is pretty much equivalent to just a single folder.

=> What is published is not modules, but packages.

**Comment by spytheman** [comment]
> Humm, you are wrong.

It will not be the first time 🤷🏻‍♂️ . That is why I need reasons for the changes and smaller PRs, if there are no reasons pointed out, so I could infer them from the changes themselves.

**Comment by spytheman** [comment]
> In any case, the document needs to be organized by someone.
> A half-baked table of contents will lead the reader astray.
> Related topics should be well organized.

I agree with these points. I just do not agree with the way you do it in this PR - combining multiple unrelated things (some of them very arguable or even wrong) in the same bowl, is not a recipe for a delicious meal, so to speak.

**Comment by kahsa** [comment]
That's right. That's why I wanted to PR and get your opinion, but you didn't and suddenly closed it lol

**Comment by kahsa** [comment]
> A package can contain multiple modules. In V a module is pretty much equivalent to just a single folder.

Humm, it should be documented. Fist time I heard it.

**Comment by kahsa** [comment]
What is the precise definition?

**Pull request closed without merging**
