### PR TITLE
run message handlers in threads

### PR DESCRIPTION
**Pull request by abom**
In order to have parallel message handlers without one of them blocking the rest, can we run every handler in a thread?

```
ws.on_message(fn(mut c ws.Client, ms ws.Message)? {
   c.on_message(fn(mut c ws.Client, ms ws.Message)? {
        // this will be blocked
   }

   // blocking call here will block other handlers
}
```

This pull request is just a small change for `send_message_event` to do so, still without any synchronization mechanism for client writes or message access.

Can we have this or it's just seems a bad idea and cannot be done this way (or in any other way)?

### CODE REVIEW

**Comment by spytheman** [comment]
To me, that seems like a bad idea. Writing multithreaded code is more complex than writing single threaded code, and forcing all clients to deal with callbacks running in different threads, will be inconvenient for most.

The client program can launch its own threads if it is needed.

**Comment by xmonader** [comment]
> The client program can launch its own threads if it is needed.
@spytheman, that's exactly what we were trying to do, but in the end all was getting blocked here. 

if you can check https://github.com/freeflowuniverse/crystallib/issues/84 and give an alternative working approach, it'd be great. This is our current implementation based on this PR https://github.com/freeflowuniverse/twinactions/pull/5

**Comment by medvednikov** [comment]
The http server uses threads/coroutines, so why not websocket?

**Comment by spytheman** [comment]
> The http server uses threads/coroutines, so why not websocket?

http connections are usually stateless and short lived, and so rarely need to share state. In contrast, websocket connections are long lived, and many messages can pass in each connection, to each client.

The proposed change would have made the handling of each *message* to use a new thread, forcing the complexity of multi-threading and synchronization on all websocket clients, whether they want it or not.

As it is, it is easy for each client to decide to launch a new thread per message if it so chooses. Opting out of multithreading is much harder.

**Pull request closed without merging**
