### PR TITLE
Fix double

### PR DESCRIPTION
**Pull request by kindlychung**

### CODE REVIEW

**Comment by Bowero** [comment]
Please watch the fact that this PR now includes multiple commits about different topics.

**Comment by medvednikov** [comment]
the `double` thing was fixed yesterday.

please rename the extension function to `ext`:

https://golang.org/pkg/path/filepath/#Ext

I don't want stdlib names to be too different from go.

**Comment by whoizit** [comment]
First commit already pushed
Second should be moved to `v/examples/.gitignore`, cause we can easily put this directory into a separate repository if there are too many examples

**Comment by whoizit** [comment]
related with second commit https://github.com/vlang/v/pull/667

**Comment by whoizit** [comment]
it should be closed cause all this changes already pushed. Also we should'nt change hello_world

**Pull request closed without merging**
