### PR TITLE
[doc/docs.md] Use nested list for Table of Contents

### PR DESCRIPTION
**Pull request by ntrel**
A nested list is much easier to browse than a table.
Move `Imports` section below `Arrays` and `Maps` for `Types` grouping.
Move `Defer` section to `Statements` group.
Move `vfmt` section next to `Profiling` for `Tools` group.

2 columns: https://github.com/vlang/v/blob/982e93512eb5490d9421e221da7eb84951401c3a/doc/docs.md

3 columns: https://github.com/vlang/v/blob/4279b24f07dbe5c6571fc992923affe54589281f/doc/docs.md

### CODE REVIEW

**Comment by medvednikov** [comment]
The reason I used a table is to save vertical space, but it does look ugly...

**Comment by medvednikov** [comment]
Nice, didn't think of this for some reason. I think 3 columns will fit.

**Comment by ntrel** [comment]
@medvednikov OK, I've made 3 columns now. It's nice that the first column is the simpler stuff, 2nd intermediate and 3rd Advanced + Appendices.

**Comment by medvednikov** [comment]
Looks lovely. Good job!

Thanks

**Comment by medvednikov** [comment]
Whoops, looks like your last commit messed up the alignment a bit

**Comment by ntrel** [comment]
@medvednikov Sorry. This commit should fix that:
https://github.com/ntrel/V/commit/729ac94ac3bb000d7aff5015ca58df5e8048f684

Or if you want the top level bullets you can revert my last commit before merge.

**Comment by ntrel** [comment]
Actually that commit isn't good, the top-level sections are on the same line!

**Comment by ntrel** [comment]
I'll make a pull to fix

**Comment by ntrel** [comment]
https://github.com/vlang/v/pull/5519

**Pull request merged**
