### PR TITLE
net.http: fix chunked decoding of response body

### LINKED ISSUE #18094: net.html: parsing in concurrent tasks results in `substr(<range>) out of bounds`
### Describe the bug

Although this bug isn't always present, its probability of occurring rises with the number of items we add. In the case of 5 requests in the reproduction, the likelihood of encountering this bug is very high. So you probably won't need to run it repeatedly.

### Expected Behavior

Parsing works.

### Current Behavior

```
V panic: substr(7, 1047477) out of bounds (len=545055)
# ...
005f48d2 : at ???: RUNTIME ERROR: invalid memory access
```

### Reproduction Steps

```v
module main

import net.html
import sync.pool

fn main() {
	mut pp := pool.new_pool_processor(callback: get_news)
	pp.work_on_items(['inab', 'cyto', 'top', 'tsla', 'tela'])
}

fn get_news(mut pp pool.PoolProcessor, idx int, wid int) voidptr {
	ticker := pp.get_item[string](idx)

	resp := http.get('https://www.google.com/search?${ticker}') or {
		eprintln('Initial request failed for: ${ticker} ${err}')
		return pool.no_result
	}
	if resp.status_code != 200 {
		eprintln('Failed requesting press release: ${resp.status}')
		return pool.no_result
	}
	mut doc := html.parse(resp.body)
	/*
	further process doc
	...*/

	return pool.no_result
}
```

### Possible Solution

_No response_

### Additional Information/Context

The above code has been reduced to not contain headers and workarounds which help us to avoid another common issue we are encountering with concurrent requests: `SSL handshake failed`. So running the above reproduction is likely to trigger this error as well.

As a workaround, we usually add custom headers and wrap the requests in a 'try_request' function that retries failed requests due to SSL handshake errors. 

### V version

0.3.4

### Environment details (OS name and version, etc.)

Linux, arch.

### PR DESCRIPTION
**Pull request by tobealive**
fixes #18094

This PR adds a check that ensures position increments during chunked decoding are within text bounds. This should help resolve out-of-bounds errors that can occur when making concurrent requests. I'm experiencing this issue on Linux based systems but not on macOS. While this check is a way to deal with it, the root cause of the underlying problem with concurrent requests on Linux should be investigated further.

### CODE REVIEW

**Comment by medvednikov** [comment]
Amazing work, thank you!

I think should be possible to add a test for this to avoid regressions in the futre.

**Comment by medvednikov** [comment]
Just a simple client + server, run together via CI.

**Comment by tobealive** [comment]
Okay I'll see what I can do! Thanks @medvednikov 

Another thing that came up during working on this was curiosity about max_bytes. I.e. go is using 8KiB. Should we also change something here?

**Comment by JalonSolov** [comment]
Since the sending side is the one that decides how large the chunks will be (there is no standard defined size), it doesn't really matter what size the receiver thinks it needs.

The only way to be sure you had the "right" size would be to read the first few bytes to get the size of the chunk, _then_ allocate the buffer.

Otherwise, just pick something and hope it's big enough for whatever the sender may send.

**Comment by tobealive** [comment]
I'm appreciating your input @JalonSolov, thank you 🙂

I'd just go with the 8*1024 max length for a chunk then. I would reason that it should result in fewer chunks being processed, potentially reducing the overhead of processing each chunk. Also following the inspiration of go and having checked on nims max length for a read.

Converting this to a draft until I have finished the CI, adapt the old test to the new reader and cleaned up the comments.

**Comment by tobealive** [comment]
Hey @spytheman, sorry about the inconvenience.

Using the buffered reader method, we don't experience the `string out of bounds` anymore. 
I can reproduce this everytime when running the provided test code above for a few seconds.

But so is the error when returning the body without decoding. I'll look into the chunked decoding again.

**Comment by tobealive** [comment]
Thanks @spytheman 

then I'd implement this and make this PR into adding a CI test to cover this case if that's fine.

To scan for a underlying reason, any of the urls in the example should work for a reproduction:
https://finance.yahoo.com/quote/inab/key-statistics

**Comment by tobealive** [comment]
Sorry about the delay. It's been a busy week and I haven't been able to reproduce the issue yet by sending a request to a simple server that responds with the HTML from the problematic URL. I'll take a closer look at it over the weekend and hopefully come up with something that can actually cover this case.

**Comment by tobealive** [comment]
I put in some hours this evening trying to reproduce the error by sending requests to a locally hosted server, but unfortunately, it remained unsuccessful. So I can't serve with an automatable test case running on a local server that would catch this error. Since this seemed to be a dead end, I wanted to take another look at the chunk scanner to give it a proper fix. Afaik, the actual solution to this problem is to check if the position increment is still within the bounds of the text.

Furthermore, it's not just "bloated" URLs like the Yahoo URL mentioned earlier that cause this issue, but it's also possible to reproduce it using a GitHub URL. You can run the code below on master and the PR and see that the error should be fixed with the recent change.

If adding a request loop like this as a test is something that is desired, I can serve with that. Please let me know your thoughts on this @medvednikov @spytheman 

```v
module main

import net.http
import sync.pool

fn main() {
	urls := [
		'https://github.com/vlang/v',
		'https://github.com/vlang/v',
		'https://github.com/vlang/v',
		'https://github.com/vlang/v',
		'https://github.com/vlang/v',
	]
	for i := 0; i < 10; i++ {
		mut pp := pool.new_pool_processor(callback: get_news)
		pp.work_on_items(urls)
	}
}

fn get_news(mut pp pool.PoolProcessor, idx int, wid int) voidptr {
	url := pp.get_item[string](idx)

	mut req := http.Request{
		url: url
		method: .get
	}
	req.add_header(.user_agent, 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36')
	req.add_header(.content_type, 'text/html')

	resp := req.do() or {
		println(err)
		return pool.no_result
	}
	body := resp.body
	println(body.len)

	return pool.no_result
}
```

**Comment by tobealive** [comment]
To narrow it down further: on mac, we do not run into this issue. On linux, compiling with `-gc none` stops this issue from happening.

**Pull request closed without merging**
