### PR TITLE
ast: add a type_size() method

### PR DESCRIPTION
**Pull request by spaceface777**

### CODE REVIEW

**Comment by StunxFS** [comment]
Also in the transformer it would be nice to replace `sizeof(T)` with a integer literal obtained with this function

**Comment by spaceface777** [comment]
@StunxFS imho, we should keep the transformer as-is, for several reasons:

1. First of all, it is impossible for V to have full information on what the final size of all types will be. For example, a programmer can define a C struct as `struct C.Foo {}` if they do not plan on using any of the fields within it, even if the signature does not match what the C struct actually looks like; the definition of the structure could be changed by the C preprocessor, etc.
2. The _implementation_ of the function is still not perfect; there are a ton of other aspects that go into determining the size of a type that the function doesn't currently take into account (packed structs, for example).
3. The C compiler is responsible for converting code into machine code, so it should also be the one deciding 
4. In C, `sizeof()` already compiles down to a constant anyways, so we wouldn't get any performance benefits anyways :)

The purpose of this function is to return V's best guess on what the size of a type will be, but not the single source of truth for that information.

**Comment by JalonSolov** [comment]
As many changes as possible should be made _before_ the cgen stage.

Otherwise, every _other_ stage (native, js, etc.) has to re-implement the same things.

**Review by spytheman — APPROVED** [review]
Great work, it will be very handy for the interpreter too.

**Pull request merged**
