### PR TITLE
math: added basic stats operations

### PR DESCRIPTION
**Pull request by archanpatkar**
This PR adds some basic statistical operations for f64 arrays-

1. ```freq``` - Frequency
2. ```mean``` - Mean
3. ```geometric_mean``` - Geometric Mean
4. ```harmonic_mean``` - Harmonic Mean
5. ```median``` - Median
6. ```mode``` - Mode
7. ```rms``` - Root Mean Square
8. ```population_variance``` - Population Variance
9. ```sample_variance``` - Sample Variance
10. ```population_stddev``` - Population Standard Deviation
11. ```sample_stddev``` - Sample Standard Deviation
12. ```mean_absdev``` - Mean Absolute Deviation
13. ```min``` - Minimum of the Array
14. ```max``` - Maximum of the Array
15. ```range``` - Range of the Array ( max - min )

Unit tests have been added and cross verified with **Wolfram Alpha**

### CODE REVIEW

**Comment by d2verb** [comment]
imo, you should deal with the case when empty array is passed.

**Comment by archanpatkar** [comment]
@d2verb Thanks, will add the checks in the consequent commit

**Comment by ciubotaru** [comment]
IMHO, 'min' and 'max' belong to 'math' module, but everything else deserves a separate sub-module (e.g. 'math:stat').

**Comment by archanpatkar** [comment]
@ciubotaru Thanks for the suggestion.
 The ```min``` and ```max``` functions are already part of math module, they compare two values (f64) . The ```max``` and ```min``` in the ```stats``` submodule operate on composite source (array) to locate the highest and the lowest value respectively. Shifting can be done but ```min``` and ```max``` operations are [standard](https://en.wikipedia.org/wiki/Sample_maximum_and_minimum) statistical operations. Would like to know your view on this.

**Comment by ciubotaru** [comment]
@archanpatkar, What you are saying makes sense, but this way we will have 'math.max()' for two numbers and 'stats.max()' for an array of numbers. If we only had variadic functions in V...

**Comment by medvednikov** [comment]
Variadic functions will be available soon.

**Pull request merged**
