### PR TITLE
string: Graceful substr() handling like Python slices

### PR DESCRIPTION
**Pull request by dloss**
- Do not overflow or underflow, but always return a sensible string
- Handle negative indexes (counting from the end)
- Add more unit tests for special cases
- Keep existing test cases passing

Think of the indices as pointing between characters,
like in Python:
https://stackoverflow.com/questions/509211/understanding-slice-notation

### CODE REVIEW

**Comment by ntrel** [comment]
Negative indexes are bug-prone, see the link in Alex's comment here: https://github.com/vlang/v/pull/706#issuecomment-506337474.

**Comment by dloss** [comment]
Thanks for the link and the background info. Personally, I think the way slices work in Python has spared me a lot of bugs and off-by-one errors. But if Alex wants to do it like Go, I accept that of course.

How about gracefully handling the other corner cases then, by handling negative indices as 0 and returning an empty string if start>end? Or should these cause runtime errors/crashes?

**Comment by ntrel** [comment]
BTW thanks for submitting your work, with good test coverage. Sorry I was a bit abrupt.

The problem with accidentally negative indexes is that it's not always obvious that a bug has occurred.

Giving a default value has the same issue (but at least the result is stable). But there's another issue with arrays of pointers - in V pointers can't have a default value.

**Comment by dloss** [comment]
No problem. I still worry about the crashes though. And I think one could make the point that substr() will probably called more often with explicit, static arguments, whereas indexing is usually done with changing, variable arguments. But anyhow, it seems it has been decided.

**Comment by ntrel** [comment]
I think invalid indices should call panic, so at least the program can inform the user or save data to a temporary file.

> But anyhow, it seems it has been decided

Indexing for maps is different, 
(currently) returning a default value - see #244. For generic code I think indexing should behave the same whatever the container is.

**Comment by dloss** [comment]
On invalid indexing I actually agree. 😊 Thanks for the pointer to the map issue. Interesting.

**Comment by medvednikov** [comment]
> I think invalid indices should call panic, so at least the program can inform the user or save data to a temporary file.

Invalid indices do panic:

```
V panic: string index out of range: -1 / 4
```

@dloss thanks for you contribution, but as it has been discussed already, negative indices are not going to be supported.

You can drop me a line via email before implementing something major like this, I answer emails quickly :)

**Pull request closed without merging**
