### PR TITLE
builtin: heap memory usage api

### PR DESCRIPTION
**Pull request by felipensp**
Expose gcboehm's API to get memory usage:

- `gc_memory_use()` _returns the total memory use in bytes by all allocated blocks_
- `gc_heap_usage()` _returns the heap usage info_

```V
import time

[heap]
struct Test {
	a []int
}

fn stats() {
	s := gc_heap_usage()
	eprintln('gc_memory_use: ${gc_memory_use():7} | heap_size: ${s.heap_size:7} | free_bytes: ${s.free_bytes:7} | total_bytes: ${s.total_bytes:7} | bytes_since_gc: ${s.bytes_since_gc:7}')
}

fn main() {
	stats()
	for {
		a := Test{
			a: [1].repeat(10)
		}
		b := Test{
			a: [1].repeat(20)
		}
		c := Test{
			a: [1].repeat(30)
		}
		_ := 'a:${a} | b:${b} | c:${c}'
		stats()
		time.sleep(10 * time.millisecond)
	}
}
```

```
gc_memory_use:  192512 | heap_size:  131072 | free_bytes:   45056 | total_bytes:   18400 | bytes_since_gc:   18400
gc_memory_use:  229376 | heap_size:  131072 | free_bytes:    8192 | total_bytes:   23168 | bytes_since_gc:   23168
gc_memory_use:  229376 | heap_size:  131072 | free_bytes:    8192 | total_bytes:   27936 | bytes_since_gc:   27936
gc_memory_use:  233472 | heap_size:  131072 | free_bytes:    4096 | total_bytes:   32704 | bytes_since_gc:   32704
gc_memory_use:  233472 | heap_size:  131072 | free_bytes:    4096 | total_bytes:   37472 | bytes_since_gc:   37472
gc_memory_use:  237568 | heap_size:  131072 | free_bytes:       0 | total_bytes:   42240 | bytes_since_gc:   42240
```

### CODE REVIEW

**Comment by spytheman** [comment]
Imho, it may be better to wrap `GC_get_heap_usage_safe` instead:
```c
/* Return the heap usage information.  This is a thread-safe (atomic)   */
/* alternative for the five above getters.   (This function acquires    */
/* the allocator lock thus preventing data racing and returning the     */
/* consistent result.)  Passing NULL pointer is allowed for any         */
/* argument.  Returned (filled in) values are of word type.             */
GC_API void GC_CALL GC_get_heap_usage_safe(GC_word * /* pheap_size */,
                                           GC_word * /* pfree_bytes */,
                                           GC_word * /* punmapped_bytes */,
                                           GC_word * /* pbytes_since_gc */,
                                           GC_word * /* ptotal_bytes */);
```

The individual functions above are not synchronized, according to the Boehm's GC documentation, and calling them one by one will give inconsistent results on multithreaded systems (the default these days).

**Comment by spytheman** [comment]
`GC_get_memory_use` appears to be safe, according to Boehm's documentation, so its wrapper can stay.

**Comment by spytheman** [comment]
```v
import time

fn C.GC_get_heap_usage_safe(pheap_size &usize, pfree_bytes &usize, punmapped_bytes &usize, pbytes_since_gc &usize, ptotal_bytes &usize)

pub struct GCHeapUsage {
	heap_size      usize
	free_bytes     usize
	total_bytes    usize
	unmapped_bytes usize
	bytes_since_gc usize
}

fn gc_heap_usage() GCHeapUsage {
	mut res := GCHeapUsage{}
	C.GC_get_heap_usage_safe(&res.heap_size, &res.free_bytes, &res.unmapped_bytes, &res.bytes_since_gc,
		&res.total_bytes)
	return res
}

[heap]
struct Test {
	a []int
}

fn stats() {
	s := gc_heap_usage()
	eprintln('gc_memory_use: ${gc_memory_use():7} | heap_size: ${s.heap_size:7} | free_bytes: ${s.free_bytes:7} | total_bytes: ${s.total_bytes:7} | bytes_since_gc: ${s.bytes_since_gc:7}')
}

fn main() {
	stats()
	for {
		a := Test{
			a: [1].repeat(10)
		}
		b := Test{
			a: [1].repeat(20)
		}
		c := Test{
			a: [1].repeat(30)
		}
		_ := 'a:${a} | b:${b} | c:${c}'
		stats()
		time.sleep(10 * time.millisecond)
	}
}
```
^ this prints:
```
gc_memory_use:  352256 | heap_size:  278528 | free_bytes:   32768 | total_bytes: 1041136 | bytes_since_gc:  150544
gc_memory_use:  356352 | heap_size:  278528 | free_bytes:   28672 | total_bytes: 1045232 | bytes_since_gc:  154640
gc_memory_use:  364544 | heap_size:  278528 | free_bytes:   20480 | total_bytes: 1053424 | bytes_since_gc:  162832
gc_memory_use:  376832 | heap_size:  278528 | free_bytes:    8192 | total_bytes: 1065680 | bytes_since_gc:  175088
gc_memory_use:  376832 | heap_size:  278528 | free_bytes:    8192 | total_bytes: 1065680 | bytes_since_gc:  175088
gc_memory_use:  376832 | heap_size:  278528 | free_bytes:    8192 | total_bytes: 1065680 | bytes_since_gc:  175088
gc_memory_use:  385024 | heap_size:  278528 | free_bytes:       0 | total_bytes: 1073792 | bytes_since_gc:  183200
gc_memory_use:  249856 | heap_size:  278528 | free_bytes:  135168 | total_bytes: 1077856 | bytes_since_gc:    4064
gc_memory_use:  249856 | heap_size:  278528 | free_bytes:  135168 | total_bytes: 1077856 | bytes_since_gc:    4064
gc_memory_use:  249856 | heap_size:  278528 | free_bytes:  135168 | total_bytes: 1087936 | bytes_since_gc:   14144
gc_memory_use:  249856 | heap_size:  278528 | free_bytes:  135168 | total_bytes: 1087936 | bytes_since_gc:   14144
gc_memory_use:  253952 | heap_size:  278528 | free_bytes:  131072 | total_bytes: 1093936 | bytes_since_gc:   20144
gc_memory_use:  258048 | heap_size:  278528 | free_bytes:  126976 | total_bytes: 1100608 | bytes_since_gc:   26816
gc_memory_use:  258048 | heap_size:  278528 | free_bytes:  126976 | total_bytes: 1100608 | bytes_since_gc:   26816
```
after it stabilizes in a few seconds

**Comment by felipensp** [comment]
> ```v
> import time
> 
> fn C.GC_get_heap_usage_safe(pheap_size &usize, pfree_bytes &usize, punmapped_bytes &usize, pbytes_since_gc &usize, ptotal_bytes &usize)
> 
> pub struct GCHeapUsage {
> 	heap_size      usize
> 	free_bytes     usize
> 	total_bytes    usize
> 	unmapped_bytes usize
> 	bytes_since_gc usize
> }
> 
> fn gc_heap_usage() GCHeapUsage {
> 	mut res := GCHeapUsage{}
> 	C.GC_get_heap_usage_safe(&res.heap_size, &res.free_bytes, &res.unmapped_bytes, &res.bytes_since_gc,
> 		&res.total_bytes)
> 	return res
> }
> 
> [heap]
> struct Test {
> 	a []int
> }
> 
> fn stats() {
> 	s := gc_heap_usage()
> 	eprintln('gc_memory_use: ${gc_memory_use():7} | heap_size: ${s.heap_size:7} | free_bytes: ${s.free_bytes:7} | total_bytes: ${s.total_bytes:7} | bytes_since_gc: ${s.bytes_since_gc:7}')
> }
> 
> fn main() {
> 	stats()
> 	for {
> 		a := Test{
> 			a: [1].repeat(10)
> 		}
> 		b := Test{
> 			a: [1].repeat(20)
> 		}
> 		c := Test{
> 			a: [1].repeat(30)
> 		}
> 		_ := 'a:${a} | b:${b} | c:${c}'
> 		stats()
> 		time.sleep(10 * time.millisecond)
> 	}
> }
> ```
> 
> ^ this prints:
> 
> ```
> gc_memory_use:  352256 | heap_size:  278528 | free_bytes:   32768 | total_bytes: 1041136 | bytes_since_gc:  150544
> gc_memory_use:  356352 | heap_size:  278528 | free_bytes:   28672 | total_bytes: 1045232 | bytes_since_gc:  154640
> gc_memory_use:  364544 | heap_size:  278528 | free_bytes:   20480 | total_bytes: 1053424 | bytes_since_gc:  162832
> gc_memory_use:  376832 | heap_size:  278528 | free_bytes:    8192 | total_bytes: 1065680 | bytes_since_gc:  175088
> gc_memory_use:  376832 | heap_size:  278528 | free_bytes:    8192 | total_bytes: 1065680 | bytes_since_gc:  175088
> gc_memory_use:  376832 | heap_size:  278528 | free_bytes:    8192 | total_bytes: 1065680 | bytes_since_gc:  175088
> gc_memory_use:  385024 | heap_size:  278528 | free_bytes:       0 | total_bytes: 1073792 | bytes_since_gc:  183200
> gc_memory_use:  249856 | heap_size:  278528 | free_bytes:  135168 | total_bytes: 1077856 | bytes_since_gc:    4064
> gc_memory_use:  249856 | heap_size:  278528 | free_bytes:  135168 | total_bytes: 1077856 | bytes_since_gc:    4064
> gc_memory_use:  249856 | heap_size:  278528 | free_bytes:  135168 | total_bytes: 1087936 | bytes_since_gc:   14144
> gc_memory_use:  249856 | heap_size:  278528 | free_bytes:  135168 | total_bytes: 1087936 | bytes_since_gc:   14144
> gc_memory_use:  253952 | heap_size:  278528 | free_bytes:  131072 | total_bytes: 1093936 | bytes_since_gc:   20144
> gc_memory_use:  258048 | heap_size:  278528 | free_bytes:  126976 | total_bytes: 1100608 | bytes_since_gc:   26816
> gc_memory_use:  258048 | heap_size:  278528 | free_bytes:  126976 | total_bytes: 1100608 | bytes_since_gc:   26816
> ```
> 
> after it stabilizes in a few seconds

Nice! I've merged your ideas.

**Pull request merged**
