### PR TITLE
Added support for unpacking zip archives

### PR DESCRIPTION
**Pull request by koplenov**
### Sample usage:
```V
// linux sample
szip.extract_zip_to_dir('./test.zip', './test')
```
```V
// windows sample
szip.extract_zip_to_dir('C:/Path/to/zip.zip', 'C:/Path/to/unzip/directory')
```

```V
path_export_zip := 'path/to/zip.zip'
path_to_dir := 'path/to/unzip/directory'

if szip.extract_zip_to_dir(path_export_zip, path_to_dir){
	println('Success unzip')
} else {
	println('Fail unzip')
}
```

#### fn szip.extract_zip_to_dir
> fn szip.extract_zip_to_dir(path_export_zip, path_to_dir) bool

Extract zip archive to path

### CODE REVIEW

**Comment by spytheman** [comment]
Please add a small test for that in vlib/szip/szip_test.v .

**Comment by koplenov** [comment]
Oki

**Comment by Terisback** [comment]
@koplenov ???

**Comment by JalonSolov** [comment]
And even deleted the repo already.  Wow.

**Comment by koplenov** [comment]
https://github.com/vlang/v/pull/9555

**Comment by koplenov** [comment]
> And even deleted the repo already. Wow.

The easiest and fastest way to make fresh changes to the repository
(Or I probably don't know Git very well :D)

**Comment by JalonSolov** [comment]
Heh.  I do the same thing.  No worries.

**Pull request closed without merging**
