### PR TITLE
string: add is_upper/is_lower and fix parser.match_expr error

### PR DESCRIPTION
**Pull request by yuyi98**
This PR add is_upper in string.v and fix parser.match_expr error when process all capital const value.

- Add `is_upper` in string.v and add `test_upper` in string_test.v.
- Add `is_lower` in strng.v and add `test_lower` in string_test.v.
- Add `is_capital` in string.v and add `test_capital` in string_test.v.
- Add `is_title` in string.v and add `test_title` in string_test.v.
- Fix `match_expr` in parser.v error, solve the problem that all of the const values are in capitals are judged to be Sum_type using string.is_upper.

### CODE REVIEW

**Comment by Delta456** [comment]
For all checking functions you can just do `s == s.upper()` and `capitalize()` and `title()` names are better than `to_title()` and `to_capital()` IMO.

**Comment by yuyi98** [comment]
`s == s.upper()` impact on performance.
`capitalize` and `is_capitalized` , Are they appropriate?
`title` and `is_titled`, Are they appropriate?

**Comment by Delta456** [comment]
`is_title()` and `is_capitalize()` sound better I think and the check functions do not have Unicode check. I had done a similar PR a long time back https://github.com/vlang/v/pull/1597

**Comment by alexesprit** [comment]
Please, leave `capitalize` and `title` as is. `is_title` and `is_capital` look fine.

**Comment by yuyi98** [comment]
@Delta456  @alexesprit  Thanks, I'll change them.

**Pull request merged**
