### PR TITLE
vdoc: optimize output format

### PR DESCRIPTION
**Pull request by yuyi98**
This PR optimize `v doc` output format.
```
-- -- -- -- -- -- -- -- -- -- -- -- -- -- module os: structs - -- -- -- -- -- -- -- -- -- -- -- -- -
struct File {
        cfile voidptr
        fd int
        opened bool
}
struct FileInfo {
        name string
        size int
}
struct Result {
        exit_code int
        output string
}
-- -- -- -- -- -- -- -- -- -- -- -- -- - module os: functions  -- -- -- -- -- -- -- -- -- -- -- -- -
[ 01 ]  fn base_dir(path string) string
[ 02 ]  fn cache_dir() string
[ 03 ]  fn chdir(path string)
[ 04 ]  fn chmod(path string, mode int)
[ 05 ]  fn clear()
[ 06 ]  fn cp(old, new string) ?bool
[ 07 ]  fn cp_all(osource_path, odest_path string, overwrite bool) ?bool
[ 08 ]  fn create(path string) ?File
[ 09 ]  fn dir(path string) string
[ 10 ]  fn environ() map[string]string
[ 11 ]  fn exec(cmd string) ?Result
[ 12 ]  fn executable() string
[ 13 ]  fn exists(path string) bool
[ 14 ]  fn ext(path string) string
[ 15 ]  fn file_last_mod_unix(path string) int
[ 16 ]  fn file_size(path string) int
[ 17 ]  fn filename(path string) string
[ 18 ]  fn find_abs_path_of_executable(exepath string) ?string
[ 19 ]  fn flush()
[ 20 ]  fn fork() int
[ 21 ]  fn get_error_msg(code int) string
[ 22 ]  fn get_line() string
[ 23 ]  fn get_lines() []string
[ 24 ]  fn get_lines_joined() string
[ 25 ]  fn get_raw_line() string
[ 26 ]  fn getenv(key string) string
[ 27 ]  fn getwd() string
[ 28 ]  fn home_dir() string
[ 29 ]  fn is_abs_path(path string) bool
[ 30 ]  fn is_dir(path string) bool
[ 31 ]  fn is_dir_empty(path string) bool
[ 32 ]  fn is_executable(path string) bool
[ 33 ]  fn is_link(path string) bool
[ 34 ]  fn is_readable(path string) bool
[ 35 ]  fn is_writable(path string) bool
[ 36 ]  fn join_path(base string, dirs ...string) string
[ 37 ]  fn log(s string)
[ 38 ]  fn ls(path string) ?[]string
[ 39 ]  fn mkdir(path string) ?bool
[ 40 ]  fn mkdir_all(path string)
[ 41 ]  fn mv(old, new string)
[ 42 ]  fn mv_by_cp(source, target string) ?bool
[ 43 ]  fn on_segfault(f voidptr)
[ 44 ]  fn open(path string) ?File
[ 45 ]  fn open_append(path string) ?File
[ 46 ]  fn open_file(path, mode string, options ...int) ?File
[ 47 ]  fn posix_get_error_msg(code int) string
[ 48 ]  fn read_bytes(path string) ?[]byte
[ 49 ]  fn read_file(path string) ?string
[ 50 ]  fn read_lines(path string) ?[]string
[ 51 ]  fn realpath(fpath string) string
[ 52 ]  fn resource_abs_path(path string) string
[ 53 ]  fn rm(path string)
[ 54 ]  fn rmdir(path string)
[ 55 ]  fn rmdir_all(path string)
[ 56 ]  fn setenv(name, value string, overwrite bool) int
[ 57 ]  fn sigint_to_signal_name(si int) string
[ 58 ]  fn signal(signum int, handler voidptr)
[ 59 ]  fn symlink(origin, target string) ?bool
[ 60 ]  fn system(cmd string) int
[ 61 ]  fn temp_dir() string
[ 62 ]  fn unsetenv(name string) int
[ 63 ]  fn user_os() string
[ 64 ]  fn wait() int
[ 65 ]  fn walk(path string, f anon_18_1)
[ 66 ]  fn walk_ext(path, ext string) []string
[ 67 ]  fn write_file(path, text string)
-- -- -- -- -- -- -- -- -- -- -- -- -- -- module os: methods - -- -- -- -- -- -- -- -- -- -- -- -- -
[ 01 ]  fn (f File) is_opened() bool
[ 02 ]  fn (f File) read_bytes(size int) []byte
[ 03 ]  fn (f File) read_bytes_at(size, pos int) []byte
[ 04 ]  fn (f mut File) close()
[ 05 ]  fn (f mut File) flush()
[ 06 ]  fn (f mut File) write(s string)
[ 07 ]  fn (f mut File) write_bytes(data voidptr, size int)
[ 08 ]  fn (f mut File) write_bytes_at(data voidptr, size, pos int)
[ 09 ]  fn (f mut File) writeln(s string)
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
```

### CODE REVIEW

**Comment by medvednikov** [comment]
There's no need in printing function numbers or -----

**Comment by yuyi98** [comment]
Sorry, I thought it showed more clarity and hierarchy.

**Comment by medvednikov** [comment]
vdoc's format is the same as godoc.

Methods will be grouped under types.

Structs are grouped together, no need to add a header "structs".

Function number is not used anywhere, and would confuse users/

**Comment by medvednikov** [comment]
To save time, it's good to ask me on Discord before implementing something ;)

**Pull request closed without merging**
