### PR TITLE
vweb2: create a sse example

### PR DESCRIPTION
**Pull request by enghitalo**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at e927c6b</samp>

This pull request adds a new example of using server-sent events (SSE) with `vweb` to create a simple notification system. It consists of a back-end server that sends notifications to connected clients, a front-end server that serves the web page and the local SSE connection, and the web page that displays the messages and alerts. The example demonstrates how to use the `vweb.sse` module and the `EventSource` API to implement the SSE protocol.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at e927c6b</samp>

*  Implement a simple SSE-based communication system between a back-end and a front-end server ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-d0bce7407650c65fb5aaba4de6372ddd9f5b41a99a1aaa8464bfb28bb21ccb8bR1-R62), [link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-b2fb2c930df518446b47832dc070f149314575a919652381128432571c357d8aR1-R19), [link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-67098c88c92ee3898b1419805d478130d3589c560d98d9ceea00f53fa3efe5c0R1-R87), [link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-21025b45e43f7e027daa46fca6593fc099a1e0fff7dc2e9521f91a5c94da0974R1-R37))
  * Add a new file `main.v` that runs the back-end server on port 9001 and handles two endpoints: `/sse` for SSE connections and `/notification` for notification messages ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-d0bce7407650c65fb5aaba4de6372ddd9f5b41a99a1aaa8464bfb28bb21ccb8bR1-R62))
    * Use the `vweb.sse` module to create and manage a shared array of `sse.SSEConnection` objects and send SSE messages to the clients ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-d0bce7407650c65fb5aaba4de6372ddd9f5b41a99a1aaa8464bfb28bb21ccb8bR1-R62))
    * Use the `net`, `time` and `rand` modules to generate random notification messages and send them to a local UDP socket ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-d0bce7407650c65fb5aaba4de6372ddd9f5b41a99a1aaa8464bfb28bb21ccb8bR1-R62))
  * Add a new file `main.v` that runs the front-end server on port 8080 and handles the `/sse` endpoint for the local SSE connection ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-21025b45e43f7e027daa46fca6593fc099a1e0fff7dc2e9521f91a5c94da0974R1-R37))
    * Use the `vweb` module to serve the static files from the `assets` folder and the `index.html` file ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-21025b45e43f7e027daa46fca6593fc099a1e0fff7dc2e9521f91a5c94da0974R1-R37))
    * Use the `vweb.sse` module to create and send SSE messages to the client with the same data as the back-end server ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-21025b45e43f7e027daa46fca6593fc099a1e0fff7dc2e9521f91a5c94da0974R1-R37))
    * Use the `os`, `rand` and `time` modules to generate random messages and listen to the local UDP socket for notification messages ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-21025b45e43f7e027daa46fca6593fc099a1e0fff7dc2e9521f91a5c94da0974R1-R37))
    * Use the `$vweb.html()` macro to render the `index.html` file with the given title ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-21025b45e43f7e027daa46fca6593fc099a1e0fff7dc2e9521f91a5c94da0974R1-R37))
  * Add a new file `index.html` that defines the front-end web page that uses SSE to communicate with both servers and display the received messages ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-67098c88c92ee3898b1419805d478130d3589c560d98d9ceea00f53fa3efe5c0R1-R87))
    * Use the `EventSource` object to create and handle two SSE connections: one for the local server and one for the back-end server ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-67098c88c92ee3898b1419805d478130d3589c560d98d9ceea00f53fa3efe5c0R1-R87))
    * Use the `onopen`, `onmessage`, `onerror` and `addEventListener` methods to register callbacks for different events and handle the JSON data from the messages ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-67098c88c92ee3898b1419805d478130d3589c560d98d9ceea00f53fa3efe5c0R1-R87))
    * Use the `close` method to terminate the connection when the user clicks the button ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-67098c88c92ee3898b1419805d478130d3589c560d98d9ceea00f53fa3efe5c0R1-R87))
    * Use the `alert` function to show notifications from the back-end server ([link](https://github.com/vlang/v/pull/20138/files?diff=unified&w=0#diff-67098c88c92ee3898b1419805d478130d3589c560d98d9ceea00f53fa3efe5c0R1-R87))
    
## TODO
- [ ] change to vweb2

### CODE REVIEW

**Comment by enghitalo** [comment]
@Casper64 Can you review it?? There a lot I am missing probably

**Comment by spytheman** [comment]
Please use names like `frontend` or `front_end` but not `front-end` for files and folders.

**Comment by Casper64** [comment]
@enghitalo how is the code supposed to run? Is it two examples one for the frontend and one for backend? In that case I don't really see the need for two seperate examples, the frontend one covers more than the backend case, because users can run the frontend example and see how it works. For the backend example they need to write their own SSE handlers first.

**Comment by enghitalo** [comment]
> @enghitalo how is the code supposed to run? Is it two examples one for the frontend and one for backend? In that case I don't really see the need for two seperate examples, the frontend one covers more than the backend case, because users can run the frontend example and see how it works. For the backend example they need to write their own SSE handlers first.

Hi, @Casper64. The back-end one shows a more real world application. With cors manipulation and SSE connection. Both need work together. I don't know why but I missed the part I wrote in vweb2, that's why I tagged you here. I'll have to redo it, sorry about that.

**Comment by Casper64** [comment]
@enghitalo  No problem, including CORS is a good idea.  Btw I just pushed a pr for SSE in `x.vweb` #20203

**Pull request closed without merging**
