### PR TITLE
array.v: added support to print arrays of floats

### PR DESCRIPTION
**Pull request by Henrixounez**
Solves #294

### CODE REVIEW

**Comment by Bowero** [comment]
It solves the issue indeed, but it is only for floats.

```
fn main() {
        arr := [i8(16)]
        println(arr)
}
```

This still doesn't work, for example.

**Comment by Henrixounez** [comment]
I added str for every numerical types of V.
I also had to add f32 argument for sprintf in parser otherwise it couldn't be displayed.

**Comment by medvednikov** [comment]
Arrays are not going to be implemented with generics to save space. I'll implement a `.str()` method for all arrays today without copy pasting it.

**Comment by medvednikov** [comment]
This has finally been implemented for all array types.

**Pull request closed without merging**
