### PR TITLE
array: add reduce() method

### PR DESCRIPTION
**Pull request by donnisnoni95**
## Description
The reduce() method executes a reducer function (that you provide) on each element of the array, resulting in a single output value.

## Usage
```go
fn sum(prev int, curr int) int {
	return prev + curr
}

fn sub(prev int, curr int) int {
	return prev - curr
}

fn main() {
	a := [1, 2, 3]
	b := a.reduce(sum, 0)
	c := a.reduce(sub, 0)
	d := a.reduce(sum, -1)
	println(b)
	println(c)
	println(d)
}

```
### Expected Output
```go
6
-6
5
```

### CODE REVIEW

**Comment by medvednikov** [comment]
`reduce` methods take just the function argument in most languages.

**Comment by donnisnoni95** [comment]
@medvednikov ok... I will remove second param

**Comment by joe-conigliaro** [comment]
@donnisnoni95 seems good to me, instead of specifying initial value you cal also just do this:
```
a := [1, 2, 3]
-1 + a.reduce(sum)
5 * a.reduce(mul)
```

**Comment by donnisnoni95** [comment]
@joe-conigliaro Great !!

**Pull request merged**
