### PR TITLE
cgen: implement sum type str gen

### PR DESCRIPTION
**Pull request by danieldaeschle**
This implements str() generation for sumtypes.

TODO:
- [x] print nested in struct
- [x] print int, string, struct etc.
- [x] print as pointer
- [ ] print as pointer nested in struct

### CODE REVIEW

**Comment by danieldaeschle** [comment]
This not working completely and missing some tests

**Comment by danieldaeschle** [comment]
last test (which is disabled) doesn't even work with non-sum-types. This is a bug which should be fixed.

**Comment by danieldaeschle** [comment]
i think it can be merged.

**Comment by medvednikov** [comment]
Nice! Thanks.

**Pull request merged**
