### PR TITLE
docs: enhance the `.vsh` section, as well as the description of the V's script mode (no `fn main(){}`)

### PR DESCRIPTION
**Pull request by spytheman**

### CODE REVIEW

**Comment by kenaryn** [comment]
By declaration, do you mean statement or expression? 😄
In the event of the latter, is it perhaps a ground expression? (Yes I'm puzzling I know!) 😅
You may want to add that a global module has its symbol  made visible by other users of the module module via public accessibility policy.

Also, can you describe what performs `-S v` in the trailing section of the shebang?

**Comment by spytheman** [comment]
> By declaration, do you mean statement or expression?

I do mean just declaration, so that is what I used.
All declarations are statements in V, but not all statements are declarations.

> In the event of the latter, is it perhaps a ground expression? (Yes I'm puzzling I know!)

I do not understand you, sorry.

> You may want to add that a global module has its symbol made visible by other users of the module via public accessibility policy.

I do not want that - that is a very confusing sentence.

> Also, can you describe what performs -S v in the trailing section of the shebang?

Yes, I can - from `man env`:
```
       -S, --split-string=S
              process and split S into separate arguments; used to pass multiple arguments on shebang lines
```

It essentially allows you to pass different additional arguments like `-prod -cc gcc` etc for example. This however is out of scope for the V documentation - the `env` command has its own man page that does it.

**Comment by spytheman** [comment]
> You may want to add that a global module has its symbol made visible by other users of the module via public accessibility policy because the (from now on) non-required fully qualified name of the predicate mkdir is merely a consequence of the aforementioned cause.

Hm, I now see what you mean, but that is already done here:
image

**Comment by kenaryn** [comment]
As you wish.
For an auxilliary note, a ground expression is an expression consisting of symbols and parentheses, which is a sequence of zero or more ground terms. A term  is either a symbol of or a ground expression enclosed in parentheses in the sense of a language like Refal-5, Refal-5lambda and Refal+.

**Pull request merged**
