### PR TITLE
checker: disallow op= and infix on a voidptr

### PR DESCRIPTION
**Pull request by ntrel**
MSVC does not allow `void*` arithmetic, and I suspect it's not in the C standard.

Note: postfix was already disallowed.
~~Merge `plus_assign` and `minus_assign` match branches.~~

For infix only a voidptr on the left is checked. This doesn't disallow `int + voidptr`, but I'll handle that in a separate pull because other checks don't handle a pointer on the right either.

### CODE REVIEW

**Comment by ntrel** [comment]
> Merge plus_assign and minus_assign match branches.

I need to split this out.

**Comment by Delta456** [comment]
MSVC does not allow void* arithmetic, and I suspect it's not in the C standard

Yes, it is MSVC does not allow void* arithmetic, and I suspect it's not in the C standard

**Comment by JalonSolov** [comment]
GCC extension is not a C standard, it is GCC specific.

**Comment by ntrel** [comment]
Examples in examples/term.ui are failing on macos and ubuntu, but I can't reproduce them on my Windows machine :-/

**Comment by ntrel** [comment]
> Examples in examples/term.ui are failing on macos and ubuntu

If the errors are due to voidptr arithmetic, please could someone (with a *nix system) post the offending lines here and I'll fix them. (The CI just says FAIL).

**Comment by spytheman** [comment]
@ntrel , I've removed the -silent flag; the errors should show now; they are something like:
```
FAIL [51/63]   272.677 ms examples/term.ui/rectangles.v
vlib/term/ui/input_nix.c.v:49:45: error: `+` cannot be used with `voidptr`
   47 | fn (mut ctx Context) shift(len int) {
   48 |     unsafe {
   49 |         C.memmove(ctx.read_buf.data, ctx.read_buf.data + len, ctx.read_buf.cap - len)
      |                                                   ~~~~
   50 |         ctx.resize_arr(ctx.read_buf.len - len)
   51 |     }
vlib/term/ui/termios_nix.c.v:224:49: error: `+` cannot be used with `voidptr`
  222 |             if ctx.cfg.event_fn != voidptr(0) {
  223 |                 unsafe {
  224 |                     len := C.read(C.STDIN_FILENO, ctx.read_buf.data + ctx.read_buf.len, ctx.read_buf.cap - ctx.read_buf.len)
      |                                                                ~~~~
  225 |                     ctx.resize_arr(ctx.read_buf.len + len)
  226 |                 }
```

**Comment by ntrel** [comment]
@spytheman Thanks!

**Comment by ntrel** [comment]
Tests green :-D

**Pull request merged**
