### PR TITLE
sokol, gg: add CKJ support.(Linux only)

### PR DESCRIPTION
**Pull request by hirossan4049**
Added support for CKJ (Chinese, Korean, Japanese) input to sokol and gg. (Linux Only)

**This is a destructive change.**

Incoming Key_down(a〜z,A〜Z) events will be notified to `ckj_input_confirm`.

<br><br>
Example

```v
	app.gg = gg.new_context(
        ...
        ckj_input_pending: jip
        ckj_input_confirm: jic
	)

...
fn jip(text string, length int, first int, caret int, mut app App){
    println("pending_text: $text")
}

fn jic(text string, mut app App){
    println("confirm text: $text")
}
```

スクリーンショット 2021-03-05 14 53 13

### CODE REVIEW

**Comment by spytheman** [comment]
I am against merging that as it is. It should be split in 2 parts imho.
The first - a PR to sokol itself ( https://github.com/floooh/sokol ), and it should work on all platforms that sokol supports, not just linux.
The second - after the first is merged in sokol, we can update our copy of sokol and make the wrapper and gg offer this functionality to user programs.

Merging it as it is, will create a big burden of maintaining that code, when we do update our sokol thirdparty headers, and will break the cross platformness of gg too.

**Comment by kahsa** [comment]
@spytheman  We seriously need IME. Otherwise, we have no way to enter our own language.
To be honest, we are not very familiar with PR, so we don't know how to solve the problem.
Could you please give us some suggestions?

**Comment by JalonSolov** [comment]
He is suggesting to first change sokol.  Submit a change to flooh/sokol repo to make the necessary changes there.  It would be best if those changes worked on all the same platforms sokol supports.

Once the change is accepted there, it will be easy enough to make gg support them as well.

If it is not broken up this way, we will no longer be able to accept changes from the main sokol repo, and would have to maintain our own separate copy from now on.

**Comment by kahsa** [comment]
For example, how about preparing a separate sokol header for IME only, so that it is not used by anyone but IME?

**Comment by kahsa** [comment]
Or is it possible for IME and V to communicate without using sokol?

**Comment by spytheman** [comment]
I have no problem with a separate header - as long as the changes to sokol itself are minimal, so that we can still upgrade it in the future.

**Comment by spytheman** [comment]
> Or is it possible for IME and V to communicate without using sokol?

I do not know, but if it is, that would be ideal.

**Comment by Larpon** [comment]
I fully agree with @spytheman here. I've updated sokol previously for V and had to give up transferring @medvednikov 's changes to `sokol_app.h`. We can't have patches coming in sporadically to something we'll (still) have to keep up-to-date with sokol/master for the time being. It's too hairy and time consuming to keep watching what changes where.

**Comment by Larpon** [comment]
@hirossan4049 - you work is much appreciated! I hope you'll consider contributing to floooh/sokol directly!

**Pull request closed without merging**
