### PR TITLE
http : Added PATCH, DELETE, and PUT methods

### PR DESCRIPTION
**Pull request by KaiLyons**
Adds the methods DELETE, PUT, PATCH

DELETE function adds DELETE method for HTTP
```
pub fn delete(url string) ?Response {
	req := new_request('DELETE', url, '') or {
		return error(err)
	}
	res := req.do() or {
		return error(err)
	}
	return res
}
```
PUT function adds PUT method for HTTP
```
pub fn put(url string) ?Response {
	req := new_request('PUT', url, '') or {
		return error(err)
	}
	res := req.do() or {
		return error(err)
	}
	return res
}
```
PATCH function adds PATCH method for HTTP
```
pub fn patch(url string) ?Response {
	req := new_request('PATCH', url, '') or {
		return error(err)
	}
	res := req.do() or {
		return error(err)
	}
	return res
}
``

### CODE REVIEW

**Comment by spytheman** [comment]
Closes #3434 .

**Comment by spytheman** [comment]
http may need some cleanup afterwards, i.e. extract the repeating code to say:
```v
pub fn method(mname string, url string, data string) ?Response {
	req := new_request(mname, url, data) or { return error(err) }
	res := req.do() or { return error(err)	}
	return res
}
pub fn get(url) ?Response { return method('GET', url, '') }
pub fn post(url) ?Response { return method('POST', url, '') }
pub fn head(url) ?Response { return method('HEAD', url, '') }
pub fn delete(url) ?Response { return method('DELETE', url, '') }
pub fn patch(url) ?Response { return method('PATCH', url, '') }
pub fn put(url) ?Response { return method('PUT', url, '') }
```

**Comment by thecodrr** [comment]
@KaiLyons can you refactor like @spytheman proposed? Or should that be in another PR?

**Comment by KaiLyons** [comment]
> @KaiLyons can you refactor like @spytheman proposed? Or should that be in another PR?

I feel like that should be another PR

**Comment by medvednikov** [comment]
You can push to this branch, and the PR will be updated, let's keep the history clean :)

**Comment by spytheman** [comment]
I can not push to this PR. 
It may be done in a new one - this one also works, after all.

**Pull request merged**
