### PR TITLE
os: rmdir_recursive => rmdir_all just like mkdir_all

### PR DESCRIPTION
**Pull request by yuyi98**
This PR rename `os.rmdir_recursive` to `os.rmdir_all` just like `os.mkdir_all`.

### CODE REVIEW

**Comment by Delta456** [comment]
os.rmdir_recusive is more easy to understand than `os.rmdir_r`.

**Comment by alexesprit** [comment]
> `os.rmdir_recusive` is more easy to understand than `os.rmdir_r`.

Yes, but in this case `os.cp_r` should be renamed. I think this PR is mostly about the consistent naming.

**Comment by Delta456** [comment]
@alexesprit Agreed as the name has now changed to `os.rmdir_all`.

**Comment by medvednikov** [comment]
I think we should continue using Go's naming:

https://golang.org/pkg/os/#RemoveAll

`os.remove_all`

**Comment by yuyi98** [comment]
`os.rm` and `os.rmdir`  => `os.remove`
`os.rmdir_recursive`  => `os.remove_all`
Just like Go do?

**Comment by medvednikov** [comment]
Yes

**Pull request closed without merging**
