### PR TITLE
array: add filter() method

### PR DESCRIPTION
**Pull request by donnisnoni95**
## Description
The `filter()` method creates a new array with all elements that pass the test implemented by the provided function.

## Usage
```go
fn callback(val string, index int, arr []string) bool {
	return val.len >= 6
}

fn main() {
	words := ['spray', 'limit', 'elite', 'exuberant', 'destruction', 'present']
	new_words := words.filter(callback)
	println(new_words)
}
```
### Output 
```go
["exuberant", "destruction", "present"]
```

### CODE REVIEW

**Comment by Delta456** [comment]
Do we really need this right now? I think lambdas and generics should be done first.

**Comment by spytheman** [comment]
@Delta456 why not? IMO, it is a good 80% solution for the most common cases of filtering []string and []int , and can be easily cleaned up when generics are working properly.

**Comment by Delta456** [comment]
We still haven't decided whether to use `array.filter()` or `filter(array, fn)`. We don't even know how generics and lambdas would be implemented. Lets leave this decision to @medvednikov.

**Comment by joe-conigliaro** [comment]
@medvednikov :)

**Comment by spytheman** [comment]
`[0,1,2,3,4,50,51,1001].filter(even_numbers).filter(greater_than_10)`
vs
`filter(filter([0,1,2,3,4,50,51,1001],even_numbers),greater_than_10)`

imo, the first is more readable and also easier to write.

**Comment by medvednikov** [comment]
method syntax

.filter()

**Comment by medvednikov** [comment]
let's keep this until a generic implementation is out

**Pull request merged**
