### PR TITLE
v/checker.v: Disallow pointer arithmetic for InfixExpr outside unsafe {}

### PR DESCRIPTION
**Pull request by ntrel**
Follows on from #5581.
Currently depends on #5619, but I can workaround that if necessary.

Require pointer arithmetic in `ptr op rhs` to be inside an unsafe block.

### CODE REVIEW

**Comment by ntrel** [comment]
@medvednikov Great! So the (updated) changes in #5619 were ok? This pull included them. If not ok I can make a pull to remove the get/set_unsafe code (but keep the unsafe blocks).

**Comment by medvednikov** [comment]
Yes, I decided it's ok, and it's safer this way. Much less error prone.

**Comment by ntrel** [comment]
The next step I'll do is disallowing pointer IndexExpr. Then there's type conversion to pointer.

**Comment by medvednikov** [comment]
@ntrel a bug was just found:

```
type Abc = int | string

fn main() {
    a := Abc(1)

main.v:8:12: error: pointer arithmetic is only allowed in `unsafe` blocks 
    6 |     match a {
    7 |         int {
    8 |             println(a + 2)
      |                     ^
    9 |         }
   10 |         else {}

```

**Pull request merged**
