### PR TITLE
GC-Boehm: fix for Windows

### PR DESCRIPTION
**Pull request by UweKrueger**
This is a small fix for a bug that had crept in with the OpenBSD support in #10300.

GC-Boehm on Windows still needs binaries that have been prepared by @spaceface777 (see #9393). Maybe we should transfer these binaries to a vlang repository and treat them similar to `vlang/tccbin`...

### CODE REVIEW

**Comment by spaceface777** [comment]
> GC-Boehm on Windows still needs binaries that have been prepared by @spaceface777

Not even, since (on Windows) you cannot link to a static library built with a different compiler, and tcc is unable to compile boehm from source, so I haven't been able to get a static boehm binary that works with tcc on Windows.

**Comment by UweKrueger** [comment]
> Not even, since (on Windows) you cannot link to a static library built with a different compiler, and tcc is unable to compile boehm from source, so I haven't been able to get a static boehm binary that works with tcc on Windows.

I see. So the the binaries are gcc specific. Have you been able to compile libgc with msvc?

**Comment by medvednikov** [comment]
> Maybe we should transfer these binaries to a vlang repository and treat them similar to vlang/tccbin

Yes we should, @spytheman already started some work on this.

**Comment by spytheman** [comment]
https://github.com/spytheman/v/tree/improve_boehm_integration

**Comment by spaceface777** [comment]
> > Not even, since (on Windows) you cannot link to a static library built with a different compiler, and tcc is unable to compile boehm from source, so I haven't been able to get a static boehm binary that works with tcc on Windows.
> 
> I see. So the the binaries are gcc specific. Have you been able to compile libgc with msvc?

I have, but the same issue still applies with msvc :|

**Comment by spaceface777** [comment]
> For tcc, we may still need to use precompiled libs on all platforms :-| .

The problem with this is *getting* a precompiled (static) lib that works with tcc on Windows.

**Comment by UweKrueger** [comment]
> The problem with this is _getting_ a precompiled (static) lib that works with tcc on Windows.

Hmm... The main problem seems to be that `tcc` does not support atomic operations. I was able to compile `libgc` using headers from `libatomic_ops`, but then got stuck in compiling that library. :cry:
For the channels implementation we use some inline assembler for atomic operations - just what is needed to make them work. But `libgc` seems to be a little bit more demanding.

Since static builds with `libgc`/`tcc` do not work on Linux either, we might perhaps define that static builds are only supported with gcc/msvc/clang and provide a (highly optimized mscv built) dll for `tcc`.

**Comment by Ekopalypse** [comment]
Excuse my ignorance but why is it necessary to create a DLL for Windows but no SO for Linux/Mac if tcc is to be used?
Or should that be implied?

**Comment by UweKrueger** [comment]
> Excuse my ignorance but why is it necessary to create a DLL for Windows but no SO for Linux/Mac if tcc is to be used?
> Or should that be implied?

That is a legitimate question, however all major Linux distributions and BSDs have a prepared package of `libgc`. E.g. on Debian or Ubuntu you can simply do
`apt install libgc-dev`
as root to get the version that works best for your version of the OS installed system-wide (libs in in `/usr/lib`, headers in `/usr/include`). (Of cause you can also use a graphical tool like `synaptic` for installation). This package is used/needed by all compilers, anyway - so there is no need for us to provide our own one.

I'm not a Mac user but AFAIK most developers seem to use the *Homebrew* 3rd party package selection that allows doing
`brew install libgc`

On Windows there is no such `libgc` package that is associated with the operating system. Software that needs `libgc*.dll` (e.g. Inkscape) brings its own version and installs it in a software specific directory (in this case `C:\Program Files\inkscape\bin\libgc-1.dll` and `C:\Program Files\inkscape\bin\libgcc_s_seh-1.dll`).
So V has to ship it's own version, too, on Windows. (We cannot rely on the user having Inkscape installed... :wink:)

**Comment by Ekopalypse** [comment]
Thanks for the clarification, I think I get it now.

**Pull request merged**
