### PR TITLE
mysql: Add more documentation

### PR DESCRIPTION
**Pull request by donnisnoni**

### CODE REVIEW

**Comment by JalonSolov** [comment]
This is not a good change.  Those comments need to be the way they are for `vdoc` to work properly with them.

See https://github.com/vlang/v/blob/master/doc/docs.md#writing-documentation

**Comment by Larpon** [comment]
Yes, the function name needs to be the first and always use present tense:
```
// func retuns the input
// and more lines if one is not enough
// Example: <optional code here will be validated>
fn func(i int) int {
...
}
```

**Comment by donnisnoni** [comment]
@Larpon Ahhh... sorry for that...  I didn't notice that before.. will commit ASAP!

**Comment by serkonda7** [comment]
Why two PRs?

**Comment by Larpon** [comment]
@serkonda7 - #7824 - adds a README, this PR is focused on function documentation. I've renamed it for clearity

**Comment by donnisnoni** [comment]
https://discord.com/channels/592103645835821068/631271043876519967/795600076117508159

**Pull request merged**
