### PR TITLE
math.bits functions test (tcc problem with 64 bit)

### PR DESCRIPTION
**Pull request by penguindark**
**what's inside**
- test for the bits functions

### CODE REVIEW

**Comment by penguindark** [comment]
@medvednikov 
As i was suspecting **tinycc** does not able to manage well 64 bit operations.
I wrote the test to verify the corecteness of the system.
Does we need to change the `ones_count64` function with another that can run on `tinycc` but that is slower?
Or can we ingore this test?
I need the `bits` functions to write the `f64` to `string` function.

**Comment by joe-conigliaro** [comment]
@penguindark ahh yes I know problem it can be fixed another way using the constant values i will paste

**Comment by penguindark** [comment]
tnx :)

**Comment by joe-conigliaro** [comment]
I made a PR #3698 it fixes the issue however I also renamed some of the functions

**Pull request closed without merging**
