### PR TITLE
clipboard_darwin: fix # being used as comment

### PR DESCRIPTION
**Pull request by serkonda7**
Needed to make https://github.com/vlang/ui/pull/238 pass.

### CODE REVIEW

**Comment by medvednikov** [comment]
It's not used as comment, objective C is injected this way.

**Comment by spytheman** [comment]
I think that these lines should work for the clipboard module to be functional. Commenting them in effect disables clipboard.

**Comment by serkonda7** [comment]
Oh okay, I didn't know.

**Comment by medvednikov** [comment]
@serkonda7 we are probably going to remove # hack entirely and import `.m` files instead

**Pull request closed without merging**
