### PR TITLE
json: fix array_fixed encode/decode

### PR DESCRIPTION
**Pull request by kolts1**
json : adding array_fixed encode/decode to c backend

### CODE REVIEW

**Comment by spytheman** [comment]
Looks good overall, but please add a test too, something like:
```v
import json

struct Abc {
	my_ints [4]int
	my_strs [2]string
}

fn test_json_serialisation_of_fixed_arrays() ? {
	a := Abc{ my_ints: [10,20,30,40]!, my_strs: ['zzz', 'www']! }
	s := json.encode(a)
	dump(s)
	b := json.decode(Abc,s)?
	dump(b)
	assert a == b
}
```

... currently failed to compile, because it generated:
```c
memcpy(res.a,*(Array_fixed_int_4*)_t1.data,4);
```

**Comment by kolts1** [comment]
Hello, how i can keep temporary .c files, that generates by compiler?

**Comment by spytheman** [comment]
Hi @kolts1 . You can pass `-keepc -showcc`, or use `-o file.c` .

**Comment by spytheman** [comment]
Another useful option, when you want to focus on a specific line of what is generated is:
`./v -o - json_fixed_array_test.v |grep memcpy.*Array_fixed_int_4`

**Comment by kolts1** [comment]
Thanks, now i must find how to debug this .c file in visual studio code.

**Comment by medvednikov** [comment]
Doom is broken for some reason.

**Pull request merged**
