### PR TITLE
scanner: refactor ident_dec_number and fix 5a..10 

### PR DESCRIPTION
**Pull request by SleepyRoy**
This PR refactors ident_dec_number function (also adds more comments) so it's easier to understand.
A by-product is fixing range `5a..10`. After this PR it results in an error.

### CODE REVIEW

**Comment by medvednikov** [comment]
can you add a test for the fix?

**Comment by SleepyRoy** [comment]
@medvednikov The tests/num_lit_call_method_test.v for this is already there, but it's in the skip list (still fails in v2). So maybe it's a good idea to merge this after the test is fixed.

**Comment by SleepyRoy** [comment]
@medvednikov a test for `5a..10` error? How to add a test for an error thrown by scanner?

**Comment by medvednikov** [comment]
For example: `vlib/v/checker/tests/inout/struct_unknown_field.out`

**Comment by SleepyRoy** [comment]
@medvednikov How will errors be organized in the future? All be moved to checker folder? I just had a look at it and found errors there are basically parser-related. BTW I also found a error.v file in scanner folder...

**Pull request merged**
