### PR TITLE
return checking: disallow statements after a return, branch check $if, $else, switch, and loops correctly.

### PR DESCRIPTION
**Pull request by schurhammer**
Changes
- compile error if there is a statement after a guaranteed return e.g.
```go
fn eg1() int {
    return 1
    println('hi') // compile error here, "unreachable code"
}

fn eg2() int {
    if true { // note: it doesn't know this always true
        return 1
    }
    println('hi') // no compile error here since the if isn't exhaustive
    return 0
}

fn eg3() int {
    if true { // note: it doesn't know this always true
        return 1
    } else {
        return 0
    }
    println('hi') // compile error here since the if/else is exhaustive and always returns
}
```
- compile-time-if return checking, like the normal `if/else` return checking but for `$if/$else`
- `switch` statement return checking, only returns if all cases return and there is a default case which also returns.
- `p.returns = false` at the end of a `for` loop, almost all loops aren't guaranteed to return.
- fix code so it compiles e.g. removing `return` after `panic`
- add some more output to make_tests.bat e.g.
```
build vc using gcc
build v using vc
..
testing v
testing v.msvc
..
pass/fail
```

### CODE REVIEW

**Comment by schurhammer** [comment]
@medvednikov tests are failing because it's trying to compile it with 0.1.17 (specified in make file), if you compile with master branch it should work. 
It specifically needs the panic/exit count as returns feature.

**Comment by medvednikov** [comment]
I've fixed the makefile @schurhammer

**Comment by schurhammer** [comment]
@medvednikov fyi now it's getting unreachable code in the vid project. Just some unneeded returns it seems. What do you want to do?
Might need to temporarily disable that test or temporarily break the vid repo.
Could also remove the error on unreachable code for now until vid is fixed.

**Comment by medvednikov** [comment]
I've updated Vid.

**Pull request merged**
