### PR TITLE
compiler/main.v: Support CentOS environment

### PR DESCRIPTION
**Pull request by Xiphin**
Support CentOS environment
Built-in v.c: compiler/v.c
Solved it: #382

### CODE REVIEW

**Comment by whoizit** [comment]
switch from gcc to clang it's not solution. Solution it's cc -std=gnu11 (on gcc)

**Comment by Xiphin** [comment]
> switch from gcc to clang it's not solution. Solution it's cc -std=gnu11 (on gcc)

cc compile failed in Centos.
clang is a temporary alternative.
@medvednikov said he will fix it with cc.

**Comment by whoizit** [comment]
#486

**Comment by Xiphin** [comment]
> #486

Try it in CentOS by yourself.

**Comment by medvednikov** [comment]
This was fixed.

**Comment by Xiphin** [comment]
**v.c still compile failed with newest code in CentOS.**
```bash
[root@xlstudio-centos compiler]# cc -v
使用内建 specs。
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
```
CentOS

**Comment by like-c** [comment]
I guess `_Atomic' is for C++. You can try:
1) delete this token in v.c
2) add `-std=gnu11' option in main.v 
3) use make or gcc compile v.c

**Comment by Xiphin** [comment]
> I guess `_Atomic' is for C++. You can try:
> 
> 1. delete this token in v.c
> 2. add `-std=gnu11' option in main.v
> 3. use make or gcc compile v.c

I used clang as an alternative.
Forked and modified: [github.com/Xiphin/v](github.com/Xiphin/v)

**Pull request closed without merging**
