### PR TITLE
doc: move attributes

### PR DESCRIPTION
**Pull request by kahsa**
~~Attributes are one of the basic features of V language, so it is appropriate to include them in Basics, not Advanced topics.
see https://github.com/vlang/v/blob/master/doc/docs.md#required-fields~~

moved it because want readers to read the Attribute before "Hot Code Reloading", before "Calling C."

### CODE REVIEW

**Review by spytheman — COMMENTED** [review]
I disagree a little - for most programs, you do not need attributes in your own V code, especially if you are just learning the language.

They are a tool to tweak the behavior of the compiler in some situations, not as basic as control flow, types, functions etc.

@medvednikov what do you think?

**Comment by kahsa** [comment]
This as well I am not particularly particular about where I put it, but I don't think it is so special information as to be the last.
Would it be better above Advanced tpics?

**Comment by kahsa** [comment]
On the contrary, I ask, what is the reason why this section must stay where it is? @spytheman

**Comment by bogen85** [comment]
@kahsa  I would tend to agree with @spytheman  here.

While yes, `attributes` are core how V works, they are not something that typically someone just learning the language is going to need or be concerned about.

As you learn the language more (because you have dove into writing non-trivial programs) then they are something that needs to be considered and used.

**Comment by kahsa** [comment]
@bogen85 I agree with half of it.
What do you think what is the reason it have to be at last of Advanced topics?
What do you think is the reason why it must be placed behind the C topic?

**Comment by kahsa** [comment]
One of the motivations for this position reorganization is to group C-related topics.
In addition to that, I thought it would be easier to read the grouping of related topics.

**Comment by kahsa** [comment]
The motivation for this reorganization can be found here.
It has been closed, though.
https://github.com/vlang/v/pull/16185#issue-1420186519

**Comment by kahsa** [comment]
I am not particular about the arrangement I made.
Rather, I am willing to discuss with interested persons how it can be reorganized to make it easier for readers to understand, to find the information they want quickly, and to make it better as the only comprehensive document.

**Comment by kahsa** [comment]
If you have a better suggestion than the edits I made, please let me know.
Together we can make this a good, user-friendly document.

**Comment by kahsa** [comment]
Because, unfortunately, this is the only comprehensive documentation of the V language that can be found anywhere on the Internet.

**Comment by kahsa** [comment]
If the information I want to know can be found all over the Internet, as is the case with major languages, I would not be so concerned about the quality of this documentation.
It's just too much trouble.

**Comment by bogen85** [comment]
@kahsa some of the items are `C` related, but most are not, I have no opinion there (in regards to it being next to the `C` topic).

But I still consider it `advanced` in that they are something `most` will not need to concerned about right away when learning `V` and that I already answered.

I guess `most` be a source of the potential disagreement here.

Is `most` a broad audience? (Composed of entry level, Junior, Senior programmers?)

If entry level, obviously an `advanced` subject. For `Junior` and `Senior` yeah, maybe not so advanced. But then again they still my be entry level in regard to V. Just because they are junior/senior does not mean they coming from C/C++/Go/Python backgrounds.

So, based on all that, I'd still consider it should be in the `advanced` section. (Broad audience and not something that needs to be focused on initially).

**Comment by kahsa** [comment]
@bogen85  thanks for your reply.
you missed this?

> Would it be better above Advanced tpics?

Again, I am asking why it is there last of all topics?
No why not in basics, why at last of all of topics.

**Comment by kahsa** [comment]
I'm asking what is the logical reason why the attribute should be behind the Hot Code Reloading rather than the Scripting?

**Comment by kahsa** [comment]
@bogen85 Would you agree with the principle of putting the information you want people to know more quickly at the beginning?
It's better that way to get first-timers to read it, right?
If so, why do you want the Attribute to be read later than "Translating C to V"?

**Comment by kahsa** [comment]
You read a lot of books and documents too, don't you?
They should be chaptered in a logical and reasoned order, and the headings should accurately represent their content.
Of course, with literature, maybe not so much.
Am I saying something so crazy?

**Comment by kahsa** [comment]
Think about it.
There is very little comprehensive, accurate, up-to-date documentation in the V language.
In fact, it would not be too wrong to say that this is the only one.

**Comment by bogen85** [comment]
> Think about it. There is very little comprehensive, accurate, up-to-date documentation in the V language. In fact, it would not be too wrong to say that this is the only one.

> It is good to have `comprehensive, accurate, up-to-date documentation in the V language`.

I totally agree.

All on one page, I totally agree.

> They should be chaptered in a logical and reasoned order, and the headings should accurately represent their content.

And one again. I totally agree.

But we also need to have constructive documentation. (And I agree, you are trying to make it more constructive).

However, many need information in small doses, based on how must they have learned about a subject.

Everything at the same level of importance can be overwhelming and hard to digest at first.

So ordering is very important.

If one has not fully digested the simple things, it is harder to digest the more complex things.

I agree all this needed to documented. But we also don't want documentation to be overwhelming. The current documentation I don't think is (overwhelming that is).

So what I'm saying is, something like `attributes` is something I see as something `most` (which again, might a be source of contention) that one does not need to immediately digest to get started in V. Hopefully people will reread the documentation occasionally (as long as it is short enough, as V's is), because every time they do they can digest more.

**Comment by kahsa** [comment]
> All more advanced (to be digested later) than `attributes` ...

Yes, you get my point.

**Comment by bogen85** [comment]
> > All more advanced (to be digested later) than `attributes` ...
> 
> Yes, you get my point.

https://github.com/vlang/v/blob/master/doc/docs.md#hot-code-reloading


```v
[live]
fn print_message() {
	println('Hello! Modify this message while the program is running.')
}
```

At a bare minimum, any sections that use attributes should be after the attributes section... (IMHO)

Because if not you are introducing a concept that has not been defined yet.
(Which is in opposition to good documentation.)

The need for good centralized documentation also factors in to issues like this:
https://github.com/Alexey-T/CudaText/issues/4473

**Comment by kahsa** [comment]
This is in _Struct_ section https://github.com/vlang/v/blob/master/doc/docs.md#required-fields.
That's why I think Attribute section should be in Basics although I feel it is suitable in Advanced topics.
Well in the real world, things not go so perfectly ;)

**Comment by spytheman** [comment]
> On the contrary, I ask, what is the reason why this section must stay where it is?

I do not defend its current position at all. Imho the Advanced section is currently like a Misc folder in a computer, and can be better structured 100%. 

=> I agree that it can be put somewhere else, and the start of the Advanced section is a good place. I just did not agree, that it should be next to control flow in importance.

**Comment by spytheman** [comment]
> These are in _Struct_ section https://github.com/vlang/v/blob/master/doc/docs.md#required-fields. https://github.com/vlang/v/blob/master/doc/docs.md#trailing-struct-literal-arguments https://github.com/vlang/v/blob/master/doc/docs.md#trailing-struct-literal-arguments That's why I think Attribute section should be in Basics although I feel it is suitable in Advanced topics. Well in the real world, things not go so perfectly ;)

These can be handled better with links/references to the section, so interested readers can skip to it, without burdening most.

**Comment by kahsa** [comment]
I've moved it to the top of Advanced topics.

**Comment by bogen85** [comment]
> These can be handled better with links/references to the section, so interested readers can skip to it, without burdening most.

@kahsa this is what I mean by incrementally digestible based on what the reader needs.

Supply what they need without overwhelming them to fast.

**Comment by kahsa** [comment]
Yes, that is correct.
That's why I also PR to put some links to details in the document.

**Comment by kahsa** [comment]
And what I mean in this https://github.com/vlang/v/pull/16185#issue-1420186519 is it.
Currently, I feel that there are many articles in the first half of the article that do not adequately take such things into account. This is a subjective opinion, though.

**Comment by changrui** [comment]
···
[mutable]
// All local varibles are mutable.
fn calc(i int) {
   a, b, c := 1, 1, 2
   print(a)
   print(b)
   for x in 3..i {
      c := a + b
      println(c)
      a, b := b, c
   } 
}
···

**Comment by spytheman** [comment]
> // All local varibles are mutable.

That changes one of the fundamentals of the language and is highly unlikely to be ever supported @changrui .

**Pull request merged**
