### PR TITLE
checker, cgen: add sumtype-like smartcasting capabilites to interfaces

### LINKED ISSUE #9061: interface types are not smartcasted inside `match` branches
**V version:** 
**OS:** 

**What did you do?**

```v
interface Animal {
    breed string
}

struct Dog {
    breed string
    name  string
}

a := Animal(Dog{ name: 'Rufus' })
match a {
    Dog { println(a.name) } // error: type `Animal` has no field or method `name`
    else { assert false }
}
```

**What did you expect to see?**

`a` should be smartcasted into `Dog` - the code above should compile and print `Rufus`
 
**What did you see instead?**

`a` is not smartcasted - `error: type Animal has no field or method name`

### PR DESCRIPTION
**Pull request by spaceface777**
it's always great to see negative diffs, that add new functionality :D

Depends on https://github.com/vlang/ui/pull/331

Closes #9061.

### CODE REVIEW

**Comment by medvednikov** [comment]
```
/Users/runner/.vmodules/ui/stack.v:807:10: error: unknown method: `ui.Widget.set_drawing_children`.
9 possibilities: `draw`, `focus`, `init`, `is_focused`, `point_inside`, `propose_size`, `set_pos`, `size`, `unfocus`.
  805 |     for mut child in s.children {
  806 |         if child is Stack {
  807 |             child.set_drawing_children()
      |                   ~~~~~~~~~~~~~~~~~~~~~~
  808 |         }
  809 |         // println("z_index: ${child.type_name()} $child.z_index")
/Users/runner/.vmodules/ui/window.v:935:10: error: unknown method: `ui.Widget.resize`.
Did you mean `size`?
  933 |     for mut child in window.children {
  934 |         if child is Stack {
  935 |             child.resize(width, height)
      |                   ~~~~~~~~~~~~~~~~~~~~~
  936 |         }
  937 |     }
```

**Comment by medvednikov** [comment]
i merged the ui pr

conflict

```
<<<<<<< proper-interface-smartcasts
fn (c Checker) smartcast(expr ast.Expr, cur_type table.Type, to_type_ table.Type, mut scope ast.Scope) {
	sym := c.table.get_type_symbol(cur_type)
	to_type := if sym.kind == .interface_ { to_type_.to_ptr() } else { to_type_ }
	match expr {
=======
fn (c &Checker) smartcast_sumtype(expr ast.Expr, cur_type table.Type, to_type table.Type, mut scope ast.Scope) {
	match mut expr {
>>>>>>> master
```

**Comment by spaceface777** [comment]
every time I fix ui, a different pr gets merged as well, which breaks the build once again :p

**Comment by medvednikov** [comment]
@codex review

**Pull request merged**
