### PR TITLE
test: make 'test-self' pass under msys2/MINGW32

### PR DESCRIPTION
**Pull request by smalltalkman**
This PR make 'test-self' pass under msys2/MINGW32.

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by smalltalkman** [comment]
@spytheman Thank you for your help, I couldn't have done it without your guidance.

**Comment by spytheman** [comment]
Happy to help, when I can 🙇🏻‍♂️ .

**Comment by smalltalkman** [comment]
Thanks!

**Pull request merged**
