### PR TITLE
freebsd: add troubleshooting advice to use gmake instead of make for bootstrapping.

### PR DESCRIPTION
**Pull request by spytheman**
GNU's make is available everywhere.

### CODE REVIEW

**Comment by medvednikov** [comment]
I'd rather make `make` work on freebsd, so that the instructions are the same for all systems.

Will test this on a freebsd VM later.

**Comment by joe-conigliaro** [comment]
There are are a lot of differences between the syntax's. I have a suggestion.
BSD make will first look for a file called `BSDmakefile` and gnu make will first look for a file called `GNUmakefile` before it loads `Makefile`.

So I suggest we either:
1.  call the BSD one `BSDmakefile` and leave the GNU one as `Makefile`
2. call the BSD one `BSDmakefile` and GNU one `GNUmakefile` and have a `Makefile.common` with some common logic and include it from both other makefiles.

**Comment by sunnylcw** [comment]
@joe-conigliaro Your suggestion #2 looks good (Call the BSD one BSDmakefile and leave the GNU one as Makefile)

**Comment by medvednikov** [comment]
Yes, I agree.

**Comment by medvednikov** [comment]
there's now a makefile for freebsd

**Pull request closed without merging**
