### PR TITLE
native: system for defining internal builtin algorithms which are not inlined

### PR DESCRIPTION
**Pull request by Spydr06**
Adding a system for defining internal algorithms which are not inlined, but rather treated like functions.
This is necessary to keep executable sizes small and the generated code clean (especially for debugging). Algorithms like the int-to-string conversion, etc. no longer get duplicated when needed.

### CODE REVIEW

**Comment by medvednikov** [comment]
windows tcc

```
 FAIL  [ 6/61]   313.880 ms cmd/tools/builders/native_builder.v
vlib/v/gen/native/builtins.v:6:8: error: module 'os' is imported but never used
    4 | module native
    5 | 
    6 | import os
      |        ~~
```

**Comment by Spydr06** [comment]
Fixed it

**Comment by medvednikov** [comment]
Great job!

**Comment by Spydr06** [comment]
Thanks :)

**Pull request merged**
