### PR TITLE
parser: Fix parsing with comments

### PR DESCRIPTION
**Pull request by nedpals**
Part of #4900. In progress.

This eliminates all the issues the parser is currently experiencing when parsing V files with comments. Will add tests soon.

So far (Will update):
- [x] Structs
- [x] Enums
- [x] Interfaces
- [x] Consts

### CODE REVIEW

**Comment by medvednikov** [comment]
A monumental task :)

Another way to solve this would be to remember the location of comments, and reinsert them later, not store them in AST nodes. But it's also tricky.

**Comment by nedpals** [comment]
@medvednikov True, it is tricky. I'm thinking of storing them in a separate comments field then the nodes would just store the indices of the comments instead.

**Comment by JalonSolov** [comment]
You need to keep track of 3 locations for comments...

Comments BEFORE a particular node (like the common comment blocks before functions).
Comments at END OF LINE in a particular node.
Comments AFTER a particular node (especially for comments at the end of the file).

This might be easier to keep track of by expanding the AST definitions to include before/eol/after strings, and just shove comments into those.  Putting them all in one array won't preserve the 3 locations.

I would also store comment blocks, like
```
/* multi-line
    comment
    block
*/
```
or
```
// another
// multi-line
// comment
// block
```
as single strings with `\n` embedded as separators.

**Comment by JalonSolov** [comment]
Ok... still learning my way around the code... I see that comments are kept as attributes of the nodes.

The idea of keeping different locations is still valid.  You _could_ keep all comments in one large array, as long as you keep the indices in the nodes separated by location.

Perhaps change the comment array in the nodes to a map, with location relative to the node as the key and index into the big comment array as the value.

The trickiest part of all is if there are multiple eol comments on a single line...
```
_ := []byte{   // eol comment 1
         len: 10  // eol comment 2
         init: 0    // eol comment 3
       }
```

Blank lines could also be handled at parse time instead of waiting for `v fmt` to run... treat a blank line as a comment (or part of one.  If a blank line was just seen, ignore any others until you see a non-blank.  If a blank line is just after a regular comment, treat it as part of the comment.  So
```
// This would be a single comment block

// with the blank line as part of it
```
and
```
// This would be stored as a single block



// with a single blank line in the middle
```

**Comment by nedpals** [comment]
Haven't work on it today. Instead, I researched what other languages did on this. Python does not store comments on the AST and a variety of solutions used for their tools. Go, meanwhile, stores comments on each node (which is what V does on some nodes). Comments are free-forming and is tricky tbh and it hurts my head lol.

**Comment by nedpals** [comment]
@JalonSolov What about introducing a new struct that would store the indices for the `top`, `trailing`, and `bottom` comments on their respective struct fields like this:

```v
struct ConstDecl {
    // const decl fields here
    comments  Comments
}

struct Comments {
    top        []int
    trailing   []int
    bottom  []int
}

**Comment by JalonSolov** [comment]
That'll work as well.  Not sure which way would be faster... probably time to benchmark it.

Basically, any method that helps keep the location of the comments intact, both for `v fmt` rewriting the file, as well as the comments being written into code generated by the backends.

**Comment by spytheman** [comment]
Parsing is slowest, but currently it just skips comments normally in the scanner, so the only overhead that they would cause is in used memory. We can use `comments  &Comments` and just pass 0 in the normal mode, so the cost would be +8 bytes per AST node.

During vfmt/vdoc runs, the comments would have to be initialized, so there will be CPU + Memory overhead per node, but vfmt and vdoc can probably afford it (they do not use the checker, nor do they invoke a C compiler afterwards).

**Comment by JalonSolov** [comment]
Sounds like a good trade-off.

**Comment by nedpals** [comment]
Will close this for now. Discussions are still welcome :smiley:

**Pull request closed without merging**
