### PR TITLE
ast, checker, cgen: change option to result in index and channel (part 1)

### PR DESCRIPTION
**Pull request by yuyi98**
This PR change option to result in index and channel (part 1).

### CODE REVIEW

**Comment by medvednikov** [comment]
Why though? I think an option is enough for indexing. The only possible error is index out of range.

An option is smaller and more performant.

@spytheman what do you think?

**Comment by yuyi98** [comment]
For consistency, range_index is required.

**Comment by spytheman** [comment]
@medvednikov consider this:
```v
mut a := []?int{len: 5}
a[1] = 123
a[3] = 456
dump(a)
```
which produces:
```
[a.v:4] a: [Option(0), Option(123), Option(0), Option(456), Option(0)]
```

What will `a[0]` be?
It should be `none`, but if `a[0]` returns `none` internally for the `index out of range` situation, there is no way to distinguish the two.

If however, it returned an error instead, it will work:
`x := a[9999] or { panic(err) }` will handle the out of range error, while:
`y := x?` will handle the possible `none` value.

**Comment by medvednikov** [comment]
What's the usecase for an array of options? I'd rather ban that than make arrays slower and more complex.

**Comment by yuyi98** [comment]
In index we can distinguish between negative value or larger than the range.

**Comment by medvednikov** [comment]
That's how it works in Rust as well. array.get() returns an Option there:

https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get

**Comment by medvednikov** [comment]
i < 0 or i > len is still the same error: out of bounds

**Comment by spytheman** [comment]
> What's the usecase for an array of options? I'd rather ban that than make arrays slower and more complex.

For example, an array of thread results, where each thread can either produce a value or none.
```v
fn work() ?Something {...}

for { ...
   threads << spawn work()`
}
all := threads.wait()
```

=> `all` will be of type `[]?Something` , where each one could be either Something or `none`.

**Comment by spytheman** [comment]
> make arrays slower 

I was wrong, it is use not for `x := a[i] or { default }` but for strings: `r := s[i] or { default_rune }` .

**Comment by medvednikov** [comment]
Ok, let's allow array of options. But arr[idx] should still return an option.
We have to somehow make your example with `mut a := []?int{len: 5}` work. I wonder how it's done in Rust.

I'm strongly against using Result for this.

**Pull request closed without merging**
