### PR TITLE
builtin, cgen: improve the assert informations (related #22666)

### PR DESCRIPTION
**Pull request by yuyi98**
This PR improve the assert informations  (related #22666).

```v
type Sum = int | string

fn main() {
	assert Sum(1) == Sum(2)
}

PS D:\Test\v\tt1> v run .    
.\\tt1.v:4: FAIL: fn main.main: assert main.Sum(1) == main.Sum(2)
  left value: main.Sum(1)
  right value: main.Sum(2)
V panic: Assertion failed...
v hash: 14b1a14
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.01JB6ZGGR5EPG0CM0FD2MRVCFX.tmp.c:7314: at _v_panic: Backtrace
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.01JB6ZGGR5EPG0CM0FD2MRVCFX.tmp.c:13684: by main__main
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.01JB6ZGGR5EPG0CM0FD2MRVCFX.tmp.c:13721: by wmain
00466ea8 : by ???
0046700b : by ???
7ffe207e259d : by ???
```

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFlMzNjMDI3Y2M3NjgxYzYyMTA1ZTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.u-dQbS_udwiBU2EHiFqDYhFlxS-HQCePpcUBVzKorVQ">Huly&reg;: <b>V_0.6-21117</b></a></sub>

### CODE REVIEW

**Comment by enghitalo** [comment]
Great!!!

**Review by spytheman — APPROVED** [review]
Excellent work.

~~Please add a .vv/.out pair too in `vlib/v/slow_tests/inout/` (include only the system independent part before the panic in the .out file; see `./vlib/v/slow_tests/inout/panic_on_fixed_array_slice.out` for example) and it will be good to merge.~~

The `_test.vv/.run.out` pair is better to be placed in `vlib/v/tests/skip_unused/`, see below.

**Comment by spytheman** [comment]
`vlib/v/tests/skip_unused/assert_of_sumtype_values_works_test.vv` with:
```v
type Sum = int | string

fn test_ab() {
        a,b := Sum(1), Sum(2)
        assert a == b
}

fn test_sumtype_literals() {
        assert Sum(1) == Sum(2)
}
```

can be tested by `vlib/v/tests/skip_unused/assert_of_sumtype_values_works_test.run.out`:
```
vlib/v/tests/skip_unused/assert_of_sumtype_values_works_test.vv:5: fn test_ab
   > assert a == b
     Left value (len: 6): `Sum(1)`
    Right value (len: 6): `Sum(2)`

vlib/v/tests/skip_unused/assert_of_sumtype_values_works_test.vv:9: fn test_sumtype_literals
   > assert main.Sum(1) == main.Sum(2)
     Left value (len: 11): `main.Sum(1)`
    Right value (len: 11): `main.Sum(2)`
    
```

Can we remove the `main.` prefix, so that it is the same as the `test_ab` failure?

**Comment by spytheman** [comment]
I've added the test pair.
You can test locally with `VTEST_ONLY=assert_of_sumtype_values_works VAUTOFIX=1 ./v vlib/v/compiler_errors_test.v`

**Pull request merged**
