### PR TITLE
vlib: add testing functions to show why assert fails

### PR DESCRIPTION
**Pull request by mvlootman**
This PR allows specifying an expected result when writing tests.
When the assert fails it shows the expected value and the actual value.

It leverages the existing assert function by returning a boolean from the new testing functions. Thus not requiring any change to the compiler or other parts of the code.

To fully support asserts on all basic types, the use of generics would be very helpful to use a single function definition, instead of adding functions per datatype. Without generics the biggest issue would not be able to overload the function, which would lead to functions as:
```
pub fn is_i8( expected, actual i8) bool {}
pub fn is_i16( expected, actual i16) bool {}
pub fn is_int( expected, actual int) bool {}
pub fn is_i64( expected, actual i64) bool {}
```
Which would seem a sub-optimal api to use.

That is why this PR only supports `int` and `string` datatypes, as they are used the most often.

Example code:
```
import testing

fn test_sample(){
       assert testing.is(42, calc_func(), 'should calculate answer')
}
```

The output of the included test, shows examples of the asserts.
```
Testing...
-------------------------------------------------
compilation took: 1636ms
running tests in: /home/michiel/v/src/github.com/mvlootman/v/vlib/testing/testing_test.v
   OK     0 ms |  1 assert  | test_is_same_int()
expected: 42
actual  : 12
reason  : should match same int**
   OK     0 ms |  1 assert  | test_is_different_int()
expected: not `42`
actual  : 42
reason  : should not match same int
   OK     0 ms |  1 assert  | test_is_not_same_int()
   OK     0 ms |  1 assert  | test_is_not_different_int()
expected: a
actual  : b
reason  : should match same string
   OK     0 ms |  1 assert  | test_is_different_string()
   OK     0 ms |  1 assert  | test_is_match_on_matched_string()
expected: `wolf` to be in the actual string
actual  : The quick brown fox jumps over the lazy dog
reason  : should match substring
   OK     0 ms |  1 assert  | test_is_match_on_nonmatch_string()
   OK     0 ms |  1 assert  | test_is_not_different_string()
expected: not `a`
actual  : a
reason  : should not match same string
```

### CODE REVIEW

**Comment by medvednikov** [comment]
How about `assert2(42, 40+2, "should add numbers together")`

And simply make V print expected and actual results as per TODO:

```
fn assert_statement() {
 // TODO print "expected:  got" for failed tests
}
```
Your solution adds a new module that depends on generics and offers an alternative way to do asserts.

I think it should all be part of the compiler.

**Comment by mvlootman** [comment]
That would make it a simpler solution, agreed. 
Looking at other languages they have layered the testing framework outside the compiler.
Will this not harm the extensibility in the long run?

**Comment by medvednikov** [comment]
Well, this is one of the decisions I made: testing is part of the language, just like in Go, but even simpler to use.

I think it's such an integral part of development, that it should be inseparable from the language, hence the `assert` keyword. This makes things easier and prevents users from choosing a testing framework and switching between frameworks in different projects/companies.

**Comment by spytheman** [comment]
@medvednikov will assert2 be a separate token, or an extension of the existing assert_statement() implementation, when it detects that it is called with () parameters ?

**Comment by Delta456** [comment]
How about  using `static_assert` (from C++/D) instead of assert2? I find this name more suitable for this case.

**Comment by medvednikov** [comment]
I don't know yet :) @spytheman

**Comment by medvednikov** [comment]
yes `static_assert` is much better than `assert2` :)

**Comment by mvlootman** [comment]
I am closing the PR as this is not the solution going forward.

**Comment by spytheman** [comment]
@Delta456 there is nothing static about the 2 forms of assert. The assert check happens at runtime, while the C++ static_assert happens during compilation, and is thus limited to information known by the compiler, checking constants, sizeof, typeof and so on.

**Comment by spytheman** [comment]
hm, actually the second form of assert will have to check that the types of the first and the second arguments match at compile time, so I am partially wrong that there is nothing static.

**Pull request closed without merging**
