### PR TITLE
all: rollback to old interpolation (step 4)

### PR DESCRIPTION
**Pull request by shove70**
done.  this is the last step.   :)

### CODE REVIEW

**Review by yuyi98 — APPROVED** [review]

**Comment by kahsa** [comment]
Does this mean that all new interpolations are obsolete?
Does it mean that my program that I have rewritten to the new syntax must revert back to the old one?

**Comment by shove70** [comment]
> Does this mean that all new interpolations are obsolete? Does it mean that my program that I have rewritten to the new syntax must revert back to the old one?

yes, kahsa.

**Comment by kahsa** [comment]
ok, thanks

**Comment by spytheman** [comment]
@shove70, @yuyi98 I would like to thank both of you, very, very much, both for the fixes for `{}`, and for the rollback fixes after that.

**Comment by shove70** [comment]
> I would like to thank both of you, very, very much, both for the fixes for `{}`, and for the rollback fixes after that.

You're welcome!  ❤️

**Comment by Wajinn** [comment]
> Does this mean that all new interpolations are obsolete? ...
> 
> yes...

Thank you, and you do a great job in general.  By the way, much preferred using ${var}, which worked very well and was distinctive.

**Pull request merged**
