### PR TITLE
orm: fix subquery without where expr

### LINKED ISSUE #21595: ORM select compile-time panic with deep relationships
**V doctor:**
```
V full version: V 0.4.6 ed7f1ff.a601653
OS: macos, macOS, 14.5, 23F79
Processor: 11 cpus, 64bit, little endian, Apple M3 Pro

vexe mtime: 2024-05-29 14:38:51

VTMP: OK, value: /tmp/v_501

Git version: git version 2.39.3 (Apple Git-146)
Git vroot status: weekly.2024.22-6-ga6016530 (1 commit(s) behind V master)
.git/config present: true

CC version: Apple clang version 15.0.0 (clang-1500.3.9.4)
thirdparty/tcc status: thirdparty-macos-arm64 5c1d002f

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg deep_orm_select.v`
```v
import db.sqlite

struct Parent {
	id int @[primary; sql: serial]
	name string
	children []Child @[fkey: 'parent_id']
}

struct Child {
	id int @[primary; sql: serial]
	name string
	parent_id int
	babies []Baby @[fkey: 'child_id']
}

struct Baby {
	id int @[primary; sql: serial]
	name string
	child_id int
}

fn main() {
	db := sqlite.connect(':memory:')!

	sql db {
		create table Parent
		create table Child
		create table Baby
	} or { panic(err) }

	new_parent := Parent{
		name: 'first parent',
		children: [
			Child{ name: 'first child' },
			Child{ name: 'second_child' }
		]
	}

	sql db {
		insert new_parent into Parent
	} or { panic(err) }

	babies := [
		Baby{name: 'first baby', child_id: 1},
		Baby{name: 'second baby', child_id: 1},
		Baby{name: 'third baby', child_id: 2},
		Baby{name: 'fourth baby', child_id: 2},
		Baby{name: 'fifth baby', child_id: 2},
	]

	for v in babies {
		sql db {
			insert v into Baby
		} or { panic(err) }
	}

	// from my testing the following query causes the panic
	parent := sql db {
		select from Parent
	} or { panic(err) }

	println(parent)
}
```

**What did you expect to see?**

The program to compile and run successfully.

**What did you see instead?**
```
================ V panic ================
   module: builtin
 function: __as_cast()
  message: as cast: cannot cast `unknown` to `v.ast.InfixExpr`
     file: /v/vlib/builtin/builtin.v:39
   v hash: a601653
=========================================
0   vdbg                                0x00000001001c8a0c __as_cast + 648
1   vdbg                                0x000000010049e3ec v__gen__c__Gen_write_orm_select + 14736
2   vdbg                                0x000000010049e800 v__gen__c__Gen_write_orm_select + 15780
3   vdbg                                0x000000010044d038 v__gen__c__Gen_sql_select_expr + 400
4   vdbg                                0x00000001003b5898 v__gen__c__Gen_expr + 10764
5   vdbg                                0x00000001003d17dc v__gen__c__Gen_assign_stmt + 22492
6   vdbg                                0x0000000100412ca8 v__gen__c__Gen_stmt + 452
7   vdbg                                0x00000001004126e8 v__gen__c__Gen_stmts_with_tmp_var + 3504
8   vdbg                                0x00000001003ca95c v__gen__c__Gen_stmts + 88
9   vdbg                                0x000000010046a034 v__gen__c__Gen_gen_fn_decl + 16452
10  vdbg                                0x000000010041d8b4 v__gen__c__Gen_fn_decl + 2496
11  vdbg                                0x000000010041334c v__gen__c__Gen_stmt + 2152
12  vdbg                                0x00000001004126e8 v__gen__c__Gen_stmts_with_tmp_var + 3504
13  vdbg                                0x00000001003ca95c v__gen__c__Gen_stmts + 88
14  vdbg                                0x00000001003fc060 v__gen__c__Gen_gen_file + 380
15  vdbg                                0x00000001003fbba8 v__gen__c__cgen_process_one_file_cb + 5324
16  vdbg                                0x0000000100246e8c sync__pool__process_in_thread + 152
17  vdbg                                0x00000001001aeec8 sync__pool__process_in_thread_thread_wrapper + 44
18  libsystem_pthread.dylib             0x000000019c7def94 _pthread_start + 136
19  libsystem_pthread.dylib             0x000000019c7d9d34 thread_start + 8
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

### PR DESCRIPTION
**Pull request by felipensp**
Fix #21595

### CODE REVIEW

**Comment by juan-db** [comment]
I think there's a bigger problem here. At some point deep select was implemented so `select` statements will automatically retrieve children as well, but as soon as you have a deeper nested relationship, you would get the panic from the original issue. I think the ORM feature needs a way for you to explicitly load children.

**Comment by spytheman** [comment]
> I think there's a bigger problem here. At some point deep select was implemented so `select` statements will automatically retrieve children as well, but as soon as you have a deeper nested relationship, you would get the panic from the original issue. I think the ORM feature needs a way for you to explicitly load children.

Please file a separate issue for that, with an example.

The PR afaik works as it is, the changes in it seem logical to me, and it does fix the problem described in your original issue. The only thing it lacks to no longer be a draft, is a test to prevent silent regressions in the future.

**Comment by juan-db** [comment]
My main concern is the `where_expr` field actually does have a value (`id ==`), it's just not a valid value. This likely points to a logic error somewhere.

**Comment by juan-db** [comment]
I've created a new issue so I'm happy with having this PR merged when ready.

**Comment by medvednikov** [comment]
Merged, thanks.

**Pull request merged**
