### PR TITLE
encoding.csv: allow passing a custom delimiter to the `new_reader` function

### LINKED ISSUE #13905: Read file with delimiter
Hi,
The following post explains how to read a csv file:
https://stackoverflow.com/questions/64726760/reading-all-csv-lines
Is there an easy way to read a delimited file? i.e. same as csv but instead of `,` using a different delimiter? I was able to change the source code of reader.v to do it. I was wondering if there is an easier way without breaking change to the source code?
I was also thinking that the example on stackoverflow could be added to your examples folder.
Thank you

### PR DESCRIPTION
**Pull request by StunxFS**
closes #13905

### CODE REVIEW

**Comment by StunxFS** [comment]
CI fails by check-md, I don't know why

**Comment by JalonSolov** [comment]
Current failure is `vlib/encoding/csv/reader_test.v:33:42: error: type `encoding.csv.ReaderConfig` is private`

**Comment by changrui** [comment]
May we read csv file to a struct, automatic check `header` or `title`, field type, etc., like R, Pandas? thx.

**Comment by spytheman** [comment]
> May we read csv file to a struct, automatic check `header` or `title`, field type, etc., like R, Pandas? thx.

Please, make a new feature request. This is out of scope for this PR imho.

**Comment by spytheman** [comment]
@StunxFS given these:
`pub fn new_custom_reader(config ReaderConfig) &Reader {`
and 
`pub fn new_reader(data string) &Reader {`

I think that we can simplify it, by merging them:
`pub fn new_reader(data string, config ReaderConfig) &Reader {`

AFAIK there is no use of doing `a := csv.new_reader()`, i.e. data is *always* required.

**Comment by StunxFS** [comment]
I thought `[params]` would work with a private struct.

@spytheman good idea, I have already implemented it

**Pull request merged**
