### PR TITLE
doc: fix up-to-date optional

### PR DESCRIPTION
**Pull request by kahsa**
This section needs to be up-to-date.
I don't have any idea what to write, anyone please.

### CODE REVIEW

**Comment by JalonSolov** [comment]
@spytheman or someone really familiar with it will update that section once the compiler is ready.  It is useless to make this change in the meantime, since the older method still works.

**Comment by kahsa** [comment]
> It is useless to make this change in the meantime, since the older method still works.

Oh, boy, you are nonsense.
This strike-through line gives the reader the impression that, hey, what's that? What do you mean? The strikeout line makes the reader think, "What is that? It prepares the user for a change in the confirmed specification.
If you cannot understand the significance of this, you are a nonsense person.
And it closes self-righteously. How self-righteous. @JalonSolov

**Comment by kahsa** [comment]
Since you are the one who understands English, you should document that this specification is changing and is in the process of changing and therefore if you write code believing this document, you will be forced to change his code it in the near future. @JalonSolov

**Comment by kahsa** [comment]
The compiler can still handle this for now, but the change in specification is already finalized.
This kind of document should explain the living specification, not just the status of the unfinished compiler.
It should describe both the specification and the current state of the compiler.
That is the documentation that contributes to the reader. @JalonSolov

**Comment by kahsa** [comment]
Hence, if you are dissatisfied with my work, don't just close, do the work yourself. I expect it. @JalonSolov

**Comment by kahsa** [comment]
If you don't want the job, you should discuss it with them before closing. @JalonSolov

**Comment by JalonSolov** [comment]
<sigh>  Believe what you will about me.  You will anyway.

The doc is currently correct.  Yes, it will change, and so will the documentation.

Marking through that single line just makes people wonder, since the example will still show the "old" way of doing things.  The entire section needs to be changed, with 2 examples instead of one, and it needs to be changed correctly.

**Comment by kahsa** [comment]
> Marking through that single line just makes people wonder, since the example will still show the "old" way of doing things.

Yes, so I asked someone edit and add appropriate comment in right English to this PR.
I think you are the one who can do that.

**Comment by kahsa** [comment]
At the very least, it would be negligent to leave a text recommending something different from the currently clearly established specifications without annotating it, even though we are aware of its existence. @JalonSolov

**Comment by kahsa** [comment]
As you can see, this PR accepts editing by the committer.
So I was asking for it.
You were in a position to do so, but failed to do so, and simply closed it and did not do any work.
Owners who give money and mouth but don't do the work will be disliked wherever they go. @JalonSolov

**Pull request closed without merging**
