### PR TITLE
Add thirdparty cjson

### LINKED ISSUE #369: json module still has a bug
this code will raise "You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."
```
import json

println('ok')
```
the code from the example doesn't work:
```
import json

struct User {
	name string
	age  int
}

data := '{ "name": "Frodo", "age": 25 }'

user := json.decode(User, data) or {
	eprintln('Failed to decode json')
	return
}
println(user.name)
println(user.age)
```
looks like `str()` has been removed?

### PR DESCRIPTION
**Pull request by musou1500**
closes #369 #406 

**This PR doesn't includes windows support.**
I don't have windows env, so I can't test it....

currently, `json` module depends on cJSON library.
to make it easy for developers to build, this PR add `cJSON` to this repository as git submodule.
In the future, JSON parser will be written by vlang.
but until then, it is better to keep add third-party libraries to `thirdparty` dir.

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks!

**Comment by musou1500** [comment]
@medvednikov BTW, would you have your `glad` files?
I can create PR that adds `stb` and `glad` files to `thirdparty` dir, if needed.

**Comment by kcorey** [comment]
Going by the answer here:
https://stackoverflow.com/questions/45492937/glad-glad-h-no-such-file-or-directory

Isn't glad.h dependent upon the version of opengl that you're compiling against on your system?

In other words, if we import glad into the build tree, we lock v to a particular version of opengl.

**Comment by kcorey** [comment]
Hrm...I'm a numpty here.  I must be doing something wrong (not played with submodule before).

After a "git pull -r origin master" to rebase my branch on top of thelatest merges, I see a thirdparty directory, and an empty cJSON under it.

So, I tried 
    git submodule update --init --recursive

...but cJSON is still empty.

Hrm...okay, 
    cd ~/code/v/thirdparty
    git clone git@github.com:DaveGamble/cJSON.git
    cd cJSON
    cmake

...then recompile v.

    cd ../examples
    vc news_fetcher.v
clang: error: no such file or directory: 'mac'
V panic: clang error

Any ideas?

**Comment by musou1500** [comment]
@kcorey can you post output of `ls ./thirdparty/cJSON`?
git does not clones submodule by default(`--recursive` option does it).

**Comment by bitsnaps** [comment]
@musou1500 now it gives `V panic: clang error` on a Mac.

**Comment by musou1500** [comment]
@bitsnaps 
> tried --recursive gives a git error
I tried to clone, but I could not reproduce.
can you post git error and entire error of `V panic: clang error`?

**Comment by bitsnaps** [comment]
@musou1500 fixed, the dir `cJSON`was already there, after fix typo `thirdparty` module `json` is detected & compiled without error, but the simple json/User demo doesn't show any output.

**Comment by bitsnaps** [comment]
> @musou1500 fixed, the dir `cJSON`was already there, after fix typo `thirdparty` module `json` is detected & compiled without error, but the simple json/User demo doesn't compile it throws `expected type 'string', but got 'void'`

Fixed, creating a `main()` solve the issue, full source:
```
import json

struct User {
	name string
	age  int
}

fn main(){
  data := '{ "name": "Frodo", "age": 25 }'

  user := json.decode(User, data) or {
  	eprintln('Failed to decode json')
  	return
  }
  println(user.name)
  println(user.age)
}
```

**Pull request merged**
