### PR TITLE
 builtin: support for Cyrillic characters in string functions

### PR DESCRIPTION
**Pull request by hedgeg0d**
fix of #21878

### CODE REVIEW

**Comment by Delta456** [comment]
Run `v fmt -w vlib/builtin/string.v`

**Comment by hedgeg0d** [comment]
> Run `v fmt -w vlib/builtin/string.v`

it is already done. 
Output of the command:
```Already formatted file: /home/hedgegod/v/vlib/builtin/string.v```

**Comment by Delta456** [comment]
My bad you need to run `v fmt -w vlib/builtin/string_test.v`

**Comment by JalonSolov** [comment]
Simplest is usually to cd to the dir with changes, and run `v fmt -w .` to get them all at the same time.

**Comment by hedgeg0d** [comment]
> You can also save time by installing the git hook that will check this before you can commit changes. To do this, from the root of your V install dir,
> 
> `cp cmd/tools/git_pre_commit_hook.vsh .git/hooks/pre-commit`
> 
> (documented in CONTRIBUTING.md)

Thanks for the advice. I'm new to contributions.

**Comment by Delta456** [comment]
As per the CI https://github.com/vlang/v/actions/runs/9959619762/job/27516879064?pr=21883

You would need to rebase to the latest commit so that the actions pass.

**Comment by hedgeg0d** [comment]
> As per the CI https://github.com/vlang/v/actions/runs/9959619762/job/27516879064?pr=21883
> 
> You would need to rebase to the latest commit so that the actions pass.

Sorry, i do not understand. Isn't it already on last commit? When i do 
```git pull```
it says
```Already up to date```
and 
```git rebase master```
```Current branch master is up to date.```

**Comment by spytheman** [comment]
I am not sure that supporting additional alphabets in the builtin methods is a good idea, since it is introducing a lot of complexity/edge cases, and will not stop at just Cyrillic.

Turkey (which is now officially `Türkiye` since May 2022) for example, has different capitalization rules - `TÜRKİYE`, not `TÜRKIYE`, and thus, unless you know the context/locale, you can not write a generic capitalization method, that will produce valid output, for both English and Turkish.

In my personal opinion, it will be significantly less complex, to just document, that certain methods work only for English, and to have a separate module, that is dedicated to processing utf/unicode, and that is sensitive to the locale (perhaps passed as a parameter), so that programs that want all that complexity, can import it.

**Comment by hedgeg0d** [comment]
Okay, I agree with you. I just needed this functionality, so I rewrote the built-in functions and thought maybe someone else needed it too.

**Comment by medvednikov** [comment]
vlib, not builtin

**Pull request closed without merging**
