### PR TITLE
ast, checker: move check_types()... from checker to ast

### PR DESCRIPTION
**Pull request by yuyi98**
This PR move `check_types()` `check_expected_call_arg()`... from checker to ast.

- In order to use check_expected_call_arg() in cgen for checking comptime method call.

### CODE REVIEW

**Comment by medvednikov** [comment]
Is it absolutely not possible to check the comptime method call in the checker?

**Comment by yuyi98** [comment]
Because there are no method's specific types in the checker phase.

**Comment by medvednikov** [comment]
@yuyi98 is it possible to generate this data in the checker phase?

**Comment by yuyi98** [comment]
Theoretically, this can be handled in the Checker.
I see, I'll try to resolve it in checker.

**Pull request closed without merging**
