### PR TITLE
vweb: add json_raw

### PR DESCRIPTION
**Pull request by esquerbatua**
Add json_raw to prevent encode an encoded body content of response

### CODE REVIEW

**Comment by esquerbatua** [comment]
mmm strange
image

**Comment by JalonSolov** [comment]
`vweb` is deprecated now.  Properly deprecated.  Should we be making changes to it?

**Comment by esquerbatua** [comment]
> no, only veb

maybe then we sould create a run version of veb with multithreading?

**Comment by medvednikov** [comment]
what do you mean? veb is built on top of picoev, it's parallel

**Pull request closed without merging**
