### PR TITLE
doc: Add more subheadings & tweaks

### PR DESCRIPTION
**Pull request by ntrel**
* Add subheadings in Functions, Variables and Structs sections for easier browsing/linking.
 * Add heading 'Symbol visibility'.
 * Remove 'Primitive types' from table of contents (to keep it short, and the Types link is good enough).
 * Remove 'no global state' as there is `__global var`.
 * Tweak variable errors example.
 * Add 2 links.
 * Clarify that the operator appendix is for primitive types.

### CODE REVIEW

**Comment by medvednikov** [comment]
Conflict

**Comment by ntrel** [comment]
@medvednikov thanks, rebased

**Comment by medvednikov** [comment]
Globals are not enabled by default, only with --enable-globals, and should only be used for low level programming only when absolutely needed. So I wouldn't remove "no global state", but made this clear.

**Comment by ntrel** [comment]
@medvednikov I've put 'no global state' back and added a link to 'pure by default' where it mentions `--enable-globals`. I also mentioned there that I/O is allowed.

Even with a compiler flag, that is still global state. vlib also uses `__global` variables, so they're not just for drivers and kernels.

**Comment by JalonSolov** [comment]
V only uses __globals when necessary for C interop.

**Comment by ntrel** [comment]
@JalonSolov are all these for C interop?:
```
vlib/builtin/builtin.v:6:__global g_m2_buf byteptr
vlib/builtin/builtin.v:7:__global g_m2_ptr byteptr
vlib/builtin/builtin.v:128:__global total_m i64=0
vlib/builtin/builtin.v:129:__global nr_mallocs int=0
vlib/builtin/string.v:1010:__global g_ustring_runes []int
```

**Comment by medvednikov** [comment]
__global is allowed in `builtin`, doesn't really change things for the end user.

**Comment by ntrel** [comment]
> I've put 'no global state' back and added a link to 'pure by default' where it mentions --enable-globals. I also mentioned there that I/O is allowed.

Is this OK? Would you like any other changes?

**Comment by medvednikov** [comment]
Yeah, looks good. I'll merge right away after the conflict is resolved.

**Comment by ntrel** [comment]
Fixed conflicts.

**Pull request merged**
