### PR TITLE
native, markused: implement `-skip-unused`

### PR DESCRIPTION
**Pull request by Spydr06**
As @spytheman demonstrated in the `#native-backend` discord channel.
This is another PR to get #17782 eventually working.

### <samp>🤖 Generated by Copilot at fcf710a</samp>

This pull request adds the `-skip-unused` flag for the native backend, which allows skipping the generation of unused functions and improves the compilation speed and binary size. It modifies the `vlib/v/gen/native/gen.v` file to implement the flag, the `vlib/v/gen/native/tests/native_test.v` file to enable the flag for testing, and the `vlib/v/markused/markused.v` file to mark only the `main.main` function as required for the native backend.

### <samp>🤖 Generated by Copilot at fcf710a</samp>

* Implement the `-skip-unused` flag for the native backend, which reduces the executable size by omitting unused functions ([link](https://github.com/vlang/v/pull/18036/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R948-R956), [link](https://github.com/vlang/v/pull/18036/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5L954-R966), [link](https://github.com/vlang/v/pull/18036/files?diff=unified&w=0#diff-d2049b86cdecb6214a965112ae97fe89d029d645e39cf9847f250e91c92e0187L17-R133))
  - Add a new method `is_used_by_main` to the `Gen` struct, which checks if a function declaration node is used by the main function ([link](https://github.com/vlang/v/pull/18036/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R948-R956))
  - Modify the `gen_fn_decl` method of the `Gen` struct, which generates the code for a function declaration, to skip the generation of unused or bodyless functions and print a verbose message ([link](https://github.com/vlang/v/pull/18036/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5L954-R966))
  - Modify the `mark_used` function in the `markused.v` file, which marks the functions that are used by the main function or are required by the backend, to only mark the `main.main` function as required for the native backend ([link](https://github.com/vlang/v/pull/18036/files?diff=unified&w=0#diff-d2049b86cdecb6214a965112ae97fe89d029d645e39cf9847f250e91c92e0187L17-R133))
* Modify the `test_native` function in the `native_test.v` file, which runs the tests for the native backend, to add the `-skip-unused` flag to the compilation command ([link](https://github.com/vlang/v/pull/18036/files?diff=unified&w=0#diff-2e8a09fc3b5271c41e2ab67cb69ad7f1d6d893a273acee9e8827285c868a2fb0L43-R43))

### CODE REVIEW

**Comment by Spydr06** [comment]
On a side note, I must say this new copilot feature is very helpful

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by Spydr06** [comment]
When enabling the builtin module (see #17782), it still tries to compile some unused builtin functions, which obviously fail to compile:
image

**Comment by Spydr06** [comment]
You can merge it, I'll fix that issue another time.

**Pull request merged**
