### PR TITLE
examples: term.ui - add pong clone

### PR DESCRIPTION
**Pull request by Larpon**
This will add "VONG" (a V pong clone) to the `term.ui` examples.
It features a notoriously evil and invincible AI named Victoria.

### CODE REVIEW

**Comment by medvednikov** [comment]
oops, forgot to ask you to add a screenshot to examples/term.ui/readme.md

**Comment by medvednikov** [comment]
you can see how it's done in tetris

**Comment by Larpon** [comment]
@medvednikov - oops - I'll have a look

**Comment by Larpon** [comment]
@medvednikov - https://github.com/vlang/v/pull/6858 :+1:

**Pull request merged**
