### PR TITLE
gen: change `typ()` to `type_name()`

### PR DESCRIPTION
**Pull request by yuyi98**
This PR change `typ()` to `type_name()`.

- The meaning of `typ()` is not clear.
- Change `cgen.typ()` to `cgen.type_name()`.
- Change `jsgen.typ()` to `jsgen.type_name()`.

### CODE REVIEW

**Comment by medvednikov** [comment]
The convention in V, like in Go, is to use `typ` instead of `type`, which is a keyword.

**Comment by yuyi98** [comment]
@medvednikov  Sorry, The `typ` here is not a variable name, it's a function. It is used to convert types to names, so I think use `type_name` is better.

**Comment by medvednikov** [comment]
But it's not type name. It adds * etc.

The function's goal is to handle a type and generate necessary C code, so `g.typ()` is ok.

**Comment by yuyi98** [comment]
@yuyi98  Thanks for your patience, I see and I'll close it.

**Pull request closed without merging**
