### PR TITLE
cgen: rewrite the closure implementation

### PR DESCRIPTION
**Pull request by spaceface777**
Among other things, this PR adds support for Windows,  x86, and improves support for arm and arm64.

### CODE REVIEW

**Comment by penguindark** [comment]
Great job man!

**Comment by medvednikov** [comment]
```
FAIL  [135/970] 18141.693 ms vlib/net/tcp_test.v
/tmp/v/test_session_104834886212/tcp_test.15887222398374793199.tmp.c:26975:43: runtime error: member access within null pointer of type 'net__Addr' (aka 'struct net__Addr')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /tmp/v/test_session_104834886212/tcp_test.15887222398374793199.tmp.c:26975:43 in 

>>> test_tcp_ip6
[/home/runner/work/v/v/vlib/net/tcp_test.v:56] l: &net.TcpListener{
```

**Comment by spytheman** [comment]
> FAIL  [135/970] 18141.693 ms vlib/net/tcp_test.v
> /tmp/v/test_session_104834886212/tcp_test.15887222398374793199.tmp.c:26975:43: runtime error: member access within null pointer of type 'net__Addr' (aka 'struct net__Addr')
> SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /tmp/v/test_session_104834886212/tcp_test.15887222398374793199.tmp.c:26975:43 in 
> 
> >>> test_tcp_ip6
> [/home/runner/work/v/v/vlib/net/tcp_test.v:56] l: &net.TcpListener{


The failures were not related; it was just GitHub actions being flaky.

**Comment by dumblob** [comment]
For those interested in **underlying implementations** of closures, coroutines, and continuations, feel free to read [how C++20 does **not** well in this regard](https://probablydance.com/2021/10/31/c-coroutines-do-not-spark-joy/ ).

I did not compare it to *V*'s design (yet), but feel free to do it and come back here with your findings :wink:.

**Pull request merged**
