### PR TITLE
String：text2 := '8'.repeat(2) + '*'.repeat(2)

### PR DESCRIPTION
**Pull request by lcddh**

### CODE REVIEW

**Comment by Delta456** [comment]
How about using `*` for strings instead?

**Comment by lcddh** [comment]
I don't understand what you mean.

**Comment by medvednikov** [comment]
Please fix indentation. Use tabs.

**Comment by Delta456** [comment]
> I don't understand what you mean.

I mean to use `*` operator instead of `repeat()` method for strings. 
```v
	text2 := '8'*(2) + '*'*(2) 
	assert text2 == '88**
```

**Comment by medvednikov** [comment]
No need, that's another rule to remember and make the language more complex.

**Comment by medvednikov** [comment]
Besides, in V operators must have the same type on both sides.

**Comment by lcddh** [comment]
but if it is other func like reverse()

**Comment by medvednikov** [comment]
@lcddh indentation is still off. Use tabs, not spaces.

**Pull request closed without merging**
