### PR TITLE
compress: support system miniz library through pkgconfig

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by spytheman** [comment]
What systems have it, and what versions? It is not there for Ubuntu 20.04 for example, `apt-file search miniz.pc` does not find anything.

Compiling it from thirdparty/ unconditionally, has the advantage that the produced executable is more portable. 

The disadvantages are that compilation will be slightly slower (always including thirdparty/zip/miniz.h, which is ~388KB, but many of those are comments, so they are skipped quickly by the C compilers), and the executable produced by V, may be larger, compared to an executable, that just links to a system provided miniz library, but the overhead is small: + ~20KB for something that does `import compress`.

**Comment by davidebeatrici** [comment]
I understand the advantage in a more portable executable, but I believe dynamic dependencies should be the default, eventually adding an option such as `-static` or `-bundle_deps` for a static build.

As for the package availability, it's kind of limited right now: https://pkgs.org/search/?q=miniz.h

I believe the reason is that https://github.com/zlib-ng/minizip-ng kind of overshadowed https://github.com/richgel999/miniz.

**Comment by medvednikov** [comment]
Having no dependencies is better for deploying Linux binaries.

**Comment by davidebeatrici** [comment]
The problem is that bundling dependencies is a disadvantage when it comes to security and fixes in general.

But I can see why you want that to be the default behavior: users expect the binary to just work when copying it to a different system.

What do you think about adding an option such as `-dynamic` or `-dyn_deps`?

**Pull request closed without merging**
