### PR TITLE
checker: disallow array with void type

### LINKED ISSUE #6394: _ in an if statement causes "C error.  This should never happen
**V version: V 0.1.29 e2e6831** 
**OS: NixOS 21.03pre243436.2147c3c34bb (Okapi)** 

**What did you do?**
Minimal case:
```
fn main() {
  x := [2,4]
  if x == [_,_] {
    print("match")
  }
}
```

**What did you expect to see?**
I was expecting _ to work as a wildcard in a match.  I'm guessing that isn't a usage of _ in V, so a syntax error chiding me appropriately.

 
**What did you see instead?**
```
v hello.v
==================
/run/user/1000/v/hello.tmp.c: In function ‘main__main’:
/run/user/1000/v/hello.tmp.c:7874:73: error: declaration of type name as array of voids
 7874 |  if (int_arr_eq(x, new_array_from_c_array(2, 2, sizeof(void), _MOV((void[2]){_, _})))) {
      |                                                                         ^
/run/user/1000/v/hello.tmp.c:7874:78: error: ‘_’ undeclared (first use in this function)
 7874 |  if (int_arr_eq(x, new_array_from_c_array(2, 2, sizeof(void), _MOV((void[2]){_, _})))) {
      |                                                                              ^
/run/user/1000/v/hello.tmp.c:7874:78: note: each undeclared identifier is reported only once for each function it appears in
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### PR DESCRIPTION
**Pull request by Noctember**
Fixes #6394

### CODE REVIEW

**Comment by Gladear** [comment]
I'm not sure this is the correct way to handle that 🤔
The problem here is that you use an identifier for a variable that doesn't exist (and never will, as this is the "blank identifier")

**Comment by Gladear** [comment]
Moreover, void type is generally used when there was a problem recognising the type of an expression earlier, so it could lead to weird errors.

**Comment by AqilCont** [comment]
TBH, I would honestly like it as a wildcard in some places too... It would be some cool synaptic sugar for checking if the array is in a specific interface or not :P

**Comment by Gladear** [comment]
Can you give an example were it would be handy ?
In the issue, if I understand the intention correctly, the `if` statement could be replaced by `if x.len == 2 { }`.

**Comment by Delta456** [comment]
@AqilCont V tries to be simple so we should try to avoid `wildcards` as it can be very complicated.

**Comment by AqilCont** [comment]
Yea true. I was thinking it could be used someplace like this:
```v
if token == [_, 200, _, _, .success] {} // Used more as a matching mechanism(like regex for strings).

// Maybe could even be implemented in a match expression.
match token {
    [200, _, _, _, .success] { print("yay it worked") }
}
```
Maybe it could make code a bit easier to read too?

**Comment by Noctember** [comment]
This PR is not about whether or not V should have wildcards. Feel free to make a feature request. 🙂  

The way I see your exemple @AqilCont  is like rust tuples where you can match tuples by one or more of it's items

**Comment by AqilCont** [comment]
@Noctember sorry! I was just elaborating on something. I will continue somewhere else if I feel strongly about this.
Also, it probably is, but I haven't had too much time with compiled languages in general so I don't completely know. I think it wouldn't take away from V so I just brought it up as an addition :D

**Comment by medvednikov** [comment]
Fixed in https://github.com/vlang/v/pull/6412

**Pull request closed without merging**
