### PR TITLE
implements get_line & get_raw_line for windows + REPL

### PR DESCRIPTION
**Pull request by joe-conigliaro**
This PR Implements get_line & get_raw_line for windows
get_line was also simplified to use the output from get_raw_line
it also allows the REPL to work on windows (removed condition with panic)

### CODE REVIEW

**Comment by vitalyster** [comment]
`fgets` on windows will return string in OEM charset in compatibility with MSDOS/Windows 9x and should be avoided at any cost. `ReadConsole` and other NT Console API should be used there

**Comment by joe-conigliaro** [comment]
thanks for the info @vitalyster I will update the PR

**Comment by vitalyster** [comment]
When UNICODE mode is not defined ReadConsole will still read in ANSI/OEM charset and loose/break non-latin characters outside of current "non-unicode apps" locale. In UNICODE mode it will return wide string (utf16) which needs to be converted into utf8. See my [PR](https://github.com/vlang/vc/pull/3/commits/2e31846d34e2f924ae019232735af15fc29eb794#diff-690243d4eae37a6f89ff1d8a24e53469R15294) for example. I'm not sure where this encoding/decoding functions should live but they should be used each time V call Win32 API functions

**Comment by joe-conigliaro** [comment]
@vitalyster once your commit is merged this can be changed to ReadConsoleW and use your decode function

**Comment by joe-conigliaro** [comment]
@vitalyster I think maybe all encoding/decoding stuff should live in vlib/encoding even base64/json etc should get moved in there.

**Comment by medvednikov** [comment]
Thanks!

**Pull request merged**
