### PR TITLE
test: more fancy output

### PR DESCRIPTION
**Pull request by danieldaeschle**
Currently:
image

Todo:
- [ ] merge both file paths
- [ ] bullet point before test function.

### CODE REVIEW

**Comment by JalonSolov** [comment]
I'm not a fan of this.  I am all for the different colors when possible, but there's no real need to have the values on separate lines.  Too much "clutter".

**Comment by danieldaeschle** [comment]
> I'm not a fan of this. I am all for the different colors when possible, but there's no real need to have the values on separate lines. Too much "clutter".

you can give me an example for a better layout.

In this case it's really good to have it in multiple lines:
image

**Comment by danieldaeschle** [comment]
@spytheman at the end of a test run there are 3 empty lines. where are they from?
image

**Comment by danieldaeschle** [comment]
image
current result

**Comment by spytheman** [comment]
`✗ test_abc2 (x_test.v:10)`
^ that looks nice, but makes it hard for IDEs to jump to the next error. 
For that to work by default, you should use the path:line: format (note the second `:` after the line), and that should be at the start of a line, not in the middle, otherwise the prefix will be interpreted as part of the path.

**Comment by spytheman** [comment]
Current look:
image

**Comment by danieldaeschle** [comment]
i'm ok with it. but "Tests took" is a weird term.

**Comment by JalonSolov** [comment]
It's just a short form of a common English idiom.  Similar to "My flight took 2 hours."

Computers should be terse for this type of output.  Pack as much information as clearly as possible into a small amount of space... just because you don't really want to read something the size of "War and Peace" for an error message.  :-\

**Comment by JalonSolov** [comment]
> 
> 
> > I'm not a fan of this. I am all for the different colors when possible, but there's no real need to have the values on separate lines. Too much "clutter".
> 
> you can give me an example for a better layout.
> 
> In this case it's really good to have it in multiple lines:
> image

And it's 2 lines shorter if you start the highlighted lines on the same lines as the `Left value` and `Right value` lines.  Messages _that_ long will never look good, no matter what you do.

**Comment by spytheman** [comment]
How about `Runtime: xyz ms.` ?

**Comment by JalonSolov** [comment]
`Tests took` works fine, but `Runtime` might be more palatable to more people. <shrug>

**Comment by medvednikov** [comment]
Tests took is fine.

**Pull request merged**
