### PR TITLE
time: use linux high-precision timers on Android as well

### PR DESCRIPTION
**Pull request by spaceface777**
~~Depends on #6473.~~

### CODE REVIEW

**Comment by fantassin** [comment]
This PR breaks the solaris build;

V self compiling ...
cannot compile to `/root/v`:
redefinition of function `time.linux_now`
/root/v/vlib/time/time_nix.c.v:71:
/root/v/vlib/time/time_solaris.c.v:30:

**Comment by fantassin** [comment]
Actually, why do we have functions like linux_now(), win_now()...etc, visible to all platforms?

**Comment by spaceface777** [comment]
Ahh! Sorry about that, I should've realized and fixed that. Not having a *BSD / solaris CI makes catching this more difficult. :confused:
I'll open another PR to fix it asap.

> Actually, why do we have functions like linux_now(), darwin_now()...etc, visible to all platforms?

That is a good question, and I don't have an answer myself.

**Comment by fantassin** [comment]
@spaceface777 Thanks!

@helto4real @spytheman Please see my question above. It is bizarre to have public dummy functions in the standard library. What is the reason for that?

**Comment by JalonSolov** [comment]
Likely just a matter of someone having the time to refactor the code into
```v
$if darwin {
    // do darwin specific now()
}
$if linux {
    // do linux specific now()
}
```
etc.

**Pull request merged**
