### PR TITLE
doc: update trim_doc_node_description, make module readmes more uniform

### PR DESCRIPTION
**Pull request by ttytm**
The PR updates `trim_doc_node_description` to generate descriptions that are more helpful to users. On current modules.vlang.io it is often just `## Description` for modules.

<details>
<summary><kbd>Visual Preview</kbd></summary>

- Current (typing in a module name like `builtin` or `crypto`)
  doc-before
- Suggested
  doc-after

</details>

In this context, some simple updates are also made to module readmes, e.g. to make the use of semicolons and line breaks uniform.

<details>
<summary><kbd>Examples of inconsistencies at current master</kbd></summary>

https://github.com/vlang/v/blob/101b8a6b1437344883a61759f499b27d1894b8e7/vlib/toml/README.md?plain=1#L1-L7

https://github.com/vlang/v/blob/101b8a6b1437344883a61759f499b27d1894b8e7/vlib/v/token/README.md?plain=1#L1-L7

</details>

View locally:
```sh
v doc -m -f html vlib
```
Open `/vlib/_docs/index.html` in a browser.

---

- [x] Update tests 
  The doc test will need an update after the formatting changes in the readmes. I forgot how to automatically update the tested files and would greatly appreciate a little hint.

### CODE REVIEW

**Comment by spytheman** [comment]
`VAUTOFIX=1 ./v test cmd/tools/vdoc/`

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by ttytm** [comment]
Looks like the doc tests are not CI covered. The CI failure in the PR is not related to the required doc test update.

Running the tests on master will fail, the autofix produces unwanted sorting changes. A regression sneaked in somewhere. Gonna look to fix the regression first instead of update the tests with the unwanted changes here 👍.

**Comment by ttytm** [comment]
The sorting issue mentioned above happens on mac but not on ubuntu.
On mac it's not a regression as well but happens for old states as well.

**Pull request merged**
