### PR TITLE
checker, cgen: fix infering type for comptimeselector when using ptr type

### LINKED ISSUE #17991: cgen: cannot convert 'int' to 'struct main__Association'
### Describe the bug

cgen error when use `val.$(field.name)` as parameter value

### Expected Behavior

assert pass

### Current Behavior

```bash
==================
/tmp/v_1000/a.5493301217696580005.tmp.c:12603: warning: implicit declaration of function 'main__get_value_from_ref_T___ptr__main__Association'
/tmp/v_1000/a.5493301217696580005.tmp.c:12603: error: '{' expected (got ";")
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### Reproduction Steps

```v
struct Encoder {}

struct Writer {}

struct APrice {}

struct Association {
	association &Association = unsafe { nil }
	price       APrice
}

fn get_value_from_ref[T](val &T) T {
	return *val
}

fn (e &Encoder) encode_struct[U](val U, mut wr Writer) ! {
	$for field in U.fields {
		// broken
		$if field.typ is &Association {
			assert get_value_from_ref(val.$(field.name)) == Association{
				association: unsafe { nil }
				price: APrice{}
			}
		}
	}
}

fn main() {
	e := Encoder{}
	mut sb := Writer{}

	value := Association{
		association: &Association{
			price: APrice{}
		}
		price: APrice{}
	}

	// work
	assert get_value_from_ref(&Association{
		price: APrice{}
	}) == Association{
		association: unsafe { nil }
		price: APrice{}
	}

	// not work
	e.encode_struct(value, mut sb)!
}
```

### Possible Solution

maybe replace
`main__get_value_from_ref_T___ptr__main__Association`
to
`main__get_value_from_ref_T_main__Association`

### Additional Information/Context

_No response_

### V version

V 0.3.3 5e48817

### Environment details (OS name and version, etc.)

Ubuntu

### PR DESCRIPTION
**Pull request by felipensp**
Fix #17991

### CODE REVIEW

**Review by yuyi98 — APPROVED** [review]

**Comment by medvednikov** [comment]
@felipensp draft?

**Comment by felipensp** [comment]
> @felipensp draft?

It is okay.

**Comment by enghitalo** [comment]
This is not missing some test. The issue work like a test. Just copy and past it should work.

**Comment by felipensp** [comment]
> Isn't this PR missing some test? The issue work like a test. Just copy and past it should work.

Yes, thanks. Test added.

**Pull request merged**
