### PR TITLE
vlib: Fix several typos

### PR DESCRIPTION
**Pull request by vbrazo**
Fix several typos while I was studying the `/vlib` last night.

### CODE REVIEW

**Comment by medvednikov** [comment]
@vbrazo you can create a single PR with all typos you found

**Comment by vbrazo** [comment]
@medvednikov Will merge them in one and mark you. Just a minute.

**Comment by medvednikov** [comment]
Thanks

**Comment by vbrazo** [comment]
@medvednikov done 👍

**Comment by medvednikov** [comment]
Thanks a lot!

**Comment by vbrazo** [comment]
@medvednikov 🤝

**Pull request merged**
