### PR TITLE
cgen: fix temporary var name conflicts between const definitions with or_block in different files(fix #19149)

### LINKED ISSUE #19149: C error when using string concat / interpolation in const in different files and gcc or clang compiling
### Describe the bug

I'm running into a builder error when using a comptime assignment or functions with result returns in constants in different files. The same constants work when they are kept in one file.

### Expected Behavior

Same behavior when moved into different files.

### Current Behavior

```
/tmp/v_1000/my_app.15060805251445125294.tmp.c: In function ‘_vinit’:
/tmp/v_1000/my_app.15060805251445125294.tmp.c:17742:16: error: redefinition of ‘_t1’
17742 | _result_string _t1 = os__config_dir();
      |                ^~~
/tmp/v_1000/my_app.15060805251445125294.tmp.c:17733:16: note: previous definition of ‘_t1’ with type ‘_result_string’
17733 | _result_string _t1 = os__config_dir();
      |                ^~~
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.
```

### Reproduction Steps

Builder error:
```v
// my_app/main.v
import os

const my_const = os.config_dir() or { panic(err) } + '/my_path'

fn main() {}
```

```v
// my_app/config.v
import os

const cfg_dir = os.config_dir() or { panic(err) } + '/my_app'
```
`v -cc gcc my_app`

Works in one file:
```v
import os

const (
	my_const = os.config_dir() or { panic(err) } + '/my_path'
	cfg_dir  = os.config_dir() or { panic(err) } + '/my_app'
)

fn main() {}
```

### Possible Solution

_No response_

### Additional Information/Context

Another scenario that will error with split files is using a comptime condition:

```v
// my_app/main.v
import os

const my_const = $if prod {
	os.getenv('APPDIR') + '/my_path'
} $else {
	'/my_path'
}

// Works when it's a function that has regular return and when it's not a comptime operation:
// const my_const = os.getenv('APPDIR') + '/my_path'

fn main() {}
```

```v
// my_app/config.v - same as above.
import os

const cfg_dir = os.config_dir() or { panic(err) } + '/my_app'
```

`v -cc gcc -prod my_app`

No issues with one file:
```v
import os

const (
	my_const = $if prod {
		os.getenv('APPDIR') + '/my_path'
	} $else {
		'/my_path'
	}
	cfg_dir = os.config_dir() or { panic(err) } + '/my_app'
)

fn main() {}
```

### V version

V full version: V 0.4.0 6a4bfef.815439a

### Environment details (OS name and version, etc.)

OS: linux, Pop!_OS 22.04 LTS
Processor: 16 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

getwd: /home/turiiya/Dev/vlang/playground
vexe: /home/turiiya/Dev/vlang/v/v
vexe mtime: 2023-08-16 05:27:47

vroot: OK, value: /home/turiiya/Dev/vlang/v
VMODULES: OK, value: /home/turiiya/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: weekly.2023.33
.git/config present: true

CC version: cc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

### PR DESCRIPTION
**Pull request by shove70**
1. Fixed #19149 
2. Add tests.

### CODE REVIEW

**Comment by spytheman** [comment]
Good find, but I think using the file hash like that in just that specific case, is a bit brittle.
I suggest modifying const_decl_init_later so that each const initialization will have its own scope, so that the temporary variable names will not conflict, i.e. they could look like this:
```c

     {
        _result_string _t1 = os__config_dir();
        if (_t1.is_error) {
           IError err = _t1.err;
           _v_panic(IError_str(err));
           VUNREACHABLE();
           ;
        }    
        _const_main__cfg_dir = string__plus( (*(string*)_t1.data), _SLIT("/my_app"));
     }

     {
        _result_string _t1 = os__config_dir();
        if (_t1.is_error) {
           IError err = _t1.err;
           _v_panic(IError_str(err));
           VUNREACHABLE();
           ;
        }
        _const_main__my_const = string__plus( (*(string*)_t1.data), _SLIT("/my_path"));
     }
```

instead of like this:
```c
_result_string _t1_2251228705892800633 = os__config_dir();
if (_t1_2251228705892800633.is_error) {
    IError err = _t1_2251228705892800633.err;
    _v_panic(IError_str(err));
    VUNREACHABLE();
;
}
    
    _const_main__cfg_dir = string__plus( (*(string*)_t1_2251228705892800633.data), _SLIT("/my_app"));
_result_string _t1_8939042397989667854 = os__config_dir();
if (_t1_8939042397989667854.is_error) {
    IError err = _t1_8939042397989667854.err;
    _v_panic(IError_str(err));
    VUNREACHABLE();
;
}
    
    _const_main__my_const = string__plus( (*(string*)_t1_8939042397989667854.data), _SLIT("/my_path"));
```

**Comment by spytheman** [comment]
The issue should also be converted to a test in: `vlib/v/tests/modules/consts_with_or_blocks_in_different_files/`, and in that folder, 2 files: `consts_should_not_conflict_test.v` (like the main.v from the issue)
and `config.v` (the same as in the issue).
Both should have `module consts_with_or_blocks_in_different_files` at their top, so that they are compiled as part of the same program.

**Comment by shove70** [comment]
MMM, it's prettier,  I'll

**Comment by shove70** [comment]
> The issue should also be converted to a test in: `vlib/v/tests/modules/consts_with_or_blocks_in_different_files/`, and in that folder, 2 files: `consts_should_not_conflict_test.v` (like the main.v from the issue) and `config.v` (the same as in the issue). Both should have `module consts_with_or_blocks_in_different_files` at their top, so that they are compiled as part of the same program, provoking the situation that has to be prevented from regression (what the PR fixes).

Ok.

**Review by spytheman — APPROVED** [review]

**Pull request merged**
