### PR TITLE
checker: allow C values in enum

### PR DESCRIPTION
**Pull request by danieldaeschle**

### CODE REVIEW

**Comment by medvednikov** [comment]
Can you add a small test to enum_test.v?

**Comment by danieldaeschle** [comment]
ok, it doesn't work because the includes are after the enum definitions.

**Comment by danieldaeschle** [comment]
don't know how to fix.

**Comment by danieldaeschle** [comment]
I merged? I said it doesn't work yet.

**Comment by danieldaeschle** [comment]
Why merged? I said it doesn't work yet...

**Pull request merged**
