### PR TITLE
fmt: always use `${}` for string interpolation

### PR DESCRIPTION
**Pull request by Gladear**
- Makes all necessary changes
- Update documentation to reflect this change

### CODE REVIEW

**Comment by yuyi98** [comment]
Unified patterns are simpler and less error-prone, as well as cleaner!

**Comment by UweKrueger** [comment]
> Unified patterns are simpler and less error-prone, as well as cleaner!

It's easier to type without `{}`. The PR does not describe what the plan is. Will the syntax '$a $b' always stay available and only be modified by `vfmt` or will this option be removed?

With array init we have a similar situation. There is the option to leave out the commata and they will be inserted by `vfmt`:
`[1 2 3] -vfmt-> [1, 2, 3]`
In the same sense i think if this PR is merged it will be at least a good to keep the option to enter the short syntax and let it extend by `vfmt`:
'$a $b.c $x.f()' -vfmt-> '${a} ${b.c} ${x.f()}'

**Comment by div72** [comment]
Discussions on the pattern for string interpolation does not seem to be concluded currently. I don't think it's a good idea to make a PR that touches 452 files and create conflicts with people when the next PR could change the pattern to `{}`.

**Comment by Gladear** [comment]
Most of the files were automatically fixed with `v test-cleancode -fix`, I had to manually fix about 10 + the documentation.
Keep in mind that this is only a "style" change, both syntax are still supported. The only difference is that `v fmt` will always use `${}`.

**Comment by Gladear** [comment]
As for the `${}` vs `{}` debate, I have no strong opinion about it, I just want to the syntax to be updated soon so that VLS can implement it's context-free grammar.

**Comment by JalonSolov** [comment]
Alex's last weigh-in was `again, if we force ${}, there's no need in $`.  Looks like just `{}` is "winning".

**Comment by danieldaeschle** [comment]
@Gladear Are you okay with that decision?

**Comment by Gladear** [comment]
I do, I'll close this PR. I won't handle the to transition to `{}`, I'm focused on Windows's closures right now

**Pull request closed without merging**
