### PR TITLE
time: new method year_day and the tests for it.

### PR DESCRIPTION
**Pull request by acimnotes**
Needed a way to get the current day of the year as an integer from the Time struct. If I'm not alone in this, please consider this PR? Thank you 🙏

### <samp>🤖 Generated by Copilot at ca69f8b</samp>

This pull request adds a new `day_of_year` method to the `Time` struct in `vlib/time/time.v`, which returns the current day of the year as an integer. It also adds a test function for this method in `vlib/time/time_test.v`, which verifies its correctness for different dates, including leap years.

### <samp>🤖 Generated by Copilot at ca69f8b</samp>

*  Add `day_of_year` method to Time struct, which returns the current day of the year as an integer, accounting for leap years ([link](https://github.com/vlang/v/pull/18107/files?diff=unified&w=0#diff-31c344f2cfe6fecdafedef24cc42ca595e29556e07d4efc67c5ab8115e199c88R270-R275))
*  Add test function `test_day_of_year` to `time_test.v`, which checks the correctness of `day_of_year` method for different days of December in a leap year ([link](https://github.com/vlang/v/pull/18107/files?diff=unified&w=0#diff-b56c81f693db672f625845374a4bd67074d4d60ba2180b658f6d5b63fc0106b7R145-R164))

### CODE REVIEW

**Comment by JalonSolov** [comment]
Looks like you need to run `v fmt` on time.v to fix most of the problems.

**Comment by spytheman** [comment]
Please add tests for day numbers for leap years, where the Month/Day is <= Feb 29 as well.

**Comment by acimnotes** [comment]
> Please add tests for day numbers for leap years, where the Month/Day is <= Feb 29 as well.

Such a test would make perfect sense, thank you for your reply. But the Time.add_days() method does not work properly for me. When I make up a Time struct of March 1st and do t.add_days(-1) on it it gives me this some weird stuff. Adding positive numbers doesn't work either. Is it a bug or am I doing something wrong? I'm using windows 10. Here is the code:
```
t := time.Time{
            year: 2024
            month: 3
            day: 1
            hour: 10
            minute: 0
            second: 0
            unix: 0
}
println(t)
println(t.add_days(-1))
println(t.add_days(1))
```
result:
`2024-03-01 10:00:00
1969-12-31 00:00:00
1970-01-02 00:00:00`

**Comment by acimnotes** [comment]
@medvednikov sure, thank you.

Seems like the reason why .add_days() wasn't working is that I put zero in the `.unix` field for the `Time` scruct, although I simply copy-pasted that code from the neighboring test `.day_of_week()` so I didn't expect it to not work. Sorry!

I've changed the test into using the `time.parse()` function, maybe it's gonna get working. And ran the `v fmt` on the main file. Thank you guys for your time, I'm really sorry for bothering you 🙏

**Comment by medvednikov** [comment]
I should probably make `unix` a readonly field to avoid such errors.

**Comment by medvednikov** [comment]
I should probably make `unix` a readonly field to avoid such errors.

**Comment by acimnotes** [comment]
@medvednikov  if I may say this here, I'm very new to lower level programming and was attracted towards Golang for it's great features, but it's code just feels so ugly after python. While V is as low level as Golang but the code is actually readable and just feels nice, so even without any tutorials as there are for Py and Go, I merely got straight into the code and was able to read and understand it! It feels like a great achievement to me, sorry 😅

So, just wanted to let you know how amazing your project is. Very thankful and grateful to you all for what you do 🙏❤

**Comment by spytheman** [comment]
Please also add at least these assertions:
```v
assert time.parse("2023-01-01 10:00:00")!.day_of_year() == 1
assert time.parse("2024-01-01 10:00:00")!.day_of_year() == 1
assert time.parse("2025-01-01 10:00:00")!.day_of_year() == 1
```

**Comment by medvednikov** [comment]
Thanks, glad you like it. And yes, readability is one the main points of V. I'm happy it works as intended :)

**Comment by medvednikov** [comment]
By the way in Go it's `YearDay()`, and we try to be consistent with their stdlib, so I think it should be renamed to`year_day()`.

**Comment by acimnotes** [comment]
@spytheman Wow! Seems like you already know that it's going to fail, sir, no? 
I've used the algorithm from the `Time.custom_format` function and Jan 1st on the **leap** years gives number 2 instead of 1 in my new method and in the custom_format both.
```
println(time.parse('2023-01-01 20:00:00')!.custom_format("DDD"))
println(time.parse('2024-01-01 20:00:00')!.custom_format("DDD"))
>1
>2
```
Seems like we have to turn to the golang's YearDay function not only for the name but for the algorithm as well 😅 Or am I just doing something wrong? I've also tried to make up the Time struct for Jan 1st 2024 manually instead of using the `.parse` method and it still gives number 2 for the leap years.

Sorry for mentioning this, but I'm studying a non-dual spiritual teaching these days, it's somewhat similar to zen-buddism, talks about the unreality of time, among other things, and here we are facing this issue with `Time` in the code... Synchronicities! 😳

**Comment by acimnotes** [comment]
Here is what I've come up with. Please review when you'll have time. 
I guess the `Time.custom_format` function needs to be fixed as well, since I originally took the algo from it. Do you want me to do that here within this PR or should it be as a separate one? What do you think?

**Comment by acimnotes** [comment]
> it is better to have a separate PR for the other function to not delay this one.
Wise approach. And when this `.year_day` method will be ready, we can just use it in `.custom_format`.

**Pull request merged**
