### PR TITLE
net: fix socket non-blocking read/write

### PR DESCRIPTION
**Pull request by kbkpbot**
TcpConn non-blocking read/write will not work, even you set_blocking(false)

### CODE REVIEW

**Comment by shove70** [comment]
net module is non-blocking by default, so why change it to blocking?


> TcpConn non-blocking read/write will not work, even you set_blocking(false)

There should be other reasons, and I think should rule out other reasons first

**Comment by JalonSolov** [comment]
Changing the default from non-blocking to blocking is a serious breaking change.  Even if that's the way it works now, people are expecting non-blocking from the current description, and that's the way they would have written their code.

**Comment by shove70** [comment]
> Changing the default from non-blocking to blocking is a serious breaking change. Even if that's the way it works now, people are expecting non-blocking from the current description, and that's the way they would have written their code.

yes 👍

**Comment by Casper64** [comment]
> I suggest change the default state of a tcp connection , from non-blocking mode to blocking mode.
> 
> As most examples, tests use a blocking mode tcp connection.
> 
> 

Everything in the net module uses non-blocking socket and `select` to check whether sockets are ready to read/write, so all examples use non-blocking sockets.

But the example code acts blocking, since we only use `select` on one socket. That is the difference.

I don't think this change is necessary and I agree with @JalonSolov that this change is too breaking

**Comment by spytheman** [comment]
I agree that this change is too breaking.

Note, that you can achieve more or less the same, by just compiling with `-d net_blocking_sockets`.

In my personal opinion, blocking sockets are a better default (since blocking programs require less debugging), but others can reasonably disagree, and changing everything now, should be done after a lot of thought :-|, not by just modifying every program to have `server.set_blocking(true)` calls in it.

**Comment by Casper64** [comment]
Hm I think I get what you mean. Why are there 2 read calls in the current implementation of `read_ptr`? 

This line

```v
if code == int(error_ewouldblock) { 
```

Could also check wether the socket is non-blocking. If it is non-blocking just return 0 (read bytes). The function exits immediately and that is what you expect from a non-blocking connection. If the connection is blocking we do want to wait for the socket to become ready to read.

It's a matter of documentation imo, because `read_ptr` and `read` will ALWAYS return some data, or an error. Even if it involves waiting for the socket to be ready.

**Comment by Casper64** [comment]
@kbkpbot currently you can do a non-blocking read the way you described:

```v
fn non_blocking_read(mut c net.TcpConn, mut buf []u8) int {
    res := wrap_read_result(C.recv(c.sock.handle, voidptr(buf.data), buf.len, 0))!
    if res > 0 { return res }
    
    // handle errors
    return 0
}
```

**Pull request closed without merging**
