### PR TITLE
checker: fix error of match in map_init (fix #8579)

### LINKED ISSUE #8579: match doesn't work either in return statement or maps
**V version:** master
**OS:** atch

**What did you do?**
```
	return {
		'token': cfg['token'][0]
		'sleep': match cfg['sleep'][0].len {
			0 { '60' }
			else { cfg['sleep'][0] }
		}
		'every': match cfg['every'][0].len {
			0 { '5' }
			else { cfg['every'][0] }
		}
	}

```

Error

```
/tmp/v/gh_notify.7498108735114691329.tmp.c: In function ‘main__config’:
/tmp/v/gh_notify.7498108735114691329.tmp.c:17969:388: error: expected expression before ‘int’
17969 |  return new_map_init_2(&map_hash_string, &map_eq_string, &map_clone_string, &map_free_string, 3, sizeof(string), sizeof(string), _MOV((string[3]){_SLIT("token"), _SLIT("sleep"), _SLIT("every"), }), _MOV((string[3]){(*(string*)/*ee elem_typ */array_get((*(array_string*)map_get_1(ADDR(map, cfg), &(string[]){_SLIT("token")}, &(array_string[]){ __new_array(0, 1, sizeof(string)) })), 0)), int _t812 = (*(string*)/*ee elem_typ */array_get((*(array_string*)map_get_1(ADDR(map, cfg), &(string[]){_SLIT("sleep")}, &(array_string[]){ __new_array(0, 1, sizeof(string)) })), 0)).len;
   
builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fixes error of match in map_init (fix #8579).

- Fix error of match in map_init.
- Add test.

```vlang
fn main() {
	a := x()
	println(a)
}

fn x() map[string]string {
	mut cfg := map[string][]string{}
	cfg['token'] = ['a', 'b']
	cfg['sleep'] = ['30', '60']
	cfg['every'] = ['1', '5']

	return {
		'token': cfg['token'][0]
		'sleep': match cfg['sleep'][0].len {
			0 { '60' }
			else { cfg['sleep'][0] }
		}
		'every': match cfg['every'][0].len {
			0 { '5' }
			else { cfg['every'][0] }
		}
	}
}

D:\Test\v\tt1>v run .
{'token': 'a', 'sleep': '30', 'every': '1'}
```

### CODE REVIEW

**Comment by Delta456** [comment]
Please use `map{'token': 'a', 'sleep': '30', 'every': '1'}` instead of `{'token': 'a', 'sleep': '30', 'every': '1'}` as it is the new map syntax.

**Comment by yuyi98** [comment]
OK

**Comment by tami5** [comment]
Thanks @yuyi98

**Comment by yuyi98** [comment]
@tami5  You're welcome. There may be other problems, we will continue to improve it.

**Pull request merged**
