### PR TITLE
Compiler: Add support for while loop, 

### PR DESCRIPTION
**Pull request by irshadshalu**
This PR adds support for ordinary while loops as raised in issue #3529 . 

Please note that I haven't removed support for `for condition {` syntax as it will break so much of existing code (I have put a warning though)

<!--

Please title your PR as follows: `time: fix foo bar`. 
Always start with the thing you are fixing, then describe the fix.
Don't use past tense (e.g. "fixed foo bar").

Explain what your PR does and why.

If you are adding a new function, please document it and add tests:

```
// foo does foo and bar
fn foo() {

// file_test.v
fn test_foo() {
    assert foo() == ...
    ...
}
```

If you are fixing a bug, please add a test that covers it.

Before submitting a PR, please:
  A) run the tests with `v test-compiler` .
  B) make sure, that V can still compile itself:
```shell
./v -o v v.v
./v -o v v.v
```

I try to process PRs as soon as possible. They should be handled within 24 hours.

Applying labels to PRs is not needed.

Thanks a lot for your contribution!

->

### CODE REVIEW

**Comment by memeone** [comment]
Iirc the for loop in V is supposed to replace both the usual for and while loops

**Comment by jtkirkpatrick** [comment]
@memeone see the linked issue. The use of `in` to test for membership leads to confusion between for-in loops and for-condition loops.

**Comment by joe-conigliaro** [comment]
I had been thinking something like this since as is already a keyword:

**for each a in items / for each items as a**
```
for items as a {

}
**while a exists in items, since the existing in syntax**
```
for a in items {

}
```

**Comment by irshadshalu** [comment]
> 
> **a exists in items (since the existing in syntax `exists := x in items`)**
> 
> ```
> for a in items {
> }
> ```
> 

But this again leads to confusion as `for-in` construct is used as iteration in most languages (Python, Ruby, etc..).

imo, `for-in` construct can be kept as is for iterating through an array. 

Having a `while` loop will certainly clear this issue as `while-condition` is a pretty common and well understood construct. 

@medvednikov , What do you think?

**Comment by joe-conigliaro** [comment]
@irshadshalu it wasn't really even a suggestion, just  something that I had thought about before and mentioned on the discord, and thought worth mentioning here.

But I'm a bit confused now after looking at this again, I thought the whole confusion to about for loop was due to the use of `for x in items`, since `x in items` is a bool

**Comment by jtkirkpatrick** [comment]
@joe-conigliaro it's probably a good candidate to pick up the infinite loop too.
```v
while {
   ... 
}
```
This probably makes more sense than `for`, since the traditional `while true` is what's being replaced.

**Comment by ka-weihe** [comment]
I personally think it would be a pity to add a while-loop. Having only one looping construct makes V special. There is a lot of ways to solve the issue without adding a while loop, `array has val`, `val exists in arr`, or change how for-in loops are declared.

**Comment by spytheman** [comment]
I also think like @ka-weihe . 

The special case, that while is intended to cleanup, can also be done with if and break like this:
```v
for {
   if !(x in [1,2,3]) { break }
   // stuff that modifies x
}
``` 

Having both `for` and `while`, and explaining the difference to each new user is not very one way-ish.

**Comment by spytheman** [comment]
@jtkirkpatrick you can also say that `for{}` is made to replace `for (;;)` . In C, most people seem to use either that, or `while(1){}`.

**Comment by jtkirkpatrick** [comment]
@spytheman @ka-weihe One-way doesn't have to mean one keyword. For-in makes sense for iterating over a sequence. While-condition makes sense for looping until a condition is false. It's still one way to do things, and it adds clarity. The inability to write `for x in y` using `in` to test for membership is a problem that requires a hidden rule to set the precedence of for-in` higher than `for-condition`.

**Comment by irshadshalu** [comment]
> Having only one looping construct makes V special. 

Yes, and it's kinda nice. However, the philosophy of V isn't to be special. It is a 
`Simple language for building maintainable programs` and concise expression of logic is what makes V maintainable. 

Your alternative suggestions are definitely good. Although I believe a conditional while loop makes more grammatical and syntactic sense and will be easy for beginners to follow.

**Comment by ka-weihe** [comment]
I disagree.  I did not use the "one-way philosophy" in my argument, but there would be a huge overlap where you could use both loops with little to no difference. That is imo not "one-way".  My argument is that having one looping construct makes V special, and I like the other solutions better as opposed to a while-loop.

**Comment by irshadshalu** [comment]
@ka-weihe , I get your point.

I submitted this PR partly because I favour while-conditional blocks and mostly because @medvednikov also seem to agree with it in the linked issue (#3529 )


But if everyone thinks it's not going to add a value to the language, we can consider alternatives :)

**Comment by irshadshalu** [comment]
@spytheman 
> 
> The special case, that while is intended to cleanup, can also be done with if and break like this:
> 
> ```v
> for {
>    if !(x in [1,2,3]) { break }
>    // stuff that modifies x
> }
> ```
Imo, that is just extra steps and doesn't look very neat.

**Comment by spytheman** [comment]
@irshadshalu yes, it does not look neat, My point is that there is a way to solve the ambiguity without requiring a new keyword for the same concept, a word that overlaps with much of the current uses of for.

**Comment by ka-weihe** [comment]
>I submitted this PR partly because I favour while-conditional blocks and mostly because @medvednikov also seem to agree with it in the linked issue (#3529 )

As far as I can see, Alex does not explicitly say that he agrees/prefers adding the while-loop in #3529. He just states that it would solve the problem, which we can all agree on.

**Comment by jtkirkpatrick** [comment]
@spytheman `while` is a keyword in so many languages, I don't think it'll be a problem for anyone. For most people, the use of `for` as the only loop keyword is going to require *more* learning than using two keywords to separate two different kinds of loops.

**Comment by medvednikov** [comment]
Yeah, exactly. `while` can be used to solve this, but I'm not a fan of adding it to the language.

This is a tricky problem, I need to think more about this.

**Comment by jtkirkpatrick** [comment]
@medvednikov what is the primary reason for your reluctance?

**Comment by memeone** [comment]
Imo: keep `for x in array {}` and change if in to `if array has x`

**Comment by jtkirkpatrick** [comment]
@memeone does this imply `for array has x` is the looping syntax?

**Comment by memeone** [comment]
@jtkirkpatrick yeah

**Comment by joe-conigliaro** [comment]
I have to say I don't like the idea of the while loop the more I think about it, I little how v had one looping construct, and the reason for adding another is over a little confusion. Ive been using/developing v since its first release and I never felt confused, I understood the issue though.
I feel like these would be the simplest solutions:
A) Just use the long for loop syntax for conditional
```
for ; i in items ; {
```
B) if the `in` syntax used in a loop and surrounded by parens its forced to the conditional form:
```
for (x in items) {
for !(x in items) {
```
C) use the `as` keyword, similar to PHP's use of `foreach items as i => v`:
```
for items as i, v {
```

**Comment by spytheman** [comment]
I agree with Joe. Also A and B have the advantage that they already work.

**Comment by ka-weihe** [comment]
I agree as well, but imo A and B does not solve the ambiguity of the `in` keyword.

**Comment by spytheman** [comment]
They do, since in both cases, the expression `x in y` is unambiguously resolved to a boolean expression, due to its placement, and is evaluated just like in the if check.

**Comment by joe-conigliaro** [comment]
@ka-weihe that would also work (so then loops would remain untouched and the conditional form changes), but it adds a new keyword, and all of these uses would need to be replaced: `exists := x in items`

**Comment by ka-weihe** [comment]
@spytheman. I get that, but `for (x in items) {` and `for x in items {` looks the same. That is imo a bit ambiguous. 

@joe-conigliaro. That is definitely true.

**Comment by joe-conigliaro** [comment]
@ka-weihe I prefer `has` than adding a while loop, I don't see a problem with it. If I was being super picky I would say it requires replacement of all uses of the conditional `in`, and it adds a new keyword.
I also like the use of `as`

**Comment by jtkirkpatrick** [comment]
@joe-conigliaro 
> I always liked how v had one looping construct, and if the only reason for adding another is over a little confusion I just don't feel as though that's a good enough reason

I would argue that V doesn't have just one looping *construct*, it has one looping *keyword* which is being used in several looping constructs. That's what leads to the ambiguity.

I don't understand the motivation for using only one keyword. It doesn't seem like a good enough reason to not have `while` and resolve the confusion of `for-in`. No one is going to look at V and say, "shame they reserved while, I needed that for a variable name!" Many people will look at `for (x in arr)`, `for ; x in arr; ` and `for x in arr` and wonder why the language was designed this way.

**Comment by joe-conigliaro** [comment]
@jtkirkpatrick There are all personal preferences, everyone things differently.

I like having one type of `looping keyword`. also the while loop and for loop would both be able to do many of the same things, and its introduction was only to solve a case of confusion. This is what bothers me.

I also never liked the crossover in other languages also. As I said these are all personal preferences.

**Comment by dhonx** [comment]
I prefer all is `for`

**Comment by jtkirkpatrick** [comment]
```v
for if x in array {

}
```
How about something like this then for conditional loops? `for-if` loops. Uses an existing keyword, doesn't break `in`, and makes a clear difference between `for x in array` and `for if x in array`.

@joe-conigliaro ?

**Comment by joe-conigliaro** [comment]
@jtkirkpatrick I'm not really a big fan of that. I don't think there's any rush to suet this out. I think it's better to think it through. Thanks for your work on this PR im sorry your first one was met with such opposition. Obviously it's nothing personal and your work is greatly appreciated so please don't feel discouraged.

**Comment by irshadshalu** [comment]
@joe-conigliaro 

Hey, thank you for your words and having gone through this discussion, I can very well understand why you guys would want just one looping mechanism that handles them all. Adding `while` does solve the ambiguity, but can we do better is what we should think about. Again, we also had many interesting alternative suggestions and I can see that you guys are very passionate about V. 

Also, I respect Alex's decision and will give time for him to come up with a proper plan. 

The community is very welcoming and I am not discouraged a bit. I will definitely keep on contributing when I get time :slightly_smiling_face:

**Comment by joe-conigliaro** [comment]
@irshadshalu Thank you, this is a great community and its fantastic to have you aboard!

**Comment by TarekAS** [comment]
@jtkirkpatrick
> 
> 
> ```v
> for if x in array {
> 
> }
> ```
> 
> How about something like this then for conditional loops? `for-if` loops. Uses an existing keyword, doesn't break `in`, and makes a clear difference between `for x in array` and `for if x in array`.

In my opinion, this is the best solution in this thread by process of elimination.

The downside with all these approaches is that they only exist to solve that single instance of ambiguity, but make readability slightly worse 99% of the time (e.g. `has` is less intuitive than `in` because the array is on the left side).

`for if`'s only downside is when doing something like `for if x` where the `if` is clearly superfluous.

IMO these are the next best solutions:
1. Changing nothing; people will adapt to this quirk and will use `for ;x in y;` for disambiguation. This condition rarely appears, so it may not be worth a syntax change.
2. `has`; unfamiliar keyword, slightly less readable/clean than `in` (subjective).
3. `while`; new keyword to solve one problem, but at least it's familiar. `while x in y` could still be mistaken as trying to iterate over elements. So it's not 100% foolproof.

**Comment by medvednikov** [comment]
@TarekAS this has been resolved already.

`while x in array` needs an `x` variable already defined, and the for loop declares a new variable.

So if the programmer tries to do

```
x := ...
for x in array { // while x in array

}
```

The program won't compile because x is redeclared.

`while x in array {` is used very rarely, and can be achieved with `for (x in array) {` or `for { if !(x in array) { break } }`

**Pull request closed without merging**
