### PR TITLE
tools/vget => tools/vpm , usage: v pm search module, v pm install module, etc

### PR DESCRIPTION
**Pull request by spytheman**
This PR should probably be merged after #2609 , or instead of it (since it includes it).

It implements draft support for the following commands:
```shell
0[11:13:30] /v/newv LINUX $ ./v pm
Usage:
  a) v pm help -- shows this help screen
  b) v pm search module [module] [module] [...]
  c) v pm install module [module] [module] [...]
  d) v pm update [module] [...]
  e) v pm remove [module] [...]

  You can also pass -h or --help to each `v pm` command, to see more details about it.
5[11:13:32] /v/newv LINUX $
```

For now, only `v pm install module` is fully implemented (the old tools/vget), the rest just show todos, and help screens.

This PR also fixes a confusing repl runner interaction with VFLAGS, where if `-cc gcc` was specified in VFLAGS, running v without any other arguments tried to compile a gcc folder.

It also launches the tools/vrepl tool with launch_tool('vrepl'), like the other v sub programs/tools, thus guaranteeing that it is compiled lazily just once per v update/tool source code update.

### CODE REVIEW

**Comment by medvednikov** [comment]
gitignore conflict

**Comment by spytheman** [comment]
rebased over current master, and fixed the .gitignore files.

**Comment by medvednikov** [comment]
I think `v install` is better than `v install`, same with search.

**Comment by spytheman** [comment]
So:
v search module
v install module
v update module
v remove module 
?

**Comment by medvednikov** [comment]
yes, where `module` is an actual module, not a command

```
v install sqlite
v search sqlite
....
```

**Comment by spytheman** [comment]
done

**Comment by spytheman** [comment]
```shell
0[14:08:39] /v/newv LINUX $
0[14:08:39] /v/newv LINUX $ ./v2 search
  v search requires *at least one* keyword
2[14:08:41] /v/newv LINUX $ ./v2 search --help
Usage:
  v search keyword1 [keyword2] [...]
  ^^^^^^^^^^^^^^^^^ will search https://vpm.vlang.io/ for matching modules,
                    and will show details about them
0[14:08:43] /v/newv LINUX $ ./v2 install
  v install requires *at least one* module name
2[14:08:47] /v/newv LINUX $ ./v2 install --help
Usage:
  v install module [module] [module] [...]
  ^^^^^^^^^^^^^ will install the modules you specified
0[14:08:49] /v/newv LINUX $ ./v2 install sqlite
Skipping module "sqlite", since https://vpm.best responded with 502 http status code. Please try again later.
1[14:08:53] /v/newv LINUX $ ./v2 update --help
Usage:
 a) v update module [module] [module] [...]
    ^^^^^^^^^^^^ will update the listed modules to their latest versions
 b) v update
    ^^^^^^^^^^^^ will update ALL installed modules to their latest versions
0[14:09:01] /v/newv LINUX $ ./v2 remove --help
Usage:
 a) v remove module [module] [module] [...]
    ^^^^^^^^^^^^ will remove the listed modules
 b) v remove
    ^^^^^^^^^^^^ will remove ALL installed modules
0[14:09:05] /v/newv LINUX $ ./v2 update
TODO: v update
4[14:09:08] /v/newv LINUX $ ./v2 remove
TODO: v remove
4[14:09:12] /v/newv LINUX $ ./v2 update sqlite
TODO: v update
4[14:09:15] /v/newv LINUX $ ./v2 remove sqlite
TODO: v remove
4[14:09:18] /v/newv LINUX $
```

**Comment by medvednikov** [comment]
Thanks.

**Pull request merged**
