### PR TITLE
vlib.http: fix request, properly add params to url

### PR DESCRIPTION
**Pull request by joe-conigliaro**
this fixes: https://github.com/vlang/v/issues/1599

later the methods should probably take a params argument?
But this keeps the interface the same for now

### CODE REVIEW

**Comment by vpervenditti** [comment]
with this pr http request doesent return anything

**Comment by joe-conigliaro** [comment]
Hrmm that's weird it works for me I'll test later out at the moment

**Comment by joe-conigliaro** [comment]
@vpervenditti It was working for me on win/lin, ive changed somethign now just to make it simpler and I had & instead if ? by accident.

I think the problem might be openssl isnt following redirects, can you try a page that dose't redirect?

@medvednikov do you know if there is a way for openssl to auto folllow 301s? If not I could do it how I did it in backend_win? if you take a look there

**Comment by medvednikov** [comment]
I'll need to test the redirects, will do that today.

**Comment by joe-conigliaro** [comment]
@medvednikov Thanks :) if it cant be done Ill just do it manually in v

**Comment by joe-conigliaro** [comment]
@medvednikov this now added with changes in https://github.com/vlang/v/pull/1631

**Comment by vpervenditti** [comment]
but http module is still broken :(

**Comment by medvednikov** [comment]
@vpervenditti you need to provide more details.

**Comment by vpervenditti** [comment]
sure. 
here is everything:

```
[dario@dariopc vtest]$ cat b.v 
import json
import net.urllib
import http

mut args := map[string]string
mut get_data := ''
url := 'https://postman-echo.com/get?'
args['bo'] = 'aa'
args['ee'] = 'yo man'
for key, value in args {
    get_data += key+'='+urllib.query_escape(value)+'&'
}
out := url + get_data
println(out)
resp := http.get(out) or {
    panic('error')
}
println(resp.text)
[dario@dariopc vtest]$ v run b.v 
https://postman-echo.com/get?bo=aa&ee=yo+man&
{"args":{},"headers":{"x-forwarded-proto":"https","host":"postman-echo.com","user-agent":"v","x-forwarded-port":"443"},"url":"https://postman-echo.com/get"}
[dario@dariopc vtest]$ 
```

it doesent add get/post value to http request

**Comment by medvednikov** [comment]
@vpervenditti fixed, thanks for reporting.

**Pull request closed without merging**
