### PR TITLE
fix primitive type variants for sumtypes

### PR DESCRIPTION
**Pull request by kalapalo**
type PrimTypes = string | int | f64 | u32 | bool

Presently V supports struct as variants for sumtypes. Support for primitive types are not fully implemented. Sumtypes can be assigned primitive types variants but cannot cast back to the variant types with the `as` cast or using match smartcasting, mainly because the type being returned is always a pointer.
This PR aims to fix the unwrapping of variants in such a way they will have the exact same type they had by the wrapping time. As a consequence, primitives will be unwrapped correctly.

Observations:
1. this PR makes smartcasts for sumtypes in mach expressions to work only when the condition is an identifier (ast.Ident). would like to know if for selectors (ast.SelectorExpr) this should be implemented;
2. would also like to know how sumtypes should behave when assigned to other sumtypes (of the same type, of course), if like structs (referencing or dereferencing, according to the need) or in a normal (strict) way. besides assignment, this is important for fn arg passing;
3. should `[]string` be allowed as a variant ? or, better asking, what should be allowed as variants ?
4. since for structs, StructType and &StructType are cast automatically, should `&` be allowed together with a variant type, for sumtype definitions or not ?

attached below goes a test. sorry, didn't know where to put it.

### CODE REVIEW

**Comment by kalapalo** [comment]
test file
[test_primitive_sumtype.v.zip](https://github.com/vlang/v/files/5013843/test_primitive_sumtype.v.zip)

**Comment by Delta456** [comment]
@kalapalo I think you should add the tests in `vlib/v/tests`.

**Comment by kalapalo** [comment]
Most of the errors are `array.get: index out of range (i == 0, a.len == 0)`. My only guess is because I access `branch.stmts[0].position()`, but this is enclosed in a `if branch.stmts.len > 0`.

**Comment by kalapalo** [comment]
Is this catch 22 ?

**Comment by SleepyRoy** [comment]
@kalapalo Hi I saw you closed this PR. Did you encounter any difficulties? And are you still planning to fix sumtype?

**Comment by kalapalo** [comment]
Hey @SleepyRoy , I am sorry, I do not check github mail at all, had to come back to this closed PR just to check one thing and saw your comment. Yes, I have closed it after much frustration, could not make it fully work.

I saw your PRs on sumtype. We have different approaches for the thing. While you go to cgen and deref the sumtypes whenever needed, I decided to go checker and then cgen, to work on smartcasts, for the unwrapped variant to have the same type it had when wrapped, be it pointer or not. Basically, I change `as cast`, `match` and `if` on both files.

If you wanna see the code, please go to https://github.com/kalapalo/v. I do a 2 steps fix, on the first commit (on branch fix-sumtype-primitive-variants-1) I introduce the changes and do a `./v -cg -o v2 cmd/v`. v2 works great, I run the test file included in the commit (vlib/v/tests/sumtype_primitives_test.v) and other tests with no problem. Wraps and unwraps correctly numbers (including any_int and any_float), strings, enums, etc.

Then, as expected, I need to change some code on the compiler because it will not compile due to the first commit. Basically I remove lots of (now unecessary) derefs `*` and do a few refs `&` and put all this on a second commit (on branch fix-sumtype-primitive-variants-2). then I do a `./v2 -cg -o v3 cmd/v`, and then comes the problem, whatever I try compile with v3 makes it segfault with a message `fn unsafe_expr: assert !c.inside_unsafe on checker.v (line 2961 on that code).

Tried hard but could not finalize the fix because of the segfault.
If you want to take a look, please be my guest.
Thanks.

**Pull request closed without merging**
