### PR TITLE
feat: vcheck-md / check vor broken TOC headline links

### PR DESCRIPTION
**Pull request by aheissenberger**
* parse all # headlines
* create an error if a headline exists more than once

**example output of existing doc:**
```
doc/upcoming.md:97:13: error: broken headline link - other headline with same wording exists
#### default
doc/upcoming.md:100:11: error: broken headline link - other headline with same wording exists
#### `mut`
doc/upcoming.md:103:14: error: broken headline link - other headline with same wording exists
#### `shared`
doc/upcoming.md:107:14: error: broken headline link - other headline with same wording exists
#### `atomic`
doc/docs.md:2190:11: error: broken headline link - other headline with same wording exists
## Modules
doc/docs.md:2282:16: error: broken headline link - other headline with same wording exists
###### Example:
doc/docs.md:2292:16: error: broken headline link - other headline with same wording exists
###### Example:
doc/docs.md:2320:15: error: broken headline link - other headline with same wording exists
###### Example
doc/docs.md:3662:12: error: broken headline link - other headline with same wording exists
File: doc/docs.md                   , Lines:  4701, example from 4508 to 4586, command: compile
doc/vscode.md:48:10: error: broken headline link - other headline with same wording exists
### Setup

Warnings: 23 | Errors: 10 | OKs: 170
```

### CODE REVIEW

**Comment by aheissenberger** [comment]
@spytheman How should I proceed - the CI fails because there are a couple of other bad MD files - should I fix them too?

**Comment by aheissenberger** [comment]
There are 3 ways to go:
1. force all files to have non matching headline title independent of their structural level
2. only check if an existing local link is broken by pointing to more than one headline in the same document
3. error if an existing local link is broken by pointing to more than one headline and warn if there are headlines with matching title

**Comment by Gladear** [comment]
In my experience, sometimes I want to link to a particular section of an MD file. It is really bothering when I can't because the link is broken.
I'd go for option 1, links aren't only internal the MD file

**Comment by spytheman** [comment]
I agree, I think checking should be done regardless of the level. That will guarantee unique and non broken links in .md files that passed the `v check-md` checks.

**Comment by spytheman** [comment]
> @spytheman How should I proceed - the CI fails because there are a couple of other bad MD files - should I fix them too?

I'll fix them in a few minutes (one of the files is a temporary generated file, that should not have been commited in the first place imho).

**Comment by aheissenberger** [comment]
I have rewritten the logic to better deal with the existing documents and only create an error if links are broken.
* If a headline exists multiple times in a document but no link exists targeting the headline only a warning is issued.
* I now also respect anchors e.g. `<a id="this-is-a-link-targe" />`
* I did fix all existing broken links and duplicated targets

with this new approach I do not get errors from all the markdown files which exist in the example folder and still can ensure non broken links in a document.

I do not check for other form of possible markdown header style e.g. "===" and I do not support the very specific references `[bar]: /url "title"` which are both not used in the existing document.

Based on this step I will be able to provide a feature which can programatically replace an existing TOC with the latest version.

**Comment by aheissenberger** [comment]
> In my experience, sometimes I want to link to a particular section of an MD file. It is really bothering when I can't because the link is broken.
> I'd go for option 1, links aren't only local to the MD file

I agree with this but I think having this as a warning is a better migration path based on the existing MD docs.
I suggest we should improve the existing normal link check to include a check for the anchor if the domain is on a whitelist. This would allow to error on broken links between existing project related documentation parts.

**Pull request merged**
