### PR TITLE
examples/text_editor: edit multiple files

### PR DESCRIPTION
**Pull request by esquerbatua**
Improve example to permit edit multiple files.

### CODE REVIEW

**Comment by spaceface777** [comment]
Good work, but I'm not sure if esc is the best key combination for this, since you can't go back to a previous file, and you have to close all other files before being able to exit.

Some possible ideas, not sure which one I like better:
- `ctrl+n`, `ctrl+p`, for next/previous file
- `ctrl+left`, `ctrl+right` / `alt+left`,`alt+right`

I would've suggested `ctrl+tab` and `ctrl+shift+tab` to move back and forth respectively, but both of those emit the exact same event as just `tab`, so we can't do that...

**Comment by spytheman** [comment]
Ctrl-< and Ctrl-> ?

**Comment by spytheman** [comment]
Ctrl-Left and Ctrl-Right are usually for going back/forward by word.

**Comment by spaceface777** [comment]
> Ctrl-< and Ctrl-> ?

Those don't seem to emit the correct events (or any events at all, actually) :/
`ctrl+,` and `ctrl+.` (< and > are shift + , and . on US keyboards), emit the same escapes as just `,` and `.` (i.e. with no modifiers)

The event_viewer example is super useful for testing different events (those that work, those that don't but can be implemented, and those that don't work but can't be fixed, because they emit the same escapes as a different event). 

> Ctrl-Left and Ctrl-Right are usually for going back/forward by word.

Ah, right. I actually wanted to implement that :smile:

**Comment by spytheman** [comment]
`micro` uses Alt-, and Alt-. for switching between tabs.

**Comment by spytheman** [comment]
> The event_viewer example is super useful for testing different events
yes, that is what I used too :-)

**Comment by spaceface777** [comment]
Those do emit proper events, makes sense that they would be used :slightly_smiling_face:

**Comment by spytheman** [comment]
On my keyboard, `,` and `<` are on the same key, same with `.` and `>` btw.

**Comment by spaceface777** [comment]
mine too, `<` being `shift + ,`  and `>` being `shift + .`

**Comment by esquerbatua** [comment]
Great Job! Thanks!

**Comment by Larpon** [comment]
@esquerbatua - nice addition - thanks!

Sorry, I'm late to the party. On my system Ctrl+PgUp/PgDown - is tab switching in browsers and editors

**Pull request merged**
