### PR TITLE
travis: Windows fixes

### PR DESCRIPTION
**Pull request by aguspiza**
add submodule freetype for windows x64
fix windows json
fix windows stbi
windows setenv unimplement disable tests
test glm disabled because it fails in windows
disable tetris, links_scraper and news_fetcher examples in Makefile

Windows can not regerate v while it is running, so i compile 'vnew' and later renamed.
Thre are several reasons that windows newline '/r/n' fails the build so i have set  *.v text eol=lf in .git attributes meanwhile

I have protected some places for paths with spaces but it is WIP

Also moved v.c inside the repo to improve reproducible builds.

### CODE REVIEW

**Comment by medvednikov** [comment]
Hi

Thanks for your work.

In the future, can you please submit 1 PR per 1 issue? That way it's easier to merge them.

v.c shouldn't be in this repo. It will cause too much noise.
Don't remove "" in paths, they are needed for paths with spaces to work.
Don't replace multiline strings with concatenation or multiple function calls, this slows things down significantly.

**Comment by aguspiza** [comment]
I am trying to split this work. The goal was having green build in travis. 
I am using the crossbuild path from linux to windows to get faster iterations. So please accept #855

Current v.c build will does not work on travis-windows. Thats is why v019.c is there.

**Comment by aguspiza** [comment]
Replaced with #858

**Comment by aguspiza** [comment]
> Don't remove "" in paths, they are needed for paths with spaces to work.

By the way I was *adding* quotes to support windows "Documents and Settings" folder, even it is just for WinXP, my tests did not work without those quotes when doing some operations with TmpPath

**Pull request closed without merging**
