### PR TITLE
vlib: add missing doc strings to `x.ttf` module

### PR DESCRIPTION
**Pull request by larpon**
Part of #7047

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYzZWNkNmYxNDRmNTg1YWU0ZTM3MmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.UCFF3C3nC_yLMlyi8fobi120GmU5KJFn4TgnDWzeYec">Huly&reg;: <b>V_0.6-21642</b></a></sub>

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Thank you 🙇🏻‍♂️ .

**Comment by penguindark** [comment]
Thanks a lot ❤️  
@larpon Are you using it?

**Comment by larpon** [comment]
> Thanks a lot ❤️ @larpon Are you using it?

@penguindark yes, for studying and testing at the moment 😊

**Comment by penguindark** [comment]
If you need any hints on that code didn't hesitate to ping me 👍 
It is divided in two part (see documentation)  loader and two renders.

**Comment by larpon** [comment]
Thanks!

**Pull request merged**
