### PR TITLE
parser: fix expected type enum error pos

### PR DESCRIPTION
**Pull request by danieldaeschle**
fixes https://github.com/vlang/v/issues/7263

### CODE REVIEW

**Comment by joe-conigliaro** [comment]
Because of the way the error is worded it feels like the rune should be underlined, maybe the error could be reversed. It's not a big deal, just an observation :)

**Comment by danieldaeschle** [comment]
I don't understand.. this PR fixes at least the position. If the error should go away is something different :D

**Comment by joe-conigliaro** [comment]
@danieldaeschle I was just making comment on the error message, nothing to do with your changes

**Comment by danieldaeschle** [comment]
ok :)

**Pull request merged**
