### PR TITLE
time: fix time offset

### PR DESCRIPTION
**Pull request by Ekopalypse**
Fixes time offset on windows by using the local time structure.

### CODE REVIEW

**Comment by Ekopalypse** [comment]
fixes #8323

**Comment by spytheman** [comment]
Can you add a regression test please?

**Comment by Ekopalypse** [comment]
That is what I'm currently evaluating, but it seems I can't find a reasonable way without introducing C functions into tests, which imho are a no-go.
Any ideas?

**Comment by Ekopalypse** [comment]
I'm going to fix the failed test.

**Comment by Ekopalypse** [comment]
The misc-tooling and the macos failures seems to be something different.
The time_test.v needs to take daylight saving into account as well and logic must be optimized.

**Pull request merged**
