### PR TITLE
cgen: check for mut var in string (fix #12998)

### LINKED ISSUE #12998: Compile error with heap and mutable structure
**V doctor:**
```
OS: linux, Ubuntu 21.04
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
CC version: cc (Ubuntu 10.3.0-1ubuntu1) 10.3.0

getwd: /var/www/vproject
vmodules: /home/tanguy/.vmodules
vroot: /var/www/vproject/v
vexe: /var/www/vproject/v/v
vexe mtime: 2021-12-30 06:06:15
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 c1711b8.d421f28

Git version: git version 2.30.2
Git vroot status: weekly.2021.52.1-14-gd421f28d
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 3654d6a8

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg /var/www/vproject/test/bug_pointer_struct.v`
```v
module main

[heap]
pub struct Grid {
pub mut:
	header      string
}

fn  main() {
    h := 'yo'

    mut grid := Grid{			
        header: h
    }
    wrap_text(mut grid)
}

fn wrap_text(mut gv Grid) {

    for mut ch in gv.header {
        println(ch)
    }
}
```

**What did you expect to see?**

An error with an explicit message.

**What did you see instead?**
```
==================
/tmp/v_1000/bug_pointer_struct.14112127675656446510.tmp.c:10919: error: pointer expected
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR check for mut var in string (fix #12998).

- Check for mut var in string.
- Add test.

```vlang
module main

[heap]
pub struct Grid {
pub mut:
	header string
}

fn main() {
	h := 'yo'

	mut grid := Grid{
		header: h
	}
	wrap_text(mut grid)
}

fn wrap_text(mut gv Grid) {
	for mut ch in gv.header {
		println(ch)
	}
}

PS D:\Test\v\tt1> v run .
.\tt1.v:19:6: error: string type is immutable, it cannot be changed
   17 | 
   18 | fn wrap_text(mut gv Grid) {
   19 |     for mut ch in gv.header {
      |         ~~~
   20 |         println(ch)
   21 |     }
.\tt1.v:20:3: error: `println` can not print void expressions
   18 | fn wrap_text(mut gv Grid) {
   19 |     for mut ch in gv.header {
   20 |         println(ch)
      |         ~~~~~~~~~~~
   21 |     }
   22 | }
```

### CODE REVIEW

**Comment by spytheman** [comment]
`string` values are not mutable in V, the above code provides a way to circumvent that without using `unsafe{}`
@medvednikov what do you think, should that be allowed?

**Comment by yuyi98** [comment]
Do we check that this is illegal?

**Comment by spytheman** [comment]
> Do we check that this is illegal?

Yes, that is one possibility, if Alex decides that it should be disallowed.

**Comment by medvednikov** [comment]
Yes, `for mut ch in mystring {` should not compile.

**Comment by yuyi98** [comment]
OK, `string type is immutable, it cannot be changed`, is it ok?

**Pull request merged**
