### PR TITLE
all: make type of `mut` function args and loop values consistent

### LINKED ISSUE #11038: Arithmetic in mutating for loop works on pointers
**V version:** V 0.2.2 66bc8bc.0ebad47
**OS:**  OS: linux, "Manjaro Linux"

**What did you do?**

```v
fn main(){
	mut ints_a := [1,2]
	for mut i in ints_a {
		j := 0 + i //NB j:= i + 0, works correctly!
		i = j
	}
	print("$ints_a")
}
```

**What did you expect to see?**

```
[1,2]
```
 
**What did you see instead?**

(array with pointers to ints)
```
[11122432, 11122436]
```

### PR DESCRIPTION
**Pull request by UweKrueger**
Function arguments, receivers and `for` loop variables that are declared `mut` are references behind the scenes. However it is not clear what their logical type is, i.e. if the behave like values or like references. The present state is like this:
```v
fn f(mut y St) &St {
    println(typeof(y).name) // -> &St
    mut x := y // `y` behaves like a value, i.e. `x` is of type `St`
    mut z := [y] // again `y` behaves like a value, i.e. `z` is of type []St
    return y // here `y` behaves like a reference (`return &y` would not be allowed)
}
```
This is an inconsistent behaviour, which is made possible by a bunch of exceptions in `checker` and `cgen`.

This PR changes the state of `mut` arguments so that they are logically pure values. In particular `typeof(y).name` would become `St` and `return &y` would be required. This eventually reduces the number of exceptions required in `checker` and limits them to `cgen`. (At the present state there *are* some exception that had to be introduced in `checker` to make existing code continue to work, but these will become warnings and can be removed later.)

This fixes #11038.

### CODE REVIEW

**Comment by SleepyRoy** [comment]
@yuyi98

**Comment by UweKrueger** [comment]
After discussing the issue with @yuyi98 in #10541 I've resumed work on this PR.
The test cases basically work, however examples need some adjustments &ndash; and of cause this is a breaking change so existing code will have to be adjusted, too.
Even though this PR removes some of @yuyi98's work his contributions were valuable since they contain a lot of test cases for `mut` arguments/for loop variables and the make the switch to the new behaviour significantly less hard.

**Comment by yuyi98** [comment]
@UweKrueger   Thanks!  You did a great job, I really admire you!

**Comment by yuyi98** [comment]
@UweKrueger  I hope the conflict can be resolved as soon as possible and the merger can take place as soon as possible!

**Comment by JalonSolov** [comment]
Only CI failure was in  MacOS compiling V UI - that's been fixed now, hasn't it?

Taking care of the conflicts should allow this to be ready to merge.

**Comment by UweKrueger** [comment]
> Taking care of the conflicts should allow this to be ready to merge.

@JalonSolov Unfortunately it's not that trivial. A lot of code has been contributed in the last few weeks that causes semantic conflicts.
In particular there has been significant progress in the JS-backend (thanks to @playXE :+1:) that was done with the old behaviour in mind.
For this reason I'm reconsidering my approach: Even though the checker does its checks with the logical types it should be somehow possible to put the low-level type into the AST. That would minimize the changes in the backends...

**Comment by danieldaeschle** [comment]
Any progress? :/

**Pull request closed without merging**
