### PR TITLE
vweb: prohibit invalid parameter types in vweb app methods

### LINKED ISSUE #10442: passing non string parameter to a vweb endpoint function
**V doctor:**
```
OS: macos, macOS, 11.4, 20F71
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 12.0.5 (clang-1205.0.22.9)

getwd: /Users/jupiter/workbench/v/vhttp
vmodules: /Users/jupiter/.vmodules
vroot: /Users/jupiter/pkg/v
vexe: /Users/jupiter/pkg/v/v
vexe mtime: 2021-06-13 13:25:45
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 cab054c

Git version: git version 2.30.1 (Apple Git-130)
Git vroot status: weekly.2021.23-76-gcab054c1
.git/config present: true
thirdparty/tcc status: thirdparty-unknown-unknown de82a130
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg main.v`
```v
import vweb
import net.http

struct App {
	vweb.Context
}

fn (mut app App) send_data(st http.Status) vweb.Result {
     return app.text("data")
}

fn main() {
	mut app := App{}
	vweb.run(app, 8080)	
}

```

**What did you expect to see?**

V compiler error

**What did you see instead?**

C compiler error
```
==================
/tmp/v/test.15634057559668031550.tmp.c:21299:32: error: passing 'string' (aka 'struct string') to parameter of incompatible type 'net__http__Status'
                                                main__App_send_data(app, ((string*)method_args.data) [0]  ); // vweb action call with args;
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/v/test.15634057559668031550.tmp.c:3660:84: note: passing argument to parameter 'st' here
VV_LOCAL_SYMBOL vweb__Result main__App_send_data(main__App* app, net__http__Status st);
                                                                                   ^
1 error generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

### PR DESCRIPTION
**Pull request by shadowninja55**
this pr prohibits invalid parameter types in vweb app methods. fixes #10442.

### CODE REVIEW

**Comment by shadowninja55** [comment]
i need to improve this to allow more types than string, just not all.

**Comment by shadowninja55** [comment]
this check should definitely be made better and moved to the compiler if possible, should be done tomorrow.

**Comment by mcastorina** [comment]
Instead of panicking, would it be better to ignore a method if one of its arguments is not supported as a URL param?

In other words, `/register/:user` is a route and `/do_register` is not.

```v
fn (mut app App) do_register(user User) vweb.Result {}

['/register/:user']
fn (mut app App) register(user string) vweb.Result {
    return app.do_register(User{user})
}

**Comment by medvednikov** [comment]
ints should be allowed as well, perhaps floats too

**Pull request merged**
