### PR TITLE
mssql: windows support

### PR DESCRIPTION
**Pull request by youyuanwu**
Fixes https://github.com/vlang/v/issues/10312

Use mssql module on windows.

~~tcc compiler is not supported.~~

Example program runs success.

### CODE REVIEW

**Comment by spytheman** [comment]
What is needed for tcc to work too?
Can it work with another C compiler, like the ones from https://winlibs.com/ ?

Unlike msvc (which is huge), we do supply prebuild versions of tcc, so if it can be made to work with it, it will benefit many people that for one reason or another do not have or do not want msvc.

**Comment by youyuanwu** [comment]
One lazy way is to ask people to copy the required dll and headers from windows sdk to v/thirdparty/mssql dir, and add the search path. I haven't tried and not sure if it will work.

The other way is in v builder for tcc, search for windows sdk path and figure out all include dir and dll dir. The v builder code for msvc does some logic to find out system headers, the process should be similar.

**Comment by spytheman** [comment]
How does it work for msvc?

**Comment by youyuanwu** [comment]
I guess for msvc, windows sdk directories are included automatically in search paths by the tool chain?

cl.exe flags are this:
```
-std=gnu99 -o "xxx\\mssql_test.exe" "xxx\\mssql_test.exe.13575218060043431084.tmp.c" -municode -ldbghelp -ladvapi32 -lodbc32
```

**Comment by JalonSolov** [comment]
msvc likely looks at the plethora of environment variables set up by the install.

**Comment by youyuanwu** [comment]
`tcc` works after following the instructions to copy headers in mssql readme.

**Pull request merged**
