### PR TITLE
math: digits panic for invalid base

### PR DESCRIPTION
**Pull request by darenliang**
If base is less than 2, it should panic.

### CODE REVIEW

**Comment by fritzblue** [comment]
Tests?

**Comment by darenliang** [comment]
Is there a way to assert panic errors?

**Comment by fritzblue** [comment]
@medvednikov I see you merged without tests in place. Something as basic as a language's math lib seems critical to have under full test coverage. Am I missing something?

**Comment by darenliang** [comment]
Normally, tests are needed for changes to libraries. However, this covers a panic error which cannot be easily checked with regular tests.

I think the only way to detect panic errors is to run a repl test and those are only found in the compiler module.

**Pull request merged**
