### PR TITLE
tutorials: create scraping and responsive page using multilingual veb

### PR DESCRIPTION
**Pull request by Ddiidev**
Simple tutorial of a responsive page using veb + htmx for scraping on amazon and instant gaming, in addition to being multilingual.

image

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY4MWNjYWYxNDRmNTg1YWU0ZWM3M2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.CtntCSYzvC28zkY8SXD8GxGlVwU_Jl8JqtCQAFsGEiA">Huly&reg;: <b>V_0.6-21674</b></a></sub>

### CODE REVIEW

**Comment by spytheman** [comment]
There is no need to merge master constantly, especially if you are doing an example/tutorial, that does not change vlib, and is unlikely to be affected to recent changes.

**Comment by spytheman** [comment]
In my opinion, that is too big and specialized to be of general value to all V users, and to be merged in the main V repository.

It can be its own repo though, linked in https://github.com/vlang/awesome-v .

**Comment by spytheman** [comment]
@medvednikov what do you think?

**Comment by enghitalo** [comment]
@Ddiidev A very short version would be cool

**Comment by spytheman** [comment]
A tutorial to me, is a guide, that has steps, where you evolve a solution little by little, with explanations on each step, not a complete application.

The goal of a tutorial, is to teach people how to approach a particular problem, so that they can then do it on their own, following on the explained steps.

**Comment by Ddiidev** [comment]
As per @spytheman's suggestion, I will close the PR, and create a repo to request an add to awesome, thanks!

**Pull request closed without merging**
