### PR TITLE
ci: fix vinix_ci.yml for latest Vinix commits

### PR DESCRIPTION
**Pull request by mintsuki**
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMwMThjYWU3Y2M1YTc4NTQyYTRlYTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.DiL5Fy-G6eWkpJXzSZyZw3GIAB0aqPjyxqB0X7I_0KY">Huly&reg;: <b>V_0.6-21263</b></a></sub>

### CODE REVIEW

**Comment by mintsuki** [comment]
V does not seem to like `-ldflags ""`, hence the CI failing. That seems to be a V bug?

**Comment by spytheman** [comment]
That is weird 🤔. Just tried this on a mac, it seems to work locally:
```
0[11:39:36]@m1: (master) /opt/v $ ./v -ldflags "" examples/hello_world.v
0[11:39:47]@m1: (master) /opt/v $ ./v -ldflags "" examples/2048/
0[11:40:07]@m1: (master) /opt/v $ ls -la examples/hello_world examples/2048/2048
-rwxr-xr-x@ 1 delyanangelov  staff  1874376 Nov 10 11:40 examples/2048/2048
-rwxr-xr-x@ 1 delyanangelov  staff   430040 Nov 10 11:39 examples/hello_world
0[11:40:17]@m1: (master) /opt/v $
```

**Comment by spytheman** [comment]
I'll try with the make invocation from the PR on my linux PC.

**Comment by spytheman** [comment]
Everything passed locally on linux too, including the equivalent of this (which the CI indicated to be failing 🤔):
```
#0 14:16:41 ^ vinix-ci-fixes ~/code/v>cd ./vinix/util-vinix/chsh
#0 14:16:44 ^ main ~/code/v/vinix/util-vinix/chsh>VCROSS_COMPILER_NAME="cc" v -os vinix -gc none -cflags "-Ulinux -U__linux -U__linux__ -U__gnu_linux__ -D__vinix__ -O2 -g -pipe" -ldflags "" .
#0 14:17:11 ^ main ~/code/v/vinix/util-vinix/chsh>
```

**Comment by spytheman** [comment]
I think it is fixed in the latest commits in the vinix repo.

**Comment by mintsuki** [comment]
> Everything passed locally on linux too, including the equivalent of this (which the CI indicated to be failing 🤔):
> 
> ```
> #0 14:16:41 ^ vinix-ci-fixes ~/code/v>cd ./vinix/util-vinix/chsh
> #0 14:16:44 ^ main ~/code/v/vinix/util-vinix/chsh>VCROSS_COMPILER_NAME="cc" v -os vinix -gc none -cflags "-Ulinux -U__linux -U__linux__ -U__gnu_linux__ -D__vinix__ -O2 -g -pipe" -ldflags "" .
> #0 14:17:11 ^ main ~/code/v/vinix/util-vinix/chsh>
> ```

Yeah, sorry, I forgot to mention that it only happens in combination with `-prod`.

**Comment by mintsuki** [comment]
@spytheman

**Comment by spytheman** [comment]
It needs also VFLAGS to be set. I think I have a fix in a local branch. I'll test and push the fix.

**Pull request merged**
