### PR TITLE
main.v: Use gmake in update_v() for FreeBSD

### PR DESCRIPTION
**Pull request by sunnylcw**
The latest Makefile does not work with FreeBSD's built-in make.  Need to use gmake (GNU make) instead

### CODE REVIEW

**Comment by joe-conigliaro** [comment]
@sunnylcw Can you have a look at my comment at the bottom if this PR, see what you think. I think instead of getting people to install gmake we should have it so make works.

**Comment by sunnylcw** [comment]
@joe-conigliaro Have replied in #1953.  Please close this request.  Thank you

**Comment by joe-conigliaro** [comment]
Thanks for taking  alook @sunnylcw maybe we should leave it open for @medvednikov to give his opinion?

**Comment by sunnylcw** [comment]
@joe-conigliaro Sure.

**Comment by medvednikov** [comment]
https://github.com/vlang/v/pull/1953

**Pull request closed without merging**
