### PR TITLE
checker: minor cleanup in cast_expr()

### PR DESCRIPTION
**Pull request by yuyi98**
This PR makes a minor cleanup in cast_expr().

- Remove  redundant conditional.

### CODE REVIEW

**Comment by spytheman** [comment]
We do not have a test for that message 🤔 . 
May be it is redundant now ... can the check be removed entirely, or is there a situation, where it would prevent an error?

**Comment by yuyi98** [comment]
It cannot removed entirely, that will be error in tests.

**Comment by spytheman** [comment]
> It cannot removed entirely, that will be error in tests.

I tried modifying the error message, and none of the tests failed. I think we need to add a test for it.

**Comment by yuyi98** [comment]
OK, I'll add a test for it.

**Comment by yuyi98** [comment]
Is the following test ok?

```vlang
type Foo = string

fn main() {
	a := Foo('hello')
	b := byte(a)
	println(b)
}

PS D:\Test\v\tt1> v run .
.\tt1.v:5:7: error: cannot cast type `Foo` to `byte`
    3 | fn main() {
    4 |     a := Foo('hello')
    5 |     b := byte(a)
      |          ~~~~~~~
    6 |     println(b)
    7 | }
```

**Comment by spytheman** [comment]
> Is the following test ok?

Yes, it matches the error message.

**Comment by spytheman** [comment]
```v
type SAlias = string

type CAlias = char
type IAlias = int
type UAlias = u32
type FAlias = f32

fn main() {
    // should be errors:
    _ := byte('hello')
    _ := byte(SAlias('hello'))

    // This should be allowed:
    _ := byte(char(1))
    _ := byte(int(1))
    _ := byte(u32(1))
    _ := byte(f32(1.0))
    //
    _ := byte(CAlias(1))
    _ := byte(IAlias(1))
    _ := byte(UAlias(1))
    _ := byte(FAlias(1))
}
```

**Comment by spytheman** [comment]
i.e. I think that a `byte()` cast should be valid for numbers, runes, and their aliases, and invalid for everything else.

**Comment by spytheman** [comment]
Anyway, that could be done in another PR, this one is good as it is imho. 
Good work!

**Comment by yuyi98** [comment]
OK, Thanks!!!

**Comment by yuyi98** [comment]
Whether enum types should also be allowed?

**Pull request merged**
