### PR TITLE
http: proper support for the plain http protocol.

### PR DESCRIPTION
**Pull request by spytheman**
Tested by:
```
import http
response := http.get('http://google.com/robots.txt') or { panic(err) }
println(response.text)
```
which previously did
```
V panic: println(NIL)
```

### CODE REVIEW

**Comment by spytheman** [comment]
Closed and reopened to trigger a new travis build.

The first travis build failed for linux : https://travis-ci.org/vlang/v/jobs/574684180 for some reason:
```
E: Unable to locate package libglfw3
E: Unable to locate package libglfw3-dev
apt-get.diagnostics
apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install gcc-5 g++-5 make libglfw3 libglfw3-dev libfreetype6-dev libssl-dev" failed and exited with 100 during .
Your build has been stopped.
```

**Comment by joe-conigliaro** [comment]
This still isn't going to work on windows, purely https only at the moment. Will try get it fixed soon

**Comment by spytheman** [comment]
@joe-conigliaro hm, it does seem to work in my win10 vm:
win10 http

**Comment by spytheman** [comment]
I've compiled it with 
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

**Comment by joe-conigliaro** [comment]
It might work if the http redirects to a https, ill check whats going on there. It deff wont work with just http though as all the https stuff is hard coded

**Comment by spytheman** [comment]
You are right - my test url does redirect from http to https.

**Comment by joe-conigliaro** [comment]
even without the redirect it would still work as it would still be connecting on 443.

I dont think it should be too much work to separate out the https stuff and just do the handshake/decryption on https requests.

**Comment by spytheman** [comment]
I'll have a look this afternoon.

**Comment by spytheman** [comment]
I am still testing the windows version, please do not merge yet.

**Comment by spytheman** [comment]
I've tested on both linux and windows. 

The http client works fine on both linux and windows.

------------------------------------------------------

The https client works fine on linux for all sites, that I have tested:
https://url4e.com/robots.txt 
https://github.com/robots.txt
https://google.com/robots.txt

The https client works fine on windows for url4e.com and google.com.

The https client does NOT work for github.com for some reason that is not relevant to this PR. I'll file a separate issue for that.

Test program:
==========================================
```
import http
import os
fn main(){
        println(os.args)
        url := os.args[1]
        response := http.get( url ) or { panic(err) }
        println('body:')
        println(response.text)
        println('body length: $response.text.len')
        println('status code: $response.status_code')
}
```

**Comment by medvednikov** [comment]
Thanks!

Can you please add a couple of http and https tests? 

Just run get on some public websites/endpoints. Like `https://vlang.io/utc_now`

**Comment by spytheman** [comment]
Done. 
Results on windows: 
http.get test results on windows

Results on linux:
http.get test results on windows

**Comment by spytheman** [comment]
On windows, https://github.com/ fails, but https://github.com/robots.txt is ok.

**Comment by joe-conigliaro** [comment]
@spytheman thanks

**Pull request merged**
