### PR TITLE
Add V Scientific Library to vlib

### PR DESCRIPTION
**Pull request by ulises-jeremias**
[Mentioned in Awesome V](https://github.com/vlang/awesome-v/blob/master/README.md#scientific-computing) [Documentation Status](http://vsl.readthedocs.io/en/stable/?badge=stable) [License: MIT](https://opensource.org/licenses/MIT)

# V Scientific Library v0.2

A pure-V scientific library with a great variety of functions.

## Docs

Visit [vsl docs](https://vsl.readthedocs.io/en/stable/) to know more about the supported features on VSL **v0.2**.

### CODE REVIEW

**Comment by Delta456** [comment]
We do not need `v.mod` file and does this have to merge with vlib?

**Comment by joe-conigliaro** [comment]
@ulises-jeremias Nice work!
I'm thinking this might be a better suited as a 3rd party module. 
What are your thoughts @medvednikov.

**Comment by Delta456** [comment]
Agreed with @joe-conigliaro

**Comment by penguindark** [comment]
A beautiful and well documented lib, my congratulations! :+1: 
Anyway I agree with @joe-conigliaro, best suited as third party.

**Comment by changrui** [comment]
`v install https://github.com/ulises-jeremias/vsl`.

**Comment by medvednikov** [comment]
We decided to use https://github.com/vlang/vsl instead

**Pull request closed without merging**
