### PR TITLE
parser: give a separate error for invalid string prefix and more

### PR DESCRIPTION
**Pull request by Delta456**

### CODE REVIEW

**Comment by JalonSolov** [comment]
Looks good.  Of course, one more thing occurs to me... should you go ahead and check for `jsr`, `jsc` and `jsrc`?

In other words, cover all the possibilities, in any order, just in case.

**Comment by JalonSolov** [comment]
Might be easier to just check for explicit either `r`, `c`, or `js`, and if _anything_ else, just show "invalid string prefix" error.

**Comment by Delta456** [comment]
I am pretty sure that no one will use `jsc`, `jsrc` and `jscr`. I can add a separate message for `jsr` and `rjs` though.

**Comment by JalonSolov** [comment]
Well, a lot  of people are "pretty sure" that nobody will ever use `rc` or `cr`... so if you're adding an error message at all, it should likely be something that will catch all possible cases.

**Pull request merged**
