### PR TITLE
Tutorial: Change speed to agility

### PR DESCRIPTION
**Pull request by ylluminate**
Speed has a connotation of performance and so using speed of Python seems contradictory + you use performance just afterwards. Agility matches the intention better and for those of us who think of Ruby instead of Python for agility is just a little more icing. :)

### CODE REVIEW

**Comment by sudo-nice** [comment]
>agility

Good find!

>agility of Ruby

That's a bold statement :smile: Even Crystal (which tries to be as expressive as Ruby) is more verbose, because static types bring their limits. Maybe, it's better not to promote V to be "as agile as Ruby", otherwise it can lead to disappointment.

**Comment by ylluminate** [comment]
Hahaha, well, we work in Ruby professionally so I feel as though I do have some reasoning for adding this.  It can be argued that it is...  Frankly I love Ruby, but the "one way" methodology of V and so many other aspects make it attractive and arguably more powerful and agile than Ruby since it reduces certain considerations.  Hmmm, I don't mind taking off Ruby though.

**Comment by medvednikov** [comment]
@sudo-nice having to do an extra couple of keystrokes doesn't mean it's slower to develop.

For example, how many unit tests do you have to write to test types in Ruby?

Or how much time to spend to refactor some types or chase runtime only bugs that are caught at compilation in V?

**Comment by sudo-nice** [comment]
@medvednikov don't get me wrong, I like V and I don't deem it to be slow in general. But can we honestly pair it with a dynamically typed language, especially that expressive as Ruby? I don't think so, because V, being a statically typed language, has its limitations.

>For example, how many unit tests do you have to write to test types in Ruby? Or how much time to spend to refactor some types or chase runtime only bugs that are caught at compilation in V?

It's hard to tell, because there are too many factors to count here, namely, the size of application, the coding style, experience of the coder.

But if we take a simple task, it would be easier to compare. For example, this snippet in ruby represents natural sorting of strings. If one tried to solve that task in V, it would be more verbose, I guess.


```ruby
%w[foo 1foo 10foo 2foo bar].sort_by do |item|
  item.split(/(\d+)/).map.with_index do |chunk, idx|
    idx.even? ? chunk : chunk.to_i
  end
end # => ["1foo", "2foo", "10foo", "bar", "foo"]
```

**Comment by medvednikov** [comment]
I've worked with lots of dynamic languages, including Ruby.

What are the limitations except eval, which should not be used and magic like method_missing (same)

**Comment by medvednikov** [comment]
`sort()` will be improved, similar to what we have with `filter()` and `map()` right now, it'll be just as clean and simple.

**Pull request merged**
