### PR TITLE
Made generics more stable

### LINKED ISSUE #9491: Infering type in recursive generics causes c error
**V version:** 
V 0.2.2 76dc4cf
**OS:** 
linux, Pop!_OS 20.10
**What did you do?**
```v
fn a<T>(b T) {
	c(b)
}

fn c<T>(d T) {
    println(d)
}

fn main() {
	a(9)
}
```

changing line `2` to `c<T>(b)` fixes the problem
**What did you expect to see?**
`9`
 
**What did you see instead?**
```v
/tmp/v/test.15849291661070945650.tmp.c:1511: error: ',' expected (got "d")
builder error:
==================
C error. This should never happen.
```

It tries to create an instance with type T (in the c code), but that type does not exist in the eyes of the c compiler:
```c
void main__a_T_int(int b);
void main__c_T_T(T d); // "T doesn't exist!" is what the c compiler means
```

### PR DESCRIPTION
**Pull request by ZargorNET**
- Added following check image
- Fixed #9491
- Fixed 
image to this 
image

<del>The third point actually just works for functions right now and not for methods. Also, it requires to call it in the for loop which is not performant, because when setting my change above the for loop, V panics. So maybe we have to rewrite the `infer_fn_types` method so that it does only process the current argument.
And some tests are currently failing as well
So 3 things to do</del>

### CODE REVIEW

**Comment by ZargorNET** [comment]
The failing generics test has something to do with point 3

**Comment by nedpals** [comment]
Format your code so that code-formatting CI will be happy :smiley:

**Comment by ZargorNET** [comment]
Will do, after I fix point 3

**Comment by medvednikov** [comment]
Thanks and welcome!

There's one conflict, I'll merge it asap once it's fixed.

**Comment by ZargorNET** [comment]
@medvednikov Thanks! And I resolved the conflicts

**Pull request merged**
