### PR TITLE
pointer_array

### PR DESCRIPTION
**Pull request by lcddh**
This PR let array can hold pointer type(*SomeSturct)!!
next can add FN type,and let map support it !!
```
fn main() {
    mut arr := [] *int
    i := 100
    pi := &i
    n := 1000
    n3 := 10000
    arr << pi
    arr << &n
    arr << &n3
    for ii,var in arr {
        print(ii)
        print(' ')
        println(*var)
    }
    for var in arr {
        println(*var)
    }
}
```

### CODE REVIEW

**Comment by medvednikov** [comment]
Why did you remove `no need to specify the full array type here, use []` error?

**Comment by lcddh** [comment]
I don't quite understand the function of this code, so I won't report an error until I delete it, so I'll try to delete it temporarily.

**Comment by medvednikov** [comment]
This error can't be removed.

**Comment by lcddh** [comment]
@medvednikov the error check is back

**Pull request merged**
