### PR TITLE
checkr,ast: cleanup code about deprecated

### PR DESCRIPTION
**Pull request by zakuro9715**
remove duplicated code

### CODE REVIEW

**Comment by spytheman** [comment]
Do not remove the deprecation message support for struct fields; if you do refactoring PRs, they should be as single purpose as possible.

**Comment by zakuro9715** [comment]
@spytheman This PR don't remove deprecation message support. deprecation_msg field is removed but messages is stored as attribute arg and use it in `Checker.deprecate()`

There are tests of deprecation message. This PR don't change any test.

https://github.com/zakuro9715/v/blob/c145fd87946445823d20236664f325c5d4aca190/vlib/v/checker/tests/module_with_structs_with_deprecated_fields/fields.v#L3-L9

https://github.com/zakuro9715/v/blob/c145fd87946445823d20236664f325c5d4aca190/vlib/v/checker/tests/deprecations.vv#L10-L15

**Comment by zakuro9715** [comment]
attrs stored here: https://github.com/vlang/v/blob/14fcc081a525ababa2037aa7888f4132b1705cf3/vlib/v/parser/struct.v#L284
And used here: https://github.com/vlang/v/blob/14fcc081a525ababa2037aa7888f4132b1705cf3/vlib/v/checker/checker.v#L1237
https://github.com/vlang/v/blob/14fcc081a525ababa2037aa7888f4132b1705cf3/vlib/v/checker/checker.v#L3865-L3867

**Comment by spytheman** [comment]
> @spytheman This PR don't remove deprecation message support. deprecation_msg field is removed but messages is stored as attribute arg and use it in `Checker.deprecate()`

You are right. My bad. Good work.

**Pull request merged**
