### PR TITLE
cgen: remove ull, which will cause compile error?

### PR DESCRIPTION
**Pull request by kbkpbot**
```sh
make fresh_vc
make[1]: Entering directory '/home/runner/work/v/v'
rm -rf ./vc
git clone --filter=blob:none --quiet https://github.com/vlang/vc ./vc
make[1]: Leaving directory '/home/runner/work/v/v'
cd ./vc && git clean -xf && git pull --quiet
make fresh_tcc
make[1]: Entering directory '/home/runner/work/v/v'
rm -rf ./thirdparty/tcc
git clone --filter=blob:none --quiet --branch thirdparty-linux-amd64 https://github.com/vlang/tccbin ./thirdparty/tcc
make[2]: Entering directory '/home/runner/work/v/v'
make[2]: Leaving directory '/home/runner/work/v/v'
make[1]: Leaving directory '/home/runner/work/v/v'
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread 
./v1.exe -no-parallel -o v2.exe  cmd/v
vlib/v/gen/c/cheaders.v:839:52: error: this hexadecimal number has unsuitable digit `u`
  837 | }
  838 | // the default secret parameters
  839 | static const uint64_t _wyp[4] = {0xa0761d6478bd642full, 0xe7037ed1a0b428dbull, 0x8ebc6af09c88c6e3ull, 0x589965cc75374cc3ull};
      |                                                    ^
  840 | 
  841 | // a useful 64bit-64bit mix function to produce deterministic pseudo random numbers that can pass BigCrush and PractRand
make: *** [GNUmakefile:114: all] Error 1
Error: Process completed with exit code 2.
```

### CODE REVIEW

**Comment by spytheman** [comment]
What is the environment, where you experience this error?

**Comment by JalonSolov** [comment]
If I'm reading this correctly...

`ull` is a C-ism, declaring the variable to be type `unsigned long long`.

`0xa0761d6478bd642full` should be replaced with `u64(0xa0761d6478bd642f)`

**Comment by JalonSolov** [comment]
No, it's not supported in all C compilers, especially older ones.  Or possibly 32-bit ones?  It's hard to tell, without checking the specific version of docs for each compiler.

**Comment by spytheman** [comment]
I think that there is a bug in https://github.com/vlang/v/pull/20726 , due to which, after some bootstrapping stages, the V scanner then tries to parse those strings, that contain the literals, as V numbers, but they are not.

**Comment by spytheman** [comment]
I'll merge this, since all the tests passed, and it has the potential to unblock #20726, or at least reveal more details for the problem that I suspect is there.

**Pull request merged**
