### PR TITLE
parser: restrict optional struct field

### PR DESCRIPTION
**Pull request by Tarang11**
fix for issue #5796

### CODE REVIEW

**Comment by JalonSolov** [comment]
You have to fix this test as well:
```
vlib/v/tests/option_test.v:185:8: error: cannot define `optional` struct field 
  183 |     name  string
  184 |     age   int
  185 |     title ?string
      |           ^
  186 | }
  187 |
```

**Comment by Tarang11** [comment]
@JalonSolov, i didn't get use of optional struct field. Can you elaborate it, pls.

**Comment by JalonSolov** [comment]
That's the error that is causing all the checks to fail.

**Comment by spytheman** [comment]
This PR does not fix anything, instead it produces an error for a planned feature. I do not see how that is helpful?

**Comment by Tarang11** [comment]
@spytheman, well using optional in struct field gives C builder error right now. If optional field implementation are reserved for  future its ok. This PR will prevent optional field in struct. Failed test are due to use of optional field in option_test.v. If optional struct field are allowed in V then we need to handle it differently.

**Pull request closed without merging**
