### PR TITLE
Add documentation with new v.c repository

### PR DESCRIPTION
**Pull request by AurelienFT**

### CODE REVIEW

**Comment by medvednikov** [comment]
But why complicate this?

vlang.io/v.c is always going to have the latest build.

**Comment by AurelienFT** [comment]
Ok i close I didn't you gonna maintain vlang.io/v.c

**Comment by whoizit** [comment]
it should not be vlang.io/v.c it's security hole. The server can be compromised at any time. PR is going to right way, It should be sourced from git with vlang/v

**Comment by whoizit** [comment]
when it is hacked there will be terrible consequences for the reputation

**Comment by AurelienFT** [comment]
Alex said on Discord : "v.c will be deployed with binaries via github instead"
So I reopen.

**Comment by AurelienFT** [comment]
Close in favor of this : https://github.com/vlang/v/commit/a0dbee7e452f58c5259d8e29d4a47b7c865c014c

**Pull request closed without merging**
