### PR TITLE
checker: check fixed array builtin method args mismatch

### PR DESCRIPTION
**Pull request by yuyi98**
This PR check fixed array builtin method args mismatch.

- Check fixed array builtin method args mismatch.
- Add test.

```v
fn main() {
	arr := [1, 2, 3]!

	_ := arr.index()
	_ := arr.index('hello')
	_ := arr.contains()
	_ := arr.contains('hello')
	_ := arr.any()
	_ := arr.any(22)
	_ := arr.all()
	_ := arr.all('hello')
}

PS D:\Test\v\tt1> v run .      
tt1.v:4:11: error: `.index()` expected 1 argument, but got 0
    2 |     arr := [1, 2, 3]!
    3 | 
    4 |     _ := arr.index()
      |              ~~~~~~~
    5 |     _ := arr.index('hello')
    6 |     _ := arr.contains()
tt1.v:4:4: error: assignment mismatch: 1 variable but `index()` returns 0 values
    2 |     arr := [1, 2, 3]!
    3 | 
    4 |     _ := arr.index()
      |       ~~
    5 |     _ := arr.index('hello')
    6 |     _ := arr.contains()
tt1.v:5:17: error: cannot use `string` as `int` in argument 1 to `.index()`
    3 | 
    4 |     _ := arr.index()
    5 |     _ := arr.index('hello')
      |                    ~~~~~~~
    6 |     _ := arr.contains()
    7 |     _ := arr.contains('hello')
tt1.v:5:4: error: assignment mismatch: 1 variable but `index()` returns 0 values
    3 | 
    4 |     _ := arr.index()
    5 |     _ := arr.index('hello')
      |       ~~
    6 |     _ := arr.contains()
    7 |     _ := arr.contains('hello')
tt1.v:6:11: error: `.contains()` expected 1 argument, but got 0
    4 |     _ := arr.index()
    5 |     _ := arr.index('hello')
    6 |     _ := arr.contains()
      |              ~~~~~~~~~~
    7 |     _ := arr.contains('hello')
    8 |     _ := arr.any()
tt1.v:6:4: error: assignment mismatch: 1 variable but `contains()` returns 0 values
    4 |     _ := arr.index()
    5 |     _ := arr.index('hello')
    6 |     _ := arr.contains()
      |       ~~
    7 |     _ := arr.contains('hello')
    8 |     _ := arr.any()
tt1.v:7:20: error: cannot use `string` as `int` in argument 1 to `.contains()`
    5 |     _ := arr.index('hello')
    6 |     _ := arr.contains()
    7 |     _ := arr.contains('hello')
      |                       ~~~~~~~
    8 |     _ := arr.any()
    9 |     _ := arr.any(22)
tt1.v:7:4: error: assignment mismatch: 1 variable but `contains()` returns 0 values
    5 |     _ := arr.index('hello')
    6 |     _ := arr.contains()
    7 |     _ := arr.contains('hello')
      |       ~~
    8 |     _ := arr.any()
    9 |     _ := arr.any(22)
tt1.v:8:11: error: `.any` expected 1 argument, but got 0
    6 |     _ := arr.contains()
    7 |     _ := arr.contains('hello')
    8 |     _ := arr.any()
      |              ~~~~~
    9 |     _ := arr.any(22)
   10 |     _ := arr.all()
tt1.v:8:4: error: assignment mismatch: 1 variable but `any()` returns 0 values
    6 |     _ := arr.contains()
    7 |     _ := arr.contains('hello')
    8 |     _ := arr.any()
      |       ~~
    9 |     _ := arr.any(22)
   10 |     _ := arr.all()
tt1.v:10:11: error: `.all` expected 1 argument, but got 0
    8 |     _ := arr.any()
    9 |     _ := arr.any(22)
   10 |     _ := arr.all()
      |              ~~~~~
   11 |     _ := arr.all('hello')
   12 | }
tt1.v:10:4: error: assignment mismatch: 1 variable but `all()` returns 0 values
    8 |     _ := arr.any()
    9 |     _ := arr.any(22)
   10 |     _ := arr.all()
      |       ~~
   11 |     _ := arr.all('hello')
   12 | }
tt1.v:11:15: error: type mismatch, should use e.g. `all(it > 2)`
    9 |     _ := arr.any(22)
   10 |     _ := arr.all()
   11 |     _ := arr.all('hello')
      |                  ~~~~~~~
   12 | }
```

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE4YmFjY2YwMmQ4YTAzZmIyZmFlOTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Dgxm_qQaqdTmJFMnKCJaPQ_7CfUmZIjjIHfyDwlo08g">Huly&reg;: <b>V_0.6-21075</b></a></sub>

### CODE REVIEW

**Comment by spytheman** [comment]
>> error: assignment mismatch: 1 variable but `index()` returns 0 values

hm, index() should return 1 value, not 0

**Comment by spytheman** [comment]
>> assignment mismatch: 1 variable but `contains()` returns 0 values
same - contains returns 1 boolean value

**Comment by yuyi98** [comment]
This means  the function returned a void_type value.

**Comment by spytheman** [comment]
I understand that, but the difference, is that in the case of strings, there is no `filter()` method.

In the case of arrays, the methods do exist, and the compiler knows what they should return, and it can provide a more precise error message, based on that information.

**Comment by spytheman** [comment]
Anyway, it is not directly related to the arity checks, that you implemented, and is out of scope of this PR.

Good work.

**Comment by yuyi98** [comment]
Ok, I see.

**Pull request merged**
