### PR TITLE
gg: add the gg.Context.remove_cached_image_by_idx() method

### PR DESCRIPTION
**Pull request by Wertzui123**
This is needed if you want to draw on the screen but cannot use a streaming image (for example, because the window has been resized).
I've tested this and it works.

### CODE REVIEW

**Comment by spytheman** [comment]
Please add a small usage/test example in `vlib/gg/testdata/` in a .vv file, to prevent regressions.

**Comment by Wertzui123** [comment]
Not sure how a test/example for this would look like. 🤔

**Comment by Wertzui123** [comment]
I'll add a test tomorrow.

**Comment by Wertzui123** [comment]
The test doesn't leak even without garbage collection.

**Pull request merged**
