### PR TITLE
checker: check match return mismatch type (fix #6826)

### LINKED ISSUE #6826: optional match got type mismatch error.
**V version:0.1.29 5069be0** 
**OS:archlinux** 

**What did you do?**

```
fn match_error(i int) ?string {
	return match i {
		1 { 'A' }
		2 { 'B' }
		else { error('illegal argument') }
	}
}

fn match_error_with_many_return(i int) ?string {
	match i {
		1 { return 'A' }
		2 { return 'B' }
		else { return error('illegal argument') }
	}
}

fn main() {
	res := match_error(3) or {
		println(err)
		return
	}
	println(res)
}
```

**What did you expect to see?**

both function print ...

 ```
illegal argument
```
**What did you see instead?**
match_error() got error 
```
/tmp/v/matcherror.4747058217545655260.tmp.c: 関数 ‘main__match_error’ 内:
/tmp/v/matcherror.4747058217545655260.tmp.c:8049:78: エラー: 条件式での型の組合わせが適合しません　"type mismatch in conditional expression"
 8049 |   Option _t78 = ((_t79 == 1) ? (tos_lit("A")) : (_t79 == 2) ? (tos_lit("B")) : (v_error(tos_lit("illegal argument"))));
````

### PR DESCRIPTION
**Pull request by yuyi98**
This PR check match return mismatch type (fix #6826).

- Check match return mismatch type.
- Add test `checker\tests\match_return_mismatch_type_err.vv/out`.

```v
module main

fn match_error(i int) ?string {
	return match i {
		1 { 'A' }
		2 { 'B' }
		else { error('illegal argument') }
	}
}

fn main() {
	res := match_error(3) or {
		println(err)
		return
	}
	println(res)
}

PS D:\Test\v\tt1> v run .
.\tt1.v:7:10: error: mismatched return type, it should be `string`
    5 |         1 { 'A' }
    6 |         2 { 'B' }
    7 |         else { error('illegal argument') }
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~
    8 |     }
    9 | }
```

### CODE REVIEW

**Comment by spaceface777** [comment]
I don't think this should be an error, they types aren't mismatched.

What this does need is a codegen fix in cgen.

**Comment by yuyi98** [comment]
The point is not here.

```v
fn main() {
	a := match 1 {
		1 { 'aa' }
		else { 22 }
	}
	println(a)
}

PS D:\Test\v\tt1> v run .
.\tt1.v:6:10: error: mismatched return type, it should be `string`
    4 |     a := match 1 {
    5 |         1 { 'aa' }
    6 |         else { 22 }
      |                ~~
    7 |     }
    8 |     println(a)
```

**Comment by spaceface777** [comment]
In that case, the error is correct:

```v
a := match 1 {
	1 { 'aa' }
	else { 22 }
}
```

The reasoning being: *what type would `a` have here?* Type inference won't work here, so an error is a good solution. <sup>unless we make `a` have a type of `string | int` (like a sumtype), but that's not the point I'm trying to make</sup>

***

The example in the original issue is different, though.

```
fn match_error(i int) ?string {
	return match i {
		1 { 'A' }
		2 { 'B' }
		else { error('illegal argument') }
	}
}
```

The type that the last expressions of the `match` branches must have is known (`?string` in this case), and both `'A'` and `error('foo')` are assignable to that type, so there shouldn't be an error.

Similarly, the first example could be changed slightly into this:
```v
type Foo = string | int

mut a := Foo{}
a = match 1 {
	1 { 'aa' }
	else { 22 }
}
```

Again, the type is known here, and both `string` and `int` are assignable to it, so this shouldn't be an error.

**Comment by yuyi98** [comment]
At present, match_return is implemented by means of a ternary conditional operator, so it must be same return type.
What you're saying does exist, and it needs to be improved.

**Comment by JalonSolov** [comment]
`mismatched return type` should be `return type mismatch`

**Pull request merged**
