### PR TITLE
bf: add a module implementing operations with bit arrays

### PR DESCRIPTION
**Pull request by ciubotaru**
This PR implements a set of functions to work with bit arrays

```
// an opaque structure to store the array of bits
struct BitField {...}

// create a new bit array capable to store 'size' bits
pub fn new(size int) BitField {...}

// get the value (0 or 1) of bit number 'bitnr' in a bit array
pub fn (instance Bitfield) getbit(bitnr int) int {...}

// set bit number 'bitnr' to 1
pub fn (instance mut BitField) setbit(bitnr int) {...}

// clear (set to 0) bit number 'bitnr'
pub fn (instance mut BitField) clearbit(bitnr int) {...}

// toggle (from 0 to 1 and vice-versa) bit number 'bitnr'
pub fn (instance mut BitField) togglebit(bitnr int) {...}

// performs bitwise AND over a pair of bitfields
pub fn bfand(input1 BitField, input2 BitField) BitField {...}

// reverse all bits in an array and return the result in a new array
pub fn bfnot(input BitField) BitField {...}

// perform bitwise inclusive OR over a pair of bit arrays
pub fn bfor(input1 BitField, input2 BitField) BitField {...}

// perform bitwise exclusive OR over a pair of bit arrays
pub fn bfxor(input1 BitField, input2 BitField) BitField {...}

// print a bit array as a series of ones and zeroes, least significant bit first
pub fn print(instance BitField) {...}

// get the number of bits an array can hold
pub fn (instance BitField) getsize() int {...}

// create a copy of an existing bit array
pub fn clone(input BitField) BitField {...}

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks.

There's no need to use a pointer, just like with strings:

`pub fn new(size int) *bitfield {`

==>

`pub fn new(size int) bitfield {`

The struct should be capitalized, and methods should be used:

`fn bitclear(instance *bitfield, bitnr int) {`

==>

`fn (b mut BitField) clear(bitnr int) {`

**Comment by ciubotaru** [comment]
@medvednikov, Thank you very much for your feedback. So, if the feature that I am proposing is conceptually acceptable, I will be happy to bring the code up to the standard.

**Comment by ciubotaru** [comment]
Update:
* Structure name capitalized
* Passing struct instead of struct pointer
* Public functions replaced with methods, where appropriate (private helper functions left as is pending further instructions)

**Comment by ciubotaru** [comment]
Oops, I accidentally closed the PR. Hopefully, I can reopen it.

**Comment by ciubotaru** [comment]
@medvednikov, Thank you very much for merging this.

I would like to implement the following features:
* extract sub-array
* concatenate two arrays
* compare two arrays bitwise
* shift/rotate an array
* popcount (nr of set bits)
* Hamming distance
* search for sub-array
* resize
* reverse the order if bits

Looking forward to your feedback.

**Pull request merged**
