### PR TITLE
time: update parse_format comment description in parse.c.v

### PR DESCRIPTION
**Pull request by martinskou**
nicer formating

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by JalonSolov** [comment]
Kinda wish the extra step had happened...
```v
// - YYYY - 4 digit year, 0000..9999
// - YY   - 2 digit year, 00..99
// - M    - month, 1..12
// - MM   - month, 2 digits, 01..12
// - MMM  - month, three letters, Jan..Dec
// - MMMM - name of month
// - D    - day of the month, 1..31
// - DD   - day of the month, 01..31
...
```
Always seems more readable if the data is in a more columnar format.

**Comment by martinskou** [comment]
I will fix it.

--
Martin Skou Drewes | Udviklingschef | Webbureauet Infoserv ApS
T: 87110300 | D: 87110302 | https://infoserv.dk | https://infoserv-hosting.dk

**Comment by martinskou** [comment]
Not sure that its possible to use monospaced font outside of source snippets.

**Comment by JalonSolov** [comment]
You may be correct about that.  Sad.

**Pull request merged**
