### PR TITLE
cgen: Edge case for multi-returns with 1 expr which is a multi-return

### PR DESCRIPTION
**Pull request by emily33901**
Fixes a bug i ran into where i was returning an optional multi return from an optional multi return which wasnt working because it doesnt know how to handle that properly! (and that code is far to complicated right now to just keep adding more edge cases - someone (probably me) needs to go in and try and fix it!)

### CODE REVIEW

**Comment by emily33901** [comment]
I tested this against protoc-v (which i think is a good test case for multi returns because it uses them a lot)

**Comment by medvednikov** [comment]
Can you please add a small test so that this doesn't happen again in the future?

**Comment by joe-conigliaro** [comment]
Im reworking most of the multi assign/return (multi exprs) and simplifying greatly, hopefully Ill have it done soon.

**Comment by medvednikov** [comment]
@emily33901 I'm waiting for Joe to merge his big change today.

**Comment by emily33901** [comment]
O fair that's a better outcome then 


I'm gonna leave this open for now - can one of you make sure that Joe's commit closes mine in the case that everything is guuciii

**Comment by medvednikov** [comment]
Of course

**Comment by joe-conigliaro** [comment]
Hey I will try merge it today :D I'm not 100% sure, in any case Im close :) Just leave this here as my works is 2 part, assignment, and also multi exprs. so It might end up being split in 2 commits

**Comment by joe-conigliaro** [comment]
Hi sorry for the late reply, I'm thinking this should probably be merged, as I ended splitting the work in two and only doing the assignment part thus far which will be merged tomorrow. The other multi expr stuff will seperate (btw the assignment stuff too way way longer than I thought it would). @medvednikov @emily33901

**Pull request merged**
