### PR TITLE
parser: Fix parsing struct attribute on struct field with array type

### PR DESCRIPTION
**Pull request by nedpals**
This fix bypasses the errors for specific peek tokens (`semicolon` and `rsbr`) to be able to use struct attributes on a field with array type.

```
modules\lsp\capabilities.v:65:31: error: unexpected `name`, expecting `]`
   63 | pub struct HoverCapability {
   64 |     dynamic_registration bool [json:dynamicRegistration]
   65 |     content_format []MarkupKind [json:contentFormat]
      |                                  ~~~~
   66 | }
   67 |
```

### CODE REVIEW

**Comment by medvednikov** [comment]
Can you add a small test to test_struct.v?

**Comment by nedpals** [comment]
@medvednikov sure. will do 👍

**Comment by nedpals** [comment]
@medvednikov Should I just declare the struct (with attributes) on `struct_test.v` and do nothing with it?

**Comment by medvednikov** [comment]
Yes

**Comment by nedpals** [comment]
@medvednikov done :)

**Pull request merged**
