### PR TITLE
js: fix codegen for multiline strings

### LINKED ISSUE #6781: Multiline strings in the JS backend
**V version:** V 0.1.29 ba366b1
**OS:** macOS 10.15

**What did you do?**

```
$ cat m.v
fn main() {
	println('hello
world
sweet
boy
')
}
```

Compiling this to C works as expected:

```
$ v run m.v
hello
world
sweet
boy

$
```

But using the js backend is not that nice:

```
$ v -o m.js m.v
$ node m.js
/Users/pancake/prg/v-frida/m.js:79
		builtin.println("hello
		                ^^^^^^

SyntaxError: Invalid or unexpected token
$ tail m.js
/** @namespace main */
const main = (function () {
	/* program entry point */
	(function() {
		builtin.println("hello
world
sweet
boy
");
	})();

	/* module exports */
	return {};
})();


$
```

**What did you expect to see?**

a working program, the code should look like this:

```
		builtin.println("hello\n"+
"world\n"
"sweet\n"
"boy\n"
);
```
 
**What did you see instead?**

invalid js code

### PR DESCRIPTION
**Pull request by trufae**
Fixes #6781

```go
$ cat multi.v
fn main() {
	println('hello
world
sweet
boy
')
}
$ v -b js multi.v ; node multi.js
hello
world
sweet
boy

$ v run multi.v
hello
world
sweet
boy

$
```

### CODE REVIEW

**Comment by spaceface777** [comment]
I think it would be better to move the `smart_quote` function (see #6474) outside of cgen (to `v.util` maybe?), and use it here as well, that would avoid any other potential issues with generated strings.

**Comment by trufae** [comment]
I first implemented this as multiline concatenated strings like this:
```
call("foo\n"
+"bar\n")
```

but i think that just replacing the newline is simpler, otherwise if we do such multiline strings maybe that should be also indented and be more complicated. I can redo this code if desired, as long as the final js will be more readable than a single line with escaped newlines.

**Comment by trufae** [comment]
im also escaping the backtick. and exposing this api. and yeah, maybe better to have it in v.util

**Comment by medvednikov** [comment]
> I think it would be better to move the `smart_quote` function (see #6474) outside of cgen (to `v.util` maybe?), and use it here as well, that would avoid any other potential issues with generated strings.

Yes.

**Comment by trufae** [comment]
Escaping backticks results in zillions of warnings in the C code generated. so dont merge this (yet), not sure if its good to expose and reuse this api instead of just a single line replace() in that case.. because $ variables use backticks in the js backend.. this syntax is from es6.. so we can say V's js requires qjs or v8 to work. duktape wont be able to run that (which im fine, but may be good to specify.. or generate the good old quoted strings)

**Comment by spytheman** [comment]
I think the cgen and jsgen need separate smar escaping output functions; C and JS are different target languages with different (although similar rules)

**Pull request merged**
