### PR TITLE
all: implement function/method with default arguments

### PR DESCRIPTION
**Pull request by yuyi98**
This PR implement function/method with default arguments.

- If we accept this feature, then we can change the following:
`time.new_stopwatch({})`  to `time.new_stopwatch()`
`p.eat_comments({})` to `p.eat_comments()`
`f.remove_new_line({})` to `f.remove_new_line()`
`...`
- To do this, we have to commit in two steps.

```vlang
module main

struct Info {
	age int
}

fn (inf Info) show(a int = 10) {
	if a == 10 {
		println('method: 10')
	} else {
		println('method: other')
	}
}

fn show_info(a int = 10) {
	if a == 10 {
		println('function: 10')
	} else {
		println('function: other')
	}
}

fn main() {
	show_info()
	show_info(2)

	info := Info{}
	info.show()
	info.show(2)
}

D:\Test\v\tt1>v run .
function: 10
function: other
method: 10
method: other
```

### CODE REVIEW

**Comment by Delta456** [comment]
Default Arguments goes against the philosophy of V.

**Comment by yuyi98** [comment]
I think a lot of things like time.new_stopwatch({}) are not neat, the default parameter still has its advantages.

**Comment by spytheman** [comment]
@medvednikov what do you think?

**Comment by medvednikov** [comment]
I'm against it, I'll explain why in details a bit later.

**Pull request closed without merging**
