### PR TITLE
utf8 utils: removed upper,lower table

### PR DESCRIPTION
**Pull request by penguindark**
**What's inside**
- removed the huge char table for upper/lower operations

### CODE REVIEW

**Comment by penguindark** [comment]
@spytheman The code compile and run well but the `test-fmt` has problem with:
```v
 FAIL  [ 314/1149]     5.914 ms v/vlib/encoding/utf8/utf8_util.v
v/vlib/encoding/utf8/utf8_util.v:196:3: error: unexpected token `(`, expecting `{`
  194 |             cp &= ~0x1
  195 |     } else if ((0x0531 <= cp) && (0x0556 >= cp)) || // ARMENIAN
  196 |         ((0x10A0 <= cp) && (0x10C5 >= cp)) {        // GEORGIAN
      |         ^
  197 |             cp += 0x30
  198 |     } else if (((0x1E00 <= cp) && (0x1E94 >= cp)) ||  // LATIN CAPITAL LETTER
```
I've no idea of the cause, can you help?

**Comment by mcastorina** [comment]
Could you measure the before and after of both performance and vlib size? It would make it easier to reason about the pros/cons of these changes.

**Comment by penguindark** [comment]
@mcastorina The tabled version is for sure more performant because it search in a table using a binary search, at max it do log2(668) = 9,4 reads in the table and consecutive if.
The new code remove the big table (668*2 entries) and thus doesn't need to read in memory but on the other size need an average of 30checks with the worst case over 60 if checks.
On the paper the table seems quickest.
I'll do some mode deep tests tomorrow.

**Comment by spytheman** [comment]
> May be the comment at the end of the line transform it in ||//ARMENIAN making for vfmt blind to the || token?
Currently vfmt does not support comments inside boolean expressions.
I've just moved the comments below, inside the `then` blocks.

**Comment by spytheman** [comment]
Here are some tests (vfmt_over_encoding_utf8 is the same as the master branch, just with vfmt run over vlib/encoding/utf8/, because I wanted to compare the source code size too, `utf8` is the branch from the current PR):
```
0[10:06:53]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ wc vlib/encoding/utf8/utf8_util.v 
  2382  16682 102635 vlib/encoding/utf8/utf8_util.v
0[10:06:56]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ ./v -cc tcc -keepc bench_utf8.v
0[10:07:03]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ ls -lart bench_utf8
-rwxrwxr-x 1 delian delian 812568 Apr 11 10:07 bench_utf8
0[10:07:12]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ strip bench_utf8
0[10:07:19]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ ls -lart bench_utf8
-rwxrwxr-x 1 delian delian 723920 Apr 11 10:07 bench_utf8
0[10:07:24]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ xtime ./bench_utf8
 SPENT 24137.648 ms in utf8.to_upper, csum: 66000000 | max_iterations: 1000000
CPU: 23.81s     Real: 24.14s    Elapsed: 0:24.14        RAM: 112060KB   ./bench_utf8
0[10:07:57]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ 
0[10:07:58]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ ./v -keepc -cc gcc-10 -prod bench_utf8.v
0[10:08:06]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ ls -lart bench_utf8
-rwxrwxr-x 1 delian delian 72248 Apr 11 10:08 bench_utf8
0[10:08:09]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ strip bench_utf8
0[10:08:12]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ ls -lart bench_utf8
-rwxrwxr-x 1 delian delian 67720 Apr 11 10:08 bench_utf8
0[10:08:14]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ xtime ./bench_utf8
 SPENT  5056.871 ms in utf8.to_upper, csum: 66000000 | max_iterations: 1000000
CPU: 4.97s      Real: 5.06s     Elapsed: 0:05.06        RAM: 111120KB   ./bench_utf8
0[10:08:23]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ 
0[10:08:35]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ 
0[10:08:35]delian@nemesis: (vfmt_over_encoding_utf8) /v/vmaster $ git co utf8
Switched to branch 'utf8'
0[10:08:40]delian@nemesis: (utf8) /v/vmaster $ wc vlib/encoding/utf8/utf8_util.v 
 1159  7314 41979 vlib/encoding/utf8/utf8_util.v
0[10:08:43]delian@nemesis: (utf8) /v/vmaster $ ./v -cc tcc -keepc bench_utf8.v
0[10:08:48]delian@nemesis: (utf8) /v/vmaster $ ls -lart bench_utf8
-rwxrwxr-x 1 delian delian 806272 Apr 11 10:08 bench_utf8
0[10:08:51]delian@nemesis: (utf8) /v/vmaster $ strip bench_utf8
0[10:08:53]delian@nemesis: (utf8) /v/vmaster $ ls -lart bench_utf8
-rwxrwxr-x 1 delian delian 717640 Apr 11 10:08 bench_utf8
0[10:08:55]delian@nemesis: (utf8) /v/vmaster $ xtime ./bench_utf8
 SPENT  2847.110 ms in utf8.to_upper, csum: 66000000 | max_iterations: 1000000
CPU: 2.77s      Real: 2.85s     Elapsed: 0:02.85        RAM: 112048KB   ./bench_utf8
0[10:09:08]delian@nemesis: (utf8) /v/vmaster $ 
0[10:09:17]delian@nemesis: (utf8) /v/vmaster $ ./v -keepc -cc gcc-10 -prod bench_utf8.v
0[10:09:24]delian@nemesis: (utf8) /v/vmaster $ ls -lart bench_utf8
-rwxrwxr-x 1 delian delian 68080 Apr 11 10:09 bench_utf8
0[10:09:29]delian@nemesis: (utf8) /v/vmaster $ strip bench_utf8
0[10:09:35]delian@nemesis: (utf8) /v/vmaster $ ls -lart bench_utf8
-rwxrwxr-x 1 delian delian 63624 Apr 11 10:09 bench_utf8
0[10:09:36]delian@nemesis: (utf8) /v/vmaster $ xtime ./bench_utf8
 SPENT   931.276 ms in utf8.to_upper, csum: 66000000 | max_iterations: 1000000
CPU: 0.88s      Real: 0.94s     Elapsed: 0:00.94        RAM: 111108KB   ./bench_utf8
0[10:09:46]delian@nemesis: (utf8) /v/vmaster $ 
0[10:09:49]delian@nemesis: (utf8) /v/vmaster $
```

The TLDR is that this PR makes for less source code and faster and smaller executables.

**Comment by spytheman** [comment]
Here is the program that I tested with:
```v
import benchmark
import encoding.utf8

fn main() {
        mut csum := u64(0)
        max_iterations := 1_000_000
        a := 'abcdeăĂ ôÔ testo æ€”абвёabc12 我是V Lang АБВЁABC1{ĂĂ ÔÔ TESTO Æ€”我是V'
        mut bench := benchmark.start()
        for _ in 0 .. max_iterations {
                b := utf8.to_upper(a)
                csum += b[1]
        }
        bench.measure('utf8.to_upper, csum: $csum | max_iterations: $max_iterations')
}
```

**Comment by penguindark** [comment]
@spytheman Tnx for the benchmark :)

**Pull request merged**
