### PR TITLE
anon-fn: call directly

### PR DESCRIPTION
**Pull request by danieldaeschle**
```
fn main() {
	a := fn() string {
		return "test"
	}()
	println(a)
}
```
this works.

What doesn't work:
- Parameters: maybe someone can help here?

### CODE REVIEW

**Comment by medvednikov** [comment]
@joe-conigliaro can you have a look at this?

This should compile, but tbh this is such weird usage of anon fns. What's the practical point of declaring a function that'll never get used again.

**Comment by danieldaeschle** [comment]
I wanted to use them in vweb template.

Currently we have this result:
```v
fn tmpl_gen_func_name() string {
    builder := strings.new_builder(1000)
    // ...
    return builder.str()
}
tmpl_gen_func_name_res := tmpl_gen_func_name()
```

This could be simplified by generation this:
```v
res := $tmpl.compile_file('myfile.html')
------
// into
res := fn () string {
    builder := strings.new_builder(1000)
    // ...
    return builder.str()
}()
```
In this case we have the advantage to not have a function with a name dangling around (the name cannot be used twice). And it would be much simpler (for the user too).

On the other hand, i have no other use case at the moment. But go supports that too afaik.

**Comment by danieldaeschle** [comment]
i think this should work as well (without assignment):
```v
fn () {
  println('hello world')
}()
```

**Comment by medvednikov** [comment]
I see, thanks

**Comment by joe-conigliaro** [comment]
@danieldaeschle your use case for vweb tmpl was originally how i was going to do it but it didnt work at the time

**Comment by danieldaeschle** [comment]
js and parameter functionality isn't given yet... the PR was just a draft :D

**Comment by medvednikov** [comment]
I like small commits. Less chance of breaking things :)

**Pull request merged**
