### PR TITLE
option control stack size of individual thread attempt 02

### PR DESCRIPTION
**Pull request by MatejMagat305**
sugest implement #17185  and continue (reimplement) to #17217

### CODE REVIEW

**Comment by MatejMagat305** [comment]
that seems like no my error ...

**Comment by spytheman** [comment]
That is much simpler. Good work.

**Comment by spytheman** [comment]
> that seems like no my error ...

Yes, it is not. That Github CI is just sometimes flaky :-| . I've restarted the job manually.

**Comment by spytheman** [comment]
Please also add 2 new files:
`vlib/v/gen/c/testdata/spawn_stack.vv`
and
`vlib/v/gen/c/testdata/spawn_stack.c.must_have`

... where the first file (the .vv one), can be the same program as your example, and the second has just the lines, with `pthread_attr_setstacksize` calls from the C output, produced by `v -o x.c examples/control_thread_stack_size.v` .

Also please rename `examples/control_thread_stack_size/main.v` to just `examples/control_thread_stack_size.v` - there is no point in the additional folder imho.

**Comment by MatejMagat305** [comment]
well I don't know why it didn't pass ...

**Comment by JalonSolov** [comment]
The failure is
```
v -o -  vlib/v/gen/c/testdata/spawn_stack.vv matches all line patterns in vlib/v/gen/c/testdata/spawn_stack.c.must_have FAIL

D:/a/v/v/vlib/v/gen/c/testdata/spawn_stack.c.must_have:1: expected match error:

`"D:\a\v\v\v.exe" -o -  "D:\a\v\v\vlib\v\gen\c\testdata\spawn_stack.vv"` did NOT produce expected line:

pthread_attr_setstacksize(&thread__t3_attributes, 65536); // fn: main.my_print2

--------- failed patterns: -------------------------------------------

pthread_attr_setstacksize(&thread__t3_attributes, 65536); // fn: main.my_print2
```
When the lines in a diff look identical, the problem is usually "invisible" or "control" characters... TABs, carriage returns (\r), linefeeds (\n), etc.

Just need to figure out what's being generated vs what is in the must_have file.

In this particular case, my first though it EOL - on Windows it expects `\r\n`, while almost every other system in existence expects just `\n`.  So a simple fix might be to make there there is _NO_ EOL in the must_have file.

**Comment by MatejMagat305** [comment]
well I give up, please how to fix it? Or could you rewrite theese char?

**Comment by JalonSolov** [comment]
Different errors now...
```
--------- failed commands: -------------------------------------------
v -o -  vlib/v/gen/c/testdata/strlit_len_optimization.vv matches all line patterns in vlib/v/gen/c/testdata/strlit_len_optimization.c.must_have OK
  > v -o -  vlib/v/gen/c/testdata/spawn_stack.vv matches all line patterns in vlib/v/gen/c/testdata/spawn_stack.c.must_have 
v -o -  vlib/v/gen/c/testdata/translated_module.vv matches all line patterns in vlib/v/gen/c/testdata/translated_module.c.must_have OK
----------------------------------------------------------------------
v -o -  vlib/v/gen/c/testdata/volatile.vv matches all line patterns in vlib/v/gen/c/testdata/volatile.c.must_have OK
vlib/v/gen/c/coutput_test.v:161: fn test_c_must_have_files
   > assert total_errors == 0
     Left value: 1
    Right value: 0
```

**Comment by MatejMagat305** [comment]
> Different errors now...
> 
> ```
> --------- failed commands: -------------------------------------------
> v -o -  vlib/v/gen/c/testdata/strlit_len_optimization.vv matches all line patterns in vlib/v/gen/c/testdata/strlit_len_optimization.c.must_have OK
>   > v -o -  vlib/v/gen/c/testdata/spawn_stack.vv matches all line patterns in vlib/v/gen/c/testdata/spawn_stack.c.must_have 
> v -o -  vlib/v/gen/c/testdata/translated_module.vv matches all line patterns in vlib/v/gen/c/testdata/translated_module.c.must_have OK
> ----------------------------------------------------------------------
> v -o -  vlib/v/gen/c/testdata/volatile.vv matches all line patterns in vlib/v/gen/c/testdata/volatile.c.must_have OK
> vlib/v/gen/c/coutput_test.v:161: fn test_c_must_have_files
>    > assert total_errors == 0
>      Left value: 1
>     Right value: 0
> ```

In windows tcc is different in gcc and msvc is still same ...

**Comment by spytheman** [comment]
> In windows tcc is different in gcc and msvc is still same ..., is it search substring or concrete line with \tab\tab\tab...?

Each line in the c.must_have files is searched as a substring in the generated source.

I will fix the PR on windows soon, do not bother with it.

**Comment by MatejMagat305** [comment]
ach, sorry, I did not notice that windows has handle, but now it is make sense ... , thank @spytheman

**Pull request merged**
