### PR TITLE
checker: support substitution of '$()' style commands in hash statements

### PR DESCRIPTION
**Pull request by StunxFS**
This PR adds the functionality to V to interpret the commands that are between `$(` and `)`.

This is very useful, and allows things like for example: `#flag $(llvm-config-11 --cflags)`

### CODE REVIEW

**Comment by spytheman** [comment]
It is too powerful - this allows unpredictable builds, and was specifically disabled for that reason (previously it was done through backticks in the #flag directives).

**Comment by Larpon** [comment]
@StunxFS and `$env(VAR)` is not enough?
I.e. what is the v-llvm project using them for?

**Comment by StunxFS** [comment]
> @StunxFS and `$env(VAR)` is not enough?
> I.e. what is the v-llvm project using them for?

No, `$env()` is replaced by a value found in the PATH. v-llvm makes use of this to get flags to compile LLVM (like pkg-config).

**Comment by spytheman** [comment]
I am against merging this - it is too powerful and unsafe.

Flags can be added through environment variables from a build system, without needing V itself to execute arbitrary external commands (which may or may not exist at all on the user's system) at compile time.

**Pull request closed without merging**
