### PR TITLE
cgen: fix assignment to sum types with pointers

### PR DESCRIPTION
**Pull request by kalapalo**
fix assignments to sum types, when it or its variants are pointers.
this fixes https://github.com/vlang/v/issues/5306

### CODE REVIEW

**Comment by kalapalo** [comment]
@medvednikov that's the third time I do this PR but it is never clean on checks. first was spaces that I had to change to tabs, then something else and now it is breaking gitly build on ubuntu.
Does this prevents you to analyze it ?

**Comment by JalonSolov** [comment]
The gitly problem is fixed by a separate PR.  There shouldn't be any further conflicts for you once that PR is merged.

**Comment by kalapalo** [comment]
OK, thanks @JalonSolov

**Comment by medvednikov** [comment]
Sorry, there's a conflict now. Will merge right away after it's resolved.

**Comment by kalapalo** [comment]
@medvednikov hold on this, please.
IMHO, it is correct, but it is breaking by reference args on functions.
`fn (mut g Gen) ref_or_deref_arg` is adding a `(voidptr)&` that is already handled by this PR and this double `&&` creates a C error.
I think it is better to fix this too and rebase.
What you think ?

**Pull request closed without merging**
