### PR TITLE
math: add factorial function

### PR DESCRIPTION
**Pull request by ulises-jeremias**
In this PR I am adding the factorial function to the math module of vlib since it was commented on the code and it could be really usefull to solve stats definitions.

The chosen definition for the implementation is in the domain of real numbers using the generalization of the Gamma function. For this, the table lookup method is used for those arguments belonging to the set of natural numbers less than 172. In any other case, the gamma function of the successor of the income number for any other case.

_NOTE: For any number n greater than 170 the result of n! it will be `max_f64` since a number greater than 170! cannot be stored in a data type f64 by the size allocated in memory for that type of data._

```v
// vlib/math/fact_tables.v
const(
	factorials = [
        f64(...),
        ...
        ]
)

// vlib/math/math.v
// factorial calculates the factorial of the provided value.
pub fn factorial(n f64) f64 {
        // For a large postive argument (n >= factorials.len) return max_f64
	if n >= factorials.len {
			return max_f64
	}

	/* Otherwise return n!. */
	if n == f64(i64(n)) && n >= 0.0 {
			return f64(factorials[i64(n)])
	}

	return gamma(n + 1.0)
}

// vlib/math/math_test.v
fn test_factorial() {
	assert math.factorial(12) == 479001600
	assert math.factorial(5) == 120
	assert math.factorial(0) == 1
}
```

### CODE REVIEW

**Comment by ulises-jeremias** [comment]
For every check, the tests modified by this PR are successfully working:

```
527 ms | /home/runner/work/v/v/vlib/math/math_test.v OK
```

The case that fails in each test case is shown below:

```v
Building examples ...
    54 ms | /home/runner/work/v/v/examples/spectral.v FAIL
`/home/runner/work/v/v/examples/spectral.v`
 (
examples/spectral.v:21:16: cannot define new methods on non-local type `[]f64`
   19| }
   20| 
   21| fn (v mut []f64) times(u []f64) {
                      ^
   22|     for i := 0; i < v.len; i++ {
   23|         mut a := f64(0)
)
```

**Comment by medvednikov** [comment]
I'm not sure why examples/spectral.v compiles right now (it shouldn't) and it doesn't with your PR :)

**Comment by medvednikov** [comment]
It's pretty cool what you did, hope it doesn't increase compilation time/binary size, otherwise it'd have to be moved to a separate `factorial` module.

**Comment by ylluminate** [comment]
Re: compilation time, I'm not seeing up-to-date results at: https://fast.vlang.io/

**Comment by medvednikov** [comment]
@ylluminate fixed, thanks.

**Pull request merged**
