### PR TITLE
rand: document all functions, document range notation form, fix copy-pasta

### PR DESCRIPTION
**Pull request by Larpon**
This will tick all `rand/...` boxes in #7047 when merged.
I've added a note about the range notation form used and cleaned up existing comments a bit also (added punctuation, made comments differ less between modules, used UTF-8 super script chars instead of HTML `<sup></sup>`).

### CODE REVIEW

**Comment by Larpon** [comment]
@spytheman - I'm not sure what the [CI error](https://github.com/vlang/v/pull/7619/checks?check_run_id=1614225898#step:4:48) is about. All I did was add a new section?

**Comment by JalonSolov** [comment]
README.md is failing the check because of 2 imports that it can't do.

**Comment by spytheman** [comment]
It is because of `./vlib/rand/README.md:67:133: error: line too long`
I think we have to make cmd/tools/check-md.v less noisy.

The other 2 import related ones, are errors reported by v, 
but they are not in fact check-md.v errors, 
because their code blocks are marked as `v failcompile`.

The actual warnings/errors by the tool are prefixed with the .md file:error line number .

**Review by spytheman — APPROVED** [review]
Good work!

**Comment by Larpon** [comment]
@spytheman - ooof that was hard to spot 😅 - thanks for the fix!

**Pull request merged**
