### PR TITLE
v run: recompile and execute a changed file.v just once.

### PR DESCRIPTION
**Pull request by spytheman**
This PR implements a cache for the 'v run file.v' compilation ( issue #1365 ).

If a corresponding executable already exists, and is newer than the source file.v, then it is directly  executed without recompilation, saving some time. 

In effect, the 'v run' overhead is negligible on subsequent runs of the same file.

example time savings on hello world script

### CODE REVIEW

**Comment by spytheman** [comment]
An useful shebang script program to test this PR may also be:

```
#!/usr/local/bin/v run
import os
fn main() {
  println('start of mini_v_script.v')
  println(os.args)
  println('done')
  exit(123)
}
```
NB: the 123 exit status should be passed back from the v runner to the shell. The second and so on executions with 'v run' should be much faster also.

**Comment by medvednikov** [comment]
I was going to leave a comment in that feature request.

Thing is, V compiles very quickly. Right now it's a bit slow because it has to recompile the entire vlib for every script, but once that's fixed, it'll take literal milliseconds.

For most scripts the compilation is going to be faster than Python's initialization.

So why do the caching? This complicates the compiler and I'm sure that (as always) Windows will require special treatment.

**Comment by spytheman** [comment]
Because some 'scripts' may be executed many times, or in resource constrained environments, where launching a C toolchain is not very cheap.

Right now launching an empty file python script takes ~20ms for me. 
Launching a v script for the first time takes 244ms. 
With this PR, the second time it takes 4ms.
An empty C file with only naked main, takes 3ms.

I agree that skipping the compilation when there is no change may not be needed in the future, especially when V gets its own native backend. Right now, however I think it will benefit from it.

**Comment by spytheman** [comment]
>> This complicates the compiler and I'm sure that (as always) Windows will require special treatment.

I am not sure that it does. It only checks the modification times of the source and the target executable. The rest of this PR is refactoring to make it possible without duplicating code.

**Comment by medvednikov** [comment]
All right, makes sense.

Thanks

**Comment by iredmail** [comment]
Avoid unnecessary compile is good. :)

**Pull request merged**
