### PR TITLE
cgen: assure floats have IEEE754 binary representation

### PR DESCRIPTION
**Pull request by UweKrueger**
This PR is the result of a [discussion](https://github.com/vlang/v/pull/8840#discussion_r580928113) about float representations.

There is code in V library (e.g. in [strconv](https://github.com/vlang/v/blob/master/vlib/strconv/f64_str.v)) but also in test cases that assume `f64` and `f32` have internal binary IEEE754 representation.

The C standard does not exactly define the float representation, so this PR adds a check that assures IEEE754 compliance (even if it would be hard to find other systems these days).

### CODE REVIEW

**Review by dumblob — CHANGES_REQUESTED** [review]
The check for usage (not just availability) of IEEE 754 base-2 has to be a **runtime check**. A compile time check (as it is now) is fine as it makes things "fail fast" in certain situations, but does not by far substitute a runtime check for obvious reasons.

**Comment by UweKrueger** [comment]
Given that there are no recent non-IEE754 systems in real world that V aims to support, I think a compile time test is more than sufficient.

**Comment by dumblob** [comment]
>Given that there are no recent non-IEE754 systems in real world that V aims to support, I think a compile time test is more than sufficient.

That's a very strong claim and I simply do not believe that *V* is that limited. Actually what many *V* enthusiasts are interested to see is the emitted C code which they can compile with compiler of their choice on a platform of their choice (AIX, Solaris, etc.) - this is what makes *V* appealing - it brings "new wind" into environments which are being "stuck".

So it's definitely worth the effort to do it properly - i.e. in run time.

**Comment by JalonSolov** [comment]
I don't want V generated code to slow down because of some weird system one person has that doesn't support IEEE-754.

If you can come up with a link to a popular system that does NOT support IEEE-754, that also has people wanting to use V generated code, perhaps we could reconsider then.

Even handheld gaming systems like PSP and 3DS use ARM CPUs, which support... you guessed it, IEEE-754.

**Comment by dumblob** [comment]
>I don't want V generated code to slow down because of some weird system one person has that doesn't support IEEE-754.

Me neither. Let me point out, that *V* already does initialization and tiny "sniffing", so this shouldn't be nearly any penalty (at least compared to e.g. thread initialization etc. which is magnitudes slower).

>If you can come up with a link to a popular system that does NOT support IEEE-754, that also has people wanting to use V generated code, perhaps we could reconsider then.

Well, I don't want to ignite any debate about what's popular and what's not. The point is, that *V* declares itself to be usable as C code generator. Which coincidentally is mostly useful in "special" cases like embedded systems, less frequently deployed systems (though these systems tend to be of much higher importance - most POWER systems), etc.

So the easiest would be to remove this claim about "useful generated C code". But if you asked me if I liked this, I'd reply "no" because that's a really cool feature and IEEE 754 runtime detection is nothing compared to what this feature brings.

>Even handheld gaming systems like PSP and 3DS use ARM CPUs, which support... you guessed it, IEEE-754.

I've emphasized it's not about "support", it's about "availability in run time" - in other words, *V* needs anyway IEEE 754 initialization to have FPU in a defined state (e.g. chosen rounding mode, handling of subnormals/denormals, etc.) and I guess, that if this fails, IEEE 754 is not available in which case runtime detection would have exactly `0` cost (but I might be wrong and the FPU init functions bringing it to a defined state do not provide any useful error reporting - didn't look into this yet).

**Comment by JalonSolov** [comment]
The other question is... what if this check fails?  Does your program just abort and say "Sorry, I don't like your hardware." ?

**Comment by dumblob** [comment]
>The other question is... what if this check fails? Does your program just abort and say "Sorry, I don't like your hardware." ?

That's not a question, that's the whole point @UweKrueger proposed in https://github.com/vlang/v/pull/8840#discussion_r580928113 . Simply put "V acts as there is no other float standard in the world". Of course, if no `float`s are being used in the to-be-compiled V program, then this check will not be part of the final binary.

**Comment by UweKrueger** [comment]
I close this. I have come to the conclusion that this is a ridiculous issue that was mostly brought up to provoke people into a flame war rather than to solve a real world problem.

**Pull request closed without merging**
