### PR TITLE
Windows: Unicode I/O

### PR DESCRIPTION
**Pull request by vitalyster**
It is not possible to read or write non-latin characters on Windows with `printf`, `fopen` and friends correctly: they all operate in "Language for non-unicode programs" encoding which is typically limited to 255 characters from user locale alphabet. In order to work with files and console correctly we need to convert all UTF-8 string to "wide strings" before calling any Windows CRT/API functions.
This PR introduces:
- console is set to UTF-8 mode, which allow to read and write raw UTF-8 strings from file streams
- string.`to_wide()` and `string_from_wide()` built-in functions (they must be builtin for now because `println` uses it internally)
- added `_UNICODE` and `UNICODE` C preprocessor definitions to use "wide" Windows APIs instead of ANSI ones; all vlib's Windows functions are updated to use -W APIs, read and write/convert "wide" parameters and return values.
Demo:
hello

Known issues:
- interpolated strings are not worked correctly (because of `printf` hardcoded in `parser.v`)
- command line arguments still processed as ANSI strings, but it will be easy to change when this PR will be merged

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks for this work. Can you have a look at the failed tests?

**Comment by vitalyster** [comment]
Tests are fixed

**Comment by medvednikov** [comment]
Is it necessary to malloc every time a Windows function requiring a string is called?

**Comment by vitalyster** [comment]
I did not found another way to allocate u16 array to not break codegen

**Comment by medvednikov** [comment]
I don't have any experience with Windows programming. Is it a normal practice to allocate a new buffer, call MultiByteToWideChar, call the function, clear the buffer every time a string function is called?

**Comment by vitalyster** [comment]
Windows expects you are always use wide strings, COM/.NET/etc. are all uses wide strings internally. Even plain Win32 API functions are wide internally and -A APIs are converted automatically to -W (but not from UTF-8).
In our case yes, we need to allocate and free buffer for wide string.

**Comment by medvednikov** [comment]
So I understand the Windows C compiler uses `L""` string literals. Perhaps we can generate them instead?

**Comment by vitalyster** [comment]
Yes `L""` string literals are used for compile time conversion, but what you will generate for user input?

**Comment by vitalyster** [comment]
For example, user type `😀`, `ReadConsole` give us `0xD8 0x3D 0xDE 0x00` bytes ("wide" UTF-16 representation), while we need `0xF0 0x9F 0x98 0x80` bytes in UTF-8. Not sure it is possible to generate :)

**Comment by medvednikov** [comment]
True, but it's possible to detect whether the string is wide and not do an allocation.

That will optimize lots of `println('hello')`s.

**Comment by joe-conigliaro** [comment]
Ohh I just re read the docs after looking at this realizing ReadConsole works for Unidoe ans Ascii. I'm the one that left those notes about ReadConsoleW in there. oops 🤣

**Comment by MaD70** [comment]
@medvednikov I don't program in C usually but I'm quite sure that the wide string literal `L"` is standard C (see [Wide Characters and C](https://www-user.tu-chemnitz.de/~heha/viewchm.php/hs/petzold.chm/petzoldi/ch02c.htm); note that it's from an old (1998) Petzold's book), it's not specific to Windows C compilers ([example on Repl.it here: Clang on Ubuntu](https://repl.it/repls/UprightLoneTelecommunications)).

But it's true that, from what I'm reading around, it's hard to write portable C code that has to deal with UNICODE. See, for example:
- [this answer](https://stackoverflow.com/a/6318604) to this Stackoverflow question: [WChars, Encodings, Standards and Portability](https://stackoverflow.com/q/6300804);
- [UTF-8 Everywhere](https://utf8everywhere.org/), section [10 How to do text on Windows](https://utf8everywhere.org/#windows);
- [The Absolute Minimum Every Software Developer Absolutely, Positively Must Know About Unicode and Character Sets (No Excuses!)](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/) and so on…

**Comment by medvednikov** [comment]
Thanks @MaD70, didn't know that.

> P.S.: very rough idea: convert, at compile time, utf-8 literal strings in V sources to wide strings while generating C when the target is Windows (I think this is what medvednikov intended).

This is correct.

**Comment by MaD70** [comment]
@medvednikov you're welcome. I was surprised myself to find it in my copy of K&R _The C Programming Language, 2nd ed_ (Italian translation).
The Windows mess about UNICODE was caused by the Microsoft rush to have a better internationalization. It was one of the early adopters on a large scale.
A lot cruft accumulated during the last decades in the basic software infrastructure. It's a hard work to hide it under the carpet of a programming language portable implementation and make it simple as possible at the same time.

**Comment by medvednikov** [comment]
I'll merge this today and fix string literals myself.

**Comment by medvednikov** [comment]
@vitalyster I had to revert this because it broke the compilation of V.

Travis stopped running on Windows for some reason.

**Comment by joe-conigliaro** [comment]
@vitalyster I can confirm it broke compilation. i think something with to_wide() because ls() and some other functions were not working.

**Comment by vitalyster** [comment]
@medvednikov first build does not work because v.exe does not define _UNICODE directives, you need to regenerate v.c first and then it should work

**Comment by medvednikov** [comment]
I always regenerate v.c.

**Comment by joe-conigliaro** [comment]
@vitalyster nah it wasn't that

**Pull request merged**
