### PR TITLE
array: sort for all numeric types

### PR DESCRIPTION
**Pull request by mobarski**
I've added array.sort for all numeric types (without using generics).
All unit tests included.

### CODE REVIEW

**Comment by Gladear** [comment]
Comparison functions could be implemented as `return *b - *a`, which would be more efficient.

**Comment by mobarski** [comment]
@Gladear But then you have to worry about the 'int' size vs a/b size:

```c
       void qsort(void *base, size_t nmemb, size_t size,
                  int (*compar)(const void *, const void *));
//                ^^^
```

**Comment by Gladear** [comment]
What I meant was to replace every comparison function body by `return *a - *b` (yeah, it's actually the opposite of what I said earlier). I didn't mean that it would be a generic way :slightly_smiling_face:

**Comment by mobarski** [comment]
@Gladear return type from cmp function must be C's int (as that's in qsort interface)
Think about u64 arguments:
0xFFFFFFFFFFFFFFFF - 1 will give 0xFFFFFFFFFFFFFFFE while the type of results must be C's int (which can be as short as 16 bits on some architectures).

I think that -1,0,1 values are more portable

**Comment by medvednikov** [comment]
Hm I'd rather implement `.sort(a < b)` we discussed on Discord right away. Not a fan of copy pasta :)

**Comment by mobarski** [comment]
> Hm I'd rather implement `.sort(a < b)` we discussed on Discord right away. Not a fan of copy pasta :)

Sure! That was meant only as a temporary solution before more generic one will be made.

**Comment by medvednikov** [comment]
I've just implemented `.sort(a < b)`, so this is no longer needed.

**Pull request closed without merging**
