### PR TITLE
compiler: add a test case to ensure more stable local modules

### PR DESCRIPTION
**Pull request by spacesinmotion**
Simply added a new unit test calling using a local module that is not inside of `vlib`

### CODE REVIEW

**Comment by medvednikov** [comment]
Please use `compiler/tests` for this.

**Comment by medvednikov** [comment]
`import local` should work.

**Comment by spacesinmotion** [comment]
`import local` works. I know. Does not hurt if it is tested automatically.

**Comment by medvednikov** [comment]
I'm referring to `import compiler.tests.local`

**Comment by spacesinmotion** [comment]
Ok, I'm not quite sure what you mean?

**Comment by medvednikov** [comment]
In your PR you do `import compiler.tests.local` instead of `import local`.

**Comment by spacesinmotion** [comment]
I see. 
Sorry. It is still early in the morning.

**Comment by spacesinmotion** [comment]
```sh
$ ./v compiler/tests/local_test.v
V panic: module "local" not found
```
does not work at the moment ...

**Comment by medvednikov** [comment]
Looks like it doesn't work with tests. Should be fixed in the future.

**Pull request merged**
