### PR TITLE
Fix #13626, check unwrapped type is fixed array and selector expr is 'len'

### LINKED ISSUE #13626: Generic cannot correctly infer type
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 20 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i7-12700  
CC version: Error: exec failed (CreateProcess) with code 2: 系統找不到指定的檔案。
 cmd: cc --version

getwd: C:\Users\chaos\projects\vaker
vmodules: C:\Users\chaos\.vmodules
vroot: C:\Users\chaos\projects\v
vexe: C:\Users\chaos\projects\v\v.exe
vexe mtime: 2022-03-01 18:59:51
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 7f8f571.996bd41

Git version: git version 2.35.1.windows.2
Git vroot status: weekly.2022.09-3-g996bd41c (4 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 9de1a49e

**What did you do?**
```v
fn main() {
       a := [5]int{}
        fake_data(&a)
}

// Faking data with default options
[inline]
pub fn fake_data<T>(t &T) {
	fake_data_wdf<T>(t, &vaker.default_df)
}

// Faking data with custom options
[inline]
pub fn fake_data_wdf<T>(t &T, df &DataFaker) {
	$if T is $Array {
		unsafe {
			for i in 0 .. t.len {
				fake_data_wdf(&t[i], df)
			}
		}
	} $else $if T is $Map {
		fake_map(t, df)
	} $else $if T is $Struct {
		$for f in T.fields {
			$if f.typ is string {
			}
			// Dummy expression to generate and specify t.$(f.name)'s type

			mut attrs := get_attrs(t.$(f.name), f)

			if !attrs.skip() {
				fake_data_wdf(&(t.$(f.name)), df)
			}
		}
	} $else {
		unsafe {
			*t = fake_primitive_value<T>(df) or { panic(err) }
		}
	}
}
```

**What did you expect to see?**
no errors
 
**What did you see instead?**
```cmd
vaker/vaker.v:39:20: error: `[5]int` has no property `len`
   37 |     $if T is $Array {
   38 |         unsafe {
   39 |             for i in 0 .. t.len {
      |                             ~~~
   40 |                 fake_data_wdf(&t[i], df)
   41 |             }
vaker/vaker.v:40:21: error: non-integer index `void` (array type `[5]int`)
   38 |         unsafe {
   39 |             for i in 0 .. t.len {
   40 |                 fake_data_wdf(&t[i], df)
      |                                 ~~~
   41 |             }
   42 |         }
```

### PR DESCRIPTION
**Pull request by ChAoSUnItY**
- Fix #13626 (unable to infer correct generic type)

> Side note: this is a temp fix, this generic issue is probably deeper than this situation.

### CODE REVIEW

**Comment by ChAoSUnItY** [comment]
Interesting... I had tested this with vaker and works fine.

**Comment by spytheman** [comment]
> Interesting... I had tested this with vaker and works fine.

Perhaps there were changes in your local copy, that were not pushed in the github's version, or it was in a branch != `main` ?

**Comment by spytheman** [comment]
The test compiles on both master and in the PR 🤔

**Comment by spytheman** [comment]
image

**Comment by ChAoSUnItY** [comment]
This one is mainly based on orignal issue's src code, and it was tested with origin master's v exe, which will cause error.

**Comment by spytheman** [comment]
This time it does work on the PR, and fails on master - good test.
(rebased over current master)

**Review by spytheman — APPROVED** [review]

**Pull request merged**
