### PR TITLE
adt: Implement binary MinHeap data structure

### PR DESCRIPTION
**Pull request by mcastorina**
Implemented with this reference: https://en.wikipedia.org/wiki/Binary_heap

### CODE REVIEW

**Comment by mcastorina** [comment]
I would like to add a comparison function to the `MinHeap` struct so it can be a more generic min/max heap:

```v
struct Heap<T> {
pub:
    comparison fn(a T, b T) bool
mut:
    data []T
}
```

however I don't think this is supported with generics yet.

**Comment by Hunam6** [comment]
I'm kinda confused by the name, Wikipedia seems to use "binary heap", even if on the sidebar they used "binary (min) heap". You seem to use "minHeap" in your code and "heap" for the file name.
Apart from if I missed something, you should choose one name.

**Comment by Hunam6** [comment]
Also please add "Min Heap" or whatever the name will be to the implemented ADTs list on the README. Also you forgot to add "Doubly linked list" in your previous PR, maybe add it in this PR.

**Comment by mcastorina** [comment]
> I'm kinda confused by the name

I chose `heap.v` to leave room for other heap-based data types. I named the struct `MinHeap` because it sorts items by the minimum (as opposed to a max heap, which sorts by the maximum). I have no preference on the naming, so if you have a suggestion I'll change it to that. As for the filename, I also have no preference since it doesn't matter for compilation / imports, although if more heap-based data types are added (e.g. `MaxHeap`) I think it makes sense to have them in the same file.

> Also please add "Min Heap" or whatever the name will be to the implemented ADTs list on the README.

Will do.

**Comment by Hunam6** [comment]
> I chose `heap.v` to leave room for other heap-based data types. I named the struct `MinHeap` because it sorts items by the minimum (as opposed to a max heap, which sorts by the maximum). I have no preference on the naming, so if you have a suggestion I'll change it to that. As for the filename, I also have no preference since it doesn't matter for compilation / imports, although if more heap-based data types are added (e.g. `MaxHeap`) I think it makes sense to have them in the same file.
Okay thanks I missed that, so it seems ok to me to have a different name (between the file name and the struct name) if you want to implement maxHeap for example and you think it's logical to put them in the same file.

**Pull request merged**
