### PR TITLE
docs: fix broken links by adding missing READMEs

### PR DESCRIPTION
**Pull request by alex-semenyuk**
As mentioned at #17003 missing README broke the links so add some short READMEs for such cases

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE5NjAxM2YwMmQ4YTAzZmIyZmViNmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ZiJl2cEHpP-UKUMKoLzSUjGxYpC3uRTB4jxdeAMIuow">Huly&reg;: <b>V_0.6-21085</b></a></sub>

### CODE REVIEW

**Comment by JalonSolov** [comment]
The `vlib/v2/README.md` is incorrect, at the least.  It is code for an intermediate change to the V compiler, not ready for regular usage.  Not sure about the status of the others...

**Comment by spytheman** [comment]
All of them are incorrect and misleading. I do not know what LLM generated them, but it is not appreciated.

Even an empty readme, or just a readme that has an explicit "placeholder" text in it, is better.

**Comment by alex-semenyuk** [comment]
if you're well know what they're doing, can make your suggestion that fix this right away   

For example, as for v2 something like?

`v2` provides code for an intermediate change to the V compiler, not ready for regular usage.

**Comment by spytheman** [comment]
Both vlib/v/ and vlib/db/ are just container modules. They do not do anything by themselves, but only provide an organization structure for the modules under them.

As for vlib/coroutines/ - it is just a wrapper around thirdparty/photon .
It is used by the compiler, to implement `go f()`. That is all that can be safely documented about it. The reason for that, since it is still experimental and can change, if we decide to use another green threads library instead of photon for example, or integrate changes that make it work on windows etc.

**Comment by spytheman** [comment]
The README for vlib/v, starts with this:
```md
## Description

`v` is a namespace for all of the V compiler modules.
```

I think something similar can be done for `vlib/v2/README.md` and `vlib/db/README.md` .

**Comment by alex-semenyuk** [comment]
> `coroutines` is a namespace for a wrapper around third party/photon.

> `v2` is a namespace for an intermediate change to the V compiler, not ready for regular usage.

> `db` is a namespace for interacting with various databases modules.

How about something like this

**Comment by StunxFS** [comment]
`coroutines` is not a namespace, it is a module that works as a wrapper for `photon`.

`v2` is a namespace containing a new version of the compiler (still in development).

`db` is a namespace that contains several useful modules for operating with databases (SQLite, MySQL, MSQL, etc.)

**Comment by spytheman** [comment]
The new versions seem fine to me.

**Comment by alex-semenyuk** [comment]
thanks, updated

**Review by spytheman — APPROVED** [review]
Excellent work.

**Pull request merged**
