### PR TITLE
fix order of the `time` struct in the `time` module

### PR DESCRIPTION
**Pull request by perry14**

### CODE REVIEW

**Comment by superwhiskers** [comment]
the title doesn't describe the pull request very well

**Comment by Kriyszig** [comment]
Is this necessary though?
Probably `mm/dd/yyyy` was the format he followed while writing this

**Comment by SuperFola** [comment]
According to http://www.cplusplus.com/reference/ctime/tm/, it's still missing a few entries 🤔 
Also, why are the fields in the reverse order? Does the compiler do some sort of conversion for the struct (by reversing their fields to match the C structure)? I couldn't find anything about that in `v.c`

**Comment by medvednikov** [comment]
Now, the order doesn't make any difference, at least right now.

**Pull request merged**
