### PR TITLE
GC-boehm: provide optimized mode

### PR DESCRIPTION
**Pull request by UweKrueger**
A conservative garbage collector must periodically scan used memory for pointers to identify non-referenced memory blocks that can be freed. All regular threads must be suspended while the scan is in progress to prevent any memory changes. However, this leads to periodic pauses ("stop-the-world garbage collection").

In principle the scan is only necessary for memory that might contain pointers. I.e. if the compiler can proof that this is not the case in a particular memory block, then this one this one does not have to be scanned. Boehm-GC provides a function `GC_MALLOC_ATOMIC()` to allocate a memory block that is not scanned (but still collected if not referenced from any other memory block).

This PR adds a recursive compile time analysis of the element type for array allocation. If the array elements do not contain any pointers then the memory area is allocated using `GC_MALLOC_ATOMIC()`.
The same could be done for maps, too, but it does not make sense as long as keys and values are stored interleaved in one `DenseArray` - but this ~~is likely to~~ [~~change~~](https://github.com/vlang/v/pull/9453#issuecomment-806034631) has changed (edit).
Two command line options have been added:

- `-gc boehm_full_opt` - classic "full" mode with the optimization
- `-gc boehm_incr_opt` - generational mode with the optimization

The benchmark test has been reworked to use both pointer arrays and data arrays with the following pause time results (less is better):
image
- `-gc boehm_full` (the mode that is currently used when `-gc boehm` is specified) shows periodic pauses of approximately 85ms (after some "warmup" time)
- With `-gc boehm_full_opt` the average pause time for the benchmark program (4-8 GB RAM usage) can be reduced from 85ms to 3ms. (The pauses occur 5 times more often, but that should not matter that much.)
- With `-gc boehm_incr_opt` no further benefits are visible (in fact it's even much worse than `-gc boehm_full_opt`).

I've also analyzed memory usage, CPU usage and the time to finish the benchmark for a very large number of iterations. The results indicate that here `-gc boehm_full_opt` is superiour to all other candidates, too (less is better):
resource usage results
For this reason we should consider making `-gc boehm_full_opt` the default mode that is used when the `-gc boehm` flag is given (what is currently `-gc boehm_full`). As a first step I've changed the CI tests to use this mode for the garbage collection tests.

Edit: embed graphics

### CODE REVIEW

**Comment by ka-weihe** [comment]
> The same could be done for maps, too, but it does not make sense as long as keys and values are stored interleaved in one DenseArray - but this is likely to change.

This has already been changed - the keys and values are no longer interleaved :slightly_smiling_face:

**Comment by UweKrueger** [comment]
> This has already been changed - the keys and values are no longer interleaved slightly_smiling_face

Great! I'll adjust this in one of the following PRs then. (This one is already big enough...)

**Comment by medvednikov** [comment]
Great job as always!

**Comment by ylluminate** [comment]
What is left to do in order to set `boehm_full_opt` to replace default `boehm`?

**Pull request merged**
