### PR TITLE
compiler: remove support for @VROOT, @VPATH, @VLIB_PATH, @VMOD . Use @VMODULE instead.

### PR DESCRIPTION
**Pull request by spytheman**
This PR simplifies handling of compile time constants by leaving only `@VMODULE` .

* `@VPATH`, `@VLIB_PATH`, `@VMOD` were not used in v nor in vos.

* `@VROOT` was replaced by the more general `@VMODULE` and relative paths.

### CODE REVIEW

**Comment by vitalyster** [comment]
I think `@VROOT` is more self-explanatory than `@VMODULE`, am I miss something?

**Comment by spytheman** [comment]
@vitalyster , `@VROOT` is useful only for modules located inside the main v repo. 

`@VMODULE` is more general, and can be used by external user modules too, not only by vlib modules. This is a cleanup in preparation for the future `-path` option (which will simplify module lookup, while keeping it flexible), as well as `v.mod` file support (`@VMODULE` will be its location, seeked through the nearest parent folder that contains it, similar to how .git/config and .gitignore work, which will allow modules to have custom folder structure, without needing symlink hacks).

**Comment by vitalyster** [comment]
I just mean maybe better to name new variable as `@VROOT`? Sure there was a difference before, but from new user perspective it should be easier to understand, so I just vote for all of these changes but to select VROOT name for final variable

**Comment by medvednikov** [comment]
I agree, VROOT is simple and self explanatory.

```@VROOT/thirdparty/vschannel
@VMODULE/../../../thirdparty/vschannel
```
I don't want users to calculate number of directions and use 3 `../`. What if code is moved to another submodule?

**Comment by AlSufyaniT1** [comment]
https://fb.me/react-unsafe-component-lifecycles

**Comment by spytheman** [comment]
Since now I have implemented v.mod support for VMODULE, and there is v.mod file in the main v repo.

In effect, that allows flags like:
`#flag @VMODULE/thirdparty/bignum/bn.o`
... just like previously there was 
`#flag @VROOT/thirdparty/bignum/bn.o`

i.e. there are now no /../ in the flags, and all vlib modules can use the same prefix, without counting folder levels.

I still think that `@VMODULE` or @VMOD is a better name for the anchor, given that it is now relative to the nearest `v.mod` file in a parent folder (which happens to be the file `v.mod` in the main folder of the V project itself).

Other modules like https://github.com/vlang-num/vnum or https://github.com/vlang/vsl will also benefit from this, but in their context VROOT is not so meaningful, while VMODULE is in my opinion.

**Comment by spytheman** [comment]
@AlSufyaniT1 I do not understand... What is the relevance of React with this PR ?

**Pull request merged**
