### PR TITLE
sokol/GLSL: example of multi shaders at the same time on screen

### PR DESCRIPTION
**Pull request by penguindark**
**What's inside**
- Example of multi shaders at the same time
- Shader Headers precompiled for: Windows/Linux/MacOS

This example explain how to use multiple shaders on the same scene,
loading and changing the pipeline every frame.

### CODE REVIEW

**Comment by medvednikov** [comment]
hm, 12k extra lines for an example is a lot of code.

**Comment by JalonSolov** [comment]
Maybe time for a `vlang/examples` repo?  This one is really cool, and would be nice to have available, but yeah, maybe a little large to include in main V examples dir.

**Comment by medvednikov** [comment]
Yeah it's a great example, but 20k lines is too much, considering the entire V compiler is ~100k right now.

At the same time all current small examples should remain, since they are very important for learning the language.

I think we can indeed create an official `vlang/examples` repo and have big examples there, and maybe add it as a subrepo to `/examples/`.

**Comment by penguindark** [comment]
Yeah, may be we need an external repository, graphic consume a lot of memory and sources

**Comment by penguindark** [comment]
Anyway, If I remove the headers of the shaders the code will be reduced a lot, but users will must recompile them.

**Review by Craddock7 — APPROVED** [review]

**Comment by penguindark** [comment]
OK, I'll remove it waiting for the example repository :)

**Pull request closed without merging**
