### PR TITLE
custom_error.v

### PR DESCRIPTION
**Pull request by hidalgo-vntu**

### CODE REVIEW

**Comment by hidalgo-vntu** [comment]
hacktoberfest-accepted

**Comment by JalonSolov** [comment]
I would change the title of this to `Create custom error example", and rename the file to `custom_error.v`.

**Comment by hidalgo-vntu** [comment]
Done

**Comment by JalonSolov** [comment]
You renamed the PR to `custom_error.v`, but your file is still named `examples/error`.  I've renamed the PR, please rename your file.

If the file itself doesn't have a `.v` extension (regardless of the name), V won't compile it.

I have verified the contents of the file do compile, and work as expected.

**Review by hidalgo-vntu — COMMENTED** [review]
Done

**Comment by JalonSolov** [comment]
Again, you have changed the title of the PR, but not the name of the file.  This is backwards from what I suggested.

At the very least, your file would need a `.v` extension before it can be compiled.

**Comment by spytheman** [comment]
I am very glad that October is nearly over.

**Review by spytheman — APPROVED** [review]

**Comment by hidalgo-vntu** [comment]
Thank you, guys!

**Pull request merged**
