### PR TITLE
vweb: router refactor

### PR DESCRIPTION
**Pull request by Terisback**
Implemented todo, and added some documentation.
Also deleted `request.v` and `request_test.v`, because it's copy of `net/http/request.v`
Next move is separate source code into files, for more readability.

### CODE REVIEW

**Comment by spytheman** [comment]
The removed filter function is used by the codegen in:
```
vlib/v/gen/c/str_intp.v:130:                    g.write('vweb__filter(')
```

**Comment by Terisback** [comment]
Why?

**Comment by spytheman** [comment]
It is used to escape strings in the context of vweb templates.

**Comment by Terisback** [comment]
ok, pushed fix

**Pull request merged**
