### PR TITLE
msvc: Unique names for pdb files, remove test job limit

### PR DESCRIPTION
**Pull request by emily33901**
Ran into this the other day attempting to do `.\make.bat -msvc` at which point it threw its hands in the air and told me that `msvc_strap` was not a valid label when it clearly is.

Quick search led to [this stackoverflow page](https://stackoverflow.com/questions/232651/why-the-system-cannot-find-the-batch-label-specified-is-thrown-even-if-label-e), which suggests that having LF in the file could be the issue. When I renormalized the line endings this issue went away.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Yes, there are a _very_ few file types which still _must_ have CRLF in Windows, in order to work correctly.  `.bat` files is one of them (and really, only if you have labels such as `make.bat`).  `.cmd`, `.dsp` and `.dsw` (these last 2 are old VisualStudio files) are others.  I'm not specifically aware of others beyond those.

**Comment by emily33901** [comment]
Nice broken tests

**Comment by emily33901** [comment]
All of these tests that break in the CI work for my local machine :thinking: which is not ideal for debugging / fixing

**Comment by vitalyster** [comment]
Are you sure there should be pdb per obj file? It is better to have one pdb file per exe/dll, isn't it?

**Comment by emily33901** [comment]
I believe thats what I mean - we only generate 1 object file per V compilation afaik so this would also only generate 1 pdb file per compilation (which it is already doing)

**Pull request merged**
