### PR TITLE
v.transformer: fix string always escaped by transformer

### LINKED ISSUE #12548: The raw string was escaped.
**V version:** 
V full version: V 0.2.4 86694dd.fbe2b5c

**OS:** 
OS: windows, Microsoft Windows 10 רҵ v19042 64 λ
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**What did you do?**
source file `test.v`:
```
module main

fn main() {
	a := r'a\nb' + r'a\nb'
	mut b := r'a\nb'
	b = b + r'a\nb'
	c := 'a\nb' + r'a\nb'
	println('a:$a')
	println('b:$b')
	println('c:$c')
}
```
Executing with: v run test.v
```
PS C:\test> v run .\test.v
a:a
ba 
b  
b:a\nba\nb
c:a       
ba        
b
```

**What did you expect to see?**
```
PS C:\test> v run .\test.v
a:a\nba\nb
b:a\nba\nb
c:a       
ba\nb
```
 
**What did you see instead?**
I tried to locate the bug.
In line 367 to 396 of file `vlib/v/transformer/transformer.v`, the infix_expr method optimizes the merging of two strings without determining whether the left and right string are raw.
```
ast.StringLiteral {
	match right_node {
		ast.StringLiteral {
			match node.op {
				.eq {
					return ast.BoolLiteral{
						val: left_node.val == right_node.val
					}
				}
				.ne {
					return ast.BoolLiteral{
						val: left_node.val != right_node.val
					}
				}
                                /*  First we need to check whether the left and right strings are original strings */
				.plus {
					return ast.StringLiteral{
						val: left_node.val + right_node.val
						pos: pos
					}
				}
				else {
					return node
				}
			}
		}
		else {
			return node
		}
	}
}
```

### PR DESCRIPTION
**Pull request by ChAoSUnItY**
Fix #12548.

Always uses `util.smart_quote` to ensure both left string literal and left literal is properly treated.

### CODE REVIEW

**Comment by spytheman** [comment]
`util.smart_quote` has rules for escaping targeting C, and the transform stage is run before the different codegens.
Does it work the same with the JS backend?

**Comment by spytheman** [comment]
on master, it was used only in the cgen:
```
0[18:38:06]delian@nemesis: (master) /v/cleanv $ rg smart_quote
vlib/v/util/quote.v:18:pub fn smart_quote(str string, raw bool) string {
vlib/v/gen/c/str.v:9:   escaped_val := util.smart_quote(node.val, node.is_raw)
vlib/v/gen/c/str.v:28:          escaped_val := util.smart_quote(val, false)
vlib/v/gen/c/cgen.v:5784:                               escval := util.smart_quote(byte(rune_code).ascii_str(), false)
vlib/v/gen/c/cgen.v:5791:                       escaped_val := util.smart_quote(ct_value, false)
vlib/v/gen/c/str_intp.v:186:            escaped_val := util.smart_quote(val, false)
```

**Comment by spytheman** [comment]
imho the Transformer should not merge/mix raw and not raw strings, because it does not know what escaping rules will be used for each backend

**Comment by ChAoSUnItY** [comment]
but still, we can merge them *only if* it's backend is C.

For now JS backend parse raw while in JS runtime, so that cannot be merged for sure.

**Comment by spytheman** [comment]
would not it lead to double escapes?
we may need to add a test with something like:
```v
fn test_many_pluses() {
	a := r'x\n'
	b := 'x\n'
	c := a + b
	d := c + c
	e := d + d
	println(e)
	result := r'x\nx
x\nx
x\nx
x\nx
'
	assert e == result
}
```

**Comment by spytheman** [comment]
this fails on master btw:
```v
const   ca = r'x\n'
const   cb = 'x\n'
const   cc = ca + cb
const   cd = cc + cc
const   ce = cd + cd

fn test_many_pluses() {
    a := r'x\n'
    b := 'x\n'
    c := a + b
    d := c + c
    e := d + d
    println(e)
    result := r'x\nx
x\nx
x\nx
x\nx
'
    assert e == result
    assert ce == e
}
```

**Comment by spytheman** [comment]
it starts diverging at ` c == cc`

**Comment by ChAoSUnItY** [comment]
At first glance this test has nothing to do with transformer, since what transformer really have done is merge two string literal in an infix expression but not two identifiers that stores string literals.

**Comment by spytheman** [comment]
> At first glance this test has nothing to do with transformer, since what transformer really have done is merge two string literal in an infix expression but not two identifiers that stores string literals.

indeed - I tried commenting the merging in the transformer, and it still failed 🤔 ; I'll file a separate bug for it.

**Pull request merged**
