### PR TITLE
cgen: fix string of map with generic struct value (fix #16594)

### LINKED ISSUE #16594: map causes a compiler bug error.
### Describe the bug

when trying to declare a  map with a key of type string and a value of type datatypes.Stack<int>{}
 program doesn't compile and state that this is a compiler bug.

```v
import datatypes

p := map[string]datatypes.Stack<int>{}
println(p)
```

### Expected Behavior

I expect a map with the specified key value type to be declared.

### Current Behavior

Throws this error and program is not compiled.
 ```
/tmp/v_1000/t.17442098459935223959.tmp.c:2244: warning: implicit declaration of function 'indent_datatypes__Stack_T_int_str'
/tmp/v_1000/t.17442098459935223959.tmp.c:2244: error: cannot convert 'int' to 'struct string'
```

### Reproduction Steps

Try to declare a map with key of type string and value of type `datatypes.Stack<int>` or `datatypes.Queue<int>` 

### Possible Solution

Throw a friendly error if such operation is not possible like when trying to use value of type [void](https://github.com/vlang/v/blob/7e9e2ff45994c3f6c348e8e6b181fd9ea91df209/vlib/v/parser/parse_type.v#L138)

### Additional Information/Context

_No response_

### V version

V 0.3.2 7e9e2ff

### Environment details (OS name and version, etc.)

```
OS: linux, Pop!_OS 22.04 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

getwd: /home/mp/AOC/day2
vmodules: /home/mp/.vmodules
vroot: /home/mp/Downloads/v
vexe: /home/mp/Downloads/v/v
vexe mtime: 2022-12-05 06:59:16
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 ffc73bf

Git version: git version 2.34.1
Git vroot status: Error: fatal: bad revision 'HEAD'
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix string of map with generic struct value (fix #16594).

- Fix string of map with generic struct value.
- Add test.

```v
import datatypes

fn main() {
	p := map[string]datatypes.Stack[int]{}
	println(p)
	assert '${p}' == '{}'
}

PS D:\Test\v\tt1> v run .
{}
```

### CODE REVIEW

**Comment by Delta456** [comment]
Can you add more tests like:

```v
import datatypes

fn main() {
	mut p := map[string]datatypes.Stack[int]{}
        mut stack := datatypes.Stack[int]{}
        stack.push(3)
        stack.push(6)
        stack.push(4)
	assert '${p}' == '{}'
        p['one'] = stack
       assert '${p}' = "{'one': Stack[int]{3, 6, 4}}"
       p['one'].push(7)
      assert '${p}' = "{'one': Stack[int]{3, 6, 4, 7}}"
      p['one'].pop()?
      assert '${p}' = "{'one': Stack[int]{3, 6, 4,}}"

}
```

I think it will be better to see if maps are truly working generics.

**Comment by spytheman** [comment]
This works:
```v
import datatypes

fn main() {
	mut p := map[string]datatypes.Stack[int]{}
	mut stack := datatypes.Stack[int]{}
	stack.push(3)
	stack.push(6)
	stack.push(4)
	assert '${p}' == '{}'
	p['one'] = stack
	assert '${p}' == "{'one': [3, 6, 4]}"
	p['one'].push(7)
	assert '${p}' == "{'one': [3, 6, 4, 7]}"
	p['one'].pop()!
	assert '${p}' == "{'one': [3, 6, 4]}"
}
```

**Comment by Delta456** [comment]
> This works:
> 
> ```v
> import datatypes
> 
> fn main() {
> 	mut p := map[string]datatypes.Stack[int]{}
> 	mut stack := datatypes.Stack[int]{}
> 	stack.push(3)
> 	stack.push(6)
> 	stack.push(4)
> 	assert '${p}' == '{}'
> 	p['one'] = stack
> 	assert '${p}' == "{'one': [3, 6, 4]}"
> 	p['one'].push(7)
> 	assert '${p}' == "{'one': [3, 6, 4, 7]}"
> 	p['one'].pop()!
> 	assert '${p}' == "{'one': [3, 6, 4]}"
> }
> ```

I think this should be added to the tests.

**Comment by Delta456** [comment]
> @Delta456, I am doubtful that adding this additional test is needed - it is more exercising the `datatypes` module and the general auto string generation done by V, not the bug that the PR fixes - for that the existing test is ok.

Ok

**Pull request merged**
