### PR TITLE
Makefile: adds static compilation

### PR DESCRIPTION
**Pull request by mathieu-aubin**
Adds static compilation option to the makefile, with '_selfcompile-static_' option

### CODE REVIEW

**Comment by mathieu-aubin** [comment]
Thanks for approving.

I thought about something tho... maybe it would be best to deactivate the self-linking function within the program if, per say, the name of the executable is 'v-static'

i wonder what is the behavior of the self-link and i must admit, right now, i have no time to test

**Comment by medvednikov** [comment]
Wouldn't this not work on most systems because of glibc?

Can we add a test to CI?

**Comment by mathieu-aubin** [comment]
@medvednikov you have a valid point, altho i would assume that people who would gear themselves towards build a static executable would have the proper libraries to build statically. Else, they will get an error but this is far from alarming and.. in my opinion doesn't affect the value of the language or it's usability (if that worried you in any ways)

**Comment by spytheman** [comment]
It is ok in my opinion as it is. 
It is just an utility `make` target, it does not affect symlinking at all.

**Comment by spytheman** [comment]
`./v symlink`  just does the equivalent of `ln -s $(realpath v) /usr/local/bin/v` .

**Comment by mathieu-aubin** [comment]
> `./v symlink` just does the equivalent of `ln -s $(realpath v) /usr/local/bin/v` .

that was my concern actually... i'm not sure it's okay to allow _v-static_ to create a link of itself to _/usr/local/bin/v_ which is, after i just checked, what it does

**Pull request merged**
