### PR TITLE
Bootstrap twice on windows

### PR DESCRIPTION
**Pull request by emily33901**
Should be pretty self explanatory

### CODE REVIEW

**Comment by medvednikov** [comment]
This shouldn't be necessary if v.c is always up-to-date.

**Comment by emily33901** [comment]
It is because msvc compat isn't built into the Linux output from v

**Comment by medvednikov** [comment]
Ah this actually fixes the Windows problem with overwriting the file...

**Comment by emily33901** [comment]
Therefore newly bootstraped builds cannot straight away build with msvc

**Comment by medvednikov** [comment]
I see, thanks.

**Pull request merged**
