### PR TITLE
checker: optimized the position indicated by pos when the function needs to return an optional or result(fix #15780)

### LINKED ISSUE #15780: result or optional type is not handled in `_test.v`
**V version:** 
**OS:** 

**What did you do?**
```
.
├── bug.v
├── bug_test.v
└── v.mod
```
bug.v
```v
module main

fn foo() !string{
	return 'abc'
}

fn main(){
	println(foo()!)
}
```
bug_test.v
```v
module main

fn test_1(){
	println(foo()!)
}
```

**What did you expect to see?**
No error as same as `v run bug.v`
 
**What did you see instead?**
```
> v run bug_test.v
bug_test.v:4:15: error: to propagate the call, `test_1` must return an result type
    2 | 
    3 | fn test_1(){
    4 |     println(foo()!)
      |                  ^
    5 | }
```

### PR DESCRIPTION
**Pull request by shove70**
1. Optimized #15780
2. Add test.

```v
fn foo() !string{
	return ''
}

fn bar() {
	println(foo()!)
}
```

output:
```
vlib/v/checker/tests/fn_must_return_optional_or_result_pos.vv:5:10: error: to propagate the call, `bar` must return an result type
    3 | }
    4 | 
    5 | fn bar() {
      |          ^
    6 |     println(foo()!)
    7 | }
```

### CODE REVIEW

**Comment by kahsa** [comment]
sorry maybe #15814 is actual cause.

**Comment by shove70** [comment]
> sorry maybe #15814 is actual cause.

thanks. no problem 👍

**Comment by spytheman** [comment]
If you have a longer function, it will not be clear, *why* it is erroring, since it will point to the function signature, and not to the callsite that used ? or ! for propagation.

**Comment by spytheman** [comment]
In V's scanner, there was a similar problem, where an error needed to point at 2 different, possibly remote positions. There the solution was adding:
`vlib/v/scanner/scanner.v:1499:pub fn (mut s Scanner) add_error_detail_with_pos(msg string, pos token.Pos) {`
and using it, to show something like this:
```v
vlib/v/scanner/tests/empty_character_literal_err.vv:2:8: error: invalid empty character literal ``
    1 | fn main() {
    2 |     a := ``
      |           ^
    3 |     println(a)
    4 | }
Details: 
vlib/v/scanner/tests/empty_character_literal_err.vv:2:7: details: use quotes for strings, backticks for characters
    1 | fn main() {
    2 |     a := ``
      |          ^
    3 |     println(a)
    4 | }
```

I think that something similar can be done in the checker, so that in cases like this, we can add more details, with instructions on what to fix, pointing to the place that needs fixing, while leaving the original error, to point to what triggered the error in the first place.

**Comment by shove70** [comment]
> I think that something similar can be done in the checker, so that in cases like this, we can add more details, with instructions on what to fix, pointing to the place that needs fixing, while leaving the original error, to point to what triggered the error in the first place.

Thanks! I see. I see.

**Comment by spytheman** [comment]
I have a patch that does:
image

I'll push it soon to this PR.

**Comment by shove70** [comment]
> I'll push it soon to this PR.

Okay, I'll close this PR

**Comment by spytheman** [comment]
> > I'll push it soon to this PR.
> 
> Okay, I'll close this PR

no, do not - I will push directly to this PR.

**Comment by shove70** [comment]
Ok, I've just finished writing it, why don't I push it once?

**Pull request merged**
