### PR TITLE
parser: remove submodule level <=4 limit,  make it unlimited

### PR DESCRIPTION
**Pull request by kevin70g**
Big projects need more levels of submodules. I remove the submodule leve limit completely.

### CODE REVIEW

**Comment by medvednikov** [comment]
I'd keep the limit but increase it to 5.

V is a strict language, if someone has 5 submodules, they have issues in their architecture. This is not Java.

**Comment by donnisnoni95** [comment]
@medvednikov Agree !!!

**Comment by joe-conigliaro** [comment]
Yeah I agree, just increase it a bit.
Allowing huge (and unlimited) sub module depth doesn't promote good design imo

**Comment by medvednikov** [comment]
I've set it to 5.

**Pull request closed without merging**
