### PR TITLE
Fix issues with picoev

### PR DESCRIPTION
**Pull request by sumeetchhetri**

### CODE REVIEW

**Comment by medvednikov** [comment]
Can you add picoev tests back to make sure it works?

testing/common.v line 234

**Comment by sumeetchhetri** [comment]
@S-YOU I have added support for fetching headers in picoev, also added initial incomplete support for handling request bodies without which the web server is in-complete and only capable of handling GET requests, I thought maybe you have a better approach to getting this done, we would need to maintain partial request objects (in some sort of a map) so that on receiving pending request body we can then complete the request and hand it over to the handler callback.

**Comment by sumeetchhetri** [comment]
> Can you add picoev tests back to make sure it works?
> 
> testing/common.v line 234

@medvednikov have updated the failing test and added it in the common.v file as well

**Comment by medvednikov** [comment]
Thanks a lot @sumeetchhetri !

**Pull request merged**
