### PR TITLE
REPL: added readline for linux users to use

### LINKED ISSUE #390: REPL Command-Line Editing
Command-line editing is an improvement over standard way to write in a REPL environment.

Being able to navigate in the line to add something in the middle or have a few shortcuts would enhance to user experience.
Having an history of previous lines could also be a thing.

It would probably work by setting the terminal as non-canonical and read the inputs.
A similar function exists in C as `readline`.

### PR DESCRIPTION
**Pull request by Henrixounez**
It brings command line editing to have a better user experience
(Only for linux users)

Resolve #390

### CODE REVIEW

**Comment by medvednikov** [comment]
Can you explain what advantages it brings? History?

**Comment by Henrixounez** [comment]
It has history but most importantly, you can navigate in the line with arrows to edit in middle of the line.

**Comment by medvednikov** [comment]
I see, this is useful. I'll test this and merge, thanks.

**Comment by joe-conigliaro** [comment]
we should try have a multi platform readline replacement

**Comment by Henrixounez** [comment]
Yes I know it is not optimal but I don't know how windows nor mac terminal works. 
The thing is that I am here reliant on the GNU readline library, but I hope as well that we can be independant from that in the future.

**Comment by joe-conigliaro** [comment]
@Henrixounez Im using a version of readline for windows to compile v on windows, maybe that function could get included for now. also not optimal. Maybe all os specific functions should get wrapped so that later on they can be rewritten without by just changing the wrapper function

**Comment by Henrixounez** [comment]
**Removed readline** library dependency. It now uses the `read` command from the **shell**.

It could be easily ported for windows and mac but i don't know what are the cmd for those and i can't test it either.
Could you check it ? @medvednikov

**Comment by medvednikov** [comment]
`os.exec('read -p "$prompt"` is not secure.

**Comment by joe-conigliaro** [comment]
yeah not the best idea i don't think

**Pull request closed without merging**
