### PR TITLE
[DISCUSS] scanner: disallow num lit with in-between spaces

### PR DESCRIPTION
**Pull request by SleepyRoy**
e.g. 
```V
12345 67
1234.5 67
123e4 5
0x111 1
0o111 1
0b111 1
```
Tests are added.

#3823 is therefore completely fixed and could be closed.

### CODE REVIEW

**Comment by JalonSolov** [comment]
I'm not sure about the error messages.  To me, it's not an "unneeded space", it's a syntax error.  For example, it might be a missing comma rather than an extra space.

Another digit after a space is a completely separate number, and is just a syntax error to have hanging out there.

**Comment by spytheman** [comment]
Would that be a better wording?
> error: numbers can not contain spaces, remove space before digit `1`

**Comment by JalonSolov** [comment]
Just alert that there is an error.  The proper fix would be up to the user.

Perhaps something like

`error: numbers cannot be follow by a space then extra characters`

It would be just as much of a problem if they had

`100 a`

as having

`100 1`

**Comment by SleepyRoy** [comment]
Thanks everyone. `100 a` this already results in error so this PR actually focuses on two number literals with spaces between.
I just found a more general bug #5056 related to this.

**Comment by spytheman** [comment]
Now that I think about it more, that would just complicates the scanner for not much actual benefit.
In v, new lines and spaces are equivalent, so this:
`fn main(){ a := 123 45 println(a) }` is the same as this:
```v
fn main(){
    a := 123
    45
    println(a)
}
```
which *is a valid V program* (although admittedly not very useful one, since the 45 is just an expression that is evaluated, then discarded immediately.

Making v produce error messages for the first, but not for the second would be weird, and the second is a valid one.

**Comment by spytheman** [comment]
@medvednikov what do you think?

**Comment by SleepyRoy** [comment]
@spytheman  
Yeah, we should either report errors for code with redundant literals, or accept it. Let Alex decide this.

**Comment by medvednikov** [comment]
@spytheman I agree, your example should result in `45 evaluated but not used`

**Comment by SleepyRoy** [comment]
@medvednikov This means all redundant literals will no longer be allowed. Then what do you think about other redundant expressions? e.g. consider this 
```V
fn main() {
    a := 1
    b := 2
    a+b  // redundant
    println(a*b)
}
```
Should this result in error, or just be accepted and compiled?

**Comment by medvednikov** [comment]
Any unevaluated expression should result in an error

**Comment by SleepyRoy** [comment]
Summary: 
I've updated issue #5056 according to Alex's reply that both unevaluated and evaluated but not used expressions should result in error.
Close this PR as it just targets a special case of this issue.

**Pull request closed without merging**
