### PR TITLE
scanner: warn when using `'$f()'` and suggest alternatives

### PR DESCRIPTION
**Pull request by ntrel**
See https://github.com/vlang/v/pull/6166#issuecomment-676282111. Suggest using `${f()}` or `$name\()` instead (in case it wasn't supposed to be a function call).

Also:
* Add Scanner.warn() method
* fmt: generate braces for `'$f()'`
* Add `vlib/v/gen/comptime.v` to CI `vfmt -verify`

### CODE REVIEW

**Comment by JalonSolov** [comment]
I don't think it should allow `$f\()` syntax at all.  Already have `${f()}`, and V is supposed to be "one way", so no need for a second syntax.

**Comment by medvednikov** [comment]
Yes, I commented on this in the other PR. No need to make the interpolation syntax more complicated.

**Comment by ntrel** [comment]
@jalonsolov
> no need for a second syntax.

There is no second syntax, it's standard character escaping in a string.

**Comment by Delta456** [comment]
@ntrel I think it also looks uglier as compared `${f()}`.

**Comment by ntrel** [comment]
@Delta456 This pull does not add alternative syntax.

**Comment by ntrel** [comment]
@medvednikov I think this will cause a lot of warnings, so perhaps it's best just to do #6179. A function call without arguments is not that complex.

**Comment by medvednikov** [comment]
`${f()}` and `$f()` is enough. No need in complicating this by adding escapes. Instead of `$name\()` the developer can use `${name}()`.

`$name\()` has to be removed from the language.

**Pull request closed without merging**
