### PR TITLE
http.get and http.post should return ?string. Fix #1352

### LINKED ISSUE #1352: Example using http does not compile
**V version:** 
```
$ v version
V 0.1.16
$
```

**OS:** 
WSL Ubuntu 18.04 LTS (Native Host Win x64.)

**What did you do?**
Typed this code into `test.v` (originally copied from vlang.io)
```v
import time
import http

fn main() {
        data := http.get('https://vlang.io/utc_now') or {
                println('failed to read data')
                return
        }
        println(data)
        // The original produces: Fn "time.unix" wrong arg #1. Expected "int" (u)  but got "string"
        /*
        t := time.unix(data)
        println(t.clean())
        */
}
```

**What did you expect to see?**
Compile successfully and produce `test` executable binary.
 
**What did you see instead?**
```
$ v test.v
.test.c: In function ‘main’:
.test.c:5576:12: error: ‘string {aka struct string}’ has no member named ‘ok’
  if (!tmp1 .ok) {
            ^
.test.c:5577:20: error: ‘string {aka struct string}’ has no member named ‘error’
  string err = tmp1 . error;
                    ^
.test.c:5584:32: error: ‘string {aka struct string}’ has no member named ‘data’
  string data = *(string*) tmp1 . data;
                                ^
V panic: clang error
```

### PR DESCRIPTION
**Pull request by spytheman**
This fixes issue #1352 .

### CODE REVIEW

**Comment by avitkauskas** [comment]
I think the issue is deeper here - req.do still returns empty string as response body on unsuccessful request, but it should also return an optional with the `?string` in the body.

**Comment by joe-conigliaro** [comment]
they really should return response struct, with response code and headers

**Comment by spytheman** [comment]
I think that it may be valuable to have simplified wrappers like http.get and http.post, that do not expose the underlying Response struct.

**Comment by spytheman** [comment]
On the other hand, returning a ?string is also a complication over returning just string, and dealing with http (or any network) is inherently prone to errors, so you may be right.

**Comment by joe-conigliaro** [comment]
I guess if we add a request method that returns a response that would make sense. But still if you do a get and you can't even see what response code or hearers you got its a bit limiting

**Comment by joe-conigliaro** [comment]
I think calling the request method response is a tad confusing. Since your making a request which returns a response? your not responding to something? htmm

**Comment by Tetralux** [comment]
This says it'll fix #1352. Does that mean that V's typechecking is broken and is allowing `or` to be used on a `string`, only to then have clang notice and error instead?

**Comment by medvednikov** [comment]
Thanks, I'll merge this for now, but all functions should indeed return `?Response`.

@Tetralux it's just a minor bug with `or`. Will fix soon.

**Pull request merged**
