### PR TITLE
tools/vcomplete: add fish auto completion support

### PR DESCRIPTION
**Pull request by Larpon**
As title states - support for `fish` auto-completion.

I don't use `fish` personally so I've done this "in the blind" via a small Docker container (like I did with zsh).

Users of `fish` will most likely have to chip in.

To get it to work add these lines to your `~/.config/fish/config.fish`:
```
v complete setup fish | source
```

Some [sources describe](https://sw.kovidgoyal.net/kitty/#fish) that fish versions >3.0.0 will source completions automatically - however I haven't been able to confirm this in the version of fish I used in the Docker dev environment.

### CODE REVIEW

**Comment by donnisnoni** [comment]
Great work @Larpon !! Fish user here :smile:

**Comment by donnisnoni** [comment]
Just need descriptions...but sure it will later

**Comment by Larpon** [comment]
@donnisnoni - awesome news! Thanks for testing!

**Comment by medvednikov** [comment]
Thanks!

Is it possible to make this work without manually adding `v complete setup fish | source`?

I guess we can just make the compiler detect the environment on first run and add this.

**Comment by Larpon** [comment]
> Thanks!
> 
> Is it possible to make this work without manually adding `v complete setup fish | source`?
> 
> I guess we can just make the compiler detect the environment on first run and add this.

@medvednikov 
Hmm... if we can detect the shell at runtime I guess we could let V bootstrap whatever shell completion at first run pr. process id? It will unfortunately shave off some ms at that first run.

Or am I misunderstanding something?

**Pull request merged**
