### PR TITLE
checker: check filter, map and sort left type

### LINKED ISSUE #6902: c error: calling filter() on a string
OS: windows, Microsoft Windows 7 Professional v7601 64-bit
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
CC version: N/A

vroot: C:\v
vexe: C:\v\v.exe
vexe mtime: 2020-11-15 19:42:21
is vroot writable: true
V full version: V 0.1.29 6ad5ecf.20bec81

Git version: git version 2.25.0.windows.1
Git vroot status: latest-commit-347-g155aa6da
.git/config present: true
thirdparty/tcc: N/A

**What did you do?**
```v
fn main() {
	str := 'abc'
	str.filter(it == `a`)
}
```

**What did you expect to see?**
running code or a proper error.
 
**What did you see instead?**
```
==================
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27039 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl -w /we4013 /volatile:ms /Fo"C:\Users\brian\AppData\Local\Temp\v\tmp.10519926342954220763.tmp.c.obj" /MDd "C:\Users\brian\AppData\Local\Temp\v\tmp.10519926342954220763.tmp.c" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared" kernel32.lib user32.lib advapi32.lib dbghelp.lib /link /NOLOGO /OUT:"C:\v\tmp.exe" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\X64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\X64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\X64" /DEBUG:FULL

tmp.10519926342954220763.tmp.c
C:\Users\brian\AppData\Local\Temp\v\tmp.10519926342954220763.tmp.c(8187): error C2065: 'it': undeclared identifier
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### PR DESCRIPTION
**Pull request by danieldaeschle**
Fixes #6902

### CODE REVIEW

**Comment by medvednikov** [comment]
I said this in another related issue, but `string.filter()` should not be allowed.

It is unclear what this function should return, and it complicates the language.

If the user needs to filter runes or bytes they can cast: `s.bytes().filter()`.

**Comment by JalonSolov** [comment]
Runes can be multiple bytes, since they're UTF-8 characters.  Casting to bytes then applying filter could be disastrous.

**Comment by Delta456** [comment]
Yes

**Comment by danieldaeschle** [comment]
@medvednikov it's not allowed. That's why it throws an error and is used as a test. ^^

**Pull request merged**
