### PR TITLE
Make byte.hex() two digits format

### PR DESCRIPTION
**Pull request by duarteroso**
I was playing around with [whirlpool](https://en.wikipedia.org/wiki/Whirlpool_(hash_function)) and noticed that the byte.hex() function did not return the second digit for anything below 15 (F).

Proposing to have it always return in the double digit (0F) hex format to be consistent.

### CODE REVIEW

**Comment by JalonSolov** [comment]
You also have to fix the tests that are expecting it to be a single hex digit.

**Comment by duarteroso** [comment]
Sure, I'm more interested in the discussion at this point. If the change is refused no point in fixing the tests 👍

**Comment by spytheman** [comment]
My personal preference, is that all of the `.hex()` methods, should return fixed length strings *with leading zeroes*, i.e. len = 2 for byte, len = 4 for u16, len = 8 for u32 and len = 16 for u64. 
This will be more consistent, and I think more useful too.

**Comment by spytheman** [comment]
@medvednikov what do you think?

**Comment by penguindark** [comment]
It was an old discussion.
My personal preference go to have only the non zero digits as result for the following reasons:
- obtain a desidered number of digit is very simple with string interpolation or using `strconv`
- obtain the number of non zero digits not require extra calcualtion

Other solution can be implement a "non zero leading" `hex()` function.
Anyway the final decision is up to @medvednikov

**Comment by spytheman** [comment]
@penguindark the question/PR is specifically for .hex(), not for .str() . 

Both the existing implementation, and the new one from the PR do not depend on the more complex strconv, or string interpolation. Using either of them, will be both slower, and cause more memory allocations, than just doing a simple conversion loop in a static buffer on the stack, then doing a single memdup call to produce the final result on the heap. I've added both u64_to_hex/2 and u64_to_hex_no_leading_zeros/2 internal functions, so switching/choosing which one to call in each method is easy to do, without further duplication of the same algorithm.

Stripping the leading zeros is also very easy with `byte(x).hex().trim_left('0')`.

**Comment by penguindark** [comment]
@spytheman 
Ok no problem, if I remember well I'had implemented all the version of `hex` in the `builtin/int.v` :smile:

**Comment by duarteroso** [comment]
Any update on the matter, before I publish my package relying on the "0x##" format?

**Comment by medvednikov** [comment]
Sorry for the delay, I had no strong opinion on this.

After some research I think there should be no leading zeroes, or it should have `0x` prepended.

In Python `hex(1) == '0x1'`, in Go `fmt.Sprintf("%x", 1) == "1"`.

**Comment by medvednikov** [comment]
If the user needs leading zeroes, they can simply use `%02x` formatting

**Comment by duarteroso** [comment]
> If the user needs leading zeroes, they can simply use `%02x` formatting

I was unaware there was formatting support, it solves the problem the C way.
Perhaps @spytheman suggestion could be made a helper function(s) for those who do have a strong opinion? :)

**Comment by medvednikov** [comment]
`1.hex()` will most likely return `0x1` in the future

**Pull request merged**
