### PR TITLE
freebsd: backtrace support

### PR DESCRIPTION
**Pull request by Martinfx**
* support for backtarce on freebsd platform
* support for freebsd platform in vlang language

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks!

There's a conflict in Makefile.

Also does github actions support freebsd?  On their features page they only mention Linux, macOS, Windows.

**Comment by medvednikov** [comment]
@Martinfx so github doesn't support freebsd after all?

**Comment by Martinfx** [comment]
@medvednikov I think that no.

**Comment by Martinfx** [comment]
@medvednikov Also is problem with docker files, but travis maybe have better some support

**Comment by Martinfx** [comment]
@medvednikov but still have bsd have regression with `V panic: Permission denied`

**Pull request merged**
