### PR TITLE
net: add unix sockets

### PR DESCRIPTION
**Pull request by Casper64**
This pr adds support for unix domain sockets.

The code for reading and writing to the socket is almost exactly like the code from `net.TcpConn`. Unix sockets are supported on all operating systems (windows since 2017 [article](https://blogs.windows.com/windows-insider/2017/12/19/announcing-windows-10-insider-preview-build-17063-pc/)).

Unix sockets also work with coroutines.

## Example

```v
module main

import net
import os

const (
	socket_path = os.vtmp_dir() + '/v_unix.sock'
)

fn main() {
	mut server := net.listen_unix(.tcp, socket_path)!
	// remove unix socket from fs when CTRL+C is pressed
	server.unlink_on_signal(.int)!
	eprintln('started listening for connection on "${socket_path}", ${server.addr()!}')
	
	for {
		mut conn := server.accept()!
		eprintln('accepted connection')
		handle_conn(mut conn)!
	}

	server.close() or {}
}

fn handle_conn(mut conn &net.UnixConn) ! {
	defer {
		eprintln('closed connection ${conn.sock.handle}!')
		conn.close() or {}
	}

	for {
		mut buf := []u8{len: 4096}
		r := conn.read(mut buf) or { break }
		if r == 0 {
			break
		}

		print('sock ${conn.sock.handle}: ${buf.bytestr()}')
		// echo back
		conn.write_string('ret: ${buf.bytestr()}')!
	}
}
```

Connect with netcat:
```
or nc -U /tmp/v_1000/v_unix.sock 
```
or
```
ncat -U /tmp/v_1000/v_unix.sock
```

### <samp>🤖 Generated by Copilot at a7dbee8</samp>

This pull request adds support for Unix domain sockets in the `net` module, by implementing the `close` method for `net.UnixListener` and adding a test file for `net.UnixListener` and `net.UnixConn`.

### <samp>🤖 Generated by Copilot at a7dbee8</samp>

*  Declare `unlink` C function to remove files or links ([link](https://github.com/vlang/v/pull/19824/files?diff=unified&w=0#diff-b5608ed9e159b851e08847918935530711c73c782b5730d6adf145f39d370e2bR31-R32))

### CODE REVIEW

**Comment by shove70** [comment]
https://github.com/vlang/v/tree/master/vlib/net/unix

I think need to think about this one

**Comment by JalonSolov** [comment]
Why call them "unix sockets" if Windows supports them, too?  Why not "raw sockets" or just "sockets"?

**Comment by Casper64** [comment]
> https://github.com/vlang/v/tree/master/vlib/net/unix
> 
> 
> 
> I think need to think about this one

Oh wow never noticed this module ...

**Comment by shove70** [comment]
> Why call them "unix sockets" if Windows supports them, too? Why not "raw sockets" or just "sockets"?

Unix sockets are used for local inter-process communication and are cheaper than using net sockets, it is not network sockets.
Is based on the file system implementation.

**Comment by Casper64** [comment]
> Why call them "unix sockets" if Windows supports them, too?  Why not "raw sockets" or just "sockets"?

That is just the technical name ("unix domain sockets"), because the sockets are actually files in the filesystem, also on windows. That is why even windows docs use the name "unix domain sockets"

**Comment by shove70** [comment]
> > https://github.com/vlang/v/tree/master/vlib/net/unix
> > I think need to think about this one
> 
> Oh wow never noticed this module ...

maybe possible to build on it, to combine it, to improve it

**Comment by Casper64** [comment]
I'll add my updates to the net/unix module and close this pull request.

**Pull request closed without merging**
