### PR TITLE
map: add unset & index methods

### PR DESCRIPTION
**Pull request by ielijose**
```
mut fruits := map[string]string{}

fruits['banana'] = '🍌'
fruits['apple'] = '🍎'
fruits['orange'] = '🍊'

fruits['pizza'] = '🍕' // 🤔🤔🤔

println(fruits)
/*
  {
    "banana" => "🍌"
    "apple" => "🍎"
    "orange" => "🍊"
    "pizza" => "🍕"
  }
*/
// ❌❌❌
pizzaIndex := fruits.index('pizza')
println('Pizza: $pizzaIndex')
// Pizza: 3

fruits.unset(pizzaIndex)

println(fruits)
/*
  {
    "banana" => "🍌"
    "apple" => "🍎"
    "orange" => "🍊"
  }
*/
// ✅✅✅

### CODE REVIEW

**Comment by AurelienFT** [comment]
maybe unset with name and free the value when remove the entry ?

**Comment by ielijose** [comment]
> maybe unset with name and free the value when remove the entry ?

Hello @AurelienFT what means "free the value"?

**Comment by AurelienFT** [comment]
Use free to free the value associate to the entry

**Comment by ielijose** [comment]
Great, I'll try. Thanks

**Comment by ielijose** [comment]
> Use free to free the value associate to the entry

done!

**Comment by ntrel** [comment]
I don't think the index of a value should be exposed, that's an implementation detail. The user might rely on an element having a certain index, then when adding elements the index can change or the implementation can change the index. Instead I'd have m.remove(key).

**Comment by medvednikov** [comment]
Yeah, I don't see the point in `.index()` either.

**Comment by ntrel** [comment]
Also both these functions are O(n).

**Pull request closed without merging**
