### PR TITLE
net.html: fix semantic inconsistencies of tag retrieving functions

### PR DESCRIPTION
**Pull request by tobealive**
This PR addresses semantic inconsistencies in the html module.

The main change is about consistent usage of "tag" and "tag**s**".
In `html/dom.v` we currently have functions such as `get_tag_by_attribute` and `get_tags_by_class_name`, both of which return an array of tags. While in `html/tag.v` all functions that return an array of tags are named `get_tags_...` and functions returning a single ?&Tag are named `get_tag_...`.

To achieve consistency the `get_tag_...` functions returning arrays of tags were marked as deprecated and refer to their added `get_tags_...` equivalents.
~~This includes a small breaking change for `get_tags`, which currently retrieves all the tags in the document without taking additional arguments. It was renamed to `get_all_tags`, allowing to use `get_tags(name string)` like it is done in `html/tag.v`~~

The other changes fix phrasing in the doc comments of the tag retrieving functions and sort the functions in `html/dom.v`. 

~~Since it includes a breaking change,~~ I'm not making this PR suggestion with high expectations of it being merged. Imho was just was easier and more practical to provide a potential result to review and work with, rather than starting a theoretical explanation of the problem. Trying to write this short theoretical description with it's consecutive explanations of slightly differing things and aiming not to be confusing just reinforced the practial approach for me. So the changes are hopefully clear when looking at them per commit or as a whole.

### CODE REVIEW

**Comment by JalonSolov** [comment]
As an alternative... you could change `get_all_tags` back to `get_tags`, but make it take a `[params]` struct as the parameter.  This means it will still be fine to pass it nothing at all, or you could pass it various options.  For instance, if you only wanted `img` tags, you could call `get_tags(type: .img)` or something along those lines.

**Comment by tobealive** [comment]
Sounds like a nice feature. I'll look into it. Thanks @JalonSolov

**Comment by tobealive** [comment]
Hey @JalonSolov 
Thinking about an implementation of the params struct, the result seems to be neither fish nor fowl.

A natural extension of the prams struct would be to also include fields like class and attribute - which you might also thought of and implied of in your last answer. So in theory, it could be used as a general alternative for the cases when a user doesn't want to chain the get_tag_ methods that we currently have but to select a tag very specifically adding name, class etc. all at once. 

But wouldn't this just be a bad and verbose implementation of a queryselector
like `querySelector('div.user-panel.main input[name="login"]');`. It'a a common thing in many langs to have such a cssselect or queryselector. But usually as third party library.

So atm I have some cognitive dissonance implementing the alternative suggestion and thinking it's the right thing to do. How we currently handle things most right thing seems to be to just fix the inconsistencies, and keep the ux with the tag selectors as it is.

**Comment by JalonSolov** [comment]
Then the simplest thing would be to make a params struct that just had a `name` field.  Then it could be used as it is now, as well as the way you made the new function.

**Comment by JalonSolov** [comment]
You could of course go crazy with it... add a way to only get tags whose names start with what you pass, end with what you pass, or have what you pass anywhere in them.

You could also implement a full `jquery` still selector.  :-)

**Comment by tobealive** [comment]
Was not certain if this would be too unfinished this way, but actually, why not. I'll add it when I have a free moment this evening, else tomorrow. Thanks for the input @JalonSolov :+1:

**Comment by JalonSolov** [comment]
The main reason to do it this way is to avoid the breaking change you mentioned earlier, with as few changed to the existing code as possible.

**Comment by JalonSolov** [comment]
Hopefully they know enough to look up `get_tags` if they see they're supposed to use it instead.  However, yes, perhaps the messages could be a little more verbose.

**Comment by tobealive** [comment]
I see your point @Wajinn. As people often have some troubles with the current lsp it might be not as smooth looking such things up until the new analyzer is out. I had a similar thought about updating the deprecating warning, but my switch flipped to late this time. When being involved in similar changes time I'll also be more aware.

**Pull request merged**
