### PR TITLE
json: add primitive type validation

### LINKED ISSUE #23021: JSON decode function does not return error on invalid type
**V doctor:**

```
V full version: V 0.4.8 e4d24e8.602b097
OS: linux, Linux version 6.11.10-300.fc41.x86_64 (mockbuild@f7de5c49aa4447a197116d46c5346643) (gcc (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3), GNU ld version 2.43.1-2.fc41) #1 SMP PREEMPT_DYNAMIC Sat Nov 23 00:51:20 UTC 2024
Processor: 6 cpus, 64bit, little endian, AMD Ryzen 5 4500U with Radeon Graphics

getwd: /home/angeljohank/Documents/coding/vlearn
vexe: /home/angeljohank/Documents/utils/v/v
vexe mtime: 2024-11-30 15:59:47

vroot: OK, value: /home/angeljohank/Documents/utils/v
VMODULES: OK, value: /home/angeljohank/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.47.1
Git vroot status: weekly.2024.48-24-g602b097d
.git/config present: true

CC version: cc (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3)
emcc version: N/A
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg src/main.v`

```v
module main

import json

struct MyStruct {
	name int // should fail
}

fn main() {
	obj := '{ "name": "John Doe" }'
	res := json.decode(MyStruct, obj) or { panic(err) }

	println(res)
}
```

**What did you expect to see?**

json.decode function to panic because name is of type string

**What did you see instead?**

```
MyStruct{
    name: 0
}
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRiNmZlOGQyZWY0Y2JjYzQ2Y2VlM2YiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.KD6tAeYA8RvOOQCazGdmf5LKSaA5GMfQB4fBAXOU3oI">Huly&reg;: <b>V_0.6-21462</b></a></sub>

### PR DESCRIPTION
**Pull request by felipensp**
Fix #23021

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVhY2ViYjFlMDYzMmRkMDhlMzQ5MzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.XigmRUC6OgaIOAHvodaPGX8o1RBh0Lk3Gn-rGwlfeRc">Huly&reg;: <b>V_0.6-21579</b></a></sub>

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by spytheman** [comment]
I think that c2v fails, because it uses json to parse the output of the clang AST nodes.

**Comment by felipensp** [comment]
> I think that c2v fails, because it uses json to parse the output of the clang AST nodes.

I just added a sumtype to handle the int and string cases, seems have fixed it.

**Comment by spytheman** [comment]
> > I think that c2v fails, because it uses json to parse the output of the clang AST nodes.
> 
> I just added a sumtype to handle the int and string cases, seems have fixed it.

Lets hope that only c2v relied on that misfeature, and thus needed a fix :-| .

**Pull request merged**
