### PR TITLE
chacha20: remove deprecated `math.max_u32` in favour of builtin `max_u32`

### PR DESCRIPTION
**Pull request by blackshirt**
This small pull request fixs some spurious warning within `x.crypto.chacha20` something related to deprecated constant from `math.max_u32` with warning message : 
```warning: const `math.max_u32` has been deprecated since 2023-12-31, it will be an error after 2024-06-28; use built-in constant `max_u32` instead```

Besides changing to the builtin `max_u32`, this pull request also includes some bits of cleaning and restructuring:
- removes some bits of test data and move into core `chacha20_test.v` file, and deletes `test_data` from repo.
- removes unnecessary bits from `common.v` something related to poly1305 one-time key generation, its already built into this module.
- moves some helper and core functions from `common.v` to the core `chacha.v` and delete `common.v` from repo.

Thanks

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by blackshirt** [comment]
> Excellent work.

Thank you

**Comment by joe-conigliaro** [comment]
Thanks @blackshirt

**Comment by blackshirt** [comment]
> Thanks @blackshirt

You're welcome

**Pull request merged**
