### PR TITLE
os: fix read_lines

### LINKED ISSUE #1044: os.read_lines function lost the last character
**V version:*0.1.12* 
**OS:*Mac 10.14.5* 

**What did you do?**
read lines from file for this code: 

// main.v
```
module main
import os

fn main()
{
    filename := 'hello.txt'

    lines := os.read_lines(filename)

    mut i:=1
    for line in lines {
        println(i.str() + ': $line')
        i++
    }
}
```

// hello.txt (Only two lines)
hello kinner!
This is a test file

**What did you expect to see?**
1: hello kinner!
2: This is a test file
 
**What did you see instead?**
1: hello kinner!
2: This is a test fil

### PR DESCRIPTION
**Pull request by avitkauskas**
Fixes #1044 ("eating" the last character of the last line if the file does not end with the new line).

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks.


`val +=` is very expensive (see Shlemiel the painter). Byte buffers should be used in this function.

**Comment by cytown** [comment]
Please check https://github.com/vlang/v/pull/1056, I think it's better with buffer.

**Comment by avitkauskas** [comment]
OK, I changed it to only fix the problem when the file does not end with the new line.

**Comment by avitkauskas** [comment]
Some side questions:
- should we care about the hard coded temporary buffer size (1000)?; if the line in the file is longer, we would get more then one line for this long line in the file;
- if we care about that, how should we realocate the buffer to make it bigger? fall back to C.realloc? is there a way in V to do that?
- there was `unused mut val := ''` in the original code; why did it compiled?

**Comment by cytown** [comment]
buffer size 1000 should be fixed, totally agree.
looks compiler has bug for unused code detect.

**Comment by cytown** [comment]
@avitkauskas please check https://github.com/vlang/v/pull/1056

**Comment by avitkauskas** [comment]
Solved buffer size issue by realocating bigger buffer at need.
Also made @ntrel change request for only one strlen call.

**Comment by medvednikov** [comment]
Sorry for the delay. It seems to have been fixed. Can you have a look?

**Comment by avitkauskas** [comment]
@medvednikov No, it was not fixed yet. Solved the merge conflicts now. Please look at it.

**Comment by medvednikov** [comment]
Ok, that particular example worked fine for me.

Will merge now, thanks.

**Comment by medvednikov** [comment]
You still have `<<<<<<< HEAD`

**Comment by avitkauskas** [comment]
I am not sure from where. But its just a comment.

**Comment by medvednikov** [comment]
https://github.com/vlang/v/pull/1050/files#diff-ff703b17e5a3032145b9228464e30da5R614

**Comment by medvednikov** [comment]
Also can you supply a text file that triggers the bug?

**Comment by avitkauskas** [comment]
Fixed. Fine now.

**Comment by avitkauskas** [comment]
Any file that did not end with the `\n` triggered the bug before the fix.

**Comment by medvednikov** [comment]
It works fine for me on all 3 platforms. Can you send me the file you experience it with?

**Comment by avitkauskas** [comment]
Sent you files via email.

**Comment by avitkauskas** [comment]
@medvednikov, this really can be merged; the bug with the last line without the `\n` is real and this PR fixes it as well as eliminates the hardcoded read buffer issue.

**Pull request merged**
