### PR TITLE
termios: new termios module

### PR DESCRIPTION
**Pull request by thomas-mangin**
move the tcgetattr and tcsetattr functions in a new termio module. The code needed refactoring as different OS have different fields size, position and number for the C.termios structure, which could not be correctly expressed consitently otherwise.

It has the positive side effect to reduce the number of unsafe calls. New testing code was also added for the readline module as it is relying of the feature.

### CODE REVIEW

**Comment by thomas-mangin** [comment]
This is a the same PR as previously (and probably with the same issue with cyclic reference) but Github had an issue which lead me to delete and re-create my v fork (deleting it was fine but due to the issue I had to wait to be able to re-create it). Oh fun.

**Comment by Delta456** [comment]
Run ` v fmt -w vlib/term/termios/termios_linux.c.v`

**Comment by thomas-mangin** [comment]
@Delta456 indeed, thank you, and some public functions had no comments. Working on passing the test suite :-)

**Review by spytheman — APPROVED** [review]
Excellent work.

**Pull request merged**
