### PR TITLE
 all: propagate optional

### PR DESCRIPTION
**Pull request by Gladear**
Allow using `?` to propagate optionals.
With this PR, `main` is handled the same as other functions, which means that you can't propagate an optional because it doesn't return an optional.

### CODE REVIEW

**Comment by spytheman** [comment]
I think that at the top level (i.e. main), `optfn()?` should also be allowed.
In this case (and only in this case), it should act as `optfn() or { panic(err) }` .

**Comment by Gladear** [comment]
It's what I remembered too, but I wasn't sure and I didn't have the time to do it now anyway ^^
I'll add that later today or tomorrow

**Comment by medvednikov** [comment]
foo()?  already worked in fn main()

**Comment by Gladear** [comment]
@medvednikov You mean with the new backend ? It didn't work for me

**Comment by medvednikov** [comment]
This worked before your PR:

```

fn foo() ?int {
        return 0
}

fn main() {
        foo()?
}
```

**Comment by Gladear** [comment]
It worked, but it didn't panic, isn't that the expected behavior ?

**Comment by medvednikov** [comment]
Ah, indeed :)

**Pull request merged**
