### PR TITLE
Generic methods

### LINKED ISSUE #2529: Add support for generic methods
```v
fn (handle &C.CURL) setopt<T>(opt int, param T) {}
```

### PR DESCRIPTION
**Pull request by shsr04**
Now methods can also be generic (of course, excluding the receiver argument). (Fixes #2529)

For example:
```v
struct Obj {}

fn (o Obj) read_data<T>(x T[]) { ... }
```

Bonus: cast to type param works now

### CODE REVIEW

**Comment by shsr04** [comment]
@medvednikov Again, the step `Test v->js` is failing. Doesn't make sense because the build and tests were all successful...

**Comment by medvednikov** [comment]
I'm having a look

**Comment by medvednikov** [comment]
@shsr04 when you have a minute, can you please have a look at vweb?

`v examples/vweb/test_vweb_app.v`

```
mut app := App{}
vweb.run(app, port)
```

There's an index out of range in `dispatch_generic_fn_instance()` (in `fn main()`)

It used to work with the old generics.

**Comment by shsr04** [comment]
@medvednikov Strange.. it even crashes for the old generics for me. I think there is a problem when importing a generic function. For each imported file, the `tokens` are cleared (or so it looks), therefore we can't shift around the tokens to instantiate the generic functions.

**Comment by medvednikov** [comment]
Each file has its own Parser object with a unique tokens array.

**Comment by shsr04** [comment]
Yes, that's why it should have been failing from the start. This could actually become a huge problem..

**Pull request merged**
