### PR TITLE
web: create http server

### PR DESCRIPTION
**Pull request by justicesuh**
Add a web module to host an HTTP server.  Not production ready.  Currently supports only `GET` requests and ignores most headers

Doesn't work on Windows yet due to lack of `fork()`.  Windows support could probably be added via `popen` or `CreateProcess`

Create an `index.html` and `style.css` in `VROOT`

```
<!DOCTYPE html>
<html>
  <head>
    <title>HTTP Demo</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    <h1>Hello World</h1>
  </body>
</html>
```

```
h1 {
    color: #ff0000;
}
```

Create `server.v`

```
import web

fn main() {
    s := s.server(8080)
    s.serve()
}
```

`localhost:8080` should now show a red `Hello World`

### CODE REVIEW

**Comment by iredmail** [comment]
Awesome. :)

What’s the plan of this “web” module?

**Comment by justicesuh** [comment]
A web server that implements HTTP/1.1

Down the line I think a web framework would be cool, but that's probably beyond `vlib` and is its own project.

**Comment by iredmail** [comment]
I believe Alex has a module called vweb pending to commit, it’s a web framework. 

Your “web” module name doesn’t clearly reflect the function, maybe call it “http_server”?

**Comment by iredmail** [comment]
Btw, Is it better to keep this as a third-party repo/project and not V builtin module?

**Comment by justicesuh** [comment]
I was going to put it in `http.server` but there's been talks about removing the `http` dependency on `libcurl` so I didn't want to deal with possible merge conflicts.  

@medvednikov thoughts on putting this in `vlib` versus as a third party project?

**Comment by joe-conigliaro** [comment]
I think this should be kept in a separate repository, maybe if it was abstracted more we could have a basic HTTP listener and server in vlib but a full web server should be seperate repo and built on top. Just mu thoughts

**Comment by medvednikov** [comment]
I'll release vweb very soon. It has an http server built in.

We'll merge our progress.

**Comment by justicesuh** [comment]
Cool.  I'll close this PR and then rebase when vweb is out

**Comment by esquerbatua** [comment]
That will not be necessary to waste. Maybe as socket and file examples?

**Comment by medvednikov** [comment]
@justicesuh 

vweb is out. https://github.com/vlang/v/tree/master/vlib/vweb

**Pull request closed without merging**
