### PR TITLE
doc: minor update for string interpolation

### PR DESCRIPTION
**Pull request by JalonSolov**
Minor changes to unchecked text regarding use of ${} in strings.

### CODE REVIEW

**Comment by morrig-n** [comment]
I may be wrong, but wasn't the documentation correct beforehand? 

'$variable' is perfectly valid V code, and, as the documentation stated, ${} can then be used for more complex interpolation.

I feel like removing any reference to interpolation without {} could lead to confusion in this regard.

**Comment by JalonSolov** [comment]
No, it's not valid any longer, as of a PR merged today.  `${}` is the only valid interpolation now.

**Comment by morrig-n** [comment]
Ah yeah, my mistake. Sorry about that

**Review by spytheman — APPROVED** [review]
Not sure, if we should mention, that `$x` is still supported for compatibility for a few months, and that `v fmt -w source.v` will convert the old source, to the new format automatically?

**Comment by spytheman** [comment]
> V should be giving a deprecation message about just $x until it's taken away.

That could be a notice, yes.

**Comment by spytheman** [comment]
OK, seems that this PR is complete. The notice could be done separately. Merging.

**Pull request merged**
