### PR TITLE
math : add error and gamma functions

### PR DESCRIPTION
**Pull request by eulerkochy**
add `erf`, `erfc`, `gamma` and `log_gamma` functions to `math.v` and add tests for the same

### CODE REVIEW

**Comment by medvednikov** [comment]
Can you please sort the functions alphabetically?

I've added a note to math.v

**Comment by eulerkochy** [comment]
@medvednikov there are lot of functions in `math.v` itself rn, that aren't in alphabetical order. Should I correct it in PR ?

**Comment by medvednikov** [comment]
As you wish. You can just order your functions, I'll order the rest.

Or you can order them all and save me a couple of minutes :)

**Comment by medvednikov** [comment]
Thanks

**Pull request merged**
