### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Xiphin**
- Updated V version number
- Modified the build step instructions

**Purpose of PR:**

Make the build step instructions clearer

### CODE REVIEW

**Comment by Xiphin** [comment]
@medvednikov

**Comment by Bowero** [comment]
The version numbering should be done in another way.

**Comment by medvednikov** [comment]
how about 0.1.x? :)

**Comment by whoizit** [comment]
`v.c` and `v` compile the same binary. As long as there is no difference, we can omit this step.

**Pull request closed without merging**
