### PR TITLE
map: use strcmp and update wyhash

### PR DESCRIPTION
**Pull request by ka-weihe**
I changed string-comparisons to `C.strcmp` instead of the current `string.compare`, because it improved performance a lot. Wyhash has been updated to the newest version, that does not have mem-errors. Thank you @dumblob for pointing this out.

### CODE REVIEW

**Comment by yuyi98** [comment]
@medvednikov   Use `C.strcmp` doesn't improved performance, It's not taking advantage of string and didn't use the len attribute to pre-judge whether it was the same string, and there are more system calls.

**Comment by vitalyster** [comment]
This can also break non-latin keys/values on Windows

**Comment by ka-weihe** [comment]
> Use C.strcmp doesn't improved performance

This is simply not true. You don't know the context in which it was used. For all of these checks, the strings are almost guaranteed to be equal, because the hashes match, so using the len attribute is unnecessary and slows the code. I benchmarked it and it was a lot faster. My plan is to maybe use something faster than `C.strcmp` but `string.eq` is not that.

 > This can also break non-latin keys/values on Windows

No it can't. It literally just checks the equality of the bytes.

**Comment by yuyi98** [comment]
@ka-weihe   Sorry, I'm just thinking theoretically that this is. I hope your PR can improve performance.
If so, can you provide performance comparison data?

**Comment by dumblob** [comment]
@ka-weihe when already at optimizing, wouldn't `C.memcmp` (since C89) be even faster?

**Comment by ka-weihe** [comment]
@yuyi98 it's totally fine. Here is a quick benchmark for you. I inserted 30000000 string of length 20, and timed the get of all 30000000.
```
strcmp: 2528 ms
string.eq: 3661 ms
```
@dumblob I'll test it, but then again I would have to check if the strings have equal length before.

**Pull request merged**
