### PR TITLE
ci: limit on push to master

### PR DESCRIPTION
**Pull request by danieldaeschle**

### CODE REVIEW

**Comment by spytheman** [comment]
That will fail for commits on different branches.

**Comment by danieldaeschle** [comment]
I know. I wanted to remove CI runs for other branches. Thought we don't need it.

**Comment by medvednikov** [comment]
CI for other branches on non-master for vlang/v is ok. I thought we already had that.

**Comment by medvednikov** [comment]
@danieldaeschle can you remove the formatter though? the diff gets too big, and I don't like "" :)

**Pull request closed without merging**
