### PR TITLE
sync.once: add Once

### PR DESCRIPTION
**Pull request by Taillook**
add sync.Once struct.
There are times when you want to call a function only once.
And I think there's a demand for it.

### CODE REVIEW

**Comment by Larpon** [comment]
🤔 why not have a way to call it X times instead and then set that you want X to be only once? I.e. a way to do 5 or 25 or 1- that's more flexible?

**Comment by Taillook** [comment]
Sure, that sounds good.
The more flexible the usage, the better.

**Comment by Taillook** [comment]
Implemented a x times caller.
I'd love to hear different opinions on this.

**Comment by spytheman** [comment]
The Go variant allows for just 1 execution: <https://pkg.go.dev/sync#Once>, and it is even in the name. 
Imho we should also allow only one execution.
Being more flexible is good, but clarity of intent is also important.

**Comment by spytheman** [comment]
If we do want an Once that can execute its function many times, it can be called ManyTimes?

**Comment by Taillook** [comment]
Is it OK to implement both `Once` and `ManyTimes`?
In that case, I'll separate PullRequests for each.

**Comment by spytheman** [comment]
> Is it OK to implement both `Once` and `ManyTimes`? In that case, I'll separate PullRequests for each.

Imho, yes. Concurrency bugs are not fun/easy to debug, and having a specialized Once is better for both maintenance and for clarity of usage.

**Comment by Larpon** [comment]
Right, I didn't know the Go version existed. I only thought of flexibility 👍

**Pull request merged**
