### PR TITLE
docs: describe object types for concurrent access

### PR DESCRIPTION
**Pull request by UweKrueger**
This PR adds a section to `docs.md` that describes the future keywords `shared` and `atomic` and compares the to `mut` and default declaration. A comparison table and a list of strengths and weaknesses is added is added as decision help.

The chapter is meant to describe WIP and as base for further discussions.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Should this be marked DRAFT, since it is still WIP?

Personally, it seems like this is drifting from the V philosophy of "one way", just with the opening line:

"To handle data exchange between coroutines more there will be 4 different ways to declare a variable:"

In V, there is only _1_ way to declare a variable, `:=`.  Anything added to that is an attribute of the variable.

**Comment by UweKrueger** [comment]
@JalonSolov I was thinking about making this DRAFT, but as far as the doc is concerned I'm not working on it any more (unless there is need for change). The implementation of all this stuff is another question. ;-)

I don't' think that "attribute" is a good term. (There were discussions on `#v-development` and `#syntax` yesterday.) When I look at GCC's documentation about variable  attributes they usually change minor things like alignment or linker section. They do not really affect how the variable is used. The keywords `mut`, `shared` and `atomic` change the semantic.

I agree, there should be *only 1 way* - and there is - the table helps to choose it. It's not a random choice - it depends on what you want to do. Just like the choice between `int`, `f64` and `string` - you can choose, but there is *only 1 way* to make the right decision. ;-)

**Comment by medvednikov** [comment]
Thanks for documenting it, but I also don't think we should document something that's not implemented yet and is going to change. Perhaps create a separate file in the docs directory for upcoming stuff.

**Comment by UweKrueger** [comment]
@medvednikov Yes, that's a good idea. I'll just call it `upcoming.md`.

**Pull request merged**
