### PR TITLE
scanner: fix string slash line breaks error (fix #4157)

### LINKED ISSUE #4157: Escaping whitespace at end of line in multi line string prints a "\n"
**V version:** 0.1.25 e09447d
**OS:** Ubuntu x86_64

**What did you do?**
Executed this code:

```V
fn main () {
    a := 'Hello\
          World'

    println(a)
}
```

**What did you expect to see?**
```
HelloWorld
```
 
**What did you see instead?**
```
Hello\n	      World
```

------------

Happens with `print` or `println` with single or double quotes.

------------

I believe this should work like in [Rust](https://doc.rust-lang.org/reference/tokens.html#string-literals) right?

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix string slash line breaks error (fix #4157).

- Fix string slash line breaks error.
- Add test `slash_line_breaks.vv/out.

```v
fn main() {
	a := 'Hello\
World'
	println(a)
}

D:\test\v\tt1>v run .
HelloWorld
```

### CODE REVIEW

**Comment by spytheman** [comment]
Unfortunately that would not solve #4157 :-| @yuyi98  .

If we want to reproduce Rust's behavior:
```v
fn test_string_literal_with_backslash(){
    a := 'HelloWorld'
    b := 'Hello\
          World'
    assert a == b
}
```
... then the above test should pass, because in their docs https://doc.rust-lang.org/reference/tokens.html#string-literals:
> Both byte sequences are normally translated to U+000A, but as a special exception, when an unescaped U+005C character (\) occurs immediately before the line-break, the U+005C character, the line-break, and all whitespace at the beginning of the next line are ignored. Thus a and b are equal:
```rust
let a = "foobar";
let b = "foo\
         bar";

assert_eq!(a,b);
```

**Comment by spytheman** [comment]
@medvednikov what do you think?

**Comment by yuyi98** [comment]
Sorry, I'll fix it.

**Comment by yuyi98** [comment]
```v
fn main() {
	a := 'Hello\
		World\
		Hi'
	println(a)
	assert a == 'HelloWorldHi'
}

D:\test\v\tt1>v run .
HelloWorldHi
```

**Pull request merged**
