### PR TITLE
Feature os path separator

### PR DESCRIPTION
**Pull request by joe-conigliaro**
This PR adds a filepath module for manipulating paths:
it has the following functions so far:
```
A := filepath.join(['home', 'user', 'docs']) 
B := filepath.split('home/user/docs')
```
- A = 'home/user/docs' (*nix)
- A = 'home\user\docs' (windows)
- B = ['home', 'user', 'docs']
```
OS_PATH_SEP := filepath.separator()
```
- OS_PATH_SEP = /  (*nix)
- OS_PATH_SEP = \  (windows)

Returns the correct path separator for the OS

It also defines constants for the different path separators. 
- PATH_SEPARATOR_NIX = /
- PATH_SEPARATOR_WIN = \

**Most of the hard coded paths (with /) in compiler/main.v have been replaced filepath.join() which uses the correct OS path separator.**

### CODE REVIEW

**Comment by MaD70** [comment]
In the light of what I uncovered in https://github.com/vlang/v/issues/994#issuecomment-508736550, which really surprised myself too, I think this PR needs more pondering.

**Comment by joe-conigliaro** [comment]
@MaD70 yeah the paths still work with forward slashes as mentioned: https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#canonicalizing-separators, but they are normalized to backslashes, which is the way windows separates paths.

This PR just makes sure the path separators are the default for the OS. sure the paths will work either way, but the paths will look all messed up with a mish mash of path separators, and if your using those paths to do something else like put in configs or other places which might not normalise you want to make sure they are standardized.

**Comment by MaD70** [comment]
Sorry, my comment was a bit cryptic. What I intended was: why not use [GetFullPathName function](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew) to normalize a path? As mentioned in [File path formats on Windows systems, Skipping normalization](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#skipping-normalization) Windows itself uses this:
> ### [Skipping normalization](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#skipping-normalization)
> Normally, any path passed to a Windows API is (effectively) passed to the [GetFullPathName function](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew) and normalized

N.B.: they link to [GetFullPathNameA](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamea) but I think is better to use [GetFullPathNameW](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew) to avoid problems with path containing UNICODE characters.

**Comment by joe-conigliaro** [comment]
@MaD70 This isn't to do with normalizing paths, this is just using the correct separator to begin with. And also you don't need to normalize something which is correct to begin with. You don't need to make extra api calls. GetFullPathNameW could defiantly be useful in certain cases for building paths, but you should try and pass it correctly structured paths to begin with.

**Comment by MaD70** [comment]
@joe-conigliaro ok, I understand your reasoning. I was trying to simplify the code, but thinking twice, there is not much to be gained. It is better to use a conditionally set constant for each platform.

**Comment by joe-conigliaro** [comment]
@MaD70 it's right to use the functions you mention when you want to normalize a path on windows. But this isn't about that. this is simply... I need to build a path, I need to use a separator, use the right one to begin with.

**Comment by MaD70** [comment]
@joe-conigliaro yes yes, your PR is simpler and more efficient (otherwise GetFullPathName would be called two times for each path passed to an OS function).

**Comment by joe-conigliaro** [comment]
@MaD70 have a look now, I have made some changes, simplified it, i added a path module.

**Comment by MaD70** [comment]
At the moment I don't have time to check and test it thoroughly, but at first glance everything seems ok.

**Comment by medvednikov** [comment]
Hi,

The module should be called `filepath`. `path` is a too commonly used name, and we can see that even in this PR you had to change lots of code because of the variable `path`.

V works fine on Windows with `/`, so why complicate this and make things slower?

**Comment by MaD70** [comment]
@medvednikov I suggest that you put, well highlighted in the appropriate section of the documentation, a brief explanation with a link to relevant official Microsoft docs (for example [File path formats on Windows systems, Canonicalizing separators](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#canonicalizing-separators)) or you'll end up repeating this times and again.

Unfortunately this is not common knowledge and I can understand why. I'm not sure when `cmd.exe` began to accept `/` as path separator but I'm sure that it was not accepted for a long time. Every time, switching from using Unix to Windows, one used the wrong path separator there was an annoying error message.

**Comment by vitalyster** [comment]
@MaD70 cmd.exe accepting / since beginning in 1993, only command.com does not accept it.

**Comment by MaD70** [comment]
@vitalyster so it were just inertia for compatibility reasons: to avoid to maintain two very similar batch scripts for the old DOS-based Windows and the new NT-based Windows. But the point remains: it's not common knowledge. One needs to know it only for portability reasons (and porting from Windows to a Unix-like system is less common than the other way around).

**Comment by joe-conigliaro** [comment]
@medvednikov I windows works either way but it's still not the correct, the paths look all retarded, and internally windows still normalizes them. if we are constructing paths and saving them places or using them with other scripts it will look strange and could cause probs.
I dunno up to you, close it if you think we dont need

**Comment by joe-conigliaro** [comment]
@medvednikov I changed to filepath either way

**Pull request closed without merging**
