### PR TITLE
scanner: print multibyte char for invalid char error

### PR DESCRIPTION
**Pull request by zakuro9715**
print broken error message for invalid char error now.

```
vlib/v/checker/tests/invalid_char_err.vv:1:1: error: invalid character `
    1 | 🐈println('')
      | ^
```

This PR fix this to

```
vlib/v/checker/tests/invalid_char_err.vv:1:1: error: invalid_character `🐈`
    1 | 🐈println('')
      | ^
```

### CODE REVIEW

**Comment by zakuro9715** [comment]
Why some CIs are failed? I have no idea

**Comment by StunxFS** [comment]
@zakuro9715 
```
FAIL  [265/474]    33.457 ms vlib/v/checker/tests/invalid_char_err.vv
============
failed cmd: /home/runner/work/v/v/v -prod vlib/v/checker/tests/invalid_char_err.vv
expected_out_path: vlib/v/checker/tests/invalid_char_err.out
============
expected:
vlib/v/checker/tests/invalid_char_err.vv:1:1: error: invalid_character `🐈`
    1 | 🐈println('')
      | ^
============
found:
vlib/v/checker/tests/invalid_char_err.vv:1:1: error: invalid character `🐈`
    1 | 🐈println('')
      | ^
============
```

expected: `invalid_character`, found: `invalid character`

An underscore is the problem.

**Comment by zakuro9715** [comment]
@StunxFS That's it! ty :)

**Comment by spytheman** [comment]
Good work.

**Pull request merged**
