### PR TITLE
orm: allow use of orm Connection interface as db

### LINKED ISSUE #16072: cgen error: interface orm.Connection cast problem
**V version:** 
V 0.3.1 f7f0e0b
**OS:** 
macos 12.16

**What did you do?**
```v
module main
import orm
import sqlite
pub struct DBF {
pub mut:
	db orm.Connection // Want to initialize as required
}

pub fn (mut b DBF) set_db(mut db orm.Connection ) {
	b.db = db
}

[table: 'users']
pub struct User {
pub mut:
	id         int    [primary; sql: serial]
}

fn main () {
	mut db := sqlite.connect(':memory:') or { panic(err) }
	mut dbf := DBF {} // notice: interface field `DBF.db` must be initialized?  use `unsafe{ nil }` is does not meet the requirements
	dbf.set_db(mut db)
	// cgen error: This database type `unknown` is not implemented yet in orm
	sql dbf.db {
		create table User
	}
}
```

**What did you expect to see?**
 
```
success
```
 
**What did you see instead?**

```
cgen error: This database type `unknown` is not implemented yet in orm
```

> Or, how can I use it correctly

### PR DESCRIPTION
**Pull request by LouisSchmieder**
close #16072

### CODE REVIEW

**Comment by JalonSolov** [comment]
Looks like the failures are related to sqlite installation.

**Comment by enghitalo** [comment]
Can someone, please, close and reopen this PR?

**Comment by enghitalo** [comment]
> close #16072
# feature example
```v
import sqlite
import orm

struct Foo {
	id   int    [primary; sql: serial]
	name string
}

fn test_orm_sub_structs() {
	sqlite_db := sqlite.connect(':memory:') or { panic(err) }

	db := orm.Connection(sqlite_db)

	sql db {
		create table Foo
	}

	foo := Foo{
		name: 'test'
	}

	sql db {
		insert foo into Foo
	}

	foo_s := sql db {
		select from Foo where id == 1
	}

	assert foo_s.name == foo.name
}
```

**Comment by medvednikov** [comment]
```
 FAIL  [ 949/1163]  8628.532 ms vlib/v/tests/orm_connection_interface_test.v
Uninitialized bytes in __interceptor_strlen at offset 8 inside [0x702000000da8, 9)
==27356==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f34dfa87717  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x1a717)
    #1 0x7f34dfaea28e  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x7d28e)
    #2 0x7f34dfb560fb  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0xe90fb)
    #3 0x7c5704 in sqlite__connect (/tmp/v_1001/tsession_7f90b81b6740_305609062941/orm_connection_interface_test+0x7c5704)
    #4 0x7ccf08 in main__test_orm_sub_structs (/tmp/v_1001/tsession_7f90b81b6740_305609062941/orm_connection_interface_test+0x7ccf08)
    #5 0x7d7ff6 in main (/tmp/v_1001/tsession_7f90b81b6740_305609062941/orm_connection_interface_test+0x7d7ff6)
    #6 0x7f34df700082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #7 0x41d68d in _start (/tmp/v_1001/tsession_7f90b81b6740_305609062941/orm_connection_interface_test+0x41d68d)
```

**Comment by walkingdevel** [comment]
@LouisSchmieder, do you mind if I finish your PR?

**Comment by LouisSchmieder** [comment]
No go ahead I just don't have time anymore

**Comment by walkingdevel** [comment]
I fixed it in #17427. This PR can be closed after the merge.

**Pull request closed without merging**
