### PR TITLE
sokol GLSL examples, gg.m4 module

### PR DESCRIPTION
**Pull request by penguindark**
**What's inside**
This PR include:
- refactoring of the sokol examples removing all C dependencies
- new matrix/vector/quaternion module, for now in `vlib/gg/m4`
- test for the `m4` module

Note: in `04_multi_shader_glsl` must click to rotate the cube, upon @JalonSolov request :smile_cat:

### CODE REVIEW

**Comment by penguindark** [comment]
@medvednikov I need to re-upload  in place the glsl headers to avoid the CI fail.
These headers can be made by the user following the instructions in the header of the .v files. 
What have we to do about this issue?

**Comment by JalonSolov** [comment]
Can it be handled with a `.vsh` script?

**Comment by penguindark** [comment]
@JalonSolov If the user has the sokol tool in a standard place maybe otherwise i suggest to supress the CI for the examples.

**Comment by JalonSolov** [comment]
Well, .vsh could download the tools for you and then run them.  :-)

**Comment by penguindark** [comment]
And this process must run in the CI... very heavy IMHO
PS: I nveer used .vsh :) I'm ingorant on this topic.

**Comment by JalonSolov** [comment]
.vsh is just a V file without the `module` line, or any need for `fn main()`.  It is still V code, and gets compiled by V to an executable which is then run (and I think deleted when it exits).

Yes, it might be a little heavy for the main CI, but can't we have an alternate CI that is only run on demand?

**Comment by Larpon** [comment]
We could use CI caching so it won't download it every run? (I managed to cache the Android emulator images in vab) - it'll still take a hit so maybe a separate run container or something would be a good idea

**Comment by penguindark** [comment]
You are the experts of the CI, I trust you :D

**Comment by penguindark** [comment]
@medvednikov Your thought?

**Comment by Larpon** [comment]
> You are the experts of the CI, I trust you :D
> Or we can simply skip the tests on these examples ;)

"expert" in my case 😅

**Comment by penguindark** [comment]
@spytheman vfmt made a mess of all teh matrix! :(

**Pull request merged**
