### PR TITLE
vlib: implement `memcpy`, `memcmp`, `memmove` and `strlen` in V

### PR DESCRIPTION
**Pull request by Gladear**
Implement `memcpy`, `memmove`, `memcmp` and `strlen` in V.
They will be able to replace their C equivalent once `usize` becomes available, so for now, I put them in an `x.builtin` module.

Some things are to be discussed in my opinion :
- Should they have the same name as in C ? It doesn't really look like V convention
- Should they be in the `builtin` module ?
- Should `strlen` be a method of `byteptr` (it would be easier to make versions for `charptr` and maybe `voidptr`)

### CODE REVIEW

**Comment by Delta456** [comment]
Can you change the PR title to `implement memcpy, memmove and strlen in V` as the current title is misleading?

**Comment by spytheman** [comment]
Why are these needed?
The C variants are usually highly optimized.

**Comment by Gladear** [comment]
@Delta456 
Indeed, the initial purpose was to replace `<string.h>`, but since it is not possible right now, I'll change it

@spytheman 
For other backends ! The C variants can't be used for x64 or JS :slightly_smiling_face:

**Comment by JalonSolov** [comment]
The C versions should be in a `.c.v` file, not a `.v` file.  @spytheman your new `-Wimpure-v` flag should show you all these.  ;-)

**Comment by Larpon** [comment]
I have [a branch](https://github.com/Larpon/v/tree/feature/missdoc-c-in-v-sniffer) that can sniff them out via missdoc. It doesn't detect calls inside block comments and non-vfmt'ed single line comments though. It doesn't really belong in missdoc either but it might be a help?

**Comment by medvednikov** [comment]
x64 backend can and will call libc functions.

**Comment by JalonSolov** [comment]
Yes, but not ALL libc functions.  For example, it would be crazy to go through the overhead of calling libc just to do strlen.

**Comment by medvednikov** [comment]
Of course, I was just commenting on `The C variants can't be used for x64`

Also, even such a simple function as strlen can be heavily optimized using some truly fascinating strategies, which is done in glibc:

https://github.com/lattera/glibc/blob/master/string/strlen.c

**Comment by JalonSolov** [comment]
Yep, they've done some fun stuff.  Which could easily be duplicated, to avoid the function call overhead.

**Comment by yaskhan** [comment]
https://joryanick.com/retro-fast-x86-memcpy.htm

**Comment by JalonSolov** [comment]
Using native Linux functions is fine... on Linux.  Doesn't help on Windows.  Or JavaScript.  Or WASM. Or... who knows what, in the future.

**Pull request closed without merging**
