### PR TITLE
checker, cgen: cleanup comptime var marking on checker optimizing the way as it is checked on cgen

### PR DESCRIPTION
**Pull request by felipensp**
- Move ct expr marking to checker instead of checking all the time on cgen
- Simplify ct expr checking on cgen.

Hence the code runs faster. :-)

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU5YTYyZDFlMDYzMmRkMDhlMzI1M2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.zVoS43mvrfhzDwPh6Kulo-128NUC3eEv0NSrpyt2aLM">Huly&reg;: <b>V_0.6-21571</b></a></sub>

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Excellent work.
The comparisons with master are very good - the current PR is consistently faster.
I am still waiting for the -prod runs, but afaik it is good to merge as it is.

**Comment by spytheman** [comment]
The results with -prod are puzzling for me - they are the reverse, compared to the the one without -prod:
```
#0 21:03:55 ^ checker_ident_mark_ct_expr /v/oo>./v run .github/workflows/compare_pr_to_master.v -prod
==================================================================================================
Current git branch: checker_ident_mark_ct_expr, commit: 169c118
    Compiling new V executables from PR branch: checker_ident_mark_ct_expr, commit: 169c118 ...
CPU: 2.66s      Real: 2.43s     Elapsed: 0:02.43        RAM: 428344KB   ./v -o vnew1 cmd/v
CPU: 2.62s      Real: 2.41s     Elapsed: 0:02.41        RAM: 427192KB   ./vnew1 -o vnew2 cmd/v
CPU: 2.39s      Real: 2.65s     Elapsed: 0:02.65        RAM: 410492KB   ./vnew2 -no-parallel -o vnew cmd/v
CPU: 0.15s      Real: 0.17s     Elapsed: 0:00.17        RAM: 44164KB    ./vnew -no-parallel -o nhw_current.c examples/hello_world.v
CPU: 2.04s      Real: 2.25s     Elapsed: 0:02.25        RAM: 410484KB   ./vnew -no-parallel -o nv_current.c cmd/v
CPU: 98.71s     Real: 101.57s   Elapsed: 1:41.57        RAM: 447000KB   ./vnew -no-parallel -prod -o vnew_prod cmd/v
>Size of        nhw_current.c:      45398
>Size of         nv_current.c:    6130223
>Size of                 vnew:    9474864
>Size of            vnew_prod:    3989328
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
==================================================================================================
    Compiling old V executables from branch: master, commit: 77e4594 ...
CPU: 2.65s      Real: 2.42s     Elapsed: 0:02.42        RAM: 428108KB   ./v -o vold1 cmd/v
CPU: 2.68s      Real: 2.43s     Elapsed: 0:02.43        RAM: 428432KB   ./vold1 -o vold2 cmd/v
CPU: 2.44s      Real: 2.67s     Elapsed: 0:02.67        RAM: 411664KB   ./vold2 -no-parallel -o vold cmd/v
CPU: 0.15s      Real: 0.18s     Elapsed: 0:00.18        RAM: 44128KB    ./vold -no-parallel -o ohw_master.c examples/hello_world.v
CPU: 2.08s      Real: 2.28s     Elapsed: 0:02.28        RAM: 411676KB   ./vold -no-parallel -o ov_master.c cmd/v
CPU: 99.20s     Real: 102.05s   Elapsed: 1:42.05        RAM: 447108KB   ./vold -no-parallel -prod -o vold_prod cmd/v
>Size of            vold_prod:    3989360
>Size of         ohw_master.c:      45398
>Size of          ov_master.c:    6132072
>Size of                 vold:    9477200
>Size of            vold_prod:    3989360
==================================================================================================
File sizes so far ...
>>>>>> size("  nhw_current.c") - size("   ohw_master.c") =      45398 -      45398 =          0
>>>>>> size("   nv_current.c") - size("    ov_master.c") =    6130223 -    6132072 =      -1849
>>>>>> size("           vnew") - size("           vold") =    9474864 -    9477200 =      -2336
Switched to branch 'checker_ident_mark_ct_expr'
==================================================================================================
    Measuring at PR branch: checker_ident_mark_ct_expr, commit: 169c118 ...
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
 >  1         base          41.5ms ± σ:   0.2ms,  41.4ms… 41.8ms `./vold_prod -check-syntax           examples/hello_world.v`
    2   +0.4% 1.00x slower  41.7ms ± σ:   0.0ms,  41.6ms… 41.7ms `./vnew_prod -check-syntax           examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
 >  1         base          41.4ms ± σ:   0.1ms,  41.2ms… 41.5ms `./vold_prod -check-syntax           examples/hello_world.v`
    2   +0.8% 1.01x slower  41.7ms ± σ:   0.0ms,  41.7ms… 41.7ms `./vnew_prod -check-syntax           examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
 >  1         base          41.5ms ± σ:   0.0ms,  41.5ms… 41.6ms `./vold_prod -check-syntax           examples/hello_world.v`
    2   +0.5% 1.01x slower  41.8ms ± σ:   0.2ms,  41.5ms… 42.0ms `./vnew_prod -check-syntax           examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
 >  1         base          59.3ms ± σ:   0.2ms,  59.1ms… 59.5ms `./vold_prod -check                  examples/hello_world.v`
    2   +0.3% 1.00x slower  59.5ms ± σ:   0.1ms,  59.3ms… 59.6ms `./vnew_prod -check                  examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
 >  1         base          59.0ms ± σ:   0.0ms,  58.9ms… 59.0ms `./vold_prod -check                  examples/hello_world.v`
    2   +0.8% 1.01x slower  59.4ms ± σ:   0.1ms,  59.3ms… 59.5ms `./vnew_prod -check                  examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
 >  1         base          59.0ms ± σ:   0.2ms,  58.7ms… 59.1ms `./vold_prod -check                  examples/hello_world.v`
    2   +0.4% 1.00x slower  59.2ms ± σ:   0.0ms,  59.2ms… 59.3ms `./vnew_prod -check                  examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
 >  1         base          69.3ms ± σ:   0.0ms,  69.3ms… 69.3ms `./vold_prod -no-parallel -o ohw.c   examples/hello_world.v`
    2   +0.5% 1.01x slower  69.7ms ± σ:   0.2ms,  69.4ms… 69.8ms `./vnew_prod -no-parallel -o nhw.c   examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
    1   -0.1% 1.00x ~same~  69.8ms ± σ:   0.0ms,  69.7ms… 69.8ms `./vnew_prod -no-parallel -o nhw.c   examples/hello_world.v`
 >  2         base          69.8ms ± σ:   0.4ms,  69.3ms… 70.2ms `./vold_prod -no-parallel -o ohw.c   examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
 >  1         base          69.3ms ± σ:   0.2ms,  69.2ms… 69.5ms `./vold_prod -no-parallel -o ohw.c   examples/hello_world.v`
    2   +0.9% 1.01x slower  69.9ms ± σ:   0.0ms,  69.9ms… 70.0ms `./vnew_prod -no-parallel -o nhw.c   examples/hello_world.v`
>>>>>> size("          nhw.c") - size("          ohw.c") =      45398 -      45398 =          0
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
 >  1         base          80.9ms ± σ:   0.0ms,  80.8ms… 80.9ms `./vold_prod -no-parallel -o ohw.exe examples/hello_world.v`
    2   +0.6% 1.01x slower  81.3ms ± σ:   0.1ms,  81.2ms… 81.4ms `./vnew_prod -no-parallel -o nhw.exe examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
 >  1         base          81.0ms ± σ:   0.1ms,  80.9ms… 81.1ms `./vold_prod -no-parallel -o ohw.exe examples/hello_world.v`
    2   +0.5% 1.00x slower  81.4ms ± σ:   0.0ms,  81.3ms… 81.4ms `./vnew_prod -no-parallel -o nhw.exe examples/hello_world.v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
 >  1         base          81.1ms ± σ:   0.0ms,  81.1ms… 81.1ms `./vold_prod -no-parallel -o ohw.exe examples/hello_world.v`
    2   +0.3% 1.00x slower  81.3ms ± σ:   0.1ms,  81.2ms… 81.5ms `./vnew_prod -no-parallel -o nhw.exe examples/hello_world.v`
>>>>>> size("        nhw.exe") - size("        ohw.exe") =     242344 -     242344 =          0
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
 >  1         base         329.7ms ± σ:   0.5ms, 329.2ms…330.4ms `./vold_prod -check-syntax           cmd/v`
    2   +0.8% 1.01x slower 332.4ms ± σ:   0.1ms, 332.3ms…332.5ms `./vnew_prod -check-syntax           cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
 >  1         base         329.7ms ± σ:   0.4ms, 329.2ms…330.2ms `./vold_prod -check-syntax           cmd/v`
    2   +0.9% 1.01x slower 332.6ms ± σ:   0.2ms, 332.2ms…332.8ms `./vnew_prod -check-syntax           cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
 >  1         base         329.5ms ± σ:   0.5ms, 329.0ms…330.2ms `./vold_prod -check-syntax           cmd/v`
    2   +1.0% 1.01x slower 332.9ms ± σ:   0.1ms, 332.8ms…333.0ms `./vnew_prod -check-syntax           cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
 >  1         base         551.4ms ± σ:   0.3ms, 551.1ms…551.7ms `./vold_prod -check                  cmd/v`
    2   +0.8% 1.01x slower 555.6ms ± σ:   0.5ms, 555.0ms…556.3ms `./vnew_prod -check                  cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
 >  1         base         550.7ms ± σ:   0.3ms, 550.3ms…551.0ms `./vold_prod -check                  cmd/v`
    2   +0.9% 1.01x slower 555.5ms ± σ:   0.8ms, 554.4ms…556.0ms `./vnew_prod -check                  cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
 >  1         base         550.2ms ± σ:   0.4ms, 549.9ms…550.7ms `./vold_prod -check                  cmd/v`
    2   +0.9% 1.01x slower 555.3ms ± σ:   0.1ms, 555.1ms…555.4ms `./vnew_prod -check                  cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
 >  1         base         914.0ms ± σ:   1.1ms, 912.9ms…915.4ms `./vold_prod -no-parallel -o ov.c    cmd/v`
    2   +0.8% 1.01x slower 921.2ms ± σ:   0.4ms, 920.7ms…921.6ms `./vnew_prod -no-parallel -o nv.c    cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
 >  1         base         913.8ms ± σ:   0.6ms, 912.9ms…914.4ms `./vold_prod -no-parallel -o ov.c    cmd/v`
    2   +0.9% 1.01x slower 921.8ms ± σ:   0.6ms, 921.3ms…922.6ms `./vnew_prod -no-parallel -o nv.c    cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
 >  1         base         915.0ms ± σ:   0.3ms, 914.7ms…915.4ms `./vold_prod -no-parallel -o ov.c    cmd/v`
    2   +0.8% 1.01x slower 922.1ms ± σ:   0.3ms, 921.6ms…922.4ms `./vnew_prod -no-parallel -o nv.c    cmd/v`
>>>>>> size("           nv.c") - size("           ov.c") =    6130223 -    6130223 =          0
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
 >  1         base         1309.6ms ± σ:   0.4ms, 1309.2ms…1310.1ms `./vold_prod -no-parallel -o ov.exe  cmd/v`
    2   +0.6% 1.01x slower 1317.7ms ± σ:   0.4ms, 1317.2ms…1318.2ms `./vnew_prod -no-parallel -o nv.exe  cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
 >  1         base         1309.3ms ± σ:   0.5ms, 1308.9ms…1309.9ms `./vold_prod -no-parallel -o ov.exe  cmd/v`
    2   +0.5% 1.01x slower 1316.5ms ± σ:   0.3ms, 1316.2ms…1316.8ms `./vnew_prod -no-parallel -o nv.exe  cmd/v`
Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
 >  1         base         1309.8ms ± σ:   0.1ms, 1309.7ms…1309.9ms `./vold_prod -no-parallel -o ov.exe  cmd/v`
    2   +0.6% 1.01x slower 1317.0ms ± σ:   0.5ms, 1316.6ms…1317.7ms `./vnew_prod -no-parallel -o nv.exe  cmd/v`
>>>>>> size("         nv.exe") - size("         ov.exe") =    9474880 -    9474880 =          0
Done. Total time: 467.119145363 s.
==================================================================================================
Final summary for file diff sizes on their own branches:
>>>>>> size("  nhw_current.c") - size("   ohw_master.c") =      45398 -      45398 =          0
>>>>>> size("   nv_current.c") - size("    ov_master.c") =    6130223 -    6132072 =      -1849
>>>>>> size("           vnew") - size("           vold") =    9474864 -    9477200 =      -2336
>>>>>> size("      vnew_prod") - size("      vold_prod") =    3989328 -    3989360 =        -32
==================================================================================================
Final summary for file diff sizes for generated files on the *current* branch:
>>>>>> size("          nhw.c") - size("          ohw.c") =      45398 -      45398 =          0
>>>>>> size("           nv.c") - size("           ov.c") =    6130223 -    6130223 =          0
>>>>>> size("        nhw.exe") - size("        ohw.exe") =     242344 -     242344 =          0
>>>>>> size("         nv.exe") - size("         ov.exe") =    9474880 -    9474880 =          0
#0 21:11:44 ^ checker_ident_mark_ct_expr /v/oo>
```

**Comment by spytheman** [comment]
I still think that it is overall an improvement.

We may have to minimize the size of the ast structures by merging some of the boolean fields into an enum flag.

**Comment by felipensp** [comment]
> The results with -prod are puzzling for me - they are the reverse, compared to the the one without -prod:
> 
> ```
> #0 21:03:55 ^ checker_ident_mark_ct_expr /v/oo>./v run .github/workflows/compare_pr_to_master.v -prod
> ==================================================================================================
> Current git branch: checker_ident_mark_ct_expr, commit: 169c118
>     Compiling new V executables from PR branch: checker_ident_mark_ct_expr, commit: 169c118 ...
> CPU: 2.66s      Real: 2.43s     Elapsed: 0:02.43        RAM: 428344KB   ./v -o vnew1 cmd/v
> CPU: 2.62s      Real: 2.41s     Elapsed: 0:02.41        RAM: 427192KB   ./vnew1 -o vnew2 cmd/v
> CPU: 2.39s      Real: 2.65s     Elapsed: 0:02.65        RAM: 410492KB   ./vnew2 -no-parallel -o vnew cmd/v
> CPU: 0.15s      Real: 0.17s     Elapsed: 0:00.17        RAM: 44164KB    ./vnew -no-parallel -o nhw_current.c examples/hello_world.v
> CPU: 2.04s      Real: 2.25s     Elapsed: 0:02.25        RAM: 410484KB   ./vnew -no-parallel -o nv_current.c cmd/v
> CPU: 98.71s     Real: 101.57s   Elapsed: 1:41.57        RAM: 447000KB   ./vnew -no-parallel -prod -o vnew_prod cmd/v
> >Size of        nhw_current.c:      45398
> >Size of         nv_current.c:    6130223
> >Size of                 vnew:    9474864
> >Size of            vnew_prod:    3989328
> Switched to branch 'master'
> Your branch is up to date with 'origin/master'.
> ==================================================================================================
>     Compiling old V executables from branch: master, commit: 77e4594 ...
> CPU: 2.65s      Real: 2.42s     Elapsed: 0:02.42        RAM: 428108KB   ./v -o vold1 cmd/v
> CPU: 2.68s      Real: 2.43s     Elapsed: 0:02.43        RAM: 428432KB   ./vold1 -o vold2 cmd/v
> CPU: 2.44s      Real: 2.67s     Elapsed: 0:02.67        RAM: 411664KB   ./vold2 -no-parallel -o vold cmd/v
> CPU: 0.15s      Real: 0.18s     Elapsed: 0:00.18        RAM: 44128KB    ./vold -no-parallel -o ohw_master.c examples/hello_world.v
> CPU: 2.08s      Real: 2.28s     Elapsed: 0:02.28        RAM: 411676KB   ./vold -no-parallel -o ov_master.c cmd/v
> CPU: 99.20s     Real: 102.05s   Elapsed: 1:42.05        RAM: 447108KB   ./vold -no-parallel -prod -o vold_prod cmd/v
> >Size of            vold_prod:    3989360
> >Size of         ohw_master.c:      45398
> >Size of          ov_master.c:    6132072
> >Size of                 vold:    9477200
> >Size of            vold_prod:    3989360
> ==================================================================================================
> File sizes so far ...
> >>>>>> size("  nhw_current.c") - size("   ohw_master.c") =      45398 -      45398 =          0
> >>>>>> size("   nv_current.c") - size("    ov_master.c") =    6130223 -    6132072 =      -1849
> >>>>>> size("           vnew") - size("           vold") =    9474864 -    9477200 =      -2336
> Switched to branch 'checker_ident_mark_ct_expr'
> ==================================================================================================
>     Measuring at PR branch: checker_ident_mark_ct_expr, commit: 169c118 ...
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
>  >  1         base          41.5ms ± σ:   0.2ms,  41.4ms… 41.8ms `./vold_prod -check-syntax           examples/hello_world.v`
>     2   +0.4% 1.00x slower  41.7ms ± σ:   0.0ms,  41.6ms… 41.7ms `./vnew_prod -check-syntax           examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
>  >  1         base          41.4ms ± σ:   0.1ms,  41.2ms… 41.5ms `./vold_prod -check-syntax           examples/hello_world.v`
>     2   +0.8% 1.01x slower  41.7ms ± σ:   0.0ms,  41.7ms… 41.7ms `./vnew_prod -check-syntax           examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
>  >  1         base          41.5ms ± σ:   0.0ms,  41.5ms… 41.6ms `./vold_prod -check-syntax           examples/hello_world.v`
>     2   +0.5% 1.01x slower  41.8ms ± σ:   0.2ms,  41.5ms… 42.0ms `./vnew_prod -check-syntax           examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
>  >  1         base          59.3ms ± σ:   0.2ms,  59.1ms… 59.5ms `./vold_prod -check                  examples/hello_world.v`
>     2   +0.3% 1.00x slower  59.5ms ± σ:   0.1ms,  59.3ms… 59.6ms `./vnew_prod -check                  examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
>  >  1         base          59.0ms ± σ:   0.0ms,  58.9ms… 59.0ms `./vold_prod -check                  examples/hello_world.v`
>     2   +0.8% 1.01x slower  59.4ms ± σ:   0.1ms,  59.3ms… 59.5ms `./vnew_prod -check                  examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
>  >  1         base          59.0ms ± σ:   0.2ms,  58.7ms… 59.1ms `./vold_prod -check                  examples/hello_world.v`
>     2   +0.4% 1.00x slower  59.2ms ± σ:   0.0ms,  59.2ms… 59.3ms `./vnew_prod -check                  examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
>  >  1         base          69.3ms ± σ:   0.0ms,  69.3ms… 69.3ms `./vold_prod -no-parallel -o ohw.c   examples/hello_world.v`
>     2   +0.5% 1.01x slower  69.7ms ± σ:   0.2ms,  69.4ms… 69.8ms `./vnew_prod -no-parallel -o nhw.c   examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
>     1   -0.1% 1.00x ~same~  69.8ms ± σ:   0.0ms,  69.7ms… 69.8ms `./vnew_prod -no-parallel -o nhw.c   examples/hello_world.v`
>  >  2         base          69.8ms ± σ:   0.4ms,  69.3ms… 70.2ms `./vold_prod -no-parallel -o ohw.c   examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
>  >  1         base          69.3ms ± σ:   0.2ms,  69.2ms… 69.5ms `./vold_prod -no-parallel -o ohw.c   examples/hello_world.v`
>     2   +0.9% 1.01x slower  69.9ms ± σ:   0.0ms,  69.9ms… 70.0ms `./vnew_prod -no-parallel -o nhw.c   examples/hello_world.v`
> >>>>>> size("          nhw.c") - size("          ohw.c") =      45398 -      45398 =          0
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
>  >  1         base          80.9ms ± σ:   0.0ms,  80.8ms… 80.9ms `./vold_prod -no-parallel -o ohw.exe examples/hello_world.v`
>     2   +0.6% 1.01x slower  81.3ms ± σ:   0.1ms,  81.2ms… 81.4ms `./vnew_prod -no-parallel -o nhw.exe examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
>  >  1         base          81.0ms ± σ:   0.1ms,  80.9ms… 81.1ms `./vold_prod -no-parallel -o ohw.exe examples/hello_world.v`
>     2   +0.5% 1.00x slower  81.4ms ± σ:   0.0ms,  81.3ms… 81.4ms `./vnew_prod -no-parallel -o nhw.exe examples/hello_world.v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
>  >  1         base          81.1ms ± σ:   0.0ms,  81.1ms… 81.1ms `./vold_prod -no-parallel -o ohw.exe examples/hello_world.v`
>     2   +0.3% 1.00x slower  81.3ms ± σ:   0.1ms,  81.2ms… 81.5ms `./vnew_prod -no-parallel -o nhw.exe examples/hello_world.v`
> >>>>>> size("        nhw.exe") - size("        ohw.exe") =     242344 -     242344 =          0
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
>  >  1         base         329.7ms ± σ:   0.5ms, 329.2ms…330.4ms `./vold_prod -check-syntax           cmd/v`
>     2   +0.8% 1.01x slower 332.4ms ± σ:   0.1ms, 332.3ms…332.5ms `./vnew_prod -check-syntax           cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
>  >  1         base         329.7ms ± σ:   0.4ms, 329.2ms…330.2ms `./vold_prod -check-syntax           cmd/v`
>     2   +0.9% 1.01x slower 332.6ms ± σ:   0.2ms, 332.2ms…332.8ms `./vnew_prod -check-syntax           cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
>  >  1         base         329.5ms ± σ:   0.5ms, 329.0ms…330.2ms `./vold_prod -check-syntax           cmd/v`
>     2   +1.0% 1.01x slower 332.9ms ± σ:   0.1ms, 332.8ms…333.0ms `./vnew_prod -check-syntax           cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
>  >  1         base         551.4ms ± σ:   0.3ms, 551.1ms…551.7ms `./vold_prod -check                  cmd/v`
>     2   +0.8% 1.01x slower 555.6ms ± σ:   0.5ms, 555.0ms…556.3ms `./vnew_prod -check                  cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
>  >  1         base         550.7ms ± σ:   0.3ms, 550.3ms…551.0ms `./vold_prod -check                  cmd/v`
>     2   +0.9% 1.01x slower 555.5ms ± σ:   0.8ms, 554.4ms…556.0ms `./vnew_prod -check                  cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
>  >  1         base         550.2ms ± σ:   0.4ms, 549.9ms…550.7ms `./vold_prod -check                  cmd/v`
>     2   +0.9% 1.01x slower 555.3ms ± σ:   0.1ms, 555.1ms…555.4ms `./vnew_prod -check                  cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
>  >  1         base         914.0ms ± σ:   1.1ms, 912.9ms…915.4ms `./vold_prod -no-parallel -o ov.c    cmd/v`
>     2   +0.8% 1.01x slower 921.2ms ± σ:   0.4ms, 920.7ms…921.6ms `./vnew_prod -no-parallel -o nv.c    cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
>  >  1         base         913.8ms ± σ:   0.6ms, 912.9ms…914.4ms `./vold_prod -no-parallel -o ov.c    cmd/v`
>     2   +0.9% 1.01x slower 921.8ms ± σ:   0.6ms, 921.3ms…922.6ms `./vnew_prod -no-parallel -o nv.c    cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
>  >  1         base         915.0ms ± σ:   0.3ms, 914.7ms…915.4ms `./vold_prod -no-parallel -o ov.c    cmd/v`
>     2   +0.8% 1.01x slower 922.1ms ± σ:   0.3ms, 921.6ms…922.4ms `./vnew_prod -no-parallel -o nv.c    cmd/v`
> >>>>>> size("           nv.c") - size("           ov.c") =    6130223 -    6130223 =          0
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  1                                                                                  
>  >  1         base         1309.6ms ± σ:   0.4ms, 1309.2ms…1310.1ms `./vold_prod -no-parallel -o ov.exe  cmd/v`
>     2   +0.6% 1.01x slower 1317.7ms ± σ:   0.4ms, 1317.2ms…1318.2ms `./vnew_prod -no-parallel -o nv.exe  cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  2                                                                                  
>  >  1         base         1309.3ms ± σ:   0.5ms, 1308.9ms…1309.9ms `./vold_prod -no-parallel -o ov.exe  cmd/v`
>     2   +0.5% 1.01x slower 1316.5ms ± σ:   0.3ms, 1316.2ms…1316.8ms `./vnew_prod -no-parallel -o nv.exe  cmd/v`
> Summary after 1 series x 10 runs (%s are relative to first command, or `base`), discard maxs:  7, repeat:  3                                                                                  
>  >  1         base         1309.8ms ± σ:   0.1ms, 1309.7ms…1309.9ms `./vold_prod -no-parallel -o ov.exe  cmd/v`
>     2   +0.6% 1.01x slower 1317.0ms ± σ:   0.5ms, 1316.6ms…1317.7ms `./vnew_prod -no-parallel -o nv.exe  cmd/v`
> >>>>>> size("         nv.exe") - size("         ov.exe") =    9474880 -    9474880 =          0
> Done. Total time: 467.119145363 s.
> ==================================================================================================
> Final summary for file diff sizes on their own branches:
> >>>>>> size("  nhw_current.c") - size("   ohw_master.c") =      45398 -      45398 =          0
> >>>>>> size("   nv_current.c") - size("    ov_master.c") =    6130223 -    6132072 =      -1849
> >>>>>> size("           vnew") - size("           vold") =    9474864 -    9477200 =      -2336
> >>>>>> size("      vnew_prod") - size("      vold_prod") =    3989328 -    3989360 =        -32
> ==================================================================================================
> Final summary for file diff sizes for generated files on the *current* branch:
> >>>>>> size("          nhw.c") - size("          ohw.c") =      45398 -      45398 =          0
> >>>>>> size("           nv.c") - size("           ov.c") =    6130223 -    6130223 =          0
> >>>>>> size("        nhw.exe") - size("        ohw.exe") =     242344 -     242344 =          0
> >>>>>> size("         nv.exe") - size("         ov.exe") =    9474880 -    9474880 =          0
> #0 21:11:44 ^ checker_ident_mark_ct_expr /v/oo>
> ```

Very weird. Consistently slow...

**Comment by spytheman** [comment]
Yes, it is weird - I also tried some manual measurements with different examples, and it all came either the same or slower, so it is consistent, but I hope it is local to my system, since I do not see a reason for it to be slower (unlike the previous PR), and the tcc versions were consistently faster by a large margin (>0.8%).

**Comment by spytheman** [comment]
According to https://fast.vlang.io/ it is an improvement.

**Pull request merged**
