### PR TITLE
tests: fix ci errors temporary

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix ci errors temporary.

### CODE REVIEW

**Comment by shove70** [comment]
Do we need to give priority to merging this PR so that some fix work can continue? Then adjust "fmt" and some test cases that do not adapt to the new "string interpolation" at the same time?

**Comment by medvednikov** [comment]
Thanks @yuyi98

**Comment by medvednikov** [comment]
1 fail on freebsd, not sure which test

```
Failed command 1:    '/tmp/cirrus-ci-build/v/v'   -o '/tmp/v/tsession_800a12000_424885892955/compiler_errors_test' '/tmp/cirrus-ci-build/v/vlib/v/compiler_errors_test.v'
Summary for testing vlib: 1 failed, 69 passed, 70 total. Runtime: 278296 ms, on 1 job.
```

**Comment by yuyi98** [comment]
```v
OK    [34/70]  3598.807 ms vlib/net/http/server_test.v
                 retrying 1/8 of vlib/net/tcp_test.v ; known flaky: true ...
                 retrying 2/8 of vlib/net/tcp_test.v ; known flaky: true ...
                 retrying 3/8 of vlib/net/tcp_test.v ; known flaky: true ...
                 retrying 4/8 of vlib/net/tcp_test.v ; known flaky: true ...
                 retrying 5/8 of vlib/net/tcp_test.v ; known flaky: true ...
                 retrying 6/8 of vlib/net/tcp_test.v ; known flaky: true ...
                 retrying 7/8 of vlib/net/tcp_test.v ; known flaky: true ...
                 retrying 8/8 of vlib/net/tcp_test.v ; known flaky: true ...
   *FAILURE* of the known flaky test file vlib/net/tcp_test.v is ignored, since VTEST_FAIL_FLAKY is 0 . Retry count: 8 .
```

**Comment by medvednikov** [comment]
Actually it's ok on master now. All green @yuyi98

**Pull request merged**
