### PR TITLE
tetris: display next tetro

### PR DESCRIPTION
**Pull request by nsauzede**
Trivial tetris enhancement to display next tetro

### CODE REVIEW

**Comment by nsauzede** [comment]
There are two failing CI checks, but those seem unrelated.
Can someone confirm that ?

**Comment by spytheman** [comment]
Yes, these are unrelated.

**Review by spytheman — APPROVED** [review]
That is a very nice addition. 
Can you make the color of the next tetro, a little lighter, say gx.rgb(220, 220, 220) ?

**Comment by nsauzede** [comment]
sure I'll add another commit..

**Comment by nsauzede** [comment]
Done, and rebase latest master
Should I also use the same lighter color for ghost tetro, too @spytheman ?
Or is it mergeable as-is ?

**Pull request merged**
