### PR TITLE
release consts

### PR DESCRIPTION
**Pull request by daquexian**
The malloc-ed memory like g_str_buf is not freed.

### CODE REVIEW

**Comment by medvednikov** [comment]
You are adding release_consts() to the end of main().

This memory will be freed by the kernel when the application exits.

**Comment by daquexian** [comment]
> You are adding release_consts() to the end of main().
> 
> This memory will be freed by the kernel when the application exits.

It is true on most modern operating systems, but not guaranteed, for example, on old PCs or PCs without operating system. It may be better to release them by ourselves, especially for such a fundamental program (a compiler).

**Comment by SuperFola** [comment]
I agree with Alex, the OS is in charge of freeing everything when a program closes. That can be considered as a bad pratice, but for such a big application, I don't think it is, it's a very small optimization for nothing. And nobody is using a very old PC without an OS nowaday. It's time to leave those computers behind, as well as the 32bits application format, everything should be in x64 now

**Comment by superwhiskers** [comment]
in such a large program, that memory can add up. poor memory management is always a bad idea and should be fixed. relying on the os to free memory isn't as much of an issue in a small application, but in a largeish program like a compiler, it can lead to bad memory leaks

**Comment by wheelcomplex** [comment]
Think about program for UEFI/Boot loader.

**Comment by ntrel** [comment]
While I think V programs should definitely work on embedded and 32-bit systems, I'm not sure that the compiler itself needs to run on those systems. Cross compilation could hopefully be used instead.

**Comment by medvednikov** [comment]
Programs built with V will have memory cleaned up, but not the compiler itself.

Actually I have an experimental branch with a custom allocator for the compiler that will fix this problem.

But I don't want to complicate and slow down the compiler as suggested in this PR.

**Pull request closed without merging**
