### PR TITLE
all: add keywords `shared`, rwshared`, `lock`, `rlock`(1. part) for locked concurrency

### PR DESCRIPTION
**Pull request by UweKrueger**
This PR allows the following semantics:
```v
fn (shared x St) f() {
    lock x {
        // do something with x
    }
}

fn main() {
    x := &St{...}
    x.go()
    lock x {
        // do something else with x
    }
}
```
More examples are added as testcases. This is the very first version - I am aware that many things are still missing, especially better checks. Also read locks and write locks do the same at the moment since there is no separate `RW_Mutex` implementation in `sync`, yet.

Also, I plan to implement the syntax `x := lock a { a.getval() }`, but that does not work, yet.

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks! I would like to do this without the `shared/rwshared` keywords.

The key feature of Go's concurrency is that you don't have to declare the function differently, you can just `go x()` any function. I want the same in V.

**Comment by medvednikov** [comment]
I see this was being discussed on Discord, I didn't participate unfortunately. I'm sure we can figure out a simpler syntax for this.

**Comment by UweKrueger** [comment]
Hmm... the point is that `x()` has to know that a `lock` is needed. In Go locks are a completely manual thing without support from the compiler. The idea of `shared` is that a hidden mutex is added to the struct and it is possible (though not yet implemented) to check that this mutex is locked before access is allowed.

**Comment by medvednikov** [comment]
@UweKrueger but we have `lock x {` in the body, we can make the compiler smart enough to detect this without manual labor :)

**Comment by medvednikov** [comment]
Add a new flag to `Var`, set it after parsing the body, then do the necessary work in cgen.

**Comment by UweKrueger** [comment]
Yes, that might indeed work. I'll try...

**Comment by UweKrueger** [comment]
After thinking this thru it seems to be less confusing to keep the explicit keywords...

**Pull request merged**
