### PR TITLE
parser: support `module:` for immutable private struct fields

### LINKED ISSUE #6582: structs' public fields should be before private fields (and do we actually need pub keyword?)
Readability matters and I find V to be very readable overall. Except one thing. When looking at struct definition we always see private fields first and public fields only after them in section delimited by "pub:". Should not this be somehow inverted, seeing public items first should help improve readability greatly.

Of course I can mark each public field with "pub" individually and list them at the top of struct definition, but that is very verbose.

UPDATE: Crucial question is whether distinguishing private and public fields adds any significant value for the language users. Some popular modern languages like Python or Kotlin have all their fields public by default (unless marked as private). I believe that leaving this symbol visibility feature out of the language definition would simplify the language very much without sacrificing anything significant. Of course it would then be up to the user to decide to communicate that some parts of struct is private and not intended to be touched by caller, e.g. by underscoring the field name like in Python. Enforcing this convention would then be up to static analyzers instead of the compiler. But the language itself would remain clean and simple.

### PR DESCRIPTION
**Pull request by ntrel**
Fixes #6582.
Otherwise immutable private fields have to come first despite being least interesting.

*Update*: this feature is necessary (but not sufficient) for:
1. optimizing alignment of types whose size is not a multiple of the bus size.
2. optimizing cache performance of commonly used fields in struct larger than the processor's cache size.

I decided to use the `module` keyword for this as non-public fields are accessible in the module only.
Alex agrees that this should be possible, but there was no agreed syntax: https://github.com/vlang/v/issues/6582#issuecomment-735765489

### CODE REVIEW

**Comment by JalonSolov** [comment]
My question is:  Why?  Despite them being "less interesting", fields without modifiers are already module private.  Why introduce syntax to denote something we already have without it?

**Comment by ntrel** [comment]
> Why introduce syntax to denote something we already have without it?

>> **immutable private fields have to come first**

Also field alignment (although currently no `keyword:` section is allowed to be repeated).

**Comment by JalonSolov** [comment]
I just don't see having to put the immutable private fields first as a horrible thing.  :-\

Field alignment is the same with or without a new `keyword:` added, and I completely agree with NOT repeating them - why clutter things up?

**Comment by ntrel** [comment]
> Field alignment is the same with or without a new keyword: added

Optimizing alignment and cache performance often involves grouping certain fields together. This is impossible if you have to group fields by mutability and visibility.

> agree with NOT repeating them 

I suspect this was done partly to make vfmt easier (there are _pos fields in ast.StructDecl only for vfmt).

**Comment by JalonSolov** [comment]
Ah, alignment of structures makes a lot more sense than just adding a keyword to make it "pretty".

Still not sure it's a good idea, but at least this is a point where it _might_ make a difference.

**Comment by medvednikov** [comment]
I'm not a huge fan of it either. But we do need to make it possible to list public fields first.

Another way would be to make them public by default, but that's not an option.

**Comment by medvednikov** [comment]
This doesn't fix the alignment problem by the way, since that may require having a public, private, public field etc

That'll be fixed via attributes.

**Comment by medvednikov** [comment]
Or perhaps we'll have to remove the `modifer:` syntax entirely, since it's causing so many problems.

**Pull request merged**
