### PR TITLE
interface: update tests

### PR DESCRIPTION
**Pull request by smartiniOnGitHub**
UPDATE:

no more runtime error with current V, see updated comments under.

----

OLD (original) subject for this PR:

and clean-up TODO resolved now.

In this PR you can see that if I call a function with an interface as argument and then I call another function with that interface argument (see related two new lines enabled in this PR) I got a runtime error:

```
==================
interface_test.tmp.c: In function ‘perform_speak’:
interface_test.tmp.c:10178:20: error: implicit declaration of function ‘I_Animal_to_Interface_Animal’; did you mean ‘I_Bird_to_Interface_Animal’? [-Werror=implicit-function-declaration]
10178 |  if (is_dog_or_cat(I_Animal_to_Interface_Animal(&a))){
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                    I_Bird_to_Interface_Animal
interface_test.tmp.c:10178:20: error: incompatible type for argument 1 of ‘is_dog_or_cat’
10178 |  if (is_dog_or_cat(I_Animal_to_Interface_Animal(&a))){
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                    |
      |                    int
interface_test.tmp.c:10038:34: note: expected ‘Animal’ {aka ‘struct <anonymous>’} but argument is of type ‘int’
10038 | static bool is_dog_or_cat(Animal a) {
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

It seems something not propagated in the right way in functions using interfaces.
Disabling (comment) those 2 lines all is good.
Hope this helps; if you need more info/changes tell me.
Thanks for now.

### CODE REVIEW

**Comment by smartiniOnGitHub** [comment]
Updating to re-test with current V ...

**Comment by smartiniOnGitHub** [comment]
Update: with latest V I don't get runtime error anymore :-) .
I'm still cleaning this PR to remove old TODO and add some more little test/assertions ... I'll remove DRAFT status ASAP.

Running test with:
```
v test interface_test.v
```
all is fine.
Running it normally to see the output with:
```
v interface_test.v
```
all is fine the same, see all output generated.

Hope you find good enough to merge in code base, or tell me so I can change; otherwise drop this PR, no problem.

Thanks

**Comment by smartiniOnGitHub** [comment]
Ready for final review now. Bye

**Comment by smartiniOnGitHub** [comment]
Hi @spytheman , do you think it would be good to merge this ?
My intention was to add some more tests in interface test source, it could be useful even to other readers ... hope it's good enough, otherwise tell me.
Thanks and sorry for direct ping on you, it's only to check what to do on this old PR ... 
Bye

**Comment by spytheman** [comment]
It looks good to me, sorry for the late answer.

**Comment by smartiniOnGitHub** [comment]
@spytheman don't worry and thanks for the review/merge. Stay well. Bye

**Pull request merged**
