### PR TITLE
checker: check private constant

### LINKED ISSUE #8439: private const can be read from out of the module
**V version:Archlinux** 
**OS:0.2.2 974cac2** 

**What did you do?**
```
.
├── a
│   └── a.v
├── b
│   └── b.v
├── main.v
└── v.mod
```

a.v
```v
module a

pub const (
        a_const = 'A'
)

pub fn a_fn() {
        println('A')
}
```

b.v
```v
module b

const (
        b_const = 'B'
)

fn b_fn() {
        println('B')
}
```

main.v
```v
import a
import b

fn main() {
        a.a_fn()
        println(a.a_const)
        b.b_fn()
        println(b.b_const)
}
```

**What did you expect to see?**
Error that `b.b_const` is private.
 
**What did you see instead?**
Compiles with no error.

### PR DESCRIPTION
**Pull request by zakuro9715**
fix #8439

### CODE REVIEW

**Comment by medvednikov** [comment]
@Larpon 

```
android/package.v:508:22: error: constant `java.keywords` is private
  506 |     // segment can't be a java keyword
  507 |     for segment in segments {
  508 |         if segment in java.keywords {
      |                            ~~~~~~~~
  509 |             return false
  510 |         }
```

**Comment by Larpon** [comment]
Pulled in good find 👍

**Comment by Larpon** [comment]
Oof there's more. I'm on it 🙂

**Comment by Larpon** [comment]
`vab` should be fixed in https://github.com/vlang/vab/commit/05ed52400f4e895aedfd272d2bed32e1ab139f63

**Comment by Larpon** [comment]
Last errors fixed here https://github.com/vlang/v/pull/8516

**Pull request merged**
