### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by renlite**
README.md vweb: use {} for block in template

### CODE REVIEW

**Comment by spytheman** [comment]
I am not sure that is correct.
Several template files:
   tutorials/code/blog/index.html:6 
   vlib/v/tests/tmpl/1.txt:7
   examples/vweb/file_upload/upload.html:5
 ... as well as the template files in gitly, do use `@for x in y` without `{` at the end.

@LouisSchmieder , @medvednikov what do you think ?

**Comment by LouisSchmieder** [comment]
it's not implemented yet, but it's planned so we shouldn't add it now because we first need to parse them

**Comment by renlite** [comment]
If you compare the directives in v/vlib/vweb/tmpl/README.md, you will see the new syntax with {}.

**Comment by LouisSchmieder** [comment]
yeah but it's not implemented yet, it's just an idea how we could do it

**Comment by renlite** [comment]
Ok

**Pull request closed without merging**
