### PR TITLE
lowercase for all struct fields

### PR DESCRIPTION
**Pull request by danieldaeschle**
```v
$if method.ReturnType is ... {}
$if method.Type is ... {}
```
is now
```v
$if method.return_type is ... {}
$if method.typ is ... {}
```

### CODE REVIEW

**Comment by spaceface777** [comment]
Why do we need this? Those fields were made uppercase explicitely to make them visually different from normal fields as they work differently.

There's more info in [#5998](https://github.com/vlang/v/pull/5998#issuecomment-667544368) where this exception was added.

**Comment by spytheman** [comment]
The motivation for the lowercasing is implementing https://github.com/vlang/v/blob/master/doc/docs.md#embedded-structs .
With the syntax from there:
```v
struct Button {
    Widget
    title string
}
```
i.e. an UpperCased name in a field position, would mean that the name is actually a struct name, that would be embedded.
A lowercase name in a field position, would mean a field name (just like now).

**Comment by spaceface777** [comment]
I see. That makes sense, thanks for explaining.

What if we force a field's type to be on the same line as the field name, and an embedded struct name to be on an independent line? That would remove the need for this change and should also make code more readable.

**Comment by danieldaeschle** [comment]
Would be nice if we could make that work another way. Currently youcould declare all fields on the same line because v ignores newlines.

**Pull request merged**
