### PR TITLE
orm: detect type mismatching on inserting an object

### LINKED ISSUE #12425: orm: failed to detect mismatched column type
**V version:** Latest git
**OS:** Arch Linux x64

**What did you do?**
```
import sqlite
import json

struct Tiddler {
  id int
  created int
}

struct Tiddlers {
  id int [primary; sql: serial]
  created string
}

fn main() {
	tiddler := json.decode(Tiddler,'{}') or { Tiddler{} }
	db := sqlite.connect(':memory:') or { panic(err) }
	sql db {
		create table Tiddlers
		insert tiddler into Tiddlers
	}
}
```

**What did you expect to see?**
Compiled successfully
 
**What did you see instead?**
```
==================
/tmp/v_1000/ormfail.14399098660649273568.tmp.c:35213: error: cannot convert 'int' to 'struct string'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.
```

In addition if `or { Tiddler{} }` is removed the v error is underlined for the wrong line
```
ormfail.v:16:2: error: assignment requires a non empty `or {}` block
   14 | fn main() {
   15 |     tiddler := json.decode(Tiddler,'{}')
   16 |     db := sqlite.connect(':memory:') or { panic(err) }
      |     ~~
   17 |     sql db {
   18 |       create table Tiddlers
```

### PR DESCRIPTION
**Pull request by walkingdevel**
Fixes #12425 

And detect using undefined variables as an inserting object.

### CODE REVIEW

**Comment by enghitalo** [comment]
Thank you for your work on ORM. This lib was really in need of some love. Very good.

**Comment by enghitalo** [comment]
Thank you for your work on ORM. This lib was really in need of some love. Very good.

**Comment by walkingdevel** [comment]
> Thank you for your work on ORM. This lib was really in need of some love. Very good.

Thank you for your kind words. I want to fix all bugs related to V ORM because I think V ORM lags far behind V and other libs. And about a week later I'll start implementing new features for ORM, like the `like` operator, full type checking, the `in` operator, etc.

**Review by spytheman — APPROVED** [review]
Excellent.

**Pull request merged**
