### PR TITLE
fix bcrypt algo

### PR DESCRIPTION
**Pull request by sibkod**
https://github.com/vlang/v/issues/19558

Fix this issue

### CODE REVIEW

**Comment by medvednikov** [comment]
```
FAIL  [ 506/3007]     4.362 ms vlib/crypto/bcrypt/bcrypt_test.v
/__w/v/v/vlib/crypto/bcrypt/bcrypt_test.v is not vfmt'ed
```

**Comment by danieldaeschle** [comment]
Why don't you use the internal b64 encode/decode anymore?

**Comment by sibkod** [comment]
> Why don't you use the internal b64 encode/decode anymore?

Bcrypt uses the alphabet "./ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789" , I did not find a way to use this alphabet without changing base64, so I decided to do it using separate methods

**Review by spytheman — APPROVED** [review]

**Comment by spytheman** [comment]
Excellent work.

**Pull request merged**
