### PR TITLE
builtin: support for Cyrillic characters in string functions

### PR DESCRIPTION
**Pull request by hedgeg0d**
Adding support for Cyrillic characters in functions to_lower(), is_lower(), to_upper(), is_upper(), capitalize(), uncapitalize(), is_capital(), starts_with_capital(), title()

These function can not recognize Cyrillic symbols because they consist of 2 bytes. For example 
```println('слово'.to_upper) //"Output: "слово"```
After changes these functions can work with these characters
```
println('СЛОВО'.to_lower())
println('привет мир'.capitalize())
println('test тест'.title())
/*
Output:
слово
Привет мир
Test Тест
*/
```

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks!

Go has a more generic implementation that works with all langes.

(btw love your chess game, I hope it gets finished)

**Comment by Delta456** [comment]
Can you add for these?

**Comment by hedgeg0d** [comment]
OK, will do this now

**Review by hedgeg0d — COMMENTED** [review]
final commit
sorry for mess, tried to pull from browser first

**Pull request closed without merging**
