### PR TITLE
builtin: fix split_nth() and rsplit_nth() on an empty delimeter

### PR DESCRIPTION
**Pull request by katekyy**
### Test:
```v
module man

fn main() {
	assert '1:2:3'.split_nth(':', 2) == ['1', '2:3']
	assert '123'.split_nth('', 2)    == ['1', '23']

	assert '1:2:3'.rsplit_nth(':', 2) == ['3', '1:2']
	assert '123'.rsplit_nth('', 2)    == ['3', '12']

	assert ''.split_nth('', 2)  == []
	assert ''.rsplit_nth('', 2) == []

	println('success')
}
```

Fix bugs in `string.split_nth` and `string.rsplit_nth` with empty delimiters. Preserve the delimiter characters in the output substrings. (#18997)

### CODE REVIEW

**Comment by spytheman** [comment]
Please add the assertions in `vlib/builtin/string_test.v` too.

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by katekyy** [comment]
Oh sorry. I forgot to fmt it.
I hope that it's not a problem.

**Comment by JalonSolov** [comment]
Has to be formatted to pass the CI.

**Pull request merged**
