### PR TITLE
http/win: fix schannel from crashing

### PR DESCRIPTION
**Pull request by joe-conigliaro**
windows HTTPS requests were crashing, since update in this PR, I think maybe overlooked pointer:
https://github.com/vlang/v/pull/2120

This fixes it the issue with GCC
crashing on the call to `CertVerifyCertificateChainPolicy` on line `978`

There seems to be another issue with MSVC which this does not fix
crashing on line `284`, call: `WSAConnectByName`

### CODE REVIEW

**Comment by joe-conigliaro** [comment]
@vitalyster news fetcher example

**Comment by joe-conigliaro** [comment]
@vitalyster  the code was deff wrong

**Comment by vitalyster** [comment]
Yes I see output from news_fetcher, and in case of crash it should return non-zero error code

**Comment by joe-conigliaro** [comment]
@vitalyster I dunno thats weird

**Comment by joe-conigliaro** [comment]
@vitalyster I ran the tests locally (`v test v`) and the examples all say OK, they passed, but if i run the news_fetcher/link_scraper manually they crash, so It looks like it doesn't detect the failure, So who knows if they are working on CI

**Comment by vitalyster** [comment]
@joe-conigliaro msvc version?

**Comment by joe-conigliaro** [comment]
@vitalyster GCC, havent tried with msvc

**Comment by joe-conigliaro** [comment]
@vitalyster I tried with MSVC, and it crashes even with this change.. hrmm

**Comment by spytheman** [comment]
CI (and `v test v`) does not run examples at all, just checks to see if they compile successfully.
Only the _test.v files are compiled and run.

**Comment by vitalyster** [comment]
There is a http_test which uses schannel/wsa and did not crash

**Comment by joe-conigliaro** [comment]
@vitalyster I checked the docs and it seems `WSAConnectByName` takes pointers for the size, I changed to pointers and it runs now for me on MSVC now, so I'm not even sure how it was working for you, super weird!

**Pull request merged**
