### PR TITLE
initial implementation of anon structs

### PR DESCRIPTION
**Pull request by LouisSchmieder**
This PR will implement the basic implementation of anon structs.

The usage will be like this:
```v
struct Foo {
    anon struct {
        foo int
    }
}
```

the anon struct is implemented in type parsing, so it will be possible to use it in many possible ways like:
```v
fn foo() struct { id int } {}
```

Todo
- [x] Handle parsing
- [x] Add checks
- [x] Gen type
- [ ] Handle like anon functions
- [x] Fmt

I would like to allow for this the short struct initialization too.

### CODE REVIEW

**Comment by LouisSchmieder** [comment]
#1122

**Comment by spytheman** [comment]
why is that needed?

**Comment by spytheman** [comment]
Structs are usually important enough to have their own name, how is anonymous one useful?
Unlike a one shot anonymous function, which I do understand, what is the use case for a struct that will be used just once?

**Comment by spytheman** [comment]
Instead of:
```v
fn test(foo struct{
    id int
    name string
}) {
    // do something with it
}
```
why not just this ?
```v
fn test(foo Foo){
}
```

**Comment by medvednikov** [comment]
@spytheman this is extremely useful for JSON apis, which get to many levels of struct fields.

```
struct JsonData {
   data struct {
      children []struct {
        ....
```

**Comment by medvednikov** [comment]
I don't like anonymous struct usage in a function either.

Can' think of why it'd be needed. Perhaps it can be disallowed.

**Comment by LouisSchmieder** [comment]
Well should I continue, and if it's not needed then pls look for the old issues which doesn't will be supported, then things like this doesn't happen

**Comment by JalonSolov** [comment]
It _is_ needed for things like V UI, it is not needed (and should not be allowed) for function parameters.  That's what I got out of the thread.

**Pull request closed without merging**
