### PR TITLE
vweb: add domain and path to cookies

### LINKED ISSUE #10434: add domain and path to vweb.Cookie
## Description

Currently we can't customize the domain or the path of a cookie when setting a cookie using `vweb.Context.set_cookie()`.

## Expected behavior

I would like to be able to do this:

```v
import vweb { Cookie } 

struct App {
  vweb.Context
}

fn (mut app App) index() vweb.Result {
  app.set_cookie(Cookie{
    name: "darkmode",
    value: "0",
    path: "/", // <------ new
    domain: "localhost", // <------ new
  })

  return app.html("<h1>Hello world</h1>")
}

fn main() {
  vweb.run(&App{}, 8000)
}
```

## Notes

I see there is a `net.http.Cookie` struct, wouldn't it be better to try to share the same struct (if there is no reason to split both of course)?

### PR DESCRIPTION
**Pull request by refrogerator**
This PR tries to fix #10434 and adds support for path and domain to the cookies in vweb.

### CODE REVIEW

**Comment by medvednikov** [comment]
you have to vfmt your prs

**Comment by medvednikov** [comment]
Can you also do a test to ensure this always works correctly?

**Comment by bettafish04** [comment]
> you have to vfmt your prs

my editor does that on save afaik

**Comment by bettafish04** [comment]
> Can you also do a test to ensure this always works correctly?

sure I'll try

**Comment by JalonSolov** [comment]
Maybe it's a problem with the port number chosen in the test file.  It simply isn't able to open that particular port, for some reason.

**Comment by JalonSolov** [comment]
This sat for over a year.  I tried to close/re-open to force the CI to re-run, but it now says the repo the pull request came from has been deleted, so it can't be re-opened.

**Comment by medvednikov** [comment]
I just fixed this by using http.Cookie instead of vweb.Cookie.

**Pull request closed without merging**
