### PR TITLE
all: support `;` statements, allowing for oneliners like `./v -e 'import os; println( os.ls(os.args[1])!.sorted(a > b) )' vlib/math`

### PR DESCRIPTION
**Pull request by spytheman**

### CODE REVIEW

**Review by yuyi98 — APPROVED** [review]

**Comment by ArtemkaKun** [comment]
So now V code can be both with `;` and without it?

**Comment by Delta456** [comment]
> I mean it can be
> 
> ```
> import os;
> 
> println(os.args);
> println('hello')
> ```
> 
> and
> 
> ```
> import os
> 
> println(os.args)
> println('hello')
> ```

From the looks of this PR, yes, just like it is in Go.

**Comment by ArtemkaKun** [comment]
I'm against this PR then. 
One liner with `;` is ok, allowing optional `;` at the end of the line has no sense to me and will harm V's readability and simplicity

**Comment by spytheman** [comment]
Sorry, but I am strongly for it. The reason is, that enables rapid and interactive iteration of short one liner programs on the command line, which later, when they do work correctly, can be just copy pasted into a file, just like most scripting languages allow.

**Comment by ArtemkaKun** [comment]
Maybe we should instead implement a feature in `fmt` that will format one liner with `;` to multiple lines code without `;` to make it work in common V code?

**Comment by spytheman** [comment]
`v fmt` can just ignore `;`, instead of putting it on the end of the lines, if it was present; I do not have strong opinion on that 🤷🏻‍♂️ .

**Comment by ArtemkaKun** [comment]
I mean `fmt` will slice one liner on lines and remove `;`

**Comment by medvednikov** [comment]
> I mean fmt will slice one liner on lines and remove ;

That's what it does in Go. It's a good idea.

**Review by Larpon — APPROVED** [review]

**Comment by JalonSolov** [comment]
I agree... it is useful for more complete one-liners, but it should be removed by `v fmt`.

**Comment by medvednikov** [comment]
Done.

; is now removed by vfmt

**Pull request merged**
