### PR TITLE
encoding.html: implement `unescape()`

### PR DESCRIPTION
**Pull request by ttytm**
Implements `unescape()` for encoding. It supersedes #18922 which has become stale for a while and it doesn't fully cover that the same character can be escaped as numeric, hex or named value. So a clean start for a rewrite that covers these cases was easier and faster for me to work with.

The replacement table for named entities is extensive already. If you prefer a table consisting only of the most commonly used for the named values, please let me know, then I will reduce the size of this monster. It doesn't cover everything, so further extending it based on https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references is also possible.

### <samp>🤖 Generated by Copilot at 847235d</samp>

Add a new function `unescape` to the `encoding/html` module that can reverse the effect of `escape`, and update the tests and code structure accordingly. This allows users to decode HTML entities in strings and improves the module's design and quality.

### <samp>🤖 Generated by Copilot at 847235d</samp>

* Add a new function `unescape` to decode HTML entities in `escape.v` ([link](https://github.com/vlang/v/pull/19267/files?diff=unified&w=0#diff-2d44634831d925adee58f6c78937bcfb295faf81b450eab99ff76893afeee1e6L19-R280))
* Import `strconv` and `encoding.hex` modules to support `unescape` ([link](https://github.com/vlang/v/pull/19267/files?diff=unified&w=0#diff-2d44634831d925adee58f6c78937bcfb295faf81b450eab99ff76893afeee1e6R3-R5))
* Rename `html_replacement_table` and `html_quote_replacement_table` arrays to `html_replacement_seq` and `html_quote_replacement_seq` to avoid confusion with the new `html_replacement_table` map, which contains more named entities ([link](https://github.com/vlang/v/pull/19267/files?diff=unified&w=0#diff-2d44634831d925adee58f6c78937bcfb295faf81b450eab99ff76893afeee1e6L9-R206))
* Update `escape` function to use the renamed arrays ([link](https://github.com/vlang/v/pull/19267/files?diff=unified&w=0#diff-2d44634831d925adee58f6c78937bcfb295faf81b450eab99ff76893afeee1e6L19-R280))
* Add a new test function `test_unescape_html` to verify the behavior and correctness of `unescape` in `escape_test.v` ([link](https://github.com/vlang/v/pull/19267/files?diff=unified&w=0#diff-250bfb2602ad7aca917da49342b07d41a28a75ba0d339219c108d54acb34b04eR23-R46))
* Include different formats, converse escape tests, and reference cases in the test function ([link](https://github.com/vlang/v/pull/19267/files?diff=unified&w=0#diff-250bfb2602ad7aca917da49342b07d41a28a75ba0d339219c108d54acb34b04eR23-R46))

### CODE REVIEW

**Comment by spytheman** [comment]
> please let me know
imho `unescape` can have a `[params]` struct, where you can specify whether to use the quicker version (the default), that does the opposite replacements of `escape()`, or the more complete version, that uses the full table, i.e. its callsites can look like this:
```v
html.unescape(s) // default to quick version with replace_each()
html.unescape(s, all: true)
```

**Comment by ttytm** [comment]
Implemented the suggested config prams with the possibility to pass `all`, though without the `quote bool` field, as I have never seen this. Or does it make sense to have an option to keep `'&#34;'` `'&#39;'` while unescaping? 
I.e. is there a case where
`'&lt;a href=&#39;http://www.example.com&#39;&gt;link&lt;/a&gt;'` should become
`<a href=&#39;http://www.example.com&#39;>link</a>` instead of
`<a href='http://www.example.com'>link</a>`?

Afaik the common default is that unescape converts a larger amount than escape, but since the slimmed down version is about `3.5x` it's good to have it I guess.

**Comment by JalonSolov** [comment]
> I.e. is there a case where
`'&lt;a href=&#39;http://www.example.com&#39;&gt;link&lt;/a&gt;'` should become
`<a href=&#39;http://www.example.com&#39;>link</a>` instead of
`<a href='http://www.example.com'>link</a>`?

If you are "unescaping" the URL, I would expect the last, by default.  However, there might be a case where someone would want to keep the codes.

**Review by spytheman — APPROVED** [review]
Good work.

**Pull request merged**
