### PR TITLE
time: consolidate sleep functions into sleep(Duration)

### LINKED ISSUE #8844: sleep based on time.Duration
Currently, there are three "sleep" functions in the `time` module: `sleep`, `sleep_ms` and `usleep`.
None of these a) allow sleeping with greater than microsecond precision nor b) use the `time.Duration` type designed specifically for representing time deltas.

I would suggest removing `sleep_ms` and `usleep`, and changing the signature of `sleep` to `fn sleep(duration time.Duration)`

### PR DESCRIPTION
**Pull request by zakuro9715**
Fix #8844

> Currently, there are three "sleep" functions in the time module: sleep, sleep_ms and usleep.
> None of these a) allow sleeping with greater than microsecond precision nor b) use the time.Duration type designed specifically for representing time deltas.
>
> I would suggest removing sleep_ms and usleep, and changing the signature of sleep to fn sleep(duration time.Duration)

I strongly agree this suggestion. We should not have many different function to sleep

### CODE REVIEW

**Comment by changrui** [comment]
Yes.

**Comment by crackedmind** [comment]
Maybe replace usleep with nanosleep?

> POSIX.1-2001. POSIX.1-2001 declares this function  obsolete; use nanosleep(2) instead.  POSIX.1-2008 removes the       specification of usleep().

**Comment by spytheman** [comment]
This would be a breaking change.
I would suggest adding `[deprecated]` tags to `.usleep` and `.sleep_ms`, and making them use the new one.
Then, after several weeks we can delete them.

**Comment by spytheman** [comment]
Update: you can now use: `[deprecated: 'call sleep(x * time.microseconds)']` for say time.usleep .

**Comment by zakuro9715** [comment]
@spytheman How about that we display warning for using sleep to sleep seconds? because duration is nanoseconds, using sleep with small duration like `sleep(1)` may be a mistake

**Pull request merged**
