### PR TITLE
cgen: fix sum type match (auto-deref) - updated Sep 2nd

### LINKED ISSUE #6275: Another attempt to test sum types gets worse
**V version:** 
V 0.1.29 cbcba2e
**OS:** 
64-bit Arch Linux, up-to-date
**What did you do?**
Wrote a little program testing sum types.

**What did you expect to see?**
An executable that, when run, prints

It's an int: 5
It's a string: hello

 
**What did you see instead?**
```
dca@franz:~/Software/v_issues$ ../v/v main.v
==================
/tmp/v/main.tmp.c: In function ‘main__main’:
/tmp/v/main.tmp.c:7848:82: error: invalid type argument of unary ‘*’ (have ‘string’)
 7848 |   println(_STR("it's a string: %.*s\000 ", 2, string_add(_SLIT("&"), string_str( *(*bar)))));
      |                                                                                  ^~~~~~~
/tmp/v/main.tmp.c: In function ‘_vinit’:
/tmp/v/main.tmp.c:7879:38: warning: integer constant is so large that it is unsigned
 7879 |  _const_math__bits__max_u64 = ((u64)(18446744073709551615));
      |                                      ^~~~~~~~~~~~~~~~~~~~
/tmp/v/main.tmp.c:7906:409: warning: integer constant is so large that it is unsigned
 7906 |   ((u64)(1)), ((u64)(10)), ((u64)(100)), ((u64)(1000)), ((u64)(10000)), ((u64)(100000)), ((u64)(1000000)), ((u64)(10000000)), ((u64)(100000000)), ((u64)(1000000000)), ((u64)(10000000000)), ((u64)(100000000000)), ((u64)(1000000000000)), ((u64)(10000000000000)), ((u64)(100000000000000)), ((u64)(1000000000000000)), ((u64)(10000000000000000)), ((u64)(100000000000000000)), ((u64)(1000000000000000000)), ((u64)(10000000000000000000))}));
      |


        ^~~~~~~~~~~~~~~~~~~~
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

dca@franz:~/Software/v_issues$
```

I've concluded that V is not far enough along for me to use it for real work, so this will be my last bug report. I will check back in the future, as I think the design has merit. I hope the reports I've contributed prove to be useful.

[main.v.gz](https://github.com/vlang/v/files/5151617/main.v.gz)

### PR DESCRIPTION
**Pull request by SleepyRoy**
Fix #6275.

My first PR with sumtype only brought some preliminary support for it. This second PR

1. enables assignments and calculations within sumtype matches, even using variables with same names in different blocks. 

2. supports advanced types such as struct and enum. 

3. fixes string interpolation. 

4. improves algorithm on speed.

Please see the added test examples to have a better understanding.

Implementing this needs skills with C pointers. The generated C code should have `*` when necessary and no `*` when unneeded : )

### CODE REVIEW

**Comment by medvednikov** [comment]
@joe-conigliaro can you have a look at this?

**Comment by medvednikov** [comment]
In the meantime, @SleepyRoy can you remove `any_int` and `any_float` from the tests, these are internal types.
They won't be accessible.

**Comment by SleepyRoy** [comment]
@medvednikov No problem. But as said in discord, I prefer first to wait to see the alternative solution #6045 by @kalapalo and then decide how to do my PR.

**Comment by SleepyRoy** [comment]
Just tried changing `any_int` and `any_float` to `int`, `f64`, etc but unfortunately it still gave such error.
```
vlib/v/tests/sum_type_test.v:329:9: error: cannot use type `any_int` as type `CommonType` in argument 1 to `as_string`
  327 |     assert !calc_expr(1.5, false)
  328 |     assert calc_expr(0, true)
  329 |     assert as_string(1) == 'This is the string representation of "1"'
      |            ~~~~~~~~~~~~
  330 |     assert as_string(3.14) == 'This is the string representation of "3.14"'
  331 |     assert as_string('String') == 'This is the string representation of "String"'
vlib/v/tests/sum_type_test.v:330:9: error: cannot use type `any_float` as type `CommonType` in argument 1 to `as_string`
  328 |     assert calc_expr(0, true)
  329 |     assert as_string(1) == 'This is the string representation of "1"'
  330 |     assert as_string(3.14) == 'This is the string representation of "3.14"'
      |            ~~~~~~~~~~~~~~~
  331 |     assert as_string('String') == 'This is the string representation of "String"'
  332 | }
```

**Comment by UweKrueger** [comment]
```
> vlib/v/tests/sum_type_test.v:329:9: error: cannot use type `any_int` as type `CommonType` in argument 1 to `as_string`
>   329 |     assert as_string(1) == 'This is the string representation of "1"'
> vlib/v/tests/sum_type_test.v:330:9: error: cannot use type `any_float` as type `CommonType` in argument 1 to `as_string`
>   330 |     assert as_string(3.14) == 'This is the string representation of "3.14"'
```
@SleepyRoy You can use `as_string(int(1))` and `as_string(f64(3.14))`. Literal numbers (this is meant by `any_int`, `any_float`) aren't converted automatically to a sum type, because it's not clear if they should be `int`, `u16`, ... or `f64`, `f32` - a sum type could accept any of them.
@medvednikov perhaps we should allow implicit conversions of literals to their default types when they are assigned to sum types. It's a frequent source of confusion. What do you think?

**Comment by Delta456** [comment]
>  perhaps we should allow implicit conversions of literals to their default types when they are assigned to sum types. It's a frequent source of confusion. What do you think?
Yeah I agree @UweKrueger

**Comment by SleepyRoy** [comment]
@UweKrueger Thanks. I've applied your solution and removed all `any_int` and `any_float`.

**Comment by SleepyRoy** [comment]
Update: Simplification and more improvements. Now you can match sumtypes with structs.
```V
struct IntAndStr {
	foo int
	bar string
}

type CommonType = int | f64 | string | IntAndStr
```

**Comment by SleepyRoy** [comment]
Update: enum is supported and string interpolation is fixed.

**Comment by JalonSolov** [comment]
Looks like cgen.v needs to be updated in this PR.  Other than that, are there any other holdups?

**Comment by SleepyRoy** [comment]
@JalonSolov Yeah many days have passed since my last update. And...no holdups, at least at this stage.
But I'm not hurry to resolve these conflicts because seems that there're some potentially better draft solutions like #6342. So probably first wait for it and I'll come back to fix this PR if that try fails.

**Comment by danieldaeschle** [comment]
No longer needed due to https://github.com/vlang/v/pull/6959

**Pull request closed without merging**
