### PR TITLE
cgen: fix array of fns init

### LINKED ISSUE #5757: cannot define array of fns
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn foo() {}

fn main() {
	a := [foo]
}
```

**What did you expect to see?**
give unused var warning but still compile
 
**What did you see instead?**
C error

### PR DESCRIPTION
**Pull request by SleepyRoy**
Fix #5757.

### CODE REVIEW

**Comment by Delta456** [comment]
@SleepyRoy can you add a test of this if it works? I am not sure if it will work

```v
fn test_array_of_fns() {
	a := [foo, foo2]
       assert a[0]() == 10
       assert a[1]() == 20
	assert a.len == 2
}
```

**Comment by SleepyRoy** [comment]
@Delta456 Unfortunately it won't work with this PR. 
This PR only fixes init of array of fns. Getting elements needs more work : )

**Comment by Delta456** [comment]
@SleepyRoy Alright

**Comment by spytheman** [comment]
```v
type FnFoo fn(a string) int
fn test_array_of_fns() {
    a := [FnFoo(foo), foo2]
    f0 := a[0]
    assert f0('x') == 10
    f1 := a[1]
    assert f1('y') == 20
}
```
this works; without the casting it does not yet

**Comment by SleepyRoy** [comment]
@spytheman Thanks for the help!

**Pull request merged**
