### PR TITLE
scanner: fix number literal calling method

### PR DESCRIPTION
**Pull request by SleepyRoy**
Note: The following intro is old. Please follow the talk.
-----------------------------------------------------------------
After this PR `12.str()`, `123.4.str()`, `12e-3.str()` are possible (no more need to write e.g. `(12).str()`).
Defining float through int with a suffix dot (e.g `5.e3`, `3.`) is no longer allowed because IMO they're confusing. Please use `5.0e3`, `3.0` instead.
Tests are also added.
It may close some issues, but I didn't check.

### CODE REVIEW

**Comment by penguindark** [comment]
`5.e3` or `4.` format is widely used and supported, it can not be avoided.
Have any solution in mind?

**Comment by SleepyRoy** [comment]
@penguindark But sometimes this format causes confusion. For example, there're two ways to understand `5..str()` - 
a. str() is a function returning a integer and it's a range (from 5 to str()).
b. float number 5. (i.e. 5.0) is calling a method named str().

**Comment by spytheman** [comment]
@SleepyRoy I have never experienced the need to call methods on number literals, while I have used numbers like 5. or 5.0 many times. What is the use case for calling `5.str()` ? You already know that it is 5 after all?

**Comment by spytheman** [comment]
Using (5).str(), or x := 5 x.str() already works.

**Comment by spytheman** [comment]
```v
V 0.1.25 e2eb0f1
Use Ctrl-C or `exit` to exit
>>> fn ten() int { return 10 }
>>> for i in 5..ten() { println(i) }
5
6
7
8
9
>>>
```

**Comment by SleepyRoy** [comment]
@spytheman Yes, syntax `5.str()` seems not very useful and we indeed have workarounds like `(5).str()` you mentioned, but IMO a compiler should also consider robustness (because users may enter everything). If code is grammatically correct, then compiler should compile it (no matter whether it's useful).

**Comment by SleepyRoy** [comment]
@spytheman And about `5..str()`, let me just give an example demonstrating ambiguity
```V
fn str() int { return 10 }
for i in 5..str() {
    println(i)
} 
```
The above code works, that's nice - `5..str()` works as a range. But why it cannot be theoretically interpreted as float literal `5.` calling `.str()`? That's exactly ambiguity. How to solve this? Many ways, but one way is exactly what I said, not allowing `5.` as float literal (use `5.0` instead).

**Comment by spytheman** [comment]
@SleepyRoy what is the meaning of a range of floating point values? You can not enumerate them anyway?

**Comment by spytheman** [comment]
>5. calling .str()
Why? What is the purpose of this?

**Comment by spytheman** [comment]
By the way, Go and C *both* allow 5., 5.0 and 5.e3 as floating point numerals:
```go
package main
import "fmt"
func main() {
	x := 5.
	y := 5.0
	z := 5.e3
	fmt.Println(x)
	fmt.Println(x==y)
	fmt.Println(z)
}
```

```c
#include <stdio.h>
int main(){
    float x=5.,y=5.0,z=5.e3;
    printf("x, y, z: %f, %f, %f\n", x, y, z);
    return 0;
}
```
Why would V disable this common format, just so you could then call methods on floating point literals?
What is the practical advantage of that?

**Comment by SleepyRoy** [comment]
@spytheman `5.` calling `.str()` gives a string. Here're the two different interpretations of the above code I gave.
A. `5..str()` is interpreted as a range, so the printed results should be `5 6 7 8 9`.
B. `5..str()` is interpreted as `5.` calling `.str()` so it's a string `5.e+00` so the printed results should be `5 . e + 0 0`.
Isn't this ambiguity?
I hope this explains better. Again, case B shouldn't be omitted just because it's not useful.

**Comment by SleepyRoy** [comment]
@spytheman Practical advantage is basically zero, even minus. But the point is, if that's not well solved, syntax of V will be theoretically ambiguous. I admit my way of removing ambiguity (i.e. simply disabling `5.`) is not a nice solution, but at least is a solution.

**Comment by penguindark** [comment]
@SleepyRoy The form `5.` is a standard used in near all the languages, I'm not a fan of it, but we must support it.

**Comment by SleepyRoy** [comment]
@penguindark OK. But then we must change some grammar of V to solve this `5..str()` ambiguity problem.

**Comment by SleepyRoy** [comment]
Change to WIP. @medvednikov Do you have an idea to solve this problem of ambiguity?

**Comment by spytheman** [comment]
@SleepyRoy - I do not see an ambiguity:
a) inside `for i in x..y{..}` constructs, x can be only an integer.
b) inside `a[x..y]`, array expressions, x can also be only an integer. Passing a float with . there is just a syntax error.
c) 5..str() by itself, can also be just a syntax error, in fact it already is one:
```v
>>> 5..str()
next token = `str`
syntax error: unexpected `..`, expecting `)`
>>>
```
It only becomes a problem, IF we allow calling methods on number literals, which has no benefit in my opinion.

Am I missing/misunderstanding something?

**Comment by penguindark** [comment]
I agree with @spytheman

**Comment by SleepyRoy** [comment]
@spytheman Your summary is great and the IF part you mentioned is exactly the source of this "minor" ambiguity. But I still have the view that always tolerating such "limitation" or "exception" will finally result in a lot of "special rules" and lead to an unserious language.
As you mentioned, we could just disable number_literal.method() and give an error like "please add brackets around number literals". Do you agree with it?

**Comment by spytheman** [comment]
@SleepyRoy 
> As you mentioned, we could just disable number_literal.method() and give an error like "please add brackets around number literals". Do you agree with it?

As long as we get to keep support for the 5. and 5.e3 formats, just like C and Go, I think a more detailed error in this situation will be fine. 

@medvednikov what do you think?

**Comment by SleepyRoy** [comment]
@spytheman @medvednikov This only needs a few lines of code changing so I'm doing it now. If you agree with that idea, just merge this after I've finished.

**Comment by SleepyRoy** [comment]
Done.

**Comment by medvednikov** [comment]
I'm not sure.

I think it makes sense for `5.str()` and `10.0.str()` to work, like in Ruby.

There's little point in using this, but it's good for consistency.

**Comment by SleepyRoy** [comment]
@medvednikov You got my point. So I'll open an issue about this later and leave this PR open until a nice solution is found/agreed. Now several possible solutions and my comments on them are

a. Disable `3.` format (actually `3.e` format doesn't have this problem). This solves it.

b. Give an detailed error when this happens, like `please add backets to avoid ambiguity`. However I must point out this is technically impossible after re-thinking - How does the compiler know `5..str()` is `5.` calling `.str()` or a range from `5` to `str()`? Afterall a compiler can only read code, not your mind.

c. Change range operator. Now it's `..`, by changing it to `->`, `to`, etc. this problem is solved.

**Comment by spytheman** [comment]
@SleepyRoy :  about your point b.
V currently does *not* have standalone ranges. You can not do `a := x..z` . You do `for a in x..z`, or `a[x..y]`. So in all cases v has the context to know what is expected when there is `..` (i.e. ints, not floats).
It does not need to read your mind, just your source code.

**Comment by SleepyRoy** [comment]
@spytheman Then for the following specific code, what should be the print? 
```V
fn str() int { return 10 }
for i in 5..str() {
    println(i)
} 
```
```V
// If 5..str() is interpreted as a range, it makes sense:
5 
6 
7
8
9
```
or
```V
// If 5..str() in interpreted as 5. calling .str(), we get a string 5.e+00, so it also makes sense:
5
.
e
+
0
0
```
Don't forget `for i in range` and `for i in string` are both allowed in V.

**Comment by spytheman** [comment]
You (and I) already pasted several times what should be printed.
That is the current v behavior. There is no ambiguity now.

If V wants to be more like ruby, there *will* be ambiguity, if we allow both 5. *and* calling methods on literal numbers.
 
I am against that - I do not see the benefit, except for contrived examples, that have no practical value to me. *At all*.

I would prefer for it to continue working like it currently does, and `for x in 5..function(){}` to continue to be treated the intuitive way. I certainly would not expect for that to print
```
5
.
e
+
0
0
```

**Comment by bokunodev** [comment]
if it's a ``float`` it should look like this
```
(5.).str()
```

**Comment by SleepyRoy** [comment]
@bokunodev If syntax `number_literal.method()`  is forbidden and we must write `(number_literal).method()` , then you're right. However I guess currently there's no such a rule in V. 

Should we add such a rule? If we do, then this `5..str()` ambiguity problem is solved, nice. But the downside is simplicity/consistency of V grammar is somewhat impaired - now that `x := 5  x.str()` is allowed (no need to write `(x).str()`), why `5..str()` is wrong and we must add brackets?

**Comment by bokunodev** [comment]
@SleepyRoy 
in the case of ``x.str ()``, ``x`` is a variable and ``5.`` is a constant.
I think there must be a difference between them and how they are treated.
if they are different, they must be treated differently.

sorry for my poor english. I'm glad you understand.

**Comment by SleepyRoy** [comment]
@medvednikov A lot of days passed and I think a perfect solution to this problem is not easy to find. I just chose a relatively good solution and updated this PR. If you think it's OK, just merge it.
So this solution fixes number literals calling methods and keeps all supports for previous syntax (including `5.` and `3.e2`). The only problem remaining is `5..str()`. In this solution it's parsed as a range. If a programmer really wants `5.` calling str(), just use `5.0.str()` instead.

**Comment by medvednikov** [comment]
Thanks @SleepyRoy

**Pull request merged**
