### PR TITLE
core: add shell auto-completion

### PR DESCRIPTION
**Pull request by Larpon**
As title states.

This will add a way to get shell (currently only bash is implemented) auto-completion with v.
The install method and communication with the completion system is inspired from how [kitty](https://sw.kovidgoyal.net/kitty/#completion-for-kitty) achieve this. It's especially nice as it gives *live* auto-completion possibilities and has a minimal intrusion and install method.

There's still room for improvement but currently it can complete:

* `v <tab>` -> top level commands
* `v help<tab>` -> available help topics
* `v build<tab>` -> available build flags
* `v -<tab>` -> available flags
* `v <command> <tab>` -> mimic normal dir and file completion.

The mimicking of dir and file completion is done in V to minimize the interaction with the different shell autocompletion systems,
as these all have their own way of doing things. This also allows for filtering of e.g. `*.v` files in the future.

I've made placeholders for `fish` and `zsh` as these are also implemented in `kitty` - but I haven't got access or experience with these particular shells - so I hope someone will pick them up :sweat_smile:.

To install and use V auto-completion with bash, simply add this code snippet to your `~/.bashrc`:
`source /dev/stdin <<<"$(v complete setup bash)"`
On more recent versions of bash (>3.2) this version is recommended:
`source <(v complete setup bash)`

Happy `<tab><tab>`'ing

### CODE REVIEW

**Comment by spytheman** [comment]
Good work, but I think this should be separated to a `cmd/tools/vcomplete.v` program, otherwise it would be compiled into tools like vdoc, vfmt, etc., and increase the size of v itself.

**Comment by Larpon** [comment]
@spytheman - that's a good idea, yes. Nice spotted :smile:

**Comment by Larpon** [comment]
@spytheman - but what about autocompletion for those tools? They'd need to call out to `cmd/tools/vcomplete` anyway?

**Comment by Larpon** [comment]
... now on par with master also :slightly_smiling_face:

**Comment by Larpon** [comment]
CI failing is websocket related I believe

**Comment by spytheman** [comment]
yes, it is unrelated; I am working on fixing that

**Pull request merged**
