### PR TITLE
map: add fn delete_keys and tests

### PR DESCRIPTION
**Pull request by esquerbatua**

### CODE REVIEW

**Comment by ka-weihe** [comment]
This is not how it should be done. This is highly inefficient.

**Comment by esquerbatua** [comment]
> This is not how it should be done. This is highly inefficient and it should be named `clear` imo, but maybe it being slow is fine for now, until I update it.

The objective of the function it's no delete all elements of the map, only an limited list of the map.

**Comment by esquerbatua** [comment]
maybe the name of the fn it's not clear?

**Comment by ka-weihe** [comment]
Oh, I see... I looked too fast. The solution is fine then. I think the name is a bit unclear tho. It could be named `delete_many` or `delete_multiple` idk. `delete_all` is maybe also fine. I think `delete_all` can be a bit ambiguous with `clear` - which we may have in the future. What do you think?

**Comment by esquerbatua** [comment]
It can be anbiguous, maybe delete_many it's fine.
@spytheman pls, give your opinion

**Comment by JalonSolov** [comment]
Why not just `delete_keys`, since that's what it does?  It deletes the keys that are passed in.  It doesn't clear unless you pass in all the keys that exist.

**Comment by esquerbatua** [comment]
> Why not just `delete_keys`, since that's what it does? It deletes the keys that are passed in. It doesn't clear unless you pass in all the keys that exist.

The best option, thx!

**Comment by medvednikov** [comment]
I think 

```
for key in keys {
	m.delete(key)
}
```

is fine, no need for a 3 line function like this. stdlib has to be as small and simple as possible, this is not a very frequently used operation, and if the user needs to delete a list of keys, they can simple use a 3 line for loop.

**Pull request closed without merging**
