### PR TITLE
types: rename `any_*`, `untyped *` -> `* literal`

### PR DESCRIPTION
**Pull request by UweKrueger**
This is a follow up to 70b921c by @joe-conigliaro. It changes the names `untyped int`, `untyped float` and some remaining `any_*` to `int literal` and `float literal`. Some more error messages got back-quotes around type names, too.
`vfmt`, however, will still output `any_int` and `any_float` when formatting methods for literals in `builtin`.

### CODE REVIEW

**Comment by UweKrueger** [comment]
@spytheman Sorry, there is a huge overlap with your commit d86304b. I didn't know that you were working on the same issue...

**Comment by spytheman** [comment]
I was just trying to fix the CI in the fastest way possible to spot other problems easier.
If you have a proper fix, do not hesitate to overwrite my changes.

**Comment by UweKrueger** [comment]
Have done that already. ;-)
There are no merge conflicts anymore. And I think the errors are unrelated.

**Comment by spytheman** [comment]
In my commit, it is mostly the new branch for any_float and any_int in vlib/v/table/types.v . All the rest (the .out) files are results of that, that were produced by running `VAUTOFIX=1 ./v vlib/v/compiler_errors_test.v` twice.

**Comment by spytheman** [comment]
Yes, I think some of them are due to 9033099 (the failing vlib/clipboard/clipboard_test.v on windows).

**Comment by joe-conigliaro** [comment]
Thanks for fixing this @UweKrueger, I was going to do it another way but it was 5am and I had to go to bed 😄

**Pull request merged**
