### PR TITLE
Contributing: simplify guidelines

### PR DESCRIPTION
**Pull request by fritzblue**
While, I love the idea of pointing first time contributors to instructions on how to submit a PR, I don't think it's V's job to teach this to people. The [First Contributions](http://github.com/firstcontributions/first-contributions) interactive guide already does this extremely well, and in many languages.

Therefore, this PR slims down the Contributing guide in favor of point first-time committers to the richer, already existing guide.

### CODE REVIEW

**Comment by spytheman** [comment]
The already existing guide to which you point, instructs people to just fork the main repository.
After that, their `origin` remote will point to their own forked repository, and `v up` will stop working, since it relies on `origin` pointing to V's main repository.

**Comment by fritzblue** [comment]
Makes sense. I still propose that we keep the contributing guide V-specific. Perhaps we add a note reminding people to keep upstream named "origin"?

**Comment by spytheman** [comment]
Well, it is already pretty V specific imo.

**Comment by spytheman** [comment]
By the way, according to hub, you are basing your PR over 703202c , which is from 2019-11-10 20:47 .

The current version of this document is at https://github.com/vlang/v/blob/master/CONTRIBUTING.md . Please make your changes to the recent one.

**Pull request closed without merging**
