### PR TITLE
sha512 and sha256 : Make `write()` and `sum()` of sha512 and sha256 digest methods as an public function

### PR DESCRIPTION
**Pull request by blackshirt**
This PR changes two methods within `crypto.sha512` and `crypto.sha256` Digest's method as an public function with two reason:
1. Consistent with other digest methods in the crypto library that exports `sum`, `write`, `size`, `block_size` and partially `checksum`.method, but there are something inconsistencies in `sha512`, `sum` and `write` was a private method, and `write` method of sha256 was a private method,
2. In my own self test for ed25519, two methods of `write` and `sum` of `sha512` need to be an public function, with typical error in my tests 
```error: method `crypto.sha512.Digest.write` is private method```
 ```error: method `crypto.sha512.Digest.sum` is private```

Thanks

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Can you squash the commit in a single one?

**Comment by spytheman** [comment]
> Can you squash the commit in a single one?

There is no need for that - github does it automatically since we always use the "Squash and merge" option.

**Comment by spytheman** [comment]
Sorry for the delay @blackshirt , thanks again for the PR!

**Comment by blackshirt** [comment]
@spytheman : nope and thank you, i know its very busy time in this typical situation,  and ypu're great. I hope and glad  i can contribute to this community ..

**Pull request merged**
