### PR TITLE
checker: modify error messages for ptrs

### PR DESCRIPTION
**Pull request by Delta456**
Fix https://github.com/vlang/v/issues/3048

Earlier:
```v
foo.v:5:18: error: mismatched types `string` and `string`
    3 |      unsafe {
    4 |         b := &a
    5 |         println(b+*b)
      |                  ^
    6 |     }
    7 | }
```

```v
foo.v:5:18: error: mismatched types `string` and `string`
    3 |      unsafe {
    4 |         b := &a
    5 |         println(*b+*b)
      |                  ^
    6 |     }
    7 | }
```

Now:
```v
foo.v:5:18: error: mismatched types `&string` and `string`
    3 |      unsafe {
    4 |         b := &a
    5 |         println(b+*b)
      |                  ^
    6 |     }
    7 | }
```

```v
foo.v:5:18: error: mismatched types `&string` and `&string`
    3 |      unsafe {
    4 |         b := &a
    5 |         println(b+b)
      |                  ^
    6 | 
    7 |      }
```

### CODE REVIEW

**Comment by Delta456** [comment]
Should I add tests too? I think it will be needed.

**Comment by medvednikov** [comment]
Tests are always good :)

It should say `&string` not `*string`

**Comment by Delta456** [comment]
Done!

**Comment by Delta456** [comment]
Can this be merged now? @medvednikov

**Pull request merged**
