### PR TITLE
refactor(documentation): clarify documented behaviour of `arrays.flatten` function

### PR DESCRIPTION
**Pull request by m-charlton**
As documented the `arrays.flatten` function gives the impression that any dimension of array `n` can be reduced to dimension `n-1`. In fact `flatten` reduces a 2d array to a 1d array.

### CODE REVIEW

**Comment by spytheman** [comment]
Consider:
```v
import arrays
x := [  [  [1, 2, 3], [4, 5]  ],  [  [10, 20, 30], [40, 50]  ] ]
dump(x)
y := arrays.flatten[[]int](x)
dump(y)
```
printing:
```
[a.v:3] x: [[[1, 2, 3], [4, 5]], [[10, 20, 30], [40, 50]]]
[a.v:5] y: [[1, 2, 3], [4, 5], [10, 20, 30], [40, 50]]
```

Imho, the documentation is correct as it is.

**Comment by m-charlton** [comment]
Ignore this PR. Somehow I've managed to add several previous commits which have already been merged. Will fix problem and resubmit.

**Comment by spytheman** [comment]
I think you are missing that `T` can represent any type, including an array type too, like `[]int`, in which case `[][]T` is equivalent to `[][][]int`.

**Comment by m-charlton** [comment]
You're right. My mistake, I misread the documentation. Would an example using a 3d array clarify things?

Also could you have  a look at this [discussion](https://github.com/vlang/v/discussions/18965).

Cheers.

**Comment by spytheman** [comment]
> Would an example using a 3d array clarify things?

More concrete examples are usually better, since they make things more explicit, yes.

**Pull request closed without merging**
