### PR TITLE
always define _UNICODE and UNICODE on Windows

### PR DESCRIPTION
**Pull request by vitalyster**

### CODE REVIEW

**Comment by spytheman** [comment]
See https://devblogs.microsoft.com/oldnewthing/?p=40643
> There’s actually a method behind the madness.
The plain versions without the underscore affect the character set the Windows header files treat as default. So if you define UNICODE, then GetWindowText will map to GetWindowTextW instead of GetWindowTextA, for example. Similarly, the TEXT macro will map to L”…” instead of “…”.
The versions with the underscore affect the character set the C runtime header files treat as default. So if you define _UNICODE, then _tcslen will map to wcslen instead of strlen, for example. Similarly, the _TEXT macro will map to L”…” instead of “…”.
> What about _T? Okay, I don’t know about that one. Maybe it was just to save somebody some typing.

**Comment by vitalyster** [comment]
@spytheman text macros are old thing for Windows 95 compatibility :) It is not needed now

**Comment by medvednikov** [comment]
Looks good.

windows_gcc fails on master right now

**Comment by vitalyster** [comment]
@medvednikov it fails occasionally, looks like there still places in code where malloc is used when calloc should

**Pull request merged**
