### PR TITLE
all: rename `[ref_only]` -> `[heap]`

### PR DESCRIPTION
**Pull request by UweKrueger**
Structures that are used in a multi-threaded environment should be heap allocated, since the function that has created them may get out of scope and thus its stack becomes invalid. To insure this there has been the `[ref_only]` tag, so it was only possible to create an object as a reference.
With #8707 handling of such structs has become more flexible - they can now be embedded as *value* part of another heap allocated struct. This way heap allocation is still assured.
Due to the slight shift in meaning this PR renames the tag to `[heap]` since this reflects more precisely the intention.
Example:
```v
[heap]
struct St {
    ...
}

struct Xy {
    St // value embed (or value field)
}

a := &St{...}
b:= &Xy{
    St{...}
}
```

### CODE REVIEW

**Comment by spaceface777** [comment]
Could you add a `use [heap] instead of [ref_only]` deprecation error? People using it in their code should know that the name of the attribute has changed; having `[ref_only]` stop working silently is not a good idea IMHO.

**Comment by UweKrueger** [comment]
> Could you add a `use [heap] instead of [ref_only]` deprecation error? People using it in their code should know that the name of the attribute has changed; having `[ref_only]` stop working silently is not a good idea IMHO.

Good hint! I've added a warning for now. This can be changed to an error in 2-3 weeks.

**Review by spaceface777 — APPROVED** [review]
Good work, thanks!

**Comment by spaceface777** [comment]
although making it a warning and not an error kind of defeats the purpose, since `[ref_only]` will NOT actually work after this PR 🤔

**Comment by UweKrueger** [comment]
> although making it a warning and not an error kind of defeats the purpose, since `[ref_only]` will NOT actually work after this PR thinking

It will. It is replaced with `[heap]` internally.

**Comment by spaceface777** [comment]
oh, missed that, never mind then :)

**Comment by spytheman** [comment]
Good work!

**Pull request merged**
