### PR TITLE
v: enable `-skip-unused` default

### PR DESCRIPTION
**Pull request by felipensp**
Lets try again. :-)

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQ4ZDEwZGQyZWY0Y2JjYzQ2YzQxMzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.0gVCTRi-F9aKiGh0gzZmRHgPeiLaPijnI47ED90i5PY">Huly&reg;: <b>V_0.6-21443</b></a></sub>

### CODE REVIEW

**Comment by medvednikov** [comment]
```
V panic: compilation failed: ================== C compilation error (from /home/runner/work/v/v/thirdparty/tcc/tcc.exe): ==============
cc: /tmp/v_1001/tsession_7fa1600e6b80_01JDW1MMFWHHJ5777A6XYZWD0G/assigning_and_printing_struct_with_optional_field.exe.01JDW1QR7AXAMKA13EGWHVQQ1P.tmp.c:4386: warning: cast between pointer and integer of different size
cc: /tmp/v_1001/tsession_7fa1600e6b80_01JDW1MMFWHHJ5777A6XYZWD0G/assigning_and_printing_struct_with_optional_field.exe.01JDW1QR7AXAMKA13EGWHVQQ1P.tmp.c:4386: error: field not found: code
... (the original output was 4 lines long, and was truncated to 2 lines)
==========================================================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .

v hash: d5a64b3
/tmp/v_1001/tsession_7fa1600e6b80_01JDW1MMFWHHJ5777A6XYZWD0G/coutput_test.01JDW1QGSTP02XWGWHD9Z84B6:5612: at _v_panic: Backtrace
/tmp/v_1001/tsession_7fa1600e6b80_01JDW1MMFWHHJ5777A6XYZWD0G/coutput_test.01JDW1QGSTP02XWGWHD9Z84B6:11146: by main__ensure_compilation_succeeded
/tmp/v_1001/tsession_7fa1600e6b80_01JDW1MMFWHHJ5777A6XYZWD0G/coutput_test.01JDW1QGSTP02XWGWHD9Z84B6:10866: by main__test_out_files
/tmp/v_1001/tsession_7fa1600e6b80_01JDW1MMFWHHJ5777A6XYZWD0G/coutput_test.01JDW1QGSTP02XWGWHD9Z84B6:11306: by main
```

**Comment by medvednikov** [comment]
14 failing, 54 successful

not bad

exciting! very close

**Comment by medvednikov** [comment]
Doesn't work with usecache.

**Comment by felipensp** [comment]
> Doesn't work with usecache.

yes, I haven't checked it yet.

**Comment by felipensp** [comment]
The doom code needs `-no-skip-unused` or add `@[markused]` in some fns. @medvednikov

**Comment by medvednikov** [comment]
that's fine @felipensp 

you can add -no-skip-unused  to DOOM

**Pull request merged**
