### PR TITLE
vlib: Add markdown parser

### PR DESCRIPTION
**Pull request by nedpals**
Part of #4900 .

Initial implementation of the "markdown" that parses markdown to HTML (for now). BInds the [md4c](https://github.com/mity/md4c) Markdown parser library instead of the cmark-gfm for minimal memory footprint.

### CODE REVIEW

**Comment by nedpals** [comment]
Not sure why the md4c C library fails on C++ ://

**Comment by nedpals** [comment]
https://github.com/mity/md4c/issues/114

**Comment by medvednikov** [comment]
Let's not add almost 10k of C to vlib, even if it's temporary.

Let's create github.com/vlang/markdown, and install it if the vdoc-markdown tool (or whatever it's called) is run.

**Comment by spytheman** [comment]
```
0[17:09:15]delian@nemesis: /v/vv $ wc thirdparty/md4c/*
  6306  21818 219621 thirdparty/md4c/md4c.c
   388   1950  14494 thirdparty/md4c/md4c.h
  6694  23768 234115 total
```

**Comment by nedpals** [comment]
I can put it into a separate repo if you want, but this will be used in vdoc so I'll need to add `git clone` the module into `.vmodules` on the makefile, and use VPM for updating.

**Comment by nedpals** [comment]
@medvednikov I'm gonna wait for the autoinstall, then I'm gonna move this to `github.com/vlang/markdown` :) I'll close this for now.

**Comment by spytheman** [comment]
the autoinstall module feature will need something to test it with...

**Comment by nedpals** [comment]
We can try using v ui as the test module for now.

**Pull request closed without merging**
