### PR TITLE
array: add index() method 

### PR DESCRIPTION
**Pull request by donnisnoni95**
Add the `find()` method to the `[]string`.

I'm not sure about the method name, but for now, `find()` is the most suitable and simple. Based on request from #2189.

### CODE REVIEW

**Comment by donnisnoni95** [comment]
hmmm ... it looks like I will change my opinion about the name of the `find()` function. It looks like the function name `index_of()` is better for this purpose #2189. `find()` might be better if we want to use the high-order function or `callback`. What do you think guys ??

**Comment by spytheman** [comment]
vlib/builtin/string.v already has `index` method, that does a similar thing - given another string x, it returns the first index in s, where x occurres. Can `find` be named just `index` too?

**Comment by spytheman** [comment]
find() may indeed be a better name for the callback variant (coming from other languages).

**Comment by medvednikov** [comment]
Yes, it should be renamed to `index()`

**Comment by donnisnoni95** [comment]
Yes ... `index()` is better ... thank you all guys  👌 ✌️

**Comment by tufanbarisyildirim** [comment]
@donnisnoni95 you also dont need to complete the loop. just return if you find it. (for all loops)

**Comment by joe-conigliaro** [comment]
> @donnisnoni95 you also dont need to complete the loop. just return if you find it. (for all loops)

It will not continue, as he has this in the loop condition: `&& j == -1`

**Comment by tufanbarisyildirim** [comment]
oh right,my bad just looked from phone.

**Comment by donnisnoni95** [comment]
@tufanbarisyildirim Nice feedback... 👍
@joe-conigliaro conscientious man  👌

**Comment by joe-conigliaro** [comment]
@tufanbarisyildirim mobile screens are the worst for code 😄

**Comment by donnisnoni95** [comment]
@joe-conigliaro yaaa...even worse when we type the code on the phone ... its hard to reach the symbols like `[`, `<`, `{`  😁

**Comment by avitkauskas** [comment]
> but this make code more slim. we return just once.
As a library function, effeciency should be the main target, not nice looking :)
In your code you do 2 comparisons on every cycle instead of 1.
Tried this on the []int of length 10.000.000 with the element you search for being the last one in the array, and run .index() function 1000 times. Results:
```
time ./test
real	0m6.764s
user	0m6.731s
sys	0m0.022s
```
```
time ./test1
real	0m3.721s
user	0m3.696s
sys	0m0.017s
```
That's the difference :)
So, perhaps it's worth to return twice :)

**Comment by donnisnoni95** [comment]
@avitkauskas great !!! i will try

**Comment by tufanbarisyildirim** [comment]
@avitkauskas I didn't see that point. Thats great to think twice and compare once :) And I totally agree with you about library functions

**Comment by avitkauskas** [comment]
If you made a test, you have to assign .index() to some variable and then use it (let's say print it), otherwise gcc optimizes the code too well (at least in production mode: v -prod) and does not perform the loop at all :)

**Comment by avitkauskas** [comment]
Try this cose in both variants:
```v
struct Arr {
mut:
	a []int
}

pub fn (a Arr) index(v int) int {
	mut j := -1
	// for i := 0; i < a.a.len; i++ {
	for i := 0; i < a.a.len && j == -1; i++ {
		if a.a[i] == v {
			j = i
			// return j
		}
	}
	return j
}

mut arr := Arr{
	[0].repeat(10000000)
}
arr.a[9999999] = 1

mut idx := 0
for k := 0; k < 1000; k++ {
	idx = arr.index(1)
}

println(idx)
```

**Comment by avitkauskas** [comment]
Could you please try `v -prod ./main.v`?

**Comment by medvednikov** [comment]
@donnisnoni95 as I posted in the previous PR, you should use

```
mut j := -1
	for i := 0; i < a.len; i++ {
		if a[i] == v {
                        return j
		}
	}
	return -1
```

There's no point in measuring this, it's clear that it's faster.

It's also simpler.

**Comment by donnisnoni95** [comment]
Ok... NP... i see.... wait a minute,,, i will change

**Pull request merged**
