### PR TITLE
pref: fix is_script flag

### PR DESCRIPTION
**Pull request by danieldaeschle**
Fixes https://github.com/vlang/v/issues/7662

### CODE REVIEW

**Comment by danieldaeschle** [comment]
@spytheman i'm not sure if .vv for certain cases is the right way.

**Comment by danieldaeschle** [comment]
Hmm, can't add a test for https://github.com/vlang/v/issues/7662 since `.vv` is a "script" but the test has to be done for `.v`. We need a mode to have a script but not like `.vsh`, but without importing `os` as default.

**Comment by danieldaeschle** [comment]
maybe a -script flag

**Comment by danieldaeschle** [comment]
i think my PR tries to fix it the wrong way :(

**Comment by spytheman** [comment]
.vv is the same as .v in all aspects, except that .vv files are skipped during module building and test finding.
This allows us to use them for specific compiler tests. They are not intended to be used by users.

**Comment by spytheman** [comment]
Also note, that .vv files CAN contain invalid v code, and SHOULD NOT be checked by check-md.v .

**Pull request closed without merging**
