### PR TITLE
transformer: minor optimization for `'string literal'.len`

### PR DESCRIPTION
**Pull request by StunxFS**
This PR does a minor optimization in transformer, writing the size of a string literal directly instead of `_SLIT("").len`.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Nifty.  It keeps auto-cancelling the freebsd check, claiming the PR is closed.

**Comment by medvednikov** [comment]
It's very nice, but it'd be better to do this in the transformer, so that all backends receive an already optimized integer literal.

**Comment by StunxFS** [comment]
I do it there xD

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by lemoncmd** [comment]
`println("Hello\n".len)` outputs 7 instead of 6 after this PR

**Comment by JalonSolov** [comment]
Hrm... that would mean it is counting the characters _before_ interpolation... not good.

**Pull request merged**
