### PR TITLE
websocket: initialize function pointers with nil

### PR DESCRIPTION
**Pull request by Wertzui123**
NOTE: I'm not sure if that's the way to go, but using optionals would introduce a lot of boilerplate code instead.

### CODE REVIEW

**Comment by JalonSolov** [comment]
That boilerplate is a _lot_ safer, though.

**Comment by Wertzui123** [comment]
This is internal code though and normally either `handler` or `handler2` is guaranteed to be set. Sure, it could segfault if one forgets to initialize them when creating a new instance, but I don't see where, except for the current usage, that would even be needed.

**Comment by Wertzui123** [comment]
Yes, I know, but that won't work here as either `handler` xor `handler2` must be set and which one is set is determined by another field.

**Review by spytheman — APPROVED** [review]
Good work. Thanks.

**Pull request merged**
