### PR TITLE
checker: check match exhaustivity on enums

### LINKED ISSUE #4239: Match must be exhaustive
**V version:** V 0.1.26 abd0686.abd0686
**OS:** MacOS

**What did you do?**
```
// enums.v 
enum Colour { red green blue }
fn main() {
  mut col := Colour.red
  match col {
    .red    { println("Red") }
    .green  { println("Green") }
    .blue   { println("Blue") }
  }
}
```
```% v enums.v```

**What did you expect to see?**
Red
 
**What did you see instead?**
enums.v:9:0: error: match must be exhaustive

### PR DESCRIPTION
**Pull request by Gladear**
Checks if match on enums are exhaustive.
Fixes #4239

### CODE REVIEW

**Comment by Gladear** [comment]
I just saw that `v fmt` automatically replaced the last `match` branch by an `else`.
Not sure if that's the desired behaviour, but it may have made my tests irrelevant.

**Comment by medvednikov** [comment]
That's a vfmt bug

**Comment by danieldaeschle** [comment]
Lol i made the same PR #4388
But with more fixes...

**Comment by danieldaeschle** [comment]
Let Alex decide which is better 😄👌
Sorry

**Comment by danieldaeschle** [comment]
Can be closed @spytheman ?

**Comment by Gladear** [comment]
@danieldaeschle You're PR is more complete :blush: If it is merged, I'll close this one :wink:

**Pull request closed without merging**
