### PR TITLE
docs: document the `[required]` struct attribute

### PR DESCRIPTION
**Pull request by spaceface777**

### CODE REVIEW

**Comment by medvednikov** [comment]
./vlib/eventbus/README.md:32:1: error: `oksyntax` example with invalid syntax

**Comment by spaceface777** [comment]
Well, I didn't touch the `eventbus` README 😀

**Comment by medvednikov** [comment]
Yeah it's strange.

**Comment by spytheman** [comment]
The reason it is failing, is because the Docs CI is setup to run only on changes to the .md files, but that heuristic fails, when there are changes to syntax that the compiler recognizes. This PR was just unfortunate to trigger the Docs CI, instead of the one that make the docs invalid.

**Comment by spytheman** [comment]
I think the docs ci should run on every commit. Otherwise it is wasting programmer's time and creating confusion, just to save some CPU cycles.

**Pull request merged**
