### PR TITLE
builtin: added read and readln functions

### PR DESCRIPTION
**Pull request by archanpatkar**
This PR adds two functions  ```read``` and ```readln``` into the builtin module which facilitate reading a single character from **stdin** and a reading a line from **stdin** ( reading characters till ```\n``` ) these are essential functions which facilitate user input. These functions are platform independent as they use ```getchar``` which is available on every platform ( ```stdio.h``` )

This is a new PR had to close the last PR and delete the last fork for cleaning up and syncing

### CODE REVIEW

**Comment by vitalyster** [comment]
Again:
> platform independent as they use getchar

No, windows does not have correct getchar implementation

**Comment by archanpatkar** [comment]
> Again:
> 
> > platform independent as they use getchar
> 
> No, windows does not have correct getchar implementation

@vitalyster I think it supports ASCII

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getchar-getwchar?view=vs-2019

**Comment by archanpatkar** [comment]
> Again:
> 
> > platform independent as they use getchar
> 
> No, windows does not have correct getchar implementation

I think it supports ASCII

**Comment by vitalyster** [comment]
And what is a purpose of this broken solution?

**Comment by ntrel** [comment]
First, please don't open extra pull requests unless you completely redesign the code, force push instead.

Second, you ignored all my review comments in the other pull, and marked them as resolved when they are unresolved. I replied to each of your points just now.

**Comment by archanpatkar** [comment]
@ntrel Sorry, I closed the PR before I could see your reviews. I am considering your suggestions in my next commit

Thanks

**Comment by medvednikov** [comment]
Thanks, but these function are not cross-platform, and there's already `os.get_line()`.

**Pull request closed without merging**
