### PR TITLE
parser: check var name is not reserved as built in type

### PR DESCRIPTION
**Pull request by LorenzoPirro**
About #2669 issue, I've added a simple check that doesn't allow to use built-in basic types (i8, i16, rune, etc...) as variable names.

### CODE REVIEW

**Comment by medvednikov** [comment]
Hm... This is adding 15 string comparisons before each var declaration.

The funny thing is that Go, for example, has no problem with `string := 10; println(string)`.

**Comment by LorenzoPirro** [comment]
@medvednikov you've reason, but the only way to do this would be having a separate `map[string]bool` in memory. Is it acceptable?

**Comment by medvednikov** [comment]
Yes, same with Java, Kotlin, etc.

But I agree with you it's better not to allow this.

Storing it in a map is not a problem.

**Comment by LorenzoPirro** [comment]
@medvednikov  ok, i try :)

**Comment by medvednikov** [comment]
You have an old version of the code.

**Pull request closed without merging**
