### PR TITLE
checker: add warn about non-option function

### PR DESCRIPTION
**Pull request by felipensp**
This PR is about the ROADMAP item "Handle function pointers safely, remove if function == 0 {".

```V

type MapFunc = fn () 

struct Test {
	a fn (int) // warn
	b ?fn () // ok
	c MapFunc // warn
	d ?MapFunc // ok
}

fn main() {
	t := Test{b: fn () {
		println('cool')
	}}
	z := t.b?
	z()
	dump(t)
}
```

```
$ v run bug.v
bug.v:2:16: warning: you should declare it as Option instead
    1 | 
    2 | type MapFunc = fn () 
      |                ~~~~~~
    3 | 
    4 | struct Test {
bug.v:5:4: warning: you should declare it as Option instead (?fn ...)
    3 | 
    4 | struct Test {
    5 |     a fn (int) // warn
      |       ~~~~~~~~
    6 |     b ?fn () // ok
    7 |     c MapFunc // warn
bug.v:7:4: warning: this is not recommended, you should use Option function instead
    5 |     a fn (int) // warn
    6 |     b ?fn () // ok
    7 |     c MapFunc // warn
      |       ~~~~~~~
    8 |     d ?MapFunc // ok
    9 | }
cool
[bug.v:17] t: Test{
    a: fn (int)
    b: Option(fn ())
    c: fn ()
    d: Option(none)
}
```

### <samp>🤖 Generated by Copilot at 100f441</samp>

Warn about direct function types in struct fields. The change modifies `vlib/v/checker/struct.v` to emit a warning when a struct field is declared as a direct function type without the option flag, as this can cause memory issues. The change is part of a pull request to improve function type safety in V.

### <samp>🤖 Generated by Copilot at 100f441</samp>

* Add a warning message for direct function types in struct fields ([link](https://github.com/vlang/v/pull/18560/files?diff=unified&w=0#diff-5a78d6ef98b6b2c2d5acab77fadb4e8131186177da378b9160e407ee02720b88R138-R144))

### CODE REVIEW

**Comment by felipensp** [comment]
> ```v
> struct Test {
> 	a fn (int)
> 	b ?fn ()
> }
> 
> fn main() {
> 	t := Test{b: fn () {
> 		println('cool')
> 	}}
> 	z := t.b?
> 	z()
> 	dump(t)
> }
> ```
> 
> ```
> $ v run bug.v
> bug.v:2:4: warning: direct function declaration is not recommended, use Option instead (?fn ...)
>     1 | struct Test {
>     2 |     a fn (int)
>       |       ~~~~~~~~
>     3 |     b ?fn ()
>     4 | }
> cool
> [bug.v:12] t: Test{
>     a: fn (int)
>     b: Option(fn ())
> }
> ```
> 
> ### 🤖 Generated by Copilot at [100f441](https://github.com/vlang/v/commit/100f441e3f865d9863dd86b5369957be3eebfd1d)
> Warn about direct function types in struct fields. The change modifies `vlib/v/checker/struct.v` to emit a warning when a struct field is declared as a direct function type without the option flag, as this can cause memory issues. The change is part of a pull request to improve function type safety in V.
> 
> ### 🤖 Generated by Copilot at [100f441](https://github.com/vlang/v/commit/100f441e3f865d9863dd86b5369957be3eebfd1d)
> * Add a warning message for direct function types in struct fields ([link](https://github.com/vlang/v/pull/18560/files?diff=unified&w=0#diff-5a78d6ef98b6b2c2d5acab77fadb4e8131186177da378b9160e407ee02720b88R138-R144))

@medvednikov Should we make possible to do "t.b?()" too?

**Comment by spytheman** [comment]
imho, this should be a notice instead of a warning, at least for now

**Comment by ArtemkaKun** [comment]
This PR is also closes #9977

**Comment by felipensp** [comment]
Already implemented as notices.

**Pull request closed without merging**
