### PR TITLE
checker: check unsafe array assign (fix #9651)

### LINKED ISSUE #9651: struct.array mut assign does not cause a compiler error
**V version:** V 0.2.2 7c79e9b
**OS:** Windows 10 (MINGW64_NT-10.0-17763 SEGOTW10400433 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys)

**What did you do?**
Copy a mutable array (ref?).

```v
struct Dumb {
mut:
	v []int
}

fn main() {
	a := Dumb{[1,2,3]}
	mut b := a.v // I expect a compiler error
	for _ in 0..100 {
		b << [4, 5, 6]
	}
	println(a) // prints [4,5,6] in this case, but I've also seen crashes
}
```

**What did you expect to see?**
I expected to get an error during compilation. When not redirecting via a struct I get a "use clone()" error message. A more complex scenario than the above example also caused crashes.

**What did you see instead?**
In this case the wrong output when executed. But in a more complex case I've also seen crashes.

### PR DESCRIPTION
**Pull request by yuyi98**
This PR check unsafe array assign (fix #9651).

- Check unsafe array assign.
- Add test.
- Modify all the related issues.

```v
struct Dumb {
mut:
	v []int
}

fn main() {
	a := Dumb{[1, 2, 3]}
	mut b := a.v // I expect a compiler error
	for _ in 0 .. 100 {
		b << [4, 5, 6]
	}
	println(a) // prints [4,5,6] in this case, but I've also seen crashes
}

PS D:\Test\v\tt1> v run .
./tt1.v:8:8: error: use `mut array2 := array1.clone()` instead of `mut array2 := array1` (or use `unsafe`)
    6 | fn main() {
    7 |     a := Dumb{[1, 2, 3]}
    8 |     mut b := a.v // I expect a compiler error
      |           ~~
    9 |     for _ in 0 .. 100 {
   10 |         b << [4, 5, 6]
```

### CODE REVIEW

**Comment by yuyi98** [comment]
@medvednikov  Can you merge the PR of VUI first?

**Comment by yuyi98** [comment]
@spytheman   Sorry, there are still some errors here, I have fixed them, please help to merge it.

**Comment by spytheman** [comment]
done

**Comment by yuyi98** [comment]
Thanks !!!

**Comment by spytheman** [comment]
@yuyi98, since that appears to have the potential, to break many code bases, although it is very good to have an error for it in the long term, can we make just the new case, a notice/warning for say a month?

**Comment by yuyi98** [comment]
Ok, I think so.

**Pull request merged**
