### PR TITLE
vlib: array: simplify/optimize current str() and add float impl

### PR DESCRIPTION
**Pull request by nsauzede**
Fix current array str() implementations to use simpler construct and optimized inner test
Add float cases

### CODE REVIEW

**Comment by nsauzede** [comment]
my fix breaks build because examples/spectral.v defines non-local array operator, which should be forbidden in user code
will push more commits to fix that
PR on hold..

**Comment by medvednikov** [comment]
hey

this is something that has to be generated by the compiler

I don't want 20 copies of `str()` for each type.

I'll implement this by tomorrow.

**Comment by nsauzede** [comment]
ok
will you consider using my simpler/optimal impl in the generated coded ?

**Comment by nsauzede** [comment]
also, if you plan to generate all those str(). you'll have to forbid/prevent user code (ex: examples) to define their own builtin types operators : this breaks compilation.. (see the current PR failing log eg: in spectral.v : you'll get the same errors if all (including f64) str() are generated/implemented)

**Comment by nsauzede** [comment]
off-topic : (sorry about that)

currently in order for "make test" to pass, I have to use that diff :
diff --git a/compiler/main.v b/compiler/main.v
index f2306f1..79b1c75 100644
--- a/compiler/main.v
+++ b/compiler/main.v
@@ -804,7 +804,7 @@ mut args := ''
                a << '-lm -lpthread ' 
                // -ldl is a Linux only thing. BSDs have it in libc.
                if v.os == .linux {
-                       a << ' -ldl ' 
+                       a << ' -ldl -lX11 ' 
                } 
        }
        if v.os == .windows {

Although I'm not sure it's the current way to solve the fact that on linux, graphical examples like tetris need to add "-lX11"
what do you think ?
are you testing graphical apps on linux/X11 ?

**Comment by medvednikov** [comment]
That's strange. Graphical examples work in Travis, `-lglfw` is enough.

**Comment by spytheman** [comment]
@nsauzede please, would you tell what distribution do you use? 
I've tested on Ubuntu 16.04.3 LTS, and -lglfw seems enough, because libglfw.so.3 itself depends on libX11 : libglfw.so.3 depends on libX11.so.6 on Ubuntu 16.04

**Comment by nsauzede** [comment]
interesting..
I'm running ClearLinux, which doesn't seem to provide devel glfw lib
so I had to compile/install it from source
then, at build time, it seems like an additional explicit -lX11 is required
oh well... probably I messed something..
anyway, since I setup the glfw manually, let's consider this is a bug on my side, so please ignore my report on -lX11..
I'll see if I can make ClearLinux push libglfw-dev upstream, rather..
thanks for your comments

**Comment by medvednikov** [comment]
@nsauzede this will be taken care of soon

All you will have to do is run

`v install glfw`, and it will build the C dependency from source.

**Comment by medvednikov** [comment]
This has finally been implemented for all array types.

**Comment by nsauzede** [comment]
> @nsauzede this will be taken care of soon
> 
> All you will have to do is run
> 
> `v install glfw`, and it will build the C dependency from source.

it seems like this still doesn't build/copy the linux libglfw.so thirdparty ? only the windows DLL is present ?

**Pull request closed without merging**
