### PR TITLE
WIP: time: module improvement and cleanup

### LINKED ISSUE #2331: Time conversion to/from Unix time is incorrect
**V version:** V 0.1.21 b1806b5
**OS:** Mac OS

Either `unix()` or `calc_unix()` functions are wrong.
Also, `unix()` function does not fill in `.uni` field.
As it is used in `add_seconds()`, this also makes `uni` field `0`.

**What did you do?**
```v
import time

d1 := time.parse('2020-01-01 00:00:00')
d2 := d1.add_seconds(time.seconds_per_day)
d3 := time.unix(d1.uni)

println(d1)
println(d2)
println(d3)
```

**What did you expect to see?**
```
{
	year: 2020
	month: 1
	day: 1
	hour: 0
	minute: 0
	second: 0
	uni: 1577829600
}
{
	year: 2020
	month: 1
	day: 2
	hour: 0
	minute: 0
	second: 0
	uni: 1577916000
}
{
	year: 2020
	month: 1
	day: 1
	hour: 0
	minute: 0
	second: 0
	uni: 1577829600
}
```
 
**What did you see instead?**
```
{
	year: 2020
	month: 1
	day: 1
	hour: 0
	minute: 0
	second: 0
	uni: 1577829600
}
{
	year: 2020
	month: 1
	day: 1
	hour: 22
	minute: 0
	second: 0
	uni: 0
}
{
	year: 2020
	month: 12
	day: 30
	hour: 22
	minute: 0
	second: 0
	uni: 0
}
```
`d2 := d1.add_seconds(time.seconds_per_day)` added only 22 hours, not a full day.
`d3 := time.unix(d1.uni)` did not convert date-time back correctly.

### PR DESCRIPTION
**Pull request by avitkauskas**
For now added just two functions to convert Time to/from Unix timestamp.
Both of these functions interpret time data as UTC.
Based on algorithms of Howard Hinnant (http://howardhinnant.github.io/date_algorithms.html).
Checked with https://www.epochconverter.com

The code of the functions could look a bit cryptic and variable names could look not so much self expanatory, but that is inevitable anyway as many "magic" constants are used in the algorithms, so I decided to leave it this way as detailed explanations for the interested are available in the link provided in the comments.

This is for discussion of how to procede further.
Now `time` module is quite a mess: 
- some functions give `struct Time` data in local time zone, but `.uni` field in UTC, 
- calculation from Unix to Time is by one day off, 
- formating functions are not systemic, but just random ad-hoc functions as needed
- etc.

I also changed the `Time.uni` field to `i64` to cover reasonably wide span of years.
All tests locally pass (except unrelated `test_float_equal_operator()`), and complier can compile itself, so most probably this did not broke anything.

If we agree that it is a good starting point and we should continue making all `time` functions consistently working with UTC time (and introducing `local` variants later), we can start looking on what should be deleted and corrected in `time` module.

In particular, this PR aiming to fix #2331.

Your comments are welcome.

### CODE REVIEW

**Comment by avitkauskas** [comment]
No, actually `.uni i64` did broke some code. But that is irrelevant at the moment. This PR should not be merged yet anyway.

**Comment by spytheman** [comment]
I think Time should have a ms (millisecond) field as well.
It is used in vlib/log/log.v , and from my experience logs of high performance apps sometimes need a millisecond resolution, not just seconds.

**Comment by spytheman** [comment]
Go's https://golang.org/pkg/time/#Time has a nanosecond precision.

**Comment by avitkauskas** [comment]
I was experimenting with the Time functions and making some research during these days to find the best way to implement the Time data structures and functions. These are my thoughts:

We use C `time()` function to get the current time (and will keep using it for the nearest future, I suppose). C `time()` works with the `time_t` data type. Historically, this data type used to be 32-bit, though in the past 10 year or so in some implementations it became 64-bit (mostly on 64-bit systems). But on 32-bit systems it still remains 32-bit.

We use C `localtime()` function to get the local time with the Time Zone difference and daylight saving time (DST) settings. This functions look to work reliably on all systems only with the 32-bit `time_t` versions, covering the years (roughly) from 1902 to 1938.

On the other side. If you care about the local time (that is about the Time Zone and DST), then it's probably does not make sense to operate in the wider range of the years, as there is no sense to talk about the Time Zones in 15th century (neither in 22nd century, I suppose - things do change).

So, for Local Time, 32bit (int) is OK to represent the time in seconds. And when we talk about the normal civil local time, seconds is enough, we do not need micro/nano seconds for that.

On the other side, if you deal with the arbitrary time (some day in 15th century, or you want some time travel experience to 3059-12-25 to see if X-mas is still there), then you should not be thinking about the Time Zones and DST. But you need much wider range of years to be covered. So, you need 64-bit (i64) number to represent the time. And seconds are enought for you.

If you want to measure some quick and short events in time though, you sometimes need minco or nano seconds. And then you probably do not talk about the dates (fixed time points), but about the Duration.

Therefore, my thinking goes this way. We need 3 different time types: 
-- LocalTime (32-bit int in seconds, with the fields in the struct for year, ..., second, TZ and DST;
-- Time (64-bit i64 in seconds, with all the same fields (year, ..., second), but no TZ and DST;
-- Duration (64-bit in nanoseconds, with same year, ..., second fields, plus micro and nano seconds.

And we need functions specializing on these types. Like 
- `loc := time.now()` giving current local time with TZ and DST
- `arb := time.new()' giving arbitrary time without the TZ (taking current UTC time initially)
- `mom := time.moment()` giving current moment in Duration with nanoseconds;
- `loc.add(sec int)` would work on LocalTime in 1901-2038 range (with checking)
- `arb.add(sec i64)` would work on Time (64-bit) (+- 209 billions years) no checking, any date.
- `mom.add(Duration) dealing with nanosecond precision.

Keeping all 3 types in one structure `Time` is possible, but inconvenient, as you should be regularly jugling with `int` to/from `i64` conversion if you would like to work directly with the `i64` field in the Time struct. And that is inconvenience and not safe when your most used type is `int`. If you need arbitrary time, then you would be prepared to work with `i64` and would plan your other variables accordingly.

Also, implementing micro/nano time functions is system dependent, so having separate Duration type and not mix it with LocalTime and Time, would make sence.

What do you think about all that?

**Comment by spytheman** [comment]
@avitkauskas thank you for your research. 

Time is fascinating and often overlooked topic in programming indeed.

In my opinion, the internal operations of the time module should be done, on what you call arbitrary values, i.e. (64-bit i64 in seconds, with all the same fields (year, ..., second), but no TZ and DST, presumably UTC times). I think that using i64 would not be a problem, since only the time module would need to be concerned with that implementation detail. The users will just use Time structs and the time module API.

I also think that there should be available input/output functions to convert local times to this format and from it to local times, by passing a locale/timezone/DST information. The goal is to be able to represent the same moment in time, in different timezones, if an application desires that (say a calendar app, or a flight scheduler).

About the nanosecond precision - you are right that it is needed most often in relative calculations and not in absolute terms, like when you want to time a given operation, or if you want to see in a log file, whether an event happened before or after another one (possibly an event from another process/machine), so a separate Duration or HighPrecisionTime type may be fine.

**Comment by avitkauskas** [comment]
I'll try to demostrate one specific problem with that. 

Let's say we have some Time that I got with `t := time.now()` with the Unix time set to some moment today (2019-10-18 15:00:00). And I am in UTC+2 and DST now. 
And `time.now()` set everything fine for me. 

Now I use function `t.add(20 * time.days)` (I have this const defined in `time` module now).

If I deal with local time here (and I am), then my result is some time in November 7, with DST set to false, so if now I had time 15:00:00 in my Time stuct (that is t.hour == 15), then affter the call to `add()` I will have `t.hour == 14). But the difference between these to moments will be exactly 20 days.

Though, if I deal with arbitrary time without the time zone, 
then I would expect my result being `t.hour == 15`.

That is the motivation of two types: `LocalTime` and `Time`. Depending on my needs, I can choose to use one or another. 

Or we need two functions (methods): `add_local(seconds)` and `add(seconds)`. What is better?

Yes, time is quite complicated matter :) And we did not even start thinking about non-Gregorian calendars :)

**Comment by shsr04** [comment]
> On the other side. If you care about the local time (that is about the Time Zone and DST), then it's probably does not make sense to operate in the wider range of the years, as there is no sense to talk about the Time Zones in 15th century (neither in 22nd century, I suppose - things do change).

I would eliminate the `LocalTime` struct and only keep `Time` and `Duration` (`HighResTime`?).
That way, you don't have to worry about time zones: if realize that you need TZ after all, you don't have to change anything because `Time` already includes that information.

Maybe it doesn't make sense to think about time zones in the 15th century, but it does make sense to keep everything consistent and naturally understandable.

**Comment by spytheman** [comment]
In my opinion, only a single i64 would need to be stored, representing the standart Unix time in seconds (although Go stores nanoseconds, which reduces by 30 the number of bits for representing the seconds, that still leaves 33 bits, i.e. more than enough imo for most practical purposes)

All time manipulation ops will use it, without exception. All other fields of Time (if any), may serve only as temporary caches, derived from this canonical source of truth for the Time struct.

Input and output should convert to it/from it, so in your example, your local time will get converted to the internal representation, then after the time period is added, and you want to say print the result in local time, it would get converted back to a string describing the new time using the information about your locale).

**Comment by spytheman** [comment]
In other words, timezones are property of the locale, not of the time itself.

**Comment by shsr04** [comment]
With a `Time` struct as return type, you can do something like this:

```v
t := time.now()    // = struct Time
println('It is the ${t.day}th ${t.month_str()} of the year ${t.year}')
```

as opposed to

```v
t := time.now()    // = i64 (epoch)
println('It is the ${time.day(t)}th ${time.month_str(t)} of the year ${time.year(t)}')
```

The struct version is a bit more convenient, but I guess either version is good.

**Comment by spytheman** [comment]
I have just encountered this: https://github.com/kstenerud/smalltime . It seems very well thought out to me.

**Comment by spytheman** [comment]
> ```v
> t := time.now()    // = struct Time
> println('It is the ${t.day}th ${t.month_str()} of the year ${t.year}')
> ```
That seems nice indeed, it would just need to specified in the documentation, that the fields have the values in UTC, and if someone wants the local time, he would need to use another API, like 
t.format_local_time(locale, 'format string') or something.

**Comment by shsr04** [comment]
Well, if the `Time` struct already includes the TZ information, it would go like this:
```v
t := time.now()    // is UTC+0
t.set_tz(time.JST)     // => UTC+9
println(t.iso_str())   // => '2019-10-19T18:48:30.9+09:00'
```

**Comment by medvednikov** [comment]
Sorry for the delay.

I'm a big fan of Go's time package. I think ours should be very similar.

It's based on nanoseconds

```
const (
	Nanosecond  Duration = 1
	Microsecond          = 1000 * Nanosecond
	Millisecond          = 1000 * Microsecond
	Second               = 1000 * Millisecond
	Minute               = 60 * Second
	Hour                 = 60 * Minute
)
```

**Comment by medvednikov** [comment]
I've already started to slowly migrate from C functions to a pure V implementation.

**Comment by avitkauskas** [comment]
OK, so then I close this PR. I just wanted to make `time` module a bit better. But my time would not allow me to reimplemet in a totally different and much more complicated way (as Go has), especially without using C fuctions. As I understand, Alex is working on this anyway.

**Pull request closed without merging**
