### PR TITLE
native: refactor PE file generation

### PR DESCRIPTION
**Pull request by Spydr06**
This PR refactors the PE file generation code (`pe.v` & `dos.v`) for native windows targets in a similar manner to `elf.v`.

I've also got all unit tests working on Windows targets now too!

I'm still deciding how to implement linking support. We have two options:

1. Output a ".EXE" file directly as done right now; PE files linking with DLLs is already partially implemented.
2. Rely on another linker like `lld-link` (from llvm) or msvc's `LINK.EXE` (microsoft standard)

(`array.v` contains beginnings of `builtin` array support, nothing concrete yet though, as we need linking to continue)

Edit:

Option 1 was chosen, linking with DLLs is now implemented _without_ a linker.
To figure out which dlls to link to and which symbols come from where, we need a list of all needed dlls then parse/index every one of them

### <samp>🤖 Generated by Copilot at 043ae00</samp>

~~This pull request adds support for the `print` and `eprint` functions, string interpolation, and array operations for the native backend on all platforms.~~ It also refactors some code, improves the native tests, and implements some parts of the PE format for Windows. It modifies and adds files in the `native` module, such as `amd64.v`, `gen.v`, `macho.v`, `array.v`, `dos.v`, `expr.v`, and `print.vv`. It also changes some files in the `native/tests` directory, such as `native_test.v`, `print.vv.out`, and `print.vv`.

### <samp>🤖 Generated by Copilot at 043ae00</samp>

*  Implement the `print` and `eprint` functions for the native backend on Windows ([link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cL1246-R1246), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cL1266-R1292), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cR1414-R1418), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cL3989-R4015), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-2c72949f2e9639a908055366823bfe6f73ef841f6c0e5f1f1bc15d8e72d73f66L394-R404), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R1144-R1207), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-a62e48caab8d150449ddcbefd2e14dba9e555b33cf19313c07f06c147a7834e5L50-R51))
*  Implement the array support for the native backend on all platforms ([link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-71677a223707eecd395dc6f17419b4481be60f2ff735cf90f9072f237d3700b7R1-R89), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-2c72949f2e9639a908055366823bfe6f73ef841f6c0e5f1f1bc15d8e72d73f66L394-R404), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R1144-R1207))
*  Implement the PE format for the native backend on Windows ([link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-364b723f2708fdfd322e47aab39a8962fd20a9691c3c604d1680262ac893e4cfR1-R167), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5L61-R70))
*  Refactor the code to improve the modularity of the ELF and PE formats ([link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-1939a07fdc8f413f48d83dd89c0def2cdeeffe49d26739babcdc103d88260d52L885), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5L31-L32), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-2c3a02685149dd0464f9255110a8d4dee49d3eb776576f9647d9adb735e67651L436-L441), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-2c3a02685149dd0464f9255110a8d4dee49d3eb776576f9647d9adb735e67651L477-L507))
*  Add a feature to suppress warnings from the native backend by passing the `-skip-warnings` flag to the compiler ([link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R1085-R1088))
*  Add a utility function to write zero bytes to the code generator buffer ([link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R604-R609))
*  Add utility functions to pad or align the code generator buffer ([link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R626-R638))
*  Enable the native tests to run on Windows and improve the portability and debugging of the test paths and messages ([link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-2e8a09fc3b5271c41e2ab67cb69ad7f1d6d893a273acee9e8827285c868a2fb0L13-R20), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-2e8a09fc3b5271c41e2ab67cb69ad7f1d6d893a273acee9e8827285c868a2fb0L40-R48), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-2e8a09fc3b5271c41e2ab67cb69ad7f1d6d893a273acee9e8827285c868a2fb0R61), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-2e8a09fc3b5271c41e2ab67cb69ad7f1d6d893a273acee9e8827285c868a2fb0L66-R77))
*  Add a test for the `print` function with interpolated strings ([link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-3eaf2edefc92d856be034a8ee0fe3032740b526fa7792e999f19e40579bdca55R97-R106), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-3eaf2edefc92d856be034a8ee0fe3032740b526fa7792e999f19e40579bdca55R115), [link](https://github.com/vlang/v/pull/19140/files?diff=unified&w=0#diff-c5cbc366fccf98ecc36867f04b4119666af26c9d00dbb4ef7daab8f2afb3e76fR22-R23))

### CODE REVIEW

**Comment by Spydr06** [comment]
There is an issue with `os.execute()` on windows; it doesn't seem to capture stderr output to a file with `2>`.
All tests work now on windows too, but `print.vv` fails because of this.

**Comment by JalonSolov** [comment]
I would go with Option 1, since you can't guarantee any particular linker will be available on a user's machine.  It will also keep things simpler for cross-compiling/linking.

**Comment by Spydr06** [comment]
With Option 1 I'm only scared that we run into issues with 3rd-party libraries.

Linking to libc isn't hard, just add `CRTDLL.DLL` and the necessary functions to the import list and fix the currently hard-coded import offsets.
I'm just worried about running into issues with 3rd-party libs and non-DLL files

**Comment by JalonSolov** [comment]
Weird error...
```
exec failed (CreateProcess) with code 193: %1 is not a valid Win32 application.
```

**Comment by Spydr06** [comment]
which program?

**Comment by spytheman** [comment]
(rebased over master to get the windows fix in 9e0c294; applied a workaround for the cstrict problem)

**Comment by spytheman** [comment]
The CI is especially slow today:
image

**Comment by Spydr06** [comment]
It's weird that `native backend CI / native-backend (windows-2022)`, while `windows-2019` passes...
Locally, the tests pass on my windows 11 install without problems

**Comment by spytheman** [comment]
> It's weird that native backend CI / native-backend (windows-2022) fails, while windows-2019 passes...

Yes, it is weird 🤔 . I also could not find the underlying reason. I'll try again tomorrow, after some sleep.

**Comment by Spydr06** [comment]
Ah ok, thanks and no pressure xD

**Comment by Spydr06** [comment]
`__offsetof()` is not consistent across OSs, even on `[packed]` structs.

**Review by spytheman — APPROVED** [review]

**Pull request merged**
