### PR TITLE
math.big: rework function naming and documentation

### PR DESCRIPTION
**Pull request by phoreverpheebs**
## Overview

* A few functions are renamed to allow for a more extensible, legible and standardized scheme; i.e. mathematical functions (`isqrt`, `gcd`, ...) remain as they are, however methods such as `left_shift` and `right_shift` are changed to be more verbose and clear -- allowing future `left_rotate` and `right_rotate` methods (more legible than e.g. `rrotate`). The renaming of `lshift` and `rshift` is applied internally as well for consistency.

* The function `bit_length` is deprecated as it seems to have been made public by accident in #15200. Instead use of `bit_len` is encouraged.

* Renaming is also done in `big.js.v` to better fit the naming of the rest of the module; warranting deprecation of renamed functions.

* In the base arithmetic operations the first operand is also renamed to match their respective formal names (see [this discussion on math.stackexchange](https://math.stackexchange.com/questions/975541/what-are-the-formal-names-of-operands-and-results-for-basic-operations)).

* Documentation is adjusted in certain situations where the declared operand name does not match the documented name. Missing documentation for overridden arithmetic operators is also added for clarity.

### Notes

* `isqrt` must remain un-renamed, so as to not be mixed up with a future decimal precision return type function, which shall be named `sqrt`.
* `inc` and `dec` are common enough to be left alone in this PR.
* Similarly, `abs` and `neg` are common short forms of absolute values and negations, therefore they remain as they are.
* `bitwise_*` methods may warrant further discussion in this PR.
* big.Integer to string methods `binary_str`, `hex` and `radix_str` should be discussed for a general scheme, such as `bin_str`, `hex_str` and `radix_str` being longer to be visually better separated from the predetermined bases. 

### <samp>🤖 Generated by Copilot at 075a6a1</samp>

This pull request renames several functions and parameters in the `math/big` module to improve clarity, consistency, and readability. It also adds deprecated annotations and wrapper functions for the old names to ensure backward compatibility. The changes affect the files `big_test.v`, `big.js.v`, `division_array_ops.v`, `exponentiation.v`, `integer.v`, `special_array_ops.v`, and their corresponding test files.

### <samp>🤖 Generated by Copilot at 075a6a1</samp>

*  Rename `lshift` and `rshift` functions to `left_shift` and `right_shift` for clarity and consistency with `Integer` methods ([link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-1a2421de75c404a48cc287a36b69e158cc54faa177f66be4ac465cd74165877eL392-R392),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-1a2421de75c404a48cc287a36b69e158cc54faa177f66be4ac465cd74165877eL400-R400),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-1a2421de75c404a48cc287a36b69e158cc54faa177f66be4ac465cd74165877eL409-R409),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-1a2421de75c404a48cc287a36b69e158cc54faa177f66be4ac465cd74165877eL438-R438),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-1a2421de75c404a48cc287a36b69e158cc54faa177f66be4ac465cd74165877eL642-R650),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-1a2421de75c404a48cc287a36b69e158cc54faa177f66be4ac465cd74165877eL696-R696),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-1a2421de75c404a48cc287a36b69e158cc54faa177f66be4ac465cd74165877eL735-R735),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-6943113b1c1fef6bdff4317a54f3fe8b6184f8faf36951316ab5cd3e5eda3848L161-R200),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-d1f03a999870fd344be9bd8b3b1a5e447b1b32a687c955562162f4ab8bdd5df2L5-R33),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-54f3a52b943ce8674a334b7d1fd2bc7093ac37b0c2e96d2dfc5439da0b6d6907L32-R33),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-54f3a52b943ce8674a334b7d1fd2bc7093ac37b0c2e96d2dfc5439da0b6d6907L167-R167),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-54f3a52b943ce8674a334b7d1fd2bc7093ac37b0c2e96d2dfc5439da0b6d6907L324-R324),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-03d80aeafad3ed636bb8e535115d3d1e47ecba70dd3ea483c62a79f0cb2e1339L612-R619),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-03d80aeafad3ed636bb8e535115d3d1e47ecba70dd3ea483c62a79f0cb2e1339L679-R693),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-03d80aeafad3ed636bb8e535115d3d1e47ecba70dd3ea483c62a79f0cb2e1339L703-R723),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-03d80aeafad3ed636bb8e535115d3d1e47ecba70dd3ea483c62a79f0cb2e1339L922-R943),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-03d80aeafad3ed636bb8e535115d3d1e47ecba70dd3ea483c62a79f0cb2e1339L971-R990),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-03d80aeafad3ed636bb8e535115d3d1e47ecba70dd3ea483c62a79f0cb2e1339L1029-R1048),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-03d80aeafad3ed636bb8e535115d3d1e47ecba70dd3ea483c62a79f0cb2e1339L1068-R1087),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-0010dc8c24e1c6f4472542e9d3789895ab0a03ba518c0b065b322c64d5c1c9e3L30-R34),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-0010dc8c24e1c6f4472542e9d3789895ab0a03ba518c0b065b322c64d5c1c9e3L42-R47),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-0010dc8c24e1c6f4472542e9d3789895ab0a03ba518c0b065b322c64d5c1c9e3L144-R147),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-0010dc8c24e1c6f4472542e9d3789895ab0a03ba518c0b065b322c64d5c1c9e3L227-R236),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-0010dc8c24e1c6f4472542e9d3789895ab0a03ba518c0b065b322c64d5c1c9e3L241-R243),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-0010dc8c24e1c6f4472542e9d3789895ab0a03ba518c0b065b322c64d5c1c9e3L258-R260),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-0010dc8c24e1c6f4472542e9d3789895ab0a03ba518c0b065b322c64d5c1c9e3L274-R276),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-0b06ffb4a948aeb94a57f533cb6da19bd8cf7b110629e827d8ba0d5ae6bb10afL27-R29))
*  Rename `divmod` function to `div_mod` to follow snake_case convention and be consistent with `Integer` method of the same name ([link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-6943113b1c1fef6bdff4317a54f3fe8b6184f8faf36951316ab5cd3e5eda3848L91-R91),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-6943113b1c1fef6bdff4317a54f3fe8b6184f8faf36951316ab5cd3e5eda3848R100-R104))
*  Rename `b_and`, `b_or`, and `b_xor` functions to `bitwise_and`, `bitwise_or`, and `bitwise_xor` for descriptiveness and consistency with `Integer` methods of the same names ([link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-6943113b1c1fef6bdff4317a54f3fe8b6184f8faf36951316ab5cd3e5eda3848L140-R160),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-6943113b1c1fef6bdff4317a54f3fe8b6184f8faf36951316ab5cd3e5eda3848L147-R167),[link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-6943113b1c1fef6bdff4317a54f3fe8b6184f8faf36951316ab5cd3e5eda3848L154-R174))
*  Rename `fact` function to `factorial_int` for descriptiveness and consistency with `factorial` function that takes a `Number` argument ([link](https://github.com/vlang/v/pull/18890/files?diff=unified&w=0#diff-6943113b1c1fef6bdff4317a54f3fe8b6184f8faf36951316ab5cd3e5eda3848L196-R231))

### CODE REVIEW

**Comment by JalonSolov** [comment]
Most builtin types support a `.hex()` method, which returns a string with the hex representation of the value.  It's suggest just using `hex` instead of `hex_str` to match.

In the same vein, the other `_str()` methods need to be examined.

**Comment by phoreverpheebs** [comment]
Oh okay, I only knew about `.str()`. So it's just a matter of seeing how we can change the rest of the str functions to work best with the builtin compliant ones. I'm assuming `.bin()` wouldn't clash with anything? But then again it could become a problem in the future or with how intuitive it is to understand what it does.

**Comment by JalonSolov** [comment]
The builtin types don't have a `bin()` method...
```
error: unknown method or field: `int literal.bin`.
3 possibilities: `hex`, `hex_full`, `str`.
    5 | import math
    6 | 
    7 | println(5.bin())
      |           ~~~~~
```
So... as long as the name makes sense, it should be fine.

Bytes do have an extra method... `ascii_str()`, which is different from `str()`.  So `bin_str()` might make some sense... not sure on that one.

**Comment by phoreverpheebs** [comment]
`bin_str` sounds alright. also i'll fix the identifier errors when i'm at my computer

**Comment by phoreverpheebs** [comment]
@hungrybluedev thoughts on `bin_str` deprecating `binary_str`?

**Comment by hungrybluedev** [comment]
> @hungrybluedev thoughts on `bin_str` deprecating `binary_str`?

Seems fine as long as we include the full word “binary” in the documentation somewhere. People should be able to find it through page search.

**Pull request merged**
