### PR TITLE
Fix #4037 - Do not use unsafe sprintf/vsprintf functions

### LINKED ISSUE #4037: Dont use vsprintf/sprintf
**V version:** V 0.1.25 66adf7a
**OS:** OpenBSD

**What did you do?**
gmake

**What did you expect to see?**

normal build output
 
**What did you see instead?**

Screenshot 2020-03-16 at 11 30 01

```
$ git grep vsprintf
Binary file thirdparty/glfw/msvc/glfw3.lib matches
vlib/builtin/builtin.v:fn C.vsprintf() int
vlib/builtin/builtin.v:        C.vsprintf(charptr(buf), fmt, argptr)
vlib/compiler/main.v:   vsprintf((char *)buf, fmt, argptr);
vlib/compiler/main.v:   vsprintf((char *)g_str_buf, fmt, argptr);
```

```
$ git grep sprintf| grep -v vsprintf
Binary file examples/hot_reload/glfw3.dll matches
thirdparty/bignum/bn.c:    sprintf(&str[i], SPRINTF_FORMAT_STR, n->array[j]);
thirdparty/bignum/bn.h:  /* sprintf format string */
thirdparty/cJSON/cJSON.c:    sprintf(version, "%i.%i.%i", CJSON_VERSION_MAJOR, CJSON_VERSION_MINOR, CJSON_VERSION_PATCH);
thirdparty/cJSON/cJSON.c:        length = sprintf((char*)number_buffer, "null");
thirdparty/cJSON/cJSON.c:        length = sprintf((char*)number_buffer, "%1.15g", d);
thirdparty/cJSON/cJSON.c:            length = sprintf((char*)number_buffer, "%1.17g", d);
thirdparty/cJSON/cJSON.c:    /* sprintf failed or buffer overrun occurred */
thirdparty/cJSON/cJSON.c:                    sprintf((char*)output_pointer, "u%04x", *input_pointer);
Binary file thirdparty/glfw/glfw3.dll matches
Binary file thirdparty/glfw/msvc/glfw3.lib matches
thirdparty/vschannel/vschannel.c:	int res = wsprintf(service_name, L"%d", port_number);
thirdparty/vschannel/vschannel.c:	sprintf(pbMessage,  req);
vlib/builtin/cfns.v:fn C.sprintf(a ...voidptr) int
vlib/builtin/int.v:	C.sprintf((buf), '%p', ptr)
vlib/builtin/int.v:	count := C.sprintf((hex), '0x%x', n)
vlib/compiler/live.v:	sprintf(cpath,"./%s", path);
vlib/compiler/live.v:	sprintf(cpath, "./%s", path);
vlib/compiler/live.v:			sprintf(new_so_base, ".tmp.%d.${file_base}", _live_reloads);
vlib/compiler/live.v:			sprintf(new_so_name, "%s.dll", new_so_base);
vlib/compiler/live.v:			sprintf(new_so_name, "%s.so", new_so_base);
vlib/compiler/live.v:			sprintf(compile_cmd, "$vexe $msvc -o %s -solive -shared $file", new_so_base);
vlib/compiler/string_expression.v:					p.error('unhandled sprintf format "$typ" ')
vlib/compiler/string_expression.v:		// Otherwise do len counting + allocation + sprintf
vlib/strconv/ftoa/f32_f64_to_string_test.v:	"1.23e+302", // this test is failed from C sprintf!!
vlib/time/parse.v:	count := C.sprintf(charptr(tmstr), '%s-%02d-%s %s'.str, fields[3].str, mm,
```

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks. I'll merge this after making sure -live examples work after this change.

They are not tested and are broken right now unfortunately.

**Comment by radare** [comment]
Thanks

**Comment by medvednikov** [comment]
-live has been fixed, good to merge.

Can you please resolve the conflict?

**Comment by radare** [comment]
rebased

**Comment by radare** [comment]
i have rebased the PR, fixed the usage of fprintf as well as using PATH_MAX . but on  mac v -live bounce.v just exits with rc=0, so it doesnt s eems to work for me

**Comment by medvednikov** [comment]
bounce.v works for me on master

**Comment by medvednikov** [comment]
So it must be this PR. @spytheman can you please have a look?

**Comment by spytheman** [comment]
> So it must be this PR. @spytheman can you please have a look?

Of course, I will.

**Comment by spytheman** [comment]
Rebased over current master.

**Comment by medvednikov** [comment]
msvc:
```
bounce.exe.tmp.c
C:\Users\RUNNER~1\AppData\Local\Temp\v\bounce.exe.tmp.c(10732): error C2065: 'PATH_MAX': undeclared identifier
```

**Comment by radare** [comment]
```
$ v -live examples/hot_reload/bounce.v
warning: vlib/glfw/glfw.v:158:3: `scale` is declared as mutable, but it was never changed
warning: vlib/glfw/glfw.v:262:3: `scale` is declared as mutable, but it was never changed
warning: vlib/glfw/glfw.v:158:3: `scale` is declared as mutable, but it was never changed
warning: vlib/glfw/glfw.v:262:3: `scale` is declared as mutable, but it was never changed
$
```

that's all i get... but it seems like it's just a cmdline error because it works fine if i do this:

```
$ v -live run examples/hot_reload/bounce.v
```

so it is unrelated to my PR :) it was also failing in master. just tested this and my pr is not breaking -live either

**Comment by radare** [comment]
No pathmax on windows but my code should define it if not set

**Comment by spytheman** [comment]
> No pathmax on windows but my code should define it if not set

Your code: 
```c
#define _POSIX_C_SOURCE 1
#include <limits.h>
#ifndef PATH_MAX
#define PATH_MAX 1024
#endif
```
... is defined only on the `if v.pref.os != .windows {` branch. 
I added also this on the windows else branch:
```c
#ifndef PATH_MAX
#define PATH_MAX 1024
#endif
```

**Comment by spytheman** [comment]
Rebased over current master (again).

**Comment by medvednikov** [comment]
Thanks @spytheman

**Comment by radare** [comment]
Thank you!

**Comment by radare** [comment]
Pathmax is not available on hurd either. And ideally it should use the heap to avoid issues with small stacks and such

**Comment by esquerbatua** [comment]
@radare this was fixed? can be closed?

**Pull request merged**
