### PR TITLE
websocket: use vlibs instead of submodules of ws 

### PR DESCRIPTION
**Pull request by esquerbatua**
Removed logger submodule, replaced with log.
Moved utf8 things to encoder.utf8 **(maybe this it's incorrect)**
Refactor client, need to make tests in other PR

### CODE REVIEW

**Comment by spytheman** [comment]
What is the goal of this PR, and why does it modify vlib/encoding/utf8/ too?

**Comment by spytheman** [comment]
Can you do it in several smaller PRs, each with smaller scopes, that are easier to review and understand?

**Comment by esquerbatua** [comment]
> Can you do it in several smaller PRs, each with smaller scopes, that are easier to review and understand?

I'll do.

The main purpose was to remove the logger submodule and use the v module log.
Move the utf8 utils to the encoder.utf8
And make and runnable example connecting and obtaining response of the ws connection.

Sorry, my English is not very good

**Comment by JalonSolov** [comment]
Just making those into 3 separate PRs will help reduce the things to examine in each.

**Pull request closed without merging**
