### PR TITLE
Rollback to old interpolation (Step 1)

### PR DESCRIPTION
**Pull request by shove70**
1. Rollback PR#16308
2. Rollback PR#16259

### CODE REVIEW

**Comment by medvednikov** [comment]
Great work, thanks!

**Comment by Wertzui123** [comment]
Why?

**Comment by shove70** [comment]
> Why?

Considering the complexity of the implementation of relevant tools such as syntax highlighting and user experience, after discussion, it was decided to retain only the $interpolation.

**Comment by Wertzui123** [comment]
Ah, ok, thanks for the answer.

**Comment by ylluminate** [comment]
It may be worth noting the apparent discussion that led to this may be found in Discord (unsure if anything occurred elsewhere) around this point:

* https://discord.com/channels/592103645835821068/592320321995014154/1037609391211425863

**Pull request merged**
