### PR TITLE
v.util: improve `color_compare_files`

### PR DESCRIPTION
**Pull request by ttytm**

### CODE REVIEW

**Review by spytheman — APPROVED** [review]

**Comment by spytheman** [comment]
I've reverted the changes here, since they break the ability to customize the diff command and options by setting VDIFF_TOOL and VDIFF_OPTIONS.

**Comment by ttytm** [comment]
Might it be that it would work with: https://github.com/vlang/v/pull/21242?

**Comment by spytheman** [comment]
No, I've tested it.
The problem is the `os.find_abs_path_of_executable(diff_cmd) or {` check, which makes an early return, when the passed diff_cmd is not just a name, but something like `code -d`, composed from VDIFF_TOOL and VDIFF_OPTIONS .

**Comment by spytheman** [comment]
I should have been more thorough when reviewing it yesterday, and just not merge it in the first place.

**Comment by ttytm** [comment]
Good point. But easily fixed with keeping the check.

**Pull request merged**
