### PR TITLE
msvc: check exit code

### PR DESCRIPTION
**Pull request by vitalyster**
Related to #1740

### CODE REVIEW

**Comment by medvednikov** [comment]
`if (res.exit_code != 0) {` is going to be a syntax error soon, please remove `()`

**Comment by vitalyster** [comment]
please update v_win.c

**Comment by medvednikov** [comment]
v_win.c generation is broken right now, trying to fix it.

**Comment by vitalyster** [comment]
it is broken with msvc, I think v_win.c from gcc should be ok

**Comment by medvednikov** [comment]
no, I'm generating it on my mac, and it's an unrelated issue :)

**Pull request merged**
