### PR TITLE
checker: have stricter checks for `.clone()` requirement, disallow empty maps

### LINKED ISSUE #10011: Array append sometimes segfaults
**V version:** V 0.2.2 99a2fd7
**OS:** Debian GNU/Linux 9.13 (stretch) x86_64

**What did you do?**

```v
$ cat 01_05_MergeSort-vbug2-min.v
fn main() {
	println(fake_sort([4, 5, 6]))
}

fn fake_sort(nums []int) []int {
	dump(nums)
	if nums.len <= 1 {
		return nums
	}

	mid := nums.len / 2
	left := nums[..mid]
	right := nums[mid..]
	mut sorted := fake_sort(left)
	println('About to merge right == $right')
	sorted_right := fake_sort(right)
	println('Appending $sorted << $sorted_right (this blows up)')
	sorted << sorted_right
	println('Successfully appended (never reached)')
	return sorted
}

$ v run 01_05_MergeSort-vbug2-min.v
```

**What did you expect to see?**

A bunch of logging followed by

```v
[4, 5, 6]
```
 
**What did you see instead?**

A bunch of logging followed by a segfault:

```
$ v run 01_05_MergeSort-vbug2-min.v
[01_05_MergeSort-vbug2-min.v:6] nums: [4, 5, 6]
[01_05_MergeSort-vbug2-min.v:6] nums: [4]
About to merge right == [5, 6]
[01_05_MergeSort-vbug2-min.v:6] nums: [5, 6]
[01_05_MergeSort-vbug2-min.v:6] nums: [5]
About to merge right == [6]
[01_05_MergeSort-vbug2-min.v:6] nums: [6]
Appending [5] << [6] (this blows up)
*** Error in `/home/user/django_projects/algorithms/01_05_MergeSort-vbug2-min': realloc(): invalid pointer: 0x0000000001ff0474 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x788f32b30bfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x788f32b36fc6]
/lib/x86_64-linux-gnu/libc.so.6(realloc+0x219)[0x788f32b3b7d9]
/home/user/django_projects/algorithms/01_05_MergeSort-vbug2-min[0x416ad8]
======= Memory map: ========
00400000-0046d000 r-xp 00000000 ca:10 1528807                            /home/user/django_projects/algorithms/01_05_MergeSort-vbug2-min
0066c000-0066f000 rwxp 0006c000 ca:10 1528807                            /home/user/django_projects/algorithms/01_05_MergeSort-vbug2-min
01fec000-0200d000 rwxp 00000000 00:00 0                                  [heap]
788f2c000000-788f2c021000 rwxp 00000000 00:00 0 
788f2c021000-788f30000000 ---p 00000000 00:00 0 
788f32488000-788f3249e000 r-xp 00000000 ca:03 261684                     /lib/x86_64-linux-gnu/libgcc_s.so.1
788f3249e000-788f3269d000 ---p 00016000 ca:03 261684                     /lib/x86_64-linux-gnu/libgcc_s.so.1
788f3269d000-788f3269e000 r-xp 00015000 ca:03 261684                     /lib/x86_64-linux-gnu/libgcc_s.so.1
788f3269e000-788f3269f000 rwxp 00016000 ca:03 261684                     /lib/x86_64-linux-gnu/libgcc_s.so.1
788f3269f000-788f326a2000 r-xp 00000000 ca:03 290988                     /lib/x86_64-linux-gnu/libdl-2.24.so
788f326a2000-788f328a1000 ---p 00003000 ca:03 290988                     /lib/x86_64-linux-gnu/libdl-2.24.so
788f328a1000-788f328a2000 r-xp 00002000 ca:03 290988                     /lib/x86_64-linux-gnu/libdl-2.24.so
788f328a2000-788f328a3000 rwxp 00003000 ca:03 290988                     /lib/x86_64-linux-gnu/libdl-2.24.so
788f328a3000-788f328bb000 r-xp 00000000 ca:03 291000                     /lib/x86_64-linux-gnu/libpthread-2.24.so
788f328bb000-788f32aba000 ---p 00018000 ca:03 291000                     /lib/x86_64-linux-gnu/libpthread-2.24.so
788f32aba000-788f32abb000 r-xp 00017000 ca:03 291000                     /lib/x86_64-linux-gnu/libpthread-2.24.so
788f32abb000-788f32abc000 rwxp 00018000 ca:03 291000                     /lib/x86_64-linux-gnu/libpthread-2.24.so
788f32abc000-788f32ac0000 rwxp 00000000 00:00 0 
788f32ac0000-788f32c55000 r-xp 00000000 ca:03 290985                     /lib/x86_64-linux-gnu/libc-2.24.so
788f32c55000-788f32e55000 ---p 00195000 ca:03 290985                     /lib/x86_64-linux-gnu/libc-2.24.so
788f32e55000-788f32e59000 r-xp 00195000 ca:03 290985                     /lib/x86_64-linux-gnu/libc-2.24.so
788f32e59000-788f32e5b000 rwxp 00199000 ca:03 290985                     /lib/x86_64-linux-gnu/libc-2.24.so
788f32e5b000-788f32e5f000 rwxp 00000000 00:00 0 
788f32e5f000-788f32f62000 r-xp 00000000 ca:03 290989                     /lib/x86_64-linux-gnu/libm-2.24.so
788f32f62000-788f33161000 ---p 00103000 ca:03 290989                     /lib/x86_64-linux-gnu/libm-2.24.so
788f33161000-788f33162000 r-xp 00102000 ca:03 290989                     /lib/x86_64-linux-gnu/libm-2.24.so
788f33162000-788f33163000 rwxp 00103000 ca:03 290989                     /lib/x86_64-linux-gnu/libm-2.24.so
788f33163000-788f33186000 r-xp 00000000 ca:03 290981                     /lib/x86_64-linux-gnu/ld-2.24.so
788f33369000-788f3336d000 rwxp 00000000 00:00 0 
788f33385000-788f33386000 rwxp 00000000 00:00 0 
788f33386000-788f33387000 r-xp 00023000 ca:03 290981                     /lib/x86_64-linux-gnu/ld-2.24.so
788f33387000-788f33388000 rwxp 00024000 ca:03 290981                     /lib/x86_64-linux-gnu/ld-2.24.so
788f33388000-788f33389000 rwxp 00000000 00:00 0 
7ffc6eebf000-7ffc6eee0000 rwxp 00000000 00:00 0                          [stack]
7ffc6ef80000-7ffc6ef83000 r--p 00000000 00:00 0                          [vvar]
7ffc6ef83000-7ffc6ef85000 r-xp 00000000 00:00 0                          [vdso]
788f32af2fff : at ???: RUNTIME ERROR: abort() called
788f32b36fc6 : by ???
3437343066663130 : by ???
0043d1a6 : at ???: RUNTIME ERROR: invalid memory access
0043cb29 : by ???
0043cdf3 : by ???
0043cfa7 : by ???
788f32af3060 : by ???
788f32b36fc6 : by ???
3437343066663130 : by ???
Segmentation fault
```

### LINKED ISSUE #10019: invalid empty map initialization syntax not detected causing panic
**V version:** 0.2.2 84f9789
**OS:** Ubuntu Focal 20.04

**What did you do?**
```v
pub fn main() {
	m := map{}
	for {
		m[0] = "asdf"
		break
	}
	println(m)
}
```

**What did you expect to see?**
```
test.v:2:10: error: invalid empty map initilization syntax, use e.g. map[string]int{} instead
    1 | pub fn main() {
    2 |     m := map{}
      |             ~~
    3 |     for {
    4 |         m[0] = "asdf"
```
 
**What did you see instead?**
```
V panic: get_final_type_symbol: invalid type (typ=0 idx=0). Compiler bug. This should never happen. Please report the bug using `v bug file.v`.
v hash: 84f9789
/tmp/v/v2.exe.18423137053851425142.tmp.c:13545: at v_panic: Backtrace
/tmp/v/v2.exe.18423137053851425142.tmp.c:34504: by v__ast__default_table_panic_handler
/tmp/v/v2.exe.18423137053851425142.tmp.c:34510: by v__ast__Table_panic
/tmp/v/v2.exe.18423137053851425142.tmp.c:35279: by v__ast__Table_get_final_type_symbol
/tmp/v/v2.exe.18423137053851425142.tmp.c:17353: by v__checker__Checker_index_expr
/tmp/v/v2.exe.18423137053851425142.tmp.c:14586: by v__checker__Checker_expr
/tmp/v/v2.exe.18423137053851425142.tmp.c:12641: by v__checker__Checker_assign_stmt
/tmp/v/v2.exe.18423137053851425142.tmp.c:13368: by v__checker__Checker_stmt
/tmp/v/v2.exe.18423137053851425142.tmp.c:13980: by v__checker__Checker_stmts
/tmp/v/v2.exe.18423137053851425142.tmp.c:13641: by v__checker__Checker_for_stmt
/tmp/v/v2.exe.18423137053851425142.tmp.c:13429: by v__checker__Checker_stmt
/tmp/v/v2.exe.18423137053851425142.tmp.c:13980: by v__checker__Checker_stmts
/tmp/v/v2.exe.18423137053851425142.tmp.c:18345: by v__checker__Checker_fn_decl
/tmp/v/v2.exe.18423137053851425142.tmp.c:13420: by v__checker__Checker_stmt
/tmp/v/v2.exe.18423137053851425142.tmp.c:8438: by v__checker__Checker_check
/tmp/v/v2.exe.18423137053851425142.tmp.c:8504: by v__checker__Checker_check_files
/tmp/v/v2.exe.18423137053851425142.tmp.c:19014: by v__builder__Builder_gen_c
/tmp/v/v2.exe.18423137053851425142.tmp.c:19036: by v__builder__Builder_build_c
/tmp/v/v2.exe.18423137053851425142.tmp.c:19073: by v__builder__Builder_compile_c
/tmp/v/v2.exe.18423137053851425142.tmp.c:20061: by v__builder__compile
/tmp/v/v2.exe.18423137053851425142.tmp.c:20802: by main__main
/tmp/v/v2.exe.18423137053851425142.tmp.c:21202: by main
```

**More info**
Changing the code as follows does appear to make the empty initialization detectable, so there must be a bug with detecting it when there is an inference to what the key and value types should be.
```v
pub fn main() {
	m := map{}
	for {
		// m[0] = "asdf"
		break
	}
	println(m)
}
```

### PR DESCRIPTION
**Pull request by crthpl**
Fixes #10019 
Fixes #10011
Depends On #10328

### CODE REVIEW

**Comment by yuyi98** [comment]
Personal advices: Array assignments should be Clone by default, If you need direct assignment, you can use unsafe to do that.

**Comment by medvednikov** [comment]
Build fails:

```
/tmp/v/v2.exe.8151136170925915032.tmp.c:18205: error: cannot convert 'extern extern struct array *' to 'struct array'

```

**Comment by crthpl** [comment]
> Personal advices: Array assignments should be Clone by default, If you need direct assignment, you can use unsafe to do that.

@yuyi98 I also support this, but Alex wants clone to be optimized first: https://github.com/vlang/v/issues/10011#issuecomment-842017426

**Comment by JalonSolov** [comment]
I'm confused by the "disallow empty maps" - what does that mean?  That you won't be allowed to clone an empty map?

If so... why not?

**Comment by crthpl** [comment]
> I'm confused by the "disallow empty maps" - what does that mean? That you won't be allowed to clone an empty map?
> 
> If so... why not?

@JalonSolov No, this PR just fixes 2 completely unrelated bugs. The empty map fix is that doing `map{}` causes an error, and becomes a void value, instead of becoming the 0 type and crashing the compiler.

**Comment by JalonSolov** [comment]
Gotcha.  So disallow _completely_ empty maps, meaning they don't even specify the key and value types.

**Comment by JalonSolov** [comment]
ping?

**Pull request closed without merging**
