### PR TITLE
compiler: let shift operators work with all types

### PR DESCRIPTION
**Pull request by avitkauskas**
With this PR right hand side operand of left and right shift operators (`<<` and `>>`) can be any integer type and different from the left hand side operand type. The result of operation is of the same type as the left hand side operand.

Now you no longer need to typecast every operand and result:
```v
a := u64(0)
// instead of this
a = u64(u64(1) << u64(10))
// you can write
a = u64(1) << 10
```

This PR does not yet cover the `<<=` and `>>=` operations.
Also, there are some issues with assignment of the bigger type as the result of shift operation to the smaller type variable. This issue exists now and is not fixed by this PR. Solutions should follow.

_Comment:_
I had to put the else clause in `check_types2()` when checking for `integer`
```v
if expected == 'integer' {
    if is_integer_type(got) {
        return true
    } else {
        p.error('expected type `$expected`, but got `$got`')
    }
}
```
because otherwise the check falls through to the interface check (ends with 'er') and _surprisingly_ it passes the check of `p.satisfies_interface(expected, got, throw)`.

### CODE REVIEW

**Comment by medvednikov** [comment]
This is great, thanks.

**Comment by avitkauskas** [comment]
Hm... Some tests are failing. Like:
```
vlib/hash/crc32/crc32.v:31:37: expected type `u32`, but got `int`
   29| 		for j := 0; j < 8; j++ {
   30| 			if crc&u32(1) == u32(1) {
   31| 				crc = u32((crc >> u32(1)) ^ poly)
             				                          ^
   32| 			} else {
   33| 				crc >>= u32(1)
)
```
Could it be complaining about `poly` here? Any thoughts @medvednikov ?

**Comment by avitkauskas** [comment]
Yes, I checked this. As before `<<` result was always `int` this worked, but now it requires casting for `poly`. I will correct this in a few hours. Strange that it compiled locally and all tests passed.

**Comment by avitkauskas** [comment]
Done. No CI errors. After the merge we can cleanup a lot of code removing unnecesary casting with shifts ;)

**Pull request merged**
