### PR TITLE
[WIP] fix time module outside utc

### PR DESCRIPTION
**Pull request by vitalyster**

### CODE REVIEW

**Comment by vitalyster** [comment]
Still broken

**Comment by medvednikov** [comment]
I have a feeling that winapi has to be used for this...

**Comment by vitalyster** [comment]
@medvednikov not sure if it is only Windows problem - https://github.com/vlang/v/issues/3373

**Comment by alexesprit** [comment]
Didn't test it on Linux, but works for me on Windows with timezone +3. Also tests are now passes (at least for me on Windows; see #3579 for details).

<details>
  <summary>Example from #3373 (Click to expand)</summary>

```v
module main

import time

fn main() {
    a := time.parse_iso('Thu, 12 Dec 2019 06:07:45 GMT')
    b := a.add_days(1)
    //
    println(a.format())
    println(b.format())
}
```
```
$ v run test.v
2019-12-12 06:07
2019-12-13 06:07
```
</details>


<details>
  <summary>time-fix.patch (Click to expand)</summary>

```diff
diff --git a/vlib/time/time.v b/vlib/time/time.v
index 3247414b..2688ab4b 100644
--- a/vlib/time/time.v
+++ b/vlib/time/time.v
@@ -252,7 +252,7 @@ pub fn (t &Time) calc_unix() int {
 		tm_mon: t.month - 1
 		tm_year: t.year - 1900
 	}
-	return C.mktime(&tt)
+	return make_unix_time(tt)
 }
 
 // TODO add(d time.Duration)
diff --git a/vlib/time/time_nix.v b/vlib/time/time_nix.v
index 9e3d182a..0747b562 100644
--- a/vlib/time/time_nix.v
+++ b/vlib/time/time_nix.v
@@ -21,9 +21,10 @@ pub fn convert_ctime(t tm) Time {
 		hour: t.tm_hour
 		minute: t.tm_min
 		second: t.tm_sec
-		unix: C.mktime(&t)
-	}.add_seconds(t.tm_gmtoff)
+		unix: make_unix_time(t)
+	}
 }
 
-
-
+fn make_unix_time(t tm) int {
+	return C.mktime(&t) + t.tm_gmtoff
+}
diff --git a/vlib/time/time_windows.v b/vlib/time/time_windows.v
index 443255df..56c405b8 100644
--- a/vlib/time/time_windows.v
+++ b/vlib/time/time_windows.v
@@ -10,7 +10,6 @@ struct C.tm {
 	tm_hour int
 	tm_min  int
 	tm_sec  int
-	//tm_gmtoff int // seconds
 }
 
 pub fn convert_ctime(t tm) Time {
@@ -21,7 +20,10 @@ pub fn convert_ctime(t tm) Time {
 		hour: t.tm_hour
 		minute: t.tm_min
 		second: t.tm_sec
-		unix: C.mktime(&t)
-	}//.add_seconds(t.tm_gmtoff)
+		unix: make_unix_time(t)
+	}
 }
 
+fn make_unix_time(t tm) int {
+	return C.mktime(&t) - C._timezone
+}
```
</details>

**Comment by medvednikov** [comment]
@alexesprit nice, can you push this to this branch?

**Comment by alexesprit** [comment]
@medvednikov sure, though I need to rebase the branch on top of master.

**Comment by alexesprit** [comment]
@medvednikov I also added missing `make_unix_time` call in `calc_unix` function. So I think it's ready to merge.

**Comment by vitalyster** [comment]
Works for me on Windows and Linux

**Pull request merged**
