### PR TITLE
Sarctiann help

### PR DESCRIPTION
**Pull request by Sarctiann**
This is just a small improvement to the output of `v help`
so that it looks for if the terminal has `less` or `more` (in that order) and depending on the height of the terminal it would use one of these **if there is one** or print the normal output

### CODE REVIEW

**Comment by Sarctiann** [comment]
Captura_20220721_005304

**Comment by Sarctiann** [comment]
I don't know why the mac os check was cancelled.
but even less understand why the ubuntu test fails

**Comment by JalonSolov** [comment]
Apparently test output has changed.  Here's what's failing:
```
 FAIL  [   7/1050]  1749.267 ms cmd/v/help/help_test.v
/__w/v/v/cmd/v/help/help_test.v:8: fn test_help
    assert res.output.starts_with('V is a tool for managing V source code.')
/__w/v/v/cmd/v/help/help_test.v:14: fn test_help_as_short_option
    assert res.output.starts_with('V is a tool for managing V source code.')
/__w/v/v/cmd/v/help/help_test.v:20: fn test_help_as_long_option
    assert res.output.starts_with('V is a tool for managing V source code.')
```

**Comment by Sarctiann** [comment]
yes I read that, but I can't replicate the issue. maybe **less** or **more** commands on the *ubuntu-docker-musl* image, give a diferent output :man_shrugging:

**Comment by spytheman** [comment]
I do not get it, why should V be concerned with paging at all?

That is something, that the user can decide manually if needed (just by appending `| less`), also most terminals do have very well functioning history/scroll features.

**Comment by Sarctiann** [comment]
OK, abort

**Pull request closed without merging**
