### PR TITLE
add another function to the Animal interface

### PR DESCRIPTION
**Pull request by smartiniOnGitHub**
Hi,
as requested by @medvednikov  I propose a simple PR with some changes in interface test; there is even a sample usage of the `typeof` that could be useful here, to get automatically struct name.

Tests passes.
Tell me if you need more info.

Bye

### CODE REVIEW

**Comment by smartiniOnGitHub** [comment]
Sorry a small question: 
in my tests I tried even to define the `str` function in both `Dog` and `Cat` implementations, but not in the interface; and add a test to print array content ... if you like this small addition, I could do it (could be useful, as another small example) ... tell me. Thanks. Bye

**Comment by medvednikov** [comment]
you can push the `str` method @smartiniOnGitHub

**Comment by smartiniOnGitHub** [comment]
@medvednikov sorry I just see, I can raise another PR for that, ok ?

**Comment by medvednikov** [comment]
Sure :)

**Pull request merged**
