### PR TITLE
simplify -path argument split

### PR DESCRIPTION
**Pull request by kevin70g**
simplify -path argument split

### CODE REVIEW

**Comment by spytheman** [comment]
This is a breaking change.
Supporting os.path_delimiter, has the benefit that then the path argument does not need quoting. 
If we reduce it to support just `|` it will:
1) need quoting
2) an error message, to tell users that already do use : or ; for separating paths in their scripts, that they need to use `|` instead.

@medvednikov what do you think?

**Comment by medvednikov** [comment]
Yeah I agree.

**Comment by kevin70g** [comment]
Yes, I got it. Users can use the os path_seperator with | together: 
v -path ***@***.******@***.***

It's great!




kevin70g

From: Delyan Angelov
Date: 2021-05-27 17:55
To: vlang/v
CC: kevin70g; Author
Subject: Re: [vlang/v] simplify -path argument split (#10206)
This is a breaking change.
Supporting os.path_delimiter, has the benefit that then the path argument does not need quoting.
If we reduce it to support just | it will:
need quoting 
an error message, to tell users that already do use : or ; for separating paths in their scripts, that they need to use | instead. 
@medvednikov what do you think?

**Comment by kevin70g** [comment]
I suggest to discard | and only use os.path_separator, it will be consistent with shell and not add any learn cost.




kevin70g

From: kevin70g
Date: 2021-05-28 07:23
To: vlang/v; vlang/v
CC: Author
Subject: Re: Re: [vlang/v] simplify -path argument split (#10206)
Yes, I got it. Users can use the os path_seperator with | together: 
v -path ***@***.******@***.***

It's great!




kevin70g

From: Delyan Angelov
Date: 2021-05-27 17:55
To: vlang/v
CC: kevin70g; Author
Subject: Re: [vlang/v] simplify -path argument split (#10206)
This is a breaking change.
Supporting os.path_delimiter, has the benefit that then the path argument does not need quoting.
If we reduce it to support just | it will:
need quoting 
an error message, to tell users that already do use : or ; for separating paths in their scripts, that they need to use | instead. 
@medvednikov what do you think?

**Comment by kevin70g** [comment]
I think again and the original way is perfect! The reasons are:
1) use | as separator to unify across different platforms;
2) If users use platform-specific path_separator, it is also handled correctly!

Really great! 




kevin70g

From: kevin70g
Date: 2021-05-28 07:28
To: vlang/v; vlang/v
CC: Author
Subject: Re: Re: [vlang/v] simplify -path argument split (#10206)
I suggest to discard | and only use os.path_separator, it will be consistent with shell and not add any learn cost.




kevin70g

From: kevin70g
Date: 2021-05-28 07:23
To: vlang/v; vlang/v
CC: Author
Subject: Re: Re: [vlang/v] simplify -path argument split (#10206)
Yes, I got it. Users can use the os path_seperator with | together: 
v -path ***@***.******@***.***

It's great!




kevin70g

From: Delyan Angelov
Date: 2021-05-27 17:55
To: vlang/v
CC: kevin70g; Author
Subject: Re: [vlang/v] simplify -path argument split (#10206)
This is a breaking change.
Supporting os.path_delimiter, has the benefit that then the path argument does not need quoting.
If we reduce it to support just | it will:
need quoting 
an error message, to tell users that already do use : or ; for separating paths in their scripts, that they need to use | instead. 
@medvednikov what do you think?

**Pull request closed without merging**
