### PR TITLE
vdoc: optimize generated pages

### PR DESCRIPTION
**Pull request by ttytm**
This PR makes the changes that remained on my list after having worked a lot with the vdoc pages.

1. Fixes the color value for the border indicator of the active item in the left sidebar:
   **Current** - missing
   Screenshot from 2023-08-19 20-30-15
   
   **Spell Corrected** - we could spell correct the current value to it's existing variable 
   ```
   - --menu-search-result-hover-background-color
   + --menu-search-result-background-hover-color
   ``` 
   But this wouldn't result in a nice style - with a light theme there would be no change for the active item with this color.
   Screenshot from 2023-08-19 20-32-36
   
   **Suggested** - opting for one of the more appropriate looking colors
   Screenshot from 2023-08-19 20-30-33

2. ~~Reverts inferring the readme for the src directory #19000:~~
   ~~I think I made a mistake suggesting to add this feature.~~
   
   ~~This is after I found that there are occasions when this is not desired. For those who want this behavior, it is much easier to write a small script to generate the docs that contains the readme section on top than it is for those who do not want this behavior to prevent it or to remove the readme section after the docs are generated.~~
   
   Reverting it makes things more explicit.
   
3. Improves keyboard navigation on the doc pages
   - Handles the focus when escaping the search box, so that the main content remains keyboard navigable
   - Improves navigation of search results.
     Uses `behavior: 'instant'` instead of `smooth` as smooth doesn't work when holding the key down and the smooth movement is rather disturbing when cycling larger amounts of search results.
     Using `block: 'nearest'` improves the scroll movement when navigating back up from a scrolled down position in the search results.

### <samp>🤖 Generated by Copilot at 0145f03</samp>

This pull request improves the vdoc theme and removes some obsolete features. It enhances the keyboard accessibility of the search feature in `doc.js`, changes the border color of the active menu item in `doc.css`, and removes the `v doc -readme -comments` command and its test case. It also fixes a bug in `vdoc.v` that caused an error when the path was not a valid module.

### <samp>🤖 Generated by Copilot at 0145f03</samp>

*  Remove support for `v doc -readme -comments` command and its test case ([link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-ec7a1448d658fed5b34ac707bba11f7a638677153a6a7b4f66cf19a98fa83339L55-L59))
*  Improve CSS style of active menu item in documentation sidebar ([link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-f749a7a4292b3edebb60063394b8d54a45ad85bf51d4862da0e10999834e990cL283-R283))
  - Removing unnecessary focus on main content element on page load ([link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-3fb25060e841bc44786d7d6ed02a91a4c6c44f16784bb57b6af7e7934f57eb0eL14-L15))
  - Declaring variable for main content element ([link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-3fb25060e841bc44786d7d6ed02a91a4c6c44f16784bb57b6af7e7934f57eb0eR169))
  - Changing scroll behavior and options for selected search result ([link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-3fb25060e841bc44786d7d6ed02a91a4c6c44f16784bb57b6af7e7934f57eb0eL193-R192))
  - Setting focus on main content element on enter key press ([link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-3fb25060e841bc44786d7d6ed02a91a4c6c44f16784bb57b6af7e7934f57eb0eR200))
  - Moving focus on main content element from `setupScrollSpy` to `setupSearchKeymaps` function ([link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-3fb25060e841bc44786d7d6ed02a91a4c6c44f16784bb57b6af7e7934f57eb0eR232-R233))
*  Simplify logic for finding readme file by module name or current directory and remove error-prone branch ([link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-03bd8fff4fb425549163bcbb5f6dba4874b83d5fd8b7993915e040975800d24cL235-L237))
*  Delete unused test files for `readme_in_project_root` scenario ([link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-498d6c4e8cd13f633280f94caf094a3f9420e80bb5948548111b9e070953bc78), [link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-b58591a71c1561f756b71e8199a61c9ae96764f83b451971f0cd5c4d4f053f2f), [link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-df39cbc2a064ee0876b221f4e55557d5c56dbf5bddc43cf923cdf01cc4c4ef90), [link](https://github.com/vlang/v/pull/19185/files?diff=unified&w=0#diff-5f8ea1b78feb5897a0319c173473c46eb3707fbb3bc5ea498d193c5b4e048b92))

### CODE REVIEW

**Comment by JalonSolov** [comment]
On `2.` - why?  I though the readme was always supposed to be included... otherwise you have to search every directory to see if one is there, instead of seeing it on modules.vlang.io

**Comment by ttytm** [comment]
> On `2.` - why? I thought the readme was always supposed to be included... otherwise you have to search every directory to see if one is there, instead of seeing it on modules.vlang.io

Hey @JalonSolov, thanks for looking into this. 

For example when generating a doc with `v doc -readme -m -f html`, it will generate an additional, dedicated README page. With the behavior added in #19000 another README on top of the src directories modules would be added - I'd say this is redundant. For projects with the application structure that I wanted to cover in the PR I see more use cases for `v doc -readme -m -f html` with just a dedicated README page than `v doc -m -f html` with just the README on top of the module page. Reverting it would require if a README on top of the module page is wanted that the README file is in the src directory when generating the doc.

So I'm thinking that the explicit behavior covers more cases and is right more often, not always. 

Maybe adding an additional option to toggle the behavior is even better. Let me know what you think. Any input is very welcome as always.

**Comment by JalonSolov** [comment]
I think we may be better off with an option to tell it _not_ to include the readme, or perhaps a more general `-exclude` type of option.

The way the module info is generated now gives the readme info on the module page itself, which is what everyone is used to seeing.  If that went away, and you had to add an extra option to get it back, that seems like more of a "breaking change" than not.

As for the `src` directory... <sigh>  A vote I lost.  I never saw the need for it, myself.  However, since it is there... the way it was always supposed to be handled was silently... as if the files/subdirs under it were in the root of the project.  The compiler would add the path when needed, but otherwise ignore it.

**Comment by ttytm** [comment]
> I think we may be better off with an option to tell it _not_ to include the readme, or perhaps a more general `-exclude` type of option.
> 
> The way the module info is generated now gives the readme info on the module page itself, which is what everyone is used to seeing. If that went away, and you had to add an extra option to get it back, that seems like more of a "breaking change" than not.
> 
> As for the `src` directory... A vote I lost. I never saw the need for it, myself. However, since it is there... the way it was always supposed to be handled was silently... as if the files/subdirs under it were in the root of the project. The compiler would add the path when needed, but otherwise ignore it.

Just to make sure we talk about the same thing: 
The change to include the README from one directory above when the project has a directory named `src/` that doesn't have a README file in it was added recently. 
Is what you referring to that most people are used to see a `my_module/README.md` structure? Where the README is used for `my_module`? This wasn't affected when adding the change it and would not be affected when reverting it.

**Comment by JalonSolov** [comment]
I am saying that if the only readme in the module is in the src subdir, it should be treated as if it was in the root of the module.  If there is a readme in the root, it should be added.  If there's one in both places, only the one in the root should be added.

**Comment by ttytm** [comment]
Okay, to satisfy all needs, a revert is not the right way. I'll update the PR tomorrow to exclude the revert change.
Then it could be solved this by either adding an exclude option as you suggest or that adding the `readme` flag prevents redundancy. I would look into this separately then.

**Comment by ttytm** [comment]
Not that bad reflecting on a change with the result that it was a right thing to integrate it. The revert was removed :+1:

**Review by spytheman — APPROVED** [review]

**Pull request merged**
