### PR TITLE
strings: use faster levenshtein distance algorithm

### PR DESCRIPTION
**Pull request by zeozeozeo**
This algorithm is about 2.8x faster compared to the old implementation (added @[direct_array_access], early array initialization and use a faster implementation of the 2 loops)

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by penguindark** [comment]
Good work!
Does it work for string longer then 32768 bytes?

**Comment by zeozeozeo** [comment]
> Good work! Does it work for string longer then 32768 bytes?

yes:

```v
import strings
import rand

fn main() {
	a := rand.string(100_000) + 'x'
	b := a + 'x'
	dist := strings.levenshtein_distance(a, b)
	println("dist: ${dist}")
	assert dist == 2
}
```

**Comment by penguindark** [comment]
my doubt is about this line: `mut row := []u16{len: a.len + 1, init: u16(index)}`
where the index list is of `u16` type, this mean that you can not compare more than 65536 bytes of distances.
If you need a confrontation wider than 2^16 it probably fail.

**Comment by zeozeozeo** [comment]
> my doubt is about this line: `mut row := []u16{len: a.len + 1, init: u16(index)}` where the index list is of `u16` type, this mean that you can not compare more than 65536 bytes of distances. If you need a confrontation wider than 2^16 it probably fail.

yeah, this is true. might want to change it to `int` instead of `u16`

**Comment by spytheman** [comment]
It was fixed in https://github.com/vlang/v/pull/20474 @sisyphus-ppcg .

**Pull request merged**
