### PR TITLE
test: fix windows test error

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix windows test error.

**Before**
```v
pub fn (g mut Gen) write_tests_main() {
	......
	g.writeln('int main() {')
```

**Change**
```v
pub fn (g mut Gen) write_tests_main() {
	......
	$if windows {
		g.writeln('int wmain() {')
	}
	$else {
		g.writeln('int main() {')
	}
```

We must use `wmain` instead of `main` in Windows platform.

### CODE REVIEW

**Comment by vitalyster** [comment]
We also need to use wWinMain for GUI apps to not have console window...

**Comment by yuyi98** [comment]
@vitalyster  Thanks, you're right.  This is not the final solution, the current entire sources has not been considered `wWinMain`.

**Comment by vitalyster** [comment]
Logic for wWinMain was present before Big Changes

**Comment by yuyi98** [comment]
I know the situation, can we solve the problem in steps?

**Comment by yuyi98** [comment]
Here's the code before the big change, It's not perfect.
```v
pub fn (v mut V) gen_main_start(add_os_args bool) {
	if v.pref.os == .windows {
		if 'glfw' in v.table.imports {
			// GUI application
			v.cgen.genln('int WINAPI wWinMain(HINSTANCE instance, HINSTANCE prev_instance, LPWSTR cmd_line, int show_cmd) { ')
			v.cgen.genln('    typedef LPWSTR*(WINAPI *cmd_line_to_argv)(LPCWSTR, int*);')
			v.cgen.genln('    HMODULE shell32_module = LoadLibrary(L"shell32.dll");')
			v.cgen.genln('    cmd_line_to_argv CommandLineToArgvW = (cmd_line_to_argv)GetProcAddress(shell32_module, "CommandLineToArgvW");')
			v.cgen.genln('    int argc;')
			v.cgen.genln('    wchar_t** argv = CommandLineToArgvW(cmd_line, &argc);')
		} else {
			// Console application
			v.cgen.genln('int wmain(int argc, wchar_t* argv[], wchar_t* envp[]) { ')
		}
	} else {
		v.cgen.genln('int main(int argc, char** argv) { ')
	}
        ......
```

**Comment by vitalyster** [comment]
`CommandLineToArgvW` require shell32/gdi32 import, it is not good for console app (delayed startup time to initialize GDI). But `CommandLineToArgvW` is the only way to get command line args in GUI app (because (w)WinMain does not have argv). So previous solution was to parse argv in console app and use CommandLineToArgvW in GUI app.

**Comment by alexesprit** [comment]
@vitalyster but is it ok to have `wmain` only for tests?

**Comment by vitalyster** [comment]
@alexesprit until we have no gui tests

**Pull request merged**
