### PR TITLE
vweb: fix parsing url error when querypath is '//'(fix #20476)

### LINKED ISSUE #20476: [vweb] Error parsing url with // appended
### Describe the bug

If a user tries to load a `vweb` webpage and the url ends with `//`, then the page fails to load.

This can have various consequences. For example [gitly](https://gitly.org//) shows a Cloudflare error currently.

My cloud-deployed server goes to 100% CPU.

Locally, I just get an error on the browser.

image
 

### Create simple web server project
$ `v new --web test`

### Run the server
$ `v run .`

### Visit the problematic path
Load  http://localhost:8082// on a web browser

### Expected Behavior

The webpage loads. It either redirects to home, displays a 404 error or something normal.

### Current Behavior

The webpage shows `The connection was reset` on Firefox and `This page isn’t working` on Chrome

The log shows

```
[vweb] tid: 005, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 000, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 006, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 001, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 002, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 004, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 003, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 005, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 003, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 000, error parsing path: net.urllib.parse: failed parsing url
[vweb] tid: 002, error parsing path: net.urllib.parse: failed parsing url
```

### Possible Solution

_No response_

### Additional Information/Context

Related to this `gitly` issue https://github.com/vlang/gitly/issues/253

### V version

V 0.4.4 4640627

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.4 aa28efc.4640627
OS: linux, Ubuntu 20.04.6 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz

getwd: /home/bill/test
vexe: /home/bill/Documents/opt/v/v
vexe mtime: 2024-01-10 21:20:23

vroot: OK, value: /home/bill/Documents/opt/v
VMODULES: OK, value: /home/bill/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.25.1
Git vroot status: weekly.2021.46-5307-g46406277
.git/config present: true

CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

### PR DESCRIPTION
**Pull request by shove70**
Close #20476

### CODE REVIEW

**Comment by spytheman** [comment]
Please also add a test, that fails on master, but works here. Without a test, it is likely that it will regress.

**Comment by shove70** [comment]
> Please also add an unit test, that fails on master, but works here. Without a test, it is likely that it will regress silently in the future.

Ok, done!    oooooops   👍

**Comment by spytheman** [comment]
Please modify `vlib/net/urllib/urllib_test.v` too. Doing it in vweb is nice too, since it is an end to end test, but a closer test will be faster to check, something like:
```v
assert net.urllib.parse('//')!.str() == '//'
```

**Comment by shove70** [comment]
> Please modify `vlib/net/urllib/urllib_test.v` too. Doing it in vweb is nice too, since it is an end to end test, but a closer _unit_ test will be faster to check/localize regression problems, something like:
> 
> ```v
> assert net.urllib.parse('//')!.str() == '//'
> ```

@spytheman 
Thanks for adding this!  ❤️ ❤️ ❤️ 

Last night after dinner came back unexpectedly did not notice there is a "urllib_test.v" file there, my fault, bad eyes, ha ha!

**Pull request merged**
