### PR TITLE
checker: check duplicated field and method (only for anon-fns yet)

### PR DESCRIPTION
**Pull request by danieldaeschle**
Fixes https://github.com/vlang/v/issues/10924

### CODE REVIEW

**Comment by danieldaeschle** [comment]
@medvednikov currenlty only for functions, more needs discussion because @spytheman has also some ideas.

**Comment by mcastorina** [comment]
I think this is a good start, great work!

I originally suggested all name collisions should be prohibited so it would be clear which attribute is being referenced. For example, passing a function as an argument, you may want to pass a method receiver.

```v
struct St {
    attr int
}
fn (st St) attr() {}

fn some_function(f fn()) { f() }

x := St{}
some_function(x.attr)
```

I'm not sure this is even valid, but it's something to consider if passing method receivers by value is something V wants to support.

**Comment by danieldaeschle** [comment]
I'm aware of this

**Comment by danieldaeschle** [comment]
I hope we can merge it as it is. Restrict more would result in a lot breaking changes. We have to prepare that.

**Pull request merged**
