### PR TITLE
Remove temporary map fields _keys, key_i

### PR DESCRIPTION
**Pull request by ntrel**

### CODE REVIEW

**Comment by ntrel** [comment]
Why am I getting:
> V panic: Import cycle detected.

**Comment by medvednikov** [comment]
Cycle detection uses maps, so I assume this breaks the maps somehow.

Does map_test.v pass?

**Comment by ntrel** [comment]
> Does map_test.v pass?

No that says import cycle detected too.

**Comment by medvednikov** [comment]
Thanks

**Pull request merged**
