### PR TITLE
os: add debugger_present() for linux

### PR DESCRIPTION
**Pull request by bstnbuck**
Updated version of: #10203
This PR implements os.debugger_present() for Linux 

The following I can not fix or provide
- [x] integrate the `ptrace.h` to the cross-compile linux package => see #9796 (comment)

### CODE REVIEW

**Comment by fantassin** [comment]
@bstnbuck 
This PR broke Solaris/SmartOS.

 make
make fresh_vc
make[1]: Entering directory '/root/v'
rm -rf ./vc
git clone --depth 1 --quiet --single-branch https://github.com/vlang/vc ./vc
make[1]: Leaving directory '/root/v'
cd ./vc && git clean -xf && git pull --quiet
make fresh_tcc
make[1]: Entering directory '/root/v'
rm -rf ./thirdparty/tcc
Pre-built TCC not available for thirdparty-unknown-i86pc at https://github.com/vlang/tccbin, will use the system compiler: cc
git clone --depth 1 --quiet --single-branch --branch thirdparty-unknown-unknown https://github.com/vlang/tccbin ./thirdparty/tcc
make[1]: Leaving directory '/root/v'
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread
./vc/v.c:1031:2: error: #error VERROR_MESSAGE Header file <sys/ptrace.h>, needed for module `os` was not found. Please install the corresponding development headers.
 1031 | #error VERROR_MESSAGE Header file <sys/ptrace.h>, needed for module `os` was not found. Please install the corresponding development headers.
      |  ^~~~~
make: *** [Makefile:91: all] Error 1

**Comment by bstnbuck** [comment]
@spytheman what should we do? Exclude functionality for `solaris` or add the header file to thirdparty?

**Comment by bstnbuck** [comment]
@fantassin thanks for reporting!
I found out that `sys/ptrace.h` is no longer available under solaris, nor its function. Unfortunately I can't find a solution for it at the moment. However, compilation should work under solaris, so I removed the debugger_present() functionality for solaris for now. Please check the installation again with this commit: https://github.com/bstnbuck/v/tree/d5179f7cb7937df7b19987aa0a2fde57d030162c 
Does the installation of V works now?

**Comment by bstnbuck** [comment]
Update: `ptrace()` seems to be available, but not with the `sys/ptrace.h` header. In your installation, can you (@fantassin) replace `sys/ptrace.h` in the file `vlib/os/os_nix.c.v` with the following piece of code and check if both compilation and os.debugger_present() function work? Unfortunately, I don't have Solaris. Thanks!

```v
$if !solaris{
	#include <sys/ptrace.h>
}
```

**Comment by fantassin** [comment]
@bstnbuck Please create a PR.

**Comment by bstnbuck** [comment]
> @bstnbuck Please create a PR.

@fantassin could you please check if it works now?

**Comment by fantassin** [comment]
```
[root@smartos ~]# git clone https://github.com/bstnbuck/v.git
Cloning into 'v'...
remote: Enumerating objects: 94712, done.
remote: Counting objects: 100% (1675/1675), done.
remote: Compressing objects: 100% (957/957), done.
remote: Total 94712 (delta 962), reused 1313 (delta 703), pack-reused 93037
Receiving objects: 100% (94712/94712), 38.18 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (67578/67578), done.
[root@smartos ~]# cd v
[root@smartos ~/v]# git checkout d5179f7cb7937df7b19987aa0a2fde57d030162c
Note: switching to 'd5179f7cb7937df7b19987aa0a2fde57d030162c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at d5179f7cb os: fix os.debugger_present() breaks v installation on solaris
[root@smartos ~/v]# make
make fresh_vc
make[1]: Entering directory '/root/v'
rm -rf ./vc
git clone --depth 1 --quiet --single-branch https://github.com/vlang/vc ./vc
make[1]: Leaving directory '/root/v'
cd ./vc && git clean -xf && git pull --quiet
make fresh_tcc
make[1]: Entering directory '/root/v'
rm -rf ./thirdparty/tcc
Pre-built TCC not available for thirdparty-unknown-i86pc at https://github.com/vlang/tccbin, will use the system compiler: cc
git clone --depth 1 --quiet --single-branch --branch thirdparty-unknown-unknown https://github.com/vlang/tccbin ./thirdparty/tcc
make[1]: Leaving directory '/root/v'
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread
./vc/v.c:1072:2: error: #error VERROR_MESSAGE Header file <sys/ptrace.h>, needed for module `os` was not found. Please install the corresponding development headers.
 1072 | #error VERROR_MESSAGE Header file <sys/ptrace.h>, needed for module `os` was not found. Please install the corresponding development headers.
      |  ^~~~~
make: *** [Makefile:91: all] Error 1
[root@smartos ~/v]#
```

@bstnbuck Can you email me (fantassin@gmail.com) or message me on Discord so I can give you access to a SmartOS machine?

**Comment by bstnbuck** [comment]
This is very strange, with SmartOS being based on Solaris. My guess is that V thinks that SmartOS is not Solaris which causes the error above. What do you think @spytheman ?
I will test the behaviour on a SmartOS system the next few days.

**Comment by spytheman** [comment]
@bstnbuck  I think I have a fix for `$if os { #include ... }` but I need to run some more tests before I push it.

**Comment by spytheman** [comment]
should be ok now since https://github.com/vlang/v/commit/6313ed6a79ad357808fb413128cc8d32b215c95c

**Comment by fantassin** [comment]
I tried and I get a different error now:

```
[root@smartos ~]# git clone https://github.com/vlang/v
Cloning into 'v'...
remote: Enumerating objects: 95910, done.
remote: Counting objects: 100% (2107/2107), done.
remote: Compressing objects: 100% (1155/1155), done.
remote: Total 95910 (delta 1251), reused 1711 (delta 931), pack-reused 93803
Receiving objects: 100% (95910/95910), 39.33 MiB | 1.99 MiB/s, done.
Resolving deltas: 100% (68427/68427), done.
[root@smartos ~]# cd v
[root@smartos ~/v]# make
make fresh_vc
make[1]: Entering directory '/root/v'
rm -rf ./vc
git clone --depth 1 --quiet --single-branch https://github.com/vlang/vc ./vc
make[1]: Leaving directory '/root/v'
cd ./vc && git clean -xf && git pull --quiet
make fresh_tcc
make[1]: Entering directory '/root/v'
rm -rf ./thirdparty/tcc
Pre-built TCC not available for thirdparty-unknown-i86pc at https://github.com/vlang/tccbin, will use the system compiler: cc
git clone --depth 1 --quiet --single-branch --branch thirdparty-unknown-unknown https://github.com/vlang/tccbin ./thirdparty/tcc
make[1]: Leaving directory '/root/v'
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread
./v -o v2.exe  cmd/v
vlib/time/time_solaris.c.v:12:16: error: cannot use `&i64` as `&time.time_t` in argument 1 to `C.localtime_r`
   10 |     C.clock_gettime(C.CLOCK_REALTIME, &ts)
   11 |     loc_tm := C.tm{}
   12 |     C.localtime_r(&ts.tv_sec, &loc_tm)
      |                   ~~~~~~~~~~
   13 |     return convert_ctime(loc_tm, int(ts.tv_nsec / 1000))
   14 | }
make: *** [Makefile:92: all] Error 1

**Comment by spytheman** [comment]
@fantassin try again with latest V (https://github.com/vlang/v/commit/29f55bdf9b8ec85dfa9082df23bc74d5d96b3e91) - it should fix that other problem.

**Pull request merged**
