### PR TITLE
net: make `net.TcpSocket` public

### PR DESCRIPTION
**Pull request by Wertzui123**
See https://github.com/Wertzui123/TLSe/blob/main/sslconn.c.v#L70

### CODE REVIEW

**Comment by emily33901** [comment]
I feel like tcpsocket still shouldn't be made public, people shouldn't be using it. Maybe consider instead a function that creates a tcpsocket from a handle? Or a conn from a handle?

**Comment by Wertzui123** [comment]
> Maybe consider instead a function that creates a tcpsocket from a handle?

That sounds like a good alternative, yes.

But why shouldn't people use the struct?

**Comment by JalonSolov** [comment]
Because you _want_ people to get a socket by using lib functions, and you only want modifications done via methods, instead of people mucking about the the socket directly.

This allows some of the details to be "hidden" in the implementation, especially if there are cross-platform differences that need to be dealt with.

Otherwise people start complaining "well, I set this bit and everything blew up!" and finding out it's because that bit didn't do what was expected on Windows while it worked fine on Linux... details like that can be handled by the methods.

**Comment by Wertzui123** [comment]
That's right, but I don't really see the problem in making this particular struct public, as it has no fields and just embeds another (this time public) struct.

So, should I close this PR and open another one with a `from_handle` function?

**Comment by spytheman** [comment]
> That's right, but I don't really see the problem in making this particular struct public, as it has no fields and just embeds another (this time public) struct.
> 
> So, should I close this PR and open another one with a `from_handle` function?

Yes, please.

Personally, I am on the fence on the whole public/private debate, since the chance of changing that particular struct is very very low, given that it has not changed till now. Yet, it may make things more maintainable in the future in principle, if there is a constructor function, rather than the struct being public, even though making the struct pub is the smallest and most elegant change in the near term.

**Comment by JalonSolov** [comment]
It is the simplest change, but simple isn't always elegant/better.

**Comment by Wertzui123** [comment]
So, there is already a function that does this, but it changes the options of the socket (https://github.com/vlang/v/blob/master/vlib/net/tcp.v#L378). How should I name the new function then?

**Comment by emily33901** [comment]
> > That's right, but I don't really see the problem in making this particular struct public, as it has no fields and just embeds another (this time public) struct.
> > 
> > So, should I close this PR and open another one with a `from_handle` function?
> 
> Yes, please.
> 
> Personally, I am on the fence on the whole public/private debate, since the chance of changing that particular struct is very very low, given that it has not changed till now. Yet, it may make things more maintainable in the future in principle, if there is a constructor function, rather than the struct being public, even though making the struct pub is the smallest and most elegant change in the near term.

I feel the point of keeping it private is to make it super obvious that you should be using tcpconn and not tcpsocket

**Comment by Wertzui123** [comment]
I am, but a `net.TcpConn` requires a `net.TcpSocket`.

**Comment by emily33901** [comment]
> I am, but a `net.TcpConn` requires a `net.TcpSocket`.

My thought then is like in Rust maybe call it `from_os_handle`?

**Comment by Wertzui123** [comment]
Maybe we should rename the other function instead to something like `from_handle_setup` or something like that

**Pull request closed without merging**
