### PR TITLE
 checker: improve errors for interface method compatibility 

### PR DESCRIPTION
**Pull request by ntrel**
Split out from #8092.

Be more specific about why a struct method doesn't match an interface method.
Make Table.is_same_method return error message.

### CODE REVIEW

**Comment by ntrel** [comment]
Note: I tried to print the method signature as an additional error detail, but it didn't print, `add_error_detail` seems broken: 2775974

**Comment by spytheman** [comment]
`c.add_error_detail(x)` was designed to be used before the error, so that you can add several details, then call c.error or c.warn.
It buffers the arguments and joins them to the actual shorter warning/error later.
It would have worked, if you had another error later in the checker.

**Comment by spytheman** [comment]
I admit it is not very intuitive that you need to use it before, then the details will appear after the main text of the error... It was just added after there were already many c.warn/c.error calls 🤔

**Comment by ntrel** [comment]
@spytheman thanks for explaining, I'll make a follow up pull.

**Comment by ntrel** [comment]
> perhaps I should have documented it better.

@spytheman I added a comment in #8111.

**Pull request merged**
