### PR TITLE
parser: fix non-void optional fn missing return value (fix #5736)

### LINKED ISSUE #5736: Option result without return none
**V version:** 0.1.28
**OS:** Ubuntu 20.04

**What did you do?**
```v
fn foo(param bool) ?string {
	if param {
		return 'Hello World'
	}
}

fn main() {
	r := foo(false) or {
		'test'
	}
	println(r)
}
```

**What did you expect to see?**
either `'test'` or a V error that foo have to return something.
 
**What did you see instead?**
```
```
(nothing)

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix non-void optional fn missing return value (fix #5736).

- Fix non-void optional fn missing return value.
- Add test `test_option_auto_add_return_none()` in option_test.v.

```v
fn foo(param bool) ?string {
	if param {
		return 'Hello World'
	}
}

fn main() {
	r := foo(false) or {
		'test'
	}
	println(r)
}

D:\test\v\tt1>v run .
test
```

### CODE REVIEW

**Comment by spytheman** [comment]
I am not sure whether the parser is the best place to put such a fix. Would not the checker be better for it?
If we keep it in the parser, it will affect every other stage - vfmt, vdoc, vvet and so on, by introducing virtual nodes, indistinguishable from code typed by the user.

**Comment by yuyi98** [comment]
Ok, you're right, I'll try to change it.

**Comment by danieldaeschle** [comment]
i wonder if not a `return none` is required?

**Comment by danieldaeschle** [comment]
this seems more like a bug. not all branches are covered regarding returns.

**Comment by danieldaeschle** [comment]
this is modifying the ast which is not a good idea in my opinion. (the position doesn not exist in the real file).

**Comment by medvednikov** [comment]
yeah we might want to have an explicit `return none`

**Comment by danieldaeschle** [comment]
it was on my todo list to check returns more explicit. let's set this one on our to do list to revert when a better return check is ready.

**Pull request merged**
