### PR TITLE
cgen: fix interface type generation for generic struct

### LINKED ISSUE #22186: C error when implementing two interfaces, one of them generic
### Describe the bug

Code: https://play.vlang.io/p/8c844fb35a

```v
interface IA {
	a int
	fa()
}
interface IB[T] {
	a int
	b T
	fa()
}
struct Foo[T] implements IA, IB {
	a int
	b T
}
fn (foo Foo[T]) fa() {
	println(foo.b)
}

foo := Foo[u8]{ b: 16 }
foo.fa()
```

### Reproduction Steps

Run the code above

### Expected Behavior

No errors, or at least a V error

### Current Behavior

Output:

```
/tmp/v_60000/code.01J7BQJ4X1E5N9VQANX1JA2JPJ.tmp.c:2174: error: ',' expected (got "*")
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
Exited with error status 1
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### V version

V 0.4.7 6528efa

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.7 6528efa
OS: linux, Debian GNU/Linux 11 (bullseye) (VM)
Processor: 1 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz

getwd: /home/admin/playground
vexe: /home/admin/v/v
vexe mtime: 2024-09-09 15:25:27

vroot: OK, value: /home/admin/v
VMODULES: OK, value: .vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.30.2
Git vroot status: Error: fatal: detected dubious ownership in repository at '/home/admin/v'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v
.git/config present: true

CC version: cc (Debian 10.2.1-6) 10.2.1 20210110
thirdparty/tcc status: Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc
 Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc

```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

### PR DESCRIPTION
**Pull request by felipensp**
Fix #22186

### CODE REVIEW

**Comment by StunxFS** [comment]
I think `IB` should necessarily be `IB[T]`

**Comment by felipensp** [comment]
> I think `IB` should necessarily be `IB[T]`.
> 
> ```v
> struct Foo[T] implements IA, IB[T] { 
>          a int 
>          b T 
>  }
> ```

What do you think @medvednikov ? This can be threated in another PR though.

**Comment by medvednikov** [comment]
I agree, it should be `struct Foo[T] implements IA, IB[T] `

**Comment by felipensp** [comment]
> I agree, it should be `struct Foo[T] implements IA, IB[T] `

I've changed the implements_type to use TypeNode to save the token pos for checker error message.

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by spytheman** [comment]
Can I merge this now @felipensp , and then https://github.com/vlang/v/pull/22218 or ?

**Pull request merged**
