### PR TITLE
builtin/array.v: Wrap pointer addition with get_unsafe, set_unsafe functions

### PR DESCRIPTION
**Pull request by ntrel**
This follows on from #5581. This pull is part of the preparation for the next stage of disallowing pointer arithmetic for `InfixExpr` outside `unsafe {}`. I'm submitting this separately as the refactoring is independent of that change.

* Instead of pointer addition to find the address of an array element, use `get_unsafe(index)`.
* Instead of `memcpy` with pointer addition to set a single element, use `set_unsafe(index, val)`.

These functions also make it easier to read and understand the code too.

* Add `unsafe {}` blocks for pointer addition (my `InfixExpr` pull will require that).
* Add some `unsafe {}` blocks for calling functions marked `[unsafe_fn]`. I didn't do this consistently, but I kept these changes (from my WIP) as I think this should be required in future (I might work on that too later).

I think these changes may be covered by existing tests, please let me know of any exceptions and I can update the tests.

### CODE REVIEW

**Comment by medvednikov** [comment]
I'm concerned about the performance, since C compilers are weird about inlining, and simply don't do that, even when asked, even with -O2/3

**Comment by spytheman** [comment]
@ntrel can you do some benchmarks before/after this change, to see what will be the performance impact?
`v self`, `v -prod self` as well as `./v run examples/path_tracing.v` and `./v -prod run examples/path_tracing.v` can serve as good candidates for performance measurement.

**Comment by ntrel** [comment]
I have the Windows release of V 0.1.28.1 in `/c/v/v.exe`. I get an abort when running `examples/path_tracing.exe` on my machine (Windows 8, see gist for gcc version):
```
$ ./examples/path_tracing.exe
Unhandled Exception 0xC00000FD
print_backtrace_skipping_top_frames is not implemented
```
So I've done a quick benchmark for `examples/nbody.v` and `v self`:
https://gist.github.com/ntrel/0453f0b02c74f646da231b44b01447df

As you can see:
* For `nbody.exe` without `-prod`, it took 55s for stock V vs 1m34 with this pull, a lot slower.
* For `nbody.exe` with `-prod`, they're about the same (this pull is a bit quicker).
* For `v self`, it took 6.9s for stock V vs 5.2s with this pull, significantly better (surprising).
* For `v -prod self`, they're about the same (this pull is a bit quicker).

**Comment by ntrel** [comment]
> significantly better (surprising)

I reran the timing for `v self` and `v -prod self`, this time timing my branch first then the stock compiler (in case order made a difference):
https://gist.github.com/ntrel/0954d86eaf393972701c2af799065755

At first, the `-prod` build was slower, 29s v 25s. But I reran it (later in the gist) and it was about the same.
Without `-prod`, the timing was about the same.

**Comment by medvednikov** [comment]
> For v self, it took 6.9s for stock V vs 5.2s with this pull, significantly better (surprising).

For me second run of `v self` is always faster, probably CPU cache.

**Comment by medvednikov** [comment]
We can make V smarter and actually handle `[inline]` without relying on C.

**Comment by ntrel** [comment]
I've now re-inlined the get and set functions but only where the caller function is performing a single index operation or a single index assign - these are the critical places for performance. The timing for `examples/nbody.v` is now about the same, even without `-prod`:
```
Czastka Family@family-desktop MINGW32 /c/git/v (arr-get)
$ ./v.exe examples/nbody.v && time ./examples/nbody.exe
-0.169075164
-0.169059907

real    0m55.729s
user    0m0.015s
sys     0m0.000s

Czastka Family@family-desktop MINGW32 /c/git/v (arr-get)
$ /c/v/v.exe examples/nbody.v && time ./examples/nbody.exe
-0.169075164
-0.169059907

real    0m55.930s
user    0m0.000s
sys     0m0.015s
```

**Comment by medvednikov** [comment]
This can be closed as I understand?

**Pull request closed without merging**
