### PR TITLE
Fix typo and remove unnecessary spaces

### PR DESCRIPTION
**Pull request by paveg**
I found typo.
Please merge if possible.

### CODE REVIEW

**Comment by elimisteve** [comment]
:+1: LGTM

**Review by AurelienFT — APPROVED** [review]
I approve

**Comment by paveg** [comment]
@AurelienFT Please check it, so I committed one more.

**Review by AurelienFT — APPROVED** [review]
I approve !

**Review by Kriyszig — APPROVED** [review]
LGTM :octocat:
Thank you

**Comment by medvednikov** [comment]
Reviewed the historical README-only diff (CI ignored). The typo and whitespace fixes are straightforward, and I don't see a content or correctness issue.

**Pull request merged**
