### PR TITLE
expression: set floats as f64 by default

### PR DESCRIPTION
**Pull request by SleepyRoy**
After this PR it's possible to write, e.g. `a := 1e100`.

### CODE REVIEW

**Comment by spytheman** [comment]
Can you add tests for this please?

The new compiler is progressing very fast, and if there are no tests for added features in the old compiler (which will get deleted after the new one is stable enough), there will be regressions for fixes/features that are added between now and then.

Adding tests will prevent that - the new compiler would have to pass the test suite.

**Comment by SleepyRoy** [comment]
@spytheman Thanks for explanation. Tests have been added.

**Comment by medvednikov** [comment]
```examples/sokol_examples/fonts.v:96:35: cannot use type `f64*` as type `f32*` in first argument to `vert_metrics()`
   94| 	ascender := 0.0
   95| 	descender := 0.0
   96| 	state.fons.vert_metrics(&ascender, &descender, &lh)
             	                           ^
   97| 	dx = sx
   98| 	dy += lh
)```

**Comment by SleepyRoy** [comment]
@medvednikov Thanks for reporting this. I just had a look. The point is how we want to design the type declaration system of numbers in V. Currently the logic is, floats are always f32 (no matter how large it is), and integers are int or u64 (and threshold is 2^32 rather than 2^31). So for now we have
a := 4000000000
typeof(a) // 'int' 
b := 1e100
typeof(b) // 'f32'
So, is this a desired system? If not, what do we want the system to be?

**Comment by medvednikov** [comment]
The default is going to be f64.

Unfortunately using that breaks tests and examples (like Tetris).

**Comment by SleepyRoy** [comment]
@medvednikov Done. Now floats are f64 instead of f32 by default.

**Comment by medvednikov** [comment]
Amazing job @SleepyRoy 

Thanks a lot! That saved me a lot of time.

**Pull request merged**
