### PR TITLE
os api: join => join_path

### PR DESCRIPTION
**Pull request by yuyi98**
This PR change `os.join` to `os.path_join` in `os` api.

The meaning of `os.join` is not clear enough, `os.path_join` is more appropriate.

### CODE REVIEW

**Comment by joe-conigliaro** [comment]
or join_path either is more clear for sure

**Comment by spytheman** [comment]
The failing tests here may be fixed after #3965 is merged. I think they are not related to the changes of this PR.

**Comment by dhonx** [comment]
`filepath.join()`

**Comment by medvednikov** [comment]
I'd call it `join_path`

**Pull request merged**
