### PR TITLE
tmpl: move to v/parser

### PR DESCRIPTION
**Pull request by Terisback**

### CODE REVIEW

**Comment by Terisback** [comment]
I think that this bug will not be solved not inside this PR
image

**Comment by Terisback** [comment]
tmpl works fine, I think everything is ready to merge

**Comment by JalonSolov** [comment]
I'm not sure I understand.  In that failure, `test` really is unused.  Are tests not supposed to fail on unused variables?

**Comment by Terisback** [comment]
it's used in template of test @JalonSolov

**Comment by spytheman** [comment]
I will finish it today. The warning is a problem in the compiler, it should not trigger, because as @Terisback said, that local variable is used in the expanded source code generated from the template expansion.

**Comment by Terisback** [comment]
@spytheman How's the fix coming?

**Comment by Terisback** [comment]
:(

**Pull request merged**
