### PR TITLE
fix autofree of heap variables

### LINKED ISSUE #13822: autofree generates double free when assigning a reference
**V version:** 
V 0.2.4 d6c4086
**OS:** 
osx 12.0.1
**What did you do?**
create a struct with a custom free function and assign a reference to it to another variable
```
module main
struct Test {a int}
fn (t&Test)free()
{
    println(t.a)
}
fn main()
{
    a := Test{1}
    b := &a
}
```

**What did you expect to see?**
free being called once with the right value:
```
1
```

 
**What did you see instead?**
two free calls, the first one with a garbage value
```
33079360
1
```

### PR DESCRIPTION
**Pull request by maddanio**
this should fix #13822 by not taking the address of a heap allocated pointer when calling auto generated free

### CODE REVIEW

**Comment by maddanio** [comment]
do I need to make a red/green test for this?

**Comment by spytheman** [comment]
> do I need to make a red/green test for this?

yes, when possible, having tests is necessary to prevent future regressions

**Comment by spytheman** [comment]
For autofree, this usually means adding a small .v program in `vlib/v/tests/valgrind/` .
It will be compiled with `-autofree`, and it will be then run under valgrind.

You can do: `./v vlib/v/tests/valgrind/valgrind_test.v` to test that locally.

**Comment by maddanio** [comment]
valgrind does seem to catch it. it does however catch a leak, because the struct itself isnt freed as it should

**Comment by spytheman** [comment]
> valgrind does seem to catch it. it does however catch a leak, because the struct itself isnt freed as it should

It is a separate problem, so add a manual `unsafe { free(x) }` for now, with a TODO: note.

**Comment by maddanio** [comment]
I think I will also have to fix the double free then

**Comment by spytheman** [comment]
> I think I will also have to fix the double free then

It can be another PR if you want - it may be a harder problem.

**Review by vincenzopalazzo — APPROVED** [review]

**Review by vincenzopalazzo — APPROVED** [review]
LGTM, as @spytheman suggested, it is missed only a test to make sure we will not introduce some regression in some point in the future

**Comment by maddanio** [comment]
and this is with the changes in this branch. as you can see even with the fixes in this branch the original case I tried to fix is still broken. I will mull over this a bit, but am open for comments :)

**Comment by maddanio** [comment]
btw, this is with `-experimental`, which is what the valgrind tests run with

**Comment by maddanio** [comment]
i have the feeling when all of these are fixed autofree would be a big step further

**Comment by JalonSolov** [comment]
Just for "fun", I found this old issue.  Perhaps some of the discussion there may help (rather than muddying things even more):  #1247

**Pull request merged**
