### PR TITLE
checker: check unnecesary cast

### PR DESCRIPTION
**Pull request by StunxFS**
Add an warn for unnecessary casts, ie `int(x)` being `x` already of type `int`.

```v
unnecessary_cast.vv:3:10: warning: unnecessary cast, expression is already of type `int`
    1 | fn main() {
    2 |     a := 1
    3 |     println(int(a))
      |             ~~~~~~
    4 | }
```

### CODE REVIEW

**Comment by JalonSolov** [comment]
Would be nice if `v fmt` took care of this for you.

**Comment by Delta456** [comment]
Shouldn't this be a warning instead of an error?

**Comment by StunxFS** [comment]
> Shouldn't this be a warning instead of an error?

Done, converted to warn!

**Comment by StunxFS** [comment]
@JalonSolov 
> Would be nice if `v fmt` took care of this for you.

I don't think it's possible, `vfmt` does not use the `checker`

**Comment by Delta456** [comment]
I think you should change it to `c.notice` for now as it seems to break many things.

**Comment by spytheman** [comment]
I do not see any value in that; it is just making the compiler to be more anal, it does not make anything safer or more strict.
It would be the same as checking if you have added too many ().

**Pull request closed without merging**
