### PR TITLE
parser: fix sumtype with multi fntype (fix #15557)

### LINKED ISSUE #15557: Does not compile function Sum types
**V version: 0.3.0 70de4e1** 
**OS: ArchLinux** 

**What did you do?**

`v run .`
```v
type Fn = fn() int | fn(int) int
```

**What did you expect to see?**
No error
 
**What did you see instead?**
Build error
```
==================
/usr/lib64/crt1.o: error: Invalid relocation entry [15] '.rela.debug_info' @ 00000504
tcc: error: file 'crt1.o' not found
/tmp/v_1000/bug.7743942395938441458.tmp.c:26: error: ';' expected (got "int_int")
...
==================
```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix sumtype with multi fntype (fix #15557).

- Fix sumtype with multi fntype.
- Add test.

```v
type Fn = fn () int | fn (int) int

fn main() {
	f1 := Fn(fn (a int) int {
		return a
	})
	println(typeof(f1).name)

	f2 := Fn(fn () int {
		return 22
	})
	println(typeof(f2).name)
}

PS D:\Test\v\tt1> v run .
Fn
Fn
```

### CODE REVIEW

**Comment by spytheman** [comment]
hm, is not that `type Fn = fn () int | fn (int) int | string` ambiguous for parsing?

**Comment by spytheman** [comment]
@medvednikov how should we handle that ambiguity?

**Comment by spytheman** [comment]
```v
type Fn = (fn () int) | (fn (int) int | string)
```
may be one way?

**Comment by yuyi98** [comment]
inline sumtype without space around `|`, just like `int|string`.  it will not ambiguous if we follow this rule.

**Comment by spytheman** [comment]
> inline sumtype without space around `|`, just like `int|string`. it will not ambiguous if we follow this rule.

try:
```v
type Fn = fn () int | fn (int) int|string

fn abc(is_string bool) Fn {
    if is_string {
        return 'abc'
    }
    return fn () int { return 123 }
}

fn main() {
    dump(abc(true))
    x := abc(false)
    y := x as fn () int
    println( y() )
}
```

It does compile, but it should not (since Fn does not have a `string` variant), then it runs, and prints:
```
[z.v:11] abc(true): Fn('abc')
V panic: as cast: cannot cast `unknown` to `fn () int`
v hash: 86dbf17
/tmp/v_1000/z.16221942547804804776.tmp.c:6695: at _v_panic: Backtrace
/tmp/v_1000/z.16221942547804804776.tmp.c:7183: by __as_cast
```

**Comment by spytheman** [comment]
Another test program is:
```v
type Fn = fn () int | fn (int) int|string

fn abc(anonymous_sumtype_fn bool) Fn {
    if anonymous_sumtype_fn {
        return fn (x int) int|string { return x + 999 }
    }
    return fn () int { return 123 }
}

fn main() {
    a := abc(true)
    b := a as fn (x int) int|string
    println( b(1) )

    x := abc(false)
    y := x as fn () int
    println( y() )
}
```
... which fails with equivalent cgen errors, with both space and no space in the `type FN` declaration, i.e. the parser & checker accept both, and produce ~ the same result (the only differences are due to the anonymous fn names, which are randomized currently in the v implementation).

**Comment by spytheman** [comment]
Oh, sorry, I misunderstood you @yuyi98 - you are proposing, that the space should serve as a way to disambiguate in the future, i.e.
```v
type Fn = fn () int | fn (int) int|string
```
vs
```v
type Fn = fn () int | fn (int) int | string
```
would parse differently in the future, not that they do now.

**Comment by joe-conigliaro** [comment]
There is another option I would like to add.
it might conflict a bit with multi return (but only visually slightly they will never syntactically conflict)
I prefer the special case rule to always be applied to the special use.. in my opinion `fn (int) int | string this` is more of a fringe use, so the special case should apply here and not to the sum type definition (well it will inherently end up in the sum type definition but comes naturally)

```go
fn (int) (int|string)
```
```go
type Fn = fn () int | fn (int) (int | string)
```

so the rule would be anon sum-types must always be surrounded by parenthesis

on another note imo anon sum types  seems unnecessary to begin with

**Comment by kahsa** [comment]
It seems to me that using round brackets is easier to understand than distinguishing with or without a space.
It is also easier to prevent human error.

**Comment by medvednikov** [comment]
I think anonymous sum types add too much complexity and should be removed.

**Comment by yuyi98** [comment]
@medvednikov   This PR has nothing to do with the anonymous sumtype and is only referred to in the test. I'll change the test.

**Pull request merged**
