### PR TITLE
 gen: implement labelled break and continue (retry)

### PR DESCRIPTION
**Pull request by ntrel**
See #6880.

### CODE REVIEW

**Comment by ntrel** [comment]
The macos error seems unrelated - `clipboard/clipboard_darwin.m`

**Comment by dumblob** [comment]
Will this somehow affect *autofree*?

**Comment by ntrel** [comment]
I don't know about autofree, but I've just realized that labelled break/continue can skip the cleanup after `for in` with a map. Perhaps using it with a map could be disallowed.

**Comment by dumblob** [comment]
>Perhaps using it with a map could be disallowed.

Well, I personally suspect it'd cause many more hard-to-find cases for the compiler. @medvednikov thoughts?

As of now I see labelled break/continue as highly experimental and untested feature with quite some potential to break some V compiler assumptions.

**Comment by ntrel** [comment]
> labelled break/continue can skip the cleanup after an inner for in loop with a map

I think I can remove the need for the map cleanup.

> As of now I see labelled break/continue as highly experimental and untested feature with quite some potential to break some V compiler assumptions.

The compiler actually already had `goto`, which is more dangerous.

About `-autofree`, the key variable is not freed at the moment. Freeing it will have to handle a bare break/continue statement, so handling labelled break/continue is no different.

**Pull request merged**
