### PR TITLE
cgen: implement sorting globals and consts definitions

### PR DESCRIPTION
**Pull request by yuyi98**
This PR implement sorting globals and consts definitions.

now `json` and `rand` module have problems to fix.

```v
const (
	weapon_keys = [&foo, &bar]!
	foo         = u32(1)
	bar         = u32(2)
)

fn main() {
	println(weapon_keys)
	assert weapon_keys[0] == &foo
	assert weapon_keys[1] == &bar
}

PS D:\Test\v\tt1> v run .
[1, 2]
```
c2v:
```v
PS D:\Test\v\c2v_out> v -o "doom.o" -w -translated .
==================
C:/Users/yuyi9/AppData/Local/Temp/v_0/doom.o.10437404920755315205.tmp.c:574: warning: WINVER redefined
C:/Users/yuyi9/AppData/Local/Temp/v_0/doom.o.10437404920755315205.tmp.c:8597: error: incompatible types for redefinition of 'LoadMenuW'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.
```

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Excellent!

**Comment by spytheman** [comment]
> now json and rand module have problems to fix.

True, but the approach is sound, well done.

**Comment by yuyi98** [comment]
Thanks !!!

**Comment by yuyi98** [comment]
@spytheman   Why is inode_test.v error?
```v
FAIL  [ 162/1022]   236.264 ms vlib/os/inode_test.v
testsuite_begin, tfolder = /tmpvtestsinode_test
V panic: folder: /tmpvtestsinode_test/, error: Permission denied
v hash: c5be228
/tmp/v/test_session_190574436608/inode_test.15734602633235500514.tmp.c:7691: at _v_panic: Backtrace
/tmp/v/test_session_190574436608/inode_test.15734602633235500514.tmp.c:13300: by os__testsuite_begin
/tmp/v/test_session_190574436608/inode_test.15734602633235500514.tmp.c:18715: by main
```

**Comment by spytheman** [comment]
Not sure yet.

**Comment by spytheman** [comment]
previously V did:
```
void _vinit(int ___argc, voidptr ___argv) {
	builtin_init();
	vinit_string_literals();
	...
```
where:
```
// >> string literal consts
void vinit_string_literals(void){
...
	_const_os__path_separator = _SLIT("/");
	_const_os__path_delimiter = _SLIT(":");
}
// << string literal consts
```

I.e. `_const_os__path_separator` was initialized before it was used by 
`_const_os__args = os__init_os_args(___argc, (byte**)___argv);`
later in _vinit.

It now generates:
```
	_const_os__fslash_str = _SLIT("/");
	_const_os__dot_dot = _SLIT("..");
	_const_os__empty_str = _SLIT("");
	_const_os__dot_str = _SLIT(".");
	_const_os__args = os__init_os_args(___argc, (byte**)___argv);

	_const_os__wd_at_startup = os__getwd();

	_const_os__path_separator = _SLIT("/");
	_const_os__path_delimiter = _SLIT(":");
```
instead.

I think that these:
```
	_const_os__args = os__init_os_args(___argc, (byte**)___argv);

	_const_os__wd_at_startup = os__getwd();
```
should be sorted last (i.e. const initialised by function calls), since functions can do arbitrary things, and can access all the previous const values.

**Comment by yuyi98** [comment]
I see, Thanks !!!

**Comment by spytheman** [comment]
Alternatively, `ast.StringLiteral` consts should be first.

**Comment by yuyi98** [comment]
Thanks !!!

**Pull request merged**
