### PR TITLE
Fix bit order in bitfield field

### PR DESCRIPTION
**Pull request by SilvanCodes**
This PR fixes the bit order inside the 'field' value of Bitfield structs.

It does so by reversing the u32 containers for the bits after they are put in place with math.bits.reverse32().

The test is fixed as well to read the bits from the input in the correct order.

### CODE REVIEW

**Comment by SilvanCodes** [comment]
@ciubotaru Thanks, you are correct about the simpler `|=` compared to the match expression!

Regarding the reversing I think you are missing the fact that I build the u32 container with byte blocks but the reverse32 works on a bit level. To avoid using reverse32 I would have to manually reverse the bytes before placing them which would just be re-implementing reverse8 and reverse  more often than doing it to the entire u32 at the end.
Please correct me if I'm wrong. :)

**Comment by ciubotaru** [comment]
Let's start with some basic assumptions:
1. The `bitfield` structure stores bits across an array of 32-bit integers (`[]u32`).
2. The bits are stored consecutively, i.e. `field[0]` stores bits 0-31, `field[1]` stores bits 32-63 and so on.
3. Inside the integer, the bits are stored consecutively, too. E.g. `.getbit(13)` will retrieve the 13-th bit from field[0]. We do not care about how the bits are stored at machine level.

I also assume that the input array of 8-bit integers stores bits in the same order. So we want the first byte to become bits 0-7 in field[0], the second one to become bits 8-15, the fifth one to become bits 0-7 in field[1] etc. Again, we do not care about how individual bits are stored inside a byte on machine level. Moreover, since we deal with bytes, we do not care about the endianness (we would, if we used u16 or smth else as input).

Now let's talk about how to copy bits from byte to u32:
1. Imagine we have one single byte as input. To store it, we will need one u32. To put it in place, we do `output.field[0] |= input[0]`.
2. Imagine we have two bytes. The first one is stored as above. The second one needs to be converted to u32, shifted 8 positions to the left, and multiplied (bitwise AND) with `output.field[0]`. If we have more, input[2] will have to be shifted 16 positions, and input[3] 24 positions to the left.
3. When we have more than 4 bytes, we will have to determine the target container (bytes 0-3 go to field[0], bytes 4-7 go to field[0] and so on) and then proceed as above.

There is nothing to reverse here. If, for whatever reason, the input data come in a different order, the user will have to order them properly _before_ importing them into a bitfield.

For reference, have a look at a C implementation: https://github.com/ciubotaru/bitfield .

**Comment by ciubotaru** [comment]
> you are correct about the simpler |= compared to the match expression

I am afraid I did not make myself clear enough. I was saying that the whole fragment

````
		match i % 4 {
					0 {
						output.field[pos] = output.field[pos] | (u32(b) << 24)
					}
					1 {
						output.field[pos] = output.field[pos] | (u32(b) << 16)
					}
					2 {
						output.field[pos] = output.field[pos] | (u32(b) << 8)
					}
					3 {
						output.field[pos] = output.field[pos] | u32(b)
					}
				}
````

can be replaced with one line `output.field[pos] |= (u32(b) << (i % 4) * 8)`.

**Comment by ciubotaru** [comment]
To sum it up: you are solving the wrong problem. The bit order is not broken. It's the byte order that needs to be fixed, both in .from_byte() method and its test.

**Comment by medvednikov** [comment]
It also needs to be replaced to `bitfield.from_string()`

**Comment by ciubotaru** [comment]
> Is it reasonable to expect those two function calls to behave identical i.e. to result in the same bitfield?

Good question.

Currently, "11110000" in str2bf is __not__ the same as 0b11110000. It's just a string of zeros and ones, of arbitrary length (not aligned to 8, or anything), where the first (left-most, not right-most) character is treated as least-significant bit.

If you want "11110000" to mean "0b11110000", then str2bf needs to be rewritten.

**Comment by SilvanCodes** [comment]
@ciubotaru 
The code now now complies with your description of the expected behavior.

The question of whether to adapt str2bf() seems dependent on the use case of that function which is not clear to me. :)

**Comment by medvednikov** [comment]
Can we rename `str2bf` to `from_string` as well?

**Comment by medvednikov** [comment]
Thanks. Is it good to merge?

**Comment by SilvanCodes** [comment]
Tests pass, v compiles itself two times in a row. :)

**Comment by SilvanCodes** [comment]
Uh, I added `pub` modifier to Bitfield struct in order to import it as a type for other structs. That's not directly related to this PR, should I remove it?

**Comment by ciubotaru** [comment]
The code compiles and works as expected.

As for that `pub`, I don't see any difference with and without it. I mean, I can not use BitField as an element of another struct in either case.

**Pull request merged**
