### PR TITLE
examples/vweb: use map instead of string in call to app.json

### PR DESCRIPTION
**Pull request by mcastorina**
Now that vweb encodes the object in `Context.json`, the example was JSON encoding a manually JSON-encoded string.

### CODE REVIEW

**Comment by hubyhuby** [comment]
Thanks for the fix ;)
I will try it
https://discord.com/channels/592103645835821068/592294828432424960/904069722646138961

**Comment by hubyhuby** [comment]
Works better now it output proper int values in json format.
Also when adding a string in my json reponse it doesn t seem to like it :
image

**Comment by spytheman** [comment]
@hubyhuby , in V, a map is always between a key of a certain type, to a value of another type. 
You can not mix value types in the same map.

What you can however, is define a custom struct:
```v
struct MyStruct {
       user int
       age int
       txt string
}
```
... then, instead of an implicit map, pass that struct:
```v
return app.json(MyStruct{ 
       user: id
       age: 50
       txt: "some text"
})
```
... which will result in the following json:
```json
{"user":92,"age":50,"txt":"some text"}
```
image

**Comment by spytheman** [comment]
If you do want the capitalized names in the generated JSON, use this custom struct declaration:
```v
struct MyStruct {
       user int
       age int [json: 'Age']
       txt string [json: 'TXT']
}
```

**Comment by hubyhuby** [comment]
Thanks for all those explaination, it works for me .
Using httpie the Json looks nice now
image

**Pull request merged**
