### PR TITLE
cgen: fix struct ref field with no ref structinit

### LINKED ISSUE #21489: Struct and Reference Struct type mismatch in Struct Default Value
### Describe the bug

_Note: Bar must at least have 1 field or it will be interpreted as nil and work_
```v
struct Foo {
	bar &Bar = Bar{}
}

struct Bar {
	field int
}

fn main() {
	dump(Foo{})
}
```
If type Foo.bar is &Bar but is provided Bar it will throw this C error:
`/tmp/v_60000/../../../../../../box/code.v:10: error: cannot convert 'struct main__Bar' to 'struct main__Bar *'`

If type Foo.bar is Bar but is provided &Bar it will convert &Bar to Bar but Bar's field values will be corrupted like #20969

### Reproduction Steps

```v
struct Foo {
	bar &Bar = Bar{}
}

struct Bar {
	field int
}

fn main() {
	dump(Foo{})
}
```

### Expected Behavior

Proper serialisation of the default field values or V error

### Current Behavior

If type Foo.bar is &Bar but is provided Bar it will throw this C error:
`/tmp/v_60000/../../../../../../box/code.v:10: error: cannot convert 'struct main__Bar' to 'struct main__Bar *'`

If type Foo.bar is Bar but is provided &Bar it will convert &Bar to Bar but Bar's field values will be corrupted like #20969

### Possible Solution

Whilst default field values don't work, setting them at runtime does, so adding those checks at comptime for default field values might help

### Additional Information/Context

Found and tested in V playground

### V version

V 0.4.5 0e2b604

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.5 0e2b604
OS: linux, Debian GNU/Linux 11 (bullseye) (VM)
Processor: 1 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz

getwd: /home/admin/playground
vexe: /home/admin/v/v
vexe mtime: 2024-05-11 08:25:23

vroot: OK, value: /home/admin/v
VMODULES: OK, value: .vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.30.2
Git vroot status: Error: fatal: detected dubious ownership in repository at '/home/admin/v'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v
.git/config present: true

CC version: cc (Debian 10.2.1-6) 10.2.1 20210110
thirdparty/tcc status: Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc
 Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc

```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

### PR DESCRIPTION
**Pull request by felipensp**
Fix #21489

### CODE REVIEW

**Comment by spytheman** [comment]
I think it should be a checker error instead.

For example this already is:
```v
struct Bar {
    field int
}

struct Foo {
    bar &Bar
}

mut a := Foo{
    bar:  Bar{}
}
```

... producing:
```
z.v:15:3: error: reference field must be initialized with reference
    9 |     mut a := Foo{
   10 |         bar:  Bar{}
      |         ~~~~~~~~~~~
```

**Comment by spytheman** [comment]
For this:
```v
struct Foo {
    bar &Bar = Bar{}
}
```
... it could require using `bar &Bar = &Bar{}` instead, which is both more explicit, and easier to handle for the compiler (no need to do automatic (de)referencing).

**Comment by felipensp** [comment]
Yes, I do agree. But unfortunately there is code using such syntax... (even on vlib) so it will produce a break.

**Comment by spytheman** [comment]
> Yes, I do agree. But unfortunately there is code using such syntax... (even on vlib) so it will produce a break.

Where are those places? If there are small in number, we can change them manually 🤔 .

**Comment by spytheman** [comment]
If they are many, we could add a checker notice, then fix them gradually, then turn the notice into a warning/error.

**Comment by felipensp** [comment]
> If they are many, we could add a checker notice, then fix them gradually, then turn the notice into a warning/error.

I think just this one:

image

**Comment by spytheman** [comment]
Given that the issue code triggers a cgen error on master, I think they will not be too many.

**Comment by spytheman** [comment]
Are all of them in `@[params]` structs?

**Comment by felipensp** [comment]
> Are all of them in `@[params]` structs?

On V project is just this one, no idea on userland cases.

**Comment by spytheman** [comment]
There is not a difference in the generated code with or without the & at all, 
for `downloader &Downloader = TerminalStreamingDownloader{}`:

```
#0 00:17:06 ^ master /space/v/oo>git diff
diff --git vlib/net/http/download_progress.v vlib/net/http/download_progress.v
index 9811f3e70..f8c9d87e6 100644
--- vlib/net/http/download_progress.v
+++ vlib/net/http/download_progress.v
@@ -23,7 +23,7 @@ mut:
 pub struct DownloaderParams {
        FetchConfig
 pub mut:
-       downloader &Downloader = TerminalStreamingDownloader{}
+       downloader &Downloader = &TerminalStreamingDownloader{}
 }

 // download_file_with_progress will save the URL `url` to the filepath `path` .
#0 00:17:08 ^ master /space/v/oo>./v -o new.c cmd/tools/vdownload.v
#0 00:17:17 ^ master /space/v/oo>git stash
Saved working directory and index state WIP on master: 97432c359 v.scanner: use table lookups for very frequently done character checks (#21931)
#0 00:17:19 ^ master /space/v/oo>./v -o old.c cmd/tools/vdownload.v
#0 00:17:21 ^ master /space/v/oo>colordiff old.c new.c
#0 00:17:25 ^ master /space/v/oo>
```

I think, that it may be because `Downloader` is an interface, not a struct 🤔 .

**Comment by spytheman** [comment]
In any case, I think, that changing the checker to error for `field &Struct = Struct{}`, will not break it.

**Review by spytheman — APPROVED** [review]

**Pull request merged**
