### PR TITLE
Create README.md file in Indonesian

### PR DESCRIPTION
**Pull request by Stevanus-Christian**

### CODE REVIEW

**Comment by spytheman** [comment]
@medvednikov what do you think?

**Comment by spytheman** [comment]
You should run `./v check-md -hide-warnings README.id-ID.md` on the new file, and wrap the lines longer than 100 characters, until it no longer complains.

**Comment by ylluminate** [comment]
@Stevanus-Christian there was some expression before that English would be the main language for some time; perhaps until 1.0 is reached, but thanks for pulling this together. We'll just have to see what @medvednikov thinks here and if it's not going to be something that adds too much additional complexity for maintenance as things evolve.

**Comment by JalonSolov** [comment]
The main problem with supporting the docs in multiple languages is keeping people around who speak those languages who are motivated to keep them up-to-date.

Creating a translation once doesn't help if the main doc gets changed.

**Comment by spytheman** [comment]
All of the above is true, but on the other hand, README.md contains mostly installation instructions, and is much shorter than the main documentation. It also was not changed substantially in the last 4-5 months (mostly fixing typos + very small changes that are easy to propagate).

**Comment by ylluminate** [comment]
@spytheman this is true and I've had the same thoughts, but likewise I've had the same thoughts of @JalonSolov. It seems to me that by introducing one such translation we may be creating some additional complexity/consideration that might cascade into complexity that the project is not yet ready to receive. Clearly if we open up this road then we need someone who's experienced with translation considerations and can produce some guidance documentation for actually properly beginning such a venture and it would seem that such translations will need to be funneled into some additional folder hierarchy to capture such...

**Comment by Stevanus-Christian** [comment]
@JalonSolov don't worry, I will update this file if there is a change in the main README file

@ylluminate right, you have to create a new directory to save the files
README in multiple languages

**Comment by Stevanus-Christian** [comment]
if you don't need README files in multiple languages, no problem. I will close this PR

**Comment by kahsa** [comment]
Even if only README.md can be read in one's native language, all other documents are in English, so in the end, one has to read English to proceed, but, well, I think it is OK for only README.md to exist in different languages.

As for Doc.md, for example, in Japanese, there is a person who translates it privately, as shown here https://qiita.com/MikuroXina/items/be3d4d9198cab32aed64, and updates are made relatively frequently.
Even if you don't incorporate it into vlib, it may be worthwhile just to post a link to each language.

**Comment by kahsa** [comment]
> A negative is that it would be harder to explain why some .md files are now translated and why some are not thinking .

No one needs to take responsibility for this.
Since it is open source, there simply was no contributor to translate it. That is a sufficient explanation.

**Comment by kahsa** [comment]
I agree with creating a new folder.
And as a rule, when updating the translated version, we should always mention what version of the English version it was based on.
Then, a few months later, when updating, the differences from the original version should be corrected.

**Comment by spytheman** [comment]
Is there a language project, that does documentation translations in a good way, so that we can look at how it is structured, and what does it use?

**Comment by spytheman** [comment]
Please do `git pull --rebase origin master`, and fix the remaining wrapping errors, reported by `v check-md README.id-ID.md` @Stevanus-Christian .

**Comment by spytheman** [comment]
How about this structure?
```
doc/translations/docs.id-ID.md
translations/README.id-ID.md
```
i.e. each folder that has translated .md files, could have a `translations/` subfolder, containing them, where each will have the postfix `.language-COUNTRY.md` . I hope that something like this is general enough to accommodate future work, without breaking URLs.

**Pull request closed without merging**
