### PR TITLE
header: add method to search header starting with key

### PR DESCRIPTION
**Pull request by esquerbatua**

### CODE REVIEW

**Comment by spytheman** [comment]
What problem does that solve? Is there a situation, where you will want to have the first header line that matches a start of a string, instead of the exact key?

**Comment by esquerbatua** [comment]
Yes, there are some services that some headers starts with x string, and have information about the number of the querys or the time that you need to wait to send another query.
Ex: https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#order-rate-limits
binance uses the header X-MBX-ORDER-COUNT-(intervalNum)(intervalLetter) to chech the count of the rate limits, and others.

**Comment by medvednikov** [comment]
string.starts_with() returns a bool, so it'd be confusing.

**Comment by esquerbatua** [comment]
I can change the method name

**Comment by spytheman** [comment]
> I can change the method name

What will be the new name?

**Comment by Gladear** [comment]
What about `starting_with` or `first_starting_with`, since it only returns the first one found

**Comment by esquerbatua** [comment]
I like 'starting_with'

**Pull request merged**
