### PR TITLE
array initialization: add more tests (for int and string arrays)

### PR DESCRIPTION
**Pull request by smartiniOnGitHub**
Hi,
note that **tests added here currently are failing**, but I think because array items are not properly initialized with the given 'init' value (but only with the default one of the type.

On string arrays default nil value is breaking even the conversion to string of the array, so not sure if my test without init value it makes sense, or if possible in that case to print a literal `nil` (or `null` or other similar) instead for a safe conversion to string (like in Java, Node.js, etc)  ...

I added a TODO comment in any test that's failing (to identify in a simpler way); before the merge tell me so I can remove those comments.

Tell me.
Thanks

### CODE REVIEW

**Comment by medvednikov** [comment]
Yeah I'll fix `init: ` today.

Thanks for the tests

**Comment by medvednikov** [comment]
```
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/v/array_init_test.tmp.c:10252:6: error: redefinition of 'int_val_t'
        int int_val_t = 1;
            ^
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/v/array_init_test.tmp.c:10204:6: note: previous definition is here
        int int_val_t = 1;
```

**Comment by medvednikov** [comment]
now it's

```
Test array of int values
array a: length: 2, capacity: 10, content: [0, 0]
array b: length: 10, capacity: 100, content: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
/Users/runner/runners/2.262.1/work/v/v/vlib/v/tests/array_init_test.v:34: failed assert in test_normal_array_int_full_options()
Source  : assert b.str() == '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
```

**Comment by smartiniOnGitHub** [comment]
@medvednikov I'll rebase my branch and update failing tests ASAP (later today or max tomorrow), thanks for now.

**Comment by smartiniOnGitHub** [comment]
@medvednikov tests on array of int values now is good, but now it's failing the test on array of string values, in the default case any item as a values of nil, so when I try to print that array I get:
```V panic: string.eq(): nil string```
for the println at line 79 ... but I think it would be useful (in general) to be able to convert to string even markers for nil/null values. For example this is similar to JSON handle null values; if you agree I could add some more test on this in other places (later PR).
Tell me what you prefer, so I can remove remaining TODO.

Sorry in more complex test suites, to better understand where errors are, what do you think on the ability during tests, to output even current test source and current test function ? Maybe enabled/disabled with a runtime flag ... should I raise a feature request on this (if you think it's useful) ?

Thanks a lot.

**Comment by medvednikov** [comment]
In V nil strings are impossible, so that always means a bug.

**Comment by smartiniOnGitHub** [comment]
ok, so do you think it's better to remove my failing test, or str function for array of strings could handle it and print the literal nil (or null for example) anytime a string doesn't have a value ? 
Tell me so I'll update last failing test. Thanks a lot.

**Comment by medvednikov** [comment]
Can you paste the failing test here?

**Comment by smartiniOnGitHub** [comment]
Sure, it's the first in test function "test_normal_array_string_full_options":
```
	a := []string{len: 2, cap: 10} // this creates an array with 2 items, initial capacity 10, default value of array type
	println('array a: length: ${a.len}, capacity: ${a.cap}') // ok
	println('array a: length: ${a.len}, capacity: ${a.cap}, content: "$a"') // gives: V panic: string.eq(): nil string // TODO: check if fix, so this could work
	assert a.len == 2
	assert a.cap == 10
	assert a.cap >= a.len
	assert a.str() == "[nil, nil]" // TODO: check if expect nil or null for missing values if good ...
```

**Comment by medvednikov** [comment]
Yeah it definitely should be removed. Default string values are '', so it should be ['', '']

**Comment by smartiniOnGitHub** [comment]
ok, with updated code now I have the same error, a V panic:
`
Test array of string values
array a: length: 2, capacity: 10
V panic: string.eq(): nil string
`
which is caused by this:
`
	println('array a: length: ${a.len}, capacity: ${a.cap}, content: "$a"')
`
so I think the bug is that default values are not set in this case on string items ... I can see it running that test source from my fork.
Hope it's good now. Thanks again.

**Comment by smartiniOnGitHub** [comment]
@medvednikov now all test code should be fine, to let it pass even last failing test we only need the fix on default initialization of string arrays (when no init value is specified) I think. 
Thank for all the help on this. Bye

**Comment by smartiniOnGitHub** [comment]
rebased on top of updated master.
@yuyi98 with your fixes now even last tests here now works !!
Thank you very much to all for fixes and the help on this.

**Pull request merged**
