### PR TITLE
Fix #2079 . Add some infrastructure for more specific errors.

### LINKED ISSUE #2079: compiler: wrong error line/position, when `cannot use type...in assignment`
**V version:** V 0.1.20 60d932e
**OS:** Ubuntu 16.04.3 LTS

**What did you do?**
I tried to compile the following program:
```v
struct Node {
mut:
  head &Node
  tail &Node
}

fn (n Node) str() string {
  return 'node content: { head: $n.head , tail: $n.tail }'
}

fn print_node(label string, n &Node) {
  println('Node $label: ' + ptr_str(voidptr(n)) + ' : ' + n.str() )
}

mut n1 := Node{}
mut n2 := Node{}
n1.tail = &n2
n2.head = &n1

print_node('n1', n1)
print_node('n2', n2)

n1.tail = voidptr(0)
// just a dummy comment, to make the v scanner update its pos and line_nr
// so that when it finally decides to bail with '..:26:10: cannot use type voidptr as type Node* in assignment'
// the error position will be wrong...
print_node('n1', n1)
```

**What did you expect to see?**
Something like:
```shell
0[11:34:42] /v/v $ ./v x.v
n1.tail = voidptr(0)
        ^
/v/v/x.v:23:10: cannot use type `voidptr` as type `Node*` in assignment
1[11:35:33] /v/v $
```
 
**What did you see instead?**
```shell
0[11:34:42] /v/v $ ./v run x.v
print_node('n1', n1)
         ^
/v/v/x.v:26:10: cannot use type `voidptr` as type `Node*` in assignment
1[11:35:33] /v/v $
```

### PR DESCRIPTION
**Pull request by spytheman**
This PR implements:
fn (p mut Parser) error_with_tok(s string, tok Tok) 
and uses it to solve issue #2079 .

### CODE REVIEW

**Comment by medvednikov** [comment]
now we have token.line_nr and token.sp.line_nr

**Comment by spytheman** [comment]
Yes, it is a duplication... I was going to remove token.line_nr , but then I saw that it is used not only for error reporting, and I thought that it is more convenient to have it directly on the token, while the scanner position sp is useful only for error reporting.

**Comment by medvednikov** [comment]
It's just there are millions of tokens created for every program. Adding new fields to `Token` struct is very expensive.

**Comment by medvednikov** [comment]
Is there a way to somehow generate that position on error only?

We have the line number and col for each token.

**Comment by spytheman** [comment]
Yes, but they are not enough unfortunately. 
You need the scanner position of the token in the original text too, or else it can not show the text of the line where it was retrieved originally. 

A possible alternative would be to split the source text that is in the scanner into an []string at the point of the error reporting, splitted by newlines (and keeping the same \r\n logic as was used in the first place).

**Comment by medvednikov** [comment]
I'd prefer that to be honest.

It's only done once, during the error.

But if we store it in token.sp, we have to store and copy it for millions of tokens.

**Comment by spytheman** [comment]
ok, I will do it that way.

**Comment by spytheman** [comment]
Error highlights

**Pull request merged**
