### PR TITLE
get extension of path

### PR DESCRIPTION
**Pull request by kindlychung**

### CODE REVIEW

**Comment by whoizit** [comment]
it should not be `get_extension()`

should be `filename_ext()`, `file_ext()` or even `ext()`

**Comment by kindlychung** [comment]
fixed that and added a `path_sans_ext` function.

**Comment by whoizit** [comment]
it should not be `path_sans_ext`

**Comment by whoizit** [comment]
maybe `file_path` or `base_filename`?

**Comment by medvednikov** [comment]
base file name is different

**Comment by medvednikov** [comment]
I'm not sure the stdlib needs that function, so it might be removed. but `ext` is useful

**Pull request merged**
