### PR TITLE
Fix up redundant type declare arguments

### PR DESCRIPTION
**Pull request by paveg**
## Overview
I found and improved redundant type declare arguments.
Please, check and merge if possible.

### And more
- Remove unnecessary space ( or tab) .

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks. There's a small conflict, can you please update it?

**Comment by paveg** [comment]
@medvednikov I updated this PR, please check.

**Comment by medvednikov** [comment]
Sorry, one last time. I won't be pushing code to master in the next 5 hours.

**Comment by paveg** [comment]
@medvednikov please, check this.

**Pull request merged**
