### PR TITLE
js: no need to generate classes

### PR DESCRIPTION
**Pull request by vitalyster**
1) classes are evil :)
2) js output should be ES5-compliant
3) no need in nightly(sic!) node, no need in harmony options, no need in custom gcc on linux

### CODE REVIEW

**Comment by joe-conigliaro** [comment]
Imo we should take advantage of ES6 and it's features including classes. ES6 should be standard already, if it weren't for slow browser adoption. Where it isn't yet it will be. There are transpilers to ES5. I can understand not liking classes 😁. But in a language where now they are first class, I don't see why we should stick with the prototype mess. Not to mention other features we can take advantage of. Just my thoughts

**Comment by vitalyster** [comment]
1. ES6 classes does not have any features except syntactic sugar
2. Yes we can convert to es5 with `babel hi.js`, but it is required to set up full nodejs build infrastructure for project, why not just produce es5? :)

**Comment by joe-conigliaro** [comment]
I know the classes are just sugar :) There are lots of new features we could use though

**Comment by vitalyster** [comment]
Sure we can and should use all new ES features when we are writing in JS, but we are writing in V, and JS output is for JS VM and not for us :)

**Comment by joe-conigliaro** [comment]
I mean for v :D

**Comment by medvednikov** [comment]
@vitalyster ok, let's do this

But can you please leave the struct fields via adding them to the jsdoc, as we discussed?

It'd also be nice to add a small vjstest.v to make sure it compiles.

**Comment by vitalyster** [comment]
@medvednikov done. Test was already there

**Comment by medvednikov** [comment]
Thanks!

**Pull request merged**
