### PR TITLE
gg: renaming drawing functions

### PR DESCRIPTION
**Pull request by BenStigsen**
```v
import gg
import gx
import math

struct App {
mut:
	gg &gg.Context
}

fn main() {
	mut app := &App{
		gg: 0
	}
	
	app.gg = gg.new_context(
		width: 200
		height: 200
		window_title: 'Renaming Test'
		frame_fn: frame
		user_data: app
	)
	
	app.gg.run()
}

fn frame(mut app App) {
	app.gg.begin()
	
	app.gg.draw_rect_empty(8, 8, 25, 25, gx.white)
	app.gg.draw_rect_filled(10, 10, 20, 20, gx.red)
	
	app.gg.draw_triangle_empty(60, 8, 80, 34, 40, 34, gx.white)
	app.gg.draw_triangle_filled(60, 12, 74, 30, 46, 30, gx.red)
	
	//app.gg.draw_circle_empty(110, 10, 10, gx.white) // Not implemented yet
	app.gg.draw_circle_filled(110, 20, 8, gx.red)
	
	app.gg.draw_arc_empty(26, 70, 10, 20, f32(math.radians(270)), f32(math.radians(90)), 30, gx.white)
	app.gg.draw_arc_filled(26, 70, 12, 18, f32(math.radians(260)), f32(math.radians(100)), 30, gx.red)
	
	app.gg.draw_slice_empty(74, 60, 12, 90, f32(math.radians(270)), 30, gx.white)
	app.gg.draw_slice_filled(74, 60, 8, 90, f32(math.radians(270)), 30, gx.red)
	
	app.gg.draw_poly_empty([f32(30), 100, 40, 110, 40, 120, 30, 130, 20, 130, 10, 120, 10, 110, 10, 100], gx.white)
	//app.gg.draw_poly([...]) // Not implemented yet
	
	app.gg.draw_ellipse_empty(120, 115, 40, 20, gx.white)
	app.gg.draw_ellipse_filled(120, 115, 36, 16, gx.red)
	
	/*
	// Deprecated
	app.gg.draw_empty_rect(8, 8, 25, 25, gx.white)
	app.gg.draw_rect(10, 10, 20, 20, gx.red)
	
	app.gg.draw_empty_triangle(60, 8, 80, 34, 40, 34, gx.white)
	app.gg.draw_triangle(60, 12, 74, 30, 46, 30, gx.red)
	
	//app.gg.draw_empty_circle(110, 10, 10, gx.white) // Not implemented yet
	app.gg.draw_circle(110, 20, 8, gx.red)
	
	app.gg.draw_empty_arc(26, 70, 10, 20, f32(math.radians(270)), f32(math.radians(90)), 30, gx.white)
	app.gg.draw_arc(26, 70, 12, 18, f32(math.radians(260)), f32(math.radians(100)), 30, gx.red)
	
	app.gg.draw_empty_slice(74, 60, 12, 90, f32(math.radians(270)), 30, gx.white)
	app.gg.draw_slice(74, 60, 8, 90, f32(math.radians(270)), 30, gx.red)
	
	app.gg.draw_empty_poly([f32(30), 100, 40, 110, 40, 120, 30, 130, 20, 130, 10, 120, 10, 110, 10, 100], gx.white)
	//app.gg.draw_poly([...]) // Not implemented yet
	
	app.gg.draw_empty_ellipse(120, 115, 40, 20, gx.white)
	app.gg.draw_ellipse(120, 115, 36, 16, gx.red)
	*/
	
	app.gg.end()
}
```
image

### CODE REVIEW

**Comment by BenStigsen** [comment]
All of the failed checks seem to be unrelated to PR, so that is good I guess?

**Comment by JalonSolov** [comment]
Looks like a lot of things failed because your PR deprecates routines, and those are showing up as errors.

**Comment by BenStigsen** [comment]
> Looks like a lot of things failed because your PR deprecates routines, and those are showing up as errors.

One is websockets.
Two is musl, alpine-musl and ubuntu-musl because of Docker errors. 

One is arm64-ubuntu-tcc
> Failed to start an instance! Failed to pull null image! Repository does not exist or may require authentication.

The only one as far as I understand that fails, is ubuntu-tcc, which fails because of the deprecation warnings.
> error: method `gg.Context.draw_rect` has been deprecated; use draw_rect_filled() instead

**Comment by BenStigsen** [comment]
Are these error not to be expected?

**Comment by JalonSolov** [comment]
The `503 service unavailable` is a network thing.  I'll try closing/re-opening to see if it happens again.

The deprecation things... yes, you expect them to be errors, but errors in CI runs mean the CI fails.  :-\

**Comment by JalonSolov** [comment]
That "may need authentication"... ?!?

**Comment by BenStigsen** [comment]
arm64-ubuntu-tcc failed again.
> Failed to start an instance! Failed to pull null image! Repository does not exist or may require authentication.

**Comment by BenStigsen** [comment]
Hnnm what should be done about this?

**Comment by JalonSolov** [comment]
Some of them look like the files just need to be updated as part of your PR.
For example:
```
vlib/gg/gg.c.v:634:6: error: method `gg.Context.draw_rect` has been deprecated; use draw_rect_filled() instead
  632 | [inline]
  633 | pub fn (ctx &Context) draw_square_filled(x f32, y f32, s f32, c gx.Color) {
  634 |     ctx.draw_rect(x, y, s, s, c)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~
  635 | }
  636 |
```
Looks like that needs to be changed to `ctx.draw_rect_filled(x, y, s, s, c)`

**Comment by BenStigsen** [comment]
Ah crap, yeah that'd do it

**Comment by JalonSolov** [comment]
Looks like most of the rest of the complaints are the same.  `draw_rect` being used instead of `draw_rect_filled`, etc.  Basically, all the `gg` source needs to be updated to use the new names instead of calling the older, deprecated one.

**Comment by BenStigsen** [comment]
Well, would you look at that! :smile:

**Review by spytheman — APPROVED** [review]
good work

**Pull request merged**
