### PR TITLE
Makefile: add make install command

### PR DESCRIPTION
**Pull request by ItaySharon**
This PR adds the `install` target to the Makefile.

By implementing this command, V can be installed via the standart
```
make
sudo make install
```
Workflow

### CODE REVIEW

**Comment by Compro-Prasad** [comment]
There is already #647

**Comment by ItaySharon** [comment]
This commit would be problematic since the repo folder could be in a private location (i.e. /home/<user>/v), v uses the repo for the libs.
My PR installs the repo folder into /opt, which is a public location

**Comment by Compro-Prasad** [comment]
I don't think there is a hard dependency on the libs. The v libs are required only at compile time. So, the final executable needs to be copied.
Am I missing something? Do you mean that libs like `import os` wont work?

**Comment by ItaySharon** [comment]
Try to rename your initial repo folder, by doing so and then running `v run <anything>.v` you should get the following message
```
Looks like you are running V for the first time.
V repo not found. Go to https://vlang.io to download V.zip 
or install V from source.
```

**Comment by Compro-Prasad** [comment]
I now understand.

**Comment by whoizit** [comment]
bad PR, watch for this https://github.com/vlang/v/issues/1195

**Pull request closed without merging**
