### PR TITLE
Able to install multiple modules in one command: 'v install m1 m2 m3 …'

### PR DESCRIPTION
**Pull request by iredmail**
Able to install multiple modules in one command:

```
v install pg gl sqlite
```

### CODE REVIEW

**Comment by medvednikov** [comment]
println('Installing module $name: git -C $home/.vmodules clone)

printing a git command is not necessary

**Comment by iredmail** [comment]
I understand, but printing such message will be better for programmers to know what it's doing. I can remove it if you insist in, just give me a confirm. :)

**Comment by medvednikov** [comment]
You can add it to verbose and debug flags

**Comment by iredmail** [comment]
Removed. :)

**Pull request merged**
