### PR TITLE
checker: simplify argument qualifier errors

### PR DESCRIPTION
**Pull request by ntrel**
Tweak error messages.
Use 'parameter' in messages instead of 'argument' for function parameter.
Add test for `mut` at call site.

### CODE REVIEW

**Comment by medvednikov** [comment]
What's wrong with the word "argument"?

Go uses it:

```
./prog.go:10:4: not enough arguments in call to foo
```

**Comment by ntrel** [comment]
@medvednikov Go's use there is correct. An argument is what is passed when the function is called. A parameter is what is declared in a function declaration.

**Comment by medvednikov** [comment]
Indeed, didn't know that. Thought they were synonyms.

**Comment by medvednikov** [comment]
Will have to rename all incorrect usages of "argument".

**Pull request merged**
