### PR TITLE
checker, parser, fmt: Fix visibility of anon struct in different modules.(fix #15763)

### LINKED ISSUE #15763: Anonymous struct declared inside another struct cannot be used by external module
Hello there!

V full version: V 0.3.1 f2f6ea5

I've defined a struct:

```v
module models

pub struct Settings {
	pub mut:
		user_settings struct {
			pub mut:
				default_active bool = true
				default_verified bool	
		}
}
```

And tried to use it:

```v
module tests

import models

fn test_settings_model_creation() {
    settings := models.Settings{
        user_settings: struct {
            default_verified: true
        }
    }
    assert settings.user_settings.default_verified == true
}
```

It gave me this error:

```v
src/tests/models_test.v:22:31: error: struct `models._VAnonStruct1` was declared as private to module `models`, so it can not be used inside module `tests`
   20 | fn test_settings_model_creation() {
   21 |     settings := models.Settings{
   22 |         user_settings: struct {
      |                               ^
   23 |             default_verified: true
   24 |         }
```

(I'm aware that I'm anti the recommended V pattern, I'm sorry for that)

One option would be to declare the **user_settings** struct, but, is there another option?

### PR DESCRIPTION
**Pull request by shove70**
1. Fix #15763
2. Add test

amod.v:
```v
module amod

pub struct Foo {
pub mut:
	bar struct  {
	pub mut:
		baz int
	}
}
```
main.v:
```v
import amod

fn main() {
	foo := amod.Foo{
		bar: struct {
			baz: 1
		}
	}
	assert foo.bar.baz == 1
}
```

output:

pass.

### CODE REVIEW

**Comment by shove70** [comment]
This may be a minor change to the language for the following reasons:

1. When the owner structure has a "pub" tag, and the fields of the structure are also within the scope of the "pub", the anonymous structure cannot be visible externally, which is difficult for users to understand

2. We directly assign the "pub" of the anonymous structure to true, which has no problem, because its visibility will be affected by the visibility of the owner structure and the field. Only when they are both "pub" can the anonymous structure be visible externally.

**Comment by shove70** [comment]
There may be a problem with fmt.

in main.v:
```v
module main

import amod  // ==> Formatted as "import anon_structs_visibility.amod"

fn main() {
	foo := amod.Foo{
		bar: struct {
			baz: 1
		}
	}
	println('foo.bar.baz == $foo.bar.baz')
}

```

This will cause compilation to fail:

```
vlib/v/checker/tests/modules/anon_structs_visibility/main.v:1:1: builder error: cannot import module "anon_structs_visibility.amod" (not found)

    1 | import anon_structs_visibility.amod

      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    2 |

    3 | fn main() {

```

**Comment by spytheman** [comment]
Hm, interesting, that formatting problem only happens on windows 🤔 .

**Comment by shove70** [comment]
> Hm, interesting, that formatting problem only happens on windows 🤔 .

Hi, spytheman, Your intuition should be very correct 👍 . After careful analysis, it is found that it should not be a problem of "fmt". It only clarifies some rules at several time points.

The problem may occur in the "builder", or in the "pub fn (b&Builder) find_module_path()", the difference between windows and posix is ignored.

I'll check it again.

**Comment by shove70** [comment]
```
C:\v>v run vlib\v\checker\tests\modules\anon_structs_visibility\main.v
foo.bar.baz == 1

C:\v>
```

I can't find any problems in the Windows environment. Everything works normally.
I can't seem to find the problem  😨 😰
Seek assistance...

**Comment by shove70** [comment]
@spytheman 
"builder" does have a small problem when processing paths according to rules. I have avoided it in this PR, and I will submit a new issue and process it.  :)
Thanks.

**Review by spytheman — APPROVED** [review]

**Comment by shove70** [comment]
> "builder" does have a small problem when processing paths according to rules. I have avoided it in this PR, and I will submit a new issue and process it. :)
> Thanks.

sorry, this issue has been put on hold since I forgot the step of reproduce.
thanks for feedback from issue: #18970, @Dracks

**Pull request merged**
