### PR TITLE
native: add additional operator support for float

### PR DESCRIPTION
**Pull request by lemoncmd**
includes unary `-` and `op=`

### CODE REVIEW

**Comment by penguindark** [comment]
I suggest to simplify the low level operation like `x % 8` and similar with bit operations,
more speed and more simple code.
Jus few examples:
`g.write8(0xb8 + int(reg) % 8)` => `g.write8(0xb8 + int(reg) &0x07)`
`offset := if j == size / 8 - 1 && size % 8 != 0 {` => `offset := if j == (size >> 3) - 1 && (size & 0x07) != 0 {`
`g.write8(rex_base + int(a) / 8 * 4 + int(b) / 8)` => `g.write8(rex_base + int(a)  >> 1 + int(b)  >> 3)`

**Comment by lemoncmd** [comment]
Just the current way is a lot cleaner and more maintainable for me.
`int(reg) / 8` and `int(reg) % 8` have the same operands and they are symmetrical operation.
About performance, yes, TCC doesn't optimise these operations (GCC and Clang does this even in -O0), so it can be slow in dev build of V. However, it is not so big problem now, so I chose the visibility.
(`int(a) / 8 * 4` is not `int(a) >> 1` but `int(a) >> 3 << 2`. It erases the lower 2 bits.)

**Comment by JalonSolov** [comment]
If this is for native output, it doesn't matter which C compilers optimize, and which don't - none of them will be called.

**Comment by lemoncmd** [comment]
(int(a) & 0xFFFFFFFC) >> 1

**Comment by lemoncmd** [comment]
not now.

**Comment by spytheman** [comment]
I agree with @lemoncmd here - the native backend is at the stage, where making it work has priority, micro optimizations can be done later, when we can gather data from profiles of compiling larger programs, like the compiler itself.

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by JalonSolov** [comment]
I don't disagree... I always work with the mantra "Make it work, first, then optimize."

I just usually do the most obvious optimizations up front.  <shrug>

**Pull request merged**
