### PR TITLE
builtin: Make all string.index methods return ?int

### PR DESCRIPTION
**Pull request by txgruppi**
The string type has come _index_ methods like (index, index_after, etc) and some return `int` and others return `?int`.

This MR makes all of them return `?int`.

The tests (`v test-all`) have beem updated to work with the changes but there are some tests that were skipped in my machine.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Looks like you missed a change in `vlib/os/environment.c.v`.

Other CI failure look more like connection failures on the Github side... push a fix for that file, and the checks should run again... hopefully successfully, this time.

**Comment by JalonSolov** [comment]
Build failure in vls showing up now.  It's customary to submit a PR there with a fix, mentioning this one needs to be merged first.  Otherwise, at least enter an issue in vls repo so they don't get "surprised" when this is merged.

**Comment by yuyi98** [comment]
The reason for reserving some returns of -1 is for performance reasons, avoiding optional for frequently called functions.

**Comment by JalonSolov** [comment]
Some benchmarking would tell us whether the change is "too slow" or not.

**Comment by txgruppi** [comment]
@JalonSolov I will take a look at `vls` tomorrow. Thanks.

@yuyi98 is performance _more important_ than consistency? The code below feels confusing and wrong.

```v
config_data = read_file('config.ini') ?
start_idx := config_data.index('DEVICE_ID=') ?
end_idx := config_data.index_after('\n', start_idx)
if end_idx == -1 {
  return error('failed to find variable end idx')
}
```

**Comment by yuyi98** [comment]
In Golang:
```vlang
func Index(s, substr string) int
    Index returns the index of the first instance of substr in s, or -1 if
    substr is not present in s.

func IndexAny(s, chars string) int
    IndexAny returns the index of the first instance of any Unicode code point
    from chars in s, or -1 if no Unicode code point from chars is present in s.

func IndexByte(s string, c byte) int
    IndexByte returns the index of the first instance of c in s, or -1 if c is
    not present in s.

func IndexFunc(s string, f func(rune) bool) int
    IndexFunc returns the index into s of the first Unicode code point
    satisfying f(c), or -1 if none do.

func IndexRune(s string, r rune) int
    IndexRune returns the index of the first instance of the Unicode code point
    r, or -1 if rune is not present in s. If r is utf8.RuneError, it returns the
    first instance of any invalid UTF-8 byte sequence.

func Join(elems []string, sep string) string
    Join concatenates the elements of its first argument to create a single
    string. The separator string sep is placed between elements in the resulting
    string.

func LastIndex(s, substr string) int
    LastIndex returns the index of the last instance of substr in s, or -1 if
    substr is not present in s.

func LastIndexAny(s, chars string) int
    LastIndexAny returns the index of the last instance of any Unicode code
    point from chars in s, or -1 if no Unicode code point from chars is present
    in s.

func LastIndexByte(s string, c byte) int
    LastIndexByte returns the index of the last instance of c in s, or -1 if c
    is not present in s.
```

**Comment by txgruppi** [comment]
@yuyi98 that's my point. Golang is consistent (at least).

**Comment by spytheman** [comment]
> @yuyi98 is performance more important than consistency? The code below feels confusing and wrong.

It depends - sometimes it does.

Is it difficult for you to convince us with benchmarks and measurements instead of rhetoric ?

**Comment by txgruppi** [comment]
@spytheman I will work on it as soon as work allows me hahah

**Comment by txgruppi** [comment]
Development continued in https://github.com/vlang/v/pull/13758

**Pull request closed without merging**
