### PR TITLE
checker: add checks and test for ~ operator

### PR DESCRIPTION
**Pull request by Delta456**
It now gives an error

```bash
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.27 a667538
Use Ctrl-C or `exit` to exit
>>> ~3.0
error: operator ~ only defined on int types
    1 | 
    2 | println(~3.0)
      |         ^
>>> 
```

### CODE REVIEW

**Comment by JalonSolov** [comment]
Your code checks .bit_not and .not, but your tests only test .bit_not twice.

**Comment by medvednikov** [comment]
Please change the error to

`operator ~ not defined on untyped float`

**Comment by Delta456** [comment]
Support checks for all types

```error
vlib/v/checker/tests/invert_other_types_bits_error.v:2:13: error: operator ~ only defined on untyped int 
    1 | fn main() {
    2 |     println(~3.0)
      |             ^
    3 |     println(~10.5)
    4 |     println(~'2')
vlib/v/checker/tests/invert_other_types_bits_error.v:3:13: error: operator ~ only defined on untyped int
    1 | fn main() {
    2 |     println(~3.0)
    3 |     println(~10.5)
      |             ^
    4 |     println(~'2')
    5 |     println(~[2, 4, 6])
vlib/v/checker/tests/invert_other_types_bits_error.v:4:13: error: operator ~ only defined on untyped int 
    2 |     println(~3.0)
    3 |     println(~10.5)
    4 |     println(~'2')
      |             ^
    5 |     println(~[2, 4, 6])
    6 | }
vlib/v/checker/tests/invert_other_types_bits_error.v:5:13: error: operator ~ only defined on untyped int
    3 |     println(~10.5)
    4 |     println(~'2')
    5 |     println(~[2, 4, 6])
      |             ^
    6 | }
```

**Comment by Delta456** [comment]
Is it good to merge?

**Comment by medvednikov** [comment]
Weird, I'm pretty sure I merged it 2 hours ago 

Anyway, merged now.

**Pull request merged**
