### PR TITLE
v: remove the automatic passing of structs with more than 8 fields by reference (too complex/unpredictable, with little benefit)

### LINKED ISSUE #17077: rule that all structures with more than 8 fields are always allocated on the heap should be removed
### Describe the feature

This rule sounds as strange as possible, and what is most terrible, it is IMPLICIT and NOT DESCRIBED in the documentation.

I don't see the point in this rule because the developer can decide YOURSELF when the structure should be allocated on the heap or on the stack.

The compiler SHOULD NOT show off one's "intelligence" and add IMPLICITIES.

### Use Case

-

### Proposed Solution

Remove this rule.

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.2 89aa695.865c0ea

### Environment details (OS name and version, etc.)

```
OS: macos, macOS, 13.0.1, 22A400
Processor: 10 cpus, 64bit, little endian, Apple M1 Pro
CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)

getwd: /Users/petrmakhnev/vlang-foundation/specification
vmodules: /Users/petrmakhnev/.vmodules
vroot: /Users/petrmakhnev/v
vexe: /Users/petrmakhnev/v/v
vexe mtime: 2023-01-22 21:48:01
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 89aa695.865c0ea

Git version: git version 2.37.1 (Apple Git-137.1)
Git vroot status: weekly.2022.50-266-g865c0ea8-dirty
.git/config present: true
thirdparty/tcc status: thirdparty-macos-arm64 173c526e
```

### PR DESCRIPTION
**Pull request by spytheman**
Fix #17077 .

### CODE REVIEW

**Review by Larpon — APPROVED** [review]

**Review by Delta456 — APPROVED** [review]

**Comment by walkingdevel** [comment]
@spytheman, thank you for your willingness to change complex and old features.  Let's make less unpredictable behavior.

**Comment by MatejMagat305** [comment]
I"m only asking:
this cause the compiler vlang have to be rewrite all place where is (mut some_complicate_struct) fn_n(...) to reference versions?

**Comment by JalonSolov** [comment]
Well, no, it will just pass those complicated structs on the stack.  You only need to change the code if you _want_ them to be passed as references, instead of it "magically" being done for you.

**Comment by JalonSolov** [comment]
Or, it other words, it will always be "pass by value" now, instead of sometimes pass by value, and sometimes pass by reference.  If you want pass by reference, you have to manually add the `&`.

**Comment by JalonSolov** [comment]
Any thoughts on finishing this one?

**Comment by JalonSolov** [comment]
`fn (f Foo)` would be pass by value, since it wouldn't be modifiable.  `fn (mut f Foo)` or `fn (&f foo)` would be pass by reference.

**Comment by spytheman** [comment]
> Any thoughts on finishing this one?

Yes, I am working on it.

**Review by KamkoAmoh — APPROVED** [review]

**Comment by spytheman** [comment]
Obsoleted by https://github.com/vlang/v/pull/22547 .

**Comment by larpon** [comment]
Thanks @yuyi98 !!! Great work!

**Pull request closed without merging**
