### PR TITLE
tetris.v: minor User Interface improvements

### PR DESCRIPTION
**Pull request by Sag-Dev**
I've improved the user interface of the tetris example. These are the changes I've done:

- I've added a gray (almost white, but less saturated) background to make it less eye straining. This also allows to differentiate the play area from the rest of the window when the user resizes it.
- I've added an upper bar that shows where the limit is, the player can see when he's going to lose clearer.
- I've added a background color to the pause and gameover texts.

This image resumes all the changes:
Screenshot from 2019-10-22 19-46-22

### CODE REVIEW

**Comment by medvednikov** [comment]
Thoughts on the gray background?

I prefer white to be honest.

**Comment by Sag-Dev** [comment]
I thought an almost white gray would be less tiring for the eyes and still get the same feeling. But I see why you prefer white, it looks cleaner indeed. Its other purpose was to make the play area stand out from the rest of the window.

I think the best solution could be just in the middle. I can set the play area background to white and the rest of the window to gray. Would you like that better?

**Comment by medvednikov** [comment]
Why is your window bigger than the playing area? It should be the same:

https://raw.githubusercontent.com/vlang/v/master/examples/tetris/screenshot.png

**Comment by Sag-Dev** [comment]
I manually resized it to see how it would look if the user decided to do so. Maybe blocking the resize could be a nice feature? Can this be achieved with the current OpenGL implementation of V?

**Comment by medvednikov** [comment]
yes, there's a glfw flag for that, will add it to `gg`

**Comment by medvednikov** [comment]
Done, `gg.Cfg.resizable`

Tetris window is no longer resizable

**Comment by Sag-Dev** [comment]
Perfect! That's much better then, I'll update my code, the background is unnecesary if window can't be resized.

**Pull request merged**
