### PR TITLE
vlib: fix ptrace signature

### PR DESCRIPTION
**Pull request by felipensp**
```
long ptrace(enum __ptrace_request request, pid_t pid,
                   void *addr, void *data);
```

### CODE REVIEW

**Comment by bstnbuck** [comment]
This is only correct for Linux based systems. Under MacOS, Solaris, ... `ptrace` is defined differently in each case.
For MacOS the following format (https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/ptrace.2.html):
```c
int ptrace(int request, pid_t pid, caddr_t addr, int data);
```
For Solaris the following (https://docs.oracle.com/cd/E36784_01/html/E36874/ptrace-3c.html):
```c
int ptrace(int request, pid_t pid, int addr, int data);
```

The `pid`, `addr` and `data` parameters for use in the `debugger_present` (https://github.com/vlang/v/blob/master/vlib/os/os_nix.c.v#L438) function are ignored (`PTRACE_TRACEME`). 

Nevertheless, this is an error if other parameters are used.
For each operating system the function should be specified precisely.

**Comment by felipensp** [comment]
> This is only correct for Linux based systems. Under MacOS, Solaris, ... `ptrace` is defined differently in each case. For MacOS the following format (https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/ptrace.2.html):
> 
> ```c
> int ptrace(int request, pid_t pid, caddr_t addr, int data);
> ```
> 
> For Solaris the following (https://docs.oracle.com/cd/E36784_01/html/E36874/ptrace-3c.html):
> 
> ```c
> int ptrace(int request, pid_t pid, int addr, int data);
> ```
> 
> The `pid`, `addr` and `data` parameters for use in the `debugger_present` (https://github.com/vlang/v/blob/master/vlib/os/os_nix.c.v#L438) function are ignored (`PTRACE_TRACEME`).
> 
> Nevertheless, this is an error if other parameters are used. For each operating system the function should be specified precisely.

Yes, but voidptr fits well with such int/void* alternance parameter. It just allow us to pass whatever.

image

**Comment by JalonSolov** [comment]
Yep.  voidptr allows us to bypass all that silly type checking that just gets in the way... oh, wait...

**Comment by medvednikov** [comment]
Yeah let's keep it safe and have valid versions for all systems, without voidptr.

**Pull request merged**
