### PR TITLE
parser: make [..] work

### PR DESCRIPTION
**Pull request by danieldaeschle**
Implements `x[..]`

### CODE REVIEW

**Comment by JalonSolov** [comment]
Why?  Would a simple `x := y` take care of it?  Why require the `[..]`?

**Comment by danieldaeschle** [comment]
it's shorthand for `x := y[1..]`. It's used to convert fixed arrays to dynamic arrays. @medvednikov

**Comment by JalonSolov** [comment]
I know what it is "shorthand" for, I just thought that assigning a fixed array to another variable cloned it.

**Comment by medvednikov** [comment]
I like how simple this was :)

**Comment by medvednikov** [comment]
@JalonSolov it does clone it. This is for converting from fixed arrays to dynamic arrays.

**Pull request merged**
