### PR TITLE
parser: fix match struct bug

### PR DESCRIPTION
**Pull request by danieldaeschle**
when (var is written capital):
```
type A = int | string
Abc = A(1)
match Abc {}
```
it resulted in an error because the compiler thought `Abc{}` is a struct

### CODE REVIEW

**Comment by medvednikov** [comment]
hm variables can't start with a capital letter, forgot to copy that check

so I don't think this is going to be needed once it's back?

**Comment by medvednikov** [comment]
Done, the check is back. Can you try again?

**Comment by danieldaeschle** [comment]
it works, but the position is wrong.

**Comment by danieldaeschle** [comment]
image

**Comment by danieldaeschle** [comment]
I will reopen it tomorrow because without this check a weird error can appear when using Type name as value (which is obviously wrong, but the resulting error is wrong too).

**Comment by danieldaeschle** [comment]
it gives a better error in case of:
```
match TypeName {}
```
`unknown TypeName` instead of `wrong }`

**Pull request merged**
