### PR TITLE
Make array reference great again

### PR DESCRIPTION
**Pull request by nsauzede**
Trivial fix to restore being able to store/use an array reference

Eg:
```v
struct ASTNode {
	val int
	ctx &[]ASTNode = voidptr(0)
}
mut arr := []ASTNode{}
println('len=${arr.len}')
mut ctx := &arr
ctx<<ASTNode{val:3}
println('len=${arr.len}')
for i:=0;i<arr.len;i++ {
	println('i=$i')
	println('${arr[i].val}')
}
```

### CODE REVIEW

**Comment by Delta456** [comment]
You have to solve this too:

```
vlib/v/parser/parse_type.v:229:2: error: unused variable: `is_array`
  227 |     language := p.parse_language()
  228 |     mut typ := table.void_type
  229 |     is_array := p.tok.kind == .lsbr
      |     ~~~~~~~~
  230 |     if p.tok.kind != .lcbr {
  231 |         pos := p.tok.position()
  ```
  😛

**Comment by nsauzede** [comment]
Thanks @Delta456 
Hopefully fixed now..

**Comment by nsauzede** [comment]
So basically, the seems to work fine, except for (sporadic ?) issues wrt. windows/mcos

Is it ok to review/merge this feature back again into V ?

**Comment by JalonSolov** [comment]
This should only be allowed in `unsafe` mode.

**Comment by nsauzede** [comment]
I just don't know rn how to implement that :-)
I must research a bit..

**Comment by medvednikov** [comment]
Why is this needed? I don't understand the example at all.

**Comment by nsauzede** [comment]
Well, I use this feature, for example, to push array elements to a "parent"'s node array, from one of its child node, while traversing a Tree :
https://github.com/nsauzede/mytstc/blob/main/tstc.v#L206
This is to replicate the design implemented in the original Javascript source code here :
https://github.com/jamiebuilds/the-super-tiny-compiler/blob/master/the-super-tiny-compiler.js#L885

**Comment by nsauzede** [comment]
macos CI hates me :-)

**Comment by medvednikov** [comment]
This check was introduced to not allow `fn foo(a &[]string) {}`

It should still remain. Perhaps it should be moved to `fn_decl()`

**Comment by nsauzede** [comment]
Ok.. I need to investigate how to implement that :-)

**Comment by medvednikov** [comment]
Also can you please provide an example that shows where this can be useful.

Your example works just fine with normal arrays.


```
struct ASTNode {
        val int
        ctx []ASTNode
}
mut arr := []ASTNode{}
println('len=${arr.len}')
arr<<ASTNode{val:3}
println('len=${arr.len}')
for i:=0;i<arr.len;i++ {
        println('i=$i')
        println('${arr[i].val}')
}
```

**Comment by nsauzede** [comment]
Lol, I give up.
Anyway I found a *workaround* : use a reference to an ASTNode, that now carries an array (of ASTNode refs FWIW) as a *common field*, which means we can't directly link to an arbitrary array ref
I close this

**Pull request closed without merging**
