### PR TITLE
ast, checker, cgen: fix generic fn with comptime for (fix #15905)

### LINKED ISSUE #15905: Comptime $For & $If with Generics / Type Inference
There are a few issues with inferring generic types from inside Comptime $If & $For.

This feature will be useful for lots of things especially encoding/decoding libs, I started a branch to fix it while developing this: https://github.com/vlang/msgpack. You can actually checkout that repo and try and run the examples/basic.v.

My branch (barely) gets it running by manually registering the concrete types for the `$if T is $Array {` and nested `for` in a similar way to how it is done with `$for`: https://github.com/joe-conigliaro/v/tree/comptime_selector_generic_call.
However this will fail in many cases with nested $for or $if, or when trying to infer a non generic type in one of those comptime branches as I'm manually setting the type currently. It does run the current examples/basic.v and quite a few other more complex cases. But it is a big mess and needs to be redone.

There is more to the issues I am forgetting here, I will add in notes as they come to mind.

We need to come up with a solid solution, as it simplifies code and allows much greater flexibility.

Here is a simple stand alone test case:

```go
fn fn_a<T>(data T, depth int, nl bool) {
    for _ in 0..depth {
        print('\t')
    }
    $if T.typ is int {
        print('int: $data')
    } $else $if T.typ is string {
        print('string: $data')
    } $else $if T is $Array {
        println('array: [')
        for i, elem in data {
            fn_a(elem, depth+1, false)
            if i < data.len-1 {
                print(', ')
            }
            println('')
        }
        print(']')
    } $else $if T is $Map {
        println('map: {')
        for key, value in data {
            print('\t(key) ')
            fn_a(key, depth, false)
            print(' -> (value) ')
            fn_a(value, depth, true)
        }
        print('}')
    } $else $if T is $Struct {
        println('struct $T.name: {')
        $for field in T.fields {
            print('\t($field.name) ')
            fn_a(data.$(field.name), depth, true)
            // uncommenting either of these lines will cause a C error in my branch as the type is
            // set manually to the $for field type, it needs to be fixed to infer the type correctly.
            // fn_a([1,2,3,4], depth+1, true)
            // fn_a(0.111, depth+1, true)
        }
        print('}')
    }
    if nl {
        println('')
    }
}

struct StructA {
    field_a int
    field_b string
}

fn main() {
    fn_a(111, 0, true)
    fn_a('hello', 0, true)
    fn_a(['a', 'b', 'c', 'd'], 0, true)
    fn_a({'one': 1, 'two': 2}, 0, true)
    fn_a(StructA{field_a: 111, field_b: 'vlang'}, 0, true)
}
```
Output using my branch listed above (does not compile on master):
```sh
int: 111
string: hello
array: [
	string: a,
	string: b,
	string: c,
	string: d
]
map: {
	(key) string: one -> (value) int: 1
	(key) string: two -> (value) int: 2
}
struct StructA: {
	(field_a) int: 111
	(field_b) string: vlang
}
```
Have you got any ideas about this @yuyi98 ?

Some other notes I would like to add is we have `$if T.typ is int` and also `$if T is $Array` and they are implemented in two different ways. Perhaps we should have `$if T.typ is i16` / `$if T.typ is []u8` and `$if T.kind is (u)integer` / `$if T.kind is array` / `$if T.kind is map`, and they could also share the same implementation, instead of needing two different ones. This is just an idea in either case, whatever the syntax is, it would be nice if the code that handles these situations was merged together.

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix generic fn with comptime for (fix #15905).

- Fix generic fn with comptime for.
- Add test.

```v
fn fn_a<T>(data T, depth int, nl bool) {
	for _ in 0 .. depth {
		print('\t')
	}
	$if T.typ is int {
		print('int: $data')
	} $else $if T.typ is string {
		print('string: $data')
	} $else $if T is $Array {
		println('array: [')
		for i, elem in data {
			fn_a(elem, depth + 1, false)
			if i < data.len - 1 {
				print(', ')
			}
			println('')
		}
		print(']')
	} $else $if T is $Map {
		println('map: {')
		for key, value in data {
			print('\t(key) ')
			fn_a(key, depth, false)
			print(' -> (value) ')
			fn_a(value, depth, true)
		}
		print('}')
	} $else $if T is $Struct {
		println('struct $T.name: {')
		$for field in T.fields {
			print('\t($field.name) ')
			fn_a(data.$(field.name), depth, true)
			// uncommenting either of these lines will cause a C error in my branch as the type is
			// set manually to the $for field type, it needs to be fixed to infer the type correctly.
			fn_a(['1', '2', '3', '4'], depth + 1, true)
			fn_a(0.111, depth + 1, true)
			fn_a('hello', depth + 1, true)
		}
		print('}')
	}
	if nl {
		println('')
	}
}

struct StructA {
	field_a int
	field_b string
}

fn main() {
	fn_a(111, 0, true)
	fn_a('hello', 0, true)
	fn_a(['a', 'b', 'c', 'd'], 0, true)
	fn_a({
		'one': 1
		'two': 2
	}, 0, true)
	fn_a(StructA{ field_a: 111, field_b: 'vlang' }, 0, true)
}

PS D:\Test\v\tt1> v run .
int: 111
string: hello
array: [
        string: a, 
        string: b, 
        string: c, 
        string: d
]
map: {
        (key) string: one -> (value) int: 1
        (key) string: two -> (value) int: 2
}
struct StructA: {
        (field_a) int: 111
        array: [
                string: 1, 
                string: 2, 
                string: 3, 
                string: 4
]

        string: hello
        (field_b) string: vlang
        array: [
                string: 1, 
                string: 2, 
                string: 3, 
                string: 4
]

        string: hello
}
```

### CODE REVIEW

**Comment by joe-conigliaro** [comment]
Thanks you @yuyi98

**Comment by yuyi98** [comment]
There are issues with `array` and `map` in `for in` when using multi types, I'm trying to figure it out.

**Comment by joe-conigliaro** [comment]
> There are issues with `array` and `map` in `for in` when using multi types, I'm trying to figure it out.

Is it something to do with needing to set the value type?

**Comment by yuyi98** [comment]
Yes, This is because the type is specified in the check phase.

**Comment by spytheman** [comment]
Is it good to merge as it is for now?

**Comment by joe-conigliaro** [comment]
@yuyi98, in checker, and cgen in for I think you can just set the node.value_type to `table.value_tyle(value_type)` take a look here: https://github.com/vlang/v/compare/master...joe-conigliaro:v:comptime_selector_generic_call where `value_type()  is used.

I would also like to try and run the msgpack demo with this branch, and also some more complicated examples I had with algorand.

**Comment by joe-conigliaro** [comment]
Hi @yuyi98 , if you get a chance could you please clone `https://github.com/v/msgpack` and try running `examples/basic.v` with this branch, I am getting C errors. I guess my stand alone test was not so good :( sorry

**Comment by yuyi98** [comment]
@joe-conigliaro  Ok, I'll try.

**Comment by joe-conigliaro** [comment]
Thanks @yuyi98

**Comment by yuyi98** [comment]
```v
module main

import msgpack
import time

pub struct TestStructA {
	field_a int            [codec: 'codecdata1']
	field_b string         [codec: 'codecdata2']
	field_c TestStructB
	field_d []string
	field_e map[string]int
	// field_f map[string]TestStructB
	// field_g []TestStructB
	field_h time.Time
}

pub struct TestStructB {
	field_a int    [codec: 'codecdata1']
	field_b string [codec: 'codecdata2']
}

fn main() {
	ts := TestStructA{
		field_a: 111
		field_b: 'TestStructA.field_b'
		field_c: TestStructB{
			field_a: 222
			field_b: 'TestStructB.field_b'
		}
		field_d: ['apple', 'banana', 'coconut', 'durian']
		field_e: {
			'one':   1
			'two':   2
			'three': 3
			'four':  4
		}
		// field_f: {
		// 	'a': TestStructB{
		// 		field_a: 1
		// 		field_b: 'field_f.a.TestStructB.field_b'
		// 	},
		// 	'b': TestStructB{
		// 		field_a: 2
		// 		field_b: 'field_f.b.TestStructB.field_b'
		// 	}
		// }
		// field_g: [
		// 	TestStructB{
		// 		field_a: 1
		// 		field_b: 'field_g.b.TestStructB.field_b'
		// 	},
		// 	TestStructB{
		// 		field_a: 2
		// 		field_b: 'field_g.b.TestStructB.field_b'
		// 	}
		// ]
		field_h: time.now()
	}
	
	// encode data
	encoded := msgpack.encode<TestStructA>(ts)
	println('ts encoded:')
	println(encoded.hex())
	
	// decode bytes
	println('ts decoded:')
	mut decoder := msgpack.new_decoder()
	decoder.decode(encoded) or {
		panic('error decoding: $err')
	}
}

PS D:\Test\v\tt1> v run .
ts encoded:
86aa636f6465636461746131d20000006faa636f6465636461746132b354657374537472756374412e6669656c645f62a76669656c645f6382aa636f6465636461746131d2000000deaa636f6465636461746132b354657374537472756374422e6669656c645f62a76669656c645f6494a56170706c65a662616e616e61a7636f636f6e7574a664757269616ea76669656c645f6584a36f6e65d200000001a374776fd200000002a57468726565d200000003a4666f7572d200000004a76669656c645f68d6ff633576b4
ts decoded:
map container_len: 42
string: codecdata1 - len: 10
int: 111
string: codecdata2 - len: 10
string: TestStructA.field_b - len: 19
string: field_c - len: 7
map container_len: 42
string: codecdata1 - len: 10
int: 222
string: codecdata2 - len: 10
string: TestStructB.field_b - len: 19
string: field_d - len: 7
array
string: apple - len: 5
string: banana - len: 6
string: coconut - len: 7
string: durian - len: 6
string: field_e - len: 7
map container_len: 35
string: one - len: 3
int: 1
string: two - len: 3
int: 2
string: three - len: 5
int: 3
string: four - len: 4
int: 4
string: field_h - len: 7
decode_ext - container len: 4
time: 2022-09-29 10:43:00
```

**Comment by joe-conigliaro** [comment]
> `field_f map[string]TestStructB` and `field_g []TestStructB` still have problem, others is ok.
> 
> ```v
> module main
> 
> import msgpack
> import time
> 
> pub struct TestStructA {
> 	field_a int            [codec: 'codecdata1']
> 	field_b string         [codec: 'codecdata2']
> 	field_c TestStructB
> 	field_d []string
> 	field_e map[string]int
> 	// field_f map[string]TestStructB
> 	// field_g []TestStructB
> 	field_h time.Time
> }
> 
> pub struct TestStructB {
> 	field_a int    [codec: 'codecdata1']
> 	field_b string [codec: 'codecdata2']
> }
> 
> fn main() {
> 	ts := TestStructA{
> 		field_a: 111
> 		field_b: 'TestStructA.field_b'
> 		field_c: TestStructB{
> 			field_a: 222
> 			field_b: 'TestStructB.field_b'
> 		}
> 		field_d: ['apple', 'banana', 'coconut', 'durian']
> 		field_e: {
> 			'one':   1
> 			'two':   2
> 			'three': 3
> 			'four':  4
> 		}
> 		// field_f: {
> 		// 	'a': TestStructB{
> 		// 		field_a: 1
> 		// 		field_b: 'field_f.a.TestStructB.field_b'
> 		// 	},
> 		// 	'b': TestStructB{
> 		// 		field_a: 2
> 		// 		field_b: 'field_f.b.TestStructB.field_b'
> 		// 	}
> 		// }
> 		// field_g: [
> 		// 	TestStructB{
> 		// 		field_a: 1
> 		// 		field_b: 'field_g.b.TestStructB.field_b'
> 		// 	},
> 		// 	TestStructB{
> 		// 		field_a: 2
> 		// 		field_b: 'field_g.b.TestStructB.field_b'
> 		// 	}
> 		// ]
> 		field_h: time.now()
> 	}
> 	
> 	// encode data
> 	encoded := msgpack.encode<TestStructA>(ts)
> 	println('ts encoded:')
> 	println(encoded.hex())
> 	
> 	// decode bytes
> 	println('ts decoded:')
> 	mut decoder := msgpack.new_decoder()
> 	decoder.decode(encoded) or {
> 		panic('error decoding: $err')
> 	}
> }
> 
> PS D:\Test\v\tt1> v run .
> ts encoded:
> 86aa636f6465636461746131d20000006faa636f6465636461746132b354657374537472756374412e6669656c645f62a76669656c645f6382aa636f6465636461746131d2000000deaa636f6465636461746132b354657374537472756374422e6669656c645f62a76669656c645f6494a56170706c65a662616e616e61a7636f636f6e7574a664757269616ea76669656c645f6584a36f6e65d200000001a374776fd200000002a57468726565d200000003a4666f7572d200000004a76669656c645f68d6ff633576b4
> ts decoded:
> map container_len: 42
> string: codecdata1 - len: 10
> int: 111
> string: codecdata2 - len: 10
> string: TestStructA.field_b - len: 19
> string: field_c - len: 7
> map container_len: 42
> string: codecdata1 - len: 10
> int: 222
> string: codecdata2 - len: 10
> string: TestStructB.field_b - len: 19
> string: field_d - len: 7
> array
> string: apple - len: 5
> string: banana - len: 6
> string: coconut - len: 7
> string: durian - len: 6
> string: field_e - len: 7
> map container_len: 35
> string: one - len: 3
> int: 1
> string: two - len: 3
> int: 2
> string: three - len: 5
> int: 3
> string: four - len: 4
> int: 4
> string: field_h - len: 7
> decode_ext - container len: 4
> time: 2022-09-29 10:43:00
> ```

Thanks @yuyi98 for your work! Greatly appreciated! Similar problem I was having with that too.

**Comment by yuyi98** [comment]
@joe-conigliaro   Thanks!!! I'll try my best to solve it.

**Comment by joe-conigliaro** [comment]
@yuyi98 the problem is with each iteration/generation of the comptime for field it needs to use the correct types for the current iteration it's on.  Actually uncommenting either `field_e map[string]int` or `field_f map[string]TestStructB` will work but not both at once since it will get stuck using the type from the previous iteration.

**Comment by yuyi98** [comment]
I have an idea, using `g.for_in_any_key_type` and `g.for_in_any_val_type` to solve it. now can work on array.

**Comment by joe-conigliaro** [comment]
try adding more fields afterwards with different array types and see if it works or is trying to use type from previous field?

**Comment by yuyi98** [comment]
Now adding more fields of different array types can work.

**Comment by joe-conigliaro** [comment]
Thanks @yuyi98, I have some more complex tests which are failing currently, let's keep this PR open for a bit. I will try with your new fixes.

**Comment by yuyi98** [comment]
It's ok now.
```v
module main

import msgpack
import time

pub struct TestStructA {
	field_a int            [codec: 'codecdata1']
	field_b string         [codec: 'codecdata2']
	field_c TestStructB
	field_d []string
	field_e map[string]int
	field_f map[string]TestStructB
	field_g []TestStructB
	field_h time.Time
	field_i []int
}

pub struct TestStructB {
	field_a int    [codec: 'codecdata1']
	field_b string [codec: 'codecdata2']
}

fn main() {
	ts := TestStructA{
		field_a: 111
		field_b: 'TestStructA.field_b'
		field_c: TestStructB{
			field_a: 222
			field_b: 'TestStructB.field_b'
		}
		field_d: ['apple', 'banana', 'coconut', 'durian']
		field_e: {
			'one':   1
			'two':   2
			'three': 3
			'four':  4
		}
		field_f: {
			'a': TestStructB{
				field_a: 1
				field_b: 'field_f.a.TestStructB.field_b'
			},
			'b': TestStructB{
				field_a: 2
				field_b: 'field_f.b.TestStructB.field_b'
			}
		}
		field_g: [
			TestStructB{
				field_a: 1
				field_b: 'field_g.b.TestStructB.field_b'
			},
			TestStructB{
				field_a: 2
				field_b: 'field_g.b.TestStructB.field_b'
			}
		]
		field_h: time.now()
		field_i: [1, 2, 3, 4]
	}
	
	// encode data
	encoded := msgpack.encode<TestStructA>(ts)
	println('ts encoded:')
	println(encoded.hex())
	
	// decode bytes
	println('ts decoded:')
	mut decoder := msgpack.new_decoder()
	decoder.decode(encoded) or {
		panic('error decoding: $err')
	}
}

PS D:\Test\v\tt1> v run .
ts encoded:
89aa636f6465636461746131d20000006faa636f6465636461746132b354657374537472756374412e6669656c645f62a76669656c645f6382aa636f6465636461746131d2000000deaa636f6465636461746132b354657374537472756374422e6669656c645f62a76669656c645f6494a56170706c65a662616e616e61a7636f636f6e7574a664757269616ea76669656c645f6584a36f6e65d200000001a374776fd200000002a57468726565d200000003a4666f7572d200000004a76669656c645f6682a16182aa636f6465636461746131d200000001aa636f6465636461746132bd6669656c645f662e612e54657374537472756374422e6669656c645f62a16282aa636f6465636461746131d200000002aa636f6465636461746132bd6669656c645f662e622e54657374537472756374422e6669656c645f62a76669656c645f679282aa636f6465636461746131d200000001aa636f6465636461746132bd6669656c645f672e622e54657374537472756374422e6669656c645f6282aa636f6465636461746131d200000002aa636f6465636461746132bd6669656c645f672e622e54657374537472756374422e6669656c645f62a76669656c645f68d6ff6335d509a76669656c645f6994d200000001d200000002d200000003d200000004
ts decoded:
map container_len: 42
string: codecdata1 - len: 10
int: 111
string: codecdata2 - len: 10
string: TestStructA.field_b - len: 19
string: field_c - len: 7
map container_len: 42
string: codecdata1 - len: 10
int: 222
string: codecdata2 - len: 10
string: TestStructB.field_b - len: 19
string: field_d - len: 7
array
string: apple - len: 5
string: banana - len: 6
string: coconut - len: 7
string: durian - len: 6
string: field_e - len: 7
map container_len: 35
string: one - len: 3
int: 1
string: two - len: 3
int: 2
string: three - len: 5
int: 3
string: four - len: 4
int: 4
string: field_f - len: 7
map container_len: 33
string: a - len: 1
map container_len: 42
string: codecdata1 - len: 10
int: 1
string: codecdata2 - len: 10
string: field_f.a.TestStructB.field_b - len: 29
string: b - len: 1
map container_len: 42
string: codecdata1 - len: 10
int: 2
string: codecdata2 - len: 10
string: field_f.b.TestStructB.field_b - len: 29
string: field_g - len: 7
array
map container_len: 42
string: codecdata1 - len: 10
int: 1
string: codecdata2 - len: 10
string: field_g.b.TestStructB.field_b - len: 29
map container_len: 42
string: codecdata1 - len: 10
int: 2
string: codecdata2 - len: 10
string: field_g.b.TestStructB.field_b - len: 29
string: field_h - len: 7
decode_ext - container len: 4
time: 2022-09-29 17:25:29
string: field_i - len: 7
array
int: 1
int: 2
int: 3
int: 4
```

**Comment by joe-conigliaro** [comment]
I found another issue, if you add a new field eg `field_j []f64` and run it it gives C error:
```sh
/tmp/v_501/basic.14350075535600201825.tmp.c:19035:4: error: implicit declaration of function 'msgpack__Encoder_encode_T_f64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        msgpack__Encoder_encode_T_f64(e, value);
                        ^
 ```
 This seems to be the issue with my more complex tests also

**Comment by yuyi98** [comment]
Ok, I'll try to fix it.

**Comment by spytheman** [comment]
@joe-conigliaro what do you think, can it be merged now?

I think it is good to merge it, even if there are other problems - they can be fixed in other PRs, and in the mean time, users will be able to enjoy the improved V, much more easily.

**Comment by joe-conigliaro** [comment]
Hey sorry I was sleeping, lets merge this, excellent! Thanks @yuyi98, looks so far that everything is working great, seems to be running with my local algorand stuff too.

**Comment by danieldaeschle** [comment]
I like the `T is $Struct` but I don't like the syntax. Do we have alternatives?

**Comment by danieldaeschle** [comment]
Can we make Json 2 work with that now?

**Pull request merged**
