### PR TITLE
native: increase support for `ast.Alias` and `ast.TypeOf`

### PR DESCRIPTION
**Pull request by Spydr06**
This PR adds support for more types in `typeof()` expressions and fixes bugs with `ast.Alias` not being resolved everywhere.
Alongside are other smaller refactors

### <samp>🤖 Generated by Copilot at 583e0a4</samp>

This pull request enhances the native code generation for the amd64 and arm64 architectures, adds and updates tests for various expressions and types, and refactors some common and utility functions. It also fixes some bugs and improves the readability and consistency of the code.

### <samp>🤖 Generated by Copilot at 583e0a4</samp>

*  Move `byt` function to `vlib/v/gen/native/gen.v` and add `stack_depth` field to `Gen` and `Amd64` structs to track stack balance ([link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cL115-L119), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R234-R238), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R44), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cR1007), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cR1017), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cR3997), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cR4013), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R996), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5R1003-R1006))
* Extract `fp_infix_expr` function from `infix_expr` function in `vlib/v/gen/native/amd64.v` and use `unwrap` and `match` to handle alias types and different function names ([link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cR2825-R2876), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-058ff896cbdc6c11f12aa1310120c759dffdd567fa79c0c4ed7cfc3a7168f07cL2841-R2998), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-2c72949f2e9639a908055366823bfe6f73ef841f6c0e5f1f1bc15d8e72d73f66L19-R37))
* Implement `trap` function for `Arm64` struct in `vlib/v/gen/native/arm64.v` to generate breakpoint instruction ([link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-adbd41fc3b79a905013a0687dac2fa118ea4d8f000879c62dd3a785296ac56a9L388-R389))
* Add `local_var_ident` function to `vlib/v/gen/native/expr.v` to handle local variable identifiers and extract it from `expr` function ([link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-2c72949f2e9639a908055366823bfe6f73ef841f6c0e5f1f1bc15d8e72d73f66L44-R48), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-2c72949f2e9639a908055366823bfe6f73ef841f6c0e5f1f1bc15d8e72d73f66R116-R118), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-2c72949f2e9639a908055366823bfe6f73ef841f6c0e5f1f1bc15d8e72d73f66R125-R147))
* Add support for `ast.TypeOf` node to `expr` function in `vlib/v/gen/native/expr.v` and handle different kinds of types in `gen_typeof_expr` function ([link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-2c72949f2e9639a908055366823bfe6f73ef841f6c0e5f1f1bc15d8e72d73f66R7), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-2c72949f2e9639a908055366823bfe6f73ef841f6c0e5f1f1bc15d8e72d73f66R116-R118), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-2c72949f2e9639a908055366823bfe6f73ef841f6c0e5f1f1bc15d8e72d73f66L216-R283))
* Modify `is_register_type` function in `vlib/v/gen/native/gen.v` to handle alias types and add `is_fp_type` function ([link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-fb95eb5c46e6f4c50431d038e29002dc61d2e5ef6d9f8eca5af1c5e71b0aa8f5L738-R754))
* Add new test cases to `vlib/v/gen/native/tests/assign.vv` and `vlib/v/gen/native/tests/typeof.vv` and update expected output in `vlib/v/gen/native/tests/assign.vv.out` and `vlib/v/gen/native/tests/typeof.vv.out` ([link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-9a9f38d5c3ea6ae04def3b4bb41b841c81d077fdf692557b96d076527847ea46R4-R5), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-9a9f38d5c3ea6ae04def3b4bb41b841c81d077fdf692557b96d076527847ea46L28-R45), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-1789dbfdd5a083b094bb2537aef38f7a7780aaeefc13806e5a9b340917a90df0L2-R4), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-e6ae1e6b4b80014e1a352d0bef5ca88924dc1ba5e501d625486ef7d40cc68446L1-R11), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-e6ae1e6b4b80014e1a352d0bef5ca88924dc1ba5e501d625486ef7d40cc68446R17-R18), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-e6ae1e6b4b80014e1a352d0bef5ca88924dc1ba5e501d625486ef7d40cc68446L14-R85), [link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-c715857450a3b54f1602119bf5644b912944b83006b081399122ce166d96f313R5-R21))
* Comment out two test cases in `vlib/v/gen/native/tests/struct.vv` that are not working yet ([link](https://github.com/vlang/v/pull/18722/files?diff=unified&w=0#diff-af025e4a9f395ee43e02d32c0fad9e0715ef84044118e2cf31b5292a3b3268b3L107-R108))

### CODE REVIEW

**Comment by Spydr06** [comment]
For some reason, the new `stack_depth` assertion fails on macos for `main()`. Windows and Linux both pass and I can't find any macos-only code that could cause this behavior.
Other than that, macos works perfectly fine, so I don't think it's an issue rn

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by spytheman** [comment]
> For some reason, the new stack_depth assertion fails on macos for main(). Windows and Linux both pass and I can't find any macos-only code that could cause this behavior.

I'll have a look on my m1 asap.

**Comment by Spydr06** [comment]
> I'll have a look on my m1 asap.
I doubt that would help anything, bc the arm64 platform isn't implemented yet. You'd need a x86 mac (or emulate one)

**Pull request merged**
