### PR TITLE
create math.mathutil with generic `min`, `max` and `abs` functions

### PR DESCRIPTION
**Pull request by serkonda7**
vls PR: https://github.com/vlang/vls/pull/84

### CODE REVIEW

**Comment by serkonda7** [comment]
@spytheman I found that all the functions for f32 and f64 are already in `builtin/float.v`.
Should I remove them here and?

**Comment by medvednikov** [comment]
util is a bad module name, too common

mathutil maybe

also we can just make it generic

**Comment by spytheman** [comment]
> `builtin/float.v`

I am not sure about that... 
The builtin ones pub `f32_abs` etc, should stay for now imho, since generics can not be used in `builtin`, and it is out of scope of this PR. `arrays` does not have this limitation, so they can and probably should be generic to save code and reduce chances of bugs.

@medvednikov what do you think?

**Comment by Gladear** [comment]
Is there a  reason not to add them directly in `math` ? JS, Java, C# and Go all have `math.min` (or their case-adapted equivalent).
Also, I think it can be very handy to make them take a variable number of arguments (well, `min` and `max`, not `abs` 😄), so it can be easily used on arrays for example (want the minimum value of an array ? `min := math.min(...array)`, so easy)

**Comment by serkonda7** [comment]
The reason they have their own submodule is the huge size and libc dependency of `math`.

But the variable argument count sounds great :+1:

**Comment by Gladear** [comment]
What if we remove the `math.h` dependency and reimplement it in V ? 😏

**Comment by ulises-jeremias** [comment]
> What if we remove the `math.h` dependency and reimplement it in V ? 😏

@Gladear it is already done on vsl.vmath. you should take a look at there. It also has some limitations on some architectures, so it is important to make it optional. We can talk about that some day if you want to contribute to VSL to implement that approach with me

**Comment by serkonda7** [comment]
@Gladear actually these are already in `arrays` https://modules.vlang.io/arrays.html#max

**Pull request merged**
