### PR TITLE
added mingw-w64 note to docs.md

### PR DESCRIPTION
**Pull request by chipnetics**
Added a quick note on required mingw gcc package install for cross-compilation.

### CODE REVIEW

**Comment by JalonSolov** [comment]
V tells you what to install if it can't find it.  :-)

**Comment by chipnetics** [comment]
I thought it did too, but on a new machine I only got `builder error: sh: 1: x86_64-w64-mingw32-gcc: not found` which also is different description than `gcc-mingw-w64-x86-64 (the name of the apt package)`

Looks like this user had the same experience as well....
https://discord.com/channels/592103645835821068/592294828432424960/989107904495898625

**Comment by JalonSolov** [comment]
Unfortunately, you either need to make the instruction more general, or you need to include installation instructions for all the package managers, with all the name variations in the different package systems.

**Comment by spytheman** [comment]
While distros do differ in their naming, I do think that mentioning the package name on Debian distros is a good start, and can help hint users of other distros what should they do better than the V error message (which mentions a different name).

**Pull request merged**
