### PR TITLE
Add exists method to map

### PR DESCRIPTION
**Pull request by ielijose**
Add **exists** method to map.

```
if m.exists(key){
    m[key] = m[key] + 1
}else{
    m[key] = 1
}

### CODE REVIEW

**Comment by LouCle** [comment]
I'd have checked if the key was even in the map to begin with, but unset keys returns a 0, which doesn't allow you to differentiate between set and unset keys.

**Comment by AurelienFT** [comment]
Maybe we should add a unset which delete an element ?

**Comment by ielijose** [comment]
> Maybe we should add a unset which delete an element ?

I'll try to add it.

**Comment by elimisteve** [comment]
Maybe `exists` should be called `has_key` so it's 100% clear that it's checking for the existence of a key, not a value?

**Comment by ntrel** [comment]
Yeah, has_key (or has) is a better name.

**Comment by ntrel** [comment]
I think a way of getting an optional value is more general. To see if the map has the key, the user would check the optional != none. The example becomes:

if val := m.get(key){
    m[key] = val + 1
}else{
    m[key] = 1
} 

(Here I've invented the inverse of the optional or construct). In the first branch, only one key lookup is made instead of two, which is more efficient.

**Comment by ntrel** [comment]
See #244 for more on using optional values for maps.

**Pull request merged**
