### PR TITLE
cgen: fix mut args in go function

### PR DESCRIPTION
**Pull request by emily33901**

### CODE REVIEW

**Comment by medvednikov** [comment]
It's crashing the test system.

**Comment by emily33901** [comment]
Dont think that was just me though :thinking:

**Comment by UweKrueger** [comment]
@emily33901 the PR definitely causes compilation crashes because the intermediate C file contains a declaration of a function with return type `&void*`...

Anyway, even if it would compile, there are a lot of questions that must be answered before a goroutine may have a mutable argument:
- Who is responsible for freeing memory? Or asked the other way round: When the calling function returns it usually frees the memory used by its variables. But then the goroutine might still be running and trying to access the variable.
- There is a race condition when accessing the mutable variable from the calling function and from the goroutine at the same time.

There are a couple of ways to address these issues in other programming languages: Garbage collector in `Go`, mutexes, atomics, ..., but they do not really fit for `v`.

I personally like the paradigm used by C++'s `std::unique_ptr` - a pointer that can only be owned by one function. The object pointed to by this type of pointer is allocated on the heap and ownership is transferred when passing a `std::unique_ptr` to another function which is than responsible for freeing the memory. Since the calling function cannot access the object any more (C++ compilers don't check this (!), but it doesn't work), there can't be any race conditions. Passing objects thru channels could use the same approach.

**Comment by emily33901** [comment]
(Putting aside the memory management issues (mainly becuase the `go`'d function will always retrive a copy of the args whether they are `mut`'d or not).

<hr>

Right now calling `go f(x, y, z)` will make copies of all the arguments and then unpack them in the new thread and call `f(...)` But if I wanted to call functions that require a `mut` variable then I would need to pass it as mut, otherwise its an error. 

However that means that the functions declaration (in C) changes from taking a struct by value to taking it by pointer.

E.g.

```go
import time

struct Test {
	a int
	b int
}

fn f(x Test) {
	println('$x.a $x.b')
}

fn main() {
	go f(Test { 5, 5 })
	time.sleep(5)
}
```

will generate the following C code (trimmed for brevity etc...)
```c
typedef struct thread_arg_f {
	Test arg1;
} thread_arg_f;
void* f_thread_wrapper(thread_arg_f *arg);

// V gowrappers:
void* f_thread_wrapper(thread_arg_f *arg) {
	f(arg->arg1);
	return 0;
}

void f(Test x) {
	println(_STR("%"PRId32"\000 %"PRId32"", 2, x.a, x.b));
}
```

However if the variables passed to the function changes to mut (`f(mut x Test)`) Then we can see that the generated code changes to (Once again trimmed for brevity etc...):
```c
typedef struct thread_arg_f {
	Test arg1;
} thread_arg_f;
void* f_thread_wrapper(thread_arg_f *arg);

// V gowrappers:
void* f_thread_wrapper(thread_arg_f *arg) {
	f(arg->arg1);
	return 0;
}

void f(Test* x) {
	println(_STR("%"PRId32"\000 %"PRId32"", 2, x->a, x->b));
}
```

As you can see now f takes a pointer to x (becuase that parameter is `mut`), however the thread wrapper passes `arg->arg1` which is a `Test` (not a `Test*`).

Without this patch programs that have `go` functions that take mut arguments will not compile (and quite rightly too, You should not under any circumstances be able to coerce a struct into a pointer).

That is what this PR is trying to fix. Its not concerning itself with the semantics of the language - I just want my copied variables (remember they are copied either way) to be allowed to be mutable so that I can call the mutable functions on them.

My test case is from my [vlang-net](https://github.com/emily33901/vlang-net) repository. If you either look at `tcp_test.v` in the root directory or at one of the examples in the `examples` folder the use case there is that I want to pass a new tcp connection from one thread to another and then set its timeout.

<hr>


Large paragraph aside its probably better to just make it an error to `go` call a function with mutable args and then just coerce the mut with a copy of the by-value argument in the function (This avoids having to make a decision about the memory management thing at the moment (becuase thats a whole different problem)).

**Comment by UweKrueger** [comment]
> Large paragraph aside its probably better to just make it an error to `go` call a function with mutable args ...

Agreed!

**Pull request closed without merging**
