### PR TITLE
vlib/math: add robust_equal

### PR DESCRIPTION
**Pull request by hazohelet**
This PR adds `robust_equal(a, b f64) bool` to math module.
This function evaluates equality considering *machine epsilon*.
The number `2.2204460492503131e-16` is based on Python `sys.float_info.epsilon`

In mathematical contexts, evaluating the equality of two floating-point numbers `d1` and `d2` using `d1 == d2` usually gives rise to problems.
Without this PR, `test_gamma()` in math_test.v causes an error on Android.
Furthermore, the following source code shows "0" at least in my OS X laptop environment, which is rather a C problem than a V problem.
```
mut a := f64(1)
b := f64(1)
a += 0.001
a -= 0.001

print(a == b)
// => 0
```

### CODE REVIEW

**Comment by medvednikov** [comment]
@hazohelet I'm considering not allowing `float1 == float2` at all.

There's already `f64.eq()` for this.

**Comment by hazohelet** [comment]
@medvednikov I didn't know that f64 builtin functions were written in int.v
Still, the implementation of `f64.eq()` was not correct I created another PR that fixes it.
https://github.com/vlang/v/pull/2134

**Comment by dumblob** [comment]
>I'm considering not allowing float1 == float2 at all.

I'd actually do it vice versa:

1. `float1 == float2` would be compiled to epsilon comparison
2. `float1.eqbit( float 2)` would do bitwise comparison (which is sometimes needed)

This way the `==` operator would do what the user expects.

Btw. *V* there is sometimes the need to change *epsilon* to something else in runtime - would *V* support that instead of hardcoding 'C.DBL_EPSILON`?

**Comment by dumblob** [comment]
@medvednikov what do you think about the "vice versa" semantics?

**Comment by medvednikov** [comment]
Not sure yet.

Changing the default behavior of == would be very unintuitive, since that's how it works in C/C++, Go, etc.

At the same time using == for a bitwise comparison is just wrong.

**Comment by dumblob** [comment]
>Changing the default behavior of == would be very unintuitive, since that's how it works in C/C++, Go, etc.

Sometimes one needs to overcome the historical burden :wink:. Higher level languages using floats as the main/only number format (e.g. Lua) actually use epsilon for all comparisons. Don't know whether *V* wants to push further the safety guarantees provided by default. I see it as the least friction solution (speed shouldn't be an issue as the method `.eqbit()` would be an intrinsic compiling to bitwise comparison operator in C). But that's just my personal opinion.

Maybe this widely regarded [article about float comparisons](https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/ ) could help in decision making :wink:.

**Comment by medvednikov** [comment]
>  Don't know whether V wants to push further the safety guarantees provided by default.

I think so. Let's do it :)

**Comment by spytheman** [comment]
Bitwise comparisons of floats with == *always* tricks new programmers in my experience, and sometimes even experienced ones.
It would be great for all to have epsilon comparison done by ==, which is what 99% of people want anyway, before they are warped by long years of C/C++.

**Comment by medvednikov** [comment]
@spytheman thanks for the input, it's been implemented.

**Pull request closed without merging**
