### PR TITLE
checker, cgen: fix generic operator overload (fix #11472)

### LINKED ISSUE #11472: operator overload doesn't work on generic structs
**V version:** 
latest master

**OS:** 
win10

**What did you do?**
```V
struct Matrix<T> {
	row int
	col int
mut:
	data [][]T
}

fn from_array<T>(arr [][]T) Matrix<T> {
	return Matrix<T>{row: arr.len, col: arr[0].len, data: arr.clone()}
}  

fn (m1 Matrix<T>) + (m2 Matrix<T>) Matrix<T> {
	if m1.row != m2.row || m1.col != m2.col {
		panic('Addition can only be performed on matrix with same size')
	}
	mut res := m1
	for i in 0..m2.row {
		for j in 0..m2.col {
			res.data[i][j] += m2.data[i][j]
		}
	}
	return res
}

fn main() {
	print(from_array([[1,2,3],[4,5,6]]) + from_array([[7,8,9],[10,11,12]]))
}
```

**What did you expect to see?**
the result matrix
 
**What did you see instead?**
```
matrix.v:26:8: error: undefined operation `Matrix<int>` + `Matrix<int>`
   24 |
   25 | fn main() {
   26 |     print(from_array([[1,2,3],[4,5,6]]) + from_array([[7,8,9],[10,11,12]]))
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   27 | }
```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix generic operator overload (fix #11472).

- Fix generic operator overload.
- Add test.

```vlang
struct Matrix<T> {
	row int
	col int
mut:
	data [][]T
}

fn from_array<T>(arr [][]T) Matrix<T> {
	return Matrix<T>{
		row: arr.len
		col: arr[0].len
		data: arr.clone()
	}
}

fn (m1 Matrix<T>) + (m2 Matrix<T>) Matrix<T> {
	if m1.row != m2.row || m1.col != m2.col {
		panic('Addition can only be performed on matrix with same size')
	}
	mut res := m1
	for i in 0 .. m2.row {
		for j in 0 .. m2.col {
			res.data[i][j] += m2.data[i][j]
		}
	}
	return res
}

fn test_generic_operator_overload() {
	result := from_array([[1, 2, 3], [4, 5, 6]]) + from_array([[7, 8, 9], [10, 11, 12]])
	println(result)
	assert result.row == 2
	assert result.col == 3
	assert result.data == [[8, 10, 12], [14, 16, 18]]
}

PS D:\Test\v\tt1> v run .
Matrix<int>{
    row: 2
    col: 3
    data: [[8, 10, 12], [14, 16, 18]]
}
```

### CODE REVIEW

**Comment by medvednikov** [comment]
```2s
Run ./v -autofree -o v2 cmd/v
==================
/tmp/v/v2.16765619818116130250.tmp.c:40116: warning: assignment from incompatible pointer type
/tmp/v/v2.16765619818116130250.tmp.c:72548: error: identifier expected
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.```

**Comment by yuyi98** [comment]
OK, I'll fix it.

**Comment by SleepyRoy** [comment]
@yuyi98 Good work! The `==` and `<` in V also have overload features, would be nice if you also implement them. 
```V
// could be added to tests
// after defining them all relational ops (<, <=, >, >=, ==, !=) should work
fn (m1 Matrix<T>) == (m2 Matrix<T>) bool
fn (m1 Matrix<T>) < (m2 Matrix<T>) bool  // though in math there's no concept of matrix comparison, you may define one, e.g. A<B if for all elements there's A<B
```

**Comment by yuyi98** [comment]
@SleepyRoy   Thanks, I will solve this problem first, and I will submit another PR for your suggestion.

**Pull request merged**
