### PR TITLE
Add MSVC C backend support, Fix live code reloading on windows (with both GCC and MSVC), Other windows (some MSVC specific) fixes.

### PR DESCRIPTION
**Pull request by emily33901**
## MSVC Support
This PR adds support for MSVC as a CGen 'backend'.

Why?
For most devs on windows MSVC is still the defacto compiler (I only had gcc installed becuase of a perl install (which I didnt even know I had)). Whilst I still think that the recommendation of a clang based compile is almost certainly better, MSVC is what I thought of first and so here we are.

`msvc` is added as a platform. This was the easiest method to differentiate `windows (gcc)` from `windows (msvc)`. I am not entirely sure this is the best method but It works for now 

This PR contains some fixes for C gen that allow msvc to compile code. This includes
* Casting `void*` to `byte*` before performing pointer arithmatic
* initialising values to `{0}` instead of `{}` 
* ignoring gcc extensions `_Atomic` (Really shouldnt do this but then again V shouldn't rely on gcc's extension _Atomic anyway and should be implementing its own atomic functions).
All of these are only performed when `v` is called with `-os msvc`.

It also contains a new thirdparty file `microsoft_craziness.h` courtosy of Jonathan Blow which allows a programmer to find *a visual studio installation*. No attempt is made at the moment to confirm whether the installation actually exists. `microsoft_craziness.c` contains the stb-style implementation of that header along with `wide_string_to_narrow_temp` which converts a widestring to a temp narrow string.

`msvc.v` is a new file that contains all of the msvc compiling code (not necessary but I felt that most of this should be kept far away from the main compiler. It contains functions to `cc` with msvc. Not all of the libs that are explicitly linked (`default_libs`) are probably necessary - they are the default ones that are linked for any visual studio project). 

`msvc.v` also handles building thirdparty object files (msvc built object files end in the extension .obj) and passing library and library folders that are `#flag`'d with gcc style `-L` and `-l`. **Of note however** MSVC cannot link directly to .dll files so for `glfw` a link-library would need to be added for msvc.

`unistd.h` has been moved into `os_nix.v`. Whilst this file is included with `mingw` it is not with msvc - it is not used on any windows platform. In `os.ticks()`, `gettimeofday` and related code has been moved into a `$else` block becuase they are not called on windows platforms.

## Windows Hot Code Reloading

This PR adds HCR for msvc / fixes(?) it for gcc on windows. `pthread` mutex replaced with a windows style mutex `pthread` thread replaced with a win32 one. `load_so` calls `LoadLibraryA`, `FreeLibrary` and `GetProcAddress` on windows. On msvc it will also load the file with a `.dll` extension (so that the rest of compilation need not be changed). It also ensures that functions that are live loaded across so files are properly `__declspec(dllexport)`ed so that they can be found with `GetProcAddress`.

## Other windows related fixes
`os.create_dir` should now be consistent with its nix equivalent by recursively creating all directories up to and including the final segment of the path.
When invoking with `run` or `test`, commands that are passed to the shell is now transformed to use `\\` instead of `/` to help cmd actually run them. 

## Other notes
All tests in `compiler/tests` passed. The compiler could compile itself from gcc to msvc and vice versa multiple times. All the examples should run (that did run before on windows). `hot_code_reloading/graph.v` does not work on either windows platform and crashes becuase the gl functions are not properly initialised in the dynamic library (which I will be looking into anyway).

Also happy to cherrypick this PR into several smaller PRs if that would be better.

I have not tested this on any *nix platform so if I have broken anything else CI should catch that and I will update accordingly.

### CODE REVIEW

**Comment by medvednikov** [comment]
Wow, thanks for such immense work.

I'll test and merge this today once the tests pass.

**Comment by joe-conigliaro** [comment]
Nice one @emily33901 🎉

**Comment by emily33901** [comment]
When you cgen for a variable to be initialized with `{}` what are you actually expecting to happen?

**Comment by emily33901** [comment]
and `bounce.v` is broken on both windows platforms for the same reasons that `graph.v` im assuming

**Comment by vitalyster** [comment]
I did the same work and have few notes:
> ignoring gcc extensions _Atomic

Many stackoverflow links say that `volatile` keyword is atomic for MSVC, so something like:
```
#ifdef _MSC_VER
#define _Atomic volatile
#endif
```
can be used.

> wide_string_to_narrow

There is a [PR for wide strings](https://github.com/vlang/v/pull/1266), we can try to combine it in one

**Comment by emily33901** [comment]
> 
> 
> I did the same work and have few notes:
> 
> > ignoring gcc extensions _Atomic
> 
> Many stackoverflow links say that `volatile` keyword is atomic for MSVC, so something like:
> 
> ```
> #ifdef _MSC_VER
> #define _Atomic volatile
> #endif
> ```
> 
> can be used.

Thanks for the insight. I did not know that msvc had that - you always hear from the big c++ people that volatile does not make something threadsafe but i guess ms specific compiler flags disagree

> > wide_string_to_narrow
> 
> There is a [PR for wide strings](https://github.com/vlang/v/pull/1266), we can try to combine it in one

I saw it but didnt look into it that much. Ill see what could be done

**Comment by medvednikov** [comment]
Thanks again and thanks for making it pass the tests.

**Comment by vitalyster** [comment]
One more note: this microsoft_craziness only needed for old visual studio versions and it does not work with Visual Studio 2019, only with 2017 and lower. At the same time microsoft provided `vswhere` utility with fixed path to find 2017 and 2019 VS installations.

**Comment by emily33901** [comment]
Vswhere would rely on an os.exec to get at the information and would still rely on the same logic to get all the paths that we need. Microsoft craziness does support finding 2019 it will just find the 2017 installation first and go with that - which I did fix in a project of mine so I'll see about pr'ing that change

**Pull request merged**
