### PR TITLE
Adding support for Haiku Operating System (part 2)

### PR DESCRIPTION
**Pull request by M4SSD35TRUCT10N**
Adds support for the Haiku Operating System (part 2).

### CODE REVIEW

**Comment by M4SSD35TRUCT10N** [comment]
CI / ubuntu-prebuilt (pull_request) Failing after 1s — ubuntu-prebuilt: **_fails to download (ignore)_**

CI / windows-msvc (pull_request) Failing after 1m — windows-msvc: **_Works for me..._**

**Comment by Delta456** [comment]
@M4SSD35TRUCT10N do you have Haiku OS with you for testing?

**Comment by M4SSD35TRUCT10N** [comment]
Yes. But yesterday I had no time to wake up the VM. But all of this worked but Alexander told me to split the changes into two commits. So I did. And on Telegram someone already tested it and said it worked. Haiku will become one of the main OS on my old laptop.

**Comment by medvednikov** [comment]
Hm strange msvc build is failing. And without any error message. Will investigate.

**Pull request merged**
