### PR TITLE
[WIP]Implement: YAML Format.

### PR DESCRIPTION
**Pull request by keito940**

### CODE REVIEW

**Comment by radare** [comment]
sooo many yaml tests (almost 3000 files..)

**Comment by keito940** [comment]
@radare 
Sorry. Using Official YAML Test suite.

**Comment by Delta456** [comment]
@keito940 can you remove all of them?

**Comment by Delta456** [comment]
Please fix your build and what's the need of `pbc` and `vc`?

**Comment by keito940** [comment]
`pbc` is not clear, but` vc` is garbage when bootstrapping

**Comment by Delta456** [comment]
Couldn't they be removed?

**Comment by radare** [comment]
uh

Screenshot 2020-03-20 at 12 14 24

**Comment by radare** [comment]
Screenshot 2020-03-21 at 11 01 28

**Comment by nedpals** [comment]
@keito940 We try to keep vlib slim as possible and I'm not sure if it will be utilized internally inside the language. Maybe we should keep it as a separate module maintained by the V core team (like github.com/vlang/yaml) or the [V community](https://github.com/v-community/).

**Comment by keito940** [comment]
@nedpals
I think it should be split.

**Comment by nedpals** [comment]
@keito940 What do you mean?

**Comment by keito940** [comment]
@nedpals 
I want to concentrate on implementing labeled loops, so I thought that YAML implementation should be left to others.

**Comment by nedpals** [comment]
I'll close this PR. Please keep your yaml branch so that someone can continue implementing it. (If it thats the case.)

**Pull request closed without merging**
