### PR TITLE
ci: check fmt before all other

### PR DESCRIPTION
**Pull request by danieldaeschle**
Because our CI is often very full and the code formatting check is the one that fails most of the time, all CI checks will run only if code formatting was successful.

### CODE REVIEW

**Comment by spytheman** [comment]
This creates a bottleneck - the `code-formatting` job is run only on `ubuntu-20.04`, so when these runners are not available, all other jobs will wait, even if there are runners that are available for say `macOS-latest` or `windows-2019`.

**Comment by spytheman** [comment]
I think that jobs that have `runs-on: ` != `ubuntu-20.04` should not depend on `needs: [code-formatting]` to avoid the bottleneck.

**Comment by spytheman** [comment]
Another potential solution will be to use a runner that is not used for anything else like say `ubuntu-22.04` or `ubuntu-18.04`, to minimize the chance of bottlenecking the rest.

**Comment by danieldaeschle** [comment]
The goal is that nothing runs if the code is not properly formatted. Then we can save the runners for other PRs if the Ci fails anyway.

**Comment by danieldaeschle** [comment]
Does the runner matter? I thought it's Docker.

**Review by spytheman — APPROVED** [review]

**Pull request merged**
