### PR TITLE
vlib: import of the filesystem level locking api

### PR DESCRIPTION
**Pull request by trufae**
This PR introduces the https://github.com/trufae/v-filelock filesystem-level locking API into the standard V library.

* Works on UNIX and Windows systems
* It's under `os.filelock` but could be probably moved to `io.filelock` or just make it available under `os`
* As vlib provides thread locking capabilities, file system ones should be also provided out of the box (IMHO)
* The API is simple and stable and has been tested and inspired by other implementations for Go and NodeJS
* It depends on the C backend, but could be ported to the native one, not sure about JS as there are many fs apis
* It's named `filelock` but `fslock` or `flock` seems like good namings to me too

### CODE REVIEW

**Comment by trufae** [comment]
Uhm i formatted it already but seems to be still unhappy 🤔

**Comment by spytheman** [comment]
Can you add tests for wait_acquire/try_acquire too?

**Comment by trufae** [comment]
Finally green

**Comment by medvednikov** [comment]
Interesting that Go has a similar module, but it's internal: https://pkg.go.dev/cmd/go/internal/lockedfile/internal/filelock

**Pull request merged**
