### PR TITLE
main.v: Fix v.exejs build on windows

### PR DESCRIPTION
**Pull request by unknown-v**

### CODE REVIEW

**Comment by spytheman** [comment]
hm, would not that hinder future cross compilation to windows on a non windows host, and also cross compilation on a windows host to another platform?

**Comment by vitalyster** [comment]
I think this will be a better solution - https://github.com/vlang/v/pull/2019

**Comment by spytheman** [comment]
@vitalyster I agree, but try putting them in compiler/cheaders.v above #include <stdio.h> . I do not know which of the std headers use them.

**Comment by medvednikov** [comment]
Yes, I prefer  #2019

Thanks

**Pull request closed without merging**
