### PR TITLE
checker: disallow for _ in string

### PR DESCRIPTION
**Pull request by danieldaeschle**
as discussed in https://github.com/vlang/v/pull/10641

### CODE REVIEW

**Comment by medvednikov** [comment]
hm Ideally this should be optimized by the compiler, since `bytes()` does a copy.

**Comment by Delta456** [comment]
Don't get me wrong but I am against this

**Comment by Gladear** [comment]
Can you explain why ? @Delta456

**Comment by Delta456** [comment]
I have the same reasons as @spytheman so I will take the following list from the discord server.

```
I still do not understand how deprecating ustring has anything to do with the for x in s{} change.
ustring is easy to remove, because it was not used much, and it did not (to me) have useful usages anyway.
The for x in s{} change is nothing like that:
a) it deprecates a very useful behaviour
b) it is breaking to existing code (so it will need compiler warnings/notices/errors)
c) the proposed for x in s.bytes() { or for x in s.runes() { will need compiler magic to be efficient in the most common case.
d) even then, it will not work for situations like this: for c in s.trim_space().bytes() { without either complicating the compiler even further, or cpu/memory cost at runtime.
I still think that iterating over the bytes of an immutable string without additional allocation costs is very useful, and should have its own syntax support (as it did/does).
```

**Comment by Gladear** [comment]
To answer spytheman and you then

a) a very useful behavior, indeed, a very dangerous one too
b) well, yeah, breaks code, happens in a alpha stage language, not the first nor the last time
c) you state that the most common case is people iterating on bytes. I highly doubt that. I think people expect to iterate through the string graphemes most of the type. Iterating through bytes is for low-level operations, which aren't done that often in, let's say, "company-level" applications
d) why wouldn't it ?

**Comment by danieldaeschle** [comment]
The biggest problem is that optimization doesn't really work on `x.some_method().bytes()`

**Comment by spytheman** [comment]
> a) a very useful behavior, indeed, a very dangerous one too

How is it dangerous?

**Comment by Gladear** [comment]
> The biggest problem is that optimization doesn't really work on `x.some_method().bytes()`

Could someone bother to explain me why the optimization isn't feasible in this case ?

**Comment by Gladear** [comment]
> How is it dangerous?

For me, this is related to point c), what people expect. In most if not all modern languages, iterating thought a string will iterate through its graphemes, not its bytes.
Go, Python, JavaScript all do this.
Best-case scenario, it leads to display errors, that can easily be fixed using runes.
Worst-case scenario, it can corrupt data, and somewhat lead to security issues I guess

**Comment by JalonSolov** [comment]
Not true for Go, @Gladear - see this comment in the other PR:  https://github.com/vlang/v/pull/10641#issuecomment-872936887

**Comment by Gladear** [comment]
Well, I kinda consider `for ... := range` to be equivalent to `for ... in`, so, depends on how you see it I guess

**Comment by danieldaeschle** [comment]
> > The biggest problem is that optimization doesn't really work on `x.some_method().bytes()`
> 
> Could someone bother to explain me why the optimization isn't feasible in this case ?

it may be possible, but it's hard to detect since the chaining have to be inspected. Every complex expr needs to be catched.

**Comment by Gladear** [comment]
Shouldn't the test be something as easy as the following ?
Are there cases that I didn't take into account ?
```v
if node.cond is ast.CallExpr {
    if node.cond.name == 'bytes' && node.cond.left_type.idx() == ast.string_type_idx {
```

**Pull request closed without merging**
