### PR TITLE
json: support raw json fields with raw attribute...

### PR DESCRIPTION
**Pull request by abom**
support encoding json with raw json string using `[raw]` attribute, it uses cJSON_CreateRaw, and should only be used when encoding as the cJSON_Raw type is not used by cJSON for parsing, see https://github.com/DaveGamble/cJSON\#data-structure.

Example:

```v
struct Sub {
	type_ int [json: "type"]
}

struct Person {
	name string
	data string [raw]
}

fn main() {
	p := Person{
		name: "ahmed"
		data: json.encode(Sub{type_: 1})
	}

	println(json.encode(p))
}
```

This should output:

```json
{"name":"ahmed","data":{"type":1}}
```

I don't know if we defined a new type like json.Raw and use it instead `[raw]` attribute for string fields.

### CODE REVIEW

**Comment by spytheman** [comment]
Please add a test for that in `vlib/json/json_test.v`, so that it does not regress.

**Comment by abom** [comment]
@spytheman do you think using a new type e.g. json.Raw for fields instead of using `[raw]` attribute is better? I already find some tests are failing as this attribute already is used already in another context.

**Comment by spytheman** [comment]
You can use another attribute name, if that has different meaning than the existing one. In any case, adding a usage example in a _test.v file is a must, both as a regression test, and as an example on how it is supposed to be used by the author (you), so that maintainers in the future can take adequate decisions on how to support it (or deprecate it in favour of a better solution, if there is one).

**Comment by spytheman** [comment]
Closing for inactivity.

**Pull request closed without merging**
