### PR TITLE
docs: fix functions in array/map example

### PR DESCRIPTION
**Pull request by glebbash**

### CODE REVIEW

**Comment by glebbash** [comment]
How can I format docs? 🤔

**Comment by JalonSolov** [comment]
Simplest way I know would be to paste the example into a .v file, then run `v fmt -w example.v`.  Open the file back up, and paste that into the docs.md file.

Is there an easier way, @spytheman ?

**Comment by spytheman** [comment]
No, unfortunately for now, there is not @JalonSolov - I also do that, and I have to admit it gets cumbersome 🤔 ...

**Comment by spytheman** [comment]
I'll add a way to autofix such, may be using `VAUTOFIX=1` like vlib/v/compiler_errors_test.v does.

**Comment by spytheman** [comment]
Hm, it seems that these are currently vfmt bugs - after running it, it ate the functions again.

**Pull request merged**
