### PR TITLE
parser: separate SelectorExpr if name is on another line

### PR DESCRIPTION
**Pull request by nedpals**
This PR treats the following lines of code as two separate AST nodes.
```
node.
name := ....
```
Prior to that, it is treated as a single unknown `AssignStmt` node (aka `node.name :=`). This doesn't change the errors it outputs on the compiler side, but it improves the information that is given to the tools that use this such as [VLS](https://github.com/vlang/vls)

### CODE REVIEW

**Comment by spytheman** [comment]
That seems brittle to me. Can we add a test for it somehow, either here or in vls?

**Comment by nedpals** [comment]
> The setting and usage of this new .name_error parser field, seems brittle to me.
> Can we add a test for it somehow, either here or in vls, so that we can know if/when it regresses?

Sure thing. I'll be adding the tests to VLS

**Comment by medvednikov** [comment]
Can you please explain what this problem solves, I still don't understand.

```
node.
name := 'bob'
```

gives me `error: struct fields can only be declared during the initialization`, which is correct

**Comment by nedpals** [comment]
> Can you please explain what problem this solves, I still don't understand.
> 
> ```
> node.
> name := 'bob'
> ```
> 
> gives me `error: struct fields can only be declared during the initialization`, which is correct

I didn't introduce a new compiler error anymore based from what you've said earlier on the Discord server. The problem it solves right now is that on the parser, the expected output of that example code you've given would be like this:

```
└ ast.ExprStmt
     └ unknown ast.Expr
```

instead of this:
```
├ ast.ExprStmt
│   └ ast.SelectorExpr  // node.
└ ast.AssignStmt          // name := 'bob'
```

This means that the parser should distinguish the invalid/incomplete selector expr and the valid assignstmt.

**Comment by nedpals** [comment]
Maybe I should add the expected error message in the test

**Comment by spytheman** [comment]
Alex, imagine that you have already written the second line.

Then you go back in VSCode, and type `node.` . The expectation is that VLS will give you autocompletion suggestions for the possible fields/methods of `node`, *and* it should consider the second line as a valid statement, assigning 'bob' to the variable `name`.

With the current parser code, `node`.  \n `name :=` gets treated as `node.name`, because the newline is simply ignored.
With this PR, that situation of incomplete code on that line alone, will produce the second AST, that @nedpals described, which is what VLS wants.

**Comment by nedpals** [comment]
Exactly. I just tried to explained mine in a way thats more general aside from the use case of VLS 😅

**Comment by medvednikov** [comment]
I understand now, thanks @spytheman

**Pull request merged**
