### PR TITLE
checker: deny empty enum 

### LINKED ISSUE #7843: declaring empty enums results in a C error
**V version:** V 0.2.1 954580f.095857d
**OS:** Linux Mint 20

**What did you do?**
I have declared an empty enum:
```v
Welcome to the V REPL (for help with V itself, type `exit`, then run `v help`).
V 0.2.1 760de7c
Use Ctrl-C or `exit` to exit, or `help` to see other available commands
>>> enum Type {}
```

**What did you expect to see?**
An error from V saying that the enum cannot be empty.
 
**What did you see instead?**
A C error:
```
/tmp/v/.noprefix.vrepl_temp.11313248834576623734.tmp.c:759:1: error: empty enum is invalid
  759 | } main__Type;
      | ^
```

### PR DESCRIPTION
**Pull request by zakuro9715**
Fix #7843

### CODE REVIEW

**Comment by medvednikov** [comment]
i had a look at it and it's weird

empty enums work fine for me

i couldn't reproduce

i think they should be allowed, just skipped in cgen. so if there are  no enum vals, nothings gets generated

**Comment by zakuro9715** [comment]
Empty enum is ill-formed 

https://wandbox.org/permlink/o8QMebFDlzkCqocA

**Comment by spytheman** [comment]
Empty enums should be a V checker or parser error imho. 
Consider the following program:
```v
enum Abc{ }
fn main() {
    a := Abc{}
    e := sizeof(a)
    println(a)
    println(e)
}
```

**Comment by zakuro9715** [comment]
I agree. It should be checker error.

@medvednikov What do you think?

**Comment by medvednikov** [comment]
Ok, let's make it an error.

**Pull request merged**
