### PR TITLE
builtin: fix a memory leak in utf32_to_str()

### PR DESCRIPTION
**Pull request by ciubotaru**
Trivial bug, trivial fix.

### CODE REVIEW

**Comment by medvednikov** [comment]
This won't work. The string escapes, and will be unusable after the free.

**Comment by medvednikov** [comment]
`tos` doesn't copy the data.

**Comment by ciubotaru** [comment]
In any case, current implementation leaks memory.

**Comment by medvednikov** [comment]
Yes, it's on my backlog. I'll fix this after the release of vweb and generics.

**Pull request closed without merging**
