### PR TITLE
checker: warn when casting non-pointer types to interfaces

### LINKED ISSUE #9377: error with mutable interface
**V version: V 0.2.2 00651c8** 
**OS: Manjoro linux** 

when trying to use a mutable interface, the memory access seems to be broken?

in this small gist i made, i try to output a speed number inside a Dog struct method speak, which is used in an interface called Mob.

in the first function it outputs the correct number,
in the second function i get a strange value or 0

https://gist.github.com/waotzi/64d5a56732698782ed36c6bec181ad4e

as spytheman mentions on discord

```
    self.mob = &Dog{}
```
works around the issue

### PR DESCRIPTION
**Pull request by spaceface777**
This should help prevent some dangling pointers when using interfaces.

Closes #9377.

### CODE REVIEW

**Comment by medvednikov** [comment]
This should be fixed in the compiler. There's no need to always use references to use interfaces. That'd be too limiting.

**Comment by spaceface777** [comment]
I agree, but until it's actually fixed, I think a warning is better than nothing.

from discord:

> a warning isn't as convenient as automatic escape analysis, that's for sure - but it is still much better than having your program crash or print wrong results for no apparent reason imho

escape analysis is *much* more difficult to implement correctly; and, meanwhile, people's code is crashing with no apparent cause (see the linked issue)

**Comment by medvednikov** [comment]
No, it's actually simple. Can be done by just adding a new field `is_local` for vars defined in fns, and then it can be memdup'ed by the interface cast function.

**Comment by medvednikov** [comment]
Things like `animals << Cat{}` need extra logic.

**Pull request closed without merging**
