### PR TITLE
os: Create epoll wrapper

### PR DESCRIPTION
**Pull request by mcastorina**
I have a few questions:

1. Is the file named correctly to only be included on linux? `vlib/os/events/epoll_linux.c.v`
2. My plan is to make a generic event notifier module that uses OS specific code. How would I set that up?

I'd like feedback on creating a new module under `os` for this. Is it a good idea or should it be under the main `os` module?

Also, here is an example program using this code:

```v
import os
import os.events
import time
import net

fn accept_connections(ch chan int) {
	mut listener := net.listen_tcp(9001) or { panic(err) }
	for {
		conn := listener.accept() or { panic(err) }
		ch <- conn.sock.handle
	}
}

fn main() {
	ch := chan int{cap: 1}
	go accept_connections(ch)

	mut notifier := events.new_notifier() ?
	notifier.add(os.stdin().fd, events.epoll_read) ?
	defer {
		notifier.close() or {}
	}

	for {
		for event in notifier.wait(1 * time.second) {
			dump(event)
			if event.kind.has(.epoll_peer_hangup) {
				println('connection closed')
				notifier.remove(event.fd) or {}
				continue
			}
			s, n := os.fd_read(event.fd, 10)
			if n == -1 {
				println(os.posix_get_error_msg(C.errno))
				return
			}
			os.fd_write(event.fd, s)
		}
		// TODO: Adding an event to watch is thread safe while waiting
		//       I'm not sure how to signal this to V
		for {
			select {
				conn_fd := <-ch {
					notifier.add(conn_fd, events.epoll_read | events.epoll_peer_hangup) ?
				}
				else {
					break
				}
			}
		}
	}
}
```

It uses two threads: one to accept TCP connections on 9001 and the other to read data and echo responses back. You can use `nc` to play with it. `nc localhost 9001`

### CODE REVIEW

**Comment by spytheman** [comment]
Perhaps `import os.notify` ?

**Comment by spytheman** [comment]
>     1. Is the file named correctly to only be included on linux? `vlib/os/events/epoll_linux.c.v`
yes, that will be included only on linux

**Comment by spytheman** [comment]
>     2. My plan is to make a generic event notifier module that uses OS specific code. How would I set that up?

You can use a file `something_default.c.v` that contains a dummy implementation (that perhaps does `panic('not implemented')`).
Then, the specialized versions can go in `something_platform.c.v` files, where `platform` is linux/windows/darwin etc.

**Comment by spytheman** [comment]
> I'd like feedback on creating a new module under os for this. Is it a good idea or should it be under the main os module?
imho a new module under os is better

**Comment by JalonSolov** [comment]
epoll does not exist on Windows.  Take a look here for possible alternatives:

https://stackoverflow.com/questions/67082/what-is-the-best-epoll-kqueue-select-equvalient-on-windows

**Comment by mcastorina** [comment]
Thanks for the feedback @spytheman and @JalonSolov

Yes this is linux only - I think `kqueue` can be used for the Mac version, and there are some good options in that link for Windows (thanks!).

> You can use a file something_default.c.v that contains a dummy implementation (that perhaps does panic('not implemented')).
Then, the specialized versions can go in something_platform.c.v files, where platform is linux/windows/darwin etc.

Does this mean all of the structs need to be named the same? I was hoping to do something like..
```go
epoll_linux.c.v        // struct EpollNotify
kqueue_darwin.c.v      // struct KqueueNotify
something_windows.c.v  // struct SomethingNotify

notify.v // detect OS and abstract relevant code, providing one interface
```
The main advantage of this organization is readability and it's just easier for me to reason about. If it's not possible then I will follow your suggestion.

**Comment by mcastorina** [comment]
Also there seems to be a bug when returning more than one event. I'm investigating now.

**Comment by mcastorina** [comment]
I have found it is an issue with tcc though I'm not sure what. gcc works fine.

**Comment by spytheman** [comment]
> Does this mean all of the structs need to be named the same? I was hoping to do something like..
No, only the file names should match.
You can do something like:
```
notify.v -> common stuff
implementation_default.v -> keep the API the same as the rest implementation_ files, possibly just panic inside each function
implementation_linux.v
implementation_darwin.v
implementation_windows.v
```
The _default.v file will *NOT* be used when there is a more platform specific file with the same name.
You are free to use platform specific names inside the different implementations, just make sure that the common functions in notify.v can call them.

**Comment by spytheman** [comment]
Can you add some tests too please?

**Comment by mcastorina** [comment]
@spytheman I added two test cases. Is there a better way to limit it to linux only besides encasing the entire test in `$if linux` ?

I'll work on more test cases but I think they can be merged in another PR

**Comment by medvednikov** [comment]
>  Is there a better way to limit it to linux only besides encasing the entire test in $if linux ?

There's only that or `foo_linux.v`

**Pull request merged**
