### PR TITLE
[WIP, need help] gen: fix insert into array inside fn

### LINKED ISSUE #5649: cannot insert elements to array inside function
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn foo(mut a []int) {
	a << 3
}

fn main() {
	mut a := [1,2]
	foo(mut a)
	println(a)
}
```

**What did you expect to see?**
[1,2,3]
 
**What did you see instead?**
[1,2]

### PR DESCRIPTION
**Pull request by SleepyRoy**
Fix #5649.

### CODE REVIEW

**Comment by yuyi98** [comment]
@SleepyRoy  Please try this:
```v
				if arg.expr is ast.Ident {
					g.write('&/*arr*/')
					g.expr(arg.expr)
				} else {
					// Special case for mutable arrays. We can't `&` function
					// results,	have to use `(array[]){ expr }[0]` hack.
					g.write('&/*111*/(array[]){')
					g.expr(arg.expr)
					g.write('}[0]')
				}
				return
```

**Comment by SleepyRoy** [comment]
@yuyi98 Thanks, I also thought like that. But as you see, this results in aes_test failing.

**Comment by yuyi98** [comment]
I think it could be the problem of `aes`.

**Comment by Delta456** [comment]
@SleepyRoy Please rebase https://github.com/vlang/v/blob/master/vlib/v/ast/str.v#L27

**Comment by SleepyRoy** [comment]
Seems that @yuyi98 has come up with a solution in PR #5769 so close this PR.

**Pull request closed without merging**
