### PR TITLE
cgen: fix in array of struct error (fix #7452)

### LINKED ISSUE #7452: Compilation error when check for struct in array of structs
**V version: 0.1.30 dc3a6bb, timestamp: 2020-12-21 17:46:26 +0100** 
**OS: linux** 

**What did you do?**
```
struct Person {
	name string
}

fn main() {
	ivan := Person{'Ivan'}
	people := [ivan]
	println(ivan in people)
}
```

**What did you expect to see?**
true
 
**What did you see instead?**
```
Compilation with tcc failed. Retrying with cc ...
==================
/tmp/v/hello.9802657856834764945.tmp.c: In function ‘array_main__Person_contains’:
/tmp/v/hello.9802657856834764945.tmp.c:1449:41: error: invalid operands to binary == (have ‘main__Person’ {aka ‘struct main__Person’} and ‘main__Person’ {aka ‘struct main__Person’})
   if ((*(main__Person*)array_get(a, i)) == v) {
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~
/tmp/v/hello.9802657856834764945.tmp.c: In function ‘eprintln’:
/tmp/v/hello.9802657856834764945.tmp.c:5045:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
  write(2, s.str, s.len);
  ^~~~~~~~~~~~~~~~~~~~~~
/tmp/v/hello.9802657856834764945.tmp.c:5046:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
  write(2, "\n", 1);
  ^~~~~~~~~~~~~~~~~
/tmp/v/hello.9802657856834764945.tmp.c: In function ‘eprint’:
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.
...
```

Related bugs: https://github.com/vlang/v/issues/7451, https://github.com/vlang/v/issues/7427

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fixes in array of struct error (fix #7452).

- Fixes in array of struct error.
- Implement `gen_struct_equality_fn()` to compare struct type.
- Add test.

```v
struct Person {
	name string
	nums []int
	kv   map[string]string
}

fn test_struct_array_of_multi_type_in() {
	ivan := Person{
		name: 'ivan'
		nums: [1, 2, 3]
		kv: {
			'aaa': '111'
		}
	}
	people := [Person{
		name: 'ivan'
		nums: [1, 2, 3]
		kv: {
			'aaa': '111'
		}
	}, Person{
		name: 'bob'
		nums: [2]
		kv: {
			'bbb': '222'
		}
	}]
	println(ivan in people)
	assert ivan in people
}
```

### CODE REVIEW

**Comment by yuyi98** [comment]
Finding that auto-generated functions are recursively nested generates nested function within the function, I'm trying to figure it out.

**Comment by SleepyRoy** [comment]
@yuyi98 great job! Is this ready to merge?

**Comment by yuyi98** [comment]
@SleepyRoy  Thanks, I don't know why it wasn't merged.
@medvednikov  Can this be merged now or what else needs to be done?

**Comment by medvednikov** [comment]
Yes, sorry, had to test something out.

**Comment by yuyi98** [comment]
@medvednikov  Thanks, and I want to implement `array.index` to generic, I don't know if we need it?

**Comment by vsyrovat** [comment]
Nice!

> I don't know if we need it?

IMO, for language concistency, yes

**Pull request merged**
