### PR TITLE
additional `.gitignore` rules for windows development

### LINKED ISSUE #1205: Using make.bat, fault.
**V version:** V 0.1.16
**OS:** win10 1803

**What did you do?**
I used make.bat to install v, bug got nothing. 
Then run the "gcc -std=gnu11 -w -o v.exe v.c".The error message is "cce1znT0.o:v.c:(.text+0x6e6e): undefined reference to `__imp_gethostname' collect2.exe: error: ld returned 1 exit status.

**What did you expect to see?**
I want to see the v.exe in the file explorer.
 
**What did you see instead?**
Nothing.

### PR DESCRIPTION
**Pull request by nedpals**
- Ignores `v.exe` and other executable files on git
- ~~Fixes compile error when executing the `make.bat` on windows. (prev on #1197 and fixes #1205 )~~

### CODE REVIEW

**Comment by medvednikov** [comment]
-lws2_32 is no longer necessary

**Comment by nedpals** [comment]
Cool, maybe i'll just push for the `.gitignore` instead so we can solve some issues when working on windows. 😃

**Comment by unknown-v** [comment]
> 
> 
> -lws2_32 is no longer necessary

but there still is 
https://github.com/vlang/v/blob/251e32948e9e7197b29e82ef37d62331910854e3/vlib/os/os_win.v#L3

and for 
https://github.com/vlang/v/blob/251e32948e9e7197b29e82ef37d62331910854e3/vlib/net/net.v#L8
net.v:hostname()-C.gethostname
on windows we need winsock
see : 
https://docs.microsoft.com/de-de/windows/win32/api/winsock/nf-winsock-gethostname

**Comment by nedpals** [comment]
@unknown-v have you tried running the latest commit? building v without `-lws2_32` on the `make.bat` works fine now even the code you mentioned above.

**Comment by unknown-v** [comment]
until you import the net module in your app
but will try it when back at home

**Comment by nedpals** [comment]
in my windows machine it didn't appear tho but certainly it compiles fine.

image

**Comment by unknown-v** [comment]
k works fine now

**Pull request merged**
