### PR TITLE
cflag: remove circular dependency

### PR DESCRIPTION
**Pull request by krischerven**
V can't compile itself unless we ignore this cycle as builder.v and table.v must import eachother

Alternatively, builder/cflags.v could be moved to another module and that would fix the issue without a hack

### CODE REVIEW

**Comment by RiordanIX** [comment]
This seems like a bad idea. If table.v only depends on the cflags.v portion of builder, then cflags should be moved to its own module like you said. Ideally these would be trees, no cycles.

**Comment by krischerven** [comment]
I'll wait to see what @medvednikov thinks

**Comment by JalonSolov** [comment]
My opinion, from far too much experience... Definitely move to a different module.  Cross-dependencies like this can lead to all sorts of problems.

**Comment by krischerven** [comment]
I think I'll do that when I get the chance.

**Comment by medvednikov** [comment]
Yes, the cycles have to be removed from the V source.

**Comment by krischerven** [comment]
@medvednikov Assuming only vlib/v/builder/cflags.v has to be moved, what would be a good name for the new module? `cflag` seems good but I want to make sure.

**Comment by medvednikov** [comment]
Yeah it's fine the way you did it :)

**Comment by krischerven** [comment]
This leaves one circular dependency between v.ast and v.table. Going to leave that one for another PR.

**Pull request merged**
