### PR TITLE
orm: add support for generic statements

### PR DESCRIPTION
**Pull request by Casper64**
orm: add support for generic statements

Fixes the error:
```
error: V ORM: the table symbol `T` has to be a struct
```

**Example:**
```v
import db.sqlite

struct User {
	id   int    [primary; sql: serial]
	name string
}

fn do_create[T](db sqlite.DB) ! {
	sql db {
		create table T
	}!
}

fn do_insert[T](db sqlite.DB, val T) ! {
	sql db {
		insert val into T
	}!
}

fn do_select[T](db sqlite.DB) ![]T {
	vals := sql db {
		select from T
	}!

	return vals
}

fn main() {
	db := sqlite.connect(':memory:')!

	do_create[User](db)!

	user := User{
		name: 'casper'
	}
	do_insert(db, user)!

	selected := do_select[User](db)!
	println('got: ${selected}')
}
```

### <samp>🤖 Generated by Copilot at 742e8f4</samp>

This pull request improves the support for generic types in the ORM module of the V compiler and adds a test case for it. It fixes the type checking and parsing of generic table expressions, insertions, and queries in `vlib/v/checker/orm.v` and `vlib/v/parser/orm.v`. It also creates a new file `vlib/orm/orm_generic_test.v` that demonstrates the usage of generic types with the ORM module.

### <samp>🤖 Generated by Copilot at 742e8f4</samp>

*  Add a test case for using generic types with the ORM module in `vlib/orm/orm_generic_test.v` ([link](https://github.com/vlang/v/pull/19018/files?diff=unified&w=0#diff-fcc1394757e8677397fcf2bab4f2a6bcad9e9e20562cbb73ce3fb6e0986ad8bcR1-R42))
*  Handle generic types in the `check_orm_select` method by unwrapping the underlying concrete types and setting the `.result` flag ([link](https://github.com/vlang/v/pull/19018/files?diff=unified&w=0#diff-93527b637b060eae115caa95bec79b56c8c13188e92dfc876c36e59524e3e672L32-R32), [link](https://github.com/vlang/v/pull/19018/files?diff=unified&w=0#diff-93527b637b060eae115caa95bec79b56c8c13188e92dfc876c36e59524e3e672R38-R44))
*  Handle generic types in the `check_orm_insert` method by unwrapping the underlying concrete types and checking for pointer types ([link](https://github.com/vlang/v/pull/19018/files?diff=unified&w=0#diff-93527b637b060eae115caa95bec79b56c8c13188e92dfc876c36e59524e3e672L183-R193), [link](https://github.com/vlang/v/pull/19018/files?diff=unified&w=0#diff-93527b637b060eae115caa95bec79b56c8c13188e92dfc876c36e59524e3e672L202-R212))
*  Handle generic types in the `check_orm_table_expr_type` method by unwrapping the underlying concrete types ([link](https://github.com/vlang/v/pull/19018/files?diff=unified&w=0#diff-93527b637b060eae115caa95bec79b56c8c13188e92dfc876c36e59524e3e672L572-R582))
*  Handle generic types in the `parse_orm_select` method by setting the `.generic` flag on the table type ([link](https://github.com/vlang/v/pull/19018/files?diff=unified&w=0#diff-38e6802f080d2a67da3a0ce797f8ac78616b5c3839e0d06861a27788277648e1R83-R85))

### CODE REVIEW

**Comment by spytheman** [comment]
Add `vlib/orm/orm_generic_test.v` around `cmd/tools/vtest-self.v:123` and `cmd/tools/vtest-self.v:212`, that will skip the test on the corresponding CI jobs.

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by JalonSolov** [comment]
Whee... missing sqlite3 header caused the failure in `ubuntu-docker-musl` test, and unitialized memory in libsqlite3 caused the error in `tests-sanitize-memory-clang`.

The first one can likely be fixed by installing correct dev headers, but the other one... unless there's a newer libsqlite3.so that has that problem fixed...

**Comment by spytheman** [comment]
Yes, that is why all the orm and sqlite tests are currently skipped in `cmd/tools/vtest-self.v`. The new one can just be added to those skip lists. Fixing them properly, is out of scope of this PR.

**Comment by walkingdevel** [comment]
I thoroughly reviewed the solution and identified two serious issues:

1. While using generic functions, the Post table was not created; only the User table was created instead. This occurred due to the generation of incorrect C-code for the do_create function, which resulted in it containing data for the User instead of the Post.
create
c


2. Furthermore, when a different type is passed to do_select, the type checker also encounters errors.
select

In general, I am personally against the use of generics in ORM, not because of the ability to write it, but due to concerns related to database and code design.

The primary goal of database design is to address these problems at the table level and manage relationships between them, rather than trying to smooth out edges or identify commonalities during the process of writing business logic. When we resort to writing a generic function for searching entities based on a date range, it does not simply aim to avoid repetition; instead, it tries to combine entities that should be kept separate. Each entity should have its own internal implementation for the find_by_date_range method and remain isolated from other entities that are unrelated. By doing otherwise, we create associations between things that should not be linked. The ORM itself is already a robust abstraction that can express all this, even if it means some code repetition.

Generic functions for create and insert serve no meaningful purpose as they merely act as functional wrappers over the ORM syntax without accepting any parameters.

In my opinion, this solution is redundant and could lead to complications in the compiler. While it may allow for shorter code, it might also lead to poor design decisions.

**Comment by spytheman** [comment]
1. and 2. are indeed issues, that should be fixed, ideally in this PR, or in future ones.

**Comment by walkingdevel** [comment]
> 1. and 2. are indeed issues, that should be fixed, ideally in this PR, or in future ones.

It needs to be done in this PR; otherwise, there are no generics. Added another way to pass entities to the ORM query(using generic parameters), but there are no generics in this PR.

**Comment by walkingdevel** [comment]
string

**Comment by Casper64** [comment]
I agree with @walkingdevel that the fixes need to be pushed in this pr. 

I really like how the current syntax `sql db` abstracts a lot of the orm and I think generics are the next step!

I was trying to code something like phpmyadmin and I felt that when using the orm I would have had a lot of boiler plate code, which could be easier generated by using generics.

I will take your advice and try to build it in orm first, then see if generics still make sense. If there is too much repeating code I can always try to abstract it and maybe add a feature to the orm rather than implementing it as a generic function.

**Pull request closed without merging**
