### PR TITLE
v/checker: Check array slicing indexes are valid

### PR DESCRIPTION
**Pull request by ntrel**
Also fix `IndexExpr.pos` - before it would get the position of the start of the next line.

### CODE REVIEW

**Comment by ntrel** [comment]
Hmm, something weird is happening with the tests - tests that are supposed to fail with certain output seem to be getting run as if they should succeed.

**Comment by spytheman** [comment]
The reason for the failures is that there is a file named `vlib/v/tests/unsafe.v` . 

Name your tests that you want compiled and run by test-fixed directly, with the postfix `_test.v`.
The ones that you want to check for warns/errors (i.e. not compiled and run), you have to put in `vlib/v/checker/tests/` or inside `vlib/v/parser/tests/`, with the postfix `.vv`, and with the expected output from v in the corresponding `.out` file.

**Comment by spytheman** [comment]
Should be fixed in fb4c3ff31a921ba78af899301b4b060e1068abd7

**Comment by spytheman** [comment]
@ntrel is it ok to merge this PR now, or do you intend to do more commits on it?

**Comment by ntrel** [comment]
@spytheman Thanks! I didn't know about `checker/tests`. This pull is ready.

**Pull request merged**
