### PR TITLE
vpm: optimize performance by adding filter when cloning

### PR DESCRIPTION
**Pull request by ttytm**

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by Wertzui123** [comment]
This breaks VPM on systems with an older Git version as `--also-filter-submodules` is fairly new.
Maybe we should revert this change or at least check for the Git version before adding the flag to the clone command?

**Comment by ttytm** [comment]
Good catch. The version check should be good or removing just this flag. We can keep the filtering benefit then.

**Comment by Wertzui123** [comment]
> Version check would be best. Nobody should be using old versions of Git - if their package manager doesn't have the newer version, they can always clone it and build it themselves.
> 
> Too many things can go wrong with older versions of Git. :-\

  While I agree with you in principle, the "old version" you're referring to is from just 2022. And yes, you could theoretically build Git manually (which I have tried earlier today), but especially if you're not very familiar with C build systems it might be a little (and mostly unnecessary) challenge. Furthermore, I need to use VPM in a Debian 10 CI/CD script (for BC reasons), which is why building Git manually is even more unsuited.

**Comment by JalonSolov** [comment]
The version check I'm referring to would check the version of Git that's available, and add the extra option if it was "new enough".

As for the age of Git... it doesn't matter.  They don't do new versions on a whim... the new versions are to fix problems found in the previous version.  Rarely, the new version will have a new feature (such as this new option).

Either way, you're always better off with the latest version of Git, since your entire codebase depends on it working properly.

If Debian made this hard to keep up with, the fault is with Debian.

**Pull request merged**
