### PR TITLE
v.debug: fix code generated for stringfy ptr with non-pointer str() 

### LINKED ISSUE #20702: `$dbg` statement in `sdl/examples/basic_window` results in compile error
### Describe the bug

`$dbg` statement in `sdl/examples/basic_window` results in compile error

### Reproduction Steps

`basic_window.v` with the following contents:
```v
module main

import sdl

fn main() {
	sdl.init(sdl.init_video)
	window := sdl.create_window('Hello SDL2'.str, 300, 300, 500, 300, 0)
	renderer := sdl.create_renderer(window, -1, u32(sdl.RendererFlags.accelerated) | u32(sdl.RendererFlags.presentvsync))

	mut should_close := false
	for {
		evt := sdl.Event{}
		for 0 < sdl.poll_event(&evt) {
			match evt.@type {
				.quit { should_close = true }
				else {}
			}
		}
		if should_close {
			break
		}
    $dbg // <- adding this yields a compile error

		sdl.set_render_draw_color(renderer, 255, 55, 55, 255)
		sdl.render_clear(renderer)
		sdl.render_present(renderer)
	}

	sdl.destroy_renderer(renderer)
	sdl.destroy_window(window)
	sdl.quit()
}
```

### Expected Behavior

Clean compile + run - and the debugger invoked

### Current Behavior

```
  v run examples/basic_window/
==================
/dev/shm/v_1000/basic_window.01HNJT6T4C374YQ9WZ2C5DPYX7.tmp.c:23075: warning: assignment discards qualifiers from pointer target type
/dev/shm/v_1000/basic_window.01HNJT6T4C374YQ9WZ2C5DPYX7.tmp.c:31646: error: cannot convert 'struct SDL_Window **' to 'struct SDL_Window'
...
==================
(Use `v -cg` to print the entire error message)
```

### Possible Solution

???

### Additional Information/Context

_No response_

### V version

V 0.4.4 fb0efc0

### Environment details (OS name and version, etc.)

Linux Arch based (Endeavor OS)
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

### PR DESCRIPTION
**Pull request by felipensp**
Fix #20702

### CODE REVIEW

**Comment by felipensp** [comment]
Can you test using this branch @Larpon ?

**Comment by spytheman** [comment]
I've tested with this branch. 

It now compiles with this PR, but when running, I get:
```
#0 13:26:31 ᛋ fix_deref_debug /v/oo❱./v -g -keepc -gc none run b.v
7fd016148d58 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v_1000/b.tmp.c:6415: by SDL_SysWMEvent_str
/tmp/v_1000/b.tmp.c:6317: by indent_sdl__SysWMEvent_str
/tmp/v_1000/b.tmp.c:6821: by indent_SDL_Event_str
/tmp/v_1000/b.tmp.c:5982: by SDL_Event_str
/tmp/v_1000/b.tmp.c:5946: by indent_sdl__Event_str
/tmp/v_1000/b.tmp.c:5943: by sdl__Event_str
/tmp/v_1000/../../../../../../space/v/oo/b.v:25: by main__main
/tmp/v_1000/../../../../../../tmp/v_1000/b.tmp.c:17345: by main
#255 13:26:47 ᛋ fix_deref_debug /v/oo❱
#255 13:26:48 ᛋ fix_deref_debug /v/oo❱
```

**Comment by spytheman** [comment]
`./v -cg -keepc -cc clang-12 b.v` also fails to compile, on both master, and here.

**Comment by spytheman** [comment]
I think what is happening, is that since it tries to stringify all variables in scope, that includes things like the locals `window` and `renderer`, and the automatic str methods for those do not work.

**Comment by felipensp** [comment]
> I think what is happening, is that since it tries to stringify all variables in scope, that includes things like the locals `window` and `renderer`, and the automatic str methods for those do not work.

Yes, probably some struct members are not proper initialized before the stringify.

**Comment by spytheman** [comment]
Adding those manually in my `~/.vmodules/sdl/fixes.v`:
```v
module sdl

pub fn (r &Renderer) str() string { return 'a renderer' }
pub fn (e &Event) str() string { return 'an event' }
pub fn (w &Window) str() string { return 'a window' }
```
fixes compilation.

Note that the manual methods above are defined on `x &Type`, not for `x Type`.

All of the 3 types above are of the form:
```v
@[noinit; typedef]
pub struct C.SDL_Renderer {
}

pub type Renderer = C.SDL_Renderer
```
i.e. a V type alias to an incomplete C declaration, so the compiler can only know how to handle a pointer to it, not how to pass it by value.

**Comment by spytheman** [comment]
I think we have to fix the automatic str() method generation for those, to also pass them by reference.

**Review by spytheman — APPROVED** [review]
Good work. It does fix compilation, even though it does not fix the whole problem.

**Comment by Larpon** [comment]
Confirmed. The fix avoids the compile error and it now results in a compile error:
```
v run ~/.vmodules/sdl/examples/basic_window/
73224028c287 : at ???: RUNTIME ERROR: invalid memory access
/dev/shm/v_1000/basic_window.01HNPZ42YER0676RQTPR78QD3S.tmp.c:32178: by main
```

**Pull request merged**
