### PR TITLE
time: Implement parse_iso8601 with regex

### PR DESCRIPTION
**Pull request by zakuro9715**
Re implement parse_iso8601 with regex to support full iso8601 in future.

### CODE REVIEW

**Comment by spytheman** [comment]
This has implications for the compiler itself - `time` is used in many places.
Importing `regex` in `time` will make many binaries larger.
@medvednikov what do you think?

**Comment by penguindark** [comment]
I've the same opinion of @spytheman have regex in the core may be not the best thing.

**Comment by penguindark** [comment]
regex problems fixed :grin:

**Comment by zakuro9715** [comment]
Oh, That's right.

**Comment by zakuro9715** [comment]
```
import time
fn main() {
        t := time.parse_iso8601("2012-01-01T00:00:00.000000Z") or { panic(err) }
        println('$t')
}
```

Before `208 -rwxr-xr-x 1 zakuro zakuro 211856 12月  4 09:53 main`
After `256 -rwxr-xr-x 1 zakuro zakuro 259992 12月  4 09:56 main`

**Comment by zakuro9715** [comment]
BTY, Can i use global compiled regex multitime like this go code https://play.golang.org/p/Zio2J-CQugd

**Comment by JalonSolov** [comment]
Since  V doesn't do globals, no, not really.

**Comment by spytheman** [comment]
The closest is using a const, which will be initialized at runtime (when your program starts). However, if you need to modify it later, that would not work @zakuro9715 .

**Comment by spytheman** [comment]
This for example works, and compiles the input regex only once:
```v
import regex

const (
        a_or_b = (fn () regex.RE {
                x := regex.regex_opt('a|b') or {
                        panic(err)
                }
                return x
        }())
)

fn f(s string) bool {
        mut re := a_or_b
        start, _ := re.match_string(s)
        return start != -1
}

fn main() {
        println(f('a'))
        println(f('b'))
        println(f('c'))
}
```

**Comment by zakuro9715** [comment]
Is no discussion remainimg? If so, I'll close this

**Comment by medvednikov** [comment]
Sorry for the delay.

`regex` can't be used in `time`. It is possible to implement this format without regex.

**Pull request closed without merging**
