### PR TITLE
all: change `[1,2,3]!!` to `[1,2,3]!`

### PR DESCRIPTION
**Pull request by yuyi98**
This PR change all the `[1,2,3]!!` to `[1,2,3]!`.

### CODE REVIEW

**Comment by medvednikov** [comment]
The old syntax should be made an error.

**Comment by yuyi98** [comment]
OK, I'll change it.

**Comment by yuyi98** [comment]
Do we use the same messages?

**Comment by medvednikov** [comment]
Yes, same message. I'll update ved.

**Comment by yuyi98** [comment]
Thanks, I have made a PR to fix it in ved.

**Pull request merged**
