### PR TITLE
initial Implementation of ls() for windows

### PR DESCRIPTION
**Pull request by joe-conigliaro**
This PR Implements ls() for windows.
We will need to add utf16 wide char support eventually with WideCharToMultiByte
at least it's working for now can be upgraded for unicode

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks, I'll test this.

Do you think we should have `os_win.v` for Window stuff? There seems to be lots of Windows specific logic.

**Comment by joe-conigliaro** [comment]
@medvednikov no worries! Yeah maybe the structs and constants could go in os_win? or maybe ls could call ls_win or something from that file? whatever you think is the cleanest way to do it. 
Also eventually the utf8 support needs to be added, but the base functionality is there not much will need to change.

**Comment by Kogam22** [comment]
What if ls could internally call ls_win or ls_nix(Unix) according to the OS.

**Comment by medvednikov** [comment]
Thanks very much for this. V can now compile itself on Windows. On my VM at least.

**Comment by joe-conigliaro** [comment]
@medvednikov no problem, I knew this would fix the no input .v files error that's why i was keen to get it implemented. I actually noticed an error if the path doesn't exist I forgot to return []string. I'm going to fix and move into os_win.v

**Comment by joe-conigliaro** [comment]
@medvednikov I still can't compile on windows
```
C:\Users\joeco//.vlang//vtest.exe.c: In function 'Parser_fn_decl':
C:\Users\joeco//.vlang//vtest.exe.c:6418:25: error: missing terminating " character
 6418 |  Parser_genln( p , tos2("
      |                         ^
C:\Users\joeco//.vlang//vtest.exe.c:6419:9: error: stray '\' in program
 6419 | load_so(\"bounce.so\");
      |         ^
C:\Users\joeco//.vlang//vtest.exe.c:6419:10: error: missing terminating " character
 6419 | load_so(\"bounce.so\");
      |          ^~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:6420:1: error: 'pthread_t' undeclared (first use in this function); did you mean '_threadid'?
 6420 | pthread_t _thread_so;
      | ^~~~~~~~~
      | _threadid
C:\Users\joeco//.vlang//vtest.exe.c:6420:1: note: each undeclared identifier is reported only once for each function it appears in
C:\Users\joeco//.vlang//vtest.exe.c:6420:10: error: expected ')' before '_thread_so'
 6420 | pthread_t _thread_so;
      |          ^~~~~~~~~~~
      |          )
C:\Users\joeco//.vlang//vtest.exe.c:6421:55: error: missing terminating " character
 6421 | pthread_create(&_thread_so , NULL, &reload_so, NULL); ") ) ;
      |                                                       ^~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:6421:54: error: expected ')' before '}' token
 6421 | pthread_create(&_thread_so , NULL, &reload_so, NULL); ") ) ;
      |                                                      ^
      |                                                      )
 6422 |
 6423 |  }
      |  ~
C:\Users\joeco//.vlang//vtest.exe.c:6421:54: error: expected ')' before '}' token
 6421 | pthread_create(&_thread_so , NULL, &reload_so, NULL); ") ) ;
      |                                                      ^
      |                                                      )
 6422 |
 6423 |  }
      |  ~
C:\Users\joeco//.vlang//vtest.exe.c:6421:54: error: expected ';' before '}' token
 6421 | pthread_create(&_thread_so , NULL, &reload_so, NULL); ") ) ;
      |                                                      ^
      |                                                      ;
 6422 |
 6423 |  }
      |  ~
C:\Users\joeco//.vlang//vtest.exe.c: In function 'Parser_gen_json_for_type':
C:\Users\joeco//.vlang//vtest.exe.c:7417:30: error: missing terminating " character
 7417 |  dec = string_add(dec,  _STR("
      |                              ^
C:\Users\joeco//.vlang//vtest.exe.c:7419:1: error: expected expression before 'Option'
 7419 | Option %.*s(cJSON* root, %.*s* res) {
      | ^~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:7424:23: error: stray '\' in program
 7424 |       fprintf(stderr, \"Error in decode() for %.*s error_ptr=: %%s\\n\", error_ptr);
      |                       ^
C:\Users\joeco//.vlang//vtest.exe.c:7424:24: error: missing terminating " character
 7424 |       fprintf(stderr, \"Error in decode() for %.*s error_ptr=: %%s\\n\", error_ptr);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:7429:1: error: missing terminating " character
 7429 | ", t.len, t.str, dec_fn .name.len, dec_fn .name.str, dec_fn .name.len, dec_fn .name.str, t.len, t.str, t.len, t.str, t.len, t.str) ) ;
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:7431:30: error: missing terminating " character
 7431 |  enc = string_add(enc,  _STR("
      |                              ^
C:\Users\joeco//.vlang//vtest.exe.c:7434:19: error: stray '\' in program
 7434 | string res = tos2(\"\");
      |                   ^
C:\Users\joeco//.vlang//vtest.exe.c:7434:20: error: missing terminating " character
 7434 | string res = tos2(\"\");
      |                    ^~~~~
C:\Users\joeco//.vlang//vtest.exe.c:7435:1: error: missing terminating " character
 7435 | ", enc_fn .name.len, enc_fn .name.str, t.len, t.str) ) ;
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:7534:15: error: missing terminating " character
 7534 |  return  _STR("
      |               ^
C:\Users\joeco//.vlang//vtest.exe.c:7542:1: error: missing terminating " character
 7542 | ", typ.len, typ.str, s.len, s.str) ;
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:7571:15: error: missing terminating " character
 7571 |  return  _STR("
      |               ^
C:\Users\joeco//.vlang//vtest.exe.c:7576:1: error: missing terminating " character
 7576 | ", fn_name.len, fn_name.str, typ.len, typ.str) ;
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:7740:26: error: missing terminating " character
 7740 |  CGen_genln( cgen , tos2("
      |                          ^
C:\Users\joeco//.vlang//vtest.exe.c:7808:20: error: missing terminating " character
 7808 | void init_consts();") ) ;
      |                    ^~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:7850:26: error: missing terminating " character
 7850 |  CGen_genln( cgen , tos2("
      |                          ^
C:\Users\joeco//.vlang//vtest.exe.c:7852:1: error: missing terminating " character
 7852 | ") ) ;
      | ^~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:7931:26: error: missing terminating " character
 7931 |  CGen_genln( cgen , tos2("
      |                          ^
C:\Users\joeco//.vlang//vtest.exe.c:7963:1: error: missing terminating " character
 7963 | ") ) ;
      | ^~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:8026:26: error: missing terminating " character
 8026 |  CGen_genln( cgen , tos2(" int load_so(byteptr path) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:8027:10: error: stray '\' in program
 8027 |   printf(\"load_so %s\\n\", path); dlclose(live_lib); live_lib = dlopen(path, RTLD_LAZY);
      |          ^
C:\Users\joeco//.vlang//vtest.exe.c:8027:11: error: missing terminating " character
 8027 |   printf(\"load_so %s\\n\", path); dlclose(live_lib); live_lib = dlopen(path, RTLD_LAZY);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:8028:24: error: stray '\' in program
 8028 |   if (!live_lib) {puts(\"open failed\"); exit(1); return 0;}
      |                        ^
C:\Users\joeco//.vlang//vtest.exe.c:8028:25: error: missing terminating " character
 8028 |   if (!live_lib) {puts(\"open failed\"); exit(1); return 0;}
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:8029:3: error: missing terminating " character
 8029 |   ") ) ;
      |   ^~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:14900:25: error: missing terminating " character
14900 |  Parser_genln( p , _STR(";\n
      |                         ^~~~
C:\Users\joeco//.vlang//vtest.exe.c:14902:8: error: stray '\' in program
14902 |   puts(\"\\x1B[31mFAILED: %.*s() in %.*s:%d\\x1B[0m\");
      |        ^
C:\Users\joeco//.vlang//vtest.exe.c:14902:9: error: missing terminating " character
14902 |   puts(\"\\x1B[31mFAILED: %.*s() in %.*s:%d\\x1B[0m\");
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:14908:8: error: stray '\' in program
14908 |   puts(\"\\x1B[32mPASSED: %.*s()\\x1B[0m\");
      |        ^
C:\Users\joeco//.vlang//vtest.exe.c:14908:9: error: missing terminating " character
14908 |   puts(\"\\x1B[32mPASSED: %.*s()\\x1B[0m\");
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:14909:2: error: missing terminating " character
14909 | }", tmp.len, tmp.str, p ->cur_fn ->name.len, p ->cur_fn ->name.str, filename.len, filename.str, p ->scanner ->line_nr, p ->cur_fn ->name.len, p ->cur_fn ->name.str) ) ;
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\joeco//.vlang//vtest.exe.c:18239:24: error: missing terminating " character
18239 | main__HelpText =  tos2("
      |                        ^
C:\Users\joeco//.vlang//vtest.exe.c:18254:1: error: missing terminating " character
18254 | ");
      | ^~~
C:\Users\joeco//.vlang//vtest.exe.c:18293:1: error: expected declaration or statement at end of input
18293 | }
      | ^
V panic: clang error
```

**Pull request merged**
