### PR TITLE
Fix news_fetcher and json_primitives.

### PR DESCRIPTION
**Pull request by kcorey**

### CODE REVIEW

**Comment by AurelienFT** [comment]
It fix the example but it include two times the cJSON folder :
```
cc -I. -w -g -o news_fetcher /home/afoucault//.vlang0.0.12//news_fetcher.c -lcurl -I$HOME/code/v/thirdparty/cJSON -Dmac -I$HOME/code/v/thirdparty/cJSON  -lm -ldl -lpthread```

**Comment by kcorey** [comment]
Ah...would replacing 8 & 9 with the lines below fix it?
```
$if windows {
// TODO: windows support
	println('Windows isnt supported yet, sorry!')  
	exit(1)
}  
$if linux {
#flag -Dlinux -I$HOME/code/v/thirdparty/cJSON
} 
$if mac {
#flag -Dmac -I$HOME/code/v/thirdparty/cJSON
} 
```

**Comment by medvednikov** [comment]
It works now, can you git pull, rebuild, and try again?

**Comment by medvednikov** [comment]
Just tested it on a clean machine, it works.

**Pull request closed without merging**
