### PR TITLE
net.http: [windows] fix long networking

### PR DESCRIPTION
**Pull request by koplenov**
code for reproduction:
```vlang
module main

import time
import net.http


fn main() {

    start_time := time.now()
    http.get_text('https://vlang.io/version')
    end_time := time.now()

    println(end_time-start_time)
}
```

with this fix:
```
483.000ms
```

without this fix:
```
21.531s
```

windows only

### CODE REVIEW

**Comment by spytheman** [comment]
I can not reproduce the long waiting on my windows 11 laptop:
изображение

The times on master and on this PR are ~ the same, and definitely < 1s .

**Comment by JalonSolov** [comment]
Seems like a good change anyway.  Completely removes a file, while keeping a similar speed?  Reducing/simplifying code is a win.

**Comment by koplenov** [comment]
@spytheman, prof video from internal tests

https://github.com/vlang/v/assets/25139987/25cf6f75-779e-4f7c-ba63-5e0109a599d1


my config:
image

**Comment by koplenov** [comment]
it also fixes this bug: https://github.com/vlang/v/issues/19256

https://github.com/vlang/v/assets/25139987/3ea7b798-a250-45a0-99e0-aee9faeeddf7

**Comment by spytheman** [comment]
> Seems like a good change anyway. Completely removes a file, while keeping a similar speed? Reducing/simplifying code is a win. 

In general yes, but in this specific case, I am not sure. The PRItmakes it pass all https requests through `net.ssl` (mbedtls or openssl), while before, it used the windows specific MS Schannel implementation in thirdparty/vschannel/ . Absent a clear way to reproduce the problem this PR solves and to verify that it actually solves it on another PC, merging this will just trade one set of bugs for another imho (and the second set of bugs may be larger or smaller).

**Comment by spytheman** [comment]
> @spytheman, prof video from internal tests

I have no doubt, that you are experiencing the problem. I still have no good way to reproduce it locally, and thus I have no way to check, if it is something that is a net positive or a net negative (mbedtls is a thirdparty library that we supply in thirdparty/, and it has to be linked statically to each app that does `import net.ssl`, while Schannel is provided by MS themselves, and is linked dynamically, and we just have a very small wrapper for it ... which may be good or bad, but is definitely different).

**Comment by spytheman** [comment]
@medvednikov what do you think?

**Comment by medvednikov** [comment]
I agree with you. Schannel should be used on Windows, @joe-conigliaro spent a lot of time to make it work.

**Comment by koplenov** [comment]
1. how can i gather more information about the problem? how to profile? how to see Schannel usage logs? (there is no information in the system's events)

2. why is it worth using Schannel? why is it worth using Schannel instead of a more stable solution currently?

**Comment by shove70** [comment]
compatibility
Schannel is a part of the Windows, making it available on all supported Windows versions, including both desktop and server editions. It seamlessly integrates with other Windows components and is compatible with various network applications and services.

Performance
Schannel efficiently implements encryption and decryption algorithms within the windows. It's optimized for multi-core processors and hardware accelerators, delivering fast and high-performance secure communication.

Schannel is part of the Windows system, so using it on Windows is a natural choice.

**Comment by shove70** [comment]
using `backend_nix.c.v` instead of `...windows.v.c` may not work on all versions of windows,  I haven't actually tried it, but it should be

**Comment by koplenov** [comment]
@shove70

okay

what are some arguments in defense of using openssl instead of schannel? (interested in different point of view)


> compatibility
strange, I see a lot of information on the internet about enabling or disabling some part of functionality via the registry (e.g. tls 1.2 support).


should it be a matter of user's attention?

if something doesn't work, can schannel be upgraded separately from the system? and downgrade the version?



> Performance
if it's part of the system - does that say it's faster?



> I haven't actually tried it, but it should be

we are talking about windows 7, windows 8, windows 8.1+?

**Comment by shove70** [comment]
How to choose, depending on the trade-off of different scenarios, is not absolute.

**Comment by spytheman** [comment]
I think, that we can make using `net.ssl` optional, behind `-d no_vschannel`.
i.e. the default will be the same as before, but people could compile using `-d no_vschannel` and get `net.http` to use the `net.ssl` (i.e. mbedtls by default), like it does on non windows systems.

**Comment by spytheman** [comment]
Then, we could test both modes, and if `-d no_vschannel` proves to solve more problems, in time switch the default.

**Comment by spytheman** [comment]
> what are some arguments in defense of using openssl instead of schannel?

I would not defend openssl, since it is very big, and very hard to compile, and use properly on windows, unlike mbedtls, that is why we distribute it in thirdparty/, instead of openssl.

mbedtls has the big benefit of portability and working (or not working) more or less the same everywhere.

> should it be a matter of user's attention?

I think yes, absent a reliable way to reproduce your problem, we should have an option, so that the user can choose one way or another, and if there are other timeout issues, we can suggest using that option too, to see if it helps or not. Hopefully in time, we will have more reliable data.

> if something doesn't work, can schannel be upgraded separately from the system? and downgrade the version?

No, only MS can update it. It is both a plus (platform stability) and a minus (if there is a problem, you are stuck with whatever tools MS provides for solving it).

> if it's part of the system - does that say it's faster?

Afaik MS does not claim that it is faster (compared to what?). It is supported though, and it is the official way to use https on windows. See https://learn.microsoft.com/en-us/windows/win32/secauthn/secure-channel?source=recommendations .

> we are talking about windows 7, windows 8, windows 8.1+?

Yes, and probably 64bit XP too, although I am not sure, if they support it there ... Probably not, since official extended support for XP ended ~10 years ago.

**Comment by spytheman** [comment]
> 1. how can i gather more information about the problem? how to profile? how to see Schannel usage logs? (there is no information in the system's events)

I do not know, if there are native tools to profile it, but you can potentially instrument the `thirdparty/vschannel/vschannel.c` wrapper with `fprintf(stderr, "some log message\n");` calls, and see where/when the delay happens.

>     2. why is it worth using Schannel? why is it worth using Schannel instead of a more stable solution currently?

Because MS supports it and recommends it, and Windows is their platform.

**Comment by spytheman** [comment]
You can also try using V's native `-trace-calls` option, to run your example, but it will only instrument the V functions/methods, not the V wrapper.

**Comment by koplenov** [comment]
image

WSAConnectByNameW takes a long time

**Comment by spytheman** [comment]
Can you try changing your DNS server settings to `1.1.1.1` and `8.8.8.8` temporarily?

**Comment by shove70** [comment]
> I think, that we can make using `net.ssl` optional, behind `-d no_vschannel`. i.e. the default will be the same as before, but people could compile using `-d no_vschannel` and get `net.http` to use the `net.ssl` (i.e. mbedtls by default), like it does on non windows systems.

Good idea 👍

**Comment by koplenov** [comment]
image

image


same

@spytheman

**Comment by JalonSolov** [comment]
Do you have anti-virus software besides the default Windows Defender?  That can seriously impact 'net performance at times.  As well as disk performance, etc., etc.

Defender doesn't seem to be _that_ bad compared to the rest, at least.

**Comment by koplenov** [comment]
image

i turned off the antivirus, and the result is the same

what else can i try?

**Comment by spytheman** [comment]
Try `./v -d no_vschannel run examples/fetch.v` . It should work with the latest commit 221be7a .

**Comment by koplenov** [comment]
image

the flag works - as temporary solution it's cool too

**Pull request merged**
