### PR TITLE
time.format: optimize time format api

### PR DESCRIPTION
**Pull request by yuyi98**
This PR optimize time format api.
```v
fn (t Time) format(fmt_dlmtr FormatDelimiter, fmt_time FormatTime, fmt_date FormatDate) string

fn (t Time) format_date(fmt_dlmtr FormatDelimiter, fmt_date FormatDate) string
fn (t Time) format_time(fmt_time FormatTime) string

fn (t Time) format_ymd() string
fn (t Time) format_dmy() string

fn (t Time) format_ymd_hm() string
fn (t Time) format_ymd_hms() string

fn (t Time) format_hm() string
fn (t Time) format_hm12() string
fn (t Time) format_hms() string
fn (t Time) format_md() string

fn (t Time) format_clean() string
fn (t Time) format_clean12() string
```

**Change:**
```v
get_fmt_str => format
get_fmt_date_str  =>  format_date
get_fmt_time_str  =>  format_time

format   =>  format_ymd_hm
format_ss  => format_ymd_hms
hhmm  => format_hm
hhmmss  => format_hms
hhmm12  => format_hm12
ymmdd   =>  format_ymd
ddmmy   =>  format_dmy
md   =>  format_md
clean   =>  format_clean
clean12   =>  format_clean12
```

### CODE REVIEW

**Comment by medvednikov** [comment]
I think instead of having format_xxx, we should just have format(.enum)

**Comment by yuyi98** [comment]
It is recommended to keep a few commonly used format_xxx.

**Comment by yuyi98** [comment]
```v
fn (t Time) format(fmt_dlmtr FormatDelimiter, fmt_time FormatTime, fmt_date FormatDate) string

fn (t Time) format_date(fmt_dlmtr FormatDelimiter, fmt_date FormatDate) string
fn (t Time) format_time(fmt_time FormatTime) string

fn (t Time) format_clean() string
fn (t Time) format_clean12() string
```

Remove some format_xxx().

**Comment by danieldaeschle** [comment]
Where is it recommended? Any source? We're here to break bad habits :D

**Pull request closed without merging**
