### PR TITLE
22:40: Fix parser not making a complete first pass on file

### LINKED ISSUE #1481: order- or main-related compilation error ?
**V version:** 
0.1.17
**OS:** 
MacOS 10.14.6
**What did you do?**
tried to compile the following:
println('hello')

struct User {
    id int 
    name string
} 

struct Repo {
    users []User 
}

**What did you expect to see?**
successful compilation, because it does compile if I put the println() underneath the structs
 
**What did you see instead?**
get_type() bad type
pass=2 fn=`main`
panic: break.v:9
unknown type `User`

After reading some more documentation I was confused about what to expect:
* should the compiler have warned about a missing main()?
* is this supposed to work in the first place?

### PR DESCRIPTION
**Pull request by tobyjwebb**
Fix parser not doing a complete first pass on a .v file if it finds any statements before declarations.

Fixes #1481

### CODE REVIEW

**Comment by tobyjwebb** [comment]
Wait...

Should this code compile?:

```
fn main() {
    struct User {
        id int
    }
    println('hello')
}
```
Because if you put the struct definition inside of main(), it doesn't like it :(

**Comment by medvednikov** [comment]
It's not valid V right now, but I guess it can be allowed in the future.

**Comment by medvednikov** [comment]
Thanks for fixing it!

**Comment by tobyjwebb** [comment]
No problem :) Thanks for making such a cool language!

**Pull request merged**
