### PR TITLE
Crossbuild tests

### PR DESCRIPTION
**Pull request by aguspiza**
cross builing in travis with windows tests

### CODE REVIEW

**Comment by medvednikov** [comment]
Hi,

Sorry for the delay. This is actually a very good PR. Can you please fix the conflict? I'll merge it right away.

**Comment by aguspiza** [comment]
> Hi,
> 
> Sorry for the delay. This is actually a very good PR. Can you please fix the conflict? I'll merge it right away.

Well it was. Now you seem to force to download https://github.com/vlang/v/releases/download/v0.1.10/winroot.zip for cross building for windows. My guess is that you do that for MacOSX, but on linux you should go with whatever mingw provides.

Anyway perhaps both are half baked solutions and we should try to build with one path by changing target and cc.

**Comment by aguspiza** [comment]
Ok I have implemented a better user_os(). I am not happy at all, we need to do a lot of cleanup in crossbuilding but travis is green.

**Comment by aguspiza** [comment]
Sorry but i think i was wrong and there is no need to implement uname, so i just resolved the conflict.

**Comment by medvednikov** [comment]
Sorry @aguspiza 

I didn't merge this because this only works for building Windows binaries on Linux.

Building Linux, FreeBSD, etc binaries on Windows and macOS would have to be implemented differently.

AFAIK there's no mingw-like package for those systems.

I'll be using Clang instead.

The test you implemented will be added to Travis.

**Pull request closed without merging**
