### PR TITLE
Sarctiann where tool

### PR DESCRIPTION
**Pull request by Sarctiann**
# Add **vwhere** tool
```
Usage:
  v where [symbol_type] [symbol_name] [params]

Examples:
  v where fn main
  v where struct User
  v where fn say_hello -mod Person
  v where fn area -m-of Square
  v where interface callable -dir some -dir other

--------------------------------------------------------------------------------
Prints the location of the searched symbols in the scope of the current project.
--------------------------------------------------------------------------------

symbol_name can be:
  fn                    (by default if omit [symbol_type])
  struct
  interface
  enum
  const
  var
  regexp

params:
  -mod  [mod_name]      Restrict to search only within of the given module,
                        if not provided, search in entire project.
  -dir  [dir_path]      Restrict to search non recursive within the given 
                        folder/s, if not provided, search in entire v scope.
  -vis  [visibility]    Can be: all, pub, pri (all by default if not provided).
                        Restrict to search symbols with the given visibility.
  -mut  [mutability]    Can be: any, yes, not (any by default if not provided).
                        Restrict to search symbols with the given mutability.
  -m-of [struct_name]   (just for fn symbol_name).
                        Restrict to search fn as method of the given struct.

Note: 
  This tool is inspired by the vdoc tool and its design. However, this is 
  for a more specific use, and can be improved. 

```

### CODE REVIEW

**Comment by JalonSolov** [comment]
`cmd/tools/vwhere/finder_utils.v` needs `v fmt -w` run on it.

**Comment by Sarctiann** [comment]
Done!

**Comment by Sarctiann** [comment]
just in case, I clarify that there are several tests that are always reported to me since before I added my code, also my code does not touch the compiler or other parts

**Comment by Sarctiann** [comment]
Oh, it seems that it was an optical illusion 😢 haha

**Comment by Sarctiann** [comment]
for some reason it seems that it is not recognizing the declarations I have made in `utils_finder.v` and in `finder.v`

why would it be like this?

Am I forced to do it all within the same file?

I suppose not, since in other tests it did find the declarations. But you tell me please

**Comment by ken0x0a** [comment]
Related to vlang/rfcs#22

This kind of `v` subcommand utilities can be useful, and I think merging into this repo might slowdown improvement speed of tools.
So, it's good either
- having a way to add subcommand by user;
- having a way to install v  and executing `vwhere` instead of `v where`

**Comment by spytheman** [comment]
> 

I am not sure I understand - how is that PR related to the RFC? 

This PR implements a tool, that is part of the main V distribution, while the RFC is related to allowing custom user tools, which are not part of the main V distribution.

Do you mean that this tool should be a user tool, and instead we should implement/improve the RFC first?

**Comment by ken0x0a** [comment]
Yes,
I mean, this tool can be a user tool.

I think this tool is cool, and good idea.
But I have doubt that, this tool will be use that much.


I want to bring news related to Rust to explain my thought.
Rust added subcommand `add` into `cargo` command these days.
There have been a user tool for a long time.
They added as many users are using it and proved to be useful.

I'm not sure that, this tool will be used by that much users.
I thought it'g good to have time to know that.


I often use ripgrep (rg) and I can use that in most case.
I think it's good for users to know how to use those ("rg", "ag" ...) general purpose tool than V specific tool...


| new command                                     |                             |
| ----------------------------------------------- | --------------------------- |
| v where fn main                                 | rg 'fn main\('              |
| v where struct User                             | rg 'struct User '           |
| v where fn say_hello -mod Person                | rg 'fn say_hello\(' person  |
| v where fn area -m-of Square                    | rg 'fn \(.*Square\) area\(' |
| v where interface callable -dir some -dir other | **I DON'T KNOW**            |

**Comment by spytheman** [comment]
I agree - I also do use ripgrep, which is a general tool, and much faster. For your last example:
`v where interface callable -dir some -dir other` would be `rg 'interface callable' some/ other/`

**Comment by Larpon** [comment]
Yes, `ripgrep` can do this much faster and with less typing

**Comment by ken0x0a** [comment]
espanso also might help us. We can register expression in it if we need.

https://espanso.org/docs/matches/forms/

```yml
  - trigger: vwhfn
    form: |-
      rg 'fn [[name]]\('
  - trigger: vwhmem
    form: |-
      rg 'fn \(.*[[Struct]]\) [[method]]\('
```

**Comment by Sarctiann** [comment]
well, this isn't really correct

| new command	| ripgrep 
|:- |:-
| v where fn main	| rg 'fn main('
| v where struct User	| rg 'struct User '
| v where fn say_hello -mod Person	| rg 'fn say_hello(' person
| v where fn area -m-of Square	| rg 'fn (.*Square) area('
| v where interface callable -dir some -dir other	| rg 'interface callable' some/ other/

because:
`v where fn main` search for a function or a method "main" (if you omit -m-of, search for both)
`v where struct User` this is the same yes... algo with interfaces and enums
`rg 'fn say_hello(' person` I think this one will fail since you omit "(p Person)" in the middle
Also, not in the examples but you can find a const and v where will find it even if the word "const" above.
Then you also can filter by mutability or visibility

I agree that rg is faster. But maybe you or other can improve this tool too.

**Comment by spytheman** [comment]
`rg 'fn say_hello(' person` means that it will search in the folder `person/` only. In V modules are folders, so it effectively restricts it, to just the local module `person`.

While in your case: `v where fn say_hello -mod Person` , `-mod` is confusing, if you are passing a method *receiver* instead, instead of a module name, like we assumed, given the name `mod`.

 You could provide something like: `v where method Person.say_hello` which would search for a method `say_hello`, on a type named Person, or you could change the flag to something like `-receiver`.

**Comment by spytheman** [comment]
> Also, not in the examples but you can find a const and v where will find it even if the word const above.

That is a good point, and one of the reasons, that I do not like `const ( ... name = value ... )` constructs, preferring multiple `const name = value` lines instead.
Multiline constructs do make generic line oriented tools less useful.

**Comment by spytheman** [comment]
image

**Comment by Sarctiann** [comment]
https://github.com/vlang/v/pull/15014#issuecomment-1182747123

Now this is pending. I think it would be worth having the symbol types separately:
* `fn`
* `method`
I also like the dot notation

**Pull request merged**
