### PR TITLE
io: input/output streams

### PR DESCRIPTION
**Pull request by LouisSchmieder**
This PR adds input & output streams. Now they're only implemented for network. There is a new module `io` which has two interfaces `InputStream` and `OutputStream` which can used for everything and they can have multiple impementations.

### CODE REVIEW

**Comment by JalonSolov** [comment]
I think this would be better as separate 'inputstream.v` and `outputstream.v`, then add net specific stuff in the `net` module.

**Comment by LouisSchmieder** [comment]
yeah I think I will do this later but I don't know how the interfaces reacts to it

**Comment by Gladear** [comment]
Since the OutputStream interface methods all start with `write`, it sounds to me like the InputStream methods should start with `read`.
What your opinion on the matter ?

**Comment by LouisSchmieder** [comment]
I don't know it was just quick names for now, but I think the most logical would be `put` and `get` because these are DataStreams imo

**Comment by JalonSolov** [comment]
A lot of V is patterned after Go.  In Go, it is all `read` and `write` for streams.

**Comment by LouisSchmieder** [comment]
Okay

**Pull request merged**
