### PR TITLE
picoev: use `net` C definitions

### PR DESCRIPTION
**Pull request by Terisback**
Fixes errors from https://discord.com/channels/592103645835821068/592114487759470596/911186148443979807
```v
/home/astro/Projects/V/v-main/vlib/picoev/picoev.v:229:7: error: field `sin_family` of struct `C.sockaddr_in` is immutable
  227 |     }
  228 |     mut addr := C.sockaddr_in{}
  229 |     addr.sin_family = C.AF_INET
      |          ~~~~~~~~~~
  230 |     addr.sin_port = C.htons(config.port)
  231 |     addr.sin_addr.s_addr = C.htonl(C.INADDR_ANY)
/home/astro/Projects/V/v-main/vlib/picoev/picoev.v:230:7: error: field `sin_port` of struct `C.sockaddr_in` is immutable
  228 |     mut addr := C.sockaddr_in{}
  229 |     addr.sin_family = C.AF_INET
  230 |     addr.sin_port = C.htons(config.port)
      |          ~~~~~~~~
  231 |     addr.sin_addr.s_addr = C.htonl(C.INADDR_ANY)
  232 |     size := 16 // sizeof(C.sockaddr_in)
/home/astro/Projects/V/v-main/vlib/picoev/picoev.v:231:16: error: `u32` has no property `s_addr`
  229 |     addr.sin_family = C.AF_INET
  230 |     addr.sin_port = C.htons(config.port)
  231 |     addr.sin_addr.s_addr = C.htonl(C.INADDR_ANY)
      |                   ~~~~~~
  232 |     size := 16 // sizeof(C.sockaddr_in)
  233 |     bind_res := C.bind(fd, voidptr(unsafe { &net.Addr(&addr) }), size)
  ```

### CODE REVIEW

**Comment by spytheman** [comment]
For some reason, this PR has a significant negative performance impact on pico (both `Latency` and `Requests/sec` are better on the current master):
```
2[09:22:42]delian@nemesis: (picoev-use-net-c-definitions) /v/cleanv $ ./v run examples/pico/pico.v > /dev/null &
[2] 329782
0[09:23:00]delian@nemesis: (picoev-use-net-c-definitions) /v/cleanv $ wrk -t1 -c10 -d10s http://localhost:8088/t
Running 10s test @ http://localhost:8088/t
  1 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.25ms    3.41ms  67.08ms   91.86%
    Req/Sec    68.25k     6.97k   86.85k    76.00%
  678147 requests in 10.00s, 81.49MB read
Requests/sec:  67806.43
Transfer/sec:      8.15MB
0[09:23:32]delian@nemesis: (picoev-use-net-c-definitions) /v/cleanv $ wrk -t1 -c10 -d10s http://localhost:8088/t
Running 10s test @ http://localhost:8088/t
  1 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.36ms    3.87ms  84.18ms   92.01%
    Req/Sec    68.41k     6.35k   84.70k    68.00%
  679294 requests in 10.00s, 81.63MB read
Requests/sec:  67912.87
Transfer/sec:      8.16MB
0[09:23:51]delian@nemesis: (picoev-use-net-c-definitions) /v/cleanv $ wrk -t1 -c10 -d10s http://localhost:8088/t
Running 10s test @ http://localhost:8088/t
  1 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.35ms    3.54ms  59.17ms   91.40%
    Req/Sec    68.05k     6.04k   80.17k    77.00%
  676584 requests in 10.00s, 81.30MB read
Requests/sec:  67637.11
Transfer/sec:      8.13MB
0[09:24:04]delian@nemesis: (picoev-use-net-c-definitions) /v/cleanv $ git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
0[09:24:13]delian@nemesis: (master) /v/cleanv $ kill %2
[2]-  Terminated              ./v run examples/pico/pico.v
0[09:24:22]delian@nemesis: (master) /v/cleanv $ 
0[09:24:24]delian@nemesis: (master) /v/cleanv $ ./v run examples/pico/pico.v > /dev/null &
[2] 329882
0[09:24:36]delian@nemesis: (master) /v/cleanv $ wrk -t1 -c10 -d10s http://localhost:8088/t
Running 10s test @ http://localhost:8088/t
  1 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   475.57us    1.50ms  31.57ms   93.92%
    Req/Sec    72.92k     7.14k   95.72k    71.00%
  724978 requests in 10.00s, 87.12MB read
Requests/sec:  72465.60
Transfer/sec:      8.71MB
0[09:24:52]delian@nemesis: (master) /v/cleanv $ wrk -t1 -c10 -d10s http://localhost:8088/t
Running 10s test @ http://localhost:8088/t
  1 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   544.89us    1.49ms  24.31ms   92.51%
    Req/Sec    72.43k     7.79k   93.10k    73.00%
  719581 requests in 10.00s, 86.47MB read
Requests/sec:  71931.67
Transfer/sec:      8.64MB
0[09:25:05]delian@nemesis: (master) /v/cleanv $ wrk -t1 -c10 -d10s http://localhost:8088/t
Running 10s test @ http://localhost:8088/t
  1 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   514.27us    1.49ms  35.24ms   93.01%
    Req/Sec    72.57k     7.62k   89.26k    75.00%
  721615 requests in 10.00s, 86.71MB read
```

**Comment by spytheman** [comment]
imho, it is better to split it into 2: 
a) only removing the conflicting definitions, and doing the minimal changes to fix code compilation
b) everything else (using `net.listen_tcp` etc, instead of the direct C calls that it used before)

**Comment by kahsa** [comment]
`net` uses only `select`, but `picoev` uses `epoll` and `kqueue` too.
and I doubt `select` in `net` seems to have some bugs.

**Comment by kahsa** [comment]
https://discord.com/channels/592103645835821068/697813437237166131/898082671492734976

`net` seems to have severe problem of performance.

**Comment by spytheman** [comment]
> `net` uses only `select`, but `picoev` uses `epoll` and `kqueue` too. and I doubt `select` in `net` seems to have some bugs.

I think the performance degradation problem is due to the the socket initialization flags, not in the select loop in `net`. `picoev` still uses its own loop, the PR does not change that.

**Pull request merged**
