### PR TITLE
checker: fix const variable type error when global variable with the same name exists (fix #15686)

### LINKED ISSUE #15686: checker bug: If a global variable name is the same as the const variable name in a module, the checker mistakenly found the type of the global variable when analyzing the const variable type.
OS: macos, macOS, 12.5.1, 21G83
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
CC version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

getwd: /Users/shove
vmodules: /Users/shove/.vmodules
vroot: /usr/local/v
vexe: /usr/local/v/v
vexe mtime: 2022-09-07 05:34:43
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 21b2a98

Git version: git version 2.32.1 (Apple Git-133)
Git vroot status: 0.3-469-g21b2a984
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 46662e20

**What did you do?**

```v
import time

__global start_time time.Time

fn main() {
}
```

**What did you expect to see?**

No error. 

**What did you see instead?**

```
/usr/local/v/vlib/time/time_darwin.c.v:49:10: error: infix expr: cannot use `time.Time` (right expression) as `u64`
   47 |         }
   48 |     }
   49 |     return (tm - time.start_time) * time.time_base.numer / time.time_base.denom
      |             ~~~~~~~~~~~~~~~~~~~~
   50 | }
   51 |
/usr/local/v/vlib/time/time_darwin.c.v:62:10: error: infix expr: cannot use `time.Time` (right expression) as `u64`
   60 |         }
   61 |     }
   62 |     return (tm - time.start_time) * time.time_base.numer / time.time_base.denom
      |             ~~~~~~~~~~~~~~~~~~~~
   63 | }
   64 |
```

### PR DESCRIPTION
**Pull request by shove70**
```v
import time

__global start_time time.Time

fn main() {
	println(start_time)
}
```

output:

```
v -enable-globals run .
0000-00-00 00:00:00
```

Maybe this is not a good way to fix it. Please give me your advice :)

### CODE REVIEW

**Comment by spytheman** [comment]
I do not understand what does that fix?

The given example already works on master:
image

**Comment by shove70** [comment]
https://github.com/vlang/v/issues/15686

MacOS

V full version: V 0.3.1 https://github.com/vlang/v/commit/21b2a9841acc74df6db6f8e82d9f63b449ad927e

Git version: git version 2.32.1 (Apple Git-133)
Git vroot status: 0.3-469-g21b2a984
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 https://github.com/vlang/v/commit/46662e209ea9a94f239d3d8eb9c545753cda459c

**Comment by shove70** [comment]
vlib/time/time_darwin.c.v:

```v
module time

#include <mach/mach_time.h>

const (
	// start_time is needed on Darwin and Windows because of potential overflows
	start_time = C.mach_absolute_time()
	time_base  = init_time_base()
	...
)

```

Both ```time_darwin.c.v``` and ```time_linux_c.v``` have ```start_time``` is the const variable, but time_linux.c.v does not, so there is no problem under Linux

**Comment by shove70** [comment]
you try this:

```v
import bitfield

__global slot_size string

fn main() {
	println(slot_size)
}

```

output:

```
$ v -enable-globals run .
a.v:18:8: warning: module 'bitfield' is imported but never used
   16 | 
   17 | 
   18 | import bitfield
      |        ~~~~~~~~
   19 | 
   20 | __global slot_size string
/usr/local/v/vlib/bitfield/bitfield.v:121:49: error: infix expr: cannot use `string` (right expression) as `int`
  119 |         return 0
  120 |     }
  121 |     return int((instance.field[bitslot(bitnr)] >> (bitnr % bitfield.slot_size)) & u32(1))
      |                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~
  122 | }
  123 |
/usr/local/v/vlib/bitfield/bitfield.v:296:23: error: infix expr: cannot use `string` (right expression) as `int`
  294 |     }
  295 |     // find offset bit and offset slot
  296 |     offset_bit := input1.size % bitfield.slot_size
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~
  297 |     offset_slot := input1.size / bitfield.slot_size
  298 |     for i in 0 .. zbitnslots(input2.size) {
/usr/local/v/vlib/bitfield/bitfield.v:297:24: error: infix expr: cannot use `string` (right expression) as `int`
  295 |     // find offset bit and offset slot
  296 |     offset_bit := input1.size % bitfield.slot_size
  297 |     offset_slot := input1.size / bitfield.slot_size
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~
  298 |     for i in 0 .. zbitnslots(input2.size) {
  299 |         output.field[i + offset_slot] |= u32(input2.field[i] << u32(offset_bit))
/usr/local/v/vlib/bitfield/bitfield.v:314:5: error: infix expr: cannot use `string` (right expression) as `int`
  312 |      * If offset_bit is zero, no additional copies needed.
  313 |     */
  314 |     if (output_size - 1) % bitfield.slot_size < (input2.size - 1) % bitfield.slot_size {
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  315 |         for i in 0 .. zbitnslots(input2.size) {
  316 |             output.field[i + offset_slot + 1] |= u32(input2.field[i] >> u32(bitfield.slot_size - offset_bit))
/usr/local/v/vlib/bitfield/bitfield.v:316:87: error: string types only have the following operators defined: `==`, `!=`, `<`, `>`, `<=`, `>=`, and `+`
  314 |     if (output_size - 1) % bitfield.slot_size < (input2.size - 1) % bitfield.slot_size {
  315 |         for i in 0 .. zbitnslots(input2.size) {
  316 |             output.field[i + offset_slot + 1] |= u32(input2.field[i] >> u32(bitfield.slot_size - offset_bit))
      |                                                                                                ^
  317 |         }
  318 |     } else if (output_size - 1) % bitfield.slot_size > (input2.size - 1) % bitfield.slot_size {
/usr/local/v/vlib/bitfield/bitfield.v:318:12: error: infix expr: cannot use `string` (right expression) as `int`
  316 |             output.field[i + offset_slot + 1] |= u32(input2.field[i] >> u32(bitfield.slot_size - offset_bit))
  317 |         }
  318 |     } else if (output_size - 1) % bitfield.slot_size > (input2.size - 1) % bitfield.slot_size {
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  319 |         for i in 0 .. zbitnslots(input2.size) - 1 {
  320 |             output.field[i + offset_slot + 1] |= u32(input2.field[i] >> u32(bitfield.slot_size - offset_bit))
/usr/local/v/vlib/bitfield/bitfield.v:320:87: error: string types only have the following operators defined: `==`, `!=`, `<`, `>`, `<=`, `>=`, and `+`
  318 |     } else if (output_size - 1) % bitfield.slot_size > (input2.size - 1) % bitfield.slot_size {
  319 |         for i in 0 .. zbitnslots(input2.size) - 1 {
  320 |             output.field[i + offset_slot + 1] |= u32(input2.field[i] >> u32(bitfield.slot_size - offset_bit))
      |                                                                                                ^
  321 |         }
  322 |     }
/usr/local/v/vlib/bitfield/bitfield.v:358:10: error: infix expr: cannot use `string` (right expression) as `int`
  356 |     size := instance.size
  357 |     bitnslots := zbitnslots(size)
  358 |     tail := size % bitfield.slot_size
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~
  359 |     mut count := 0
  360 |     for i in 0 .. bitnslots - 1 {
/usr/local/v/vlib/bitfield/bitfield.v:361:12: error: range types do not match
  359 |     mut count := 0
  360 |     for i in 0 .. bitnslots - 1 {
  361 |         for j in 0 .. bitfield.slot_size {
      |                  ^
  362 |             if u32(instance.field[i] >> u32(j)) & u32(1) == u32(1) {
  363 |                 count++
/usr/local/v/vlib/bitfield/bitfield.v:362:32: error: cannot cast string to `u32`, use `j.u32()` instead.
  360 |     for i in 0 .. bitnslots - 1 {
  361 |         for j in 0 .. bitfield.slot_size {
  362 |             if u32(instance.field[i] >> u32(j)) & u32(1) == u32(1) {
      |                                         ~~~~~~
  363 |                 count++
  364 |             }
/usr/local/v/vlib/bitfield/bitfield.v:415:18: error: infix expr: cannot use `string` (right expression) as `int`
  413 |     }
  414 |     mut output := new(end - start)
  415 |     start_offset := start % bitfield.slot_size
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
  416 |     end_offset := (end - 1) % bitfield.slot_size
  417 |     start_slot := start / bitfield.slot_size
/usr/local/v/vlib/bitfield/bitfield.v:416:16: error: infix expr: cannot use `string` (right expression) as `int`
  414 |     mut output := new(end - start)
  415 |     start_offset := start % bitfield.slot_size
  416 |     end_offset := (end - 1) % bitfield.slot_size
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  417 |     start_slot := start / bitfield.slot_size
  418 |     end_slot := (end - 1) / bitfield.slot_size
/usr/local/v/vlib/bitfield/bitfield.v:417:16: error: infix expr: cannot use `string` (right expression) as `int`
  415 |     start_offset := start % bitfield.slot_size
  416 |     end_offset := (end - 1) % bitfield.slot_size
  417 |     start_slot := start / bitfield.slot_size
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~
  418 |     end_slot := (end - 1) / bitfield.slot_size
  419 |     output_slots := zbitnslots(end - start)
/usr/local/v/vlib/bitfield/bitfield.v:418:14: error: infix expr: cannot use `string` (right expression) as `int`
  416 |     end_offset := (end - 1) % bitfield.slot_size
  417 |     start_slot := start / bitfield.slot_size
  418 |     end_slot := (end - 1) / bitfield.slot_size
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  419 |     output_slots := zbitnslots(end - start)
  420 |     if output_slots > 1 {
/usr/local/v/vlib/bitfield/bitfield.v:424:103: error: string types only have the following operators defined: `==`, `!=`, `<`, `>`, `<=`, `>=`, and `+`
  422 |             for i in 0 .. output_slots - 1 {
  423 |                 output.field[i] = u32(input.field[start_slot + i] >> u32(start_offset))
  424 |                 output.field[i] = output.field[i] | u32(input.field[start_slot + i + 1] << u32(bitfield.slot_size - start_offset))
      |                                                                                                                   ^
  425 |             }
  426 |         } else {
/usr/local/v/vlib/bitfield/bitfield.v:433:16: error: infix expr: cannot use `string` (right expression) as `int`
  431 |     }
  432 |     if start_offset > end_offset {
  433 |         output.field[(end - start - 1) / bitfield.slot_size] = u32(input.field[end_slot - 1] >> u32(start_offset))
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  434 |         mut mask := u32((1 << (end_offset + 1)) - 1)
  435 |         mask = input.field[end_slot] & mask
/usr/local/v/vlib/bitfield/bitfield.v:436:45: error: string types only have the following operators defined: `==`, `!=`, `<`, `>`, `<=`, `>=`, and `+`
  434 |         mut mask := u32((1 << (end_offset + 1)) - 1)
  435 |         mask = input.field[end_slot] & mask
  436 |         mask = u32(mask << u32(bitfield.slot_size - start_offset))
      |                                                   ^
  437 |         output.field[(end - start - 1) / bitfield.slot_size] |= mask
  438 |     } else if start_offset == 0 {
/usr/local/v/vlib/bitfield/bitfield.v:437:16: error: infix expr: cannot use `string` (right expression) as `int`
  435 |         mask = input.field[end_slot] & mask
  436 |         mask = u32(mask << u32(bitfield.slot_size - start_offset))
  437 |         output.field[(end - start - 1) / bitfield.slot_size] |= mask
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  438 |     } else if start_offset == 0 {
  439 |         mut mask := u32(0)
/usr/local/v/vlib/bitfield/bitfield.v:440:39: error: string types only have the following operators defined: `==`, `!=`, `<`, `>`, `<=`, `>=`, and `+`
  438 |     } else if start_offset == 0 {
  439 |         mut mask := u32(0)
  440 |         if end_offset == bitfield.slot_size - 1 {
      |                                             ^
  441 |             mask = u32(-1)
  442 |         } else {
/usr/local/v/vlib/bitfield/bitfield.v:446:16: error: infix expr: cannot use `string` (right expression) as `int`
  444 |             mask = mask - u32(1)
  445 |         }
  446 |         output.field[(end - start - 1) / bitfield.slot_size] = (input.field[end_slot] & mask)
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  447 |     } else {
  448 |         mut mask := u32(((1 << (end_offset - start_offset + 1)) - 1) << start_offset)
/usr/local/v/vlib/bitfield/bitfield.v:451:16: error: infix expr: cannot use `string` (right expression) as `int`
  449 |         mask = input.field[end_slot] & mask
  450 |         mask = u32(mask >> u32(start_offset))
  451 |         output.field[(end - start - 1) / bitfield.slot_size] |= mask
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  452 |     }
  453 |     return output
/usr/local/v/vlib/bitfield/bitfield.v:463:12: error: range types do not match
  461 |     mut output := new(size)
  462 |     for i := 0; i < (bitnslots - 1); i++ {
  463 |         for j in 0 .. bitfield.slot_size {
      |                  ^
  464 |             if u32(instance.field[i] >> u32(j)) & u32(1) == u32(1) {
  465 |                 output.set_bit(size - i * bitfield.slot_size - j - 1)
/usr/local/v/vlib/bitfield/bitfield.v:464:32: error: cannot cast string to `u32`, use `j.u32()` instead.
  462 |     for i := 0; i < (bitnslots - 1); i++ {
  463 |         for j in 0 .. bitfield.slot_size {
  464 |             if u32(instance.field[i] >> u32(j)) & u32(1) == u32(1) {
      |                                         ~~~~~~
  465 |                 output.set_bit(size - i * bitfield.slot_size - j - 1)
  466 |             }
/usr/local/v/vlib/bitfield/bitfield.v:465:27: error: infix expr: cannot use `string` (right expression) as `int`
  463 |         for j in 0 .. bitfield.slot_size {
  464 |             if u32(instance.field[i] >> u32(j)) & u32(1) == u32(1) {
  465 |                 output.set_bit(size - i * bitfield.slot_size - j - 1)
      |                                       ~~~~~~~~~~~~~~~~~~~~~~
  466 |             }
  467 |         }
/usr/local/v/vlib/bitfield/bitfield.v:469:29: error: infix expr: cannot use `string` (right expression) as `int`
  467 |         }
  468 |     }
  469 |     bits_in_last_input_slot := (size - 1) % bitfield.slot_size + 1
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  470 |     for j in 0 .. bits_in_last_input_slot {
  471 |         if u32(instance.field[bitnslots - 1] >> u32(j)) & u32(1) == u32(1) {
/usr/local/v/vlib/bitfield/bitfield.v:489:28: error: infix expr: cannot use `string` (right expression) as `int`
  487 |     instance.field = field.clone()
  488 |     instance.size = new_size
  489 |     if new_size < old_size && new_size % bitfield.slot_size != 0 {
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  490 |         instance.clear_tail()
  491 |     }
/usr/local/v/vlib/bitfield/bitfield.v:523:19: error: infix expr: cannot use `string` (right expression) as `int`
  521 | // clear_tail clears the extra bits that are not part of the bitfield, but yet are allocated
  522 | fn (mut instance BitField) clear_tail() {
  523 |     tail := instance.size % bitfield.slot_size
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~
  524 |     if tail != 0 {
  525 |         // create a mask for the tail
/usr/local/v/vlib/bitfield/bitfield.v:534:27: error: infix expr: cannot use `string` (right expression) as `int`
  532 | // bitmask is the bitmask needed to access a particular bit at offset bitnr
  533 | fn bitmask(bitnr int) u32 {
  534 |     return u32(u32(1) << u32(bitnr % bitfield.slot_size))
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~
  535 | }
  536 |
/usr/local/v/vlib/bitfield/bitfield.v:539:9: error: infix expr: cannot use `string` (right expression) as `int`
  537 | // bitslot is the slot index (i.e. the integer) where a particular bit is located
  538 | fn bitslot(size int) int {
  539 |     return size / bitfield.slot_size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
  540 | }
  541 |
/usr/local/v/vlib/bitfield/bitfield.v:553:9: error: infix expr: cannot use `string` (right expression) as `int`
  551 | // zbitnslots returns the minimum number of whole integers, needed to represent a bitfield of size length
  552 | fn zbitnslots(length int) int {
  553 |     return (length - 1) / bitfield.slot_size + 1
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  554 | }
```

**Comment by shove70** [comment]
@spytheman
Sorry, I didn't describe the problem clearly. Please have a look

**Comment by spytheman** [comment]
> @spytheman Sorry, I didn't describe the problem clearly
No problem, thanks for the clarification - it is indeed a problem, and I think the fix is good.

I just used another public constant in `time` and simplified the test a little to avoid warnings.

**Review by spytheman — APPROVED** [review]

**Comment by shove70** [comment]
Thanks!!!

**Pull request merged**
