### PR TITLE
cgen: printing of enum

### PR DESCRIPTION
**Pull request by danieldaeschle**
Solves:
- printing of enums either directly or through a Enum_str() generated method.

Current problems:
- default_expr of enum can be anything currently, but the Enum_str() function can only handle IntegerLiteral
- don't know which types of Exprs enums should handle @medvednikov

### CODE REVIEW

**Comment by danieldaeschle** [comment]
currently not working: `println('${Color.green}') // 1`

**Comment by danieldaeschle** [comment]
currently not working: `println(Color.green.str())`
Should it work? @medvednikov

**Comment by medvednikov** [comment]
Can you run `vfmt -w ` on the files and also add a test?

Since it's doing a print, you can't  use `assert`, you'll have to add it to tests/inout/

**Comment by medvednikov** [comment]
I don't think enum_str() is getting generated yet.

**Pull request merged**
