### PR TITLE
math: add easing

### PR DESCRIPTION
**Pull request by kahsa**
As part of the refactoring of `ui`, I think this https://github.com/vlang/ui/blob/master/easing.v would be more appropriate in `math` than in `ui`, so I moved it here.

### CODE REVIEW

**Comment by mneumann** [comment]
@kahsa @spytheman The code you merged seems to be under a GPL license (at least the header mentions it), while V seems to be MIT licensed, right? Be careful with that, as this has a **huge** impact on anyone using V with `vlib`.

**Comment by mneumann** [comment]
@kahsa @spytheman Please consider reverting this PR or relicense the code in question.

**Comment by spytheman** [comment]
done

**Comment by kahsa** [comment]
Sorry, I overlooked that.

@leahlundqvist are you ok to change it to MIT license?

**Comment by leahlundqvist** [comment]
Sorry for missing this and taking so long to respond! Yes, i consent to the MIT license change of my easing code.

**Pull request merged**
