### PR TITLE
term: feature terminal functions

### PR DESCRIPTION
**Pull request by bpryer**
# Functions Added
##  get_cursor_position() Coord
// get_cursor_position returns a Coord containing the current cursor position
```
cursor_position := term.get_cursor_position()
println('x: $cursor_position.x')
println('y: $cursor_position.y')
```
## set_terminal_title(title string) bool
```
title_change := term.set_terminal_title('v is awesome')
println('Title changed: $title_change')
```

## Testing
tests have been added to ./vlib/term/term_test.v

### CODE REVIEW

**Comment by medvednikov** [comment]
You've implemented this only for windows, that's why tests are failing.

**Comment by bpryer** [comment]
Right when I saw the first test fail I knew I had forgotten Linux and macOS. I'll get them added and resubmit.

**Comment by bpryer** [comment]
Any guidance as to how this is implemented in *nix systems?  Other than WSL, I'm limited on testing non windows options.

**Comment by ylluminate** [comment]
I think just biting the bullet with VM setups for the various systems you want to test on is going to be your best option at the moment until things calm down with getting 0.2 out the door.

**Comment by bpryer** [comment]
Roger that. I'll see what I can do. Thanks.

**Comment by Larpon** [comment]
@bpryer [this might help](https://stackoverflow.com/a/50885322/1904615)

**Pull request merged**
