### PR TITLE
gg: add new draw_image_with_config method

### PR DESCRIPTION
**Pull request by kjlaw89**
This PR adds a new `draw_image_cfg` method to `gg` and combines all of the other methods into one. All of the existing methods have had `[deprecated]` added to them except `draw_image`.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Why have it as a separate function?  The config could be passed as a parameter to `draw_image` to use when drawing, so it would only be one function call instead of 2.

**Comment by kjlaw89** [comment]
> Why have it as a separate function? The config could be passed as a parameter to `draw_image` to use when drawing, so it would only be one function call instead of 2.
> 
> And, if you make it the _last_ parameter, short struct syntax can be used for when you only need to set a couple of fields in the config.

I'm perfectly okay with that - I was mostly just trying to minimize the effort for people to update (not like it's used too heavily). This leaves the basic `draw_image` method for the real simple images that don't need anything special and provides a much more involved method for the more complex cases. But I'd be fine with combining them.

**Comment by JalonSolov** [comment]
Keeping it as 2 separate functions is fine, to avoid breaking current simple `draw_image` calls.  However, I would rename the new function to `draw_image_with_config`.  A little longer to type, but more explicit about why you need it over just `draw_image`.

**Comment by kjlaw89** [comment]
@spytheman what do you think? Separate, or combine to a single method?

It would be nice where if the last item of a function was a struct that it would be optional. Then we could do the combined method with no breaking changes. But it appears that you need to at least pass in `{}` if none of the struct's values are set.

**Comment by spytheman** [comment]
In my opinion, keeping the separate functions is better, i.e. the simple ones should stay and should not be deprecated. 
The whole point of their existence, is that you may not want to deal with all the options (otherwise you could always drop to the underlying sgl calls).

**Comment by spytheman** [comment]
> But it appears that you need to at least pass in {} if none of the struct's values are set.

That was discussed in https://discord.com/channels/592103645835821068/592115457029308427/839912689039310889 and Alex decided that an empty struct `{}` should be skipable, so it would be implemented in the future, but it is not for now.

**Pull request merged**
