### PR TITLE
scanner: replace ascii unicode(\u0020) with hex(\x20)

### LINKED ISSUE #6317: Unicode escaping seems not to work correctly
**V version:** 2cb711e
**OS:** Win10

**What did you do?**
Ran following code:
```
fn main() {
	println('äöü\u0020\u00c4\u00d6\u00dc')
}
```

**What did you expect to see?**
```
äöü ÄÖÜ
``` 
**What did you see instead?**
```
äöü ���
```

### PR DESCRIPTION
**Pull request by zakuro9715**
~~Fix #6317~~

universal character less than `\u00A0` is ill-formed in C standard.

This PR replace it with hex escape sequence to work it.

### CODE REVIEW

**Comment by spytheman** [comment]
I am not sure that I understand what this fixes exactly. All the asserts pass on master, even without this PR?
Is there a case where it did not work, but now it works?

**Comment by JalonSolov** [comment]
ASCII hex(\x20) and Unicode(\u0020) are exactly the same in memory, only taking one byte.

The previous, however, is shorter to type.  Not sure if that's enough reason to change it.  :-\

**Comment by zakuro9715** [comment]
universal character less than "\u00A0" is not allowed in C99 standard.

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf 6.4.3 Universal character names

> A universal character name shall not specify a character whose short identifier is less than
00A0 other than 0024 ($), 0040 (@), or 0060 (‘), nor one in the range D800 through
DFFF inclusive.

At least it will be error in my environment.

```
$ v doctor
OS: linux, Ubuntu 18.04.5 LTS (WSL 2)
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 3800X 8-Core Processor
CC version: clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

getwd: /home/zakuro/src/github.com/zakuro9715/v
vmodules: /home/zakuro/.vmodules
vroot: /home/zakuro/src/github.com/zakuro9715/v
vexe: /home/zakuro/src/github.com/zakuro9715/v/v
vexe mtime: 2021-03-12 19:20:13
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 204f57d.0c33656
env VFLAGS: "-cc clang"

Git version: git version 2.30.0
Git vroot status: weekly.2021.10-69-g0c33656a
.git/config present: true
thirdparty/tcc status: master 17d18c13

```

```
$ cat main.v
fn main() {
        println('\u0020')
}
$  v main.v
==================
                                             ^
/tmp/v/main.3308132778832393360.tmp.c:8676:17: error: character ' ' cannot be specified by a universal character name
        println(_SLIT("\u0020"));
                       ^~~~~~
/tmp/v/main.3308132778832393360.tmp.c:356:63: note: expanded from macro '_SLIT'
#define _SLIT(s) ((string){.str=(byteptr)("" s), .len=(sizeof(s)-1), .is_lit=1})
                                                              ^
2 errors generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by zakuro9715** [comment]
strings_test is failed without this PR change.

https://github.com/vlang/v/pull/9259/checks?check_run_id=2099254574#step:13:392

```
==================
/tmp/v/test_session_390597083062/strings_test.5625965497648016176.tmp.c: In function ‘main__test_escape’:
/tmp/v/test_session_390597083062/strings_test.5625965497648016176.tmp.c:12475:30: error: \u0020 is not a valid universal character
12475 |  if (string_eq(_SLIT("\u0020"), _SLIT(" "))) {
      |                              ^
/tmp/v/test_session_390597083062/strings_test.5625965497648016176.tmp.c:12475:30: error: \u0020 is not a valid universal character
/tmp/v/test_session_390597083062/strings_test.5625965497648016176.tmp.c:12485:51: error: \u0020 is not a valid universal character
12485 |   v_assert_meta_info__t406.lvalue = _SLIT("\u0020") /* typeof: v.ast.StringLiteral type: 18 */ ;
      |                                                   ^
/tmp/v/test_session_390597083062/strings_test.5625965497648016176.tmp.c:12485:51: error: \u0020 is not a valid universal character
/tmp/v/test_session_390597083062/strings_test.5625965497648016176.tmp.c:12498:51: error: \u0020 is not a valid universal character
12498 |   v_assert_meta_info__t407.lvalue = _SLIT("\u0020") /* typeof: v.ast.StringLiteral type: 18 */ ;
      |                                                   ^
...
```

**Comment by spytheman** [comment]
Thanks for the clarification. `vlib/v/tests/strings_test.v` does fail to compile for me too with gcc and clang.

**Pull request merged**
