### PR TITLE
Add thirdparty freetype for windows

### PR DESCRIPTION
**Pull request by yuyi98**
This PR add thirdparty freetype for windows.

`ft2build.h` is needed in many modules, so add thirdparty `freetype` for convenience.

### CODE REVIEW

**Comment by Delta456** [comment]
I am against this because it will just bloat the repo and it's better to install it by yourself.

**Comment by yuyi98** [comment]
The `freetype` are only C header files less than 1M size, why not like the other thirdparty do?

**Comment by spytheman** [comment]
@yuyi98 though convenient, it will indeed bloat v's repository.
People use v in contexts where freetype does not make sense, like for example in server environments for web apps, or just for CLI tools.

**Comment by spytheman** [comment]
freetype is different from all other thirdparty dependencies, because except on windows, it is already provided by the user's OS/package manager

**Comment by yuyi98** [comment]
Thanks, I see.
Maybe we can provide an easy to install command.

**Pull request closed without merging**
