### PR TITLE
expression: set integers as int by default

### PR DESCRIPTION
**Pull request by SleepyRoy**
After this PR integers are always 'int' by default. 
So e.g. before this PR `a := 0xffffffffffffffff` defines a 'u64', but after this PR it defines an 'int'. Use `a := u64(0xffffffffffffffff)` to define a 'u64'.

### CODE REVIEW

**Comment by medvednikov** [comment]
Ints are going to stay 32 bit by default, like in Go.

**Comment by SleepyRoy** [comment]
@medvednikov How about large integers like 0xffffffffffff, -0xffffffffffff, etc? Now they're u64.

**Comment by spytheman** [comment]
Why would you do that @SleepyRoy ? what is wrong with large hex literals continue being u64? Such constants are usually used as bit patterns for masking. What would we gain if they are i64?

**Comment by SleepyRoy** [comment]
@spytheman 
a. This makes the system more consistent (int and i64 are both signed types) and takes good care of large negative integers.
b. Some languages apply this (e.g. in C++ `auto a = 1000000000000` defines an i64).

BTW the current int/u64 threshold is 2^32 instead of 2^31 (max of int), which I think is strange (e.g. `a := 0xffffffff` defines an int instead of u64). Should this be fixed?

**Comment by medvednikov** [comment]
Hex literals should be 32 bit ints, like in Go.

Then the developer can define what they need: `x := u64(0x23434343434)`

**Comment by SleepyRoy** [comment]
@medvednikov Got it.

**Comment by SleepyRoy** [comment]
@medvednikov Done. There's only one failing test `vlib/v/gen/cgen_test.v` and I think it'll become OK after master is fixed.

**Comment by medvednikov** [comment]
Thanks.

**Pull request merged**
