### PR TITLE
v: add support for `v crun examples/hello_world.v`, use crun mode for .vsh files by default.

### PR DESCRIPTION
**Pull request by spytheman**
`v file.vsh` will now compile the file just once, and keep the
executable, unless the file.vsh source is changed. Subsequent runs of
the same script file will just execute the already built executable,
thus they can be much faster.

That cached run mode can be used with ordinary .v files as well, just
pass `v crun file.v`, instead of `v run file.v`.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Why not piggyback off `-usecache` instead of introducing a new command specifically for this?

Since V is it's own build system, this type of functionality is like `make` and most others, which check to see if source is newer before building.

This should be the default behavior for V as well, without having to use a special command.

**Comment by spytheman** [comment]
By default `v run file.v` *removes* the executable after it has been executed.

The infrastructure (caches and dependency analysis) developed for -usecache is used here too, but for a different result - with -usecache, the modules that are imported, are build separately, and then only linked at the end, instead of compiling the program as a whole.
In other words, -usecache is much more complex, and not completely finished yet, for example, the modules that are build separately, are still parsed when the final program is build, V just does not do code generation for them, while ideally, it should not even parse them.

In contrast, crun is simpler - it either compiles the whole program, or it does not (if it determines that it was already build and can be reused).

The time tradeoffs are different too - in the cache hit scenario, the V overhead is ~1ms, since V does not parse/check/compile anything.

Such a tradeoff is very nice for scripts, that are changed very seldom, but are executed very frequently (cron jobs or tools for example).

**Comment by spytheman** [comment]
All right, the windows CI passed 🥳 !

**Comment by spytheman** [comment]
@Larpon thanks again!

**Comment by Larpon** [comment]
My pleasure

**Pull request merged**
