### PR TITLE
tutorial: Fix consistency between content and code

### PR DESCRIPTION
**Pull request by jcbledsoe**
Update the content and code and to match each other. Remove references to SQLite file database usage in favor of in-memory database.

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks.

The goal of the tutorial is to build a realistic web app. Real life web apps don't use :memory: for storing data.

**Comment by medvednikov** [comment]
I see that :memory: was added earlier, this was a mistake. It should use a sqlite file.

**Comment by jcbledsoe** [comment]
Fiar enough. Would you rather leave the script and command line instructions back in and remove the table/data creation from `init_once()` or leave it as is and just use use `sqlite.connect('blog.db')` instead (while also removing the In-Memory doc addition)?

**Comment by medvednikov** [comment]
I'd say leave it as is and just use use sqlite.connect('blog.db')

I've also vfmt'ed the file while pushing a vweb fix, so it should be rebased.

**Pull request closed without merging**
