### PR TITLE
vlib: move the mysql/sqlite/pg/mssql modules under vlib/db

### PR DESCRIPTION
**Pull request by yuyi98**
This PR add `db` for mysql/sqlite/pg/mssql.

### CODE REVIEW

**Comment by yuyi98** [comment]
It's a break change, if we accept this change, we first need to merge this PR, then fix VEX, VPM, etc.

**Comment by JalonSolov** [comment]
Nice logical grouping of the different database wrappers under a common subdir.

The problem, as you say, will be breaking everything else.

You can fix this by not completely removing the existing `sqlite`, etc. subdirs, but instead put a single file in them that imports the new package.  Preferably with a deprecation note telling people to change their source.

**Comment by spytheman** [comment]
We can keep the existing modules where they are, and just add tags to them for a while:
```v
[deprecated: 'you can `import db.sqlite` instead']
[deprecated_after: '2023-02-01']
module sqlite
...
```

This will not break compilation with them, just produce notices till `2023-02-01`, so that people could update, then it will become a warning, and finally we can remove the old sources.

**Comment by spytheman** [comment]
image

**Comment by JalonSolov** [comment]
I just hate to have that much duplicated code, which is why I suggested replacing the old names with code that calls the new instead with a message.  But yes, it will certainly work this way.

**Comment by spytheman** [comment]
> I just hate to have that much duplicated code
Me too, but giving users some time to upgrade is nicer imho.

**Comment by JalonSolov** [comment]
Of course, and either way would do that... but it would be a lot more work for us to create the truncated files that just call the new ones, instead of having the duplicates.

**Comment by spytheman** [comment]
> Of course, and either way would do that... but it would be a lot more work for us to create the truncated files that just call the new ones, instead of having the duplicates.

You are 100% right.

**Review by LouisSchmieder — CHANGES_REQUESTED** [review]
Everything so far, but I would appreciate that fmt or vet would handle the update of the imports, idk if it's already doing it but would be a nice feature imo

**Comment by spytheman** [comment]
> Everything so far, but I would appreciate that fmt or vet would handle the update of the imports, idk if it's already doing it but would be a nice feature imo


It is a nice feature indeed, but imho out of scope for this PR.

**Comment by spytheman** [comment]
(rebased over current master)

**Review by LouisSchmieder — APPROVED** [review]

**Comment by LouisSchmieder** [comment]
yeah indeed

**Review by LouisSchmieder — APPROVED** [review]

**Pull request merged**
