### PR TITLE
js: use write() on the freestanding backend

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by playXE** [comment]
Not all JS engines have `write` provided. V8 and JSC for example provide `print` instead, this should somehow be checked

**Comment by trufae** [comment]
i think the proper way to fix that issue would be to add a function that initializes all those basic things like "print, write, eprintln, exit" and remove the need for specifying the backend. this way a single .js will work everywhere, but we can specify a backend to trim out some code later if needed. imho print/eprint can fallback to println/eprintln if not implemented. it's up to the runtime implementation to handle that and users may be aware of this i think its better than getting errors and having to sort them out in a more complex way from the user pov

**Review by playXE — APPROVED** [review]
Should work for now but initialization function is definitely needed in later PR

**Comment by spytheman** [comment]
The JS tests fail.

**Comment by trufae** [comment]
Should be good to go now

**Pull request merged**
