### PR TITLE
flag: add parsing mode that turn flag match errors into `no_match` instead

### PR DESCRIPTION
**Pull request by larpon**
This PR adds a parsing mode for `FlagMapper` that makes it easier to identify what flags the `FlagMapper` would otherwise error on.

### CODE REVIEW

**Comment by larpon** [comment]
An alternative name for the mode I considered was `.relaxed` since it relaxes specific errors, that may be a shorter/better name for the mode :shrug:

**Comment by spytheman** [comment]
An alternative is `allow_non_matching`, but it is a lot longer.

`relaxed` is more mnemonic and shorter. 

In my opinion, `relaxed` is more ergonomic overall, and contrasts well with the default `strict` mode.

**Comment by larpon** [comment]
> An alternative is `allow_non_matching`, but it is a lot longer.
> 
> `relaxed` is more mnemonic and shorter.
> 
> In my opinion, `relaxed` is more ergonomic overall, and contrasts well with the default `strict` mode.

You are right. Let me change to that

**Comment by spytheman** [comment]
`passthru` has too many consonants and a double `s`, which will make it prone to typos.

**Comment by larpon** [comment]
Renamed in [21fe88a](https://github.com/vlang/v/pull/22191/commits/21fe88a2e1286033157475d816ae40d0c8ce6326)

**Pull request merged**
