### PR TITLE
Fix for windows os.exec and os.get_raw_line

### PR DESCRIPTION
**Pull request by spytheman**
This is based on PR  #1708 .
Fixes windows os.exec and os.get_raw_line , so that testing in general works properly on windows, and the repl tests pass.

### CODE REVIEW

**Comment by spytheman** [comment]
No need to merge this, if #1708 is fixed and merged.

**Comment by spytheman** [comment]
All `v test v` tests pass now. Most of the examples build too, except tetris:
```
examples/rune.v OK
examples/spectral.v OK
examples/terminal_control.v OK
examples/tetris/tetris.v failed `C:\v\examples\tetris\tetris.v` (
C compiler=gcc
C:\v\examples\tetris\tetris.tmp.c:127:10: fatal error: ft2build.h: No such file or directory
 #include "ft2build.h"
          ^~~~~~~~~~~~
compilation terminated.
V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
)
fail
```

**Comment by spytheman** [comment]
I do not understand why the travis build fails.

I've made a fresh clone in my VM from
https://github.com/spytheman/v/tree/fix_for_windows_os_exec_and_os_get_raw_line
and both make_msvc.bat and make_tests.bat pass.

tests pass on win10

**Comment by joe-conigliaro** [comment]
@spytheman I think I know why

**Comment by spytheman** [comment]
The problem was fixed by running .replace('\r', '') over the input/expected strings too.
On the travis side, it seems that the repl files are checkout out with CRLF lineendings, even though
./compiler/tests/repl/.gitattributes specify for them to use LF ...

**Comment by medvednikov** [comment]
Let's try this on master.

**Pull request merged**
