### PR TITLE
windows: read console using ReadFile/ReadConsole

### PR DESCRIPTION
**Pull request by vitalyster**
Now we are compatible up to Windows 2000 :)

### CODE REVIEW

**Comment by spytheman** [comment]
Does C.ReadFile support reading emojies :-) ?

**Comment by vitalyster** [comment]
Sure, ReadFile/WriteFile does, but Read/WriteConsole - depends on console :)

Why test is failing?

**Comment by spytheman** [comment]
Not sure why yet ... The repl tests use os.get_raw_line indirectly, probably a stray \r or \n?
I will test in a VM shortly.

**Comment by vitalyster** [comment]
Found the issue, it does not stop reading after newline, will fix

**Comment by vitalyster** [comment]
Ready to merge

**Comment by medvednikov** [comment]
Thanks @vitalyster

**Pull request merged**
