### PR TITLE
examples: add more .obj files for 06_obj_viewer

### PR DESCRIPTION
**Pull request by spytheman**
I had these in my Downloads folder, but I could not find where I got them, and they do not seem to have sources mentioned in them 🤔 .

They look like this:
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by spytheman** [comment]
I think that the `utahTeapot.obj` is common enough to be included without problems, it even has its own wiki article: https://en.wikipedia.org/wiki/Utah_teapot .
Same with the cubes and the plane .obj files.

The plane.obj, stall.obj and objtext.obj are murkier, since I do not know their sources and license.

**Comment by spytheman** [comment]
image
donut.obj does not look good, but it was made within 5 minutes with Blender by me, so it should be safe to use.

**Comment by Larpon** [comment]
The donut looks more like an onion ring 😄

**Comment by spytheman** [comment]
> The donut looks more like an onion ring 😄

Yeah, I am a very lousy cook, that does not know how to use blenders and stuff 😄.

**Comment by spytheman** [comment]
> > The donut looks more like an onion ring 😄
> 
> Yeah, I am a very lousy cook, that does not know how to use blenders and stuff 😄.

I should have hired a chef 🤔 .

**Pull request merged**
