### PR TITLE
examples: refactoring js_dom_draw_bechmark_chart

### PR DESCRIPTION
**Pull request by enghitalo**
Refactoring js_dom_draw_bechmark_chart.

- [x] implement select chart.
- [x] implement update chart.
- [x] change faster precision from ('n'x faster) to ('n.00'x faster).
- [x] change nanoseconds to milliseconds(/1000000) with 4 decimal places.
- [x] left bar still in nanoseconds
- [x] show version
- [x] more responsive
image

### CODE REVIEW

**Comment by spytheman** [comment]
run `v fmt -w examples/js_dom_draw_bechmark_chart/v_vweb_orm/src/main.v`

**Comment by spytheman** [comment]
`chart_colors` should be removed from `examples/js_dom_draw_bechmark_chart/chart/draw.js.v`, since on some of the CI jobs, the examples are built with `-prod` -> the warning about the unused variable becomes an error.

**Comment by ken0x0a** [comment]
This kind of improvements is really cool!!

But wait a second.
Is it really good idea to include TypeScript source code in main repository?
Why not have in separate repository?

**Comment by JalonSolov** [comment]
I think it's ok for an example.  Though it would be easier if V generated JavaScript.

**Comment by enghitalo** [comment]
#15518

**Pull request closed without merging**
