### PR TITLE
v.util: add `path_styled_for_error_messages/1`

### PR DESCRIPTION
**Pull request by StunxFS**
Based on https://github.com/vlang/v/pull/14972#discussion_r916093903.

### CODE REVIEW

**Comment by JalonSolov** [comment]
I think it needs a different name.  I wasn't sure it had anything to do with system paths until I checked the code.  Also - how can it be rel _or_ abs?

**Comment by spytheman** [comment]
How about just `path_for_error_messages` ?

**Review by spytheman — APPROVED** [review]
Good work, it would have been useful for https://github.com/vlang/v/pull/16209 as well.

**Comment by spytheman** [comment]
> I think it needs a different name. I wasn't sure it had anything to do with system paths until I checked the code. Also - how can it be rel _or_ abs?

It depends on whether `VERROR_PATHS` is set to `absolute`. In this case, the resulting path will be absolute, which is very nice for IDEs and editor jump to errors functionality, but not desirable for automated CIs and tests (because the output should be stable, and not dependent on the current setup/what folder V is installed in).

**Comment by JalonSolov** [comment]
Yeah... I saw the env var when I looked again.  Maybe `path_style_for_error_messages`?  Then `relative` vs `absolute` would make more sense.  Without the `_style` part, it reads more like a directive setting the path.

**Review by JalonSolov — APPROVED** [review]

**Pull request merged**
