### PR TITLE
symlink: create /usr/local/bin if it not exists

### PR DESCRIPTION
**Pull request by serkonda7**
Fix https://github.com/vlang/v/issues/6619

### CODE REVIEW

**Comment by medvednikov** [comment]
@spytheman do you think it's safe?

**Comment by serkonda7** [comment]
Safe in what regard?

**Comment by Larpon** [comment]
I'm not sure this is optimal.
Maybe we should search for other known paths to symlink it to instead, before operating under root privileges?
`$HOME/.local/bin`
`$HOME/bin`
are well known alternatives

**Comment by serkonda7** [comment]
If we create the symlink in `$HOME/foo` we would not even need root privileges.

**Comment by Larpon** [comment]
Reading this question and answers hints - that `/opt/v` should probably be used (maybe even instead of `/usr/local/bin`).
https://unix.stackexchange.com/a/11552
Placement of executables in user land are the user's own decision IMO - and thus they'd be better of symlinking manually to match their setup. :smile:

**Comment by JalonSolov** [comment]
In order for the symlink to work, it must be created somewhere in the path.  It could be created in the user's path if they only want it for themselves, or it should be created in a system path if it should be available to all users/processes.

Moving to /opt/v is fine, except the user would then have to add that to their own path or the system path as required.

This is never an easy issue to resolve, but at least /usr/local/bin _is_ in the system path, even on Ubuntu, where it isn't created by default.

**Comment by medvednikov** [comment]
Yeah I think it's better to reuse an existing dir. This seems too invasive to me.

Very unfortunate that these things are not standardized across distros.

**Comment by spytheman** [comment]
I do not see why `/usr/local/bin` can not be made, if it does not exist already, by `sudo v symlink`. 

That folder is not sacred. Any time you install some software from source, by `./configure; make; sudo make install` by default, without giving --prefix, the final binary will be inside `/usr/local/bin/` .

`sudo ./v symlink` is a convenience for people, that do not know how a symlink works, how to make one, or how to emulate it on windows. There is nothing forcing the users to do it, it is just convenient to not have to worry about it.
It abstracts the process of making a short command available to future shell sessions.  On unix systems, this traditionally is done by copying an executable into `/usr/local/bin` . V can not copy itself to /usr/local/bin/ because it needs to be able to find the rest of vlib relative to the executable => the closest thing is making a symlink in that folder which is commonly used and in the PATH of  the vast majority of users.

Technically, we can just prepend the folder where V is to the user's PATH, and achieve the same effect, but unlike on windows, there is no standardized mechanism for doing that on unix - doing it is usually done through adding a short snippet to the user's shell startup script, but then you will have to take into account that there are several popular shells with incompatible syntaxes for doing the PATH manipulation - bash, rc, zsh, fish, etc. The symlink to /usr/local/bin solution works in all of them, because /usr/local/bin is already on the user's path in most cases (due to the system settings, or because the user/programmer has already installed another software package from source, and has added it).

NB: a symlink in any other user accessible and writable folder, that is already on the user's PATH will work just as well as a link in /usr/local/bin, but will complicate the code somewhat, and may create potentially more failure scenarios (like what happens if the user added another folder to his PATH, that also has another unrelated v symlink/executable).

**Comment by Larpon** [comment]
I agree that PATH manipulation is also a bad idea.
Also adding to path via `.profile`/`.bashrc`/`.bash_profile` is out of the question.

If `/usr/local/bin` is missing there could be many reasons for it to be absent.

* Is it a mount point?
* Is it a dir at all - maybe a file?
* Is `/usr/local` existing
* what about just `/usr` ?
* If `/usr` is missing - are there a reason for this?
* maybe it's an immutable OS or file system

It opens too many questions - that's why I suggest a list of other places to try before we start making paths from root (`/`) - it should at least be last resort.

We do this kind of reasoning in the code other places as well.

Plus it would have the benefit that we might hit a directory in that list that doesn't even require root access...
We could run through PATH and match it against the list as a first try - that way we might not even require a sudo.

Just thoughts and ideas

**Comment by spaceface777** [comment]
> We could run through PATH and match it against the list

I like that idea, I think searching for whitelisted directories inside the user's PATH is an elegant solution.

**Comment by spytheman** [comment]
The failure modes for /usr/local/bin are less - it is either there, or it is not. The reasons for why it may not be there, may be many, but are very unlikely to happen in practice for most people using v on modern unix systems. When something is not working, you can just tell the user to delete /usr/local/bin/v and/or try again. It is easy to see whether it worked or not.

The failure modes for writing in another arbitrary location that can vary depending on the current state of the PATH variable, when the user started `sudo v symlink` will be many more imho.

**Comment by spytheman** [comment]
That said, the benefit of not requiring sudo, while still achieving making v available everywhere, may be worth the trouble, I am just skeptical about it, that is all.

**Comment by Larpon** [comment]
https://github.com/vlang/v/issues/6619#issuecomment-710721820

**Comment by serkonda7** [comment]
Nice approach, but would need creation of a folder too.

**Pull request merged**
