### PR TITLE
compiler: add makefile for build v

### PR DESCRIPTION
**Pull request by chai2010**

### CODE REVIEW

**Comment by kvinwang** [comment]
No makefiles is a highlighted feature of v. You are trying to remove it 😃.

**Comment by lunny** [comment]
Or maybe a bash script to do that.

**Comment by kvinwang** [comment]
> Or maybe a bash script to do that.

Good idea. Something like [rustup.sh](https://rustup.rs) would be better.

**Comment by medvednikov** [comment]
> No makefiles is a highlighted feature of v. You are trying to remove it 😃.

Yeah, sorry. A bash script I'd be ok with.

**Comment by ntrel** [comment]
Make seems like the right tool for this. A bash script would be more verbose.

The v target should include the .v source files as dependencies.

**Comment by ntrel** [comment]
v replaces make, but here the user doesn't have v yet, so using make is sensible.

**Comment by ntrel** [comment]
Make is a much smaller dependency than bash, and more portable.

**Comment by lunny** [comment]
@ntrel Go itself also use a bash script but not makefile. So I think v could follow that. https://github.com/golang/go/blob/master/src/all.bash

**Comment by ntrel** [comment]
@lunny V does not only target people that build Go from source (I've never used Go), but you're right that it is OK to depend on bash, *so long as there is a good reason* vs Make. Make checks timestamps and matches targets, it's messy to do that in bash. I expect a bash script wouldn't bother to support the functionality that a Makefile would. What about building V on unusual platforms, pretty much all platforms have a C compiler and Make, many do not have bash.

**Comment by medvednikov** [comment]
All right, let's see how it works.

**Comment by medvednikov** [comment]
Just tested it, and it works great.

Thanks a lot @ntrel.

**Comment by kvinwang** [comment]
> The v target should include the .v source files as dependencies

> Make checks timestamps and matches targets, it's messy to do that in bash

Nope, the makefile here doesn't manage any dependency. It just download and compile the single v.c file. Shell script is better for this simple task.


> What about building V on unusual platforms, pretty much all platforms have a C compiler and Make, many do not have bash.

AFAIK:
- For Unix-like systems, shell is always available by default. but on most of them, you need manually install make with a variety of pm commands.
- For windows, both shell and make need to be installed manually. So, it is better to provide pre-built binaries for this platform.

> Make is a much smaller dependency than bash, and more portable.
Nope, both bash and make depends on GNU toolchains to be built. So it is false that make is more portable.

In fact, Make is highly depending on a shell to work correctly, commands in a makefile are shell commands. So, if there is a working make, there must be a working shell, but not vice versa.

**Comment by lunny** [comment]
On windows, a .bat file could be written.

**Comment by ntrel** [comment]
Thanks @chai2010.

**Comment by ntrel** [comment]
@kvinwang The makefile could include the dependencies. Building software is what make was designed for, not bash.

Bash is not available on all systems that make is available for:
1. Bash isn't even required on Unix, it can use Bourne.
2. Every C compiler vendor also ships make, why do you only consider gnu make?
3. Windows and Unix are not the only systems that exist!

Bash would be bad enough compared to make, Bourne would be worse. It's a bad idea, use make.

**Comment by kvinwang** [comment]
> The makefile could include the dependencies

it could, but it isn't needed here. Here, there is `only one` file to be compiled. call cc directly is good enough. using makefile will introduce complexity.


> 1. Bash isn't even required on Unix, it can use Bourne

All of them are shell. I sad `SHELL`.


> 2\. Every C compiler vendor also ships make

How can you claim this? I have rarely seem a c compiler shiping with a make.

> 3\. Windows and Unix are not the only systems that exist

They are the only systems people used for developing software. Have you ever seem an exception and shell is missing on that system? If yes, them congrats, our makefile wont work on that system too.

For this task, if we have to choose one of the two, shell script is good enough. using makefile will introduce more dependency and more complexity.

**Comment by kvinwang** [comment]
I thought vlang's zen contains:
- Keep it simple.
- There is only one way to do a thing.

**Pull request merged**
