### PR TITLE
jsgen: Fix javascript backend treats u32 as i32 [issue #20499]

### PR DESCRIPTION
**Pull request by GGRei**
Fix issue #20499 

Addresses the issue where u32 variables in the JavaScript backend were incorrectly treated as i32, leading to incorrect arithmetic results and comparisons for values exceeding the i32 range.

These adjustments ensure that u32 values are correctly managed in the JavaScript backend.

I'm always available for any suggestions/modifications.

**Edit :**

my test files is a bit usless but I can remove if needed...

### CODE REVIEW

**Comment by enghitalo** [comment]
What about u16? 🤔

**Comment by spytheman** [comment]
> What about u16? 🤔

`u16` fits entirely into a signed JS number and it is already handled.

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by spytheman** [comment]
Hm, `u16` is not handled entirely correctly.
```v
a := u16(0x7FFF)
b := u16(0xFFFF)
println(a)
println(b)
```
this does work, producing:
```
32767
65535
```
with both the default C backend, and the JS one.

However this produces different results with `-b c` and `-b js`, due to the default mask:
```v
a := u16(0x7FFFFFFF)
b := u16(0xFFFFFFFF)
println(a)
println(b)
```
produces:
```
0[14:44:36]@m1: (master) ~/v $ v run x.v
65535
65535
0[14:44:38]@m1: (master) ~/v $ v -b js run x.v
2147483647
-1
```

**Comment by GGRei** [comment]
@spytheman i'm going to work on it.

**Pull request merged**
