### PR TITLE
Struct updating syntax

### PR DESCRIPTION
**Pull request by danieldaeschle**
implements this:
```v
f := Foo{
    name: 'test'
    age: 18
}
f2 := Foo{
    ...f
    name: 'f2'
}
```

@serkonda7 there are some special vfmt cases for struct init. Could you check it that everything is correct for all cases?

Currently comment formatting doesn't work. What should i do to make it work?

---

Assoc syntax needs to be deprecated.

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
good work

**Comment by serkonda7** [comment]
All tests passed, so it should be fine. Else I'll fix it soon.

**Comment by danieldaeschle** [comment]
I haven‘t added much tests with update syntax because it don‘t know all kinds of struct formatting.

**Comment by serkonda7** [comment]
Okay, I will do a PR to expand the fmt tests.

**Comment by danieldaeschle** [comment]
Thanks :)

**Pull request merged**
