### PR TITLE
builtin.array: optimize array.delete_many() (fix #11150)

### LINKED ISSUE #11150: a.delete(a.len - 1) runs very inefficiently. Causes segmentation fault on armv7 (router)
**V version:** V 0.2.2 90adf4d

**OS:** 
x86_64 - debian 10
armv7 soft-float - gcc-10.2, uclibc-ng

**What did you do?**
https://github.com/lancethepants/36cube-vlang/blob/master/36cube.v

While working around https://github.com/vlang/v/issues/11149 I tried compiling my test program using the c-backend and using using `a.delete(a.len - 1)` instead of `a.delete_last()`.  I was surprised to see how inefficient `a.delete(a.len -1 )` runs on both x86_64 and arm. On arm, it does successfully run but gives `Segmentation fault` at the end of running the program.

**What did you expect to see?**
I would have thought `a.delete(a.len - 1)` would have the same or negligible performance difference to `a.delete_last()`, and no segfault on arm.
 
**What did you see instead?**
x86_64
a.delete_last(): **1.4s**
a.delete(a.len -1 ):  **2.4s**
adds a whole second to the runtime.

arm
a.delete_last(): **6.8s**
a.delete(a.len -1 ):  **16.2s**
and segfaults at end of program

In all cases ran v -prod 36cube.v

### PR DESCRIPTION
**Pull request by yuyi98**
This PR makes minor optimization in array.delete_many(). (fix #11150)

- Avoid realloc memory.
- Using `C.memmove` instead of `C.memcpy`.
- Avoid cross-border access.

### CODE REVIEW

**Comment by Gladear** [comment]
There was a reason `array.delete_many` was made to reallocate, this can cause issues with slices iirc.
I'm wondering why that it isn't caught by any test thought 🤔

cc @UweKrueger 
ref: https://github.com/vlang/v/pull/10889

**Comment by yuyi98** [comment]
I don't agree that slice's parent has changed and make sure that slice is not affected by realloc parent.

**Comment by UweKrueger** [comment]
> There was a reason `array.delete_many` was made to reallocate, this can cause issues with slices iirc.

Yes, there was a reason. When you have an original array and create a slice and delete an element from one of the arrays the other should not be changed. That was a requirement that came up on Discord (because growing one of the arrays does not change the other, either).

Of cause that's a performance penalty &ndash; so it might be a good idea to use the implementations of this PR here as optimized alternatives with other names &ndash; like `delete_in_place()` and `delete_many_in_place()`.

> I'm wondering why that it isn't caught by any test thought :thinking:

This would have been caught by `test_slice_delete()` and `test_delete_many()` in `vlib/builtin/array_test.v` &ndash; however this PR here changes these test cases by adding `.clone()` to the slice operations &ndash; so they pass.

**Comment by UweKrueger** [comment]
We should of cause investigate the segmentation fault on the ARM platform. However, the issue report (#11150) claims
*armv7 soft-float - gcc-10.2, uclibc-ng*
which is not a platform normally used by V developers &ndash; especially *soft-float* and *uclibc-ng* are quite unusual... :thinking:

**Comment by lancethepants** [comment]
Is there a way we can check if an array is also a slice or not?  And if not, then skip the expensive copies? 

Maybe one check, though not comprehensive, would check if the array has a cap. Any array without a cap we know can't be a slice, because according to the documentation slices **always** have a cap. Or maybe be able to check with it shares memory with another array.

It seems like the language could be aware on what type of an array it's working with, and not default to the most expensive way to do an operation.

**Comment by UweKrueger** [comment]
> Is there a way we can check if an array is also a slice or not? And if not, then skip the expensive copies?
> ... check if the array has a cap...

All arrays have a `cap` property. In V arrays/slices are indistinguishable (by design decision).

> ... check if it shares memory with another array ... It seems like the language could be aware ...

Well, V has no VM or supervisor process that could be "aware" of such things...

However, when an array does not escape from the function that has created it, i.e. there are no other instances referring the same array data, the compiler could detect this and do possible optimizations. Otherwise a reference counter as part of the array data could provide this information. (We will need a reference counter anyway for memory management unless `-gc boehm` is used.) 

These things are not trivial so for now we must find another solution. Having two types of functions could be one &ndash; I'm not biased towards which one should be "default". It would also be ok to change `delete()`/`delete_many()` as in this PR and provide other alternatives like `delete_clone()`/`delete_many_clone()` that enforce reallocations.

**Comment by medvednikov** [comment]
V's `array` == Go's `slice`. So yeah, you could say V arrays are slices.

**Comment by lancethepants** [comment]
Sounds good, hopefully down the road there will be a unified solution.

Not that my opinion carries much weight, but right now I would be more inclined to say keep the current functionality as it's something that just works in all scenarios for everyone all the time, and then make delete_in_place() and delete_many_in_place() methods you mentioned for better optimization where slices aren't a factor.

I wonder if all functions that add to or take from an array, as they could trigger a slice becoming independent from the parent,  need optimized (or else non-optimized) version too.
insert, prepend, trim, clear, delete, delete_many, delete_last and << if I didn't miss any.

Some of those like delete_last() is what I have used because it's already optimized in non-child/non-parent aware scenarios, but it should also have a child/parent-aware version as it removes elements from an array like delete and delete_may.

This is starting to get more complicated.

**Comment by lancethepants** [comment]
Since this pull request is now closed I've started a new issue that explains what was discussed here.
https://github.com/vlang/v/issues/11223

**Comment by ntrel** [comment]
> V has no VM or supervisor process that could be "aware" of such things.

What if `cap` is set to `0` for slices? Does `cap` actually need to match array length?

**Pull request closed without merging**
