### PR TITLE
time: Adding support for socket errors

### PR DESCRIPTION
**Pull request by ElDonad**
I've added the possibility to get a system agnostic error message when working with sockets. 
I tried to get the error messages as clear as possible, even if they differ a bit from their C counterpart, I thought it would be better for code readability.

I plan to convert the map of strings to a map of enum members, when the map keys will be generic.

### CODE REVIEW

**Comment by vitalyster** [comment]
Not sure why it is needed. You can get error text with gai_strerror on linux and GetLastError on windows

**Comment by ElDonad** [comment]
You can of course, I only wanted to have it system agnostic. Besides that, the os.get_error_msg don't work well for windows (for example this code will not work properly with some socket errors (ECONNREFUSED for example): 
```v
fn C.WSAGetLastError() int
//main
error_code := C.WSAGetLastError()
error_msg := os.get_error_msg(error_code)
```

**Comment by vitalyster** [comment]
1. WSAECONNREFUSED and ECONNREFUSED have different codes
2. It does not print text because of bug, see #2554 

No need to reinvent code to text mappings already existed in C runtime

**Comment by ElDonad** [comment]
Okay, I have tried your fix of os.get_error_msg(), and it outputs now a nice error message :
`Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.`

However my goal with this PR is to provide a way to process these errors automatically, since I aim to use that in an "embedded" device (namely a raspberry). I didn't know it already existed solutions for that in the C runtime, that would effectively make this PR useless.

**Pull request closed without merging**
