### PR TITLE
doc: minor fix

### PR DESCRIPTION
**Pull request by kahsa**
No need to be header.

### CODE REVIEW

**Review by spytheman — APPROVED** [review]

**Comment by kahsa** [comment]
```markdown
- [V Documentation](#v-documentation)
	- [Introduction](#introduction)
	- [Installing V from source](#installing-v-from-source)
	- [Upgrading V to latest version](#upgrading-v-to-latest-version)
	- [Table of Contents](#table-of-contents)
	- [Hello World](#hello-world)
	- [Running a project folder with several files](#running-a-project-folder-with-several-files)
	- [Comments](#comments)
	- [Functions](#functions)
		- [Hoistings](#hoistings)
		- [Returning multiple values](#returning-multiple-values)
	- [Symbol visibility](#symbol-visibility)
	- [Variables](#variables)
		- [Mutable variables](#mutable-variables)
		- [Initialization vs assignment](#initialization-vs-assignment)
		- [Declaration errors](#declaration-errors)
	- [V Types](#v-types)
		- [Primitive types](#primitive-types)
		- [Strings](#strings)
		- [String interpolation](#string-interpolation)
		- [String operators](#string-operators)
		- [Runes](#runes)
		- [Numbers](#numbers)
		- [Arrays](#arrays)
			- [Array Fields](#array-fields)
			- [Array Initialization](#array-initialization)
			- [Array Types](#array-types)
			- [Multidimensional Arrays](#multidimensional-arrays)
			- [Array methods](#array-methods)
				- [Sorting Arrays](#sorting-arrays)
			- [Array Slices](#array-slices)
				- [Slices with negative indexes](#slices-with-negative-indexes)
			- [Array method chaining](#array-method-chaining)
		- [Fixed size arrays](#fixed-size-arrays)
		- [Maps](#maps)
	- [Module imports](#module-imports)
		- [Selective imports](#selective-imports)
		- [Module import aliasing](#module-import-aliasing)
	- [Statements & expressions](#statements--expressions)
		- [If](#if)
			- [Type checks and casts](#type-checks-and-casts)
		- [In operator](#in-operator)
		- [For loop](#for-loop)
			- [for/in](#forin)
				- [Array for](#array-for)
				- [Custom iterators](#custom-iterators)
				- [Map for](#map-for)
				- [Range for](#range-for)
			- [Condition for](#condition-for)
			- [Bare for](#bare-for)
			- [C for](#c-for)
			- [Labelled break & continue](#labelled-break--continue)
		- [Match](#match)
		- [Defer](#defer)
	- [Structs](#structs)
		- [Heap structs](#heap-structs)
		- [Default field values](#default-field-values)
		- [Required fields](#required-fields)
		- [Short struct literal syntax](#short-struct-literal-syntax)
			- [Trailing struct literal arguments](#trailing-struct-literal-arguments)
		- [Access modifiers](#access-modifiers)
		- [Anonymous structs](#anonymous-structs)
		- [[noinit] structs](#noinit-structs)
		- [Methods](#methods)
		- [Embedded structs](#embedded-structs)
	- [Unions](#unions)
	- [Functions 2](#functions-2)
		- [Immutable function args by default](#immutable-function-args-by-default)
		- [Mutable arguments](#mutable-arguments)
			- [Struct update syntax](#struct-update-syntax)
		- [Variable number of arguments](#variable-number-of-arguments)
		- [Anonymous & higher order functions](#anonymous--higher-order-functions)
		- [Closures](#closures)
	- [References](#references)
		- [Parameter evaluation order](#parameter-evaluation-order)
	- [Constants](#constants)
		- [Required module prefix](#required-module-prefix)
	- [Builtin functions](#builtin-functions)
		- [println](#println)
		- [Printing custom types](#printing-custom-types)
		- [Dumping expressions at runtime](#dumping-expressions-at-runtime)
	- [Modules](#modules)
		- [init functions](#init-functions)
	- [Type Declarations](#type-declarations)
		- [Interfaces](#interfaces)
			- [Implement an interface](#implement-an-interface)
			- [Casting an interface](#casting-an-interface)
			- [Interface method definitions](#interface-method-definitions)
			- [Embedded interface](#embedded-interface)
		- [Function Types](#function-types)
		- [Enums](#enums)
		- [Sum types](#sum-types)
			- [Dynamic casts](#dynamic-casts)
			- [Smart casting](#smart-casting)
			- [Matching sum types](#matching-sum-types)
		- [Type aliases](#type-aliases)
		- [Option/Result types and error handling](#optionresult-types-and-error-handling)
		- [Handling optionals](#handling-optionals)
	- [Custom error types](#custom-error-types)
	- [Generics](#generics)
	- [Concurrency](#concurrency)
		- [Spawning Concurrent Tasks](#spawning-concurrent-tasks)
		- [Channels](#channels)
			- [Syntax and Usage](#syntax-and-usage)
			- [Channel Select](#channel-select)
			- [Special Channel Features](#special-channel-features)
		- [Shared Objects](#shared-objects)
	- [JSON](#json)
		- [Decoding JSON](#decoding-json)
		- [Encoding JSON](#encoding-json)
	- [Testing](#testing)
		- [Asserts](#asserts)
		- [Asserts with an extra message](#asserts-with-an-extra-message)
		- [Asserts that do not abort your program](#asserts-that-do-not-abort-your-program)
		- [Test files](#test-files)
			- [Running tests](#running-tests)
	- [Memory management](#memory-management)
		- [Control](#control)
		- [Examples](#examples)
		- [Stack and Heap](#stack-and-heap)
			- [Stack and Heap Basics](#stack-and-heap-basics)
			- [V's default approach](#vs-default-approach)
			- [Manual Control for Stack and Heap](#manual-control-for-stack-and-heap)
	- [ORM](#orm)
	- [Writing Documentation](#writing-documentation)
		- [Newlines in Documentation Comments](#newlines-in-documentation-comments)
	- [Tools](#tools)
		- [v fmt](#v-fmt)
		- [v shader](#v-shader)
		- [Profiling](#profiling)
	- [Package management](#package-management)
					- [module options:](#module-options)
		- [Publish package](#publish-package)
- [Advanced Topics](#advanced-topics)
	- [Memory-unsafe code](#memory-unsafe-code)
	- [Structs with reference fields](#structs-with-reference-fields)
	- [sizeof and __offsetof](#sizeof-and-__offsetof)
	- [Calling C from V](#calling-c-from-v)
	- [Calling V from C](#calling-v-from-c)
	- [Export to shared library](#export-to-shared-library)
	- [Atomics](#atomics)
	- [Global Variables](#global-variables)
	- [Passing C compilation flags](#passing-c-compilation-flags)
	- [#pkgconfig](#pkgconfig)
	- [Including C code](#including-c-code)
	- [C types](#c-types)
	- [C Declarations](#c-declarations)
	- [Debugging](#debugging)
		- [C Backend binaries Default](#c-backend-binaries-default)
		- [Native Backend binaries](#native-backend-binaries)
		- [Javascript Backend](#javascript-backend)
	- [Conditional compilation](#conditional-compilation)
		- [Compile time code](#compile-time-code)
			- [$if condition](#if-condition)
			- [$embed_file](#embed_file)
			- [$tmpl for embedding and parsing V template files](#tmpl-for-embedding-and-parsing-v-template-files)
			- [$env](#env)
			- [$compile_error and $compile_warn](#compile_error-and-compile_warn)
		- [Environment specific files](#environment-specific-files)
	- [Compile time pseudo variables](#compile-time-pseudo-variables)
	- [Performance tuning](#performance-tuning)
	- [Compile-time reflection](#compile-time-reflection)
	- [Limited operator overloading](#limited-operator-overloading)
	- [Inline assembly](#inline-assembly)
	- [Translating C to V](#translating-c-to-v)
	- [Hot code reloading](#hot-code-reloading)
	- [Cross compilation](#cross-compilation)
	- [Cross-platform shell scripts in V](#cross-platform-shell-scripts-in-v)
	- [Vsh scripts with no extension](#vsh-scripts-with-no-extension)
	- [Attributes](#attributes)
	- [Goto](#goto)
- [Appendices](#appendices)
	- [Appendix I: Keywords](#appendix-i-keywords)
	- [Appendix II: Operators](#appendix-ii-operators)
```
Since many of the advanced topics are articles on C and compilation, first it would be better to group them under the headings `Compilation` and `V and C`, to keep the information organized.
Any suggestions? @spytheman

**Comment by kahsa** [comment]
```
	- [Attributes](#attributes)
	- [Goto](#goto)
```
What reason these are last?
They must be last?

**Comment by kahsa** [comment]
```
	- [Hot code reloading](#hot-code-reloading)
	- [Cross compilation](#cross-compilation)
```
Why Cross compilation is after Hot code reloading?
It must be there?

**Comment by kahsa** [comment]
```
	- [Limited operator overloading](#limited-operator-overloading)
	- [Inline assembly](#inline-assembly)
```
These two must between Comptime-reflection and Translating C to V?

**Comment by kahsa** [comment]
```
	- [Compile time pseudo variables](#compile-time-pseudo-variables)
	- [Performance tuning](#performance-tuning)
	- [Compile-time reflection](#compile-time-reflection)
```
Why Performance tuning must be between them?

**Comment by kahsa** [comment]
```
	- [Atomics](#atomics)
	- [Global Variables](#global-variables)
```
Humm, indeed these are topic of C, but these title remind us more V language specific topic.

**Comment by kahsa** [comment]
There are many places, at least as far as the headings are concerned, that do not appear to be in logical order.

**Pull request merged**
