### PR TITLE
math: basic prime checker with tests

### PR DESCRIPTION
**Pull request by git-vince**
This PR adds basic support for Prime number checker in the math module and also implements tests.

_Sieve of Eratosthenes has been avoided for space complexity_

### CODE REVIEW

**Comment by hazohelet** [comment]
This not-so-fast built in function is not necessary imo.

It's no cool for V to include functions for everything like this, I guess.

How often do you actually need to know whether the number at hand is a prime?

**Comment by git-vince** [comment]
> This not-so-fast built in function is not necessary imo.
> 
> It's no cool for V to include functions for everything like this, I guess.
> 
> How often do you actually need to know whether the number at hand is a prime?

it has a factorial function. I did ask the same question at first.

**Comment by hazohelet** [comment]
Oh, I've nothing to say...
It's all up to @medvednikov

**Comment by ciubotaru** [comment]
Besides cryptography, prime numbers do not have much practical use. Cryptography would require a separate module (or even modules).

**Comment by git-vince** [comment]
Presence of such functions (factorial/prime) can mislead others as it happened here.

**Comment by medvednikov** [comment]
If a math function is present in Go's, Python's, or Jula's stdlib, then it's merged. Prime checker is not.

**Pull request closed without merging**
