### PR TITLE
os.exec: return ?string instead of just string

### PR DESCRIPTION
**Pull request by schurhammer**
This changes os.exec to return a ?string, based on if the command ran successfully. 
1. Return the error 'popen $cmd failed' if the popen call failed.
2. Return the command's output as an error if the return code was non-zero.
3. Otherwise return the output as a string.

Also updated all the calls to os.exec to handle the option type.

### CODE REVIEW

**Comment by medvednikov** [comment]
Looks like there's an unhandled `os.exec` on Windows.

**Comment by schurhammer** [comment]
I think it might be a bug with or blocks, forgot to put this in the pr. 

Sometimes it says `return/continue/break/panic` is required even though there already is a `panic` there.
eg main.v:1362
```
s := os.exec('git -C "$vroot" pull --rebase origin master') or {
	panic(err)
	return // TODO doesn't recognise the panic for some reason
}
```
When I remove the return I get

```
panic: main.v:1362
`or` block must return/continue/break/panic
```

**Comment by medvednikov** [comment]
Yeah, there's a bug with panics. It doesn't recognize them. `return` is still needed.

**Comment by schurhammer** [comment]
@medvednikov are the windows tests just broken? can't get them to pass locally, even before any of my changes.

Anyway, more changes:
- require functions to return in all branches e.g. `fn() int {if false { return 1 }}` is now a compile error since it doesn't return an int all the time
- calling panic sets the p.returns flag so it is recognized for or blocks and for checking if a branch returns
- added a bunch of returns after panics so it compiles, these can be removed again immediately

**Comment by medvednikov** [comment]
@schurhammer Windows tests seem to be fine on master.

**Comment by schurhammer** [comment]
Gonna close this and open new ones for each change, hopefully with passing test

**Comment by medvednikov** [comment]
Tests will be broken within the next hour.

**Comment by schurhammer** [comment]
ok, ill wait a bit then

**Pull request closed without merging**
