### PR TITLE
fixed array: fix fixed array errors.

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix fixed array init `[...]!!` error.

- Fix `[1,2,3]!!` error.
- Add `fixed_array_init_test.v`.

### CODE REVIEW

**Comment by yuyi98** [comment]
There is still a problem, can only be initialized, can not be assigned.

**Comment by yuyi98** [comment]
Sorry, I'm not sure if there's `[1,2,3]!` syntax right now.

**Comment by medvednikov** [comment]
It was a hack in V1, we'll think of something better in the new parser.

**Comment by yuyi98** [comment]
Fix all fixed-array error.
```v
OK   [ 99/162]  1150.031 ms vlib\v\tests\fixed_array_test.v
------------------------------------------------------------------------------------------
               110007.485 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   146,     0,    16,   162
```

**Pull request merged**
