### PR TITLE
json: support `@[json_null]` tag to enforce `null`, when encoding `none` option values

### PR DESCRIPTION
**Pull request by felipensp**
Implementing feature request.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcyYmM3NmYxNDRmNTg1YWU1MTZmMmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.IuqTMFe-F_ZEWbZgfl9dlS5Z2iuZ5myuO48HUP_kkqA">Huly&reg;: <b>V_0.6-21751</b></a></sub>

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Excellent work.

**Comment by enghitalo** [comment]
What about just `@[nulltable]` so this can make sense to others encoders as well

**Comment by enghitalo** [comment]
IMHO, `@[required; skip]` should do the same work (What I think would be better)

**Comment by spytheman** [comment]
> IMHO, `@[required]`, or `@[required; skip]`, or `@[required; omitempty]` should do the same work (What I think would be better)

No. The current name @[json_null] is better - it has `json` in it, and so it is restricted to only the `json` modules. This avoids the conflict with the decisions of other modules, that may also do serialization.

**Comment by spytheman** [comment]
`omitempty` in particular does the opposite, and is only valid for non option fields.

**Comment by JalonSolov** [comment]
Logically, `@[omitempty]` should apply to Option fields as well.  If the Option is set to `none` (the default), then it is "empty".  Same as a string field set to `''`.

**Comment by spytheman** [comment]
The *default* for option fields, with a value of `none`, is that they are already omitted when serialized to json => adding a `@[omitempty]` tag to them is redundant to that default, and non effective for them.

**Comment by JalonSolov** [comment]
That sounds like "magic".  It would make more sense to output `null` unless `omitempty` was used.

**Comment by spytheman** [comment]
No, it does not sound like "magic" - the default behavior is to not produce anything for option values that are `none`, and that saves resources, and that is not changed by the PR.

**Pull request merged**
