### PR TITLE
parser: allow void return type for C functions

### PR DESCRIPTION
**Pull request by Delta456**
Before this was invalid

```v
fn C.gba() void

fn main() {
   println('hello')

}
```
Error:

``` error
foo.v:1:12: error: use `?` instead of `?void` 
    1 | fn C.agb() void
      |            ~~~~
    2 | 
    3 | fn main() {
```

Now it works

```v
fn C.gba() void

fn main() {
   println('hello')

}
```

Output:
```terminal
hello
```

### CODE REVIEW

**Comment by Gladear** [comment]
Out of curiosity, why allowing to set explicitly the return type to `void` while not setting a return type has the same meaning ?

**Comment by medvednikov** [comment]
This should not have been merged.

**Comment by medvednikov** [comment]
There's no `void` type in V. I'll revert it.

**Comment by spytheman** [comment]
The `void` type is for C compatibility, same as `voidptr`.

**Pull request merged**
