### PR TITLE
os/notify: Make epoll wrapper thread safe

### PR DESCRIPTION
**Pull request by mcastorina**
Also adds comments to document the code.

### CODE REVIEW

**Review by Larpon — CHANGES_REQUESTED** [review]
@mcastorina good work.
It'd be nice if you use present tense for doc strings, and always start with the function name itself.

You can dig around #7047 for links and more in depth info about writing documentation

**Comment by JalonSolov** [comment]
Yes, please.  This helps when looking up functions on https://modules.vlang.io

**Comment by mcastorina** [comment]
Thanks for the pointers, I'll update the comments. Since this is internal backend code, I'm not sure it will be publicly viewable on modules.vlang.io or `v doc` though.

**Comment by Larpon** [comment]
Yes, but it aids "grepability" when using the commandline 🙂

**Comment by mcastorina** [comment]
@Larpon updated the comments, let me know what you think! I wasn't sure if punctuation is discouraged so I mostly left out periods.

**Review by Larpon — APPROVED** [review]
Looks good to me!

**Comment by Larpon** [comment]
I think punctuation is preferred, but I'm a little rusty in remembering it. It can be improved later on imho

**Pull request merged**
