### PR TITLE
Fix sumtype primitive variants 2

### PR DESCRIPTION
**Pull request by kalapalo**
This is a 2 steps fix, done in 2 PRs. This is 2 of 2;
testfile sumtype_primitives_test.v is provided. Thanks to @spytheman who greatly improved it.

### CODE REVIEW

**Comment by spytheman** [comment]
Part 1: https://github.com/vlang/v/pull/6341

**Comment by medvednikov** [comment]
Both of these are incredibly hard to merge unfortunately. As things are, for the first time ever I'd have to manually update the C code in `vc`. I want to avoid that.

Is there an option to enable this partially via cmdflags?

Also we'll most likely switch to unions for sumtypes, perhaps it can be done here, to avoid doing such a big change twice.

**Comment by kalapalo** [comment]
yeah, I understand, this touches V too much.

answering your question now, with a lot of work I think this could be possible to do through flags. probably for the same amount of work it is possible to do the union implementation, that you mulled about.

my suggestion is:
1. create a new feature, let's call it internally union types;
2. let's implement it based on C unions and with, of course, a different signature, instead of '|' let's use, say, '#' or '^'. so we would have: `type Number32 = int # u32 # f32`;
3. it would have, just like for sum types and interfaces, `as` cast and smartcast with `if` and `match`;
4. when you think it is good enough to make the leap, we "transform" union types into sum types, basically by deleting the old code for sum types and changing the signature of union types from '#' to '|';

from #1 to #3 would be merged smoothly into V, but from what I see from here, it will be unavoidable your manual intervention when we do step #4. but there it will be for definitive solution.

**Comment by spytheman** [comment]
I think that adding an alternative sumtype implementation here, will make the code even harder to understand/review, because it is unrelated to what the goal of these PRs is. These PRs break V, because the compiler itself used sumtypes in an incompatible way to how it will be after the PRs are merged. Changing the *implementation* of sumtypes to use unions will hopefully be transparent to V code, thus it will not require manual intervention to vc.

**Comment by SleepyRoy** [comment]
hi everyone, any latest progress about this PR/topic?

**Comment by medvednikov** [comment]
This was fixed by @danieldaeschle

**Pull request closed without merging**
