### PR TITLE
Add log module  to replace the colors module. 

### PR DESCRIPTION
**Pull request by nzlov**
I think the old `colors` module is just the color of the console, but the `color` means color, anywhere.

### CODE REVIEW

**Comment by medvednikov** [comment]
`log` is also not the best name for this. It'll be used later. Can you rename it to something like `termcolor`?

**Comment by RustemB** [comment]
`io` the best name for it, imho

**Comment by nathanKramer** [comment]
Why all the single character function names?

**Comment by medvednikov** [comment]
Don't add binaries to git please.

And the color part has to be moved to a `termcolor` module.

Singer character function names are indeed not readable.

**Comment by nzlov** [comment]
I'm very sorry. I forgot to clear it.

**Pull request merged**
