### PR TITLE
github actions: simplify ci.yml, fix log in win, test js backend in win

### PR DESCRIPTION
**Pull request by zaoqi**
close #2059

### CODE REVIEW

**Comment by joe-conigliaro** [comment]
you need to use `.\make.bat` look in #2059. thats why it's failing

**Comment by zaoqi** [comment]
why it's failing:
```
V.js compiler not found, building...
D:\a\v\v\v.exejs.tmp.c: In function 'os__ls':
D:\a\v\v\v.exejs.tmp.c:6335:42: error: dereferencing pointer to incomplete type 'struct dirent'
 string name= tos_clone ( ((byteptr)( ent ->d_name ) ) ) ;...
(Use `v -debug` to print the entire error message)

V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
Failed.
```

**Comment by joe-conigliaro** [comment]
Try running make.bat, as when you just do make, it used make from mingw

**Comment by joe-conigliaro** [comment]
@zaoqi  v.js dosent work on windows

**Comment by joe-conigliaro** [comment]
Thanks @zaoqi

**Comment by joe-conigliaro** [comment]
@medvednikov This ones good to go!

**Pull request merged**
