### PR TITLE
add docs

### PR DESCRIPTION
**Pull request by donnisnoni95**
Add Docs - Based on https://vlang.io/docs

- [x] Introduction
- [x] Hello World
- [x] Comments
- [x] Functions
- [x] Variables
- [x] Strings
- [x] Arrays
- [x] If
- [x] Maps
- [x] In operator
- [x] For loop
- [x] Match
- [x] Structs
- [x] Access modifiers
- [x] Methods
- [x] Pure functions
- [x] High order functions
- [x] References
- [x] Constants
- [x] println
- [x] Modules
- [x] Interfaces
- [x] Enums
- [x] Option/Result types & error handling
- [x] Generics
- [x] Concurrency
- [x] Decoding JSON
- [x] Testing
- [x] Memory management
- [x] Defer
- [x] ORM
- [x] vfmt
- [x] writing_documentation

### CODE REVIEW

**Comment by Delta456** [comment]
Is there any need of this?

**Comment by donnisnoni95** [comment]
@medvednikov  will explain why

**Comment by medvednikov** [comment]
Thanks @donnisnoni95 looks good.

You should use 

```

``v 
```

instead of

```
``go
```

**Comment by donnisnoni95** [comment]
@medvednikov Yeah... I forgot that... I use it to getting syntax highlighting in markdown... will fix this  😁

**Pull request merged**
