### PR TITLE
fmt: remove extra parentheses

### PR DESCRIPTION
**Pull request by yuyi98**
This PR remove extra parentheses.

- Remove extra parentheses just like Golang.
- Add test.

```v
fn main() {
	_, _ := (((22 > 11))), (43 > 22)
	_ := ((10 + 11))
	_ := ((((((11 * 2))))))
	_ := ((11 * 2))
}
```
format to:
```v
fn main() {
	_, _ := (22 > 11), (43 > 22)
	_ := (10 + 11)
	_ := (11 * 2)
	_ := (11 * 2)
}
```

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
The CI failure is not related. Good work.

**Comment by JalonSolov** [comment]
Looks like it could have removed even more, such that the final result could (should?) have been
```
fn main() {
	_, _ := 22 > 11, 43 > 22
	_ := 10 + 11
	_ := 11 * 2
	_ := 11 * 2
}
```

**Comment by Hunam6** [comment]
> Looks like it could have removed even more, such that the final result could (should?) have been
> 
> ```v
> fn main() {
> 	_, _ := 22 > 11, 43 > 22
> 	_ := 10 + 11
> 	_ := 11 * 2
> 	_ := 11 * 2
> }
> ```

I think that the goal isn't to remove all parentheses but only remove duplicate parentheses. Because sometimes you want to add extra parentheses that are not strictly useful but still useful for understanding.

**Comment by JalonSolov** [comment]
<shrug> They're not necessary, so they could be removed.  That was my only point.

**Pull request merged**
