### PR TITLE
Closes #4285

### LINKED ISSUE #4285: "v up" builds when it doesn't need to
"v up" will build v whether anything was updated or not.

While it doesn't take long to build it is still "wasting cycles" to build when nothing has changed.

$ v up
Updating V...
From https://github.com/vlang/v
 * branch              master     -> FETCH_HEAD
   7cf9b327..900a18f9  master     -> origin/master
Updating 7cf9b327..900a18f9
Fast-forward
 .editorconfig                               |   3 +
 .github/workflows/ci.yml                    |  18 +--
 cmd/tools/vcreate.v                         |   5 +-
 cmd/tools/vtest-fixed.v                     | 222 ++++++++++------------------
 cmd/v/internal/help/default.txt             |   3 +-
 cmd/v/v.v                                   |   2 +-
 vlib/builtin/string.v                       |  12 +-
 vlib/v/ast/ast.v                            |   1 +
 vlib/v/checker/checker.v                    |  30 ++--
 vlib/v/fmt/fmt.v                            |  54 ++++---
 vlib/v/gen/cgen.v                           |  64 ++++----
 vlib/v/parser/parser.v                      |  21 ++-
 vlib/v/table/table.v                        |  24 +--
 vlib/v/tests/module_test.v                  |  12 +-
 vlib/v/tests/prod/assoc.prod.v.expected.txt |   2 +-
 15 files changed, 221 insertions(+), 252 deletions(-)
Current branch master is up to date.
cd /tmp/vc && git clean -xf && git pull --quiet
cd /var/tmp/tcc && git clean -xf && git pull --quiet
cc  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
./v self
V self compiling...
make modules
make[1]: Entering directory '/home/xxxxx/git/v'
#./v build module vlib/builtin > /dev/null
#./v build module vlib/strings > /dev/null
#./v build module vlib/strconv > /dev/null
make[1]: Leaving directory '/home/xxxxx/git/v'
V has been successfully built
$ v up
Updating V...
From https://github.com/vlang/v
 * branch              master     -> FETCH_HEAD
**Already up to date.
Current branch master is up to date.**
cd /tmp/vc && git clean -xf && git pull --quiet
cd /var/tmp/tcc && git clean -xf && git pull --quiet
cc  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
./v self
V self compiling...
make modules
make[1]: Entering directory '/home/xxxxx/git/v'
#./v build module vlib/builtin > /dev/null
#./v build module vlib/strings > /dev/null
#./v build module vlib/strconv > /dev/null
make[1]: Leaving directory '/home/xxxxx/git/v'
V has been successfully built
$

### PR DESCRIPTION
**Pull request by Immortalin**
Checks if git log contains "master is up to date" string and returns early if it does.

### CODE REVIEW

**Comment by alexesprit** [comment]
This way won't allow to do `v up` in some cases, if you pulled changes manually. :) Perhaps, it's better to compare V's hash and hash of a latest commit after pull.

**Comment by spytheman** [comment]
I think it is better for `v up` to be more predictable/stable, even at the cost of doing another recompilation (which should not take more than 1-2 seconds), instead of relying on heuristics that may fail.

**Comment by spytheman** [comment]
Checking the commit hash will be more stable in my opinion too.

**Comment by spytheman** [comment]
You can do something like:
```v
import v.util
... git operations
v_hash := util.githash(false)
current_hash := util.githash(true)
if v_hash != current_hash { return }
```

**Comment by Immortalin** [comment]
@spytheman your snippet does not work.

**Comment by alexesprit** [comment]
> (which should not take more than 1-2 seconds)

It takes about 30-60 sec on Windows.

**Comment by Immortalin** [comment]
I have updated the algorithm to use the snippet suggested by @spytheman

**Comment by Immortalin** [comment]
So behaviour with new algorithm: if you manually pulled from e.g. a different fork other than master it will automatically rebuild instead of returning early.

**Comment by Immortalin** [comment]
@medvednikov review

**Comment by medvednikov** [comment]
> It takes about 30-60 sec on Windows.

raspberry pi? :D

it should never take more than 5 seconds

**Comment by alexesprit** [comment]
> it should never take more than 5 seconds

If you take a look at the `v up` code, you can notice it runs `make.bat`, which always pulls `v_win.c`, and then compiles V twice. :)

**Comment by medvednikov** [comment]
right, so it depends on internet speed

so I wouldn't say 

> It takes about 30-60 sec on Windows.

I think `v up` should be smarter and only fall back to `cc v.c` if `git pull && v self` fails.

**Pull request merged**
