### PR TITLE
fmt: remove inline comments

### PR DESCRIPTION
**Pull request by yuyi98**
This PR remove inline comments.

```v
fn main() {
	a, b := 11, 22/*11,22*/
}

PS D:\Test\v\tt1> v fmt -w tt1.v
tt1.v:2:16: error: inline comment is deprecated, please use line comment
    1 | fn main() {
    2 |     a, b := 11, 22/*11,22*/
      |                   ~~~~~~~~~
    3 | }

Internal vfmt error while formatting file: tt1.v.
Encountered a total of: 1 errors.
```

### CODE REVIEW

**Comment by ArtemkaKun** [comment]
So no inline comments in V at all?

**Comment by yuyi98** [comment]
Yes, refer to #19236.

**Comment by medvednikov** [comment]
Great work!

How did you replace all /**/ with // ?

**Comment by yuyi98** [comment]
Find and replace them.

**Comment by ArtemkaKun** [comment]
> Yes, refer to #19236, and multiline comments /* ...\n... */ can work.

Ok, I have the similar thoughts. Thanks for the explanation

**Pull request merged**
