### PR TITLE
gen: add prefix when printing type aliases

### PR DESCRIPTION
**Pull request by danieldaeschle**
```v
struct Foo {}
type Type = Foo
type Type2 = int
fn main() {
	t := Type(Foo{})
        t2 := Type2(0)
	println(t)
        println(t2)
}
```

prints: `Type(Foo{})` & `0`

### CODE REVIEW

**Comment by danieldaeschle** [comment]
i didn't get it running for int and string... maybe someone can help me here

**Comment by danieldaeschle** [comment]
This is the current behaviour:
```v
type MyInt = int
println(MyInt(0))
//=> 0

struct Foo {}
type MyFoo = Foo
println(MyFoo(Foo{}))
//=> MyFoo{}
```

I thought about that type aliases should be printed like SumTypes.
```v
type MyInt = int
println(MyInt(0))
//=> MyInt(0)

struct Foo {}
type MyFoo = Foo
println(MyFoo(Foo{}))
//=> MyFoo(Foo{})
```

What do you guys think about this?

**Comment by StunxFS** [comment]
I think the first would look good.
Well, for example, it will work for someone who has created an alias for ``int`` called ``Number`` and tries to print a number, he will wait for the number to appear directly in the console.
```v
type Number = int

fn main() {
    println(Number(44))
}
```
With output: ``44``.

**Comment by medvednikov** [comment]
Yeah after thinking about it I'm now not so sure that this needs to be changed.

Perhaps when using `typeof()`.

Creating custom numeric types is very common, and in most cases the user will definitely expect a simple number printed.

Same in Go:

```package main

import (
	"fmt"
)

type Number int

func main() {
	var x Number = 0
	fmt.Println(x) // 0
}

```

**Comment by StunxFS** [comment]
Without a doubt it is better to use a typeof.
```v
type Number = int

fn main() {
    number := Number(2004)
    println(number) // Print '2004'
    println(typeof(number)) // Print 'Number(int)'
}
```

**Comment by danieldaeschle** [comment]
Ok. That means, primitives should still be how it is. But how is it with structs? `MyType(MyStruct{})` or `MyType{}`?

**Comment by StunxFS** [comment]
In my opinion, in the case of structs, it is better to print ``MyType(MyStruct {})``.

**Comment by medvednikov** [comment]
Yeah, I agree, with structs it's ok.

**Comment by danieldaeschle** [comment]
Why is it failing?

**Comment by Delta456** [comment]
> 
> 
> Why is it failing?

Windows MSVC being MSVC.

**Comment by danieldaeschle** [comment]
i try to debug it. If anyone knows why this happens, let me know.

**Comment by danieldaeschle** [comment]
```v
type MyType = string

fn main() {
	t := 'test'
	t2 := MyType(t)
	println(t2)
}
```
generates:
```c
static void main__main() {
	string t = tos_lit("test");
	main__MyType2 t2 = ((main__MyType2)(t));
	println(string_str(t2));  // string_str is unnecessary...
}
```

just that all of you are aware of that.

**Comment by StunxFS** [comment]
Wouldn't it be nice to check that the variable is not of type 'string' to make use of the 'str' method?

**Comment by danieldaeschle** [comment]
Fixed that `string_str`

**Comment by StunxFS** [comment]
I think Microsoft doesn't want this pull request to be merged, which is why MSVC fails.

**Comment by danieldaeschle** [comment]
thanks

**Pull request merged**
