### PR TITLE
checker: check if struct field type isn't `multi return`  type

### PR DESCRIPTION
**Pull request by Delta456**
Fixes https://github.com/vlang/v/issues/15083

Code:
```v
struct Tuple{
	data (int, int)
}

fn main() {
	x := Tuple{}
	println(x)
}
```

Output:
```err
vlib/v/checker/tests/struct_multi_return_field_err.vv:2:16: error: cannot use multi return as field type
    1 | struct Tuple{
    2 |     data (int, int)
      |                   ^
    3 | }
    4 |
```

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by Apocryphon-X** [comment]
I found a little variation of this issue using generics that results in the same error as #15083:
```v
struct Tuple<T> {
    data T
}

fn main() {
    sample := Tuple<(int, int)>{}
    println(sample)
}
```
```
==================
/tmp/v_1000/m2.16193058604107645978.tmp.c:1072: error: field 'data' has incomplete type
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by Apocryphon-X** [comment]
Should I make another issue or complement #5366 with this discovery?

> I found a little variation of this issue using generics that results in the same error as #15083:
> 
> ```v
> struct Tuple<T> {
>     data T
> }
> 
> fn main() {
>     sample := Tuple<(int, int)>{}
>     println(sample)
> }
> ```
> 
> ```
> ==================
> /tmp/v_1000/m2.16193058604107645978.tmp.c:1072: error: field 'data' has incomplete type
> ...
> ==================
> (Use `v -cg` to print the entire error message)
> 
> builder error:
> ==================
> C error. This should never happen.
> 
> This is a compiler bug, please report it using `v bug file.v`.
> 
> https://github.com/vlang/v/issues/new/choose[](https://github.com/vlang/v/issues/new/choose)
> 
> You can also use #help on Discord: https://discord.gg/vlang[](https://discord.gg/vlang)
> ```

**Comment by spytheman** [comment]
@Apocryphon-X , yes of course. Please file a new issue.

**Comment by Apocryphon-X** [comment]
@spytheman, done! (#15369 and #15366).

**Pull request merged**
