### PR TITLE
gen: if expressions with multiple statements

### PR DESCRIPTION
**Pull request by Gladear**
Allow generating if expressions with multiple statements.
Add tests covering this and some related errors in the checker.
```v
a := if true {
    x := 1
    y := x + 1
    x + y
} else {
    0
}
```
Edit : Canceled, maybe later :sweat_smile: 
Edit2: Back on track :muscle:

### CODE REVIEW

**Comment by Gladear** [comment]
This should fix #4822 and #4846

**Comment by medvednikov** [comment]
This is a big change, need some time.

**Comment by Gladear** [comment]
No problem :+1: Tell me if you need anything

**Comment by Gladear** [comment]
If you want, I can comment the things I've changed, to explain why I changed them ? It may be easier for you to understand the consequence the changes may have.

**Comment by medvednikov** [comment]
I remember having an example of an expression where only `?:` would work. I can't find it right now. Otherwise I'd implement it like this from the start and not mess with `?:` and `,`...

As I understand, current solution doesn't work only with variable declarations inside if expr blocks.

**Comment by Gladear** [comment]
I found this example:
```v
fn test_if_expression_mutate_var() {
	mut b := false
	r := b && if true {
		b = true
		true
	} else {
		true
	}
	assert r == false
}
```
This test fails. I have no idea how to fix that. Maybe I should keep only the fix on the checker for this PR, until I (or someone else) finds a way to handle this ?

**Comment by dkull** [comment]
The generated C is:
```
        bool b = false;
        bool tmp1;
        if (true) {
                b = true;
                tmp1 = true;
        } else {
                tmp1 = true;
        }
        bool r = b && tmp1;
        // assert
        if (r == false){
```

The issue seems to be that it defers the `b && if ...` until the end, in which case `b` has already been changed

**Comment by Gladear** [comment]
You're comment gave me an idea ! I'll try to make it work :smile:

**Comment by Gladear** [comment]
This will be much more complicated than I expected... I'll change this PR so that it fixes #4846 and I'll continue working on the rest on my side.

**Comment by medvednikov** [comment]
Yeah it's a tricky problem.

**Comment by Gladear** [comment]
Made it :tada: 
There are some edge cases (I see you _multi return_) that won't work, and the generated C code is awful, but it works the tests pass :sweat_smile:

**Comment by dkull** [comment]
I am doing multireturn from expressions in my own PR, but it's still a day or two to away.

**Pull request merged**
