### PR TITLE
all: update to new attribute syntax (stage 3)

### PR DESCRIPTION
**Pull request by joe-conigliaro**
This PR updates all uses (hopefully) of the attribute syntax to the new syntax.

next I will create fixes which will allow the failing tests to pass.

a clean up / removal of old attribute code & deprecation warning will then be done in a final PR

### <samp>🤖 Generated by Copilot at 243ca77</samp>

No summary available (Limit exceeded: required to process 65731 tokens, but only 50000 are allowed per call)

### <samp>🤖 Generated by Copilot at 243ca77</samp>

No walkthrough available (Limit exceeded: required to process 65731 tokens, but only 50000 are allowed per call)

### CODE REVIEW

**Comment by JalonSolov** [comment]
I know `@[attr]` is the "new" way... but Alex was already talking about changing it to `@attr()` instead.  Might want to check with him...

**Comment by joe-conigliaro** [comment]
> I know `@[attr]` is the "new" way... but Alex was already talking about changing it to `@attr()` instead. Might want to check with him...

Im pretty sure that would be ambiguous in a few ways

**Review by spytheman — APPROVED** [review]
Excellent @joe-conigliaro !
Your preparations seem to be paying off very well.

**Comment by joe-conigliaro** [comment]
> Excellent @joe-conigliaro ! Your preparations seem to be paying off very well.

Thanks @spytheman, I think there is just one issue remaining and I know what it is, I think around 5 files are failing the format verification due to that. so the long road is almost at an end :)

**Comment by joe-conigliaro** [comment]
@spytheman even if the test pass dont merge this yet, just want to check something with you

**Comment by joe-conigliaro** [comment]
Just need to fix the fuzz test, then this will finally be good to go :)

**Comment by ylluminate** [comment]
You're a force of nature Joe!

**Pull request merged**
