### PR TITLE
complex : add abs

### PR DESCRIPTION
**Pull request by eulerkochy**
This PR adds `abs` method for a `Complex` struct.
The absolute value of a complex number , `a+bi` (also called the modulus ) is defined as the distance between the origin (0,0) and the point (a,b) in the complex plane.

### CODE REVIEW

**Comment by medvednikov** [comment]
Can you fix the small conflict with `angle`?

**Comment by eulerkochy** [comment]
Sure!

**Comment by eulerkochy** [comment]
Ok cool! Saw it late!

**Comment by eulerkochy** [comment]
@medvednikov that was the other PR right?

**Comment by eulerkochy** [comment]
@medvednikov done! The CI failure is unrelated to this PR. Tests for this PR passes.

**Comment by ntrel** [comment]
There is already `Complex.mod` for the modulus, which is the same. `mod` doesn't use `C.hypot` is more efficient though. See #1072 which tries to resolve this.

**Pull request merged**
