### PR TITLE
cgen: fix some compiler error of empty struct init

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix some compiler error of empty struct init.

- Empty struct init generated c codes `(Foo){0}` will be error in some compiler.
```vlang
/tmp/v/test_session_590515162822/generics_with_nested_generics_fn_test.14081481805459519835.tmp.c:13537:49: error: excess elements in struct initializer [-Werror]
13537 |  main__NestedGeneric ng = (main__NestedGeneric){0};
      |                                                 ^
```
- It should generate `(Foo){}` instead of `(Foo){0}` when it's empty struct.

### CODE REVIEW

**Comment by spytheman** [comment]
This broke bootstrapping with msvc. I am adding a regression test to prevent future breakage, since that struct initialization difference between all other compilers and msvc already broke the CI several times...

**Comment by yuyi98** [comment]
@spytheman   Thanks!  I'm sorry to make these ci errors.  How do we solve empty struct init error in some cases?

**Comment by spytheman** [comment]
@yuyi98, the problem is that msvc has different treatment of that 0 compared to the rest of the compilers, but the generated C code has to be portable, because vc's code is generated by: `v -os windows -o v_win.c cmd/v` .
That `v_win.c` file is used for both gcc/tcc/clang and msvc on windows through `make.bat` .

I think the proper solution for the same file being portable for several different C compilers is using C macros, i.e. have a macro that will expand to 0 or nothing by the compiler itself, based on `#ifdef` conditionals.

We have such a macro, named `EMPTY_STRUCT_INITIALIZATION`, which may just need re-definition with `#ifdef _MSC_VER`  around vlib/v/gen/c/cheaders.v:653 .

**Comment by yuyi98** [comment]
```vlang
#define EMPTY_STRUCT_INITIALIZATION
......
#ifdef _MSC_VER
	#undef __V_GCC__
	#undef EMPTY_STRUCT_INITIALIZATION
	#define EMPTY_STRUCT_INITIALIZATION 0
#endif
```
Is that OK?

**Comment by spytheman** [comment]
I think yes.

**Pull request merged**
