### PR TITLE
Examples: term.ui --- Create vyper.v

### PR DESCRIPTION
**Pull request by nyx-litenite**
Adds a simple snake clone using term.ui.
vyper_1

### CODE REVIEW

**Comment by Larpon** [comment]
@nyx-litenite - just played it, good job!

A few suggestions:
 * Pressing the opposite direction of the snake will result in a Game Over, but going into a wall will not?
 * The snake feels like it moves faster in the vertical direction due to terminal chars, normally, not being equal in cell w/h - can we fix this somehow? (maybe use "half" chars)
 * The "Game Over" would be nice to have as centered text
 * A lower start speed - and then every, say, 10 points - there could be an increase of speed?
 * The eat collision seems off in some cases? Like this: 
image

Just suggestions - not required as the game plays fine as is :smile:

**Comment by nyx-litenite** [comment]
Alrighty, sounds good. I can take a look after work :) I'll make this a draft in the meantime.

**Comment by nyx-litenite** [comment]
>   ~~  * Pressing the opposite direction of the snake after eating a few rats will result in a Game Over, but going into a wall will not? ~~
> 
>  ~~    * The snake feels like it moves faster in the vertical direction due to terminal chars, normally, not being equal in cell w/h - can we fix this somehow? (maybe use "half" chars - or adjust to half speed when going vertical?) ~~
> 
>  ~~   * The "Game Over" would be nice to have as centered text ~~
> 
>     * A lower start speed - and then every, say, 10 points - there could be an increase of speed?
> 
>  ~~   * The eat collision seems off in some cases? Like this case: ~~
>       image

Items that have been stricken out should be taken care of. Idk if I'll implement the variable speed though.

**Comment by nyx-litenite** [comment]
vyper_2

**Comment by Larpon** [comment]
@nyx-litenite wow! 😯 that's awesome. Looks good to me 👍

**Comment by medvednikov** [comment]
Very cool @nyx-litenite :)

**Pull request merged**
