### PR TITLE
v atof implementation

### PR DESCRIPTION
**Pull request by penguindark**
**Motivation**
In order to have v more independent from C and working on math data and DL, I have added some functions and a v implementation of atof, string to float conversion.
All the internal calculus are done with 96 bit precision.
I have also added some "float to string" functions that are very useful when you want have float in different string formats.
I have also integrate **atof64** and the utility functions in the `string.v` and `float.v` files.
It is IEEE 754 compliant.

**Functions**
```v
// **** Utilities ****

// return a string of the input f64 in scientific notation with digit_num digits displayed
pub fn (x f64) strsci(digit_num int) string

// return a long string of the input f64, max  
pub fn (x f64) strlong() string

// **** strconv function ****

// atof64 return a f64 from a string doing a parsing operation
pub fn atof64(s string) f64

```

**test and sample**
```v
a := strconv.atof64('3.1456e-3')
println( a.strlong() )
b := '3.1456e-3'.f64()
println( b.strsci(15) )
```

### CODE REVIEW

**Comment by medvednikov** [comment]
This is amazing work, thanks!

Have you tested the performance compared to the C version?

**Comment by penguindark** [comment]
not yet, I tested the compliance an compatibility with the c standard library and it is OK! :+1: 
I'm experience only one doubt on the gcc on windows, probabily a difference in the text string when you must print an 'infinte'.
I'll benchmark this implementation asap.
But the main point is that another independence piece from C in very near ;)

**Comment by donnisnoni95** [comment]
please remove `v2` binary from your commit

**Comment by penguindark** [comment]
my apologies.
It is possible to add to .gitignore v2? Thanks

**Comment by medvednikov** [comment]
Done.

**Comment by penguindark** [comment]
@medvednikov 
**First benchmark**
I made some fast benchmark, with this version compiled with -O3 we are roughly 3 times slower than gcc atof.
I'm sure that with a little help we can improve a lot :)
Thanks you for your support.

**Pull request merged**
