### PR TITLE
cgen: fix error with arrays named 'new_array'

### LINKED ISSUE #4407: Naming an Array 'new_array' causes a C error
**V version:** 
0.1.26 83289d7.f91e3a5
**OS:** 
windows 10
**What did you do?**
mut new_array:=[]string
new_array<<"hello"

**What did you expect to see?**
The program getting compiled

**What did you see instead?**
```
C:\Users\malt2\AppData\Local\Temp\v\test.tmp.c: In function 'wmain':
C:\Users\malt2\AppData\Local\Temp\v\test.tmp.c:4665:27: error: called object 'new_array' is not a function or function pointer
  array_string new_array = new_array(0, 0, sizeof(string));
                           ^~~~~~~~~
C:\Users\malt2\AppData\Local\Temp\v\test.tmp.c:4665:15: note: declared here
  array_string new_array = new_array(0, 0, sizeof(string));
               ^~~~~~~~~
C:\Users\malt2\AppData\Local\Temp\v\test.tmp.c: In function 'strconv__ftoa__f32_to_str':
C:\Users\malt2\AppData\Local\Temp\v\test.tmp.c:5032:8: warning: initialized field overwritten [-Woverride-init]
   .u = 0,
        ^
C:\Users\malt2\AppData\Local\Temp\v\test.tmp.c:5032:8: note: (near initialization for '(anonymous).u')
...
==================
(Use `v -cg` to print the entire error message)

builder error: C error.
```

### PR DESCRIPTION
**Pull request by krischerven**
fixes #4407

### CODE REVIEW

**Comment by medvednikov** [comment]
Let's rename it to __new_array instead

V identifiers can't begin with __

Actually it's a bit tricky, requires a 2 step process, I'll do it

**Comment by krischerven** [comment]
Ok. Should I close this PR?

**Comment by medvednikov** [comment]
I'll keep it open so that I don't forget :)

**Comment by krischerven** [comment]
@medvednikov This still occurs, is the new code satisfactory?

**Pull request merged**
