### PR TITLE
README: replace deprecated align attribute, correct tcc info in C com…

### PR DESCRIPTION
**Pull request by JalonSolov**
Please read the changes carefully... make sure they make sense to you.

### CODE REVIEW

**Review by spytheman — COMMENTED** [review]
I do agree with every single line/change here. Excellent work.

**Comment by ylluminate** [comment]
Seems good. I'd have left a couple of the `.exe`s and a colon for to clarify connection to that which follows, etc., but I suppose my conventions perhaps are not the norm; I just do them for clarity. 🙂

**Review by ylluminate — APPROVED** [review]
Seems good. I'd have left a couple of the `.exe`s and a colon for to clarify connection to that which follows, etc., but I suppose my conventions perhaps are not the norm; I just do them for clarity. 🙂

**Comment by JalonSolov** [comment]
The only reason to type the `.exe` extension is if you're afraid there might be a possibility of Windows finding a `.cmd` file with the same name before it finds your `.exe`.  When bringing up V, the possibility of that happening is too low to be worthwhile mentioning.

**Comment by ylluminate** [comment]
Lol... Like I said, I have dealt with a lot of "novice" users... Perhaps I'm using too kind a term here. You're probably right. Just explaining my thoughts - but this is probably not the last time you'll see me do things a certain way that you may not think is traditionally kosher. C'est la vie I suppose. 😝

**Comment by JalonSolov** [comment]
Oh, I certainly approve, just not certain it's necessary in this case.

**Pull request merged**
