### PR TITLE
cgen: fix error for fn argument of optional  (fix #6708)

### LINKED ISSUE #6708: compilation error when passing option type to a function
**V version:** V 0.1.29 9fdf04b.e250547
**OS:** Windows 7 Professional (x64, little-endian)
**CC version:** clang version 10.0.0 (https://github.com/llvm/llvm-project.git d32170dbd5b0d54436537b6b75beaf44324e0c28)

**What did you do?**
```v
fn optional_arg(x ?int) {
	println("int type")

}

fn main() {
	optional_arg(1)
}
```

**What did you expect to see?**
I expected V to either to throw an error for unable to convert between `any_int` to `option_int` or convert the corresponding type to its option counterpart
 
**What did you see instead?**
```
C:\Users\lambda\AppData\Local\Temp\v\hello_world.1829071214341309535.tmp.c:8082:21: error: passing 'int' to parameter of incompatible type 'Option_int' (aka 'struct Option_int')
        main__optional_arg(1);
                           ^
C:\Users\lambda\AppData\Local\Temp\v\hello_world.1829071214341309535.tmp.c:8077:36: note: passing argument to parameter 'x' here
void main__optional_arg(Option_int x) {
                                   ^
9 warnings and 1 error generated.
```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix error for fn argument of optional  (fix #6708).

- Fix error for fn argument of optional.
- Add test.

```v
fn optional_arg(x ?int) {
	println('int type')
	assert true
}

fn main() {
	optional_arg(1)
	optional_arg(none)
}

PS D:\Test\v\tt1> v run .
int type
int type
```

### CODE REVIEW

**Comment by medvednikov** [comment]
```
FAIL  [ 63/132]   289.840 ms examples/net_raw_http.v
==================
/tmp/v/test_session_773095126393/net_raw_http.904352[71](https://github.com/vlang/v/runs/6060675957?check_suite_focus=true#step:16:71)1393307[73](https://github.com/vlang/v/runs/6060675957?check_suite_focus=true#step:16:73)34.tmp.c:21408: error: cannot convert 'struct Option_net__Addr' to 'unsigned short'
...
==================
(Use `v -cg` to print the entire error message)
```

**Comment by spytheman** [comment]
```v
fn optional_arg(x ?int) {
        println('int type: $x')
        assert true
}

fn test_fn_arg_of_optional() {
        optional_arg(0)
        optional_arg(1)
        optional_arg(none)
}
```
with this PR prints:
```
int type: 0
int type: 1
int type: 0
```
i.e. there is no way to distinguish `optional_arg(0)` from `optional_arg(none)` or to handle the `none` explicitly inside the function.

I think that without fully implementing https://github.com/vlang/rfcs/blob/master/error_handling.md , a partial implementation, that only allows optional arguments will lead to undefined/buggy situations like in the above example, and it is better to have an explicit checker error, than that.

**Comment by yuyi98** [comment]
OK, I see.

**Comment by spytheman** [comment]
Closing this for now, since I've merged #14076 .

**Pull request closed without merging**
