### PR TITLE
v: missing `-skip-unused` fixes

### PR DESCRIPTION
**Pull request by felipensp**
This PR fixes some missing break when enabling `-skip-unused` as default.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQ1YTc3MWQyZWY0Y2JjYzQ2YjY0MTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.3U2IzRbslNDk7dbxq3z9z_oWiXLw1M0ezBxbXdlBU4c">Huly&reg;: <b>V_0.6-21419</b></a></sub>

### CODE REVIEW

**Comment by medvednikov** [comment]
@felipensp we can merge this for now by commenting `res.skip_unused = true` in pref.v

To make sure all tests pass otherwise and so that we don't work on the same thing.

**Comment by felipensp** [comment]
> @felipensp we can merge this for now by commenting out `res.skip_unused = true` in pref.v
> 
> To make sure all tests pass otherwise and so that we don't work on the same thing.

Ok @medvednikov removing commenting again...

**Comment by medvednikov** [comment]
```
>    failed   1/1 times, doing `'/home/runner/work/v/v/v' -d no_backtrace -skip-unused run 'vlib/v/tests/skip_unused/aggregate_call.vv'`
 FAIL  [21/40]   167.017 ms vlib/v/tests/skip_unused/aggregate_call.vv
============
failed cmd: '/home/runner/work/v/v/v' -d no_backtrace -skip-unused run 'vlib/v/tests/skip_unused/aggregate_call.vv'
expected_out_path: vlib/v/tests/skip_unused/aggregate_call.skip_unused.run.out
============
expected (len:     0, hash: 0):

============
found    (len:   844, hash: -1330108580):
================== C compilation error (from tcc): ==============
cc: /tmp/v_1001/tsession_7f29a5053b80_01JDPQB0ZNC7D1HSHVPFW998WE/aggregate_call.01JDPQFMHCARCFTQ8RPHSJ1WC4.tmp.c:1386: warning: implicit declaration of function '__new_array_with_default_noscan'
cc: /tmp/v_1001/tsession_7f29a5053b80_01JDPQB0ZNC7D1HSHVPFW998WE/aggregate_call.01JDPQFMHCARCFTQ8RPHSJ1WC4.tmp.c:1386: error: '{' expected (got ";")
=================================================================
```

**Comment by felipensp** [comment]
image

**Comment by medvednikov** [comment]
```
>    failed   1/1 times, doing `'/home/runner/work/v/v/v' -d no_backtrace -skip-unused run 'vlib/v/tests/skip_unused/println_os_executable.vv'`
 FAIL  [36/40]   331.977 ms vlib/v/tests/skip_unused/println_os_executable.vv
============
failed cmd: '/home/runner/work/v/v/v' -d no_backtrace -skip-unused run 'vlib/v/tests/skip_unused/println_os_executable.vv'
expected_out_path: vlib/v/tests/skip_unused/println_os_executable.skip_unused.run.out
============
expected (len:    21, hash: -[549](https://github.com/vlang/v/actions/runs/12052778293/job/33606890108?pr=22978#step:14:550)076427):
println_os_executable
============
found    (len:   990, hash: 1157929151):
================== C compilation error (from /home/runner/work/v/v/thirdparty/tcc/tcc.exe): ==============
cc: /tmp/v_1001/tsession_7f738ec88b80_01JDQJ51SZB2GR8Z018TYY3307/println_os_executable.01JDQJB7Q0CC7FET1H4CJY9NES.tmp.c:4999: warning: cast between pointer and integer of different size
cc: /home/runner/work/v/v/thirdparty/tcc/lib/libgc.a: error: 'GC_noop1_ptr' defined twice
cc: tcc: error: undefined symbol 'charptr_vstring_literal'
```

**Pull request merged**
