### PR TITLE
examples: add port of simple triangle sokol sample

### PR DESCRIPTION
**Pull request by Larpon**
This PR adds a V port of https://github.com/floooh/sokol-samples/blob/master/sapp/triangle-sapp.c
The aim of this example is to be short and clear about what is happening in the code.

### CODE REVIEW

**Comment by spytheman** [comment]
I can add an exception for this like for the other glsl examples, in around cmd/tools/modules/testing/common.v:170 ?

**Comment by penguindark** [comment]
@Larpon not so sure if this example run on all platforms: color as float may not work on mobiles,
but it is only a speculation of mine.

**Comment by spytheman** [comment]
it does work on linux and macos

**Comment by Larpon** [comment]
> ~I can add an exception for this like for the other glsl examples, in around cmd/tools/modules/testing/common.v:170 ?~ Oh, you already did, sorry.

Yeah it got a little messed up. Thanks for fixing it!

**Comment by penguindark** [comment]
@Larpon not a simply answer, in my code I usually use: `.ubyte4n // color as u32`
but I'm not sure what is the best solution in this case, sorry.

**Comment by Larpon** [comment]
> @Larpon not a simply answer, in my code I usually use: `.ubyte4n // color as u32` but I'm not sure what is the best solution in this case, sorry.

No problem - the nice thing is that you mention it - because **if** the problem arise I'll have a chance a fixing it instead of a 4 hour bug hunt in the blind :smile:

**Pull request merged**
