### PR TITLE
checker: require `mut` with `if` smart cast

### PR DESCRIPTION
**Pull request by ntrel**
Require `mut` to mutate `name` with `if mut name is T`. (`vfmt` already updated in #6188).
Require `mut` to mutate `name` with `if expr is T as mut name`, update `vfmt`.

Draft as it needs error tests.

### CODE REVIEW

**Comment by danieldaeschle** [comment]
In case:
```v
mut a = SumType(0)

if a is int {
    // why does a needs to be marked as mut in if if it's already declared with mut?
}
```

**Comment by ntrel** [comment]
> why does a needs to be marked as mut in if if it's already declared with mut?

Internally V is actually creating a new variable, but your right the status quo isn't bad. But for the `as` case the new variable doesn't even have the same name. Perhaps we could only require mut with `as`.

**Comment by danieldaeschle** [comment]
that's right. but i think we will get rid of the `as` feature in future if we migrate to union in sum types.

**Comment by danieldaeschle** [comment]
is this needed anymore?

**Comment by medvednikov** [comment]
I think it's handled by your recent work?

**Comment by ntrel** [comment]
I could update this just for `as`.

> i think we will get rid of the as feature in future if we migrate to union in sum types.

I don't see why union sum types affects `as`. That pull implemented shadowing for fields, but surely we still need `as` when the condition is a function call? Also when the condition is mutable. Smart casting can't work safely then.

**Comment by danieldaeschle** [comment]
I removed itwith the last comment. It was Discussed with alex before.

**Comment by ntrel** [comment]
@danieldaeschle mutable smart casting allows memory safety violation. That's why we need something like `as`.

**Comment by danieldaeschle** [comment]
You can also create a new var by your own with `as`. It's the same behavour.

**Pull request closed without merging**
