### PR TITLE
Compiler: Scoped defer + Build tests with msvc

### PR DESCRIPTION
**Pull request by emily33901**
Changes defer to perform at the end of every scope (including returns) as opposed to singularly at the end of functions - I think this makes more sense and could also be more useful. 

It may also end up that having a non-scoped defer and using lambdas to control defers may be better (like is done in go). 

And building tests with `-os msvc` instead of just with the msvc built compiler to make sure it doesnt regress for real!

### CODE REVIEW

**Comment by emily33901** [comment]
Not sure why CI has failed like that

**Comment by medvednikov** [comment]
```
'v.exe' is not recognized as an internal or external command,
operable program or batch file.
'v.msvc.exe' is not recognized as an internal or external command,
operable program or batch file.
'v.msvc.exe' is not recognized as an internal or external command,
operable program or batch file.
'v' is not recognized as an internal or external command,
```

I've been seeing this since yesterday.

Travis started failing like that about an hour ago.

**Comment by emily33901** [comment]
It downloads v.c and then fails to build it?

**Comment by emily33901** [comment]
vc.exe fails to build v.exe

**Comment by emily33901** [comment]
```
if p.tok != expected {
		println('check()')
		s := 'expected `${expected.str()}` but got `${p.strtok()}`'
		p.next()
		println('next token = `${p.strtok()}`')
		print_backtrace()
		p.error(s)
	}
```

**Comment by emily33901** [comment]
fairly certain it errors here but travis doesnt pick up on the output or smth (or printfs are smashed again)

**Comment by medvednikov** [comment]
Works on my Windows VM.

**Comment by emily33901** [comment]
okay nice

**Comment by emily33901** [comment]
Well the travis logs has a `check()`but then nothing else - you mean this pr compiles or that printfs work

**Comment by joe-conigliaro** [comment]
you guys there was a typo i fixed it in a PR that is whats causing the issue https://github.com/vlang/v/pull/1508

@emily33901 @medvednikov

**Comment by medvednikov** [comment]
Thanks @joe-conigliaro

**Comment by emily33901** [comment]
okay so too many tests and i need to remove the debugging stuff

**Comment by medvednikov** [comment]
It's ok on master now @emily33901

**Comment by emily33901** [comment]
That should make the tests for pass with `-os msvc`

**Comment by emily33901** [comment]
I really think flag should be split up into stuff lie `#lib` or `#obj` which would really help with trying to parse them out for msvc

**Comment by emily33901** [comment]
Sigh geometric mean test fails on msvc

**Pull request merged**
