### PR TITLE
all: make `lock` and `rlock` dead lock free :-)

### PR DESCRIPTION
**Pull request by UweKrueger**
Using locks usually involves the problem of deadlocks. Example:
```v
//thread 1:
lock a, b {
    ...
}

//thread 2:
lock b, a {
    ...
}
```
Here, thread 1 may lock `a` while thread 2 locks `b`. Then thread 1 waits for `b` while thread 2 waits for `a` - both not getting freed - a dead-lock.

In principle this can be solved by using always the same lock order. However, the threads are different functions and/or have been called with different argument orders so it's very hard (sometimes impossible) to make this sure at development/compile time.

This PR solves the problem at run time! In every lock statement the mutexes are sorted by their address before locking is done, so it can be assured that always the same order is used. If the same mutex occurs twice in the lock list it's only locked once (with `lock` if there are mixed `rlock`/`lock` occurences).

For this to work, nested locks are forbidden. To be able to still use `lock` and `rlock` in the same code the syntax has been extended:
```v
lock a, b, c; rlock d, e {
    // read `d` or `e`
    // read, modify, write a, b, c
}
```
From within a `lock` block only functions with `mut` or value arguments/receiver can be called (otherwise nested locks would become possible thru the backdoor).

Concerning `shared` variables, `lock` and `rlock` V can now be called "dead-lock free".
Channels, however, still make it possible to create dead-locks.

### CODE REVIEW

**Comment by medvednikov** [comment]
Looks really cool, @UweKrueger . Great job!

**Comment by dumblob** [comment]
Good idea! Simple and readable implementation, easy to grasp. Well done, thanks!

Some questions:

1. What's the (approximate) performance penalty in a heavily multithreaded code with a mixture of `lock` and `rlock`?

2. Why was the `;` (semicolon) syntax introduced? Why not simply `lock a, b, c rlock d, e {`? I find the semicolon confusing and not matching most of the *V* code.

**Comment by UweKrueger** [comment]
> 1. What's the (approximate) performance penalty in a heavily multithreaded code with a mixture of `lock` and `rlock`?

It depends on the number of elements to lock. For 3 elements the penalty is about 1.3 nanoseconds, for 5 about 3.2 nanoseconds (on my Ryzen 7 3800X running Linux). It's O(n^2), so the time increases with the square of the number of elements. (For >10 elements another sort algorithm with O(n*ln(n)) would be better, but I think this is no realistic scenario.)
In practice, i.e. when there has to be waited for mutexes to become available the sorting time can probably be neglected. And a solution with a watchdog to detect a dead-lock will waste significantly more time.

> 2. Why was the `;` (semicolon) syntax introduced? Why not simply `lock a, b, c rlock d, e {`? I find the semicolon confusing and not matching most of the _V_ code.

V has the good-old C-style `for` loop:
```v
for i := 0; i < 10; i++ {
    ...
}
```
There, the semicolons are used to separate statements/expressions that belong together. `lock a, b, c` and `rlock d, e` in the same way are separate statements/expressions that form a semantic unit that is followed by a `{ ... }` group. That's why I've chosen the syntax with `;` here, too.

**Comment by dumblob** [comment]
>It depends on the number of elements to lock. For 3 elements the penalty is about 1.3 nanoseconds, for 5 about 3.2 nanoseconds (on my Ryzen 7 3800X running Linux). It's O(n^2), so the time increases with the square of the number of elements. (For >10 elements another sort algorithm with O(n*ln(n)) would be better, but I think this is no realistic scenario.)

Thanks for the numbers. Once *V* semantics will mature and freeze, we can optimize e.g. by special casing for 1, 2, and maybe 3 locks by using a compile-time sorting network. 4 locks and more will be sorted with the sorting algorithm (I'd actually recommend an [ILP bubble sort](https://blog.reverberate.org/2020/05/29/hoares-rebuttal-bubble-sorts-comeback.html ) - see https://github.com/MusicTheorist/Rewritten-Grailsort/issues/1 ).

>`for i := 0; i < 10; i++ {`

I'm aware of that, but I have a different feeling from `lock a, b, c; rlock d, e {` due to the keyword `rlock` already separating the statements (pretty much as many other keywords in V do - e.g. one can use `module` `import` `type` `const` in one row without `;`).

**Pull request merged**
