### PR TITLE
Move WS example to examples folder

### PR DESCRIPTION
**Pull request by esquerbatua**
This PR moves ws example into examples folder.

### CODE REVIEW

**Comment by LouisSchmieder** [comment]
could you please fix the examples

**Comment by LouisSchmieder** [comment]
do we need the utf8.h?

**Comment by esquerbatua** [comment]
> do we need the utf8.h?

I don't know exactly why the creator of the module ws, added the dependency, but is not necessary

**Comment by esquerbatua** [comment]
Also there are an log module inside ws, if I have time I want to replace it with the v log module

**Comment by esquerbatua** [comment]
Failing example:
FAIL  [16/49]  4400.930 ms examples/gg/raven_text_rendering.v

**Pull request merged**
