### PR TITLE
cgen: fixes for ... in with index

### PR DESCRIPTION
**Pull request by andrepiske**
When using `for idx, value in foo` where `foo` is a struct with a `next` function (i.e. an iterator), no C code is generated for the `idx` variable.

This is an attempt to solve issue #11994 using the opinion that the index should be an integer that starts at zero and counts up on each iteration. I realize this might not be the desired solution, but here is the PR anyway :)

The fix only touches cgen. It changes how code is generated for _for .. in_ cases when using an iterator. Instead of generating a `while (1) {` loop, it will always generate a `for (i=0;;++i) {` loop, where the variable name `i` is the variables used as the key, or a temporary name in case there is no index declared.

### CODE REVIEW

**Comment by spaceface777** [comment]
Maybe we could keep the existing infinite `while` loop if the user didn't specify an index variable? That avoids unnecessary instructions when compiling tcc or gcc without optimizations enabled[<sup>1</sup>](https://godbolt.org/z/WxGhW5nEh).

Apart from that, this looks good, thanks for the fix :)

**Comment by medvednikov** [comment]
> Maybe we could keep the existing infinite while loop if the user didn't specify an index variable?

Yeah, let's do that.

**Comment by andrepiske** [comment]
Just did that. I'm now wondering if the index should be something else than `int`, like `unsigned int` or `unsigned long int` -- since it's never going to be negative anyway. Any input on that?

@spaceface777 btw thanks for the godbolt link, I didn't know that awesome tool 😄

**Comment by JalonSolov** [comment]
If you expect someone might have more than 2 _billion_ elements in a single array, it would be time to change the type away from `int`.  There are also arguments for leaving it as a signed type for ease of doing index arithmetic (which I'm still not convinced about, myself, but others seem to be).

**Comment by spytheman** [comment]
`i64` is both signed and large enough hopefully

**Comment by JalonSolov** [comment]
It needs to be the "native" size of the machine.  `i64` just causes extra code on a 32-bit machine.  But I think he was talking about the generated type anyway... `long` vs `unsigned long` vs `unsigned long long`, etc.  `size_t` is likely a better option for the C code, as that is adjusted automatically per machine.

**Comment by andrepiske** [comment]
I went with @JalonSolov suggestion of changing to `size_t`, which then adjusts itself according to the machine. I wasn't comfortable with `int` because as 2 billion sounds too big, one never knows what developers are up to and since this use case is for an iterator and not an array, I would think the use cases might be broader. In the end, I also really doubt anyone will ever need more than i32 for the index :)

In any case, IMO it's now ready to go! 😃

**Pull request merged**
