### PR TITLE
example: add pendulum_sim

### PR DESCRIPTION
**Pull request by jordan-bonecutter**
I wrote the pendulum simulator to learn V, I think it could be a good addition to the examples directory.

Essentially, the pendulum sim runs a simulation of a pendulum with a metallic tip swinging over three magnets. I run this simulation with the initial position at each pixel in an image and color the pixel according to the magnet over which it finally rests.

I used some fun features in V like coroutines, channels, struct embedding, mutability, methods, and the like.

### CODE REVIEW

**Comment by spytheman** [comment]
I just ran the simulation with:
```v
fn sim_runner(mut state SimState, params SimParams) Pixel {
    // do the simulation!
    for _ in 0 .. 100000 { // original
```
vs
```v
fn sim_runner(mut state SimState, params SimParams) Pixel {
    // do the simulation!
    for _ in 0 .. 1000 { // reduced iterations
```
and they seem to produce the same results bit for bit:
```
$ md5sum test_1000.ppm test_100000.ppm
027801357fbfe0b8c77bd7756599d49d  test_100000.ppm
027801357fbfe0b8c77bd7756599d49d  test_1000.ppm
```
except that the second one is much faster.

Can we reduce the number of iterations, so that it runs faster for most people?

**Comment by spytheman** [comment]
If I increase width & height to 800x600, I get a small difference in the center (see the images below),
but the 1000 iterations took ~30 seconds with: `./v -cc clang-11 -prod run examples/pendulum_sim/sim.v`, while 100000 iterations took 1375 seconds.

test_100000
test_1000

**Comment by jordan-bonecutter** [comment]
Yes, let's do that. I was having some issues with instability so I increased the sim time but it seems I did it unnecessarily large.

**Comment by jordan-bonecutter** [comment]
The center should be very unstable anyways so that's not too concerning

**Pull request merged**
