### PR TITLE
html: Create html module

### PR DESCRIPTION
**Pull request by Jictyvoo**
To make V have a easily builtin module that allows users to parse and explore HTML files, the html module has been created, which have two main objects: Parser and DocumentObjectModel (or DOM).

### Parser

Responsible for read HTML in full strings or splited string and returns all Tag objets of it HTML or return a DocumentObjectModel, that will try to find how the HTML Tree is.

#### split_parse(data string)
This functions is the main function called by parse method to fragment parse your HTML

#### parse_html(data string, is_file bool)
This function is called passing a filename or a complete html data string to it

#### add_code_tag(name string)
This function is used to add a tag for the parser ignore it's content. For example, if you have an html or XML with a custom tag, like `<script>`, using this function, like `add_code_tag('script')` will make all `script` tags content be jumped, so you still have its content, but will not confuse the parser with it's `>` or `<`

#### finalize()
When using **split_parse** method, you must call this function to ends the parse completely

#### get_tags() []Tag_ptr
This functions returns a array with all tags and it's content

#### get_dom() DocumentObjectModel
Returns the DocumentObjectModel for current parsed tags

### WARNING
If you want to reuse parser object to parse another HTML, call `initialize_all()` function first

### DocumentObjectModel

A DOM object that will make easier to access some tags and search it

#### get_by_attribute_value(name string, value string) []Tag_ptr
This function retuns a Tag array with all tags in document that have a attribute with given name and given value

#### get_by_tag(name string) []Tag_ptr
This function retuns a Tag array with all tags in document that have a name with the given value

#### get_by_attribute(name string) []Tag_ptr
This function retuns a Tag array with all tags in document that have a attribute with given name

#### get_root() Tag_ptr
This function returns the root Tag

#### get_all_tags() []Tag_ptr
This function returns all important tags, removing close tags

### Tag

An object that holds tags information, such as `name`, `attributes`, `children`

#### get_children() []Tag_ptr
Returns all children as an array

#### get_parent() &Tag
Returns the parent of current tag

#### get_name() string
Returns tag name

#### get_content() string
Returns tag content

#### get_attributes() map[string]string
Returns all attributes and it value

#### text() string
Returns the content of the tag and all tags inside it. Also, any `<br>` tag will be converted into `\n`

## Future

In the future, I'll try to complete xpath object, wich will allow users to search tags more easily.

### CODE REVIEW

**Comment by Jictyvoo** [comment]
Additional information about performance, I ran two codes, one in V, using this module, and other in Python, using BS4.
Including file reading operation, both codes give an average time very close.
V (normal compilation): **Parse file** - 88.605 ms | **Generate DOM and verify`<script>` tag names** - 32.776 ms
V -prod: **Parse file** - 38.750 ms | **Generate DOM and verify`<script>` tag names** - 21.564 ms
Python3.8: **Parse file** - 84.351 ms | **Generate DOM and verify`<script>` tag names** - 1.194 ms

I think if make dom tree constructor run while parsing the file, some time can be saved
All code runs with same file, which has 141525 characters. 

V:
```v
module main

import html
import benchmark

fn main() {
	mut parser_average := i64(0)
	mut dom_average := i64(0)
	mut total := 0
	for counter := 0; counter < 100; counter++ {
		mut parser := html.Parser{}
		parser.add_code_tag('')
		mut b := benchmark.start()
		parser.parse_html('khwiki_test.html', true)
		parser_average += b.measure('parse file') // mut
		dom := parser.get_dom()
		for s_tag in dom.get_by_tag('script') {
			if s_tag.get_name() != 'script' {
				return
			}
		}
		dom_average += b.measure('generate dom')
		total++
	}
	println('Parse file - ${parser_average/(total)} ms')
	println('Generate DOM and print `<script>` tag names - ${dom_average/(total)} ms')
}
```
Python:
```python
from bs4 import BeautifulSoup, Tag
import time


def main():
    parser_average = 0
    dom_average = 0
    total = 0
    for counter in range(0, 100):
        start = time.time()
        file_to_parse = open("./khwiki_test.html", "rb")
        page_content = file_to_parse.read().decode("utf-8")
        soup = BeautifulSoup(page_content, "html.parser")
        file_to_parse.close()
        end = time.time()
        parser_average += (end - start) * 1000
        start = time.time()
        for scripts in soup.find_all("script"):
            if scripts.name != "script":
                return
        end = time.time()
        dom_average += (end - start) * 1000
        total += 1

    print("Parse file - %f ms" % (parser_average / (total)))
    print(
        "Generate DOM and print `<script>` tag names - %f ms" % (dom_average / (total))
    )


main()
```

**Comment by nedpals** [comment]
@Jictyvoo Great work man. But I think it would be much better to have it at least as a officially-maintained package instead similar to markdown: https://github.com/vlang/markdown.

This way it would be easier to update compare to syncing it with each compiler release. Also, we can change the name to `htmlparser` instead to avoid ambiguities if thats the case (??).

**Comment by medvednikov** [comment]
Go uses `net.html`, I think we should also move it to `net.html`.

https://godoc.org/golang.org/x/net/html

**Comment by medvednikov** [comment]
Great job @Jictyvoo, I think it's fine having it in vlib, especially if there's a browser in V in the future :)

**Comment by Jictyvoo** [comment]
@nedpals I think about it before, and thinking about whrere to put It, or the name itself. I think now that follow @medvednikov  suggestion is a good way, I'll rename it

**Comment by Jictyvoo** [comment]
Initialy it was a standalone module because is possible to search tags and information in dom object, making scrappers and crawlers possible. But moving to net module make more sense for anyone studyng scrappers and crawlers in V, or a browser in V too.

**Comment by medvednikov** [comment]
Merged, thanks for your contribution!

**Comment by nedpals** [comment]
Noicee. Can't wait to use it :))

**Pull request merged**
