### PR TITLE
Optimized processing path separator

### PR DESCRIPTION
**Pull request by yuyi98**
This PR is to optimized processing path separator.

1. delete `pub os.path_separator`.
2. change `filepath.path_separator` to `pub filepath.separator`.
3. modify related calls.

Its benefits is unified handling path separator.

### CODE REVIEW

**Comment by alexesprit** [comment]
Probably, we should keep the constant in `os` module for compatibility and mark it as deprecated.

**Comment by yuyi98** [comment]
@alexesprit Thanks for your advice! It's not a function, How can I mark it as `[deprecated]`

**Comment by medvednikov** [comment]
Interesting, Go has both `os.PathSeparator` and `filepath.Separator`.

Probably due to their philosophy of keeping number of imports as minimal as possible.

**Comment by yuyi98** [comment]
Module `os` already `import filepath`, I think it's best to keep uniqueness as vlang do.

**Comment by alexesprit** [comment]
@yuyi98 Yes, you can't use `deprecated` attribute, but you can add a comment:
```v
pub const (
	// FIXME Remove this separator, as it a part of `filepath` module.
	path_separator = '/'
)
```

**Pull request merged**
