### PR TITLE
Regex: more flexibility for bsls, small fixes, first implementation negation groups

### PR DESCRIPTION
**Pull request by penguindark**
**What's inside**
- Added better support for bsls checks
- First implementation for negation groups `(?!prefix)postfix`

Note:
?! stand for: if the following match is prefixed by this group then the match must fail!

Example:
```v
import regex
fn main() {
    mut query := r"(?!auto)\w+ile"
    mut re := regex.regex_opt(query) or { panic(err) }
    println("query: ${re.get_query()}")

    tests := [
        'automobile',
        'botomobile',
        'auto_caravan'
        'moto_mobile'
    ]

    for test in tests {
        println('\nTesting string: $test')
        start, end := re.match_string(test)
        if start >= 0 {
            it_is_good := if end == test.len {true} else {false}
            println('$start $end is_match=${it_is_good} [${test[start..end]}]')
        } else {
            println('NO MATCH [${test}]')
        }
    }
}
```
yield to:
```
query: (?!auto)\w+ile

Testing string: automobile
NO MATCH [automobile]

Testing string: botomobile
0 10 is_match=true [botomobile]

Testing string: auto_caravan
NO MATCH [auto_caravan]

Testing string: moto_mobile
0 11 is_match=true [moto_mobile]
```

### CODE REVIEW

**Comment by penguindark** [comment]
@spytheman I'm exerience this test failing in the CI:
`FAIL  [ 10/672]  3623.500 ms vlib/v/parser/tests/check_undefined_variables_too_deep_nested.vv`
What is it? ❓

**Comment by spytheman** [comment]
(rebased over current master, which has `max_expr_level` reduced to 310, instead of 2500)

**Comment by dumblob** [comment]
@penguindark during skimming of this PR I thought "hm, it's getting quite complex to feel assured the expression I wrote is correct".

Do you think we could leverage the recently introduced "general compile-time computation" support and implement a ".validate()" method which could be called in compile-time and validate the syntactical correctness of the expression?

I imagine I'd write something like `sassert re.validate( myregexstring, ['these', 'inputs shall', 'match'], ['and these', 'shall', 'not'] )` (`sassert` being a compile-time assert).

**Comment by penguindark** [comment]
@dumblob I can possibly add a function but I don't understand what is the purpose of this functionality.
This `validate` is more like the test functions in the test file, only "compressed" in one function.

**Comment by penguindark** [comment]
you can use the simply `assert` for this purpose :)

**Comment by JalonSolov** [comment]
`assert` works in regular mode, but becomes a NOOP with `-prod`.

**Comment by penguindark** [comment]
I see -_-

**Comment by JalonSolov** [comment]
Well, it still shouldn't be a problem, because you should always compile without `-prod` while developing, and only with `-prod` when you're ready to "release" something... right?  :-\

**Comment by dumblob** [comment]
`assert` on its own unfortunately doesn't fulfill my wish to avoid panics due to regex syntax errors. The compile-time support doesn't seem to be enough functional nor intuitive in this context:

```v
const ( myregex = regex.regex_opt( r"(?!auto)\w+le" ) or { panic(err) } )
```
^^^doesn't seem to work at all. And even if it worked, it wouldn't be as convenient as using a true inline static assert.

And the second point of encouraging programmers to write "micro tests" is thus kind of borked. I can't use runtime `assert` because it depends on the path through all nested conditions and thus can't be relied upon (it's difficult to ensure the particular assert will be reached in bigger apps as it's very demanding and generally difficult to simulate the whole-app behavior).

I'm really thinking of some wrapper API (maybe just one function) forcing one to provide a list of test matches and list of test non-matches **while** creating the regex. This'd make people at least think of one example match and one example non-match. But again, this requires compile-time support which seems not given (at least not yet as per the example above).

Can we actually mark/tog a function in a module to be only callable in compile-time? That'd be very handy for the wrapper API I speak about in the previous paragraph.

**Comment by penguindark** [comment]
Ok I'll think about to implement a sort ot "assert" at runtime for the regex :)

**Comment by dumblob** [comment]
> Ok I'll think about to implement a sort ot "assert" at runtime for the regex :)

Wait, you meant "compile time", right? Because for runtime we already can achieve it easily.

**Comment by penguindark** [comment]
compile time is not possible for regex, at least without an immense effort :(

**Comment by dumblob** [comment]
Ah, ok. What are the main obstacles in your opinion?

**Comment by penguindark** [comment]
run the regex compiler at runtime, need some compiler magic and it is hevy

**Comment by dumblob** [comment]
> run the regex compiler at runtime, need some compiler magic and it is hevy

Ok. Just to clarify - do you expect the obstackles be rather on the side of *V* language implementation or on the side of the regex module?

So far I feel it's 100% about the V lang impl. and 0% about regex module.

**Comment by JalonSolov** [comment]
It's probably 99% V lang impl.

However, that 99% will make V larger, slower, and more complex, for something that's relatively rare compared to the bulk of code "out there".

**Comment by penguindark** [comment]
I agree with @JalonSolov the complexity is in the compiler side and this task is very rarely used IMHO.
The regex module is simply V code nothing more.

**Comment by dumblob** [comment]
Thanks for the insight! That's a pity but somewhat understandable.

What I don't understand though is what the **4+k SLOC** of the V interpreter are then useful for if this, still rather simpler use case compared to a full featured V evaluation, is currently impossible (or not even planned as I understood from you @JalonSolov ) to achieve?

Could you point me to some discussions about this (if it's on Discord, please copy & paste to some GitHub Discussion topic)? If this hasn't been discussed enough, then I'd invite Alex to express himself about this.

**Comment by penguindark** [comment]
If you mean a discussion about the interpreter on discord there is an entire channel about it.
Otherwise, if you mean a discussion about V validation at compiler time I don't remember a discussion about this topic.
Anyway, when the interpreter will be ready, add a "compiler time" validation will be more simple.

**Comment by dumblob** [comment]
> If you mean a discussion about the interpreter on discord there is an entire channel about it. Otherwise, if you mean a discussion about V validation at compiler time I don't remember a discussion about this topic.

Hm, I thought it's the same thing. Apparently I was wrong. In which case it's clearly a duplicated effort & duplicated code in V implementation.

>Anyway, when the interpreter will be ready, add a "compiler time" validation will be more simple.

Oh, it's not yet ready. I didn't know that. But it gives me hope that one day compile-time evaluation of regexes as I envisioned above will be not only feasible but the preferred way. Let's postpone my proposal above to the time when the V interpreter will be mostly ready.

Thanks!

**Pull request merged**
