### PR TITLE
parser: fix mutability with chained fields

### LINKED ISSUE #1676: false immutable error?
**V version: 0.1.18** 
**OS: macOS Mojave** 

**What did you do?**
Iterate array of structs, using the struct value as an indexer to modify another array.

result[rec.parent].children << TNode{id: rec.id}        // tree.v:22 `rec` is immutable (can't <<)

complete code:
```
import json

struct TNode {
pub:
        id      int
        children []TNode
}

struct Record{
pub:
        id      int
        parent  int
}

fn build(records []Record) ?TNode{
        if records.len == 0 { return Node{}}

        mut result :=  [TNode{}; records.len]

        for i, rec in records{
                result[rec.id] = TNode{id: rec.id}
                result[rec.parent].children << TNode{id: rec.id}        // tree.v:22 `rec` is immutable (can't <<)
                // result[records[i].parent].children << TNode{id: rec.id}    // does work
                
        }
        return result[0]
}


fn main(){
        mut recs := []Record
        recs << Record{id: 0, parent:0}
        recs << Record{id: 1, parent: 0}
        recs << Record{id: 2, parent: 0}


        n := build(recs) or {
                return
        }
        print_tnode(n)

}

fn print_tnode(tnode TNode){
        println('id:$tnode.id #childs:$tnode.children.len') 
        for cn in tnode.children{
                print_tnode(cn)
        }
}
```
**What did you expect to see?**
No errors about the need of the array to be mutable.
 
**What did you see instead?**
tree.v:22 `rec` is immutable (can't <<)

### PR DESCRIPTION
**Pull request by kawa-yoiko**
Some unrelated changes are made for V to compile itself again.

In an assignment/append statement, it should be ensured that all chained fields (e.g. `a.b.c.d`) are mutable.

Fixes #1676 combined with #1790.

Here is a test, but I haven't figured out how to properly automate this.

```v
struct A { mut: v int }
struct B {      a A }
struct C { mut: b B }
struct D { mut: c C }

struct E { mut: v []int }
struct F {      e []E }

mut s := 'hello world'
s.len = 0   // Error (field len immutable)

fn (b mut B) bb() {
    b.a = A{}   // Error (field a immutable)
}

mut b := B{}
b.a.v = 1   // Error (field a immutable)
b.a = A{}   // Error (field a immutable)
b = B{A{2}} // Correct

mut c := C{}
c.b = B{}   // Correct
c.b.a = A{} // Error (field a immutable)
c.b.a.v = 1 // Error (field a immutable)

c2 := C{}
c2.b = B{}  // Error (c2 immutable)
mut d := D{}
d.c.b = B{} // Correct

mut f := F{}
f.e << E{}      // Error (field e immutable)
f.e[0].v << 1   // Error (field e immutable)

e := E{}
e.v << 1    // Error (e immutable)
```

### CODE REVIEW

**Comment by kawa-yoiko** [comment]
Currently vlib/vweb does not properly compile, will try to investigate when I get the chance > <

(Do not merge before it's fixed)

**Comment by kawa-yoiko** [comment]
Looks good now. Hope squash and merge will save me 😝

Btw can the aforementioned test be added to the automated testset?

**Comment by medvednikov** [comment]
All files that end with `_test.v` are tested automatically. You can add it  yourself to `compiler/tests/mut_test.v`

**Comment by kawa-yoiko** [comment]
Yes, but is there a way to ensure that the compiler emits errors on some code?

**Comment by medvednikov** [comment]
Thanks for the fix.

Why are you doing 


```
for _, f in p.fields {
  if !f.is_mut {
``

instead of just `if !field.is_mut`?

Am I missing something? :)

By the way, there's no need in `for _, f in p.fields {`, just use `for f in p.fields {`

**Comment by medvednikov** [comment]
> Yes, but is there a way to ensure that the compiler emits errors on some code?

I've wanted this for a while. Not yet, but the REPL tests are doing something similar, so it'd be trivial to add this.

**Comment by kawa-yoiko** [comment]
> `for f in p.fields` instead of just `if !field.is_mut`

For example, we do not want `a.b.c = 0` to happen if the field `b` is immutable, even if `c` is mutable. So I kept a list of all fields in the current variable (`p.fields`) and ensured that all of them are mutable ones.

Did I understand it correctly?

**Comment by medvednikov** [comment]
Right, good catch. Can you add that example (`a.b.c`) as a comment in `struct Parser{}`, next to the new `fields` field?

**Comment by medvednikov** [comment]
Also instead of allocating a new array  all the time, can't we use a single variable `p.all_fields_mutable`?

**Comment by kawa-yoiko** [comment]
> can't we use a single variable `p.all_fields_mutable`?

> Right, good catch.

Doing that now 😝

**Comment by medvednikov** [comment]
`all_dot_fields_mutable` is a better name I think

**Comment by kawa-yoiko** [comment]
https://github.com/vlang/v/blob/dae4c4b83fa69923727236ec5e86eae058ed5c7d/compiler/parser.v#L1799-L1805

Would you mind explaining the purpose of this? It is not very clear from the comments...

**Comment by kawa-yoiko** [comment]
So is it really redundant?

**Comment by medvednikov** [comment]
no, it's not redundant

a field can be mutable, but not public, that's what it checks

**Pull request merged**
