### PR TITLE
Feature: Add bytes2bf function

### PR DESCRIPTION
**Pull request by SilvanCodes**
This PR adds a function that creates a Bitfield from a byte array.
It seems necessary to me that they can be created from more than strings of '1' ans '0' or from scratch.

Documentation and test are in place.

```
some_bytes := [byte(0xFF), byte(0xF0)]
some_bitfield := bitfield.bytes2bf(some_bytes)
```

### CODE REVIEW

**Comment by medvednikov** [comment]
Can you rename it to `bitfield.from_bytes`?

**Comment by ciubotaru** [comment]
I think I know where this function comes from, and I am happy to see it ported.

The only concern is long-term support. At this stage the container size is fixed at 32 bits, which results in very fast bitfield operations on 32-bit architectures only. This code heavily relies on the 32-bit assumption, but I hope one day we will have smth like 'sizeof' and will make the container size architecture-dependent.

**Comment by spytheman** [comment]
@ciubotaru we already have sizeof(type) and generics ...

**Comment by SilvanCodes** [comment]
Thanks for the feedback! Actually I'm confused by my own test. I realized I'm reading the bits from the input backwards. (seems like I was somewhat sleepy) While this seems to match the bitfield, I don't see why the bits would be reversed when settings them.

**Comment by ciubotaru** [comment]
> I realized I'm reading the bits from the input backwards

... and writing them backwards, too.

**Pull request merged**
