### PR TITLE
freestanding: fix `-freestanding`

### PR DESCRIPTION
**Pull request by crthpl**
This PR brings back support for `-freestanding`

An issue:
`v fmt` does not seem to work for `vlib/v/gen/c/cheaders.v`, it turns lines like this:
```c
#if defined(_WIN32) || defined(__CYGWIN__)
```
into 
```c
#if defined(_WIN32)
		|| defined(__CYGWIN__)
```

### CODE REVIEW

**Comment by medvednikov** [comment]
@crthpl this has thousands of lines copy pasted from `builtin/`

V has a strict no copy paste policy.

**Comment by crthpl** [comment]
> @crthpl this has thousands of lines copy pasted from `builtin/`
> 
> V has a strict no copy paste policy.

I think I am going to refractor to make builtin use `$if freestanding` instead, but I need that the file that defines `calloc`, `malloc`, `strlen`, etc. only be included in bare. `builtin.freestanding.v`?

**Comment by medvednikov** [comment]
Right, so that's what I started doing.

First, I move old "bare" to linux_bare, since it's a libc free implementation of builtin on linux.

For real bare we need a command line flag with the location to user implementation of malloc etc for their platform.

You can't really define malloc here because it will be different on each platform.

**Comment by crthpl** [comment]
> Right, so that's what I started doing.
> 
> First, I moved old "bare" to linux_bare, since it's a libc free implementation of builtin on linux.
> 
> For real bare we need a command line flag with the location to user implementation of malloc etc for their platform.
> 
> You can't really define malloc here because it will be different on each platform.

The user will need to implement these functions:
```v
malloc(size int) &byte
calloc(n int, size int) &byte
realloc(ptr &byte, size int) &byte
memcpy(dest &byte, src &byte, n int) &byte
memset(s &byte, c int, n int) &byte
memmove(dest &byte, src &byte, n int) &byte
getchar() int
tolower(c int) int
toupper(c int) int
exit(code int)
```

but if the flag is not specified, it should default to `linux_bare`.

**Comment by medvednikov** [comment]
Thanks for the list.

tolower and toupper usage should be removed. 

Using linux_bare by default is fine I guess, by the way check out the functions already defined in `builtin/linux_bare`

**Comment by crthpl** [comment]
@medvednikov what should the flag be called?

**Comment by medvednikov** [comment]
-bare-builtin-dir

**Comment by JalonSolov** [comment]
An alternative might be to have `-freestanding` pay attention to `_bare` files and use the correct one based on the target OS.  So if you were compiling on Windows and there was a `windows_bare` file, it would use that.  It would also use it if you cross-compiled for Windows.

**Comment by crthpl** [comment]
> An alternative might be to have `-freestanding` pay attention to `_bare` files and use the correct one based on the target OS. So if you were compiling on Windows and there was a `windows_bare` file, it would use that. It would also use it if you cross-compiled for Windows.

That would not work since `-freestanding` is *without* libc, and the windows syscall API is not stable.

**Comment by JalonSolov** [comment]
So are you saying that `-freestanding` is supposed to mean "run on the bare metal, with no OS at all"?  In that case `linux_bare` doesn't make any sense, either.  There wouldn't be any syscalls if you didn't at least have the Linux kernel.

If you're allowing for the Linux kernel, then you have to allow for the Windows APIs, in which case a `windows_bare` should work fine.

**Comment by crthpl** [comment]
> So are you saying that `-freestanding` is supposed to mean "run on the bare metal, with no OS at all"? In that case `linux_bare` doesn't make any sense, either. There wouldn't be any syscalls if you didn't at least have the Linux kernel.
> 
> If you're allowing for the Linux kernel, then you have to allow for the Windows APIs, in which case a `windows_bare` should work fine.

`-freestanding` means running freestanding, without libc, and it *can* be used for kernels, etc., but Windows API is libc, which is exactly what `-freestanding` is not. `linux_bare` manually calls the system calls, which cannot be done on Windows, since the system calls for windows frequently change.

`linux_bare`, or the path specified by `-bare-builtin-dir`, must contain an implementation of `malloc`, `memcpy`, etc., without calling C library functions. for `v-os`, we will not use `linux_bare`, since we do not have the Linux system calls, but instead will have to manually make them.
[This](https://github.com/vlang/vos/blob/main/kernel/c/builtins.c`) is the current vos implementation of `-bare-builtin-dir`, which doesn't do anything for malloc, and other complex functions like that.

**Comment by medvednikov** [comment]
@JalonSolov -freestanding wouldn't make sense with any os but linux, since only linux has a stable syscall api, everything else uses libc as a system api.

That's why we only have `builtin/linux_bare`.

**Comment by dumblob** [comment]
Great job @crthpl !

**Pull request merged**
