### PR TITLE
v: allow multi return as fn argument

### LINKED ISSUE #21956: Can't pass multiple values returned by a function to another function
### Describe the bug

This works in Go:
```go
package main

func my_func(a1 int, a2 int) {}

func my_func2() (int, int) { return 0, 0 }

func main() {
	my_func(my_func2())
}
```

Doesn't work in V:

```v
fn my_func(a1 int, a2 int)  {}

fn my_func2() (int, int) { return 0,0}

fn main() {
	my_func(my_func2())
}

```

```bash
/tmp $ v run a.v
a.v:6:2: error: expected 2 arguments, but got 1
    4 |
    5 | fn main() {
    6 |     my_func(my_func2())
      |     ~~~~~~~~~~~~~~~~~~~
    7 | }
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

### PR DESCRIPTION
**Pull request by felipensp**
Fix #21956

```v 
fn my_func(a1 int, a2 int)  {}

fn my_func2() (int, int)  { return 0,0 }

fn main() {
	my_func(my_func2())
}
```

### CODE REVIEW

**Comment by spytheman** [comment]
In my opinion, that makes the code that uses that new feature, harder and more confusing.

`my_func3(my_func2(), 'foo')` by the look of it, until now, meant that the `my_func3` has 2 arguments, and the first one is whatever the return value of `my_func2()` is (a single value).

Now, instead, it means that my_func3 accepts an arbitrary amount of arguments, the first of which are formed by the returned multiple values/tuple of `my_func2()`.

Given that we do not support tuples as first class values, it makes it confusing and inconsistent.

For example, the following code, that looks equivalent, will not work:
```v
val := my_func2()
my_func3( val, 'foo' )
```

**Comment by medvednikov** [comment]
@spytheman you're right, and it shouldn't work like that. Only what was posted in the bug report.

In Go we get

```
./a.go:12:11: multiple-value my_func2() (value of type (int, float64)) in single-value context
./a.go:12:23: not enough arguments in call to my_func3
	have ((int, float64), string)
	want (int, int, string)
./a.go:13:18: multiple-value my_func2() (value of type (int, float64)) in single-value context
./a.go:13:18: not enough arguments in call to my_func4
	have (string, (int, float64))
	want (string, int, int)
```

**Comment by felipensp** [comment]
Adjusted to just works on single-argument context.

**Comment by spytheman** [comment]
If the goal for this feature, is to emulate Go's rule, it may need an extension for the case where more returned values are passed, but the outer function (that accepts them as arguments), have its last argument be a variadic one:

> As a special case, if the return values of a function or method g are equal in number and individually assignable to the parameters of another function or method f, then the call f(g(parameters_of_g)) will invoke f after binding the return values of g to the parameters of f in order. The call of f must contain no parameters other than the call of g, and g must have at least one return value. If f has a final ... parameter, it is assigned the return values of g that remain after assignment of regular parameters.

**Comment by spytheman** [comment]
In my personal opinion, the whole thing is not very useful, and will encourage people to use function that return multiple values, more than they should.

In Go, that rule/special case, may have been more useful, because of their pattern of returning errors as a second element in the return tuple, so for them it could be a convenient way to write wrappers to handle the errors in a common way, like logging them for example.

In V, we do not have that, but instead use `!Type`, and require handling with `f() or { ... }` . I think that this special case rule, will be pretty much used only for translated Go code.

**Comment by bakul** [comment]
I agree 100% with @spytheman and consider this a misfeature. Go's "feature" was forced on it due to it not having sum types. Something like go2v can use an idiom that doesn't require this feature.

**Comment by eptx** [comment]
This also closed the bug I had opened: https://github.com/vlang/v/issues/16502

**Pull request merged**
