### PR TITLE
docs(v doc): added available output formats

### PR DESCRIPTION
**Pull request by Zerotask**
Added available output formats as defined in the source code. I also noticed, that the help flag is `--help` and not `-help`.

### CODE REVIEW

**Comment by medvednikov** [comment]
it's help, -help, --help

we support all of them to make finding help easier

but the convention is to use -arg everywhere

**Comment by Zerotask** [comment]
I thought `--help` instead of `-help` since in the Linux world words are mostly with `--` and only single chars are with `-`. I will update it then.

Regarding `-h` I found this line https://github.com/vlang/v/blob/master/cmd/tools/vdoc/vdoc.v#L488 this should be `-help` instead of `-h` then.

**Comment by Zerotask** [comment]
I thought it's not -h?

**Comment by spytheman** [comment]
> we support all of them to make finding help easier

**Comment by Zerotask** [comment]
> it's help, -help, --help

**Pull request merged**
