### PR TITLE
fix: v new <name> web

### PR DESCRIPTION
**Pull request by enghitalo**
// Note: here are the currently supported invokations so far:
// 1) `v init` -> create a new project in the current folder
// 2) `v new abc` -> create a new project in the new folder `abc`, by default a "hello world" project.
// 3) `v new abcd web` -> create a new project in the new folder `abcd`, using the vweb template.
// 4) `v new abcde hello_world` -> create a new project in the new folder `abcde`, using the hello_world template.

image
image

### CODE REVIEW

**Comment by enghitalo** [comment]
TODO -> test `v run .` in web project

**Comment by enghitalo** [comment]
CI windows error:
```bash
starting cmd\tools\vcreate_test.v ...
 FAIL  [37/63]  1059.862 ms cmd/tools/vcreate_test.v
failed    cmd: "D:\a\v\v\v.exe" init

failed   code: 1

Change the description of your project in `v.mod`

V panic: failed to open file "src/main.v"
v hash: 30fb760

C:/Users/RUNNER~1/AppData/Local/Temp/v_0/tsession_19a8_8[86](https://github.com/vlang/v/actions/runs/3864708607/jobs/6587703840#step:12:87)278300/vcreate.11616346328105593818.tmp.c:4524: at _v_panic: Backtrace
C:/Users/RUNNER~1/AppData/Local/Temp/v_0/tsession_19a8_[88](https://github.com/vlang/v/actions/runs/3864708607/jobs/6587703840#step:12:89)6278300/vcreate.11616346328105593818.tmp.c:7722: by main__Create_create_files_and_directories
C:/Users/RUNNER~1/AppData/Local/Temp/v_0/tsession_19a8_886278300/vcreate.11616346328105593818.tmp.c:7596: by main__init_project
C:/Users/RUNNER~1/AppData/Local/Temp/v_0/tsession_19a8_886278300/vcreate.11616346328105593818.tmp.c:7523: by main__main
C:/Users/RUNNER~1/AppData/Local/Temp/v_0/tsession_19a8_886278300/vcreate.11616346328105593818.tmp.c:7[89](https://github.com/vlang/v/actions/runs/3864708607/jobs/6587703840#step:12:90)9: by wmain
004540f0 : by ???
00454253 : by ???
7ffa3e7b7af4 : by ???
```

**Comment by enghitalo** [comment]
Can someone try this on windows. In the branchs `master` and `fix/vcreate-web`, please?

**Comment by medvednikov** [comment]
Thanks!

**Pull request merged**
