### PR TITLE
add more tests on interfaces

### PR DESCRIPTION
**Pull request by smartiniOnGitHub**
Hi,
here I'm adding some additional test on interfaces, and add some comment to clarify to newbies (like me) what happens behind compilation.
String delimiters are different to test more combinations.
Also I add even some (commented) statements on two features that would be useful (is possible to have).
Hope it's good. Thanks for now. Bye

### CODE REVIEW

**Comment by smartiniOnGitHub** [comment]
Sorry I have another test (shown here):
```
// TODO: move in a negative test, but check how to do ...
fn test_interface_without_implementation() {
	println("Test on Speaker2 that doesn't have an implementation here ...")
	s2 := Speaker2{}
	assert false // should never be executed
	// println('Speaker2 instance is: ${s2}') // not possible
	// assert s2 is Speaker2 // not possible
}
```
to ensure compiler will raise error, but no idea on if/how to implement it ... suggestions ?
Thanks.

**Comment by medvednikov** [comment]
@smartiniOnGitHub to test errors, check out an `inout` test, like `tests/inout/bad_st_as.vv` and `bad_st_as.out`

**Comment by spytheman** [comment]
@smartiniOnGitHub 

Your negative test can be done by creating 2 files:
`vlib/v/checker/tests/interface_simple.vv` 
and
`vlib/v/checker/tests/interface_simple.out`

`vlib/v/checker/tests/interface_simple.vv` contains:
```v
interface Speaker {
    name() string
    speak()
}

s := Speaker{}
eprintln('Speaker instance is: ${s}')

a := []Speaker{}
eprintln('Total speakers are: ${a.len}')
```

`vlib/v/checker/tests/interface_simple.out`contains:

```
x.v:7:2: warning: type `Speaker` is private
    5 |
    6 | s := Speaker{}
    7 | eprintln('Speaker instance is: ${s}')
      |  ~~~~~~~~~
    8 |
    9 | a := []Speaker{}
Speaker instance is: 0
Total speakers are: 0
```

i.e. currently v does not prevent compilation and execution of code creating immutable interface variables. @medvednikov should produce a checker error in that instance?

**Comment by spytheman** [comment]
also it is an error just in -prod and when run by `./v vlib/v/checker/checker_test.v`:
```
0[08:34:31]delian@nemesis: /v/nv $ ./v -prod run x.v
x.v:7:2: error: type `Speaker` is private
    5 |
    6 | s := Speaker{}
    7 | eprintln('Speaker instance is: ${s}')
      |  ~~~~~~~~~
    8 |
    9 | a := []Speaker{}
1[08:34:41]delian@nemesis: /v/nv $ ./v run x.v
x.v:7:2: warning: type `Speaker` is private
    5 |
    6 | s := Speaker{}
    7 | eprintln('Speaker instance is: ${s}')
      |  ~~~~~~~~~
    8 |
    9 | a := []Speaker{}
Speaker instance is: 0
Total speakers are: 0
0[08:34:46]delian@nemesis: /v/nv $
```

**Comment by medvednikov** [comment]
> should it produce a checker error in that instance?

yes

**Comment by smartiniOnGitHub** [comment]
@medvednikov sorry I just see that my rebase of the branch (for the PR) has been pushed into main repo ... excuse me, really (weird that I have such grants for me).
I'll raise another PR for those changes, ok ?

**Comment by medvednikov** [comment]
yes, thanks

**Pull request merged**
