### PR TITLE
add string is_digit method

### PR DESCRIPTION
**Pull request by makao007**

### CODE REVIEW

**Comment by medvednikov** [comment]
Can you rename please? (s string) is_letter() doesn't make sense. Letters consist of 1 character.

is_digit should be is_number

I'm not sure having an stdlib method `string.is_name` is necessary, because each application has its unique definition of what a name is.

**Comment by spy16** [comment]
May be `is_letter` should be `is_alpha` ?

**Comment by makao007** [comment]
> Can you rename please? (s string) is_letter() doesn't make sense. Letters consist of 1 character.
> 
> is_digit should be is_number
> 
> I'm not sure having an stdlib method `string.is_name` is necessary, because each application has its unique definition of what a name is.



> May be `is_letter` should be `is_alpha` ?

Yes, I rename it to "is_alpha"

**Comment by makao007** [comment]
add one more function "is_alnum", which check only contains alpha and digits
"is_digit"  "is_alpha"  "is_alnum"  these are reference the python string functions.

**Comment by makao007** [comment]
add "pub fn (s string) contain(c byte) bool {"

**Comment by ntrel** [comment]
The 3 is_ functions should work on a byte, not a string. Users can write something like functional `str.all(is_alpha)` instead of adding string wrappers to the standard library.

contain should be contains, and for efficiency it should call C memchr. It should probably be in a separate pull as it's distinct and for reviewer visibility, and this pull title doesn't mention it.

**Comment by AtjonTV** [comment]
Why don't you just return the output of `is_alpha` and `is_digit` in `is_alnum`?

```go
pub fn (s string) is_alnum() bool {
    return s.is_digit() && s.is_alpha()
}
```

Wouldn't this have the same results AND prevent redundant code?

**Comment by medvednikov** [comment]
I agree with @ntrel  here.

**Pull request closed without merging**
