### PR TITLE
Updated to use string builder

### PR DESCRIPTION
**Pull request by orneo1212**
Use string builder to increase speed of c gen.

Old pull request #6452

### CODE REVIEW

**Comment by orneo1212** [comment]
Will be #5912 and #2216

**Comment by spytheman** [comment]
The slowdown is around 4% this time.
(measured with `hyperfine 'cd /v/vmaster; ./v -o v2.c cmd/v' 'cd /v/nv; ./v -o v2.c cmd/v'`)
smart_quote in cgen
With a v compiled with -prod, the slowdown is also ~3-4%.
smart_quote in cgen with v compiled with -prod

**Comment by orneo1212** [comment]
> 
> 
> The slowdown is around 4% this time.
> (measured with `hyperfine 'cd /v/vmaster; ./v -o v2.c cmd/v' 'cd /v/nv; ./v -o v2.c cmd/v'`)
> smart_quote in cgen
> With a v compiled with -prod, the slowdown is also ~3-4%.
> smart_quote in cgen with v compiled with -prod

Much better than concatenating strings

**Comment by orneo1212** [comment]
Is it ready to merge?

**Comment by medvednikov** [comment]
@orneo1212 I need to test the perf and play with it. This is a very critical part of the compiler.

**Comment by orneo1212** [comment]
Thanks fof info. Take your time

**Comment by orneo1212** [comment]
> @orneo1212 I need to test the perf and play with it. This is a very critical part of the compiler.

Any news?

**Comment by spytheman** [comment]
I've just rebased this over the current master.

**Comment by spytheman** [comment]
I think we can merge this as it is, and optimize it later.

**Pull request merged**
