### PR TITLE
Simplify os.read_lines()

### PR DESCRIPTION
**Pull request by radare**
The current readlines implementation is buggy and duplicates some code, 

```
import os

fn main() {
        mut len := 0
        for i := 0; i < 200 ; i++  {
                lines := os.read_lines('/etc/services') or {
                        panic(err)
                }
                len = lines.len
        }
        eprintln('$len')
}
```

There's a small performance degradation:

* Before: 1.6s
* Using .split('\n') = 3.2s
* Using .split_into_lines() = 1.8s

So my feeling is:
* the simpler the better
* we should optimize split('\n') to be as fast as split_into_lines

### CODE REVIEW

**Comment by spytheman** [comment]
Just out of curiosity, on what hardware/OS reading /etc/services 200 times takes over a second?
On my system (linux + ssd), it takes ~ 36ms, probably because it gets cached after the first read.

**Comment by radare** [comment]
macOS

**Comment by radare** [comment]
Its not a prod build and heap allocations are expensive in V. Its not about reading the file. Its about splitting it into several chunks into a linked list

**Comment by medvednikov** [comment]
This results in x2 allocations and worse performance.

What bugs did you face?

**Comment by spytheman** [comment]
wow, macOS's /etc/services is huge:
```shell
0[10:41:42] /v/newv MACOSX $ wc /etc/services
   13921   68850  677972 /etc/services
0[10:41:43] /v/newv MACOSX $
0[10:42:22] /v/newv MACOSX $
0[10:42:22] /v/newv MACOSX $ wc /etc/services
   13921   68850  677972 /etc/services
0[10:42:24] /v/newv MACOSX $ time /v/misc/200_reads_of_etc_services
13921

real    0m0.632s
user    0m0.496s
sys     0m0.132s
0[10:42:28] /v/newv MACOSX $
```

**Comment by radare** [comment]
but its duplicated logic and the optimization must be done in the split method instead. and the performance lost compared to the current implementation is quite low (1.8s vs 1.6s) probably no difference on production builds

**Comment by medvednikov** [comment]
No, with current implementation you allocate lines as you go.

With your implementation you allocate the entire text, and then allocate the same amount of memory for the lines.

For 1 GB logs this can be a problem.

Just measure the memory usage of both implementations and you'll see.

**Comment by radare** [comment]
The old implementation only works if you have lines shorter than 1024 chars. I understand the memory usage implications but i think this duplicated logic in the api makes it a bit ugly to me

**Comment by radare** [comment]
any decission here?

**Comment by medvednikov** [comment]
Ok let's use it for now, in can be optimized later.

Better, than having a buggy implementation.

**Pull request merged**
