### PR TITLE
map: use hashmap instead of b-tree

### PR DESCRIPTION
**Pull request by ka-weihe**
Observe the figures below. The hashmap is a lot faster in all cases, while only using a bit more memory on average. The memory usage can and will be improved. The hashmap acts as a much better default for `map` as opposed to the current b-tree implementation. The b-tree will be added back as `sorted_map`, `ordered_map` or something else. I'm thinking docs could say something like:

>Use a `map` when:
>* You want to associate arbitrary keys with an arbitrary value.
>* You want the fastest map, with no extra functionality.
>* You want a cache.
>
>Use a `sorted_map` when:
>* You want a map sorted by its keys (not insertion order).
>* You want to view a portion of this map whose keys lie in some range
>* You're interested in what the smallest or largest key-value pair is.
>* You want to find predecessor or successor of a key
>* You have few incredibly long keys 

This is a performance comparison between the b-tree (current `map`) and the hashmap. Lower is better. The difference is naturally bigger for larger quantities of key-value pairs.
alt text

alt text

### CODE REVIEW

**Comment by spytheman** [comment]
How are these graphs generated?

**Comment by spytheman** [comment]
Why are tests deleted?

Also, if the current b-tree map  implementation is indeed inferior for some cases, would not it be better to just rename it, and keep its tests, or they would not be able to run with the replacement?

**Comment by ka-weihe** [comment]
Graph data is generated from my benchmarks [here](https://github.com/ka-weihe/hashmap-v/blob/master/hashmap/hashmap.v). hashmap_test.v are deleted because they are already in `map_test.v`. B-tree map will be renamed and once I add It back, all the tests from `map.v` can be copied.

**Comment by joe-conigliaro** [comment]
In either case you should still keep both map implementations, even if hashmap were to become default

**Comment by ka-weihe** [comment]
Thank you @joe-conigliaro. I have moved the b-tree to a new file `sorted_map.v`. The name is just temporary until we find right name for it. I have not added it to the compiler.

**Comment by gslicer** [comment]
Not sure if feasible for this implementation, but there could be just a method like e.g.: `.sort(asc)` which would then change the internal structure of a map from hash to b-tree?

**Comment by ka-weihe** [comment]
@gslicer that won't be possible. The hashmap and b-tree will have many different methods.

**Pull request merged**
