### PR TITLE
new interface to the regex module (transition phase with the "_opt" suffix)

### PR DESCRIPTION
**Pull request by mobarski**
Regex module with api that uses option result type.

```v
// POSITIVE EXAMPLE
mut re := regex2.regex("a") or { panic(err) }
println(re.find("xx aaa xx")) // (3, 4)

// NEGATIVE EXAMPLE
query := r"ciao da ab[ab-]"  // there is an error, a range not closed!!
mut re := regex2.new_regex()

re.compile(query) or { println(err) }
// Outputs:
// query: ciao da ab[ab-]
// err  : ----------^
// ERROR: err_syntax_error
```

### CODE REVIEW

**Comment by Delta456** [comment]
@mobarski Why can't we replace the old one with the new one?

**Comment by penguindark** [comment]
There are external modules that are using the old interface.
For some time can be better keep both.

**Comment by spytheman** [comment]
I do not agree with naming this regex2.

The only functional code difference is regex vs regex2
The rest is simplifying changes to the README.

If we do not want to break compatibility, we can do the following:
1) name the new option returning regex and compile wrappers something different, say `regex_opt` and `compile_opt`
2) put a [deprecated] tag to the existing compile and regex functions
3) after a while (say 2-3 months) rename compile_opt to compile and regex_opt to regex, and add new [deprecated] `compile_opt` and `regex_opt` wrappers, that just return the new official functions.
4) after another 2-3 months, remove compile_opt and regex_opt completely.

**Comment by spytheman** [comment]
@mobarski you can even put the new functions in a new file regex_opt.v inside vlib/regex/, without changing much the existing ones (except for bumping the version, and adding a `[deprecated]` tag to the functions that you wrapped).

V compiles all .v files in the same module as part of a whole, so it would be functionally equivalent to adding them in the same file.

**Comment by spytheman** [comment]
Copying the whole module under a new name for a few small changes, is both bad for git history, and confusing for users.

**Comment by mobarski** [comment]
Excellent remarks. I'll do as @spytheman suggests.

**Comment by medvednikov** [comment]
Also I think `regex.new_regex()` can be renamed to `regex.new()`

**Comment by mobarski** [comment]
I made changes mentioned by @spytheman and @medvednikov.

```v
// POSITIVE EXAMPLE
mut re := regex.regex_opt("a") or { panic(err) }
println(re.find("xx aaa xx")) // (3, 4)

// NEGATIVE EXAMPLE
query := r"ciao da ab[ab-]"  // there is an error, a range not closed!!
mut re := regex.new()

re.compile_opt(query) or { println(err) }
// Outputs:
// query: ciao da ab[ab-]
// err  : ----------^
// ERROR: err_syntax_error
```

Unit test for the new interface: regex_opt_test.v

**Pull request merged**
