### PR TITLE
v: remove the automatic passing of structs with more than 8 fields by reference (related #17159)

### PR DESCRIPTION
**Pull request by yuyi98**
This PR remove the automatic passing of structs with more than 8 fields by reference (related #17159).

### CODE REVIEW

**Comment by spytheman** [comment]
THANK YOU!!!
🥳 🥳 🥳

**Comment by spytheman** [comment]
What about the remaining bits in `vlib/v/parser/fn.v:774`, and the `is_auto_rec` field in ast.Param ?

Will they be removed in a follow up PR?

**Review by spytheman — APPROVED** [review]
Excellent work!

That simplification was long overdue.

I could not finish <https://github.com/vlang/v/pull/17159> after trying several times :-| .

**Comment by felipensp** [comment]
Consistency wins. 👍🏻

**Comment by larpon** [comment]
Fantastic! Thanks again @yuyi98 !

**Pull request merged**
