### PR TITLE
Resolve optional enum type

### PR DESCRIPTION
**Pull request by radare**
<!--

Please title your PR as follows: `time: fix foo bar`. 
Always start with the thing you are fixing, then describe the fix.
Don't use past tense (e.g. "fixed foo bar").

Explain what your PR does and why.

If you are adding a new function, please document it and add tests:

```
// foo does foo and bar
fn foo() {

// file_test.v
fn test_foo() {
    assert foo() == ...
    ...
}
```

If you are fixing a bug, please add a test that covers it.

Before submitting a PR, please:
  A) run the tests with `v test-compiler` .
  B) make sure, that V can still compile itself:
```shell
./v -o v v.v
./v -o v v.v
```

I try to process PRs as soon as possible. They should be handled within 24 hours.

Applying labels to PRs is not needed.

Thanks a lot for your contribution!

->

### CODE REVIEW

**Comment by radare** [comment]
Fixes https://github.com/vlang/v/issues/3603

**Comment by joe-conigliaro** [comment]
thanks @radare , I'm just wondering if changing expected_type there could have any unexpected consequences. If something else uses it after that, expecting the type as it was (optional or not).
It might be better to just strip the option off for find_type.
There may not be any cases like this, though.

**Comment by radare** [comment]
i just pushed another commit without modying that field and i can confirm it works as expected, so it fixes the issue. will be good to add it to the testsuite btw

**Comment by medvednikov** [comment]
Can you add a small test to enum_test.v please?

**Comment by spytheman** [comment]
@radare , @joe-conigliaro : with 3b81a0d , the example from the issue no longer compiles.

It produces a C error, because of the following C code:
```c
Option_Foo main__foo(bool i) {
   if (i) {
      Option_Foo tmp1 = OPTION_CAST(Option_Foo)(main__Option_Foo_one);
      return opt_ok(&tmp1, sizeof(Foo));
   };
   return v_error(tos3("failed"));
}
```

Before the last commit, the generated C code was:
```c
Option_Foo main__foo(bool i) {
   if (i) {
      Foo tmp1 = OPTION_CAST(Foo)(main__Foo_one);
      return opt_ok(&tmp1, sizeof(Foo));
   };
   return v_error(tos3("failed"));
}
```
... which worked fine.

**Comment by radare** [comment]
oh seems like something is wrong in this approch :<

**Comment by radare** [comment]
oh seems like something is wrong , i reverted the "donot mess" commit and fixed the test

**Comment by medvednikov** [comment]
Thanks

**Comment by joe-conigliaro** [comment]
@spytheman @radare , my point was about other code which could now or in the future rely on, p.expected_type after its modified here (this could never happen) I'm just saying the fact that it was an optional is now lost for future users of p.expected_type

**Pull request merged**
