### PR TITLE
sokol: update to floooh/sokol@c602d83

### PR DESCRIPTION
**Pull request by Larpon**
Update all sokol + examples to match sokol @ rev c602d83 (latest as of this writing) (https://github.com/floooh/sokol/commit/c602d83)

I find this update important as many things have changed in preparation for the automatic language binding project floooh is working on.

I've been through this more than once and cross-referenced with our implementation/wrappers.
https://floooh.github.io/2021/02/07/sokol-api-overhaul.html
We're on-par with 01-Apr-2021 [in the CHANGELOG.md](https://github.com/floooh/sokol/blob/master/CHANGELOG.md)

I'm unsure if [this contribution](https://github.com/vlang/v/pull/8817/files) by @rcqls is fixed - otherwise we might have to patch it again.

I can see that there's been some contribution to drag'n'drop support - which is probably worth looking into :)

### CODE REVIEW

**Comment by penguindark** [comment]
Great job man! :+1:

**Review by penguindark — APPROVED** [review]
Good for me :)

**Comment by Larpon** [comment]
@medvednikov you'll have to re-apply your patch from d991712b3caea3f5a82165411a1ef231a4d759db

**Comment by medvednikov** [comment]
Thank you very much for this immense work!

**Pull request merged**
