### PR TITLE
json: maps, memory leak, and error forwarding

### LINKED ISSUE #3367: JSON not encoding maps
**V version:** V 0.1.24 3425934
**OS:** Linux 

**What did you do?**
Run the following code:
```v
import json

struct Nested1 {
	item1	string
	item2	string
}

struct Nested2 {
	item1	int
	item2	bool
}

struct Top {
mut:
	mp1	map[string]int
	nes1	map[string]Nested1
	nes2	Nested2
}

fn main() {
	mut tp := Top{}
	tp.mp1['int example'] = 2
	tp.nes1['struct example'] = Nested1{
		item1: 'string1',
		item2: 'string2',
	}

	tp.nes2 = Nested2{
		item1: 39,
		item2: true,
	}

	js1 := json.encode(tp.nes1['struct example'])

	println(js1)

	js2 := json.encode(tp.nes2)

	println(js2)

	js3 := json.encode(tp)

	println(js3)
}
```
**What did you expect to see?**
( I formatted the JSON for readability)
```json
{
    "item1": "string1",
    "item2": "string2"
}
{
    "item1": 39,
    "item2": true
}
{
    "mp1": {
        "int example": 2
    },
    "nes1": {
        "example": {
            "item1": "string1",
            "item2": "string2"
        }
    },
    "nes2": {
        "item1": 39,
        "item2": true
    }
}
``` 

**What did you see instead?**
(I formatted the JSON for readability)
```json
{
    "item1": "string1",
    "item2": "string2"
}
{
    "item1": 39,
    "item2": true
}
{
    "mp1": {},
    "nes1": {},
    "nes2": {
        "item1": 39,
        "item2": true
    }
}
```

or perhaps an error if maps are not meant to be encoded.

### PR DESCRIPTION
**Pull request by viniciuslrangel**
Fixes #3367 

Also fixes a leaking  json object when decoding array

Testing code:
```V
import json

struct Nested1 {
	item1	string
	item2	string
}

struct Nested2 {
	item1	int
	item2	bool
}

struct Top {
mut:
	mp1	map[string]int
	nes1	map[string]Nested1
	nes2	Nested2
}

fn main() {
	mut tp := Top{}
	tp.mp1['int example'] = 2
	tp.nes1['struct example'] = Nested1{
		item1: 'string1',
		item2: 'string2',
	}
	tp.nes2 = Nested2{
		item1: 39,
		item2: true,
	}

	str := json.encode(tp)
	tp2 := json.decode(Top, str) or { panic(err) }
	assert tp.str() == tp2.str()
}
```

### CODE REVIEW

**Comment by helto4real** [comment]
Awesome, I just did a leak fix for encode and decode and was getting ready to do a PR haha. Good job!

**Comment by viniciuslrangel** [comment]
> Awesome, I just did a leak fix for encode and decode and was getting ready to do a PR haha. Good job! ps is this going to fix the missing `cJSON_delete(root)` ?

Nop, sorry

**Comment by medvednikov** [comment]
Great job, thanks! Can you add a simple test to json_test.v?

**Comment by viniciuslrangel** [comment]
> Great job, thanks! Can you add a simple test to json_test.v?

Sure

**Comment by viniciuslrangel** [comment]
> Awesome, I just did a leak fix for encode and decode and was getting ready to do a PR haha. Good job! ps is this going to fix the missing `cJSON_delete(root)` ?

Actually, I fixed it

**Comment by medvednikov** [comment]
You're a hero! Thanks!

**Pull request merged**
