### PR TITLE
Compound assignment operators

### PR DESCRIPTION
**Pull request by Henrixounez**
Solves : #549 

I only change the CAO string into a basic when the scanner finds a ***_ASSIGN token :

```
// Initial
a += b

// New string
a = a + b
```

A better fix would be to change lot of things inside parser

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks, but it doesn't compile (`v .` fails). Please test your changes by running (`./v -o v .`) twice.

**Comment by medvednikov** [comment]
CI still doesn't work with PRs unfortunately.

**Comment by medvednikov** [comment]
Hm, CI did catch it: https://dev.azure.com/alexander0785/vlang/_build/results?buildId=31

Just didn't display it here.

**Comment by Henrixounez** [comment]
Sorry i messed it up when i was trying to tidy up the indentation...

**Pull request merged**
