### PR TITLE
vfmt: fix fn return unnecessary parentheses (fix #11423)

### LINKED ISSUE #11423: vfmt: do not remove unnecessary parentheses
this formatted:
```v
fn is_ascii_upper_alpha(char int) bool {
	return (char >= 65 && char <= 90)
}
```
should return:
```v
fn is_ascii_upper_alpha(char int) bool {
	return char >= 65 && char <= 90
}
```
(**I think**)
And anyway if it's one or the other the best, it's against V's philosophy, one way of writing code.

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix fn return unnecessary parentheses (fix #11423).

- Fix fn return unnecessary parentheses.
- Add test.

### CODE REVIEW

**Comment by medvednikov** [comment]
@yuyi98 the new policy is not use vlang/v branches for PRs to improve CI speed.

Your fork branches should be used instead.

**Comment by yuyi98** [comment]
Maybe there's still a problem here, it cause Vinix build error.

**Comment by JalonSolov** [comment]
The vinix build failure doesn't look like it's related to your changes.

@mintsuki ^^

**Comment by medvednikov** [comment]
@mintsuki we need Vinix CI back.

**Pull request merged**
