### PR TITLE
vup: fix 'v up' on windows

### LINKED ISSUE #3148: Failed to compile for update Vlang version "v up"
**V version: 0.1.23 519f299** 
**OS** 
Windows

**What did you do?**
I just do "v up" in my cmd with admin mode after install v language

**What did you expect to see?**
I expect to see the "last version is allready install" 
 
**What did you see instead?**
The error message returned is:

LINK : fatal error LNK1104: impossible d'ouvrir le fichier 'C:\languages\v\v.exe'
V failed to build itself
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

### PR DESCRIPTION
**Pull request by kdmult**
This PR fixes #3148, which is a regression caused by changes in tools/vup.v:
```diff
-		os.mv('$vroot/v.exe', v_backup_file)
+		os.mv_by_cp('$vroot/v.exe', v_backup_file)
```

`os.mv_by_cp` calls `_wremove` for removing `v.exe` and fails because it requires that all handles to v.exe must be closed before it can be deleted but there is an open one since v.exe runs the tool vup.exe as a subprocess. 

`os.mv` on the other hand calls `_wrename` which has no such a requirement and allows to rename a file with open handle.

### CODE REVIEW

**Comment by spytheman** [comment]
It would be better to call os.cp in this situation. renaming does not work across partitions/filesystems.

**Comment by kdmult** [comment]
I have renamed a file from disk c: to disk d:, which is a different physical disk, successfully.

**Comment by kdmult** [comment]
If you use cp, then you should use rm. But rm cannot delete v.exe on Windows because it is a parent process and its descriptor is open, so rm fails to delete it.

**Comment by kdmult** [comment]
Here is an excerpt from the documentation for _wrename:
"[You can use rename to move a file from one directory or device to another by giving a different path in the newname argument](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rename-wrename?view=vs-2019)".

**Pull request merged**
