### PR TITLE
array.reverse()

### PR DESCRIPTION
**Pull request by joe-conigliaro**
This PR adds array.reverse() which returns a new array in reverse order

### CODE REVIEW

**Comment by medvednikov** [comment]
Calling `memcpy` a.len times is inefficient. It's possible to do this with pointer arithmetics in a single loop.

But ok for now I guess.

Can you add a couple of simple tests?

**Comment by joe-conigliaro** [comment]
@medvednikov I had done it with pointers earlier but then changed it because if you modify the original array it will modify the new one? I can change it back, what do you think?

**Comment by joe-conigliaro** [comment]
@medvednikov I will update it

**Comment by joe-conigliaro** [comment]
@medvednikov do you think it should return a new array or modify the existing?

**Comment by medvednikov** [comment]
definitely return a new array.

**Comment by joe-conigliaro** [comment]
@medvednikov cool thats what I thought just wanted to make sure

**Comment by joe-conigliaro** [comment]
@medvednikov it doesn't seem to work like in C. How can i increment a pointer? Can you give a example on how you would so this?

**Pull request closed without merging**
