### PR TITLE
checker: disallow incomplete thread type struct fields 

### PR DESCRIPTION
**Pull request by Delta456**
Fixes https://github.com/vlang/v/issues/14043

### CODE REVIEW

**Comment by spytheman** [comment]
hm, why disallow them?

**Comment by spytheman** [comment]
The original code in https://github.com/vlang/v/issues/14043 which is:
```v
struct Str {
	t thread
	a [0xF]bool
}
```
currently compiles cleanly, while before the parser could not handle it.

Imho the issue can be just closed as completed, without introducing a special checker error.

**Comment by spytheman** [comment]
Keep in mind, that one may want to represent threads, in a generic way, without caring about the type of the work they do, and just call `.wait()` on them, to complete.

**Comment by Delta456** [comment]
> Keep in mind, that one may want to represent threads, in a generic way, without caring about the type of the work they do, and just call `.wait()` on them, to complete.

I noticed that a while ago, so I forgot to close the PR.

**Pull request closed without merging**
