### PR TITLE
repl: Reduced the logo

### PR DESCRIPTION
**Pull request by ZaViBiS**
Reduced the logo

I don't know why the logo is needed, but the previous one was taking up too much space. 
If you don't like this one, you can choose another one [here](https://patorjk.com/software/taag/#p=testall&f=Graffiti&t=V), there are many options.
Снимок экрана от 2022-02-13 00-44-22

### CODE REVIEW

**Comment by ZaViBiS** [comment]
I made this PR not because I don't like this particular logo, but because I don't like the size of it.
@vincenzopalazzo

**Comment by vincenzopalazzo** [comment]
>I made this PR not because I don't like this particular logo, but because I don't like the size of it.

The size is relative, unfortunately, there are people with different disability that after your change will said "this logo is too small"

**Comment by ZaViBiS** [comment]
It's not much smaller, but it looks neater to me.

image

**Comment by ZaViBiS** [comment]
Well, it's up to you, but I'm going to bed.

**Comment by vincenzopalazzo** [comment]
The logo needs to maintain the same width.

From the style point of view, the second that you propose looks a little bit messy, and I preferer to remove it

**Comment by spytheman** [comment]
Julia has a nice approach:
image

Their logo is to the left of the rest of the text, thus it uses the vertical space more efficiently, than a separate logo, all by itself as the current V one does.

**Comment by spytheman** [comment]
What about something like this ?:
image

**Comment by vincenzopalazzo** [comment]
I like it @spytheman  :)

**Comment by spytheman** [comment]
Here it is in actual code (I will push the change soon to this PR):
image

**Pull request merged**
