### PR TITLE
vvet: fix false positive, add test

### LINKED ISSUE #14402: v vet confused about specific docstring
**V version:** V 0.2.4 b10cf3e0f.b10cf3e
**OS:** linux, "EndeavourOS Linux"

**What did you do?**

I wrote some code with the following docstring & ran it through `v vet`.

```v
// test.v

// read_response is a convenience function combining read_response_head &
// read_response_body. It can be used when you know for certain the response
// won't be chunked.
pub fn read_response() ?(string, string) {}
```

**What did you expect to see?**

I expected there to be no warnings, considering the docstring correctly starts with the function name.

 
**What did you see instead?**

I received the following warning

```
jjr@tuur ~/test> v vet test.v
test.v:4: warning: The documentation for "pub fn read_response() ?(string, string)" seems incomplete.
```
Importantly, when changing the docstring to the following (note the "a" at the start of the second line)

```v
// read_response is a convenience function combining read_response_head &
// a read_response_body. It can be used when you know for certain the response
// won't be chunked.
pub fn read_response() ?(string, string) {}
```

the warning goes away. It seems v vet gets confused when another line of the docstring starts with the function name.

### PR DESCRIPTION
**Pull request by Larpon**
Fixes #14402 

On a side note there seem to have been updates related to the `NB` -> `Note` wording - which I've fixed also so the tests actually pass if I run `v test .` locally in the directory, I wonder why this didn't show in CI - has the `vvet` tests been disabled?

### CODE REVIEW

**Comment by spytheman** [comment]
Good spot about the test 🤔 ... May be cmd/ just is not tested by any of `v test-self` etc 🤔 ...

**Comment by Larpon** [comment]
> Good spot about the test thinking ... May be cmd/ just is not tested by any of `v test-self` etc thinking ...

It would be a shame to skip all of them since they all pass:
image

**Comment by spytheman** [comment]
> It would be a shame to skip all of them since they all pass (with this PR)

Please go ahead and edit cmd/tools/vtest-self.v, changing:
```v
    mut all_test_files := os.walk_ext(os.join_path(vroot, 'vlib'), '_test.v')
```

to:
```v
    mut all_test_files := os.walk_ext(os.join_path(vroot, 'vlib'), '_test.v')
    all_test_files << os.walk_ext(os.join_path(vroot, 'cmd'), '_test.v')
```

**Comment by Larpon** [comment]
> > It would be a shame to skip all of them since they all pass (with this PR)
> 
> Please go ahead and edit cmd/tools/vtest-self.v, changing:
> 
> ```v
>     mut all_test_files := os.walk_ext(os.join_path(vroot, 'vlib'), '_test.v')
> ```
> 
> to:
> 
> ```v
>     mut all_test_files := os.walk_ext(os.join_path(vroot, 'vlib'), '_test.v')
>     all_test_files << os.walk_ext(os.join_path(vroot, 'cmd'), '_test.v')
> ```

Awesome. Done :slightly_smiling_face:

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by Larpon** [comment]
Had to comment out another one. Output is not in same order on Windows:
(`cmd/tools/vdoc/tests/testdata/multiline/main.v`)
https://github.com/Larpon/v/runs/6441046091?check_suite_focus=true#step:9:11

**Comment by spytheman** [comment]
> Had to comment out another one. Output is not in same order on Windows: (`cmd/tools/vdoc/tests/testdata/multiline/main.v`) https://github.com/Larpon/v/runs/6441046091?check_suite_focus=true#step:9:11

that is indeed weird 🤔

**Pull request merged**
