### PR TITLE
fmt: fix inter quote of nested string in string interpolation

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix inter quote of nested string in string interpolation.

keep fmt:
- Inter quote is not same as outer quote in string interpolation.

```v
fn foo() string {
	match true {
		true {
			fields := ['aaa', 'bbb', 'ccc']
			return '[]T{{fields.join(", ")}}'
			
		}
		else {
			fields := ['aaa', 'bbb', 'ccc']
			return ('const ({fields.join(" ")})')
		}
	}
}

fn main() {
	ret := foo()
	println(ret)
}
```

### CODE REVIEW

**Comment by shove70** [comment]
That is to say, the new interpolation no longer allows nested single quote or double quote?

**Comment by medvednikov** [comment]
I  understand why you did it, to detect } at the end of the string. But I'm not a fan of this...

**Comment by medvednikov** [comment]
I wonder if there's another way.

**Comment by yuyi98** [comment]
ok, I'll try to find other way.

**Comment by spytheman** [comment]
Meanwhile, the following program works nicely, and is imho much clearer to read and understand (since `${x}` very clearly shows that there will be interpolation inside, unlike `{{x}}` which for some reason, means that the outer `{}` will be literals, but the inner ones do interpolation:
```v
fn foo() string {
	match true {
		true {
			fields := ['aaa', 'bbb', 'ccc']
			return '[]T{${fields.join(', ')}}'
		}
		else {
			fields := ['aaa', 'bbb', 'ccc']
			return 'const (${fields.join(' ')})'
		}
	}
}

fn main() {
	ret := foo()
	println(ret)
}
```

**Comment by yuyi98** [comment]
ok, I see.

**Comment by spytheman** [comment]
> I wonder if there's another way.

Yes, there is - if only we use just `${}`, all of these problems will magically disappear.

**Comment by Wajinn** [comment]
> Yes, there is - if only we use just `${}`, all of these problems will magically disappear.

Have to agree.  I always thought `${var}` was great for the purpose and distinctive.  If it would be too much trouble, think at least that one should be kept around.

**Comment by JalonSolov** [comment]
No.  We want _one_ way of doing this.  Either the new `{}` or back to `${}` (while doing away with just `$`).  We don't want 2 ways.

**Pull request closed without merging**
