### PR TITLE
fix #4066 - 'a b zz'.trim(' a') gets empty string, under shell

### LINKED ISSUE #4066: 'a b zz'.trim(' a') gets empty string, under shell
current source code (2020/03/19). 

```
>>> x := 'a b zz'
>>> println(x.trim(' a'))
b zz
>>> x.trim(' a')
>>> x.trim('a')
b zz
```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix #4066 - 'a b zz'.trim(' a') gets empty string, under shell.

```
>>> 2 + 3
5
```
Originally because there are spaces, so the results can not be displayed.

### CODE REVIEW

**Comment by yuyi98** [comment]
Is there anything wrong with this pull request?

**Comment by RiordanIX** [comment]
I don't think we want to print if the line contains '=' either.
`mut x := 5` <- shouldn't print
`x = 3` <- still shouldn't print

**Comment by medvednikov** [comment]
Yeah, lots of old conditions were removed.

The old REPL is very hacky, looking forward to the new V interpreter.

**Comment by yuyi98** [comment]
Perfecting the treatment conditions:

- Remove the ' ' and " " strings error-judgment effects.
- Restoring most of the original judgment.

**Comment by yuyi98** [comment]
@medvednikov  Now this PR restoring most of the original judgment, mainly resolves the BUG that determines whether to print the results by including spaces, and filter the ' ' and " ", I think it's good to merge.

**Pull request merged**
