### PR TITLE
parser: implement `T.name` for generic types

### PR DESCRIPTION
**Pull request by ntrel**
This follows on from the existing `typeof(expr).name` expression. Note that in future `typeof(expr)` should produce a type known at compile-time, not a string.

I think there's no reason to support this for non-generic types e.g. `int.name`.

### CODE REVIEW

**Comment by ntrel** [comment]
I'm assuming the Ubuntu test fails are unrelated.

**Comment by JalonSolov** [comment]
I disagree with "I think there's no reason to support this for non-generic types e.g. int.name."

It would be nice for orthogonality (and "only one way") if every type supported the same option.  Just to avoid "if this type, get the name this way, else do it the other way, and maybe a third way for something else".

**Comment by ntrel** [comment]
>  Just to avoid "if this type, get the name this way, else do it the other way

It doesn't depend on the actual type. Why write int.name when you can write 'int' instead?

**Comment by JalonSolov** [comment]
`println('using type $foo.name')`

**Comment by ntrel** [comment]
foo has to be a variable. I don't think we should allow `my_var.name` to be equivalent to `typeof(foo).name`. The former is not clear at all that a type name is wanted.

**Comment by JalonSolov** [comment]
From a user standpoint, especially if `T` is defined in a module or anywhere other than the user's code, it just looks like a type.

So either `typeof(T).name` just like regular types, or `<any type including generics>.name` is better for consistency.

**Comment by ntrel** [comment]
I don't understand your point. If you have a type, use `Type.name`. If you have an expression, use `typeof(expr)`. `typeof(Type)` should definitely be an error.

**Comment by ntrel** [comment]
'Consistency' is not a good argument to https://github.com/vlang/v/pull/6783#issuecomment-724054838.
This pull is consistent: generic types can get the type name. Non-generic types can't, because you already know the type name if it's non-generic.

**Pull request merged**
