### PR TITLE
tetris: use better unique colors, implement game over/pause

### PR DESCRIPTION
**Pull request by nsauzede**
Make tetris use more distinguishable colors for all blocks, and document those colors
Implement game over/pause modes to freeze the game, with key handling to restart/resume
Remove duplicate key const in glfw and add missing key_space

### CODE REVIEW

**Comment by medvednikov** [comment]
Screen Shot 2019-08-16 at 09 16 42

This can be solved by using one variable for the game's state and removing `game_paused` and `game_over`.

F5 to restart should be replaced by space.

**Comment by nsauzede** [comment]
do you mean you want the same key to pause/unpause, and restart ? (in gameover)

**Comment by medvednikov** [comment]
I mean both. Same key for pause/restart, and an enum for the game state.

**Comment by nsauzede** [comment]
understood; will push more commits to fix

**Comment by nsauzede** [comment]
comment addressed

**Comment by medvednikov** [comment]
use `g.state == .gameover` etc instead of `g.state == GameState.gameover`

I should make this a compilation error.

**Comment by nsauzede** [comment]
done.
wow, wasn't even aware of this compact enum notation :-)

**Comment by medvednikov** [comment]
Thanks

**Pull request merged**
