### PR TITLE
docs: add a `Parameter evaluation order` section

### LINKED ISSUE #15463: wrong execution order caused by Option / Result type
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 20 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i7-12700
CC version: Error: exec failed (CreateProcess) with code 2: 系統找不到指定的檔案。
 cmd: cc --version

getwd: C:\Users\chaos\projects\v_test
vmodules: C:\Users\chaos\.vmodules
vroot: C:\Users\chaos\projects\v
vexe: C:\Users\chaos\projects\v\v.exe
vexe mtime: 2022-08-18 15:50:32
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 22a79cf

Git version: git version 2.35.1.windows.2
Git vroot status: weekly.2022.33-21-g22a79cfa
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 125e21e2

**What did you do?**
`v run seq.v`

seq.v:
```v
fn err() !u8 {
	println('err')
	return 0
}

fn opt() ?u8 {
	println('opt')
	return 0
}

fn consume() u8 {
	println('consume')
	return 1
}

fn result(a u8, b u8) {
	// Do nothing
}

result(consume(), err()!)
result(consume(), opt()?)
```

**What did you expect to see?**
```
consume
err
consume
opt
```

**What did you see instead?**
```
err
consume
opt
consume
```

**Note:**
This issue is caused by V's error handling generated by c gen, c gen always lift the function with option / result type returned out of actual parameter position and handle it first.

**Possible Fix:**
Check if there is need to lift out parameter out of function calling, if there's need, also lift out other function parameters as well.

### PR DESCRIPTION
**Pull request by spytheman**
As discussed on Discord, document the current V implementation
dependent lack of guarantee of the evaluation order of function
parameters.
See: https://discord.com/channels/592103645835821068/592114487759470596/1009858931776032888

Closes #15463

### CODE REVIEW

**Review by ChAoSUnItY — APPROVED** [review]

**Review by JalonSolov — APPROVED** [review]
Look good!

**Review by vincenzopalazzo — APPROVED** [review]

**Comment by Wertzui123** [comment]
Good that this is documented now, but I think we should really change this before 1.0.

**Comment by JalonSolov** [comment]
Change what?  The documentation?  Or the evaluation order?

**Comment by Wertzui123** [comment]
It should always evaluate the arguments in the order they were passed.

**Comment by JalonSolov** [comment]
Sounds like a discussion point.

Java, for example, guarantees evaluation order from left to right.

C++ does not.
```
Bjarne Stroustrup also says it explicitly in "The C++ Programming Language" 3rd edition section 6.2.2, with some reasoning:

    Better code can be generated in the absence of restrictions on expression evaluation order
```

**Pull request merged**
