### PR TITLE
Add mongoDB client

### PR DESCRIPTION
**Pull request by esquerbatua**
As the title says, this PR adds the mongoDB client.
This is an early version of the client, needs more implementations, but you can work with it right now.

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks a lot!

V ORM is designed for traditional relational databases (sqlite, postgres, mysql).

Do we need mongodb in vlib or as an officially supported module? (`v install mongodb`)

It also has a bit shady license now, so I don't think it should be part of vlib.

Thoughts?

**Comment by JalonSolov** [comment]
Having it available is great.  A lot of people - and whole companies - use mongodb.  We use it on several different projects at my company.

However, having it as an extra module is fine.  You have to install mongodb separately anyway.

**Comment by JalonSolov** [comment]
Of course, the same argument could be used for sqlite, mysql, and postgres support.  Perhaps it's time to consider moving them to an external module as well.

**Comment by medvednikov** [comment]
sqlite, mysql, and postgres are used by ORM, but they can indeed still be moved to separate modules

**Comment by JalonSolov** [comment]
It'll be good for people who don't use ORM - they won't have the extra stuff cluttering their disk.  And those who do use it will only have the ones they use, instead of all of them.

Is this a good time to think about multi-level modules?  Perhaps have

vlang/db/mongodb
vlang/db/mysql
vlang/db/postgres
vlang/db/sqlite

**Comment by medvednikov** [comment]
Yeah that looks nice.

**Comment by medvednikov** [comment]
@esquerbatua I've created an official module http://github.com/vlang/mongo

Can you submit this code there please?

**Comment by esquerbatua** [comment]
@medvednikov of course, when I have time I push it.

My intention it's to build a mongodb client in pure V, but as first versión it's great.

**Comment by medvednikov** [comment]
Good luck with that.

But yeah, a wrapper on top of C works fine.

**Comment by JalonSolov** [comment]
Heh.  `vlang/db/mongodb` looks looks nice, but you created `vlang/mongodb` - ah, well.  Can be changed later, I suppose.

**Comment by medvednikov** [comment]
vpm only works with GitHub repos right now.

**Comment by esquerbatua** [comment]
> Good luck with that.
> 
> But yeah, a wrapper on top of C works fine.

This works faster than any other popular client of mongoDB, like java, # javascript, PHP, python, etc.

In a future, you'll see an odm? Like the orm

**Comment by JalonSolov** [comment]
There are lots and lots of multi-level github repos out there already. `vlang` is a repo with multiple subrepos under it.

**Pull request closed without merging**
