### PR TITLE
vfmt: enforce add comma in multi-line brace-less struct init fields

### PR DESCRIPTION
**Pull request by nedpals**
This PR enforces adding comma's to multi-line, brace-less struct init fields as per agreement in the [Discord server](https://discord.com/channels/592103645835821068/700746775962714232/876119009253294091).  For those who did not read, this is part of our efforts to adapt the V syntax into a [context-free grammar](https://github.com/nedpals/tree-sitter-v).

On a side-note, I have called this a "brace-less" init fields, instead of "short struct init" syntax since this is both referring to the established `Foo{x, y}` and the one this PR is tackling on which is `func(x: 1, y: 2)` which can be confusing to me (and might be to others). I might have called this `named arguments`-esque struct init but others may have a different interpretation of it. In relation to this, I have renamed the `short_syntax` variable to `in_call_expr` in order to prevent such confusion.

Another side note is that I'm not sure if `in_call_expr` field is an appropriate name to detect if the struct init is "brace-less" and within the call expression arguments.

### CODE REVIEW

**Comment by medvednikov** [comment]
No, this is not the way.

Multiline struct inits must have no commas.

**Comment by medvednikov** [comment]
It was decided to force them only with struct inits inside struct inits.

**Comment by medvednikov** [comment]
The message you linked literally says that:

> This syntax can then be valid for simple, single level structs and arrays while nested ones can be parsed without ambiguity.

**Comment by nedpals** [comment]
> The message you linked literally says that:
> > This syntax can then be valid for simple, single level structs and arrays while nested ones can be parsed without ambiguity.

Oh I thought that was the one you're agreeing for, my bad. 

> No, this is not the way.
>
> Multiline struct inits must have no commas.

Syntax-wise, they are "virtually" part of call arguments, meaning they should also abide the rules for it such as having commas. At the same time, no other node aside from call expressions that allows a special syntax for struct inits.

> It was decided to force them only with struct inits inside struct inits.

I had no problems whatsoever with other rules specified for struct init. The fields can be separated in commas or in line terminators as long as they are just like the usual, regular syntax.

**Comment by spytheman** [comment]
@medvednikov without `,` tooling for V will indeed need to become much more complex. 
For example VLS, would also allow this:
```v
f(
  some_variable_here
  some_variable_here_again
)
```, which is invalid for the normal parser (which uses context to disambiguate it).

**Comment by spytheman** [comment]
The current tree sitter grammar can be found here: https://github.com/nedpals/tree-sitter-v/blob/master/grammar.js#L712

**Pull request closed without merging**
