### PR TITLE
scanner: minor optimization

### PR DESCRIPTION
**Pull request by yuyi98**
This PR makes a minor optimization in scanner.v.

- Avoid importing `mathutil` just for simple max/min().

### CODE REVIEW

**Comment by medvednikov** [comment]
Why? The compiler uses `math` anyway, so it's imported.

**Comment by yuyi98** [comment]
```v
module mathutil

[deprecated: 'use math.min instead']
[deprecated_after: '2022-01-19']
[inline]
pub fn min<T>(a T, b T) T {
	return if a < b { a } else { b }
}

[deprecated: 'use math.max instead']
[deprecated_after: '2022-01-19']
[inline]
pub fn max<T>(a T, b T) T {
	return if a > b { a } else { b }
}

[deprecated: 'use math.abs instead']
[deprecated_after: '2022-01-19']
[inline]
pub fn abs<T>(a T) T {
	return if a > 0 { a } else { -a }
}
```

**Comment by spytheman** [comment]
> ```v
> module mathutil
> ```

That is from `vlib/math/mathutil/mathutil.v` . The scanner imports `vlib/v/mathutil/mathutil.v`

**Comment by spytheman** [comment]
> > ```v
> > module mathutil
> > ```
> 
> That is from `vlib/math/mathutil/mathutil.v` . The scanner imports `vlib/v/mathutil/mathutil.v`, which is not deprecated.

**Comment by yuyi98** [comment]
Feeling a little confused.

**Comment by medvednikov** [comment]
I think spy meant `math` which is not deprecated.

**Comment by medvednikov** [comment]
Juse replace it with `math.min` etc

**Comment by spytheman** [comment]
No, I mean that it should remain as it is, because it is importing `v.mathutil`, while the deprecated module is `math.mathutil`.

Replacing it with `math.min` etc, will make the compiler bigger without reason.

**Pull request closed without merging**
