### PR TITLE
added math constants

### PR DESCRIPTION
**Pull request by RustemB**
I think that LOG2E and LOG10E should be constants too

### CODE REVIEW

**Comment by avitkauskas** [comment]
Why `SqrtPi`, `SqrtPhi` and not `SqrtPI` and `SqrtPHI` or `Pi` and `Phi`? Would be nice to be consistent.

**Comment by medvednikov** [comment]
Consts must have PascalCase,  just like here: https://golang.org/src/math/const.go

I'll update the docs.

**Comment by ofunc** [comment]
I think constant E is necessary and other constants are unnecessary.

**Comment by RustemB** [comment]
🤯🔫

**Pull request closed without merging**
