### PR TITLE
http: set Header struct field to pub

### PR DESCRIPTION
**Pull request by sh0f**

### CODE REVIEW

**Comment by spytheman** [comment]
why?

**Comment by JalonSolov** [comment]
It doesn't need to be public - there are several routines to modify the headers.

**Comment by sh0f** [comment]
> why?

`
module main

import net.http

fn main() {
	header := get_header('https://httpbin.org/get') ?
	println(header.data['Content-Type'])
}

fn get_header(url string) ?http.Header {
	get := http.get(url) ?
	return get.header
}
test.v:7:17: error: field `net.http.Header.data` is not public
    5 | fn main() {
    6 |     header := get_header('https://httpbin.org/get') ?
    7 |     println(header.data['Content-Type'])
      |                    ~~~~
    8 | }
    9 |
`

**Comment by JalonSolov** [comment]
That just means the Header struct needs a `get_header()` method, not that the `.data` should be made public.  `vweb` has `get_header()` - that should be in the Header struct, instead, and `vweb` should use it.

**Comment by spytheman** [comment]
Thanks for the example, but I do agree with @JalonSolov - the .data and .keys fields seem to me like an internal implementation detail, and should not be exposed directly.

**Pull request closed without merging**
