### PR TITLE
cgen: uniform string output format

### PR DESCRIPTION
**Pull request by yuyi98**
This PR uniform string output format in cgen.v.

Before
```
use `abc` in struct_to_string
```

Now
```
uniform use "abc" in to_string of `map` `struct` `array`...
```

### CODE REVIEW

**Comment by medvednikov** [comment]
The default character for denoting string literals is `'`, not `"`

**Comment by yuyi98** [comment]
@medvednikov  Can they all be unified to 'abc' in `map` `struct` `array` to_string format ?

**Comment by medvednikov** [comment]
yes

**Comment by yuyi98** [comment]
OK, I'll change them.

**Comment by yuyi98** [comment]
Use 'abc' uniform string format.
```v
[Man {
    name: 'Superman'
    age: 30
    interests: ['flying', 'fighting evil', 'being nice']
}, Man {
    name: 'Bilbo Baggins'
    age: 111
    interests: ['exploring', 'hiding']
}]
```

**Pull request merged**
