### PR TITLE
os: rename open_stdin to stdin

### LINKED ISSUE #9988: os: rename open_stdin() to stdin()
### Proposal
Rename `os.open_stdin()` to `os.stdin()`.

### Why
Stdin is not opened and cannot be closed. The `open_` prefix implies to the reader that a resource is being acquired that needs to be cleaned up, but that's not the case here. In other languages like Go and Rust getting a-hold of stdin involves accessing a package/module variable without open semantics, and it is confusing to see the concept of opening stdin here.

Examples of how to access stdin in other languages.

Go:
```go
import "os"

os.Stdin
```

Rust:
```rust
use std::io;

io::stdin()
```

### PR DESCRIPTION
**Pull request by leighmcculloch**
### What
Rename os.open_stdin to os.stdin.

### Why

Stdin is not opened and cannot be closed. The `open_` prefix implies to the
reader that a resource is being acquired that needs to be cleaned up, but that's
not the case here. In other languages like Go and Rust getting a-hold of stdin
involves accessing a package/module variable or function without open
semantics, and it is confusing to see the concept of opening stdin here.

Examples of how to access stdin in other languages.

Go:
```go
import "os"

os.Stdin
```

Rust:
```rust
use std::io;

io::stdin()
```

Close  #9988

### CODE REVIEW

**Comment by leighmcculloch** [comment]
Note: I ran tests locally, there were a couple errors, but they look unrelated to the change and are related to my environment setup. It does not appear there are any existing tests testing the function being changed.

**Comment by spytheman** [comment]
Please add a deprecation also:
```v
[deprecated: 'use os.stdin() instead']
[deprecated_after: '2021-05-17']
pub fn open_stdin() File {
    return stdin()
}
```

**Comment by Gladear** [comment]
Instead of renaming it directly, please create a new function and deprecate the former one, like [this example](https://github.com/vlang/v/blob/master/vlib/strings/builder.v#L28).
I don't know if there is a convention for the time a function should be deprecated before removal.

**Comment by spytheman** [comment]
I think 14 days is a good grace period.

**Comment by spytheman** [comment]
Hm, we may need to add tooling to scan the repo for deprecations, although for now `rg deprecated_after` also works 🤔 .

**Pull request merged**
