### PR TITLE
Added few math functions. I know that it's not that much, but i'm planning to add more of them. 

### PR DESCRIPTION
**Pull request by ThreadedStream**

### CODE REVIEW

**Comment by JalonSolov** [comment]
Both 32-bit and 64-bit `isqrt` in V, using `union` instead of pointers: https://github.com/vlang/v/discussions/9159

**Comment by ThreadedStream** [comment]
@JalonSolov,thanks for comment. Will be more attentive next time. By the way, is glm library usable?

**Comment by JalonSolov** [comment]
I don't know about glm - never used it.  However, if you're looking for modules one place to check is the Awesome-V page: https://github.com/vlang/awesome-v

**Comment by ThreadedStream** [comment]
@JalonSolov, thank you very much.

**Pull request closed without merging**
