### PR TITLE
all: implement for rune in string

### PR DESCRIPTION
**Pull request by danieldaeschle**

### CODE REVIEW

**Comment by danieldaeschle** [comment]
I don't get why it fails. On my local PC it works.

**Comment by danieldaeschle** [comment]
@spytheman I had to cast some runes to byte to use as example ascii_str. Default .str() method on rune didn't work.

**Comment by danieldaeschle** [comment]
currently
```v
fn main() {
    for r in 'test💪🏼' {
        println(typeof(r).name)
        println(r)
    }
}
```

results in one iteration too much. I don't know why.

**Comment by Gladear** [comment]
In my opinion, `for c in string` should be deprecated, then removed, in favor of `for b in string.bytes()` and `for r in string.runes()`, making it explicit what type `b` and `r` will be
It also requires absolutely no change in the compiler (appart' from the adeprecation

**Comment by danieldaeschle** [comment]
Go works like that and alex wants it like that.

**Comment by spytheman** [comment]
I want an efficient way to iterate over the *bytes* of a string.

I do not care about the syntax, but preferably it should be short.

Imho, supporting emojies and the Klingon alphabet, while making one of the most common operations that you may want to do, for practical tasks like parsing harder and less efficient, is a bad tradeoff.

I do not care about runes at all, other people may disagree.

@medvednikov what do you think?

**Comment by spytheman** [comment]
What is the performance impact of all this, have you measured?
For example, how does it affect self compilation (which involves a lot of parsing)?

**Comment by danieldaeschle** [comment]
This PR is equivalent to `for x in 'test'.runes()` So for me it doesn't really make sense to support iterating over a string natively. An explicit `.runes()` or `.bytes()` is better imo.

**Comment by Larpon** [comment]
I *think* many, unfortunately, will expect `for c in 'test💪🏼' { ... }` to be iteration over the runes, and not the raw bytes.
Personally I'd prefer `'test💪🏼'.bytes()` and `'test💪🏼'.runes()` - because I can clearly see what type I'm iterating.

**Comment by JalonSolov** [comment]
Go is even more fun... if you iterate a string using
```go
for i := 0; i < len(str); i++ {
    println(str[i])
}
```
it prints the bytes.

If you use `range`...
```go
for pos, c := range "日本語" {
    fmt.Printf("character %c starts at byte position %d\n", c, pos)
}
```
it does runes.

I prefer V's "one way"... I'd vote for `.bytes()/.runes()` as well.

**Comment by JalonSolov** [comment]
The question now is... what to do about all the existing code that's just doing `for i in 'foo' {`?

**Comment by medvednikov** [comment]
Ok I agree let's make it explicit :)

**Comment by medvednikov** [comment]
`.bytes()/.runes()` and disallow `for x in s {`

**Comment by JalonSolov** [comment]
Alternative would be to document

`for i in s will iterate bytes, for i in s.runes() will iterate runes`

This would avoid breaking existing code, while making the new functionality available.

**Comment by danieldaeschle** [comment]
We're in alpha stage. I don't see the point of preventing breaking changes

**Pull request closed without merging**
