### PR TITLE
checker: fix for_in_index type error (fix #5214)

### LINKED ISSUE #5214: Cannot list files
**V version:** V 0.1.27 fb7ca56
**OS:** MacOS

**What did you do?**

```
import os

fn main() {
  for file in os.ls('.') {
    println(file)
  }
}
```

**What did you expect to see?**

list of files
 
**What did you see instead?**

```
==================
                                                                                                                                                                                                                                                                                                                                                                                                                      ^
/private/var/folders/qc/03n3xp8n0v3866tj26mg953r0000gn/T/v/vterm.tmp.c:11713:8: error: initializing 'array' (aka 'struct array') with an expression of incompatible type 'Option_array_string' (aka 'struct Option_array_string')
        array _t1 = os__ls(tos_lit("."));
              ^     ~~~~~~~~~~~~~~~~~~~~
68 warnings and 1 error generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix for_in_index type error (fix #5214).

- Fix for_in_index type error.
- Add test `for_in_index_optional.vv/out`.

```v
import os

fn main() {
  for file in os.ls('.') {
    println(file)
  }
}

D:\test\v\tt1>v run .
.\tt1.v:4:18: error: for in: cannot index `?[]string` 
    2 | 
    3 | fn main() {
    4 |   for file in os.ls('.') {
      |                  ~~~~~~~
    5 |     println(file)
    6 |   }
```

### CODE REVIEW

**Comment by sheerun** [comment]
You might want to fix docs.md as they mention `in .ls(...) {` in vsh section

**Comment by sheerun** [comment]
(also vsh seems to be completely not working, os is not imported by default)

**Comment by Delta456** [comment]
`.vsh` files import os module by default.

**Comment by sheerun** [comment]
Yes, ls() is not working in .vsh which is in os

**Comment by yuyi98** [comment]
```v
C:\Users\yuyi9\v>v
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.27 30e0bda
Use Ctrl-C or `exit` to exit
>>> import os
>>> a := os.ls('./') ?
>>> a
['.ctags.d', '.editorconfig', '.git', '.gitattributes', '.github', '.gitignore', '.noprefix.vrepl_temp.exe', '.noprefix.vrepl_temp.v', '0.2_roadmap.txt', 'BSDmakefile', 'CHANGELOG.md', 'cmd', 'CODE_OF_CONDUCT.md', 'CONTRIBUTING.md', 'doc', 'Dockerfile', 'Dockerfile.alpine', 'Dockerfile.cross', 'examples', 'LICENSE', 'make.bat', 'Makefile', 'README.md', 'thirdparty', 'tutorials', 'v.exe', 'v.mod', 'vc', 'vlib', 'v_old.exe']
>>>
```

**Comment by sheerun** [comment]
@yuyi98 You use `os.ls`, not `ls` (v script should automatically import os package):

```
$ cat test.vsh
files := ls('.') ?
println(files)

$ v run test.vsh
test.vsh:1:10: error: unknown function: ls
    1 | files := ls('.') ?
      |          ~~~~~~~
    2 |
    3 | println(files)
```

**Pull request merged**
