### PR TITLE
all: comptime if generic T is

### PR DESCRIPTION
**Pull request by danieldaeschle**

### CODE REVIEW

**Comment by danieldaeschle** [comment]
@joe-conigliaro could you take a look as well?

**Comment by danieldaeschle** [comment]
I can get it working...

**Comment by danieldaeschle** [comment]
@spytheman fixed

**Review by spytheman — APPROVED** [review]
Good work.

**Comment by amoyyy** [comment]
@danieldaeschle Thanks for the fix , `$T is sometype` what i need at this moment, and could you take a look at the test code? It failed in my machine, I can't figure out the reason.

**Comment by danieldaeschle** [comment]
Please create an issue

**Pull request merged**
