### PR TITLE
fix the missing msg argument

### PR DESCRIPTION
**Pull request by lydiandy**
fix the missing msg argument

### CODE REVIEW

**Comment by medvednikov** [comment]
@prime31

**Comment by prime31** [comment]
Looks like mostly just moving things around. Looks fine to me though I don’t know what it has to do with “fix the missing msg”...

**Comment by lydiandy** [comment]
the sokol code for  fail_userdata_cb has two arguments,the first is msg
  void (*fail_userdata_cb)(const char*, void*);
but in V code just one, lost the msg,so I change it
and I also go through  the sokol code and V code,check all the different part

**Comment by lydiandy** [comment]
and change the event_cb from voidptr to C.sapp_event
event_cb fn(&C.sapp_event)
so it do not need to be casted in the callback function

**Pull request merged**
