### PR TITLE
Fix unsafe pointer

### PR DESCRIPTION
**Pull request by MatejMagat305**
I was compile vab with '-prod' and it was needed  to fix and it is of course warning

### CODE REVIEW

**Comment by Delta456** [comment]
The file also needs to be formated and it can be done by `v fmt -w vlib/sync/pool/pool.v`.

**Comment by MatejMagat305** [comment]
Sorry

**Comment by Delta456** [comment]
> Sorry

You can do this in the next commit.

**Comment by MatejMagat305** [comment]
I do, really sory

**Comment by Delta456** [comment]
> I do, really sory

There is no need to be sorry 😄

**Comment by spytheman** [comment]
Thank you, good find.

**Pull request merged**
