### PR TITLE
fmt: align each contiguous field of struct. not the whole.

### LINKED ISSUE #7068: vfmt: make struct formatting a bit smarter, and cleaner
Extra spaces should not be added if the longer field (or a block of fields with one of them being longer) is separated by a comment, like in gofmt:

```
type Foo struct {
	bar    int
	bazzzz int
	//
	lonlonglonglong string
}
```

Right now vfmt formats it like this:
```
struct Foo {
	bar             int
	bazzzz          int
        //
	lonlonglonglong string
}

```

Which results in longer git diffs and is less readable.

### PR DESCRIPTION
**Pull request by zakuro9715**
go fmt like struct align

Close #7068

### CODE REVIEW

**Review by serkonda7 — APPROVED** [review]
Nice work :+1:

**Comment by medvednikov** [comment]
Conflicting files
cmd/tools/vvet/vvet.v
vlib/v/gen/cgen.v

**Comment by zakuro9715** [comment]
@medvednikov fixed

**Comment by medvednikov** [comment]
Sorry, due to the nature of your fmt PR, there are conflicts after each commit.

Can you fix again please, and I'll merge this asap, before merging anything else.

**Comment by zakuro9715** [comment]
@medvednikov No problem. This kind of conflict can be easily resolved by just reset last commit and run 'v fmt'. It's fixed

**Pull request merged**
