### PR TITLE
cgen: fix missing sync auto import when using SelectExpr

### LINKED ISSUE #9867: select timeout does not compile
OS: linux
V full version: V 0.2.2 0da827f.7f5c3cc

**What did you do?**
`v -g -o vdbg cmd/v && vdbg test.v`
```v
import time

fn main () {
	select {
		> 1 * time.second {}
	}
	println('ok')
}

```

**What did you expect to see?**
```
ok
```

**What did you see instead?**
```
==================
/tmp/v/test.6753601119017554917.tmp.c:11187: error: 'Array_sync__Channel_ptr' undeclared
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

### PR DESCRIPTION
**Pull request by felipensp**
Fix #9867

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 1793f54</samp>

Add `sync` as an auto-import for the parser to support `if_match` syntax. This allows using `sync.wait` for concurrency in pattern matching.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 1793f54</samp>

*  Implement the `if_match` syntax for pattern matching in V ([link](https://github.com/vlang/v/pull/19998/files?diff=unified&w=0#diff-0185db9758da469bd38f53e5be2cfd9af3104f31dc749d51f967041be8f253b9R535),                             F0L533

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Good find.

**Comment by spytheman** [comment]
It fails to compile with msvc:
image

I suggest adding that new test in `skip_on_windows` in cmd/tools/vtest-self.v (for now).

**Comment by felipensp** [comment]
> It fails to compile with msvc: image
> 
> I suggest adding that new test in `skip_on_windows` in cmd/tools/vtest-self.v (for now).

I'll take a look on it.

**Comment by felipensp** [comment]
> It fails to compile with msvc: image
> 
> I suggest adding that new test in `skip_on_windows` in cmd/tools/vtest-self.v (for now).

I've changed the cgen to fix the C code generated.

**Comment by spytheman** [comment]
> I've changed the cgen to fix the C code generated.

Even better. Thank you.

**Pull request merged**
