### PR TITLE
test: fix const_embed_test.v error

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix const_embed_test.v error.

```v
......
OK    1172 ms [ 85/154] vlib\v\tests\const_embed_test.v
......
--------------------------------------------------------------------------------------------------------------------------------------------
   71266 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   120,     0,    34,   154
```

**Cause**
Due to file resolution and cgen order is not correct.

**Solution**
Resolving file groups is divided into `builtin_files` `user_files` and `import_files`.
Cgen order:  `builtin_files` -> `import_files`  -> `user_files`.

### CODE REVIEW

**Comment by medvednikov** [comment]
@joe-conigliaro what do you think?

**Comment by yuyi98** [comment]
```v
module main
import math

const (
	aa = math.max_f32
)

fn main() {
	println(aa)
}
```
output  00e+00
generate c code:
```v
...
f64 _const_math__max_f32; // inited later
...
f64 _const_aa; // inited later
...
void _vinit() {
	builtin_init();
	vinit_string_literals();
	...
	_const_aa = _const_math__max_f32;
        ...
	_const_math__max_f32 = 3.40282346638528859811704183484516925440e+38;
        ...
}
```
As we can see from the generated c code, `_const_aa` and `-const_math__max_f32` init order is error, so produced this result.

**Comment by spytheman** [comment]
>The solution is to change the order in which files are compiled and compile dependent files in front of them to avoid such problems.
That is true. It is better solved through topological sorting like old v did though.
Separating the files into 3 groups is not necessary.

**Comment by yuyi98** [comment]
Yes, the best way is through topological sorting of the module dependency graph.

**Pull request closed without merging**
