### PR TITLE
ci: update `vmodules` docs on every commit

### LINKED ISSUE #7183: update vlib documentation automatically
The vlib documentation has fallen behind a lot

Currently, I want to view the latest vlib documentation

The only way is to view the vlib source code, or manually generate the documentation

```bash
$ cd $(which v)
$ v doc -m -f html vlib/
```

I searched the vlang org, but I didn’t found where to store the vlib documentation.

This document should also be updated automatically.

The static files are stored in Github, and the domain name is bound by CNAME

Automatically update documents via Github Action.

### PR DESCRIPTION
**Pull request by spaceface777**
Closes #7183.

NOTE: this change requires a new `VERCEL_TOKEN` secret to be added.

I have my fork set up to deploy this already; an example workflow can be seen [here](https://github.com/spaceface777/v/runs/1565527949), and this is being deployed to https://vmodules.vercel.app. Feel free to push changes to the `master` branch on my fork to try out the new action :)

### CODE REVIEW

**Comment by danieldaeschle** [comment]
vercel :D

**Comment by spaceface777** [comment]
> vercel :D

What would you suggest instead of Vercel? Creating a new branch/repo and using github pages? Uploading the html files straight to some server? imho, Vercel is the simplest to integrate, and has always worked very well for me.

**Comment by JalonSolov** [comment]
Can "GitHub Pages" be made to work?

**Comment by spaceface777** [comment]
Yes, but (as I mentioned above) the generated html would need to be `git push`ed somewhere (a new branch / a new repo / a new folder inside this repo). As far as I know, there's no way to upload files to github pages without saving them somewhere yourself, unlike Vercel.

**Comment by spaceface777** [comment]
I don't care which hosting method is used in the end, this one just seemed like the easiest to implement.

**Comment by JalonSolov** [comment]
I'm fine with it.

**Comment by danieldaeschle** [comment]
I think currently Alex has his own server. Don't know if he want to change. But we can ask.

**Comment by nedpals** [comment]
Something similar like https://github.com/adnanh/webhook would make the auto-rebuilds in the server (afaik i think it's Lightsail-powered) possible

**Comment by spaceface777** [comment]
Yes, a webhook will also work (and afaik, updating the `vc` repo uses a similar approach), but will require manual configuration on the server where the docs are hosted currently.

I guess it's up to @medvednikov to decide which option is best; whether he prefers to host everything himself, or deploy to an external service.

**Comment by medvednikov** [comment]
I'm fine with a simple external service, it's just html.

**Comment by medvednikov** [comment]
@spaceface777 does Vercel allow using our domain? 

If not, can you please change this to github pages?

**Comment by spaceface777** [comment]
It does afaik, but requires DNS configuration.

**Comment by axetroy** [comment]
don't forget to close this #7183 when PR has been merged

**Comment by medvednikov** [comment]
modules.vlang.io now runs on Vercel

**Pull request merged**
