### PR TITLE
v: add constant folding AST transformation

### PR DESCRIPTION
**Pull request by brightly-salty**
Adds basic constant-folding to V as an AST transformation in the middle end that occurs after checking.

### CODE REVIEW

**Comment by spytheman** [comment]
> Currently a draft because there are weird bugs that appear when you bootstrap too many times, and the tests do not all pass

You can add a flag in `vlib/v/pref/pref.v` say `-constant-folding`, so that it is off by default, but on when you do `v -constant-folding file.v`, then add tests that turn it on for specific .vv files, and test the behavior (produced results and/or generated C code). 

Then gradually we can improve it, till it is ready to be on by default.

**Comment by JalonSolov** [comment]
Do you have any tests, especially ones that show the before/after states?

Timing info is always good, too.  :-)

**Comment by brightly-salty** [comment]
There should be timing info in Builder.middle_end, I can add more fine-grained timers if needed as well.
As far as tests go, I haven't investigated how vlang does tests yet, but I can add them too if that is wanted. They probably would have to test the actual AST as this behavior already exists for comptime const eval for the generated C.

**Comment by spytheman** [comment]
For such a feature, I think using the `vlib/v/gen/c/coutput_test.v` will be best for now:
1) create a small program in `vlib/v/gen/c/testdata/` in a .vv file , that does say:
```v
fn main() {
    zzz := 123 + 456
    println(zzz)
}
```
Currently on master, that generates: `int zzz = 123 + 456;` for the addition, so:

2) (optionally) add a corresponding .out file, named like the .vv file, that will contain the output of that program, so that we can test that it still works.

3) add a corresponding .c.must_have file, named like the .vv file, that will have the line:
`int zzz = 123 + 456;`

4) run `vlib/v/gen/c/coutput_test.v`, it should pass.

**Comment by spytheman** [comment]
Since that option is off by default, we need a way to enable it, I think the easiest will be to:
5) modify vlib/v/gen/c/coutput_test.v by copy/pasting/refactoring the `test_c_must_have_files` function inside, to say
`test_constant_folding_c_must_have_files`, and modifying the pattern to be `.c-constant-fodling.must_have`, so that it is different than the normal pattern.
then
6) add a `addition.c-constant-fodling.must_have` file (if your program was `addition.vv` initially), with the line:
`int zzz = 579;`

7) do again `v vlib/v/gen/c/coutput_test.v` - it should pass again, but this time it should also execute your pattern, by recompiling addition.vv with -constant-folding , so that your code is active.

**Comment by JalonSolov** [comment]
`folding`, not `fodling`.  :-)

And just remove the option again, since it works now, so you don't have to worry about how to enable it for the tests.

**Comment by spytheman** [comment]
ops, my bad - I will edit it

**Comment by JalonSolov** [comment]
Hmm... I don't think that test actually tests your code.  I works fine in V now.

I think you'll need to do what @spytheman was saying, and compare the C output.

Current V does
```
int zzz = 123 + 456;
```
while your changes should make that
```
int zzz = 579;
```
and that's what needs to be tested.

**Comment by brightly-salty** [comment]
I thought I did that, in `addition.c-must-have`?

**Comment by JalonSolov** [comment]
Doh!  Never mind.  I missed that one... sorry.

**Pull request merged**
