### PR TITLE
docs: goto

### PR DESCRIPTION
**Pull request by EPonyA**
I added a `goto` section under Advanced Topics.

### CODE REVIEW

**Comment by EPonyA** [comment]
I will draft this briefly, because I am unsure of the best way to make this example compliant (i.e., a self-contained V program). The example I envisioned is very nebulous, and writing an example which is both realistic and terse may require a fundamentally different approach.

I'll think on this some more.

**Comment by spytheman** [comment]
I think the minimal program demonstrating that, is this one:
```v
my_label:
    goto my_label
```

Of course, that program is useless, but that is actually a good thing imho.
The explanation in the docs is enough for people that really do want to use goto. 
Its usage should not be encouraged for regular code.

**Comment by medvednikov** [comment]
Yeah can we move this to "advanced" since it's only for low level stuff and make it clear it should be the last resort?

**Comment by EPonyA** [comment]
It looks like it is at the bottom of Advanced Topics, if I'm not mistaken.

**Pull request merged**
