### PR TITLE
cgen: string interpolation field width support for large integers and utf8 string

### PR DESCRIPTION
**Pull request by UweKrueger**
Several problems are mitigated by this PR:
- field widths are now supported for i64 and u64 in the form '${x:20d}' or '0x${y:08x}'
- the type specifier is optional, e.g. '${x:15}' - there are still some problems with that...
- in the C part memory is allocated with exponential growth. Expensive dummy calls to snprintf are no more necessary which improves performance significantly. 
- a field width for strings like '${20s}' now refers to the number of UTF-8 characters not the string length
- expressions are now evaluated only once
In order to archive the last two points the format parameters have to be adjusted at run time. Since C does not allow modifying a va_list in any portable way, the _STR() function had to be supplemented with a further function _STR_PRINT_ARG() that evaluates a single object and is responsible for the memory management.

### CODE REVIEW

**Comment by medvednikov** [comment]
Thanks!

```
FAIL  [ 69/166]   336.670 ms vlib/builtin/string_test.v
cgen error: illegal format specifier x for type int
```

**Comment by UweKrueger** [comment]
I've allowed hexadecimal conversion for signed types, however this is questionable as 'man 3 printf' states that 'x' is for unsigned.
There are still some problems when interpolating structs and arrays - I'm working on that...

**Comment by medvednikov** [comment]
Thanks for updating the docs, wanted to do that for ages.

**Comment by penguindark** [comment]
@UweKrueger great job!
Have you seen the strconv format functions?
May be we can avoid to call C.sprintf?

**Comment by UweKrueger** [comment]
@penguindark: I've thought about the strconv.format functions. However for the cgen-Backend this would mean that a lot of additional code (the C translations of those functions) had to be included in the output C file. Since glibc/musl/... has to be linked to the resulting binary anyway, including the C.printf() functions, this would be somewhat duplicated code in this case.
For other output modules (x64, ...) things would be different, of cause.

**Comment by penguindark** [comment]
ok, tnx for the reply :)

**Pull request merged**
