### PR TITLE
db, json, time, term: change optional to result

### PR DESCRIPTION
**Pull request by yuyi98**
This PR change optional to result in db, json, time, term.

Remaining projects to be checked for compilation with this PR:
- [x] Build V Language Server (VLS) - compiles cleanly, errors in the tests, fixed in https://github.com/vlang/vls/pull/402
- [x] Build V Coreutils - compiles cleanly
- [x] Build VAB - compiles cleanly, there is a local test failure, that is unrelated, and will probably pass on the CI
- [x] Build Gitly - compiles cleanly
- [x] Build libsodium
- [x] Build VEX - warnings in the examples - https://github.com/nedpals/vex/pull/59
- [x] Build go2v - compiles cleanly
- [x] Build vlang/pdf - compiles cleanly
- [x] Install UI through VPM - all examples compile cleanly on Linux, except `~/.vmodules/ui/examples/child_window.v`, because of unrelated compiler bug (it needs -no-parallel as a workaround) 
- [x] Build VSL - compiles cleanly
- [x] Build VTL - compiles cleanly

### CODE REVIEW

**Comment by yuyi98** [comment]
@spytheman  Could you merge this first, then we can fix vls and other libraries?

**Comment by spytheman** [comment]
> @spytheman Could you merge this first, then we can fix vls and other libraries?

I will check first what will be the needed changes, and prepare PRs, so that they could be applied right away.

**Comment by yuyi98** [comment]
Ok, Thanks !!!

**Comment by spytheman** [comment]
ok, it seems that everything should work more or less after this, there were just 2 PRs to be made, one to VEX and one to VLS.

**Pull request merged**
