### PR TITLE
fix to csv reader

### PR DESCRIPTION
**Pull request by my-ijet**

### CODE REVIEW

**Comment by yuyi98** [comment]
Please describe what this PR is going to fix.

**Comment by JalonSolov** [comment]
Hmm... looks like there is a bug in the current code that incorrectly starts checking for the next field at the character BEFORE the delimiter, instead of the character AFTER.

So if you have

foo,bar

The current code will find 'foo' correctly, then shorten the line to 'o,bar' to keep looking.

This PR fixes it so the pointer is moved to the next character AFTER the ',' which will shorten the line to 'bar', which is the correct action.

**Comment by my-ijet** [comment]
this pr fixing quoted fields
but there is bug with line endings. 
foo,bar -> foo,ba

**Comment by spytheman** [comment]
This PR really needs tests cases, so:
a) it would be obvious what it fixes (for me, it is not right now, so thanks for the explanation!)
b) future regressions due to other bugfixes/enhancements would be prevented.

**Pull request closed without merging**
