### PR TITLE
array: remove redundant index method in array.v

### PR DESCRIPTION
**Pull request by yuyi98**
This PR just remove redundant index method in array.v.

### CODE REVIEW

**Comment by spytheman** [comment]
That will also remove the method from the documentation.
I think we should leave at least one copy 🤔, or we need a way to `inject` such auto generated methods into the documentation.
```
1[08:08:04]delian@nemesis: /v/cleanv $ git co master
Already on 'master'
Your branch is up to date with 'origin/master'.
0[08:08:25]delian@nemesis: /v/cleanv $ ./v doc builtin |grep index > indexes
0[08:08:30]delian@nemesis: /v/cleanv $ hub pr checkout 7523
Switched to branch 'rm_redundant_index'
0[08:08:34]delian@nemesis: /v/cleanv $ ./v doc builtin |grep index > indexes_cleaned
0[08:08:38]delian@nemesis: /v/cleanv $ colordiff indexes indexes_cleaned 
1,5d0
< fn (a []byte) index(v byte) int
< fn (a []char) index(v char) int
< fn (a []int) index(v int) int
< fn (a []rune) index(v rune) int
< fn (a []string) index(v string) int
1[08:08:47]delian@nemesis: /v/cleanv $
```
@medvednikov what do you think?

**Comment by yuyi98** [comment]
It is recommended to use a common expression for this type of interface.
`fn (a []T) index(v T) int`
`fn (a []T) prepend(v T)`
`fn (a []T) insert(i int, v T)`
`fn (a []T) contains(v T) bool`

**Comment by Delta456** [comment]
Just like go yeah

**Comment by spytheman** [comment]
I agree with that. Currently though `v doc` or vsl will not produce anything.
=> For the user, these methods may as well not exist, if he does not know about them already.

**Comment by spytheman** [comment]
I will make a discussion topic for that, commenting further under this PR may not be appropriate - the problem is not with it directly, but more general.

**Comment by yuyi98** [comment]
I think that we can define attr just like [auto_gen_function] to mark these auto generated functions, so vdoc can parse them.

[auto_gen_function]
pub fn (a []T) insert(i int, v T)

[auto_gen_function]
pub fn (a []T) index(v T) int

**Comment by yuyi98** [comment]
keep only one method `fn (a []string) index(v string) int`, and this is more widely used.

**Pull request merged**
