### PR TITLE
[WIP] Add support for mkirchner/gc

### PR DESCRIPTION
**Pull request by IsaiahPatton**
**Work-in-progress** inital support for [mkirchner/gc](https://github.com/mkirchner/gc/), a tiny garbage collection, as an alternative to boehm-gc.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Any idea of performance difference?

**Comment by IsaiahPatton** [comment]
> Any idea of performance difference?

Currently the performance is not good. <8 FPS with UI.

**Comment by JalonSolov** [comment]
Ouch.

**Comment by ylluminate** [comment]
So are you thinking you're going to be able to make some improvements @IsaiahPatton or is this effort kind of a lost cause given the suboptimal results thus far?

**Pull request closed without merging**
