### PR TITLE
vlib: add get_level to log module

### PR DESCRIPTION
**Pull request by trollkarlen**
Signed-off-by: Robert Marklund <robbelibobban@gmail.com>

### CODE REVIEW

**Comment by medvednikov** [comment]
V is not Java, such getters are considered an anti pattern.

This can be achieved by using fields' access modifiers (`pub/mut/pub mut`)

**Comment by trollkarlen** [comment]
Then we don't need the dual set functions also?

//T

**Comment by trollkarlen** [comment]
If i make it(move) pub mut then it can be changed outside of(one set function) set_level.
This way you can make trouble for your self in the future if the loggging framework needs to be informed when the level change.

**Comment by medvednikov** [comment]
Yeah, that's why I only mentioned getters.

Actually there's a bug in V's access modifiers. Or rather an unimplemented feature because we don't know how it should look like. `pub mut` fields aren't supposed to be modifiable outside the module. Only "global" fields, but there are no global fields yet :)

**Comment by medvednikov** [comment]
So let's keep it for now.

**Pull request merged**
