### PR TITLE
builtin+strconv: conditionally append ".0" to floats to ensure clarity

### LINKED ISSUE #5263: floats without fractional parts are printed like integers in REPL
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
In REPL run
```V
    100.
```
```V
    100.0
```
```V
    1e2
```

**What did you expect to see?**
all print 100.0 
 
**What did you see instead?**
all print 100

### PR DESCRIPTION
**Pull request by hungrybluedev**
Currently, floats with no digits (or zeros) after the decimal point are output in the same way as integers. This makes the output ambiguious. Moving forward, this will ensure that float outputs can always be identified at a glance without having to check the source.

This will fix #5263.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Hmm... @Larpon are the burntsushi tests for toml dependent on seeing `0` instead of `0.0` for floats?

I suppose this could be an allowable exception... 0 is always 0 whether it has `.0` after it or not...

**Comment by Larpon** [comment]
For the failing test I believe we can either add a modifier around here: <https://github.com/vlang/v/blob/6e46933c554743c4d2d90b23561b611e9b5fd8f2/vlib/toml/tests/burntsushi.toml-test_test.v#L245> or, IIRC, add a case for floats here: <https://github.com/vlang/v/blob/6e46933c554743c4d2d90b23561b611e9b5fd8f2/vlib/toml/any.v#L22> I can't remember right now why we shoehorn some of the results, but I think it's because of the intermediate JSON format we have to go through in order to reuse all their test data

**Comment by penguindark** [comment]
Just for the record: IIRC, the choice of show `0` instead of `.0` or `0.0` was made in 2019 in order to maintain C compatibility.
I've no objection if this behaviour change.

**Comment by Larpon** [comment]
Fixed

**Comment by spytheman** [comment]
> I'd like to not have to write `x:=0.0` instead of `x := 0` if x is a float,

Do not worry. This PR only changes the default output, not what V accepts as input in the source.

**Review by Larpon — APPROVED** [review]

**Review by spytheman — APPROVED** [review]

**Comment by penguindark** [comment]
> > I'd like to not have to write `x:=0.0` instead of `x := 0` if x is a float,
> 
> Do not worry. This PR only changes the default output, not what V accepts as input in the source.

Then perfect for me :)

**Pull request merged**
