### PR TITLE
tests: fix num_lit_call_method_test.v

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix num_lit_call_method_test.v.

- Fix num_lit_call_method_test.v.
- Remove `num_lit_call_method_test.v` from skip list.

```v
OK   [135/175]  1272.267 ms vlib\v\tests\num_lit_call_method_test.v
------------------------------------------------------------------------------------------
               158622.001 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   172,     0,     3,   175
```

Solution
Because `prefix` has a lower precedence than `call`, so `x2 := -0xffff.str()` => `x2 := -(0xffff.str())`, that's not what we need. 
We can add parenthesis like `x2 := (-0xffff).str()` to resolve it. 
If this is not in line with the habit, we must change scanner.v to scan negative, I don't know if this is the right way.

### CODE REVIEW

**Comment by spytheman** [comment]
It is a good find @yuyi98 and the fixed test may stay that way, but I think we should either detect it in the checker too and produce a nice error message with a hint of what to do, or make it work.
Currently that test fails with a C compilation error.

**Comment by spytheman** [comment]
The old compiler produced: `string x2= int_str ( - 0xffff ) ;`  for this situation.

**Comment by spytheman** [comment]
I am not sure what would be the best place to fix it in a general way.
@medvednikov what do you think?

**Comment by yuyi98** [comment]
I don't quite understand why scanner doesn't consider negative values when scanning numbers, Is there any special consideration?

**Comment by medvednikov** [comment]
yeah need to change the precedence

**Comment by yuyi98** [comment]
```v
right = p.expr(token.Precedence.call)
```
It can avoid over-parsing of call.

**Comment by SleepyRoy** [comment]
Good work! 
BTW #4482 could be closed after merging this.

**Comment by medvednikov** [comment]
This doesn't fix it yet :)

**Comment by medvednikov** [comment]
Oh, I missed the comment. @yuyi98 can you push it please?

**Comment by yuyi98** [comment]
> can you push it please?
@medvednikov   Sorry, I don't understand, How can I push it?

**Pull request merged**
