### PR TITLE
vlib: Add FSM plot

### PR DESCRIPTION
**Pull request by mihaigalos**
This PR contributes a way to automatically plot the `fsm` states and their transitions using `dot`.

### CODE REVIEW

**Comment by mihaigalos** [comment]
Need advice on how to install `dot` / `xdot` on supported all supported OSes.

**Comment by JalonSolov** [comment]
Need to format `fsm_graph.v`

**Comment by mihaigalos** [comment]
> Need to format `fsm_graph.v`

Seems `master` is broken:
```bash
» v fmt -w .

failed    cmd: '/home/mihai/git/v/v' -skip-unused '/home/mihai/git/v/cmd/tools/vfmt.v'
failed   code: 1
/home/mihai/git/v/vlib/v/ast/table.v:1493:31: error: field `elem_type` does not exist or have the same type in all sumtype variants
 1491 |             mut dims := 1
 1492 |             for mut elem_sym.info is Array {
 1493 |                 elem_type = elem_sym.info.elem_type
      |                                           ~~~~~~~~~
 1494 |                 elem_sym = t.sym(elem_type)
 1495 |                 dims++
 ```

**Comment by spytheman** [comment]
`vlib/datatypes/fsm/fsm_graph.v` is a program, that processes another program's source code, in order to extract lines matching `add_transition`.

It is not part of the `fsm` module itself, but a tool, to help visualizing/working with programs that use the `fsm` module. fsm_graph.v is also its own program (having main, having flags etc), not a library.

For all of the above reasons, I think it should not be inside the `vlib/datatypes/fsm/` folder directly, since .v files there, are compiled as parts of the `fsm` module.

A suitable location may be: `vlib/datatypes/fsm/tools/` or `vlib/datatypes/fsm/examples/`.

**Comment by spytheman** [comment]
> > Need to format `fsm_graph.v`
> 
> Seems `master` (`a83493c34545ecfcc2fc077ec497213c0aa4fa31`) is broken:
> 

It works for me:
image

**Comment by mihaigalos** [comment]
> > > Need to format `fsm_graph.v`
> > 
> > 
> > Seems `master` (`a83493c34545ecfcc2fc077ec497213c0aa4fa31`) is broken:
> 
> It works for me.

Ok. Seems just pulling is not sufficient since I need to rebuild the `v` binary.

**Pull request merged**
